### PR TITLE
[doc] Moving Configuration.md from swss to sonic-yang-models folder

### PR DESCRIPTION
**Pull request by dgsudharsan**
Signed-off-by: Sudharsan Dhamal Gopalarathnam <sudharsand@nvidia.com>

#### Why I did it
Moved Configuration.md from swss to yang folder. The configuration schema should be present along with yang models and when users add yang model they could update configuration document as well.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Could you link the PR on sonic-swss which remove the old md file?

**Review by praveen-li — COMMENTED** [review]
-- The diff is full file, due to move in Repos I guess? 
-- There will be another PR which deletes the file in sonic-swss repo ?

**Comment by dgsudharsan** [comment]
> -- The diff is full file, due to move in Repos I guess? -- There will be another PR which deletes the file in sonic-swss repo ?

Correct.

**Comment by dgsudharsan** [comment]
> Could you add the link to the PR on sonic-swss which removes the old md file?

https://github.com/Azure/sonic-swss/pull/2177

**Review by qiluo-msft — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Pull request merged**
