### PR TITLE
[201811][dhcp-relay]: Launch DHCP Relay On L3 Vlan Only

### PR DESCRIPTION
**Pull request by tahmed-dev**
Recent changes brought l2 vlan concept which does not have DHCP
clients behind them and so DHCP relay is not required. Also,
dhcpmon fails to launch on those vlans as their interfaces
lack IP addresses. This PR backposts #6527 that limits launch
of both DHCP relay and dhcpmon to L3 vlans only.

original-pr: https://github.com/Azure/sonic-buildimage/pull/6527
singed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Comment by jleveque** [comment]
@tahmed-dev: Can you confirm that this change is already in all upstream branches?

**Comment by tahmed-dev** [comment]
> @tahmed-dev: Can you confirm that this change is already in all upstream branches? I don't see any mention of it in your description.

@jleveque: it is included in 20201231 and 20191130 branches.

**Comment by jleveque** [comment]
> > @tahmed-dev: Can you confirm that this change is already in all upstream branches? I don't see any mention of it in your description.
> 
> @jleveque: it is included in 20201231 and 20191130 branches.

Great. And master, I assume?

**Comment by tahmed-dev** [comment]
> > > @tahmed-dev: Can you confirm that this change is already in all upstream branches? I don't see any mention of it in your description.
> > 
> > 
> > @jleveque: it is included in 20201231 and 20191130 branches.
> 
> Great. And master, I assume?

Yes, it is in master.

**Review by jleveque — APPROVED** [review]

**Review by yxieca — APPROVED** [review]

**Review by jleveque — APPROVED** [review]

**Pull request merged**
