### PR TITLE
[platform]: fixed syseeprom access for BFN platform

### PR DESCRIPTION
**Pull request by akokhan**
Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>

**- What I did**
Added eeprom.py for x86_64-accton_wedge100bf_32x-r0 and x86_64-accton_wedge100bf_65x-r0 devices.

**- How to verify it**
show version
sudo decode-syseeprom
redis-dump -d 6 | python -mjson.tool | grep EEPROM

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by akokhan** [comment]
@lguohan , @jleveque , please review

**Comment by lguohan** [comment]
retest vsimage please

**Comment by msosyak** [comment]
retest vs please

**Comment by akokhan** [comment]
retest vsimage please

**Comment by akokhan** [comment]
Please merge

**Pull request merged**
