### PR TITLE
[device][accton]: Update for AS5835-54T

### PR DESCRIPTION
**Pull request by pollyhsu2git**
* Update Accton-AS5835-54T to adapt xxx.config.bcm based on the latest update of Device-Specific File Directory Structure.
* Update Accton-AS5835-54T upon the port link / led test / PING out / SCP upon self-bringing up the new SAI version, 3.5.2.3.

Signed-off-by: polly_hsu@edge-core.com

**- What I did**
Update Accton-AS5835-54T upon the port link / led test / PING out / SCP upon self-bringing up the new SAI version, 3.5.2.3

**- How I did it**
1. Update Accton-AS5835-54T to adapt xxx.config.bcm based on the latest update of Device-Specific File Directory Structure the SONiC Porting Guide.
2. Update Accton-AS5835-54T against the latest update of the SONiC Porting Guide (https://github.com/Azure/SONiC/wiki/Porting-Guide).

**- How to verify it**
1. Target-verified the port mapping of 48x10G+6x100G as expected.
2. Target-verified the port link of 48x10G+6x100G as expected.
3. Target-verified the port led of 48x10G+6x100G as expected, however, we off-loaded the MV2 LED BINs to our self-brought up SAI libraries due to SONiC NOT supporting them currently.
3. We off-loaded the MV2 SDK config setting to our self-brought up SAI libraries, and will update it upon more verification check.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
what is MV2 SDK?

**Comment by pollyhsu2git** [comment]
@lguohan 
The Broadcom SAI -3.5.2.3 / SDK-6.5.14.

**Comment by pollyhsu2git** [comment]
@lguohan 
Our customer is waiting for this update~
Any issue for this merge blocked?

**Comment by lguohan** [comment]
i cannot find mv2 file, since mv2 sdk is in your private branch, i suggest you keep td3 and keep all mv2 work in your private branch.

**Comment by Lewis-Kang** [comment]
@lguohan what do you mean by "mv2" file? It's the same BRCM SAI pacakge. We modify platform dependent code to make it work for AS5835 which is using BRCM MV2 ASIC.

**Comment by pollyhsu2git** [comment]
@lguohan 
Upon your last comment, after our internal discussion, we have a question we'd like to clarify with you:
* Will this PR be merged if we provide mv2-as5835t-48x10G+6x100G.config.bcm? Or?

**Pull request merged**
