### PR TITLE
[submodule] Update sonic-utilities

### PR DESCRIPTION
**Pull request by deran1980**
ac47e5   Skip route check for tun0 interfaces (#1399)
ba68aed do not parse stderr to get correct routing stack (#1398)
aa7b90e [storyteller] allow storyteller to work on downloaded logs (#1388)
a6ae218 [vrf]: Fix freezing during interface binding (#1325)
2e1f354 Use SonicV2Connector/ConfigDBConnector/SonicDBConfig from swsscommon instread of swsssdk (#1392)
28d358f [show] Run fwutil with sudo (#1364)
a50b7a2 [ecnconfig] Allow ecn unit test to run without sudo (#1390)
8a1109e [sonic-installer] Add information to syslog (#1369)
c7c01e4 [show] fix "show interfaces breakout" command (#1198)
7a8024a Prevent user from adding more then a single untagged VLAN to an interface (Azure#1382)
41e62c6 [pcieutil] Add 'pcie-aer' sub-command to display AER stats (Azure#1169)
47f412b Improve robustness of consutil plugin loading (Azure#1353)
64aa1b8 [show] Fix warnings, related to gearbox, while show commands execution (Azure#1343)
ff226d0 Prevent configuring IP interface on a port which is a member of VLAN (Azure#1374)
f1522b9 [config_mgmt.py]: Set leaf-list to empty list while port breakout. (Azure#1268)
99c05d5 add vlan_intf_object only if there are ipv4 or ipv6 mappings (Azure#1377)
b082684 [ecn] Add tests for ecnconfig command (Azure#1372)
23e0920 [sfpshow] Enhance QSFP-DD DOM information (Azure#1207)
f4edba1 [ecnconfig] handle backend port names when extracting port I/F ID from the port name (Azure#1361)

### CODE REVIEW

**Review by liat-grozovik — DISMISSED** [review]

**Comment by lguohan** [comment]
unit test failed.

**Comment by neethajohn** [comment]
Fix for unit test failure is checked in. Please include Azure/sonic-utilities#1390

**Comment by daall** [comment]
https://github.com/Azure/sonic-buildimage/pull/6635 includes these commits for 202012, dropping label

**Comment by liat-grozovik** [comment]
@daall not sure i understand. have you taken all of them to 202012 regardless of this PR?
@deran1980 can you please add the fix by @neethajohn  and update it so we can have all these fixes in master as well?

**Comment by daall** [comment]
> @daall not sure i understand. have you taken all of them to 202012 regardless of this PR?
> @deran1980 can you please add the fix by @neethajohn and update it so we can have all these fixes in master as well?

We branched sonic-utilities off at the same point as this PR + included the fix Neetha mentioned, so all the commits that were included in this submodule update will also be present in the 202012 branch

**Comment by liat-grozovik** [comment]
Note: There are more fixes for sonic-utilities for DPB. so closing this one and new one will be provided by DPB owners.

**Comment by zhenggen-xu** [comment]
> Note: There are more fixes for sonic-utilities for DPB. so closing this one and new one will be provided by DPB owners.

I don't think we need close this one,  we either merge this one and then raise the another one for DPB fix, or just update this one directly with the new commit id from sonic-utilities master.

For sonic-buildimage 202012 branch, we have to backport/cherry-pick https://github.com/Azure/sonic-utilities/pull/1198 to sonic-utilities repo 202012 branch, then update the submodule for sonic-buildimage 202012 too.

**Review by liat-grozovik — APPROVED** [review]

**Comment by lguohan** [comment]
obsoleted by #6681

**Pull request closed without merging**
