### PR TITLE
td2/td3 change cpu cos num to 10

### PR DESCRIPTION
**Pull request by prsunny**
#### Why I did it
bcm_num_cos=10 forces SDK default to map internal priority 0-7 to COS 0. It is now consistent with other SKUs. 

#### How I did it
Modified config.bcm

#### How to verify it
Verified the Cosq for trapped packets

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [x] 202106

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Review by gechiang — COMMENTED** [review]
Should we consider S6000 HW SKUs as well?  They are also TD2 based I think...

**Comment by prsunny** [comment]
> Should we consider S6000 HW SKUs as well? They are also TD2 based I think...

@gechiang, its already set as 10 for S6000.

**Comment by gechiang** [comment]
> > Should we consider S6000 HW SKUs as well? They are also TD2 based I think...
> 
> @gechiang, its already set as 10 for S6000.

That's great!  Thanks!

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Pull request merged**
