### PR TITLE
Remove python-netsnmp deb package from makefile

### PR DESCRIPTION
**Pull request by qiluo-msft**
**- Why I did it**
No one is using it in buildimage repo

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by qiluo-msft** [comment]
Retest broadcom please

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Review by jleveque — APPROVED** [review]

**Pull request merged**
