### PR TITLE
BIOS upgrade support with API2.0 for DellEMC S6100

### PR DESCRIPTION
**Pull request by paavaanan**
**- What I did**
- Added BIOS upgrade support in install_component_firmware()

**- How I did it**
- sonic_installer trigger  install_component_firmware(), with component name as BIOS and squashfs mount point in image_path.
- With the help of image_path BIOS image is identified from the mount location and approprite upgrade/downgrade/no-change decision is taken.
- get_firmware_version is implemented  to do version check between the BIOS image and current installed version.
- "flashrom" binary is generated at the time of build-creation
- User do have an option to continue/stop BIOS upgrade. 
- If new BIOS is available for upgrade, prompt user a confirmation message [yes/no] for upgrade. 
- If "yes" BIOS is upgraded with the help of flashrom utility.

**- How to verify it**
- sonic_installer install sonic-broadcom.bin

**- Description for the changelog**

[BIOS-Infra-logs.txt](https://github.com/Azure/sonic-buildimage/files/3355347/BIOS-Infra-logs.txt)

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by paavaanan** [comment]
This PR is associated with https://github.com/Azure/sonic-utilities/pull/570

**Comment by jleveque** [comment]
Please fix conflicts.

**Comment by jleveque** [comment]
Looks good to me. Adding @lguohan for a secondary review.

**Comment by jleveque** [comment]
@paavaanan: Please fix new conflicts.

**Pull request merged**
