### PR TITLE
[201911] [Mellanox] Read PSU fan max/min speed per PSU

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Backport https://github.com/Azure/sonic-buildimage/pull/8563 to 201911

#### Why I did it
New PSU could install different type of fan, so fan max/min speed should be read per PSU

#### How I did it
The existing implementation read PSU max/min fan speed from a common file, change it to read from per PSU file

#### How to verify it

Manual test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
slave.mk:561: recipe for target 'target/docker-sonic-mgmt-framework.gz' failed

**Pull request merged**
