### PR TITLE
[sonic-swss] submodule update

### PR DESCRIPTION
**Pull request by Sabareesh-Kumar-Anandan**
[buffermgmt] more build error fixes when compiling for armhf (32-bit) (#1559)
Sflow fix to avoid NULL in field. (#1531)
[fgnhgorch] Fg Nhg link handling (#1537)
[dpb]: make sure port is in admin down state before remove port. (#1513)
[FPMSYNCD/FDBSYNCD] EVPN Type-5 route removing prefix-len for host route
and removing junk character present in the mac (#1553)
Added support for EVPN L3 VXLAN as described in the PR Azure/SONiC#437 (#1267)
[crm]: Typecast to unit64_t to avoid divide by 0 during overflow (#1550)
[vxlanmgr] Fix build error when compiling for armhf (32-bit) (#1552)
[Dynamic buffer calc]  Support dynamic buffer calculation (#1338)
[dvs] Clean-up dvs_database and dvs_common (#1541)
[VxlanMgr] changes for EVPN VXLAN (#1266)
Statistics support for Tx and Rx counters of different frame sizes (#1536)
[orchagent/phy]: Add firmware info propagation (#1540)
[vxlanorch] Use PRI instead of %l to avoid warnings in 32-bit arch (#1539)
[FDBSYNCD] Added support for EVPN as described in the PR Azure/SONiC#437 (#1276)
[everflow] Add retry mechanism for mirror sessions and policers (#1486)
Enable ACL table type  mirror_v6 for Innovium Platform (#1527)
[fgnhgorch] Change format specifier %lu to %zu for size_t (#1529)
[dvs] Fix issue where concurrent netns operations cause test setup to fail (#1535)
Add support for headroom pool watermark (#1453)
Change gAsicInstance to type string with max length limit (#1526)

Signed-off-by: Sabareesh Kumar Anandan <sanandan@marvell.com>

**- Why I did it**

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
retest vsimage please

**Comment by carl-nokia** [comment]
retest vsimage please

**Comment by carl-nokia** [comment]
retest vsimage please

**Review by lguohan — DISMISSED** [review]

**Comment by radha-danda** [comment]
retest vsimage please

**Comment by Sabareesh-Kumar-Anandan** [comment]
retest vsimage please

**Comment by Sabareesh-Kumar-Anandan** [comment]
retest mellanox please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by Sabareesh-Kumar-Anandan** [comment]
Hi @lguohan ,
During "[test_po_update](https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/8041/testReport/pc/test_po_update/test_po_update/)" test there are multiple "invalid response" errors from redis counters_db. I suspect it to be caused by https://github.com/Azure/sonic-swss/pull/1453. 
I updated swss submodule pointer to this PR#1453 and got the same test failure - https://github.com/Azure/sonic-buildimage/pull/6257

Can you please check this?  or Is this because of any test env/script issue?

**Comment by prsunny** [comment]
retest vsimage please

**Pull request closed without merging**
