### PR TITLE
DellEMC: N3248PXE Initial platform commit

### PR DESCRIPTION
**Pull request by arunlk-dell**
#### Why I did it
Added support for the device N3248PXE
#### How I did it
Implemented the support for the platform N3248PXE
[n3248pxe_unit_test_log.txt](https://github.com/Azure/sonic-buildimage/files/7038385/n3248pxe_unit_test_log.txt)

Switch Vendor: DellEMC
    * Switch SKU: N3248PXE
    * ASIC Vendor: Broadcom
    * SONiC Image: sonic-broadcom.bin
#### How to verify it
Verified the show platform commands
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by jeff-yin** [comment]
@sujinmkang @prgeor Can you review? Thanks

**Comment by jeff-yin** [comment]
@arunlk-dell are the remaining LGTM alerts false-positives?
@lguohan can someone re-trigger the pipeline checks? I don't think we have permissions. I checked a while back and they had been all passing. Not sure what happened.

**Comment by arunlk-dell** [comment]
@jeff-yin Yes, the remaining LGTM alerts are false positive and the wrong name/number of the argument alerts are due to different platform definitions.

**Comment by arunlk-dell** [comment]
@sujinmkang... All checks got passed and the remaining LGTM alerts are false positive. Can you review the changes? Thanks

**Review by sujinmkang — APPROVED** [review]

**Comment by arunlk-dell** [comment]
@sujinmkang .....
Have addressed the LGTM alerts, the wrong name/number of the argument alerts are due to different platform definitions.
And 'result of integer division may be truncated' alert can be ignored in python3
Can you merge the pull request.

**Review by sujinmkang — APPROVED** [review]

**Pull request merged**
