### PR TITLE
[centec] fix some bugs on centec tsingma bsp and v682 sonic_platform package

### PR DESCRIPTION
**Pull request by LuiSzee**
#### Why I did it
Fix some bugs on centec tsingma bsp and v682 sonic_platform package.

#### How I did it
1.  add module license for centec mars phy driver
2.  Fix i2c function ability setting for tsingma soc i2c controller
3.  Fix eeprom read error on v682 sonic_platform sfp module

#### How to verify it
Build SONiC image and verify it on centec E530-48T4X and V682-48Y8C board.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111

### CODE REVIEW

**Comment by xumia** [comment]
LGTM, @qiluo-msft , could you please help take a look?

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
