### PR TITLE
[201911] Broadcom SAI 3.7.5.2

### PR DESCRIPTION
**Pull request by judyjoseph**
**- Why I did it**

Update for new Brcm SAI 3.7.5.2.

saibcm (3.7.5.2) unstable; urgency=medium  
  * 20200816 (2799d3ef7a02fec9da2b28af4063eaac040266c9)
    3.7 GA Candidate Release
 -- ethan.lin@broadcom.com <ethan.lin@broadcom.com> Sun Aug 16 22:18:22 2020 -0400

**The following fixes are included in this version**
```
e5e06f43d50409da9ef403663b6aa61f21a6af47 (HEAD -> INT_3.7, origin/INT_3.7) Fix for CS00010914668(KB0029456/SDK-218585) and CS00010503275(KB0029315/SDK-213475)
cf4f8da29ad97f7acde85c98d8723e87a73c90c0 Solution for CS00010775359 in 3.7
0348f03c26fe68f6f612a36171a7c4267e0ce97c Patch for CS00010897814
bb99fbae4092ab073347c60f81842598d7c24480 (tag: REL_GA2_3.7.5.2) Update changelog for 3.7.5.2
2799d3ef7a02fec9da2b28af4063eaac040266c9 SAI3.7.5.2 Release Notes
7897ce000797a19dfad1e1a58b7fd8d1ae544c5c Remove fields unneeded.
a2d2fdd3fbec827f8a572acbee6238c9052097e5 Patch for CS00010817763
4d362e8f7fc73bb8d6258b1a793e2d0333b777d9 Patch for CS00010636736
557ddc686c52a0786bcefcdc514d519a30bfc7bb Solution for CS00010443542
0f122f157e07e399e199fb1088b8b7e70ca8621f Port SDK SER fix for dynamic tables (SDK-175398 / SDK-221245) to SAI 3.7
37e5c5ee37134eba04f4b58fc1d1a765cdca0ce3 Fix for CS00010790550
a57910c06c9bdbdd87960c68e5aec4fe0af0f6f4 Merge branch 'INT_3.7' of https://github.com/Broadcom-Switch-Collab/SONiC_SAI into INT_3.7
64daf8a3c8fc7d7ff365e721d74c9cd6dd38850f Fix for CS00010726597
e7f000eb86010ccc0e4aafbaae7ac19135722423 Fix for CS00010697761
44b7ab3e8e87fc8d64ca951101d67ff17be1ae5d Solution for CS00010617498.
1475c241e25c91fc8cb93d7c14cd70194bad1328 CSP10503275 request to pull KB0029314 into 3.7
```

**- How I did it**

**- How to verify it**
Verified on S6100, A7060, A7050, S6000

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [x ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
can you have changelog?

**Comment by judyjoseph** [comment]
> can you have changelog?

It is updated in the PR already "platform/broadcom/saibcm-modules/debian/changelog". Are you referring to any other changelog file ?

**Review by abdosi — CHANGES_REQUESTED** [review]
To confirm some failures with manual run

**Comment by lguohan** [comment]
yes, can you put that changelog update here?

**Comment by judyjoseph** [comment]
> yes, can you put that changelog update in the commit message?

sure will add it in commit message, updated the PR description as well.

**Comment by lguohan** [comment]
do we have detail bug fixes for SAI 3.7.5.2?

**Comment by judyjoseph** [comment]
> do we have detail bug fixes for SAI 3.7.5.2?

updated the description @lguohan , will add it while merging the PR.

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
approve for this time. I think we need better description for the pr. it is difficult to understand what those changes are.

**Comment by judyjoseph** [comment]
> approve for this time. I think we need better description for the pr. it is difficult to understand what those changes are.

Sure Guohan, since the changes were more in this release - I have left the Broadcom CS case numbers which can be tracked back. Btw I am doing some more manual validation of some failed tests, plan to finish this and merge this week.

**Comment by judyjoseph** [comment]
retest broadcom please

**Review by abdosi — APPROVED** [review]

**Pull request merged**
