### PR TITLE
[iccpd][docker] fix initial startup configuration

### PR DESCRIPTION
**Pull request by novikauanton**
#### Why I did it
The process of config generation (sonic-cfggen) fails, but the services continue to run with invalid config

#### How I did it
* add exit with error on errors in start.sh script (because supervisord relies on start.sh return code).
* fix jinja template. Jinja use common python expressions under the hood and `has_key` method was removed from dict in py3, so use check by `in` operator as it is supported by both py2 and py3.
#### How to verify it
* compile sonic with enabled iccp. 
* add mclag config to CONFIG_DB. 
    ``` 
    'MC_LAG|1' => {
        "local_ip": "10.0.0.2",
        "peer_ip": "10.0.0.3",
        "peer_link": "Ethernet8",
        "mclag_interface": "Ethernet12" 
    }
* unmaks, enable and start swss and iccpd services in sonic.
* log in into the iccpd container and check the config file `/etc/iccpd/iccpd.conf`
* expected config:
    ```
    mclag_id:1
        local_ip:10.0.0.2
        peer_ip:10.0.0.3
        peer_link:Ethernet8
        mclag_interface:Ethernet12
    system_mac:YOUR_SYSTEM_MAC

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012 (contains the same bug)
- [x] 202106 (contains the same bug)

#### Description for the changelog
Fixed initial iccpd startup configuration.

### CODE REVIEW

**Comment by akokhan** [comment]
@Praveen-Brcm, please take a look

**Review by qiluo-msft — APPROVED** [review]

**Review by jleveque — APPROVED** [review]

**Comment by novikauanton** [comment]
@qiluo-msft Could you please cherry-pick this fix to 202012 and 202106?

**Comment by novikauanton** [comment]
@lguohan could you please cherry-pick this fix to 202012 and 202106?

**Comment by novikauanton** [comment]
@qiluo-msft could you please cherry-pick it to 202106 too?

**Comment by qiluo-msft** [comment]
I am not the 202106 branch owner.

**Pull request merged**
