### PR TITLE
[DellEMC] S5232 platform updates

### PR DESCRIPTION
**Pull request by srideepDell**
FPGA driver crash fix for stale buffer in i2c transfer
LED firmware load issue fix.
10G port swapfix
psu/sfp bug fixes to report correct states/status of hw

**- What I did**
issues fixed related to 
FPGA driver crash fix for stale buffer in i2c transfer
LED firmware load issue fix
psu/sfp bug fixes to report correct states/status of hw

**- How I did it**
Code changes done in platform related areas

**- How to verify it**
Verified on S5232 platform. Logs in comments section

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by srideepDell** [comment]
Platform /BMC chip supported system logs for FAN,PSU,Temperatures, direction of the fan

root@sonic-s5232-01:~# platform_sensors.py

Onboard Temperature Sensors:
  PT_Left_temp:                     25 degrees C
  PT_Mid_temp:                      30 degrees C
  PT_Right_temp:                    20 degrees C
  Broadcom Temp:                    25 degrees C
  Inlet Airflow Temp:               19 degrees C
  CPU Temp:                         24 degrees C

Fan Trays:
  Fan Tray 1:
    Fan1 Speed:                     9120 RPM
    Fan2 Speed:                     8160 RPM
    Fan1 State:                     Normal
    Fan2 State:                     Normal
    Airflow:                        B2F
  Fan Tray 2:
    Fan1 Speed:                     9000 RPM
    Fan2 Speed:                     8160 RPM
    Fan1 State:                     Normal
    Fan2 State:                     Normal
    Airflow:                        B2F
  Fan Tray 3:
    Fan1 Speed:                     9120 RPM
    Fan2 Speed:                     8280 RPM
    Fan1 State:                     Normal
    Fan2 State:                     Normal
    Airflow:                        B2F
  Fan Tray 4:
    Fan1 Speed:                     9120 RPM
    Fan2 Speed:                     8280 RPM
    Fan1 State:                     Normal
    Fan2 State:                     Normal
    Airflow:                        B2F

PSUs:
    PSU1:                      NOT OK
    PSU2:
       FAN Normal Temperature:         29 degrees C
       FAN AirFlow Temperature:        18 degrees C
       FAN RPM:                        8160 RPM
       Input Voltage:                  207.90 Volts
       Output Voltage:                 12.40 Volts
       Input Power:                    140 Watts
       Output Power:                   120 Watts
       Input Current:                  0.64 Amps
       Output Current:                 10.50 Amps
       Airflow:                        B2F

    Total Power:                       140 Watts
root@sonic-s5232-01:~#



LED firmware load successfull

Apr  3 21:05:34.888074 sonic-s5232-01 INFO syncd#supervisord: start.sh ledinit: started
Apr  3 21:05:34.908141 sonic-s5232-01 INFO syncd#supervisord: ledinit rcload /usr/share/sonic/platform/led_proc_init.soc#015#015
Apr  3 21:05:34.916043 sonic-s5232-01 INFO syncd#supervisord: ledinit Loading M0 Firmware located at /usr/share/sonic/hwsku/custom_led.bin#015
Apr  3 21:05:34.945769 sonic-s5232-01 INFO syncd#supervisord: ledinit drivshell>
Apr  3 21:05:34.945922 sonic-s5232-01 INFO syncd#supervisord: ledinit

**Comment by srideepDell** [comment]
please do help in adding this commit to 201911 branch.

**Comment by srideepDell** [comment]
retest vsimage please

**Comment by srideepDell** [comment]
retest vsimage please

**Comment by srideepDell** [comment]
retest vsimage please

**Comment by srideepDell** [comment]
Retest vsimage please

**Comment by srideepDell** [comment]
Retest vsimage please

**Comment by jeff-yin** [comment]
@lguohan can you tag this for `201911` branch?

**Pull request merged**
