### PR TITLE
[Accton]as7512-32x: change console speed to be 115200 as BIOS's & ONI…

### PR DESCRIPTION
**Pull request by roylee123**
Change console speed to be 115200.

### CODE REVIEW

**Comment by lguohan** [comment]
does the device support baud rate 9600? What is the reason to change the rate to 115200?

**Comment by roylee123** [comment]
Yes, the uart port supports rate 9600. 
The reason to change it to 115200 is because BIOS run at this speed. The factory default ONIE is run at 115200 as well.

**Comment by lguohan** [comment]
I think maybe we should add an option to specify the baud rate for sonic, or check if it is possible to use the same baudrate as the onie image in long run.

**Comment by stcheng** [comment]
https://github.com/Azure/sonic-buildimage/issues/542 related issue opened

**Pull request merged**
