### PR TITLE
[Juniper QFX5210] Fix Python errors

### PR DESCRIPTION
**Pull request by jleveque**
- `__init__` method cannot return a value
- Also remove unnecessary 'pass' statement

### CODE REVIEW

**Comment by lguohan** [comment]
retest broadcom please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vs please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by abdosi** [comment]
@jleveque seeing conflict in cherry-pick for 201911. Please Create PR

**Comment by jleveque** [comment]
@abdosi: Thanks for the heads-up. Done: https://github.com/Azure/sonic-buildimage/pull/4413

**Pull request merged**
