### PR TITLE
[device/arista]: Update 

### PR DESCRIPTION
**Pull request by Staphylo**
**- What I did**

 - Update arista-drivers submodules for broadcom and barefoot platforms
 - Reduce the verbosity of boot0 by default (can still be re-enabled)
 - Add support for hooks in boot0
 - Fix timestamp extraction bug in the boot0
 - Fix flash detection for Arista platforms in the initramfs hook
 - Refresh configuration files for the 7170-64C

### CODE REVIEW

**Comment by prsunny** [comment]
Can we also get the sensors data updated inhttps://github.com/Azure/sonic-mgmt/blob/master/ansible/group_vars/sonic/sku-sensors-data.yml

**Comment by Staphylo** [comment]
I will add the sensor definition for the 7170 in sonic-mgmt.
It is the only one affected but is not defined yet in sku-sensors-data.yml

**Comment by arkadiyshapiro** [comment]
> I will add the sensor definition for the 7170 in sonic-mgmt.
> It is the only one affected but is not defined yet in sku-sensors-data.yml

Is this to support this functionality: https://github.com/Azure/SONiC/pull/202 ?

**Comment by Staphylo** [comment]
> > I will add the sensor definition for the 7170 in sonic-mgmt.
> > It is the only one affected but is not defined yet in sku-sensors-data.yml
> 
> Is this to support this functionality: [Azure/SONiC#202](https://github.com/Azure/SONiC/pull/202) ?

We already support this feature for our products as we implemented the `get_transceiver_change_event` 
API a few months back.
This PR is a mix of features and fixes for issues we've seen during our testing.
Regarding the 7170-64C, it brings the support for `arista reboot-cause`, better reset cli via `arista reset`, fixes for temperature thresholds and the fancontrol configurations.

**Pull request merged**
