### PR TITLE
[docker_image_ctl.j2] Share UTS namespace with host OS

### PR DESCRIPTION
**Pull request by stepanblyschak**
Instead of updating hostname manualy on Config DB hostname change,
simply share containers UTS namespace with host OS.
Ideally, instead of setting `--uts=host` for every container in SONiC,
this setting can be set per container if feature requires.
One behaviour change is introduced in this commit, when `--privileged`
or `--cap-add=CAP_SYS_ADMIN` and `--uts=host` are combined, container
has privilege to change host OS and every other container hostname.
Such privilege should be fixed by limiting containers capabilities.

Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

**- What I did**

**- How I did it**

**- How to verify it**

```
admin@arc-switch1004:~$ hostname
arc-switch1004
admin@arc-switch1004:~$ docker exec -it swss hostname
arc-switch1004
admin@arc-switch1004:~$ sudo hostname sonic
admin@arc-switch1004:~$ hostname
sonic
admin@arc-switch1004:~$ docker exec -it swss hostname
sonic

```

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Thanks, @stepanblyschak!

I think we could also safely cherry-pick this into the 201911 branch. Any objections?

**Comment by SuvarnaMeenakshi** [comment]
> ny objections?

**Comment by stepanblyschak** [comment]
@jleveque Sure, it should be in 201911

**Comment by mykolaf** [comment]
retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by stepanblyschak** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by qiluo-msft** [comment]
Should we also cherry-pick to 201811 branch? Are you aware of any dependencies, such as docker engine's version?

**Comment by stepanblyschak** [comment]
@qiluo-msft docker engine in 201811 supports this feature. Why do we need to cherry-pick this PR into 201811? The idea behind this PR was to replace updateHostName functionality with simpler approach, but 201811 does not update hostname inside containers.

**Comment by qiluo-msft** [comment]
I notice this PR could not directly cherry-pick, so submit a new one https://github.com/Azure/sonic-buildimage/pull/4219.
The `--uts` feature is useful to keep host/container hostnames in sync.

**Comment by rlhui** [comment]
@jleveque , based on Qi's last comment, is this PR still needed in 201911?  If so, please remove the label and please confirm. Thanks.

**Comment by jleveque** [comment]
@rlhui: Qi's comment is regarding the 201811 branch. This PR still needs to be cherry-picked into 201911.

**Pull request merged**
