### PR TITLE
Lldp docker to use python3 version of sonic-db-syncd package.

### PR DESCRIPTION
**Pull request by abdosi**
What I did:

- Made changes so that Lldp docker start using py3 of sonic-db-syncd

- submodule update sonic-db-syncd

5cc29a1b32d8d1f4dfbc967bfea2727c50a49c76 (HEAD -> master, origin/master, origin/HEAD) Changes to convert sonic-dbsyncd from python 2 to 3

How I verify:

Verify and tested local build.

### CODE REVIEW

**Review by jleveque — COMMENTED** [review]
Do we still need to list the Python 2 swsscommon package (`PYTHON_SWSSCOMMON`) as a dependency in rules/docker-lldp.mk?

**Comment by abdosi** [comment]
> Do we still need to list the Python 2 swsscommon package (`PYTHON_SWSSCOMMON`) as a dependency in rules/docker-lldp.mk?

@jleveque No we don't need it and i wanted to remove it but saw other modules still having it even though move to python 3 so i thought there might be reason for that.

**Comment by jleveque** [comment]
> > Do we still need to list the Python 2 swsscommon package (`PYTHON_SWSSCOMMON`) as a dependency in rules/docker-lldp.mk?
> 
> @jleveque No we don't need it and i wanted to remove it but saw other modules still having it even though move to python 3 so i thought there might be reason for that.

If you're positive nothing else in the container needs it, you can remove it. We need to make a pass later and clean up other places where Python 2 packages no longer need to be installed.

**Comment by lguohan** [comment]
please resubmit the pr. the commit is no longer available.

**Comment by lguohan** [comment]
retest this please

**Comment by abdosi** [comment]
retest vsimage please

**Comment by abdosi** [comment]
> > > Do we still need to list the Python 2 swsscommon package (`PYTHON_SWSSCOMMON`) as a dependency in rules/docker-lldp.mk?
> > 
> > 
> > @jleveque No we don't need it and i wanted to remove it but saw other modules still having it even though move to python 3 so i thought there might be reason for that.
> 
> If you're positive nothing else in the container needs it, you can remove it. We need to make a pass later and clean up other places where Python 2 packages no longer need to be installed.

@jleveque updates to remove python2 swsscommon

**Comment by abdosi** [comment]
Retest vsimage please

**Review by jleveque — APPROVED** [review]

**Pull request merged**
