### PR TITLE
frr: Move docker to stretch and add pythontools

### PR DESCRIPTION
**Pull request by nikos-github**
Debian packages for frr-dbgsym and frr-snmp-dbgsym are also built and will be under src/sonic-frr directory.

Signed-off-by: nikos ntriantafillis@gmail.com

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
Is it possible to move dbgsym packages to TARGET dir also?

**Comment by nikos-github** [comment]
@pavel-shirshov Main target dbgsym added:

nikos@bs101-01r:~/sonic-201904221202/sonic-buildimage/target/debs/stretch$ ls -la frr*
-rw-r--r-- 1 nikos apstrktr 2015124 Apr 25 00:05 frr_6.0.2-1~sonic.debian9+1_amd64.deb
-rw-r--r-- 1 nikos apstrktr  696106 Apr 25 00:05 frr_6.0.2-1~sonic.debian9+1_amd64.deb.log
-rw-r--r-- 1 nikos apstrktr 7292036 Apr 25 00:05 frr-dbgsym_6.0.2-1~sonic.debian9+1_amd64.deb
-rw-r--r-- 1 nikos apstrktr   35678 Apr 25 00:05 frr-pythontools_6.0.2-1~sonic.debian9+1_amd64.deb

**Comment by nikos-github** [comment]
Retest this.

**Comment by nikos-github** [comment]
retest this please

**Comment by jipanyang** [comment]
The build seems to be failing when using frr routing stack:

```
jipan@jipan:~/sonic-buildimage$ git log
commit 452e75c95144d8aa5b0bd5a769a78cd59b41a406 (HEAD -> master, origin/master, origin/HEAD)
Author: pavel-shirshov <pavelsh@microsoft.com>
Date:   Thu Apr 25 16:16:22 2019 -0700

    Downport the netlink patch to libteam1.26. Increase netlink buffers (#2822)

commit 6bf97d8a23897459a3037dd5383ec7b472afdb64
Author: Nikos <31227248+nikos-github@users.noreply.github.com>
Date:   Thu Apr 25 13:21:20 2019 -0700

    [docker-frr]: Move docker to stretch and add pythontools (#2819)

```


```
jipan@jipan:~/sonic-buildimage$ make target/debs/stretch/frr_6.0.2-1~sonic.debian9+1_amd64.deb-clean
+++ --- Making target/debs/stretch/frr_6.0.2-1~sonic.debian9+1_amd64.deb-clean --- +++
BLDENV=stretch make -f Makefile.work stretch
make[1]: Entering directory '/home/jipan/sonic-buildimage'
SONiC Build System

Build Configuration
"CONFIGURED_PLATFORM"             : "vs"
"SONIC_CONFIG_PRINT_DEPENDENCIES" : ""
"SONIC_BUILD_JOBS"                : "1"
"SONIC_CONFIG_MAKE_JOBS"          : "8"
"USERNAME"                        : "admin"
"PASSWORD"                        : "YourPaSsWoRd"
"ENABLE_DHCP_GRAPH_SERVICE"       : ""
"SHUTDOWN_BGP_ON_START"           : ""
"ENABLE_PFCWD_ON_START"           : ""
"INSTALL_DEBUG_TOOLS"             : "y"
"ROUTING_STACK"                   : "frr"
"FRR_USER_UID"                    : "300"
"FRR_USER_GID"                    : "300"
"ENABLE_SYNCD_RPC"                : ""
"ENABLE_ORGANIZATION_EXTENSIONS"  : "y"
"HTTP_PROXY"                      : ""
"HTTPS_PROXY"                     : ""
"ENABLE_SYSTEM_TELEMETRY"         : "y"
"SONIC_DEBUGGING_ON"              : "y"
"SONIC_PROFILING_ON"              : ""
"KERNEL_PROCURE_METHOD"           : "build"
"BUILD_TIMESTAMP"                 : "20190426.173427"
"BLDENV"                          : "stretch"
"VS_PREPARE_MEM"                  : "yes"

[ FAIL LOG START ] [ target/debs/stretch/frr_6.0.2-1~sonic.debian9+1_amd64.deb ]
make[1]: Entering directory '/sonic/src/sonic-frr'
# Build the package
pushd ./frr
# This could very well be tools/tarsource.sh -V -e sonic
tools/tarsource.sh -V
# This is a no-op but here in case the changelog stops being a symlink
debchange -b -v 6.0.2-1~sonic.debian9+1 'SONiC FRR debian package build'
sudo apt-get -y install install-info
dpkg-buildpackage -rfakeroot -b -us -uc -Ppkg.frr.nortrlib

....

 dh_builddeb -O--parallel
	dpkg-deb --build debian/frr ..
	dpkg-deb --build debian/frr-snmp ..
	dpkg-deb --build debian/frr-doc ..
	dpkg-deb --build debian/frr-pythontools ..
dpkg-deb: building package 'frr-doc' in '../frr-doc_6.0.2-0_all.deb'.
dpkg-deb: building package 'frr-pythontools' in '../frr-pythontools_6.0.2-0_all.deb'.
dpkg-deb: building package 'frr-snmp' in '../frr-snmp_6.0.2-0_amd64.deb'.
dpkg-deb: building package 'frr' in '../frr_6.0.2-0_amd64.deb'.
make[2]: Leaving directory '/sonic/src/sonic-frr/frr'
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../frr_6.0.2-1~sonic.debian9+1_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build frr
dpkg-buildpackage: info: binary-only upload (no source included)
mv: target 'frr_6.0.2-1~sonic.debian9+1_amd64.deb' is not a directory
Makefile:12: recipe for target '/sonic/target/debs/stretch/frr_6.0.2-1~sonic.debian9+1_amd64.deb' failed
make[1]: *** [/sonic/target/debs/stretch/frr_6.0.2-1~sonic.debian9+1_amd64.deb] Error 1
make[1]: Leaving directory '/sonic/src/sonic-frr'
[  FAIL LOG END  ] [ target/debs/stretch/frr_6.0.2-1~sonic.debian9+1_amd64.deb ]
slave.mk:285: recipe for target 'target/debs/stretch/frr_6.0.2-1~sonic.debian9+1_amd64.deb' failed
make: *** [target/debs/stretch/frr_6.0.2-1~sonic.debian9+1_amd64.deb] Error 1
Makefile.work:133: recipe for target 'stretch' failed
make[1]: *** [stretch] Error 2
make[1]: Leaving directory '/home/jipan/sonic-buildimage'
Makefile:6: recipe for target 'target/debs/stretch/frr_6.0.2-1~sonic.debian9+1_amd64.deb-clean' failed
make: *** [target/debs/stretch/frr_6.0.2-1~sonic.debian9+1_amd64.deb-clean] Error 2
```

**Pull request merged**
