### PR TITLE
[Mellanox] Update hw-management package to version 7.0010.2000

### PR DESCRIPTION
**Pull request by keboliu**
**This PR depends on https://github.com/Azure/sonic-linux-kernel/pull/195  and https://github.com/Azure/sonic-buildimage/pull/6490**

**- Why I did it**

**Bug fixes**

-  In rare cases when thermal algorithem is Re-activiated after FAN/PSU insertion, FAN remians at high rpm
-  When stop hw-managment code received error in the log instead of exit code '0'.
-  In SPC1 i2c sometimes collide with chip reset coming from SDK
-  Remove raw eeprom data link, when working with PSU which don't have eeprom for "msn274x", "msn24xx" and "msn27xx" systems
-  Fix memory leak on mlxsw_core_bus_device module removal

**- How I did it**

Update the hw-mgmt version number in the make file
Update the hw-mgmt repo pointer

**- How to verify it**
run platform related test cases on all Mellanox platform

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by lguohan** [comment]
kernel patch is merge, can you update this pr?

**Comment by keboliu** [comment]
@lguohan when update sonic-linux-kernel submodule pointer in this branch always have a conflict which I can not resolve, so I created a separated PR to update the kernel submodule: https://github.com/Azure/sonic-buildimage/pull/6908  please have a look

**Comment by liat-grozovik** [comment]
/azp run

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by liat-grozovik** [comment]
/AzurePipelines run

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
