### PR TITLE
[Nokia]: EEPROM platform API Python3 compliance changes

### PR DESCRIPTION
**Pull request by carl-nokia**
**- Why I did it**
Make EEPROM platform APIs Python3 compliant in Nokia platform.

**- How I did it**
Handle bytearray type returned by read_eeprom and read_eeprom_bytes methods.

**- How to verify it**
Boot Nokia ixs7215 and verify PMON docker running and show platform syseeprom 

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by carl-nokia** [comment]
Please retest vsimage

**Comment by carl-nokia** [comment]
Please retest mellanox

**Comment by dflynn-Nokia** [comment]
Retest mellanox please

**Comment by dflynn-Nokia** [comment]
Retest vsimage please

**Pull request merged**
