### PR TITLE
Updated Internal BGP Templates for chassis packet

### PR DESCRIPTION
**Pull request by abdosi**
What/Why I did:

```
   Some time jinja2 template renderation of Loopbcack4096 was not happening
    correctly because of timing issue where DB might not be poupulated.
    So Instead of using IP Address using Interface name.

    Fixes: https://github.com/Azure/sonic-buildimage/issues/9610
```

How I verify:

Unit Test.

### CODE REVIEW

**Comment by abdosi** [comment]
@anamehra Can you please check if this fixes the issue.

**Comment by anamehra** [comment]
> @anamehra Can you please check if this fixes the issue.

@abdosi , I validated this change before the holidays and it worked fine. You may go ahead with the merge.

**Review by anamehra — APPROVED** [review]

**Comment by abdosi** [comment]
@arlakshm can you please help review/approve this.

**Comment by arlakshm** [comment]
@abdosi, as discussed offline can you verify the race condition where the Loopback4096 ip address is configuration after the bgp configuration is applied in FRR

**Comment by abdosi** [comment]
> @abdosi, as discussed offline can you verify the race condition where the Loopback4096 ip address is configuration after the bgp configuration is applied in FRR

@arlakshm I have done some more regression testing with this change and it looks fine. Can you please approve this.

**Pull request merged**
