### PR TITLE
[submodule] Advance sonic-utilities submodule pointer

### PR DESCRIPTION
**Pull request by liorghub**
Update sonic-utilities submodule to include the below commits:
510a9b9 Add date to show version (#2086)
61b1396 [sfpshow][recycle_port] sfpshow script needs to skip recycle ports (#2109)
4681697 Support command `show ip fib` and `show ipv6 fib` (#2100)
2a982a1 Update `config mirror_session` CLI to support heximal gre type value (#2095)
b25f1e1 [generic-config-updater] Add caclrule validator (#2103)
968900c [sonic-package-manager] do not mod_config for whole config db when setting init_cfg (#2055)
bf55ceb [nvgre] Added auto-generated CLI plugins and test for NVGRE Tunnel feature (#1915)
8389c81 [sonic-cli-gen] fix failure "Error: digits_class" when field "digit_class" does not exist in DB (#2054)
f71ef64 Fix import statement in mclag.py (#2073)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by msosyak** [comment]
@liorghub Could you, please, include one more commit in your PR https://github.com/Azure/sonic-utilities/pull/2073

**Comment by liorghub** [comment]
> @liorghub Could you, please, include one more commit in your PR [Azure/sonic-utilities#2073](https://github.com/Azure/sonic-utilities/pull/2073)

2 more commits were added.

**Comment by liorghub** [comment]
Test kvmtest-t0-part1 failed with:
ERROR pc/test_po_update.py::test_po_update[vlab-01-None] - Failed: Processes ...

Rerunning now to see if fails with the same error.

**Comment by liorghub** [comment]
@liat-grozovik can you rerun please?

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
