### PR TITLE
[Mellanox]Fix the issue when an SFP module is plugged into a QSFP port via QSA

### PR DESCRIPTION
**Pull request by stephenxs**
**- What I did**
Fix the issue when an SFP module is plugged into a QSFP port via an adapter.

**- How I did it**
Originally the type of an SFP module is determined according to the SKU dictionary. However, it's possible that as SFP module is plugged into a QSFP port via an adapter. In this case, the EEPROM content will be parsed in the wrong format.
To address that we fetch the identifier value of an xSFP module and then get the type by parsing it.

**- How to verify it**
Fetch and parse the content of SFP modules and check them.
[sfp-type-detect-test.txt](https://github.com/Azure/sonic-buildimage/files/3924776/sfp-type-detect-test.txt)

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by stephenxs** [comment]
To be cherry-picked to bmtor, it requires the following PR cherry-picked first:
[[Mellanox] support get_transceiver_threshold_info (#3777)](https://github.com/Azure/sonic-buildimage/pull/3777) commit hash 0c9040dec9642688fdb944f2f2da161acbfe07a2

**Comment by nazariig** [comment]
@yxieca just a kindly reminder: please take it to bmtor.

**Comment by jleveque** [comment]
@stephenxs, @nazariig: Should this PR (and https://github.com/Azure/sonic-buildimage/pull/3777) also be cherry-picked into the 201911 branch? Are there any other dependencies or any reasons not to?

**Comment by stephenxs** [comment]
hi @jleveque, I suggest doing so. no dependency on 201911.

**Comment by jleveque** [comment]
@stephenxs: Thanks. Just to clarify, https://github.com/Azure/sonic-buildimage/pull/3777 is a required dependency, but there are no others, correct?

**Comment by stephenxs** [comment]
> @stephenxs: Thanks. Just to clarify, #3777 is a required dependency, but there are no others, correct?

Hi @jleveque ,
Yes. 
On bmtor, it depends on #3777 and doesn't have any other dependencies.
On 201911, it doesn't require any dependency.

**Comment by jleveque** [comment]
@stephenxs: So we should or should not also cherry-pick https://github.com/Azure/sonic-buildimage/pull/3777 into the 201911 branch?

**Comment by stephenxs** [comment]
3777 is already merged into 201911.
probably I failed to express it clear. 
for both branch when I said it didn't require other dependencies what I meant is other dependencies have already been merged into the branch. :)

**Comment by jleveque** [comment]
Ah, I've got it now. Thanks! #3777 didn't have any "Request for 201911" or "Included in 201911" labels, so I wasn't aware that it had already had been cherry-picked. I will add the "Included in 201911" label to it now.

**Pull request merged**
