### PR TITLE
[Juniper] Migrating to SONiC Platform API package

### PR DESCRIPTION
**Pull request by ciju-juniper**
This patch set introduce platform API package for QFX5210 & QFX5200 platforms

Signed-off-by: Ciju Rajan K <crajank@juniper.net>

### CODE REVIEW

**Comment by ciju-juniper** [comment]
Test logs for QFX5200

root@sonic:~# show interfaces status 
  Interface            Lanes    Speed    MTU    FEC            Alias    Vlan    Oper    Admin             Type    Asym PFC
-----------  ---------------  -------  -----  -----  ---------------  ------  ------  -------  ---------------  ----------
  Ethernet0      49,50,51,52     100G   9100    N/A   hundredGigE1/1  routed      up       up  QSFP28 or later         N/A
  Ethernet4      53,54,55,56     100G   9100    N/A   hundredGigE1/2  routed      up       up  QSFP28 or later         N/A
  Ethernet8      57,58,59,60     100G   9100    N/A   hundredGigE1/3  routed      up       up  QSFP28 or later         N/A
 Ethernet12      61,62,63,64     100G   9100    N/A   hundredGigE1/4  routed      up       up  QSFP28 or later         N/A
 Ethernet16      65,66,67,68     100G   9100    N/A   hundredGigE1/5  routed      up       up  QSFP28 or later         N/A
 Ethernet20      69,70,71,72     100G   9100    N/A   hundredGigE1/6  routed      up       up  QSFP28 or later         N/A
 Ethernet24      73,74,75,76     100G   9100    N/A   hundredGigE1/7  routed      up       up  QSFP28 or later         N/A
 Ethernet28      77,78,79,80     100G   9100    N/A   hundredGigE1/8  routed      up       up  QSFP28 or later         N/A
 Ethernet32      81,82,83,84     100G   9100    N/A   hundredGigE1/9  routed    down       up   QSFP+ or later         N/A
 Ethernet36      85,86,87,88     100G   9100    N/A  hundredGigE1/10  routed    down       up   QSFP+ or later         N/A
 Ethernet40      37,38,39,40     100G   9100    N/A  hundredGigE1/11  routed    down       up  QSFP28 or later         N/A
 Ethernet44      33,34,35,36     100G   9100    N/A  hundredGigE1/12  routed      up       up  QSFP28 or later         N/A
 Ethernet48      41,42,43,44     100G   9100    N/A  hundredGigE1/13  routed      up       up  QSFP28 or later         N/A
 Ethernet52      45,46,47,48     100G   9100    N/A  hundredGigE1/14  routed    down       up  QSFP28 or later         N/A
 Ethernet56      89,90,91,92     100G   9100    N/A  hundredGigE1/15  routed      up       up  QSFP28 or later         N/A
 Ethernet60      93,94,95,96     100G   9100    N/A  hundredGigE1/16  routed      up       up  QSFP28 or later         N/A
 Ethernet64     97,98,99,100     100G   9100    N/A  hundredGigE1/17  routed    down       up  QSFP28 or later         N/A
 Ethernet68  101,102,103,104     100G   9100    N/A  hundredGigE1/18  routed    down       up              N/A         N/A
 Ethernet72      17,18,19,20     100G   9100    N/A  hundredGigE1/19  routed    down       up              N/A         N/A
 Ethernet76      21,22,23,24     100G   9100    N/A  hundredGigE1/20  routed    down       up              N/A         N/A
 Ethernet80      29,30,31,32     100G   9100    N/A  hundredGigE1/21  routed    down       up              N/A         N/A
 Ethernet84      25,26,27,28     100G   9100    N/A  hundredGigE1/22  routed    down       up              N/A         N/A
 Ethernet88  105,106,107,108     100G   9100    N/A  hundredGigE1/23  routed    down       up              N/A         N/A
 Ethernet92  109,110,111,112     100G   9100    N/A  hundredGigE1/24  routed    down       up              N/A         N/A
 Ethernet96  113,114,115,116     100G   9100    N/A  hundredGigE1/25  routed    down       up              N/A         N/A
Ethernet100  117,118,119,120     100G   9100    N/A  hundredGigE1/26  routed    down       up              N/A         N/A
Ethernet104  121,122,123,124     100G   9100    N/A  hundredGigE1/27  routed    down       up              N/A         N/A
Ethernet108  125,126,127,128     100G   9100    N/A  hundredGigE1/28  routed    down       up              N/A         N/A
Ethernet112          1,2,3,4     100G   9100    N/A  hundredGigE1/29  routed      up       up  QSFP28 or later         N/A
Ethernet116          5,6,7,8     100G   9100    N/A  hundredGigE1/30  routed      up       up  QSFP28 or later         N/A
Ethernet120       9,10,11,12     100G   9100    N/A  hundredGigE1/31  routed      up       up  QSFP28 or later         N/A
Ethernet124      13,14,15,16     100G   9100    N/A  hundredGigE1/32  routed      up       up  QSFP28 or later         N/A
root@sonic:~# show platform fan 
  Drawer    LED            FAN    Speed    Direction    Presence    Status          Timestamp
--------  -----  -------------  -------  -----------  ----------  --------  -----------------
FanTray0    N/A  FanTray0 Fan1      55%       intake     Present        OK  20210707 00:28:32
FanTray0    N/A  FanTray0 Fan2      55%       intake     Present        OK  20210707 00:28:32
FanTray1    N/A  FanTray1 Fan3      55%       intake     Present        OK  20210707 00:28:32
FanTray1    N/A  FanTray1 Fan4      55%       intake     Present        OK  20210707 00:28:32
FanTray2    N/A  FanTray2 Fan1      55%       intake     Present        OK  20210707 00:28:32
FanTray2    N/A  FanTray2 Fan2      55%       intake     Present        OK  20210707 00:28:32
FanTray3    N/A  FanTray3 Fan3      55%       intake     Present        OK  20210707 00:28:32
FanTray3    N/A  FanTray3 Fan4      55%       intake     Present        OK  20210707 00:28:32
FanTray4    N/A  FanTray4 Fan1      55%       intake     Present        OK  20210707 00:28:32
FanTray4    N/A  FanTray4 Fan2      55%       intake     Present        OK  20210707 00:28:32
     N/A    N/A      PSU 0 Fan      20%       intake     Present        OK  20210707 00:28:32
     N/A    N/A      PSU 1 Fan      14%       intake     Present        OK  20210707 00:28:32
root@sonic:~# show platform temperature 
       Sensor    Temperature    High TH    Low TH    Crit High TH    Crit Low TH    Warning          Timestamp
-------------  -------------  ---------  --------  --------------  -------------  ---------  -----------------
Temp sensor 1         39.438         85       N/A             N/A            N/A      False  20210707 00:29:32
Temp sensor 2         39.875         85       N/A             N/A            N/A      False  20210707 00:29:32
Temp sensor 3         46             85       N/A             N/A            N/A      False  20210707 00:29:32
Temp sensor 4         41.25          85       N/A             N/A            N/A      False  20210707 00:29:32
Temp sensor 5         38.875         85       N/A             N/A            N/A      False  20210707 00:29:32
Temp sensor 6         45.688         85       N/A             N/A            N/A      False  20210707 00:29:32
Temp sensor 7         40.688         85       N/A             N/A            N/A      False  20210707 00:29:32
Temp sensor 8         42.875         85       N/A             N/A            N/A      False  20210707 00:29:32
root@sonic:~# show platform psustatus
PSU    Model    Serial    HW Rev    Voltage (V)    Current (A)    Power (W)    Status       LED
-----  -------  --------  --------  -------------  -------------  -----------  -----------  -----
PSU 1  N/A      N/A       N/A       12.0           17.0           204.0        OK           False
PSU 2  N/A      N/A       N/A       N/A            N/A            N/A          NOT PRESENT  False
root@sonic:~# show platform firmware version
fwutil version 2.0.0.0
root@sonic:~# show platform firmware status
Chassis             Module    Component    Version      Description
------------------  --------  -----------  -----------  -------------------------
QFX5200-32C-S-CHAS  N/A       BIOS         V0018.6U     Basic Input/Output System
                              TMC          0x05_000002  TOR Master Control fpga
                                           04
root@sonic:~#

**Comment by ciju-juniper** [comment]
Test logs on both the platforms are attached:

[QFX5210_commands_log.txt](https://github.com/Azure/sonic-buildimage/files/6771418/QFX5210_commands_log.txt)

[QFX5200_command_log.txt](https://github.com/Azure/sonic-buildimage/files/6771419/QFX5200_command_log.txt)

**Comment by ciju-juniper** [comment]
@lguohan @jleveque  Could you consider merging this patch set?

**Comment by ciju-juniper** [comment]
This PR fixes the issue https://github.com/Azure/sonic-buildimage/issues/5986

**Comment by ciju-juniper** [comment]
@lguohan @jleveque  Could you review and approve the patches? This patch set will make Juniper platforms functional on master branch which was broken for a while.

**Comment by ciju-juniper** [comment]
@lguohan @jleveque  Could you please take a look?

**Comment by lguohan** [comment]
can you fix lgtm alerts?

**Comment by ciju-juniper** [comment]
@lguohan Most of the alerts are due to this warning Wrong number of arguments to constructor initialization from a for loop.

Eg: 
  thermal = Thermal(idx) 

For which constructor is having the initialization routine
   def __init__(self, thermal_index=0):

I'm not sure what is wrong with the call / definitions.  I've already suppressed it using '#lgtm [py/call/wrong-number-class-arguments]',

**Comment by ciju-juniper** [comment]
@lguohan All the false positive warnings are marked with the comment '#lgtm [...]'. You could see it by opening the lgtm link: https://lgtm.com/projects/g/Azure/sonic-buildimage/rev/pr-f582fa5952ed702151a827f96acf2f5d1bf5f363

Lgtm says, the warnings will go away only when the pull request is merged, if the updates are made from a pull request.

Please merge the patch set.

**Comment by ciju-juniper** [comment]
@lguohan Would you be able to merge this patch set as there is no way as per the LGTM to show the warnings as zero in the pull request?

**Comment by ciju-juniper** [comment]
Closing this pull request as lgtm is not able to show the fixed alerts.

**Pull request closed without merging**
