### PR TITLE
[watermark] Fix error: BUFFER_POOL_WATERMARK isn't enabled by default

### PR DESCRIPTION
**Pull request by stephenxs**
**- Why I did it**
Fix error: watermarkstat -t buffer_pool doesn't work

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@stephenxs is this required for 201911 as well?

**Comment by stephenxs** [comment]
> @stephenxs is this required for 201911 as well?

Yes, it is.

**Comment by lguohan** [comment]
@neethajohn , can you review?

**Comment by neethajohn** [comment]
Is the intention of this PR to get the buffer pool watermark or to have the buffer pool watermark enabled by default in the image? You could just use 'counterpoll watermark enable' to enable the buffer pool watermark polling

**Comment by stephenxs** [comment]
> Is the intention of this PR to get the buffer pool watermark or to have the buffer pool watermark enabled by default in the image? You could just use 'counterpoll watermark enable' to enable the buffer pool watermark polling



> Is the intention of this PR to get the buffer pool watermark or to have the buffer pool watermark enabled by default in the image? You could just use 'counterpoll watermark enable' to enable the buffer pool watermark polling

to have the buffer pool enabled by default in the image.

**Pull request merged**
