### PR TITLE
Install mcelog package to host OS; log machine check exceptions (MCE) to syslog

### PR DESCRIPTION
**Pull request by jleveque**
**- What I did**

- Install mcelog package to host Debian OS. This installs a daemon which checks for machine check exceptions (MCE) and logs them to syslog.

**- How to verify it**

Check syslog for messages from the mcelog daemon (example below)

```
Jul 15 19:30:39 sonic mcelog[445]: Starting Machine Check Exceptions decoder: mcelog.
Jul 15 19:30:39 sonic mcelog: failed to prefill DIMM database from DMI data
Jul 15 19:30:39 sonic mcelog: warning: 32 bytes ignored in each record
Jul 15 19:30:39 sonic mcelog: consider an update
Jul 15 19:30:39 sonic mcelog: failed to prefill DIMM database from DMI data
Jul 15 19:30:39 sonic mcelog: warning: 32 bytes ignored in each record
Jul 15 19:30:39 sonic mcelog: consider an update
```

This commit should cherry-pick cleanly into the 201904 branch, but I will need to open a similar PR against the 201811 branch due to conflicts.

### CODE REVIEW

**Comment by jleveque** [comment]
Retest vs please

**Comment by jleveque** [comment]
Retest vs please

**Comment by lguohan** [comment]
I am not sure the mcelog is logged into the syslog.

**Comment by jleveque** [comment]
@lguohan: Yes, it logs to syslog. I have verified this. By default, it logs to /var/log/mcelog, but with our rsyslog settings, it is instead directed to /var/log/syslog.

**Comment by lguohan** [comment]
I installed this on device, I found the errors are still in /var/log/mcelog.

**Comment by jleveque** [comment]
@lguohan: That's strange. I have an image currently running, and the messages are written to syslog. Did you install the package manually or build and install an image with this PR?

**Comment by jleveque** [comment]
Gotcha. I was unaware that  mcelog logs to two different location by default. All messages go to syslog *except* MCE messages which, by default, get logged to mcelog. Commit https://github.com/Azure/sonic-buildimage/pull/3158/commits/dda1326fd0c345c9636a3c6395f4d1457857e1c9 configures mcelog to log MCE messages to syslog, as well.

**Pull request merged**
