### PR TITLE
[LLDP] Enable/disable container auto-restart based on configuration.

### PR DESCRIPTION
**Pull request by yozhao101**
- What I did
Currently we already have the auto-restart features for each docker container. That means if a critical
process exited abnormally or crashed, this event will be captured and then the corresponding
container will be restarted. Right now, we want to add a knob/switch for this feature in LLDP such that the developer can dynamically turn on/off it during testing new docker images.

- How I did it
We will create a table in the database container. In this table, we store the current state of
auto-restart feature for LLDP. Initially, the state of this feature will be enabled.
The event listener will dynamically read the state from database container and then decide whether
restart the container based on it once receive the event showing a critical process exited.
The user can use the existing interface (TBD) to modify this state from enabled to disabled or
vice versa.

- How to verify it
I manually created a table in the database container called CONTAINER_FEATURE. In this table, each
container will have its corresponding state row such as the initial state of auto-restart for LLDP is in the 'enabled' status.

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
Is it possible to have one listener script for everything?

**Comment by yozhao101** [comment]
Actually in our first version, we have a single listener script for all the containers. In detail, we placed this listener script in the files/scripts/ and then copy this script into the image of different containers. However, currently we want to implement a knob/switch to dynamically turn on/off this event listener for all containers. If we still use a single script, we should have to decide in the script which container we should turn on/off this listener. That will let a container to touch the state of other different containers.

**Comment by yozhao101** [comment]
@pavel-shirshov I do not know whether I answered your question clearly. If I am not, we can have a talk with Joe together to polish this design.

**Comment by jleveque** [comment]
@pavel-shirshov: As Yong stated above, my original design shared one listener script among all containers. However, we are now adding a "knob" to enable/disable the feature on a per-container basis using Config DB. This requires the listener script to have knowledge of the name of the container in which it is running. However, we currently do not have a way to obtain the container name from within the container.

**Comment by pavel-shirshov** [comment]
@jleveque Is it possible to run the script with a parameter?

**Comment by jleveque** [comment]
@pavel-shirshov: Good idea. It's worth looking into. The official documentation doesn't mention anything about parameters. Since the event listener command is specified in the supervisor config file, I don't see we we cannot pass a parameter specifying the container name.

@yozhao101: Can you please look into this approach?

**Comment by yozhao101** [comment]
@jleveque Sure, I will do it.

**Comment by yozhao101** [comment]
@pavel-shirshov @jleveque The method passing container name as the parameter to event listener does work. I double check this using multiple containers such as lldp, snmp, teamd and syncd. Thanks so much again @pavel-shirshov for your solution!

**Pull request closed without merging**
