### PR TITLE
[barefoot][platform] increase init timeout in eeprom.py

### PR DESCRIPTION
**Pull request by vboykox**
**- Why I did it**
Because of platform-specific reasons I have to increase init timeout in (platform-plugin)/eeprom.py
**- Description for the changelog**
[barefoot][platform] increase init timeout in eeprom.py

### CODE REVIEW

**Comment by vboykox** [comment]
@akokhan @msosyak

**Comment by akokhan** [comment]
Please cherry pick into 202006

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
retest broadcom please

**Pull request merged**
