### PR TITLE
[sonic-utilities] Update submodule

### PR DESCRIPTION
**Pull request by daall**
Add a switch to route_check to control whether write log to syslog (#1215)
[consutil] Store console port state in STATE_DB (#1208)
[sfputil] Display 'N/A' for non-SFP ports (#1078)
Show FG_NHG CLI Commands Added (#1056)
[show] remove 'device2interface_dict' in show interface neighbor expected (#1188)
Add license file, remove third-party licenses file (#1192)
[fwutil]: Set min log priority to INFO. (#1191)
[CLI][show][platform] Added ASIC count in the output. (#1185)
fdbshow and nbrshow use SonicV2Connector with decode_responses=True, and remove all the decode() (#1187)
Remove stdeb.cfg; no longer used now that we build as wheel (#1182) 
[counterpoll] Disable Counter Poll When Entering Fast Reboot (#1174) 
Fixes the issue with show interface counters and for pfc and queue counters. (#1180)
[config/show] Add CLI support for proxy arp (#1168)
[consutil] Add brief option to show line command (#1176)
Modify fast-reboot script to use BGP service script to stop bgp service (#1177)
[config/console] Support update console configuration related commands (#1166)
[consutil] Fix issue where the show line command crash if no ttyUSB exists (#1173)
[watermarkstat] Add unit tests for watermarkstat show commands (#1157)
Fix exception for ipaddress in python2 (#1164) 
[celestica] consutil to support customize tty device name (#1155)

Signed-off-by: Danny Allen <daall@microsoft.com>

**- Why I did it**
To get sonic-utilities up to date and pull in some bug fixes to the master image.

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

**Comment by lguohan** [comment]
retest vs please

**Comment by lguohan** [comment]
retest mellanox please

**Comment by jleveque** [comment]
Looks like this PR is now superceded by https://github.com/Azure/sonic-buildimage/pull/5828. Do we still want to merge this?

**Comment by daall** [comment]
> Looks like this PR is now superseded by #5828. Do we still want to merge this?

the vs failed and that will take ??? time to build so we may as well use the other PR

**Comment by lguohan** [comment]
#5828 has build issue, cannot pass baseimage build. need someone to investigate. this pr is ok. vsimage pass. I will merge it to unblock.

**Pull request merged**
