### PR TITLE
[device]Add configuration parameters for as5835_54x

### PR DESCRIPTION
**Pull request by dereksun01**
Signed-off-by: derek_sun <derek_sun@edge-core>

**- Why I did it**
Add configuration parameters for as5835_54x.

**- How I did it**
Modify device configuration file(mv2-as5835-48x10G+6x100G.config.bcm).

**- How to verify it**
-Running this configuration file on device(as5835_54x).

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [x] 202006
- [x] 202012

**- Description for the changelog**

Add configuration parameters for as5835_54x

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by dereksun01** [comment]
Retest vsimage please

**Comment by dereksun01** [comment]
Dear Manager,

Could you merge this PR? or need to improve it ? Thanks.

**Comment by dereksun01** [comment]
Dear Manager,

Could you merge this PR to 202012 branch? Thanks.

**Comment by Lewis-Kang** [comment]
@lguohan could you please review and merge or let us know your concern? Thanks.

**Comment by dereksun01** [comment]
Dear Manager,

Could you merge this PR to 202012 branch?
We have verify this PR on 202012 branch and it's works fine, Thanks.
[
[as5835_54x_202012branch.log](https://github.com/Azure/sonic-buildimage/files/5846111/as5835_54x_202012branch.log)
](url)

**Comment by dereksun01** [comment]
Dear Manager,

Could you merge this PR into 202012 branch too?
We have test this PR on 202012 branch and test log can refer the as5835_54x_202012branch.log, thanks.

**Comment by dereksun01** [comment]
-Close by derek_sun
-Reference: PR-6970
https://github.com/Azure/sonic-buildimage/pull/6970

**Pull request closed without merging**
