### PR TITLE
[monit] Periodically monitor VNET route consistency

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Signed-off-by: Volodymyr Samotiy <volodymyrs@nvidia.com>

**- Why I did it**
To run VNET route consistency check periodically.

For any failure, the monit will raise alert based on return code.
The tool will log required details.

Depends on https://github.com/Azure/sonic-utilities/pull/1300

**- How I did it**
Added configuration entry to "SONiC monit"

**- How to verify it**
Configure VNET routes then remove some in ASIC_DB or APP_DB and verify logs for error messages.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

**- Description for the changelog**

[monit] Periodically monitor VNET route consistency

### CODE REVIEW

**Review by prsunny — DISMISSED** [review]

**Comment by prsunny** [comment]
https://github.com/Azure/sonic-utilities/pull/1300

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
@volodymyrsamotiy please check failures and if there are dependencies to have this passing.

**Pull request closed without merging**
