### PR TITLE
[arista] Update platform drivers submodules

### PR DESCRIPTION
**Pull request by Staphylo**
- Use SONIC_DPKG_DEBS instead of SONIC_MAKE_DEBS to build the drivers
 - Refactor buildsystem to make it more packaging dependent
 - Automatically change kernel dependency based on KVERSION_SHORT
 - Kernel driver fixes for linux 4.19 with support up to 5.5
 - Add platform-arista-daemon.service (currently disabled because of driver restart issues)
 - Add management port mac address check in the daemon
 - Disable power cycle on SEU and monitor SEU state in the daemon
 - Improved test runtime
 - Misc fixes and improvements

### CODE REVIEW

**Comment by Staphylo** [comment]
retest vsimage please

**Comment by Staphylo** [comment]
retest vsimage please

**Comment by Staphylo** [comment]
retest vsimage please

**Comment by Staphylo** [comment]
retest vsimage please

**Comment by Staphylo** [comment]
retest vs please

**Comment by Staphylo** [comment]
retest vsimage please

**Comment by akokhan** [comment]
retest vsimage please

**Comment by akokhan** [comment]
retest vsimage please

**Comment by jleveque** [comment]
@Staphylo: Should this PR also get cherry-picked into the 201911 branch?

**Comment by Staphylo** [comment]
@jleveque that would be great, yes

**Pull request merged**
