### PR TITLE
[201911] DellEMC platform API 2.0 for Z9264f, S5232f 

### PR DESCRIPTION
**Pull request by aravindmani-1**
**- Why I did it**
Added API 2.0 in 201911 branch 
**- How to verify it**
Executed necessary API's through python shell
[s5232_API_2.0_UT.txt](https://github.com/Azure/sonic-buildimage/files/5384592/s5232_API_2.0_UT.txt)
[z9264f_API_2.0_UT.txt](https://github.com/Azure/sonic-buildimage/files/5384593/z9264f_API_2.0_UT.txt)

- [ ] 201811
- [ ] 201911
- [ ] 202006

### CODE REVIEW

**Comment by lguohan** [comment]
can you fix the ltgm alerts?

**Comment by aravindmani-1** [comment]
Hi @lguohan ,
The first alarm seems to be false warning. I'm passing correct number of argument only.

10 for Wrong number of arguments in a class instantiation.

- When clicking the values field in lgtm link, it redirects to sfp.py defined for Dell S6000 platform.  
-          root/platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/sfp.py

- When clicking the psu,thermal,component__init__ link redirects to API 2.0 files defined in Mlnx platform 
-         root/platform/mellanox/mlnx-platform-api/sonic_platform/(psu/thermal/component).py.

**Comment by jleveque** [comment]
Yes, this seems to be a bug/limitation of LTGM. With the platform API, we have multiple definitions of each class, provided by each vendor. LGTM generates "Wrong number of arguments in a class instantiation" alerts because when it attempts to find the class definition, it finds a different vendor's implementation, and if they modified the definition, it thinks there is a problem and generates a false alarm. There's not much we can do about this unless LGTM makes their algorithm smarter.

**Comment by aravindmani-1** [comment]
@jleveque , @lguohan fixed the applicable LGTM alerts.
Please let me know if any modification is required.

**Comment by aravindmani-1** [comment]
retest broadcom please

**Comment by aravindmani-1** [comment]
retest broadcom please

**Comment by aravindmani-1** [comment]
retest broadcom please

**Comment by aravindmani-1** [comment]
retest broadcom please

**Comment by aravindmani-1** [comment]
retest mellanox please

**Comment by aravindmani-1** [comment]
retest broadcom please

**Comment by aravindmani-1** [comment]
retest mellanox please

**Review by jleveque — APPROVED** [review]

**Pull request merged**
