### PR TITLE
[platform/ragile] support ra-b6910-64c

### PR DESCRIPTION
**Pull request by pettershao-ragilenetworks**
What I did it
Add new platform x86_64-ragile_ra-b6910-64c-r0 (Tomahawk 3)
ASIC Vendor: Broadcom
Switch ASIC: Tomahawk 3
Port Config: 64x100G

-How I did it
Provide device and platform related files.

-How to verify it
show platform fan
show platform ssdhealth
show platform psustatus
show platform summary
show platform syseeprom
show platform temperature
show interface status

### CODE REVIEW

**Review by jleveque — COMMENTED** [review]
I don't see device/ragile/x86_64-ragile_ra-b6910-64c-r0/custom_led.bin being used anywhere. Should this file be removed?

**Comment by pettershao-ragilenetworks** [comment]
@jleveque fixed, help forward!

**Comment by pettershao-ragilenetworks** [comment]
@jleveque hi, help forward this!

**Comment by pettershao-ragilenetworks** [comment]
@jleveque @lguohan hi, help forward this!

**Comment by pettershao-ragilenetworks** [comment]
@jleveque @lguohan hi, help forward this，thanks!

**Review by sujinmkang — DISMISSED** [review]

**Review by sujinmkang — APPROVED** [review]

**Comment by pettershao-ragilenetworks** [comment]
@yxieca @lguohan help forward this, thanks!

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
@qiluo-msft  for awareness: new platform added.

**Comment by qiluo-msft** [comment]
@yxieca ACK

**Pull request merged**
