### PR TITLE
[docker-sonic-mgmt]: set docker-sonic-mgmt as stretch docker

### PR DESCRIPTION
**Pull request by lguohan**
Signed-off-by: Guohan Lu <lguohan@gmail.com>

**- What I did**

**- How I did it**

**- How to verify it**
build locally.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
fix the build break https://sonic-jenkins.westus2.cloudapp.azure.com/job/bldenv/job/docker-sonic-mgmt/285/

**Comment by yxieca** [comment]
So sonic-mgmt docker is build as both stretch and jessie? Which one will be used?

**Comment by lguohan** [comment]
only stretch is built

**Comment by lguohan** [comment]
only stretch is built

**Pull request merged**
