### PR TITLE
Add build as7716-32xb to platform-modules-accton.mk file

### PR DESCRIPTION
**Pull request by jostar-yang**
**- What I did**
Add build as7716-32xb to platform-modules-accton.mk
**- How I did it**
Add build as7716-32xb to platform-modules-accton.mk
**- How to verify it**
make target/debs/sonic-platform-accton-as7716-32xb_1.1_amd64.deb-clean
make target/debs/sonic-platform-accton-as7716-32xb_1.1_amd64.deb
Make sure there is no compile error.
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by stcheng** [comment]
please check
the build check failed 😢

**Comment by jostar-yang** [comment]
Sorry for forget to check-in onie-image.mk for as7716-32xb. Please help merge new onie-image.mk and build again.

**Comment by lguohan** [comment]
build still fails

**Comment by jostar-yang** [comment]
Please mereg 84fc98c8601d3e5610fcb14e4811467f1c6992bd  for adding as7716-32xb to debian build and fix Makefile

**Comment by lguohan** [comment]
in fact, you can add that commit in this commit, so one commit add this platform, it is better.

**Comment by jostar-yang** [comment]
Sorry. I has send Pull Request. So I need to cancel  "84fc98c "  commit?  And add new files in "#1496"?

**Comment by jostar-yang** [comment]
I just add 3 modified files for add as7716-32xb to debian build and fix Makefile.  This should add to the same commit (#1496)

**Pull request merged**
