### PR TITLE
DellEMC S6000 fancontrol support

### PR DESCRIPTION
**Pull request by paavaanan**
**- What I did**
- Added fancontrol support for DellEMC S6000 platform

**- How I did it**
- Implemented fancontrol service to monitor S6000 fans and adjust fan speed w.r.t temperature.
- fancontrol.service starts the fancontrol script at startup.
- This script takes the average temperature by reading three sensors and configure FANS to appropritate RPM against the temperature. 
- When the temperature is adjusted script will log in syslog for future reference.
- Also, script checks for faulty fans and report the status in syslog. 

**- How to verify it**
- verify fancontrol status by issuing "systemctl status fancontrol" command
- Check syslog for fancontrol like below messages.
```
Jan  3 07:34:55.716486 sonic NOTICE root: Adjusted FAN Speed to 7000 RPM against 29 Temperature
Jan  3 07:34:55.777522 sonic NOTICE root: FanTray3 Fans are Faulty.. 240 240. Please check.
```
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by sujinmkang** [comment]
retest this please

**Comment by lguohan** [comment]
We need this for master. I am not sure we need this in 201811 branch.

**Comment by jleveque** [comment]
Curious: Are you not able to simply provide a config file for the existing fancontrol daemon (example: https://github.com/Azure/sonic-buildimage/blob/master/device/arista/x86_64-arista_7050_qx32/fancontrol)?

**Comment by paavaanan** [comment]
@jleveque - Linux fancontrol script/config files is designed to work only with PWM values. But max6620 (FAN) Linux driver support fancntrol only through RPM values. PWM values are read-only. No read-write support is availlable via PWM in current driver. So, config file and associated scripts are not usable for out case.

**Comment by paavaanan** [comment]
Raised a new Pr for master in #4048

**Pull request closed without merging**
