### PR TITLE
[DELL] S6100 Add PowerCycle Support for Last Reset Reason

### PR DESCRIPTION
**Pull request by sridhar-ravindran**
**- What I did**
Added support to fix power-cycle last reboot cause in S6100
Known Caveat :- If we upgrade old_image (old_image without this fix) to the new_image(with this fix)
If we do a power-cycle instead of fast/warm/cold reset, show reboot-cause will return "Unknown" instead of "power-cycle"
**- How I did it**
Changes Done
modified: files/image_config/process-reboot-cause/process-reboot-cause
modified: files/image_config/platform/rc.local
modified: platform/broadcom/sonic-platform-modules-dell/common/dell_pmc.c
modified: platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/chassis.py
modified: platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh
modified: platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py

rc.local will inform the platform about first boot. Platform Init Script will use the info and update the
logical to return non-hardware in case of first time onie boot/image upgrade.

process-reboot-cause will use the first_boot notification and use it to return Valid last-reset-reason
Currently it will show unkwown which is not correct.
**- How to verify it**
a) power-cycle the box and issue show reboot-cause
b) Onie install the box and check return value of get_reboot_cause api
c) Upgrade the image and check return value of get_reboot_Cause api
**- Description for the changelog**

[DELL] S6100 Support PowerCycle in Last Reboot Reason in 201811 branch

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by sridhar-ravindran** [comment]
[UnitTesting_Final_With_PowerCycle_and_FirstBoot_201811.txt](https://github.com/Azure/sonic-buildimage/files/3568963/UnitTesting_Final_With_PowerCycle_and_FirstBoot_201811.txt)

**Comment by lguohan** [comment]
retest broadcom please

**Comment by sujinmkang** [comment]
There is a regression on S6000 with power reset. The reboot cause gets stuck and no update after all.
Please make sure if this is working on across the platform.

**Comment by sridhar-ravindran** [comment]
Hi sujinmkang, 
Fixed it and uploaded the UT results for S6000.
S6000 does not support powerCycle. Hence it will be Unknown for that.
Subsequent reloads will show proper results.
[S6000_UT_Logs.txt](https://github.com/Azure/sonic-buildimage/files/3578476/S6000_UT_Logs.txt)

Will check again for S6100 and update

**Comment by sridhar-ravindran** [comment]
Hi @sujinmkang 

I verified in S6100 using the same build.
It  is working fine

After APC power-cycle
root@sonic:/home/admin# show reboot-cause
Power Loss


Could you please share the following output from your system after Power-Cycle

```
root@sonic:/home/admin# cat /sys/devices/platform/SMF.512/hwmon/hwmon1/smf_version
root@sonic:/home/admin# cat /sys/devices/platform/SMF.512/hwmon/hwmon1/smf_firmware_ver
root@sonic:/home/admin# cat /sys/devices/platform/SMF.512/hwmon/hwmon1/smf_reset_reason
root@sonic:/home/admin# cat /sys/devices/platform/SMF.512/hwmon/hwmon1/smf_poweron_reason
root@sonic:/home/admin# cat /sys/devices/platform/SMF.512/hwmon/hwmon1/mb_poweron_reason
```

**Comment by sujinmkang** [comment]
Hi @sridhar-ravindran,
It seems the previous reported problems are all resolved but fast-reboot and warm-reboot on S6000 are not working with this Jenkins build.
Can you please double check if your changes on top of latest 201811 branch since those reboot works on latest  build?

**Comment by sridhar-ravindran** [comment]
> Hi @sridhar-ravindran,
> It seems the previous reported problems are all resolved but fast-reboot and warm-reboot on S6000 are not working with this Jenkins build.
> Can you please double check if your changes on top of latest 201811 branch since those reboot works on latest build?

hi @sujinmkang 
Synced to latest 201811 branch. FastBoot and Warmboot are working. Attached the logs.
[201811_fast_warm_boot.txt](https://github.com/Azure/sonic-buildimage/files/3588972/201811_fast_warm_boot.txt)

**Pull request merged**
