### PR TITLE
[Wistron] Add 6512-32r platform support

### PR DESCRIPTION
**Pull request by WistronNetwork**
#### Why I did it

1. Add 6512-32r support for Wistron platform
2. Update sw-to3200k for newer branch

#### How I did it

1. Add code in device and platform folder for 6512-32r
2. Update sw-to3200k code both in device and platform folder

#### How to verify it

Install on Wistron device and run command to verify

Signed-off-by: RogerChang <Roger_Chang@wistron.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [ ] 202106
- [x] 202111

#### Description for the changelog
both verified in 202111 and 202012

#### Link to config_db schema for YANG module changes
N/A

### CODE REVIEW

**Comment by WistronNetwork** [comment]
@prgeor , the 12 alerts all related to __init__ but seems wrong parsing for other platform, would you provide suggestion for this? Thanks.

**Comment by WistronNetwork** [comment]
@prgeor , @lguohan , would you please review our PR, thanks.

**Comment by sujinmkang** [comment]
@WistronNetwork Can you please share the outputs of all platform status check cli commands "show platform *" , "show interfaces *" and other docker status commands?

**Comment by WistronNetwork** [comment]
[6512_32R_sonic_202111.log](https://github.com/Azure/sonic-buildimage/files/8965313/6512_32R_sonic_202111.log)
@sujinmkang Hi, please check uploaded log, thanks.

**Review by sujinmkang — APPROVED** [review]

**Comment by sujinmkang** [comment]
@WistronNetwork I see the full support of the platform is not done yet. Since some cli output doesn't have the proper information.

**Comment by WistronNetwork** [comment]
@sujinmkang Would you please describe more about CLI "not done" part? Sure we will create another PR if any missing, thanks.

**Comment by shihjeff** [comment]
@sujinmkang - what is the process to backport to 202012, 202111 branch?  I don't have permissions to add the "Request for XXX branch" label to the MR.

**Pull request merged**
