### PR TITLE
[Barefoot]: fix unresolved SFP type on Newport/Montara

### PR DESCRIPTION
**Pull request by dmytroxshevchuk**
**- Why I did it**
`show interface status` and `sfpshow eeprom` commands show not correct information about sfp status.
`show interface status` command result:
```
admin@sonic:~$ show interfaces status
  Interface            Lanes    Speed    MTU    FEC        Alias    Vlan    Oper    Admin             Type    Asym PFC
-----------  ---------------  -------  -----  -----  -----------  ------  ------  -------  ---------------  ----------
  Ethernet0          0,1,2,3     100G   9100    N/A    Ethernet0  routed    down       up              N/A         N/A
  Ethernet8        8,9,10,11     100G   9100    N/A    Ethernet8  routed    down       up  QSFP28 or later         N/A
 Ethernet16      16,17,18,19     100G   9100    N/A   Ethernet16  routed    down       up  QSFP28 or later         N/A
 Ethernet24      24,25,26,27     100G   9100    N/A   Ethernet24  routed    down       up  QSFP28 or later         N/A
```
For example `sfpshow eeprom` show something like this:
```
admin@sonic:~$ sfpshow eeprom
Ethernet0: SFP EEPROM Not detected

Ethernet8: SFP EEPROM detected
...
```

Also command `sfpshow presence` show `Not present` for Ethernet0
```
admin@sonic:~$ sfpshow presence
Port         Presence
-----------  -----------
Ethernet0    Not present
Ethernet8    Present
Ethernet16   Present
```

**- How I did it**

**- How to verify it**
After fix must be correct SFP status in `show interface status` command.
Before:
```
admin@sonic:~$ show interfaces status
  Interface            Lanes    Speed    MTU    FEC        Alias    Vlan    Oper    Admin             Type    Asym PFC
-----------  ---------------  -------  -----  -----  -----------  ------  ------  -------  ---------------  ----------
  Ethernet0          0,1,2,3     100G   9100    N/A    Ethernet0  routed    down       up              N/A         N/A
  Ethernet8        8,9,10,11     100G   9100    N/A    Ethernet8  routed    down       up  QSFP28 or later         N/A
 Ethernet16      16,17,18,19     100G   9100    N/A   Ethernet16  routed    down       up  QSFP28 or later         N/A
 Ethernet24      24,25,26,27     100G   9100    N/A   Ethernet24  routed    down       up  QSFP28 or later         N/A
```
After:
```
admin@sonic:~$ show interfaces status
  Interface            Lanes    Speed    MTU    FEC        Alias    Vlan    Oper    Admin             Type    Asym PFC
-----------  ---------------  -------  -----  -----  -----------  ------  ------  -------  ---------------  ----------
  Ethernet0          0,1,2,3     100G   9100    N/A    Ethernet0  routed    down       up  QSFP28 or later         N/A
  Ethernet8        8,9,10,11     100G   9100    N/A    Ethernet8  routed    down       up  QSFP28 or later         N/A
 Ethernet16      16,17,18,19     100G   9100    N/A   Ethernet16  routed    down       up  QSFP28 or later         N/A
 Ethernet24      24,25,26,27     100G   9100    N/A   Ethernet24  routed    down       up  QSFP28 or later         N/A
```
Also must be resolved `sfpshow eeprom` and `sfpshow presence` commands.
```
admin@sonic:~$ sfpshow presence
Port         Presence
-----------  ----------
Ethernet0    Present
Ethernet8    Present
Ethernet16   Present
```

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by akokhan** [comment]
retest vsimage please

**Comment by jleveque** [comment]
@akokhan: Please review.

**Comment by akokhan** [comment]
@vboykox , please take a look

**Review by akokhan — APPROVED** [review]

**Comment by vboykox** [comment]
Approved.

**Review by vboykox — APPROVED** [review]

**Review by vboykox — APPROVED** [review]

**Review by jleveque — APPROVED** [review]

**Comment by jleveque** [comment]
@dmytroxshevchuk: Can you please add a brief description for this PR?

**Comment by dmytroxshevchuk** [comment]
> @dmytroxshevchuk: Can you please add a brief description for this PR?

done, please check

**Pull request merged**
