### PR TITLE
[sonic-platform-common][sonic-platform-daemons][sonic-utilities] Update submodules

### LINKED ISSUE #4716: show ipv6 interfaces command result doesn't conclude neighbor ipv6 address
[version]
SONiC Software Version: SONiC.HEAD.67-8367dfeb
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: 8367dfeb
Build date: Wed May 6 13:49:49 UTC 2020
Built by: johnar@jenkins-worker-7

Platform: x86_64-ruijie_b6510-48vs8cq-r0
HwSKU: B6510-48VS8CQ
ASIC: broadcom
Serial Number: G1MW80H000123
Uptime: 17:39:24 up 21 min, 2 users, load average: 0.76, 0.94, 0.80

[configuration]
[config_db_201911_20200523.txt](https://github.com/Azure/sonic-buildimage/files/4734810/config_db_201911_20200523.txt)

"LCv6": {
"ip_range": [
"2001:49:5:1::1",
"2001:50:5:1::1"
],
"name": "LCv6",
"password": "hello",
"remote_as": "501"
}

[operation & rslt]
root@switch2:/var/core# show ipv6 interface
Interface Master IPv6 address/mask Admin/Oper BGP Neighbor Neighbor IP

Bridge fe80::ace7:b3ff:fe6e:c1c0%Bridge/64 up/up N/A N/A
Ethernet0 PortChannel1 fe80::5a69:6cff:fefb:2230%Ethernet0/64 up/up N/A N/A
Ethernet52 2001:50:5:1::2/64 up/up N/A N/A <- incorrect
fe80::5a69:6cff:fefb:2230%Ethernet52/64
Loopback0 6::6/128 up/up N/A N/A
fe80::709b:ebff:fe3e:b593%Loopback0/64
PortChannel1 Bridge fe80::5a69:6cff:fefb:2230%PortChannel1/64 up/up N/A N/A
Vlan3 150::1/64 up/up N/A N/A
fe80::5a69:6cff:fefb:2230%Vlan3/64
eth0 fe80::5a69:6cff:fefb:2230%eth0/64 up/up N/A N/A
lo ::1/128 up/up N/A N/A
root@switch2:/var/core# show ipv4 interface
Usage: show [OPTIONS] COMMAND [ARGS]...

Error: No such command "ipv4".
root@switch2:/var/core# show ip interface
Interface Master IPv4 address/mask Admin/Oper BGP Neighbor Neighbor IP

Ethernet24 10.0.0.48/31 up/down N/A N/A
Ethernet52 50.5.1.1/31 up/up LC 50.5.1.0
Loopback0 6.6.6.6/32 up/up N/A N/A
Vlan3 150.1.1.1/16 up/up N/A N/A
docker0 240.127.1.1/24 up/down N/A N/A
eth0 172.28.57.33/24 up/up N/A N/A
lo 127.0.0.1/8 up/up N/A N/A
root@switch2:/var/core# show ipv6 bgp summary

IPv6 Unicast Summary:
BGP router identifier 6.6.6.6, local AS number 8005 vrf-id 0
BGP table version 74
RIB entries 5, using 920 bytes of memory
Peers 2, using 41 KiB of memory
Peer groups 2, using 128 bytes of memory

Neighbor V AS MsgRcvd MsgSent TblVer InQ OutQ Up/Down State/PfxRcd
2001:49:5:2::1 4 501 0 0 0 0 0 never Active
2001:50:5:1::1 4 501 48 79 0 0 0 00:03:54 Active

[expection]
"show ipv6 interface" for Ethernet52's Neighbor IP should not be N/A, but 2001:50:5:1::1/64

[log]
[syslog.txt](https://github.com/Azure/sonic-buildimage/files/4734814/syslog.txt)

### PR DESCRIPTION
**Pull request by jleveque**
* src/sonic-platform-common 75698a8...82bbeab (9):
  > [sfputil] Make SfpUtilHelper.get_physical_to_logical noexcept as in SfpUtilBase (#96)
  > [sfp_base] Update return value documentation of channel-specific methods (#98)
  > [sfp] Tweak key names of some transceiver info fields (#97)
  > fix typo:  portconfig.ini to port_config.ini (#94)
  > [chassis_base] Add platform API support for system LED (#91)
  > Add PCIe check commad  (#64)
  > [sfputilbase.py] Don't try to print EEPROM sysfs file name if we failed to read from it (#81)                                                                                    
  > [sfputilbase | sfputilhelper] Add support of platform.json (#72)
  > [eeprom] Add try-except to catch the IOError (#85)

* src/sonic-platform-daemons 0f4fd83...abe115e (2):
  > [xcvrd] Tweak some transceiver info key names (#62)
  > [psud][thermalctld] Always get fan/PSU LED status from platform API to avoid status inconsistencies (#59)                                                                        

* src/sonic-utilities fd7781b...16a33f2 (9):
  > [config] Fix syntax error (#966)
  > [config] Fix indentation level in _get_disabled_services_list() (#965)
  > a4e64d1 [sonic_installer] Refactor sonic_installer code (#953)
  > 90efd62 [Show | Command Reference] Add Port breakout Show Command (#859)
  > [sfpshow][mock_state_db] Tweak key names of some transceiver info fields (#958)
  > [show] Add missing verbose option to "show line" (#961)
  > [filter-fdb] Check VLAN Presence When Filter FDB (#957)
  > [master]fix #4716 show ipv6 interfaces neighbor_ip is N/A issue (#948)
  > Fix for command. show interface transceiver eeprom -d Ethernet (#955)

Note: sonic-utilities update fixes #4716

### CODE REVIEW

**Comment by qiluo-msft** [comment]
* src/sonic-utilities fa19b4c...a4e64d1 (2):
   > a4e64d1 [sonic_installer] Refactor sonic_installer code (#953)
   > 90efd62 [Show | Command Reference] Add Port breakout Show Command (#859)

**Comment by jleveque** [comment]
@qiluo-msft: Thanks for documenting the new commits you pulled in. I have added them to the description.

**Comment by jleveque** [comment]
Converted to draft to wait until https://github.com/Azure/sonic-utilities/pull/965 merges, then I will pull that commit into the sonic-utilities submodule update.

**Comment by qiluo-msft** [comment]
Retest mellanox please

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by qiluo-msft** [comment]
It is okay to merge this when new fixes are not immediately ready.

**Comment by jleveque** [comment]
Advanceds sonic-utilities by two more commits:

* src/sonic-utilities a4e64d1...16a33f2 (2):
  > [config] Fix syntax error (#966)
  > [config] Fix indentation level in _get_disabled_services_list() (#965)

**Comment by jleveque** [comment]
Advanced sonic-platform-common by one more commit:

* src/sonic-platform-common 85edabb...82bbeab (1):
  > [sfputil] Make SfpUtilHelper.get_physical_to_logical noexcept as in SfpUtilBase (#96)

**Comment by jleveque** [comment]
Retest mellanox please

**Pull request merged**
