### PR TITLE
[sonic-swss-common]: Update Submodule

### PR DESCRIPTION
**Pull request by tahmed-dev**
Update in this change:
640a218 [packaging]: Add Support For Libboost v1.71.0 (#449)

signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

**- Why I did it**
Fix build/bugs in sonic-buildimage

**- How I did it**
ported fixes via submodule update

**- How to verify it**
PR check and on target verification

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Could you resolve the conflict?

**Comment by tahmed-dev** [comment]
> Could you resolve the conflict?

just did.

**Comment by qiluo-msft** [comment]
Also change the PR description?

**Review by qiluo-msft — APPROVED** [review]

**Comment by tahmed-dev** [comment]
> Also change the PR description?

**Comment by tahmed-dev** [comment]
> > Also change the PR description?

done

**Comment by tahmed-dev** [comment]
retest this please

**Comment by tahmed-dev** [comment]
retest mellanox please

**Pull request merged**
