### PR TITLE
[sonic-cfggen] fix name conflict between sonic_platform package and sonic_platform.py

### PR DESCRIPTION
**Pull request by keboliu**
**- What I did**
There is a name conflict between a module "sonic_platform.py" which sonic-cfggen is using and the new added "sonic_platform" package form each platform's implementation of new platform API.

This name conflict cause pmon container not able to go up since sonic-cfggen can't load correct "sonic_platform.py".  So rename "sonic_platform.py" to "sonic_device_util.py" as a temporary mitigation to this issue. In the long run, this "sonic_platform.py" will be moved out and shared with multiple applications.

**- How I did it**
rename "sonic_platform.py" to "sonic_device_util.py" and change sonic-cfggen, package setup.py accordingly.

**- How to verify it**

run sonic-cfggen

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by keboliu** [comment]
@jleveque thanks for the heads-up, I created another PR for sonic-utilities repo https://github.com/Azure/sonic-utilities/pull/528.  I searched other repos and they should be clean.

**Comment by jleveque** [comment]
@keboliu: I opted against updating the submodule in this PR as it makes it harder to cherry-pick commits into other branches.

**Comment by keboliu** [comment]
@jleveque I realized that and just reverted.

**Comment by jleveque** [comment]
@keboliu: After discussion with Guohan, we think it is best to continue the old practice of adding the submodule update into any PRs which require it to build sucessfully, even if it makes the cherry-pick more complicated. Can you please update the sonic-utilities submodule here? I will merge this after it passes the PR checks.

**Comment by keboliu** [comment]
@jleveque sure.

**Comment by jleveque** [comment]
Retest this please.

**Comment by jleveque** [comment]
Retest this please.

**Comment by keboliu** [comment]
@jleveque the Broadcom image build failure should irrelevant.

**Pull request merged**
