### PR TITLE
[Mellanox] Add initial support for SN4800 for simulation device

### PR DESCRIPTION
**Pull request by tomer-israel**
#### Why I did it
Add initial support of SN4800 platform for Mellanox ASIC simulation device.
NOTE: This is work in progress and not full support of the platform.

#### How I did it
Add new folders for SN4800 with zero ports based on SN4700 Spectrum-3 switch.

#### How to verify it
Verify basic functionality on a simulator successfully, all dockers were up (with almost identical content of the device files)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by lguohan** [comment]
can you assign cla?

**Comment by tomer-israel** [comment]
this pull request is depended on this pull request:
https://github.com/Azure/sonic-buildimage/pull/7447

thats why we see those errors on build:
cp: cannot stat '../../../device/mellanox/x86_64-mlnx_msn4800_simx-r0/ACS-MSN4800': No such file or directory
cp: cannot stat '../../../device/mellanox/x86_64-mlnx_msn4800_simx-r0/default_sku': No such file or directory
cp: cannot stat '../../../device/mellanox/x86_64-mlnx_msn4800_simx-r0/plugins': No such file or directory

**Review by keboliu — APPROVED** [review]

**Review by jleveque — APPROVED** [review]

**Pull request merged**
