### PR TITLE
[sonic-sairedis][sonic-swss-common] Update submodules

### PR DESCRIPTION
**Pull request by smaheshm**
<- Why I did it
Linker error when compiling with ENABLE_SYNCD_RPC. Fix is in SAI repo.

- How I did it
Moved variable declaration to object file included in librpcserver.a

- How to verify it
compile with 'ENABLE_SYNCD_RPC" flag enabled.

- Description for the changelog

[sonic-sairedis]
```
update submodule to include SAI1.6.1.

[MultiDB] use get API to obtain dbid instead of hardcode value (#618) …
dzhangalibaba

Add synchronous mode to sairedis library (#617) …
kcudnik

[meta] Fix tests to be backward compatible (#619)
kcudnik
```
[sonic-swss-common]
```
EVPN VXLAN DB support (#339) …
srj102
tapashdas

Add modifyRedis flag to consumer table object (#344) …
kcudnik

Fix memory leak in pyext when Selectable is returned to Python (#343) …
pavel-shirshov
```

- A picture of a cute animal (not mandatory but encouraged)

### CODE REVIEW

**Comment by smaheshm** [comment]
Original draft PR is #4708

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
@smaheshm: FYI, I updated the PR title to align with our standard convention.

**Comment by smaheshm** [comment]
retest vsimage please

**Pull request merged**
