### PR TITLE
[sonic_debian_extension] install docker_image_ctl.j2 template in the …

### PR DESCRIPTION
**Pull request by stepanblyschak**
…image templates

Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>

This PR is part of [SONiC Application Extension](https://github.com/stepanblyschak/SONiC/blob/sonic-app-ext-3/doc/sonic-application-extention/sonic-application-extention-hld.md)

**- Why I did it**
SONiC Package Manager will require to auto-generate the start script using that template. For that, we need this template to be recorded in SONiC filesystem.

**- How I did it**
Copy the template in SONiC filesystem during image build.

**- How to verify it**
Build an image and cat /usr/share/sonic/templates/docker_image_ctl.j2.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by rajendra-dendukuri — APPROVED** [review]

**Review by renukamanavalan — APPROVED** [review]

**Comment by renukamanavalan** [comment]
retest vsimage please

**Comment by renukamanavalan** [comment]
retest vsimage please

**Comment by renukamanavalan** [comment]
retest vsimage please.

**Comment by renukamanavalan** [comment]
retest vsimage please

**Comment by yxieca** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
Note: I have restarted the pipelines but the tests are not really restarted. Any way to do so?

**Review by lguohan — APPROVED** [review]

**Pull request merged**
