### PR TITLE
PG buffer profile based on port configuration

### PR DESCRIPTION
**Pull request by andriymoroz-mlnx**
**- What I did**
- updated SONiC start scripts to use new buffer profile config
- unified buffer configs for all Mellanox 27xx platforms
- fixed small minigraph parsing issue (neighbor names)

**- How I did it**
Updated swssconfig.sh in orchagent docker 

**- How to verify it**
After orchagent docker start make sure swss:/etc/swss/config.d/msn27xx.32ports.buffers.json is successfully generated

**- Description for the changelog**
PG buffer profile for Mellanox platform is now generated basing on port configuration (speed and cable)

**- A picture of a cute animal (not mandatory but encouraged)**
```
     / \
    / _ \
   | / \ |
   ||   || _______
   ||   || |\     \
   ||   || ||\     \
   ||   || || \    |
   ||   || ||  \__/
   ||   || ||   ||
    \\_/ \_/ \_//
   /   _     _   \
  /               \
  |    O     O    |
  |   \  ___  /   |
 /     \ \_/ /     \
/  -----  |  -----  \
|     \__/|\__/     |
\       |_|_|       /
 \_____       _____/
       \     /
       |     |
```

### CODE REVIEW

**Comment by andriymoroz-mlnx** [comment]
**This PR advances swss submodule pointer. This will also include the following commits to the swss**:
- Refactor TableConsumable (#291) by qiluo-msft
- Optimize orch performance by pops() (#312) by qiluo-msft
- [github]: Add pull request template (#313) by stcheng
- [switchorch]: Add SwitchOrch to deal with switch attributes changes (#314) by stcheng
- [aclorch]: Refactor doAclTableTask and doAclRuleTask (#318) by sihuihan88

**Comment by stcheng** [comment]
Since this pull request contains more commits that are not related to PG buffer profile. The way you use to verify seems not sufficient. Could you also build an image with all the submodule updates and see if everything works fine as expected? Also, you could check if the PG configurations are generated correctly and successfully configured to the ASIC.

**Comment by stcheng** [comment]
btw, i think you might need to include this commit as well: https://github.com/Azure/sonic-swss/commit/770a8f33c1bff299be683bfc7f8e07a2d65f9ef3

**Comment by andriymoroz-mlnx** [comment]
770a8f3 is mine and counts by default :) I listed all extra

**Comment by andriymoroz-mlnx** [comment]
Built image with the swss and swss-common including all changes from the github - all tests on out testbed passed.

**Comment by stcheng** [comment]
thanks. please give me one extra day before merging this pull request to check the current image status.

**Pull request merged**
