### PR TITLE
Added 40G {300/40/5m} pg lookup profile for 7260 100G SKU

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
Added 40G {300/40/5m} profile for 7260 100G SKU

How I verify:
Manual Verification.

### CODE REVIEW

**Review by neethajohn — APPROVED** [review]

**Review by prsunny — APPROVED** [review]
@neethajohn approved

**Review by prsunny — APPROVED** [review]

**Comment by abdosi** [comment]
@qiluo-msft / @yxieca this is needed for 202012.

**Pull request merged**
