### PR TITLE
Updated sonic-utilities submodule.

### PR DESCRIPTION
**Pull request by nazarii-gnydyn**
**- What I did**

Updated sonic-utilities submodule.
Now it points to the latest commit from 201709 branch.

### CODE REVIEW

**Comment by nazarii-gnydyn** [comment]
@stcheng This still needs work: sonic-buildimage [201709] -> sonic-utilities [master] <77c9f81>. I will update sonic-utilities [201709] with commit <77c9f81> from sonic-utilities [master].

**Comment by stcheng** [comment]
@nazarii-gnydyn thanks.

**Comment by NStetskovych** [comment]
@stcheng PR is ready for merge. Could you merge this one?

**Comment by nazarii-gnydyn** [comment]
@stcheng Please have a look at this PR. It is ready for merge. If you have some concerns regarding this, please let me know.

**Comment by NStetskovych** [comment]
@lguohan this PR point to the commit in 201709 branch in sonic-utilities submodule.

**Pull request closed without merging**
