### PR TITLE
[Mellanox] [202106] remove 2x40G and 4x40G breakout modes due to no hardware support

### PR DESCRIPTION
**Pull request by dgsudharsan**
#### Why I did it
Manual cherry-pick of https://github.com/Azure/sonic-buildimage/pull/8280
Mellanox platforms do not support 2x40G or 4x40G breakout modes.

#### How I did it
Removed these breakout modes from platform.json and hwsku.json files

#### How to verify it
Run show interface breakout and verify no 2x40G or 4x40G modes are shown in the supported breakout modes.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by alexrallen — APPROVED** [review]
All the changes here look good. Assuming no SKUs were removed from 202106 to master this should be correct.

**Review by liat-grozovik — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@judyjoseph Can you please review and merge the changes?

**Pull request merged**
