### PR TITLE
[docker-syncd-cavm]: Properly manage syncd with supervisord

### PR DESCRIPTION
**Pull request by jleveque**
This allows supervisord to log syncd exit events to syslog.

### CODE REVIEW

**Comment by jleveque** [comment]
@NStetskovych: Can you please review and test this PR? Thanks.

**Comment by NStetskovych** [comment]
@jleveque tested -all main services started.
admin@sonic:~$ ps -ax | grep "orchagent -m\|portsyncd\|intfsyncd\|neighsyncd\|syncd -p\|/usr/bin/redis-server"
 1424 pts/0    Sl     0:02 /usr/bin/redis-server 127.0.0.1:6379       
 6325 pts/8    Sl     0:08 syncd -p /etc/ssw/AS7512/profile.ini -N
 6390 pts/7    Sl     0:00 orchagent -m cc:37:ab:d4:48:40
 6391 pts/7    Sl     0:00 portsyncd -p /usr/share/sonic/hwsku/port_config.ini
 6392 pts/7    Sl     0:00 intfsyncd
 6393 pts/7    Sl     0:00 neighsyncd
 8182 pts/9    S+     0:00 grep orchagent -m\|portsyncd\|intfsyncd\|neighsyncd\|syncd -p\|/usr/bin/redis-server
The only thing here that I plan to use sai.profile from device directory. Now it looks a little bit duplicated to put syncd init script in each docker.

**Comment by jleveque** [comment]
@NStetskovych: I agree that you should use the sai.profile from the device directory. Doing so should also remove the need for you to use a custom syncd init script. You should instead be able to directly use the init script at https://github.com/Azure/sonic-sairedis/blob/master/debian/syncd.init, as other vendors currently are. This will also allow me to create a more universal solution for creating these supervisord start scripts for syncd. I should be able to reuse code between the systemd init script and the supervisord start script.

**Comment by NStetskovych** [comment]
@jleveque https://github.com/Azure/sonic-sairedis/blob/master/debian/syncd.init already has support  for cavium. I need only remove profile.ini from docker file. But now it looks like I should duplicate syncd.init(syncd.sh ).
Please, let me know your father action regarding universal solution. I will add commit to this branch that remove profile.ini from syncd docker.

**Comment by jleveque** [comment]
@NStetskovych: I am working on a new PR to replace this one which will use syncd.init for all vendors, including Cavium. I will create it so that it uses the old sai profile location. That way you can test that it works with the current configuration, then after it gets merged, you can submit a PR to use the proper sai.profile.

**Comment by jleveque** [comment]
Closing in favor of PR https://github.com/Azure/sonic-buildimage/pull/617.

**Pull request closed without merging**
