### PR TITLE
[BCM SAI] update BCM SAI to 4.2.1.5

### PR DESCRIPTION
**Pull request by smaheshm**
**- Why I did it**

Update BCM SAI release to 4.2.1.5

**- How I did it**

Updated the link to BCM SAI debian package.

**- How to verify it**

```
admin@str-s6000-acs-8:~$ show version

SONiC Software Version: SONiC.master.487-a98cf221
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: a98cf221
Build date: Thu Nov 12 12:21:45 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-dell_s6000_s1220-r0
HwSKU: Force10-S6000
ASIC: broadcom
Serial Number: 1QBRX42
Uptime: 05:46:28 up 3 min,  1 user,  load average: 6.62, 4.26, 1.81

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-snmp                   latest                568cb21eda49        458MB
docker-snmp                   master.487-a98cf221   568cb21eda49        458MB
docker-teamd                  latest                1422216bcfe8        454MB
docker-teamd                  master.487-a98cf221   1422216bcfe8        454MB
docker-sonic-mgmt-framework   latest                bb46790ef1e3        582MB
docker-sonic-mgmt-framework   master.487-a98cf221   bb46790ef1e3        582MB
docker-router-advertiser      latest                67413229aa0b        421MB
docker-router-advertiser      master.487-a98cf221   67413229aa0b        421MB
docker-platform-monitor       latest                3b2792be9884        532MB
docker-platform-monitor       master.487-a98cf221   3b2792be9884        532MB
docker-lldp                   latest                ebb46d49ccfd        485MB
docker-lldp                   master.487-a98cf221   ebb46d49ccfd        485MB
docker-dhcp-relay             latest                fa31612ad91e        428MB
docker-dhcp-relay             master.487-a98cf221   fa31612ad91e        428MB
docker-database               latest                4d8f58a8b2de        421MB
docker-database               master.487-a98cf221   4d8f58a8b2de        421MB
docker-orchagent              latest                ec379c9a72ad        468MB
docker-orchagent              master.487-a98cf221   ec379c9a72ad        468MB
docker-nat                    latest                a55340900bb3        457MB
docker-nat                    master.487-a98cf221   a55340900bb3        457MB
docker-sonic-telemetry        latest                c5fb11b655f4        491MB
docker-sonic-telemetry        master.487-a98cf221   c5fb11b655f4        491MB
docker-fpm-frr                latest                3d4adad06659        471MB
docker-fpm-frr                master.487-a98cf221   3d4adad06659        471MB
docker-sflow                  latest                8062f1a22846        455MB
docker-sflow                  master.487-a98cf221   8062f1a22846        455MB
docker-syncd-brcm             latest                7913ac552c9d        527MB
docker-syncd-brcm             master.487-a98cf221   7913ac552c9d        527MB

admin@str-s6000-acs-8:~$ bcmcmd version
version
Broadcom Command Monitor: Copyright (c) 1998-2020 Broadcom
Release: sdk-6.5.19 built 20201118 (Wed Nov 18 02:57:57 2020)
From sonicbld@00f6fd7d7172:/var/sonicbld/workspace/Build/broadcom/broadcom_sai/20-sai-build-brcm-4.2.1.5/output/x86-xgs5-deb80/hsdk
Platform: X86
OS: Unix (Posix)
Chips:
      
      
      
      
      
      
      
      
       BCM56640_A0,
       BCM56850_A0,
       BCM56340_A0,
       BCM56960_A0, BCM56860_A0,
      
      
      
      
      
       BCM56970_A0, BCM56870_A0,
       BCM56980_A0, BCM56980_B0,
       BCM56370_A0,
       BCM56770_A0,
PHYs:  BCM5400, BCM54182, BCM54185, BCM54180,
    BCM54140, BCM54192, BCM54195, BCM54190,
    BCM54194, BCM54210, BCM54220, BCM54280,
    BCM54282, BCM54240, BCM54285, BCM5428X,
    BCM54290, BCM54292, BCM54294, BCM54295,
    BCM54296, BCM56160-GPHY, BCM53540-GPHY, BCM8750,
    BCM8752, BCM8754, BCM84740, BCM84164,
    BCM84758, BCM84780, BCM84784, BCM84318,
    BCM84328, Sesto, BCM82780, copper sfp
   
drivshell>




admin@str-s6000-acs-8:~$ show ip bgp summary

IPv4 Unicast Summary:
BGP router identifier 10.1.0.32, local AS number 65100 vrf-id 0
BGP table version 8020
RIB entries 12753, using 2346552 bytes of memory
Peers 24, using 502080 KiB of memory
Peer groups 2, using 128 bytes of memory


Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down    State/PfxRcd    NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.0.1       4  65200       3239       3750         0      0       0  00:02:30   6370            ARISTA01T2
10.0.0.5       4  65200       3228       3231         0      0       0  00:01:59   6368            ARISTA03T2
10.0.0.9       4  65200       3239       3750         0      0       0  00:02:29   6370            ARISTA05T2
10.0.0.13      4  65200       3239       3750         0      0       0  00:02:29   6370            ARISTA07T2
10.0.0.17      4  65200       3239       3748         0      0       0  00:02:29   6370            ARISTA09T2
10.0.0.21      4  65200       3225       3227         0      0       0  00:01:48   6368            ARISTA11T2
10.0.0.25      4  65200       3238       3750         0      0       0  00:02:29   6368            ARISTA13T2
10.0.0.29      4  65200       3238       3750         0      0       0  00:02:29   6368            ARISTA15T2
10.0.0.33      4  64001          0          0         0      0       0  never      Active          ARISTA01T0
10.0.0.35      4  64002          0          0         0      0       0  never      Active          ARISTA02T0
10.0.0.37      4  64003          0          0         0      0       0  never      Active          ARISTA03T0
10.0.0.39      4  64004          0          0         0      0       0  never      Active          ARISTA04T0
10.0.0.41      4  64005          0          0         0      0       0  never      Active          ARISTA05T0
10.0.0.43      4  64006          0          0         0      0       0  never      Active          ARISTA06T0
10.0.0.45      4  64007          0          0         0      0       0  never      Active          ARISTA07T0
10.0.0.47      4  64008          0          0         0      0       0  never      Active          ARISTA08T0
10.0.0.49      4  64009          0          0         0      0       0  never      Active          ARISTA09T0
10.0.0.51      4  64010          0          0         0      0       0  never      Active          ARISTA10T0
10.0.0.53      4  64011          0          0         0      0       0  never      Active          ARISTA11T0
10.0.0.55      4  64012          0          0         0      0       0  never      Active          ARISTA12T0
10.0.0.57      4  64013          0          0         0      0       0  never      Active          ARISTA13T0
10.0.0.59      4  64014          0          0         0      0       0  never      Active          ARISTA14T0
10.0.0.61      4  64015          0          0         0      0       0  never      Active          ARISTA15T0
10.0.0.63      4  64016          0          0         0      0       0  never      Active          ARISTA16T0

Total number of neighbors 24
admin@str-s6000-acs-8:~$ docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
3830a3e08026        docker-snmp:latest                   "/usr/bin/supervisord"   5 days ago          Up About a minute                       snmp
97a5ae654f75        docker-sonic-mgmt-framework:latest   "/usr/bin/supervisord"   5 days ago          Up About a minute                       mgmt-framework
5cf8387ecf56        docker-router-advertiser:latest      "/usr/bin/docker-ini…"   5 days ago          Up 4 minutes                            radv
8dcd6f0fcb9a        docker-lldp:latest                   "/usr/bin/docker-lld…"   5 days ago          Up 4 minutes                            lldp
36f35b42bd9a        docker-dhcp-relay:latest             "/usr/bin/docker_ini…"   5 days ago          Up 4 minutes                            dhcp_relay
3dbbf6b3e436        docker-syncd-brcm:latest             "/usr/bin/supervisord"   5 days ago          Up 4 minutes                            syncd
9ca95b1a2979        docker-teamd:latest                  "/usr/bin/supervisord"   5 days ago          Up 4 minutes                            teamd
738c33a7033e        docker-orchagent:latest              "/usr/bin/docker-ini…"   5 days ago          Up 4 minutes                            swss
a8531cb4f927        docker-fpm-frr:latest                "/usr/bin/docker_ini…"   5 days ago          Up 4 minutes                            bgp
b1cf709c5f49        docker-platform-monitor:latest       "/usr/bin/docker_ini…"   5 days ago          Up 4 minutes                            pmon
84375c386a04        docker-database:latest               "/usr/local/bin/dock…"   5 days ago          Up 4 minutes                            database



admin@str-s6000-acs-8:~$ show arp
Address     MacAddress         Iface            Vlan
----------  -----------------  ---------------  ------
10.0.0.1    52:54:00:c9:7a:2e  PortChannel0002  -
10.0.0.5    52:54:00:34:6f:96  PortChannel0005  -
10.0.0.9    52:54:00:43:84:05  PortChannel0008  -
10.0.0.13   52:54:00:20:9c:79  PortChannel0011  -
10.0.0.17   52:54:00:db:95:02  PortChannel0014  -
10.0.0.21   52:54:00:7c:6d:e2  PortChannel0017  -
10.0.0.25   52:54:00:eb:15:f5  PortChannel0020  -
10.0.0.29   52:54:00:60:05:87  PortChannel0023  -
10.3.146.1  00:00:5e:00:01:64  eth0             -
Total number of entries 9 
admin@str-s6000-acs-8:~$ ping 10.0.0.9
PING 10.0.0.9 (10.0.0.9) 56(84) bytes of data.
64 bytes from 10.0.0.9: icmp_seq=1 ttl=64 time=14.2 ms
64 bytes from 10.0.0.9: icmp_seq=2 ttl=64 time=14.0 ms
^C
--- 10.0.0.9 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 2ms
rtt min/avg/max/mdev = 14.006/14.110/14.215/0.158 ms

admin@str-s6000-acs-8:~$ sudo grep -w CRIT /var/log/syslog | grep -v http_server | grep -v "Set uid to user"
admin@str-s6000-acs-8:~$ 

admin@str-s6000-acs-8:~$ show ip route 
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
       T - Table, v - VNC, V - VNC-Direct, A - Babel, D - SHARP,
       F - PBR, f - OpenFabric,
       > - selected route, * - FIB route, q - queued route, r - rejected route

B>* 0.0.0.0/0 [20/0] via 10.0.0.1, PortChannel0002, 00:03:39
  *                  via 10.0.0.5, PortChannel0005, 00:03:39
  *                  via 10.0.0.9, PortChannel0008, 00:03:39
  *                  via 10.0.0.13, PortChannel0011, 00:03:39
  *                  via 10.0.0.17, PortChannel0014, 00:03:39
  *                  via 10.0.0.21, PortChannel0017, 00:03:39
  *                  via 10.0.0.25, PortChannel0020, 00:03:39
  *                  via 10.0.0.29, PortChannel0023, 00:03:39
C>* 10.0.0.0/31 is directly connected, PortChannel0002, 00:04:21
C>* 10.0.0.4/31 is directly connected, PortChannel0005, 00:04:21
C>* 10.0.0.8/31 is directly connected, PortChannel0008, 00:04:21
C>* 10.0.0.12/31 is directly connected, PortChannel0011, 00:04:21
C>* 10.0.0.16/31 is directly connected, PortChannel0014, 00:04:21
C>* 10.0.0.20/31 is directly connected, PortChannel0017, 00:04:21
C>* 10.0.0.24/31 is directly connected, PortChannel0020, 00:04:21
C>* 10.0.0.28/31 is directly connected, PortChannel0023, 00:04:21
C>* 10.0.0.32/31 is directly connected, Ethernet64, 00:04:23
C>* 10.0.0.34/31 is directly connected, Ethernet68, 00:04:23
C>* 10.0.0.36/31 is directly connected, Ethernet72, 00:04:23
C>* 10.0.0.38/31 is directly connected, Ethernet76, 00:04:23
C>* 10.0.0.40/31 is directly connected, Ethernet80, 00:04:23
C>* 10.0.0.42/31 is directly connected, Ethernet84, 00:04:23
C>* 10.0.0.44/31 is directly connected, Ethernet88, 00:04:23
C>* 10.0.0.46/31 is directly connected, Ethernet92, 00:04:23
C>* 10.0.0.48/31 is directly connected, Ethernet96, 00:04:23
C>* 10.0.0.50/31 is directly connected, Ethernet100, 00:04:23
C>* 10.0.0.52/31 is directly connected, Ethernet104, 00:04:23
C>* 10.0.0.54/31 is directly connected, Ethernet108, 00:04:23
C>* 10.0.0.56/31 is directly connected, Ethernet112, 00:04:23
C>* 10.0.0.58/31 is directly connected, Ethernet116, 00:04:23
C>* 10.0.0.60/31 is directly connected, Ethernet120, 00:04:23
C>* 10.0.0.62/31 is directly connected, Ethernet124, 00:04:23
C>* 10.1.0.32/32 is directly connected, Loopback0, 00:05:04
C>* 10.3.146.0/23 is directly connected, eth0, 00:05:59
B>* 100.1.0.1/32 [20/0] via 10.0.0.1, PortChannel0002, 00:04:20
B>* 100.1.0.3/32 [20/0] via 10.0.0.5, PortChannel0005, 00:03:50
B>* 100.1.0.5/32 [20/0] via 10.0.0.9, PortChannel0008, 00:04:20
B>* 100.1.0.7/32 [20/0] via 10.0.0.13, PortChannel0011, 00:04:20
B>* 100.1.0.9/32 [20/0] via 10.0.0.17, PortChannel0014, 00:04:20
B>* 100.1.0.11/32 [20/0] via 10.0.0.21, PortChannel0017, 00:03:39
B>* 100.1.0.13/32 [20/0] via 10.0.0.25, PortChannel0020, 00:04:20
B>* 100.1.0.15/32 [20/0] via 10.0.0.29, PortChannel0023, 00:04:20
B>* 192.168.128.0/25 [20/0] via 10.0.0.1, PortChannel0002, 00:03:39
  *                         via 10.0.0.5, PortChannel0005, 00:03:39
  *                         via 10.0.0.9, PortChannel0008, 00:03:39
  *                         via 10.0.0.13, PortChannel0011, 00:03:39
  *                         via 10.0.0.17, PortChannel0014, 00:03:39
  *                         via 10.0.0.21, PortChannel0017, 00:03:39
  *                         via 10.0.0.25, PortChannel0020, 00:03:39
```

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

This release includes changes for supporting Debian Buster, fixes for internally found issues and more enhancement related to spec coverage and feature parity for Broadcom ASICs. 

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by smaheshm** [comment]
@prsunny FYI. There's a crash in syncd. Opened a CSP with BRCM.

```
Nov  9 22:33:43.550843 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_switch_assert:529 ERROR: Assertion failed: (block == SOC_CORE_ALL) at /var/sonicbld/workspace/Build/broadcom/broadcom_sai/20-sai-build-brcm-4.2.1.5/output/x86-xgs5-deb80/hsdk/src/soc/common/reg.c:6056
Nov  9 22:33:43.586550 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1103 Obtained 20 stack frames.
Nov  9 22:33:43.586550 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1106 /usr/lib/libsai.so.1(_brcm_sai_log_backtrace+0x1e) [0x7f6490d7e84e]
Nov  9 22:33:43.586550 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1106 /usr/lib/libsai.so.1(_brcm_sai_switch_assert+0x2d) [0x7f6490c6215d]
Nov  9 22:33:43.586550 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1106 /usr/lib/libsai.so.1(soc_reg_xaddr_get+0xc00) [0x7f6491fb1710]
Nov  9 22:33:43.586550 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1106 /usr/lib/libsai.so.1(soc_reg_addr_get+0x13) [0x7f6491fb5063]
Nov  9 22:33:43.586550 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1106 /usr/lib/libsai.so.1(soc_reg32_get+0xe7) [0x7f6491fb7a37]
Nov  9 22:33:43.586550 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1106 /usr/lib/libsai.so.1(soc_trident2_port_lanes_get+0xe7) [0x7f64913d0147]
Nov  9 22:33:43.586701 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1106 /usr/lib/libsai.so.1(bcm_esw_port_control_get+0x6e56) [0x7f6491144266]
Nov  9 22:33:43.586701 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1106 /usr/lib/libsai.so.1(bcm_port_control_get+0x3c) [0x7f649234fc3c]
Nov  9 22:33:43.586753 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1106 /usr/lib/libsai.so.1(_brcm_get_hardware_lane_count+0xcc) [0x7f6490d50edc]
Nov  9 22:33:43.587392 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1106 /usr/lib/libsai.so.1(+0x24451e0) [0x7f6490d4e1e0]
Nov  9 22:33:43.588113 str-s6000-acs-9 CRIT syncd#syncd: [0] SAI_API_SWITCH:_brcm_sai_log_backtrace:1106 /usr/bin/syncd(+0x92281) [0x55bac77d0281]
```

**Comment by smaheshm** [comment]
Includes fixes for:

CS00011465498 - Warm reboot
CS00011465061 - interfaces not coming up
CS00011396506 - nexthop resource leak
CS00011452080 - BCM SAI crash while getting lane count

**Comment by rlhui** [comment]
Why 4.2.1.5-4? Should we just name it 4.2.1.5-1, where -1 is the first patch on top of 4.2.1.5 containing multiple fixes.

**Review by gechiang — APPROVED** [review]

**Comment by smaheshm** [comment]
> Why 4.2.1.5-4? Should we just name it 4.2.1.5-1, where -1 is the first patch on top of 4.2.1.5 containing multiple fixes.

There are 4 separate patches applied separately, I built 4 debian pkgs and named them accordingly to avoid mix up.

**Pull request merged**
