### PR TITLE
Enable SAI thrift for Mellanox platform

### PR DESCRIPTION
**Pull request by andrii-savka**
**- What I did**
Enable SAI thrift in RPC image for Mellanox platform

**- How I did it**
Changed MLNX platforms related makefiles to enable SAI thrift

**- How to verify it**
Build and check if syncd process has a "-r" and "-m" flags. 
Check the SAI thrift listening socket. 

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
Hi Andrii,

I've pushed my changes enabling building the libsaithrift-dev library in the following PR: https://github.com/Azure/sonic-buildimage/pull/1296

**Comment by lguohan** [comment]
retest this please

**Comment by andrii-savka** [comment]
Retested and updated based on #1296

**Comment by lguohan** [comment]
added for all platforms, no longer needed for this pr.

**Pull request closed without merging**
