### PR TITLE
[Submodule update]: Update swss-common

### PR DESCRIPTION
**Pull request by pavel-shirshov**

### CODE REVIEW

**Comment by stcheng** [comment]
where is this commit in the sonic-swss-common repository?

**Comment by pavel-shirshov** [comment]
https://github.com/Azure/sonic-swss-common/commit/96018b55e29a31ff22c50db30843d98eff847c35

Do you mean we should use v1.0.1 branch in sonic-swss-common?

**Comment by lguohan** [comment]
1.0.3-squash branch?

**Comment by pavel-shirshov** [comment]
ok

**Pull request closed without merging**
