### PR TITLE
[submodule][202012] Update sonic-sairedis submodule

### PR DESCRIPTION
**Pull request by kcudnik**
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@kcudnik could you please fix conflicts so we can have the above merged?

**Comment by liat-grozovik** [comment]
@kcudnik could you please check if this submodule update is still needed and if so resolve conflicts?

**Comment by liat-grozovik** [comment]
> if there are conflicts here, then probably this PR is already obsoleted and submodule was moved forward

OK, so can you check and see if we are missing something in 202012 and if not, just close it?

**Comment by kcudnik** [comment]
yes, this is obsoleted:
```
* 1027eef [202012] Prevent other notification event storms to keep enqueue unchecked and drained all memory that leads to crashing the switch router (#976)
* 94455e5 Add cisco-8000 checks to syncd_init_common (#839)
* 2df5394 [lgtm] Add gmock libs to lgtm (#979)
* 7389704 [202012] Add ACL_TABLE object to break before make list (#971)
* f334349 Fix hung issue when installing linux kernel modules (#969)
* 07e1f79 [syncd] Add workaround for warm boot new objects (#959)
* 50fd353 Fix the option missing in kernel config issue (#956)
* e77503c [syncd] Comparison logic workaround for empty buffer profile (#906) (#941)
```

those are changes that are included now in 202012 branch on buildimage from sonic-sairedis, and this change was for 
```
* e77503c [syncd] Comparison logic workaround for empty buffer profile (#906) (#941)
```

**Pull request closed without merging**
