### PR TITLE
[platform-celestica]: Add new fancontrol service for haliburton device

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- What I did**
-  Upgrade fancontrol daemon of Haliburton device to support the temperature hysteresis and difference config for each unit fan direction type (B2F/F2B)

**- How I did it**
- Add fancontrol config file "[fancontrol-F2B](https://github.com/Azure/sonic-buildimage/compare/master...celestica-Inc:master-e1031-new-fsc?expand=1#diff-b245b600c3566b3bbad96de0f40e8b37)" for  F2B unit
- Add fancontrol config file "[fancontrol-B2F](https://github.com/Azure/sonic-buildimage/compare/master...celestica-Inc:master-e1031-new-fsc?expand=1#diff-72fc8250294cec1811a198b9d6928d3d)" for  B2F unit
- Add "[fancontrol.sh](https://github.com/Azure/sonic-buildimage/compare/master...celestica-Inc:master-e1031-new-fsc?expand=1#diff-15da393b0a1ba1f352d9dd9d9e10bd70)" and  "[fancontrol.service](https://github.com/Azure/sonic-buildimage/compare/master...celestica-Inc:master-e1031-new-fsc?expand=1#diff-8341977147680bf77a63103d752e54a6)" to control fancontrol daemon
- Add "[fancontrol](https://github.com/Azure/sonic-buildimage/compare/master...celestica-Inc:master-e1031-new-fsc?expand=1#diff-480cfc7d7305ff9294fa823f4125a364)" to be the fancontrol daemon

**- How to verify it**
- Run thermal test 

Signed-off-by: Wirut Getbamrung wgetbumr@celestica.com

### CODE REVIEW

**Comment by renukamanavalan** [comment]
Can you please post the results and as well the command to run the tests?

**Comment by mudsut4ke** [comment]
@renukamanavalan 

For fan speed control validation test, thermal test ambient range from 20C–45C–20C to complete 1 cycle, 5C each step, waiting the temperature reach stable state and change to next step, record all fan speed data from `sensors` command in the duration. 

**Result**: Fan speed curve based on FSC algorithm (F2B)

F2B

**Result**: Fan speed curve based on FSC algorithm (B2F)

B2F

**Conclution**: The actual fan speed curve match fan speed control algorithm setting and all components temperature is under the required operating conditions.

**Comment by renukamanavalan** [comment]
Is there a automated way to test this script ?

Reason: We would like to test this locally, when we get the updated image

**Comment by mudsut4ke** [comment]
@renukamanavalan , In this version we didn't prepare the way for automate test, 
We just record fan speed during thermal change on test chamber.

**Pull request merged**
