### PR TITLE
[celestica/silverstone]: Update platform driver and platform APIs

### PR DESCRIPTION
**Pull request by mudsut4ke**
#### Why I did it
- Platform driver and APIs must support F2B and B2F SKUs 
- Platform APIs must passed all test cases in the SONIC Platform Testing Framework.

#### How I did it
- Update platform driver to support latest firmware
- Update Platform APIs to follow latest spec and fixes failed test cases
- Update Silverstone Switch configuration

#### How to verify it
- Run platform test on testbed

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [x] 202106

### CODE REVIEW

**Comment by sujinmkang** [comment]
@mudsut4ke Can you please share the output of `show platform` & `show interface` commands and sonic-mgmt platform api test result?

**Comment by sujinmkang** [comment]
@mudsut4ke Can you also check the build failure?

**Comment by mudsut4ke** [comment]
> @mudsut4ke Can you also check the build failure?

@sujinmkang , The error is caused by the driver file not supporting kernel 5.10 in the master branch.
Since in the code on local repo is based on the 202012 branch that using kernel version 4.19

Can I make a new PR to 202012 branch directly ?

**Comment by sujinmkang** [comment]
@mudsut4ke Yes, please open a new PR against your expected branch. Do you also plan to have a new PR  to support for master branch, kernel 5.0?

**Comment by mudsut4ke** [comment]
> @mudsut4ke Yes, please open a new PR against your expected branch. Do you also plan to have a new PR to support for master branch, kernel 5.0?

@sujinmkang , Yes, I will close this PR first
And here is a new PR https://github.com/Azure/sonic-buildimage/pull/9911 for 202012 branch

**Pull request closed without merging**
