### PR TITLE
[device/celestica]: Update psuutil follow new platform API

### LINKED ISSUE #3518: [Celestica DX010] "show platform psustatus" failure
admin@sonic:~$ show version 

```
SONiC Software Version: SONiC.HEAD.152-c74822a
Distribution: Debian 9.11
Kernel: 4.9.0-9-amd64
Build commit: c74822a
Build date: Tue Sep 24 01:08:36 UTC 2019
Built by: johnar@jenkins-worker-3

Platform: x86_64-cel_seastone-r0
HwSKU: Seastone-DX010-25-50
ASIC: broadcom
Serial Number: DX010B2F016304LI000036
Uptime: 05:43:33 up 7 min,  1 user,  load average: 0.90, 0.74, 0.41

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.152-c74822a    a1978c17489b        369MB
docker-syncd-brcm          latest              a1978c17489b        369MB
docker-orchagent-brcm      HEAD.152-c74822a    3b5b6516b879        288MB
docker-orchagent-brcm      latest              3b5b6516b879        288MB
docker-lldp-sv2            HEAD.152-c74822a    8d872df696d0        276MB
docker-lldp-sv2            latest              8d872df696d0        276MB
docker-dhcp-relay          HEAD.152-c74822a    91573246e277        260MB
docker-dhcp-relay          latest              91573246e277        260MB
docker-database            HEAD.152-c74822a    dc1b9bcd3496        257MB
docker-database            latest              dc1b9bcd3496        257MB
docker-teamd               HEAD.152-c74822a    7856527a1682        276MB
docker-teamd               latest              7856527a1682        276MB
docker-snmp-sv2            HEAD.152-c74822a    84fdac980e40        293MB
docker-snmp-sv2            latest              84fdac980e40        293MB
docker-router-advertiser   HEAD.152-c74822a    1075f07bbb04        256MB
docker-router-advertiser   latest              1075f07bbb04        256MB
docker-platform-monitor    HEAD.152-c74822a    f41860432c3e        289MB
docker-platform-monitor    latest              f41860432c3e        289MB
docker-fpm-quagga          HEAD.152-c74822a    1c2c116750d7        283MB
docker-fpm-quagga          latest              1c2c116750d7        283MB

admin@sonic:~$ 
admin@sonic:~$ 
admin@sonic:~$ 
admin@sonic:~$ ls /sys/class/gpio/
export  gpio422  gpio423  gpio424  gpio425  gpio426  gpio434  gpio437  gpio439  gpio440  gpio441  gpio442  gpio443  gpio444  gpio445  gpio446  gpio447  gpio448  gpio449  gpio450  gpiochip412  gpiochip452  unexport
admin@sonic:~$ ls -l /sys/class/gpio/
total 0
--w------- 1 root root 4096 Sep 26 05:36 export
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio422 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio422
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio423 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio423
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio424 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio424
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio425 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio425
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio426 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio426
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio434 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio434
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio437 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio437
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio439 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio439
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio440 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio440
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio441 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio441
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio442 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio442
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio443 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio443
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio444 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio444
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio445 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio445
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio446 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio446
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio447 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio447
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio448 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio448
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio449 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio449
lrwxrwxrwx 1 root root    0 Sep 26 05:43 gpio450 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpiochip1/gpio/gpio450
lrwxrwxrwx 1 root root    0 Sep 26 05:36 gpiochip412 -> ../../devices/pci0000:00/0000:00:13.0/i2c-0/i2c-17/17-0020/gpio/gpiochip412
lrwxrwxrwx 1 root root    0 Sep 26 05:36 gpiochip452 -> ../../devices/pci0000:00/0000:00:1f.0/gpio_ich.1.auto/gpio/gpiochip452
--w------- 1 root root 4096 Sep 26 05:35 unexport
admin@sonic:~$ 
admin@sonic:~$ 
admin@sonic:~$ show platform psustatus 
Traceback (most recent call last):
  File "/usr/bin/psuutil", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'psuutil')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/psuutil/main.py", line 176, in status
    presence = platform_psuutil.get_psu_presence(psu)
  File "/usr/share/sonic/device/x86_64-cel_seastone-r0/plugins/psuutil.py", line 85, in get_psu_presence
    psu_absence = self.read_psu_statuses(self.psu[index]['abs'])
  File "/usr/share/sonic/device/x86_64-cel_seastone-r0/plugins/psuutil.py", line 47, in read_psu_statuses
    raise IOError("Unable to open " + gpio_file + "file !")
IOError: Unable to open /sys/class/gpio/gpio479/valuefile !
```

This is from 201811 github prebuilt binary:
https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-201811/152/artifact/target/sonic-broadcom.bin

The issue happens on master too. please check the serial number for more HW information. 

As you can probably see, "gpiochip452" was the one screwed up the PSU gpio base.

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- What I did**

- Fixes #3518 

**- How I did it**
- Update psuutil API to detect PSU GPIO base from label

**- How to verify it**
- run command `show platform psustatus`
```
admin@sonic:~$ show platform psustatus
PSU    Status
-----  --------
PSU 1  OK
PSU 2  OK
admin@sonic:~$ 
```

### CODE REVIEW

**Comment by mudsut4ke** [comment]
retest vsimage please

**Comment by zhenggen-xu** [comment]
@jleveque can you add label for "request_for_201811"?

**Comment by jleveque** [comment]
Retest this please

**Comment by mudsut4ke** [comment]
retest vsimage please

**Comment by mudsut4ke** [comment]
retest vs please

**Pull request merged**
