### PR TITLE
[sonic-utilities]: Update submodule

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>

**- What I did**
Updated ```sonic-utilities``` submodule
**- How I did it**
Updated ```sonic-utilities``` submodule
**- How to verify it**
Deploy new SONiC image and verify that all is up and running
**- Description for the changelog**
[sonic-utilities]: Update submodule

### CODE REVIEW

**Comment by volodymyrsamotiy** [comment]
retest this please

**Comment by volodymyrsamotiy** [comment]
retest this please

**Comment by yxieca** [comment]
retest this please

**Comment by rlhui** [comment]
@mlok-nokia , this was a super old PR, why it's added here now?

**Pull request merged**
