### PR TITLE
Port a fix from FRR community

### PR DESCRIPTION
**Pull request by sudhanshukumar22**
Author: sudhanshukumar22 <sudhanshu.kumar@broadcom.com>
Date:   Tue Oct 16 12:33:20 2019 -0700
     https://github.com/donaldsharp/frr/commit/39c93f379a5b57c56739a339ad75ec06e30daef3
     If we have a case where have created a fd for i/o and we have removed the
     handling thread but still have the fd in the poll data structure, there
     existed a case where we would get the handle this fd return from poll but we
     would immediately do nothing with it because we didn't have a thread to hand
     the event to.

     This leads to an infinite loop.  Prevent the infinite loop
    from happening and log the problem.
Signed-off-by: Preetham Singh (preetham.singh@broadcom.com)

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
retest vs please

**Comment by pavel-shirshov** [comment]
retest vs please

**Comment by sudhanshukumar22** [comment]
> retest vs please

Hi Pavel,
The VS image  has been successfully built. Can you please tell me what I need to test furthur ? Also, these changes are inside FRR docker and will not impact any VS testing.

Thanks,
Sudhanshu

**Comment by pavel-shirshov** [comment]
@sudhanshukumar22 I've merged the changes. Thank you for your PR

**Pull request merged**
