### PR TITLE
Add submodule platform/broadcom/sonic-platform-modules-accton

### PR DESCRIPTION
**Pull request by roylee123**

### CODE REVIEW

**Comment by stcheng** [comment]
could you resolve the `cla-required` issue?

**Comment by lguohan** [comment]
is this related #662? If yes, can you merge it?

**Comment by roylee123** [comment]
Yes, this is related to #662.  platform/broadcom/sonic-platform-modules-accton will be merged.

**Comment by stcheng** [comment]
hi, once the cla is signed, we could merge the commit.

**Comment by lguohan** [comment]
@roylee123, can you merge with other commit and submit one PR.

**Comment by roylee123** [comment]
As I discussed with Polly(issuer of #662), I will cancel this PR. After PR#662 is merged, I send a PR based on the change of #662.

**Pull request closed without merging**
