### PR TITLE
[Mellanox] Fix select timeout in sfp event

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

Python select.select accept a optional timeout value in seconds, however, the value passes to it is a value in millisecond.

#### How I did it

Transfer the value to millisecond.

#### How to verify it

Manual test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by keboliu — DISMISSED** [review]

**Review by liat-grozovik — APPROVED** [review]
please fix LGTM

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox could you please clarify if this is required for 202111?

**Review by keboliu — DISMISSED** [review]

**Comment by Junchao-Mellanox** [comment]
This change shall not affect sonic-xcvrd unit test at all. So I did a rebase to see if it could fix the unit test issue for sonic-xcvrd.

**Comment by Junchao-Mellanox** [comment]
Hi @sujinmkang , could you please help review?

**Review by sujinmkang — APPROVED** [review]

**Pull request merged**
