### PR TITLE
[201911][sonic-telemetry] Point submodule to head of 201911 branch

### PR DESCRIPTION
**Pull request by jleveque**
Update sonic-telemetry submodule pointer in sonic- buildimage 201911 branch to point to 201911 branch of submodule (sonic-telemetry).

This effectively rolls the following commit out of the 201911 branch:
•	aaa9188fda4b6f36dd5da00cdb240933fedae5ce: SONiC Management Framework Release 1.0 (#23)

### CODE REVIEW

**Comment by pra-moh** [comment]
Just FYI, I updated PR description to correct commit.

**Comment by jleveque** [comment]
@pra-moh: I believe the commit I had originally was correct. I was listing the commit which I effectively *rolled out* by updating this submodule. You changed it to be the new head.

**Comment by pra-moh** [comment]
> @pra-moh: I believe the commit I had in the description originally was correct. I was listing the commit which I effectively _rolled out_ by updating this submodule. You changed it to be the new head.

Oh Ok. My bad. I thought you wanted to show commit to which it will point. Let me revert back

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by lguohan** [comment]
what is the problem of master? is the function broken?

**Comment by jleveque** [comment]
@pra-mah, @hui-ma: Can you answer Guohan's question? I understand you want to roll the SONiC Manangent Framework changes out of the 20911 branch. Can you explain why?

**Comment by jleveque** [comment]
Abandoning this pull request. There is no need to create a 201911 branch of sonic-telemetry at this point in time.

**Pull request closed without merging**
