### PR TITLE
[Makefile] Allowing interactive session with the slave docker-container

### PR DESCRIPTION
**Pull request by rodnymolina**

### CODE REVIEW

**Comment by marian-pritsak** [comment]
What is the use-case for this? If you need to go to sonic-slave container, you can simply execute `make sonic-slave-bash`

**Comment by nikos-li** [comment]
I want the container to stay up and running so when I recompile, my compilation is faster. I also want to have keep the original container up and have its filesystem mounted at a certain mount point in the local fs. What is your concern over this change?

**Comment by marian-pritsak** [comment]
@nikos-li, I'm not saying that it will break anything, but I just don't get the benefit of that. If you just want to stay inside slave container, there's `make sonic-slave-bash` command for that purpose. Then you can do anything you want inside the container.

**Comment by nikos-li** [comment]
@marian-pritsak make sonic-slave-bash won't work in quite the same way. If I exit from it, the information will be lost again, no? The intend is to keep the container (not through make sonic-slave-bash)  and (with private changes) to have that container's filesystem mounted through sshfs.

**Comment by marian-pritsak** [comment]
Ok, now I see. It's a bit complicated scenario, but I'm ok with it.

**Pull request merged**
