### PR TITLE
[Mellanox] fix sfp lpmode set failure caused by extra nv port

### PR DESCRIPTION
**Pull request by keboliu**
**- What I did**
Fix a bug that causes set sfp lpmode failure on some port.

**- How I did it**
When getting all front panel ports from SDK it will return an nv port alongside with the front panel ports, this port needs to be skipped or will cause an issue when trying to set lpmode for it.  Add some logic to skip the nv port.

**- How to verify it**
Run "sfputil lpmode on/off EthernetX" on Mellanox platform.
**- Description for the changelog**

```
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#       modified:   device/mellanox/x86_64-mlnx_msn2700-r0/plugins/sfplpmset.py
#
```

**- A picture of a cute animal (not mandatory but encouraged)**
```
                 .
             /\ /l
            ((.Y(!
             \ |/
             /  6~6,
             \ _    +-.
              \`-=--^-'
               \ \
              _/  \
             (  .  Y
            /"\ `--^--v--.
           / _ `--"T~\/~\/
          / " ~\.  !
    _    Y      Y./'
   Y^|   |      |~~7
   | l   |     / ./'
   | `L  | Y .^/~T
   |  l  ! | |/| |          -Row
   | .`\/' | Y | !
   l  "~   j l j_L______
    \,____{ __"~ __ ,\_,\_
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by andriymoroz-mlnx** [comment]
retest this please

**Comment by liat-grozovik** [comment]
Retest this please

**Comment by keboliu** [comment]
retest this please

**Comment by andriymoroz-mlnx** [comment]
```
Cloning into 'isc-dhcp'...
fatal: unable to access 'https://salsa.debian.org/berni/isc-dhcp.git/': Failed to connect to salsa.debian.org port 443: Network is unreachable
```

**Comment by jleveque** [comment]
Retest this please

**Pull request merged**
