### PR TITLE
[submodule update]: Advance sonic-linux-kernel submodule

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

Commits on Sep 06, 2019
Extend 'lpc_ich' driver with additional chipsets support. (#99) 6d55e9a

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by nazariig** [comment]
retest this please

**Comment by jleveque** [comment]
@nazariig: Please list the commits included in this update in the PR description.

**Comment by nazariig** [comment]
@jleveque done.

**Comment by nazariig** [comment]
@liat-grozovik closing this because new hw-mgmt is not ready.

**Pull request closed without merging**
