### PR TITLE
[buildfix-201911] Fix the snmp docker build error.

### PR DESCRIPTION
**Pull request by abdosi**
Why I did:
Issue is get_pip.py is moved to pip 21.1 (https://github.com/pypa/get-pip/commits/main) which is not compatible with 3.6.
Issue of pip itself is fixed as part of 21.1.1 in pip community (https://github.com/pypa/pip/pull/9835).  
However get-pip.py is still not updated to latest pip. Also get.pip.py does not support python 3.6 version explicitly (https://github.com/pypa/get-pip/issues/88)

```
Step 15/29 : RUN curl https://bootstrap.pypa.io/get-pip.py | python3.6
 ---> Running in bece31f49267
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1891k  100 1891k    0     0  9564k      0 --:--:-- --:--:-- --:--:-- 9600k
Traceback (most recent call last):
  File "<stdin>", line 24298, in <module>
  File "<stdin>", line 139, in main
  File "<stdin>", line 115, in bootstrap
  File "<stdin>", line 96, in monkeypatch_for_cert
  File "/tmp/tmp5fnxrz0a/pip.zip/pip/_internal/commands/__init__.py", line 9, in <module>
  File "/tmp/tmp5fnxrz0a/pip.zip/pip/_internal/cli/base_command.py", line 12, in <module>
  File "/tmp/tmp5fnxrz0a/pip.zip/pip/_internal/cli/cmdoptions.py", line 30, in <module>
  File "/tmp/tmp5fnxrz0a/pip.zip/pip/_internal/utils/hashes.py", line 2, in <module>
ImportError: cannot import name 'NoReturn'
The command '/bin/sh -c curl https://bootstrap.pypa.io/get-pip.py | python3.6' returned a non-zero code: 1
```
How I did:

- Got the file from https://github.com/pypa/get-pip/tree/21.0 and added to the buildimage
-  pin pip to the previous release 21.0.1. (Similar is done in other public repos eg: https://github.com/grpc/grpc-java/pull/8115)

How I verify:
Build is fine locally for 201911.

```
Step 15/30 : COPY ["get-pip.py", "/usr/bin/"]
 ---> 2a5d3cad0278
Step 16/30 : RUN python3.6 /usr/bin/get-pip.py pip==21.0.1
 ---> Running in 4b3898ea8dab
Collecting pip==21.0.1
  Downloading pip-21.0.1-py3-none-any.whl (1.5 MB)
Collecting setuptools
  Downloading setuptools-56.0.0-py3-none-any.whl (784 kB)
Collecting wheel
  Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
Successfully installed pip-21.0.1 setuptools-56.0.0 wheel-0.36.2
WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/usr/bin/python3.6 -m pip install --upgrade pip' command.
Removing intermediate container 4b3898ea8dab
 ---> 852694b5b26d
Step 17/30 : RUN python3.6 -m pip install setuptools==49.6.0
 ---> Running in 0bbcba80534a
Collecting setuptools==49.6.0
  Downloading setuptools-49.6.0-py3-none-any.whl (803 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
Successfully installed setuptools-49.6.0
```

### CODE REVIEW

**Comment by abdosi** [comment]
@yxieca 201811 is also failing for same reason. We need this there also.

**Review by jleveque — APPROVED** [review]

**Comment by lguohan** [comment]
@qiluo-msft, can you take a look?

**Review by lguohan — APPROVED** [review]

**Comment by qiluo-msft** [comment]
LGTM

**Pull request merged**
