### PR TITLE
[201911][thermal control] Backport feature from master branch

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**- Why I did it**

There are a few PRs related to thermal control feature and auto merge doesn't work, so I created a pull request to integrate those PRs to 201911.

**- How I did it**

Cherry-pick all realted PRs to 201911 branch and fix all conflict manually.

**- How to verify it**

Manual test on SN2700, SN3800 and SN4700.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
Depends on https://github.com/Azure/sonic-platform-common/pull/90, neew merge https://github.com/Azure/sonic-platform-common/pull/90 first and update submodule pointer to make build success.

**Comment by Junchao-Mellanox** [comment]
Depend on https://github.com/Azure/sonic-utilities/pull/929

**Comment by prsunny** [comment]
Can you provide a reference to master PR?

**Comment by Junchao-Mellanox** [comment]
https://github.com/Azure/sonic-buildimage/pull/3949
https://github.com/Azure/sonic-buildimage/pull/4298
https://github.com/Azure/sonic-buildimage/pull/4403
https://github.com/Azure/sonic-buildimage/pull/4476
https://github.com/Azure/sonic-buildimage/pull/4631
https://github.com/Azure/sonic-buildimage/pull/4638

**Comment by Junchao-Mellanox** [comment]
> * 5 for Wrong number of arguments in a class instantiation
> * 3 for 'import *' may pollute namespac

For the 5 wrong number of arguments in a class instantiation, it's not an issue. Instead, I create a issue for LGTM https://github.com/github/codeql/issues/3617.
I will supress the 3 import * warning.

**Comment by prsunny** [comment]
Can you resolve conflict?

**Comment by Junchao-Mellanox** [comment]
Resolved

**Comment by keboliu** [comment]
Retest this please

**Pull request merged**
