### PR TITLE
[submodule]: Advance sonic-utilities

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>

**- What I did**
* Advanced sonic-utilities submodule

**- How I did it**
* N/A

**- How to verify it**
1. make configure PLATFORM=mellanox
2. make target/sonic-mellanox.bin

**- Description for the changelog**
```
Commits on Feb 21, 2020
[Command-Reference.md] Unify Usage statments and Examples (including … a4cb4dd
Multi-Db changes for NAT feature. (#818) 40eff82

Commits on Feb 23, 2020
[reboot] make sure the reboot happens even if platform reboot failed (#… 118620f

Commits on Feb 24, 2020
add support for MCLAG (#453) 8aea564
```

**- A picture of a cute animal (not mandatory but encouraged)**
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Comment by nazariig** [comment]
@liat-grozovik please add `201911` label

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
@nazariig: Submodule was updated via another PR. Can you please rebase to fix conflicts?

**Comment by nazariig** [comment]
> 
> 
> @nazariig: Submodule was updated via another PR. Can you please rebase to fix conflicts?

Done

**Comment by nazariig** [comment]
retest vsimage please

**Comment by nazariig** [comment]
retest vsimage please

**Comment by nazariig** [comment]
This PR is a source of `vsimage` failures: https://github.com/Azure/sonic-utilities/pull/453

**Comment by nazariig** [comment]
@liat-grozovik closing this as was requested

**Pull request closed without merging**
