### PR TITLE
[submodule] Advance sonic-p4rt/sonic-pins pointer

### PR DESCRIPTION
**Pull request by rhalstea**
#### Why I did it

To pick up new commits:
*  60d2467 Add depends to p4rt debian package

#### How I did it

update sonic-p4rt/sonic-pins submodule pointer

#### How to verify it

should be able to build with p4rt enabled.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by rhalstea** [comment]
For info: @bocon13 @donNewtonAlpha

**Review by bocon13 — DISMISSED** [review]

**Comment by rhalstea** [comment]
It looks like a test is failing to establish a SSH connection?

```
generic_config_updater/test_dhcp_relay.py::test_dhcp_relay_tc5_rm[config_add_default] ERROR [ 81%]
...
<10.250.0.101> ESTABLISH SSH CONNECTION FOR USER: admin
```

Which I'm not sure is related to this change. Can someone help rerun the buildimage tests? I don't seem to have the right permissions.

**Comment by rhalstea** [comment]
Looks like I forgot to document this in the original comment, but this PR is the followup mentioned in #10182, and is need for P4RT to run in bullseye.

**Review by donNewtonIntel — APPROVED** [review]

**Review by bocon13 — APPROVED** [review]

**Comment by rhalstea** [comment]
@lguohan would you mind reviewing?

**Review by bocon13 — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
