### PR TITLE
[sonic-cfggen]: Fix minigraph.py when port_alias_map absent

### PR DESCRIPTION
**Pull request by stcheng**

### CODE REVIEW

**Comment by lguohan** [comment]
can you add descriptions? what is the bug?

**Comment by stcheng** [comment]
when there is no port_alias_map, the default interface name should be used. here in this case, if no port_alias_map is set, the minigraph.py will crash with KeyError.

**Comment by taoyl-ms** [comment]
I think we have a piece of code to fill port_alias_mapping with identical mappings when port mapping is not specified in port_config?

**Comment by stcheng** [comment]
@taoyl-ms not really. the `port_alias_map` will be empty if no file is given.

**Pull request merged**
