### PR TITLE
Refine installation order of mlnx-sdk debs

### PR DESCRIPTION
**Pull request by qiluo-msft**

### CODE REVIEW

**Comment by stcheng** [comment]
in #70 the applibs_*.deb is removed, what's the intention here?

**Comment by qiluo-msft** [comment]
Install applibs first for late depending packages. Original it is there in order to be installed first, it is not a perfect trick, because makefile rules don't guarantee the order of the targets.

**Comment by stcheng** [comment]
which package depends on this?

**Comment by qiluo-msft** [comment]
$ apt-cache rdepends applibs
applibs
Reverse Depends:
  mlnx-sai
  applibs-dev

**Pull request merged**
