### PR TITLE
[FRR]there is no need to checkout master branch after compiling frr.

### PR DESCRIPTION
**Pull request by wangshengjun**
Signed-off-by: wangshengjun <wangshengjun@asterfusion.com>

**- What I did**
 the frr submodule should restore to the detach status with the right commit id.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
@wangshengjun Please try to build frr twice with your patch.
```
make target/debs/stretch/frr_7.2-sonic-0_amd64.deb
make target/debs/stretch/frr_7.2-sonic-0_amd64.deb-clean
make target/debs/stretch/frr_7.2-sonic-0_amd64.deb
```

**Comment by wangshengjun** [comment]
@pavel-shirshov  It works fine for me. Is there any problem in your environment?

**Comment by pavel-shirshov** [comment]
retest this please

**Comment by pavel-shirshov** [comment]
retest this please

**Comment by pavel-shirshov** [comment]
retest vsimage please

**Pull request merged**
