### PR TITLE
[Platform]  Accton as7712 32x support oom

### PR DESCRIPTION
**Pull request by roylee123**
**- What I did**
Replace OOM sfp driver to optoe OOM driver.

**- How I did it**
1. Add optoe driver and instantiate 32 SFP ports by it.
2. Add SFP sideband controls to cpld driver
3. Modify sfputil.py to read the new node paths.

**- How to verify it**
sensors
decode-syseeprom
psuutil status
sfputil show presence
sfputil reset

**- Description for the changelog**
Replace sfp driver to optoe OOM driver.

### CODE REVIEW

**Comment by lguohan** [comment]
why not use the sonic sff_8436_eeprom driver instead of optoe OOM driver? Is it because of sfp support?

**Comment by roylee123** [comment]
Yes, it supports both QSFP and SFP.   
Attribute port_name also provides an identity to each individual port.

**Comment by lguohan** [comment]
have you tried this patch for sfp?

https://github.com/Azure/sonic-linux-kernel/pull/20

We are moving to 4.9. We have ported sff_8436 driver to 4.9 kernel. However, this oom driver does not 4.9 kernel version. How do you plan to support 4.9 then?

**Comment by roylee123** [comment]
Hi,  
I've tried pathed sff_8436_eeprom.c. It can't show ddm information, the SFF-8472 part. 
Even this product has only qsfp ports, but others have 10/25G sfp ones.  
For kernel 4.9, my colleague will request the author of optoe driver to support as well.

**Comment by lguohan** [comment]
I believe you need to set sfp_compatible to 1

echo 1 > (your eeprom directory)/sfp_compatible

**Comment by roylee123** [comment]
lguohan,    
The author of  optoe,c, Don Bollinger, https://github.com/donboll,  has responded:
1. Why use optoe.c instead of drivers/misc/eeprom/sff_8436_eeprom.c?
    sff_8436_eeprom.c can not support pages on SFP devices. Finisar has devices that access more than 4 pages.  Also sff_8436_eeprom.c copies data from the eeprom to an internal buffer, then into the user buffer.  This wastes memory and is inefficient.
2. sff_8436_eeprom.c already support Linux 4.9, will optoe.c support it too?
Yes, optoe.c will support Linux 4.9. I have successfully built it today.

If you have more questions on it, could I involve your mail into the loop?

**Comment by donboll** [comment]
lguohan,
Hi, I'm Don Bollinger the author of optoe.  I am working on behalf of Finisar (major opto vendor), as the architect and implementer of the OCP Networking  Project 'OOM'.  The optoe driver is intended to provide better access to SFP and QSFP (and upcoming QSFP-DD/OSFP) EEPROM data.  It supports all MSA standard i2c devices under the SFF-8472 and SFF-8476 standards.  Optoe is being incorporated by 3 switch vendors right now (two of them are trying to submit optoe to you right now), and has already been accepted into the ONL public mainline for 6 switch platforms from two vendors (including one you are not working with right now.)  Bottom line:  optoe is real, solid, supported, an emerging industry standard.  I and Finisar are prepared to support it and extend it as needed to accommodate future devices and evolution in the Linux base.

I have examined the version of sff_8436 in the patch you referenced above (https://github.com/Azure/sonic-linux-kernel/pull/20).  I don't think this particular patch supports SFP at all.  It doesn't have the 'sfp_compat' flag that other versions of that driver have, and it doesn't have any code to access the second i2c address (A2h or 51) that holds the majority of the SFP EEPROM data.  (Search for 'i2c_new_dummy' in earlier versions, note it is missing in this version.)  Finally, this version still has the reference to 'struct memory_accessor' which was removed at Linux 4.6.  I don't think this version will compile under Linux 4.9.

I have the same code in optoe, since optoe is based on sff_8436.  I have a version that removes all the code that depends on struct memory_accessor (search for macc in optoe or in sff_8436).  I *think* it is safe to just remove that code, but that means kernel code can no longer access the EEPROM data (user space still can).  Is that OK?  Specifically, does Sonic use that macc/struct memory_accessor interface to access the sff_8436 driver?  If not, I can pull that code out, and submit it to Sonic.  You will then have a driver that supports at least two of your switch vendors, that works for SFP and QSFP, and that works under Linux 4.9.  But I need to know:  Does Sonic access the optical driver through the macc interface?

**Comment by donboll** [comment]
Yes, I can give an introduction Tuesday (Feb 5, 2018) at 7-8AM (PST).  Please send meeting info, I can't find the meeting schedule, phone number, virtual meeting code, etc.

**Comment by lguohan** [comment]
@donboll, thanks for the confirmation. I have sent the meeting invite to you.

**Comment by lguohan** [comment]
@roylee123 , based on yesterday discussion, we plan to wait donboll to submit optoe patch on sonic-linux-kernel and let you adapt use the optoe driver in the sonic-linux-kernel. let me know if you have any concern on this?

**Comment by roylee123** [comment]
Good news. I'm OK with that.

**Comment by lguohan** [comment]
@roylee123 , optoe driver has been merged into latest sonic kernel. can you update the PR to use that?

https://github.com/Azure/sonic-linux-kernel/commit/3525f35568145f4c40c6b3dfebfbd72011085aa5

**Comment by lguohan** [comment]
I see another commit from https://github.com/Azure/sonic-buildimage/pull/1380 which also update accton driver submodule. can you coordinate?

**Comment by roylee123** [comment]
I've removed related optoe files and test sfputil for 
1. sfputil show presence
2. sfputil show eeprom
2. sfputil reset  EthernetXX

**Comment by lguohan** [comment]
still see as7312-54x/modules/optoe.c

**Comment by lguohan** [comment]
you also need to update the kernel submodule to include the optoe module.

**Comment by lguohan** [comment]
commit message says "Replace sfp driver to optoe OOM driver.", but I still see sfp drivers in the platform driver directories, are they still used?

**Comment by roylee123** [comment]
No, I'll remove it on PR #1339, New model as7312 54x .

**Pull request merged**
