### PR TITLE
[sonic-sairedis][sonic-swss-common] Update submodules

### PR DESCRIPTION
**Pull request by smaheshm**
**- Why I did it**
Linker error when compiling with ENABLE_SYNCD_RPC. Fix is in SAI repo.

**- How I did it**
Moved variable declaration to object file included in librpcserver.a

**- How to verify it**
compile with 'ENABLE_SYNCD_RPC" flag enabled.

**- Description for the changelog**
[sonic-sairedis] 
update submodule to include SAI1.6.1.

[MultiDB] use get API to obtain dbid instead of hardcode value (#618) …
dzhangalibaba

Add synchronous mode to sairedis library (#617) …
kcudnik

[meta] Fix tests to be backward compatible (#619)
kcudnik

[sonic-swss-common]
EVPN VXLAN DB support (#339) …
srj102
tapashdas

Add modifyRedis flag to consumer table object (#344) …
kcudnik

Fix memory leak in pyext when Selectable is returned to Python (#343) …
pavel-shirshov

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Please update PR title to be more descriptive. E.g., `[sairedis] Update submodule`

**Comment by qiluo-msft** [comment]
You may need advance sonic-swss-common

**Comment by jleveque** [comment]
Now that you're updating a second submodule in this PR, the title should read:

```
[sairedis][swss-common] Update submodules
```

**Comment by smaheshm** [comment]
> Mellanox build failed:
> 
> ```
> 21:50:14  configure: error: libthrift is required for rpcserver
> 21:50:14  Makefile:367: recipe for target 'config.status' failed
> 21:50:14  make[2]: *** [config.status] Error 1
> 21:50:14  make[2]: Leaving directory '/sonic/src/sonic-sairedis'
> 21:50:14  dh_auto_clean: make -j16 distclean returned exit code 2
> 21:50:14  debian/rules:37: recipe for target 'binary-syncd' failed
> 21:50:14  make[1]: *** [binary-syncd] Error 2
> 21:50:14  make[1]: Leaving directory '/sonic/src/sonic-sairedis'
> 21:50:14  dpkg-buildpackage: error: fakeroot debian/rules binary-syncd gave error exit status 2
> 21:50:14  [  FAIL LOG END  ] [ target/debs/stretch/libsairedis_1.0.0_amd64.deb ]
> ```

checking.

**Comment by smaheshm** [comment]
retest vsimage please

**Comment by smaheshm** [comment]
retest mellanox please

**Comment by qiluo-msft** [comment]
Wait for another fix https://github.com/Azure/sonic-sairedis/pull/621

**Comment by qiluo-msft** [comment]
Retest mellanox please

**Comment by smaheshm** [comment]
retest vsimage please

**Comment by lguohan** [comment]
why they are 28 commits. can you rebase and push?

**Comment by lguohan** [comment]
your rebase does not work, I would expect to see only 1 or 2 commits after you rebase

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by lguohan** [comment]
retest mellanox please

**Comment by qiluo-msft** [comment]
https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all-pr/3456/consoleFull passed
```
20:59:53  GitHub pull request #4708 of commit 5eed2f9b206c60ff56f489b558680c5b548ff741, no merge conflicts.
20:59:53  Setting status of 5eed2f9b206c60ff56f489b558680c5b548ff741 to PENDING with url https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all-pr/3455/ and message: 'Build started for merge commit.'
20:59:53  Using context: mellanox
20:59:54  Obtained jenkins/mellanox/buildimage-mlnx-all-pr/Jenkinsfile from git https://github.com/Azure/sonic-build-tools
20:59:54  Running in Durability level: MAX_SURVIVABILITY
20:59:54  [Pipeline] Start of Pipeline
20:59:54  [Pipeline] node
20:59:54  Running on jenkins-worker-2 in /data/johnar/workspace/mellanox/buildimage-mlnx-all-pr@2
20:59:54  [Pipeline] {
20:59:55  [Pipeline] stage
20:59:55  [Pipeline] { (Declarative: Checkout SCM)
20:59:55  [Pipeline] checkout
20:59:55  No credentials specified
20:59:55  Cloning the remote Git repository
20:59:55  Checking out Revision 91c5c67504c756cd6a4e5463abeb04d671c33949 (refs/remotes/origin/master)
20:59:55  Commit message: "[buildimage-mlnx-all-pr]: build docker-syncd-mlnx-rpc.gz and docker-ptf-mlnx.gz"
20:59:55  Cloning repository https://github.com/Azure/sonic-build-tools
20:59:55   > git init /data/johnar/workspace/mellanox/buildimage-mlnx-all-pr@2 # timeout=10
20:59:55  Fetching upstream changes from https://github.com/Azure/sonic-build-tools
20:59:55   > git --version # timeout=10
20:59:55   > git fetch --tags --progress https://github.com/Azure/sonic-build-tools +refs/heads/*:refs/remotes/origin/*
20:59:55   > git config remote.origin.url https://github.com/Azure/sonic-build-tools # timeout=10
20:59:55   > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
20:59:55   > git config remote.origin.url https://github.com/Azure/sonic-build-tools # timeout=10
20:59:55  Fetching upstream changes from https://github.com/Azure/sonic-build-tools
20:59:55   > git fetch --tags --progress https://github.com/Azure/sonic-build-tools +refs/heads/*:refs/remotes/origin/*
20:59:55   > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
20:59:55   > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
20:59:55   > git config core.sparsecheckout # timeout=10
20:59:55   > git checkout -f 91c5c67504c756cd6a4e5463abeb04d671c33949
20:59:55   > git rev-list --no-walk d0f856d2ce326d7c952484000527d1bee50a34aa # timeout=10
20:59:56  [Pipeline] }
20:59:56  [Pipeline] // stage
20:59:56  [Pipeline] withEnv
20:59:56  [Pipeline] {
20:59:56  [Pipeline] stage
20:59:56  [Pipeline] { (Prepare)
20:59:56  [Pipeline] cleanWs
20:59:56  [WS-CLEANUP] Deleting project workspace...
20:59:56  [WS-CLEANUP] Deferred wipeout is used...
20:59:56  [WS-CLEANUP] done
20:59:56  [Pipeline] checkout
20:59:56  No credentials specified
20:59:56  Cloning the remote Git repository
20:59:56  Cloning repository http://github.com/Azure/sonic-buildimage
20:59:56   > git init /data/johnar/workspace/mellanox/buildimage-mlnx-all-pr@2 # timeout=10
20:59:56  Fetching upstream changes from http://github.com/Azure/sonic-buildimage
20:59:56   > git --version # timeout=10
20:59:56   > git fetch --tags --progress http://github.com/Azure/sonic-buildimage +refs/heads/*:refs/remotes/origin/*
20:59:59   > git config remote.origin.url http://github.com/Azure/sonic-buildimage # timeout=10
20:59:59   > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
20:59:59   > git config remote.origin.url http://github.com/Azure/sonic-buildimage # timeout=10
20:59:59  Fetching upstream changes from http://github.com/Azure/sonic-buildimage
20:59:59   > git fetch --tags --progress http://github.com/Azure/sonic-buildimage +refs/pull/*:refs/remotes/origin/pr/*
21:00:08  JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://wiki.jenkins-ci.org/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData
21:00:08  Checking out Revision 2756bd2a940744c3969e481f100fb42c625441e7 (refs/remotes/origin/pr/4708/merge)
21:00:08   > git rev-parse refs/remotes/origin/pr/4708/merge^{commit} # timeout=10
21:00:08   > git rev-parse refs/remotes/origin/origin/pr/4708/merge^{commit} # timeout=10
21:00:08   > git config core.sparsecheckout # timeout=10
21:00:08   > git checkout -f 2756bd2a940744c3969e481f100fb42c625441e7
21:00:09  Commit message: "Merge 5eed2f9b206c60ff56f489b558680c5b548ff741 into 6b332f74a028087abee01cd28ac16ed1ffc3aa74"
```

```
23:49:03  Adding one-line test results to commit status...
23:49:03  Setting status of 5eed2f9b206c60ff56f489b558680c5b548ff741 to SUCCESS with url https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all-pr/3455/ and message: 'Build finished. No test results found.'
23:49:03  Using context: mellanox
23:49:03  Finished: SUCCESS
```

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by smaheshm** [comment]
retest vsimage please

**Comment by smaheshm** [comment]
Closing this in favor of PR #4722

**Pull request closed without merging**
