### PR TITLE
Clear VXLAN tunnel table from State DB on startup

### PR DESCRIPTION
**Pull request by lukasstockner**
#### Why I did it
When reloading config after crashes, VTEP interfaces are sometimes not created since the tunnel still exists in the STATE_DB.

See also https://github.com/Azure/sonic-buildimage/issues/9694#issuecomment-1022363135.
#### How I did it
Adding `VXLAN_TUNNEL_TABLE` to the list of tables to be cleaned in `swss.sh` fixes the problem.
#### How to verify it
* Setup EVPN-VXLAN fabric
* Crash orchagent
* Reload the config
* Observe missing VTEP interfaces
* Perform cold reboot
* Observe that VTEP interface gets created again
* Repeat all this with fix applied, observe that VTEP interfaces always get created now
#### Which release branch to backport (provide reason below if selected)
- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [x] 202106
- [x] 202111

Reproduced in 202111 and 202106, didn't check the older releases but I'd expect them to have the same issue.

#### Description for the changelog
Clear VXLAN tunnel table from State DB on startup to prevent stale entries from blocking tunnel creation.

#### A picture of a cute animal (not mandatory but encouraged)
Image from iOS

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by liuh-80** [comment]
202012 branch PR merged: https://github.com/sonic-net/sonic-buildimage/pull/11078

**Pull request merged**
