### PR TITLE
[202012][sonic-swss] Updated submodule for sonic-swss

### PR DESCRIPTION
**Pull request by vmittal-msft**
#### Why I did it
To enable switch level attribute setting for DSCP->TC QoS map

#### How I did it
Updating sonic-swss submodule 

#### How to verify it
Verified on TD3 based system

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog

Updated sonic-swss submodule

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by prsunny** [comment]
@vmittal-msft , i think we can close this in favor of #9422

**Comment by vmittal-msft** [comment]
Sure.

**Pull request closed without merging**
