### PR TITLE
[device/accton]:Update Accton-AS7326-56X

### PR DESCRIPTION
**Pull request by pollyhsu2git**
* Update Accton-AS7326-56X to adapt xxx.config.bcm based on the latest update of `Device-Specific File Directory Structure`
* Update Accton-AS7326-56X upon the port link / led test upon bringing-up the new SAI version, 3.2.1.1 / OpenNSL, 3.5.0.4
* Update Accton-AS7326-56X to add the MAC RESET opeation before bring-up the SDK based on the HW spec

Signed-off-by: polly_hsu@edge-core.com

**- What I did**
Update Accton-AS7326-56X based on the port link / led test via self bringing-up the new SAI version, 3.2.1.1 / OpenNSL, 3.5.0.4

**- How I did it**
1. Update Accton-AS7326-56X to adapt xxx.config.bcm based on the latest update of Device-Specific File Directory Structure the SONiC Porting Guide.
2. Update Accton-AS7326-56X against the latest update of the SONiC Porting Guide (https://github.com/Azure/SONiC/wiki/Porting-Guide).

**- How to verify it**
1. Target-verified the port mapping of 48x25G+8x100G as expected
2. Target-verified the port link of -48x25G+8x100G as expected
3. Target-verified the port led of -48x25G+8x100G as expected
4. Ran config_checker passed on our config.bcm

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
@pollyhsu2git , can you resolve conflict?

**Comment by pollyhsu2git** [comment]
@lguohan 
We've updated our latest submodule  code for resolving the conflict here~

**Comment by pollyhsu2git** [comment]
@lguohan @stcheng 
May we know whether we still have the conflicting files shown (minigraph.xml / sonic-platform-modules-accton?

**Comment by lguohan** [comment]
yes, we have

Conflicting files
device/accton/x86_64-accton_as7326_56x-r0/minigraph.xml 
platform/broadcom/sonic-platform-modules-accton

**Comment by lguohan** [comment]
btw, you no longer need to check-in minigraph.xml due to this commit.

https://github.com/Azure/sonic-buildimage/pull/2050

**Comment by pollyhsu2git** [comment]
@lguohan
Thanks for the info~
For the sonic-platform-modules-accton conflict, do we do the compiling against the latest master base (Kernel 4)? or?

**Comment by lguohan** [comment]
all source code is in buildimage now.

**Comment by pollyhsu2git** [comment]
@lguohan 
Thanks!
We'll watch your posted build status here~

**Comment by pollyhsu2git** [comment]
@nikos-github
Got it! Sir~  We'll close this PR then.  After we've tested it again with the latest Kernel 4, we'll create a new one.

**Pull request closed without merging**
