### PR TITLE
[platform]Accton, add platform as6712-32x.

### PR DESCRIPTION
**Pull request by roylee123**
New platform of accton as6712-32x:
ASIC Vendor: Broadcom
Swich ASIC: Trident2
Port Configuration: 32x40G
SONiC Image: SONiC-ONIE-Broadcom

For too much changes to be made,  I closed PR #1599 "New platform as6712-32x", 
and open this new PR for stretch.

- What I did
Add device and platform files for new mode as6712-32x.

- How I did it
Add as SONiC Porting Guide.

- How to verify it
decode-syseeprom
sensors
psuutil
sfputil
thermal monitor
bcmsh on port status
port led

### CODE REVIEW

**Comment by jleveque** [comment]
Retest this please.

**Comment by roylee123** [comment]
I've run "git clone & make all" twice and no error was found. 
Is that mean I have to check other branches, not just master?

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by roylee123** [comment]
I've tested image of buildimage-brcm-all #755.
No error was found.

**Pull request merged**
