### PR TITLE
[202012][Arista] Update platform drivers

### PR DESCRIPTION
**Pull request by Staphylo**
- Provide `hw-management-generate-dump.sh` for `show techsupport`
 - Load `optoe3` for OSFP and QSFP-DD transceivers
 - Enhance reboot-cause caching robustness

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by Staphylo** [comment]
retest broadcom please

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by Staphylo** [comment]
retest broadcom please

**Pull request merged**
