### PR TITLE
Buffers config

### PR DESCRIPTION
**Pull request by wendani**
**- What I did**
Improve memory utilization and robustness to traffic burstiness through better buffer sharing at the ingress
**- How I did it**

Consolidate the buffer pools of PG 3 and 4. 

Reduce the size of dedicated buffers per port per lossless PG to leave buffer space for shared pool.

Use dynamic threshold to absorb burstiness while maintain fairness.

**- How to verify it**

Verified the config on A7050-QX-32S:
Tested ingress PG pool sizing
Tested ingress xon offset
Tested ECN min threshold and max threshold

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by wendani** [comment]
@yxieca Does the old config still work? If so, I prefer updating to the new one in a separate PR.

**Comment by yxieca** [comment]
The old one still work. You can update in a separate PR.

Cheers,
Ying

**Comment by stcheng** [comment]
short reminder: Use squash and merge to update the commit message and check in the commit 🍺

**Comment by wendani** [comment]
🍻

**Pull request merged**
