### PR TITLE
[BFN] Removed thermal manager for BMC-based platforms

### PR DESCRIPTION
**Pull request by VadymYashchenko**
#### Why I did it
On BMC-based platforms, the thermal control is handled by BMC itself.

As per HLD:

"This cooling device control function can be disabled if the vendor have their own implementation in the kernel or somewhere else."
https://github.com/Azure/SONiC/blob/master/thermal-control-design.md#3-thermal-control-management

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by akokhan — APPROVED** [review]

**Review by akokhan — APPROVED** [review]

**Comment by akokhan** [comment]
@prgeor , please approve and merge. Thank you.

**Comment by prgeor** [comment]
@sujinmkang could you please review?

**Review by sujinmkang — APPROVED** [review]

**Comment by sujinmkang** [comment]
@akokhan  How about thermalctld?  Does the thermalctld on the platform still run without the platform thermal_manager api?

**Comment by akokhan** [comment]
> @akokhan How about thermalctld? Does the thermalctld on the platform still run without the platform thermal_manager api?

@sujinmkang , yes, thermalctld is still running  to perform thermal monitor function:
https://github.com/Azure/sonic-platform-daemons/blob/94fa239a7bcfcab008e94fb5c118b628e4256561/sonic-thermalctld/scripts/thermalctld#L828

For me, it looks excessive to run 2 threads in case we want to disable thermal_manager. Looks like it would be better to run ThermalMonitor in main thread and start new thread for thermal_manager if supported. But that's by design..

**Comment by akokhan** [comment]
@prgeor , please merge. Thank you.

**Pull request merged**
