### PR TITLE
[submodule] Update submodule for sonic-utilities

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
b550c44 Add command reference for trap flow counters (#1876)
67a267b [Reclaim buffer] [Mellanox] Db migrator support reclaiming reserved buffer for unused ports (#1822)
30e4654 Add show command for BFD sessions (#1942)
e63f47e [warm-reboot] Fix failures of warm reboot on disconnect of ssh session (#1529)
c05845d Add trap flow counter support (#1868)
ef82f00 [load_minigraph] Delay pfcwd start until the buffer templates are rendered (#1937)
f5e5a56 [sonic-package-manager] support sonic-cli-gen and packages with YANG model (#1650)
64777a4 generic_config_updater: Filename changed & VLAN validator added (#1919)
1f8f6ab [config reload] Update command reference (#1941)

#### Why I did it

Include trap flow counter feature

#### How I did it

Update submodule for sonic-utilities

#### How to verify it

Run build.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Comment by stepanblyschak** [comment]
@Junchao-Mellanox  @keboliu  Please check this comment - https://github.com/Azure/sonic-buildimage/pull/9379#issuecomment-979807503

**Comment by Junchao-Mellanox** [comment]
@stepanblyschak thanks.

**Comment by Junchao-Mellanox** [comment]
Checker depends on https://github.com/Azure/sonic-buildimage/pull/9487

**Comment by prgeor** [comment]
seems there is already similar pr [https://github.com/Azure/sonic-buildimage/pull/9467](https://github.com/Azure/sonic-buildimage/pull/9467)

**Comment by Junchao-Mellanox** [comment]
closing this since there is another similar PR

**Pull request closed without merging**
