### PR TITLE
Remove "rules/python3.dep"

### PR DESCRIPTION
**Pull request by joyas-joseph**
Signed-off-by: Joyas Joseph <joyas_joseph@dell.com>

**- Why I did it**
This is a cleanup.
We use python3 from the debian buster distribution itself and so "rules/python3.dep" got removed.

**- How I did it**
Delete the file.

**- How to verify it**
Check that "rules/python3.dep" doesnt exist in a new clone.

**- Description for the changelog**
Remove "rules/python3.dep"

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by joyas-joseph** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest broadcom please

**Comment by lguohan** [comment]
retest vsimage please

**Pull request merged**
