### PR TITLE
[sonic-py-swsssdk] Update submodule

### PR DESCRIPTION
**Pull request by jleveque**
Commits included:

* src/sonic-py-swsssdk 748c404...1ea30d2 (1):
  > Fix bug: ConfigDBConnector.get_table does not work in python3 (#92)

### CODE REVIEW

**Comment by jleveque** [comment]
Retest baseimage please

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by jleveque** [comment]
Retest vs please

**Review by qiluo-msft — APPROVED** [review]

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by jleveque** [comment]
retest vsimage please

**Pull request merged**
