### PR TITLE
[device/celestica]: Implement Silverstone platform API [SFP]

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- What I did**
  - Add Sfp APIs base on SfpBase and SfpUtilBase 

**- How I did it**
1. Implement Sfp APIs.
3. Init Sfp object list on chassis API.

**- How to verify it**
- Create python script follow the new platform API design doc to verify it (Azure/SONiC#285.)
- Test Log : [sfp_api_silverstone_test.log](https://github.com/Azure/sonic-buildimage/files/3948496/sfp_api_silverstone_test.log)

Signed-off-by: Wirut Getbamrung wgetbumr@celestica.com

### CODE REVIEW

**Comment by mudsut4ke** [comment]
retest mellanox please

**Comment by mudsut4ke** [comment]
retest this please

**Comment by mudsut4ke** [comment]
Retest mellanox please

**Comment by abdosi** [comment]
@mudsut4ke  Cherry-pick has conflict. Raise separate PR for 201911.

cc @rlhui @yxieca

**Pull request merged**
