### PR TITLE
[hostcfgd] record feature state in STATE DB

### PR DESCRIPTION
**Pull request by stepanblyschak**
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>

#### Why I did it

To implement blocking feature state change.

#### How I did it

Record the actual feature state in STATE DB from hostcfg.

#### How to verify it

UT + verification by running on the switch and checking STATE DB. 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111

### CODE REVIEW

**Comment by stepanblyschak** [comment]
/Azpw.run Azure.sonic-buildimage

**Comment by liat-grozovik** [comment]
@yxieca kindly reminder to review or assign someone.

**Comment by liat-grozovik** [comment]
@yxieca kindly reminder to review or assign someone. this is needed for 202111 and we would like to have it there as soon as possible.

**Review by yxieca — APPROVED** [review]

**Pull request merged**
