### PR TITLE
[sonic-sairedis submodule] Updated SAI header 1.7.1 for BRCM and Mellanox SDK/SAI

### PR DESCRIPTION
**Pull request by vmittal-msft**
**- Why I did it**
To update SAI header to tag 1.7.1 

**- How I did it**
1. Updated sonic-sairedis to point to new SAI 1.7.1 header
2. Updated MLNX SAI/SDK supporting new header
3. Updated BRCM debians supporting new header

**- How to verify it**
Installed sonic image on DUT to verify -
1. ports
2. interfaces
3. IP routes
4. BGP neighbors
5. ping working for BGP neighbors

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

Updated sonic-sairedis to point to SAI 1.7.1
https://github.com/Azure/sonic-sairedis/compare/d814d2cc7c52240d49752c45ca4c9ebd0ca7106c...560c17139f5519d5976360b99e657fc879053bb2

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vmittal-msft** [comment]
This PR is in draft mode. It is awaiting sonic-sairedis to be merged (https://github.com/Azure/sonic-sairedis/pull/748) so compilation may not go thru till then.

**Comment by liat-grozovik** [comment]
few general comments
- PR subject is not aligned with the changes. It is not just submodule update but rather Mellanox SDK/SAI update as well.
- Please add list of submodule fixes while introducing submodule to buildimage

The Mellanox SDK/FW and SAI components are correct :-)

**Comment by vmittal-msft** [comment]
retest vsimage please

**Review by smaheshm — APPROVED** [review]
Looks good. Please wait for all test results to pass. :shipit:

**Comment by vmittal-msft** [comment]
retest vsimage please

**Comment by vmittal-msft** [comment]
retest this please

**Comment by lguohan** [comment]
can you resolve conflict?

**Comment by vmittal-msft** [comment]
retest vs please

**Comment by vmittal-msft** [comment]
retest vsimage please

**Comment by vmittal-msft** [comment]
retest this please

**Review by lguohan — APPROVED** [review]

**Pull request merged**
