### PR TITLE
[201911][procdockerstatsd] Fix unit conversion for docker stats

### PR DESCRIPTION
**Pull request by pra-moh**
#### Why I did it
Bug exists in 201911 branch where unit conversion for docker stats is incorrect. Both MiB/GiB to byes conversion is incorrect
Example: 
`admin@str-s6000-acs-10:/usr/bin$ docker stats --no-stream -a`
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
e958c81d27a8        mgmt-framework      0.00%               0B / 0B               0.00%               0B / 0B             0B / 0B             0
9b6b7b4361d5        telemetry           3.13%               86.31MiB / 7.785GiB   1.08%               0B / 0B             0B / 106kB          30
e7fee0b617fe        snmp                70.28%              57.03MiB / 7.785GiB   0.72%               0B / 0B             0B / 102kB          9

admin@str-s6000-acs-10:/usr/bin$ redis-cli -n 6 hgetall "DOCKER_STATS|e7fee0b617fe"
 1) "MEM%"
 2) "0.72"
 3) "MEM_LIMIT_BYTES"
 4) "8359080099840"
 5) "NAME"
 6) "snmp"
 7) "NET_OUT_BYTES"
 8) "0"
 9) "MEM_BYTES"
10) "5980028928"
11) "BLOCK_OUT_BYTES"
12) "102000"
13) "NET_IN_BYTES"
14) "0"
15) "BLOCK_IN_BYTES"
16) "0"
17) "PIDS"
18) "9"
19) "CPU%"
20) "5.96"
#### How I did it
Installed 2019 image and verified values
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

This has been fixed as part 0f 202006 and 202012 image, along with some other changes which are not supposed to be backported.

### CODE REVIEW

**Comment by jleveque** [comment]
For posterity, I wound up fixing this upstream while converting procdockerstatsd to Python 3 [here](https://github.com/Azure/sonic-buildimage/pull/5657).

**Review by jleveque — APPROVED** [review]

**Comment by lguohan** [comment]
@pra-moh, please add unit test for master branch.

**Comment by jleveque** [comment]
> @pra-moh, please add unit test for master branch.

@lguohan: I added a unit test for this function in master when I moved the daemon to the new sonic-host-services package: https://github.com/Azure/sonic-buildimage/pull/5694/files#diff-b2ff224f39880bebc4f96bcf7f3bf7200947652c8cfd190ac01e670dea6643f6R20-R41

However, we should still increase unit test coverage for the daemon as a whole.

**Comment by pra-moh** [comment]
> > @pra-moh, please add unit test for master branch.
> 
> @lguohan: I added a unit test for this function in master when I moved the daemon to the new sonic-host-services package: https://github.com/Azure/sonic-buildimage/pull/5694/files#diff-b2ff224f39880bebc4f96bcf7f3bf7200947652c8cfd190ac01e670dea6643f6R20-R41
> 
> However, we should still increase unit test coverage for the daemon as a whole.

Ack!

**Pull request merged**
