### PR TITLE
Update sonic-swss pointer

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>

Update sonic-swss pointer in order to include cable breakout feature

### CODE REVIEW

**Comment by lguohan** [comment]
I believe this is not enough, this commit has an known issue. A later commit fixed the issue.

**Comment by volodymyrsamotiy** [comment]
@lguohan 
I didn't observe any issues and I don't see any fixes related to these changes in the history.
Could you please clarify the issue and commit which fixed it? Just to know what else should be included.

**Comment by lguohan** [comment]
https://github.com/Azure/sonic-swss/commit/a3d39296268a0e9185e7d105e7d9b2a72c59ca5d

**Comment by lguohan** [comment]
submodule updated in #1065

**Pull request closed without merging**
