### PR TITLE
[sonic-platform-common] Update submodule pointer

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
9935fca5 Fixed eeprom_tlvinfo.py to make it Python2/Python3 compatible (#155)
7e23e63 [y_cable] Skip ImportError in y_cable.py (#154)

**- Why I did it**

Update submodule pointer for sonic-platform-common to provide a fix for python3 pmon daemons build issue.

**- How I did it**

Update submodule pointer for sonic-platform-common

**- How to verify it**

Build

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by jleveque — DISMISSED** [review]

**Comment by akokhan** [comment]
@Junchao-Mellanox , could you please update to the latest commit to pull in eeprom_tlvinfo.py fix as well. Thank you in advance.

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox , could you please update to the latest commit to pull in eeprom_tlvinfo.py fix as well. Thank you in advance.

Done

**Comment by akokhan** [comment]
retest vsimage please

**Comment by akokhan** [comment]
retest mellanox please

**Comment by akokhan** [comment]
retest broadcom please

**Comment by akokhan** [comment]
retest broadcom please

**Comment by akokhan** [comment]
retest broadcom please

**Comment by akokhan** [comment]
retest vsimage please

**Comment by akokhan** [comment]
retest mellanox please

**Comment by akokhan** [comment]
retest vsimage please

**Comment by akokhan** [comment]
retest vsimage please

**Review by jleveque — APPROVED** [review]

**Comment by akokhan** [comment]
retest vsimage please

**Comment by akokhan** [comment]
@jleveque , @lguohan , please merge

**Review by akokhan — APPROVED** [review]

**Pull request merged**
