### PR TITLE
DellEMC S6000 tmp75 temperature update

### PR DESCRIPTION
**Pull request by paavaanan**
**- What I did**
- Change tmp75 sensors default temperature value from 25/50 to 70/80 degree.

**- How I did it**
- Updated sensors.conf for DellEMC S6000.

**- How to verify it**
- Run sensors command.
[sensors.txt](https://github.com/Azure/sonic-buildimage/files/3950477/sensors.txt)

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by paavaanan** [comment]
This need to be cherry-picked for 201911 branch

**Comment by sujinmkang** [comment]
what does 70/80 means? what will be  the fan speed for each temperature range?

**Comment by paavaanan** [comment]
- 80 is max temperature and 70 is  max_hyesteris value. Switch temperature is safe between these values. You can read more about these (max, max_hyst) sensor.conf attributes in 
https://linux.die.net/man/5/sensors.conf

>what will be the fan speed for each temperature range?
  - fan-speed/temperature corrleation is handled when we add fancontrol support.

**Comment by jleveque** [comment]
Removed "Request for 201911 Branch" label. We should not cherry-pick a PR forward. PR's should be cherry-picked backward to prevent regressions. I expect Dell to open a separate PR against the master branch, and if it cannot be cherry-picked into the 201911 branch, a separate PR should be opened against that branch.

**Pull request merged**
