### PR TITLE
[Mellanox] bug fix - adpt sfputil plugin to support ACS-MSN4700

### PR DESCRIPTION
**Pull request by keboliu**
**- What I did**
Add ACS-MSN4700 support to sfputil plugin

**- How I did it**
Add ACS-MSN4700 to hwsku-dict of sfputil plugin

**- How to verify it**
run "sfputil lpmode/reset/..."   command to test 

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by keboliu** [comment]
retest vsimage please

**Comment by keboliu** [comment]
retest vsimage please

**Comment by keboliu** [comment]
retest vsimage please

**Comment by keboliu** [comment]
retest vsimage please

**Comment by keboliu** [comment]
retest vsimage please

**Comment by keboliu** [comment]
retest vsimage please

**Pull request merged**
