### PR TITLE
Updating submodule pointers for sonic-utilities

### PR DESCRIPTION
**Pull request by dgsudharsan**
DO NOT MERGE THIS UNTIL https://github.com/Azure/sonic-buildimage/pull/4861 is merged
The PR is for submodule update for  sonic-utilities

sonic-utilities:
[3f15835] [sflow] Add mVRF support (#1230)
[dadfc18] Copp Changes (#1004)
[b226159] [CLI][PFCWD] Fix issue with specifying ports in pfcwd start on masic platforms (#1203)
[40377d3] [chassis]: Configure and show for platform chassis_modules (#1145)
[d5eb2f8] [consutil][connect] Remove root need from connect line command (#1225)
[6cbec6b] [multi-ASIC] CRM show/config commands changes for multi-asic (#1127)

**- Why I did it**

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by prsunny** [comment]
retest vs please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vs please

**Comment by dgsudharsan** [comment]
retest vsimage please

**Comment by dgsudharsan** [comment]
retest vs please

**Comment by dgsudharsan** [comment]
retest vs please

**Comment by dgsudharsan** [comment]
retest vsimage please

**Comment by dgsudharsan** [comment]
retest vsimage please

**Comment by jleveque** [comment]
This PR is superseded by https://github.com/Azure/sonic-buildimage/pull/5926

**Comment by dgsudharsan** [comment]
retest vsimage please

**Comment by dgsudharsan** [comment]
retest vsimage please

**Review by prsunny — APPROVED** [review]

**Pull request merged**
