### PR TITLE
[DPB] [Mellanox] added capability files for SN3420 platform

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
**- Why I did it**

`platform.json` and `hwsku.json` files are required for a feature called Dynamic Port Breakout

**- How I did it**

Created capability files according to platform specification `SN3420`

**- How to verify it**

Full qualification requires bugs fixes reported under sonic-buildimage

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Review by liat-grozovik — CHANGES_REQUESTED** [review]
4x25 means split, right? but for the first ports we have 1 lane so how can it be 4x25g?

**Comment by vadymhlushko-mlnx** [comment]
retest vs please

**Comment by vadymhlushko-mlnx** [comment]
Please don't merge this PR until [[DPB][MLNX][YANG-models] extended regex pattern according to MLNX systems speeds requirements](https://github.com/Azure/sonic-buildimage/pull/6279) PR will be merged

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
retest vsimage please

**Pull request merged**
