### PR TITLE
[dell-hwmon] Changed variables in psuutil scripts for both Z9100/S6100 platforms 

### PR DESCRIPTION
**Pull request by paavaanan**
**- What I did*
Changed hwmon variables in psuutil scripts for Z9100 and S6100 platforms. Now scripts are full-hwmon compatiable.

**- How I did it**
Replaced dell_s6100_lpc proc reference to SMF/hwmon1

**- How to verify it**
Execute the script and expect for same results. Without any issues.

**- IMPORTANT NOTE**
Please do merge this change along with this "https://github.com/Azure/sonic-platform-modules-dell/pull/26" pull request. This is the real code to introduce hwmon for dell platforms. Both should be in the build to avoid breakage.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by paavaanan** [comment]
Please do merge this change along with this "Azure/sonic-platform-modules-dell#26" pull request. This is the real code to introduce hwmon for dell platforms. Both should be in the build to avoid breakage.

**Comment by paavaanan** [comment]
I can see hwmon code is merged in sonic-dell-repository.  Old psustil script fails with new hwmon changes until this new psutil script pushed in the build.

**Comment by stcheng** [comment]
do we need to have the submodule update included in this pull request as well?

**Comment by jleveque** [comment]
@stcheng: Yes, the submodule pointer needs to be updated here before the merge.

@paavaanan: Guohan merged https://github.com/Azure/sonic-platform-modules-dell/pull/26 earlier today. Can you please update the submodule pointer here now?

**Comment by paavaanan** [comment]
jileveque, raised a new handle here.  
https://github.com/Azure/sonic-buildimage/pull/1328

**Comment by jleveque** [comment]
@paavaanan: For the future, you could have pushed the submodule update commit to this branch, and it would become part of this PR. That way, all of these changes get merged along with the submodule pointer update in one atomic commit.

**Comment by stcheng** [comment]
yes. agree with @jleveque could you close the #1328 and move the submodule update into this pull request? then we won't have a broken commit in the master that would have a broken state.

**Comment by paavaanan** [comment]
@jleveque I missed the same branch part while raising the pull request. Thanks for pointing this. I raised the submodule request now.

**Pull request merged**
