### PR TITLE
[centec] support v682-48y8c and v682-48x8c

### PR DESCRIPTION
**Pull request by LuiSzee**
#### Why I did it
Adding platform support for centec v682-48y8c and v682-48x8c.
V682-48y8c switch has 48 SFP+ (1G/10G/25G) ports, 8 QSFP28 (40G/100G) ports on CENTEC TsingMa.MX.
V682-48y8c is different from V682-48y8c_d in that:
1. transceiver is managed by cpu smbus rather than TsingMa.MX i2c bus.
2. port led is managed by mcu inside TsingMa.MX.
3. fan, psu, sensors, leds are managed by cpu smbus other than the cpu board vendor's close sourse driver. 

V682-48x8c switch has 48 SFP+ (1G/10G) ports, 8 QSFP28 (40G/100G) ports on CENTEC TsingMa.MX.
CPU used in v682-48y8c and v682-48x8c is Intel(R) Xeon(R) CPU D-1527.

#### How I did it
1. Modify related code in platform and device directory.
2. Upgrade centec sai to v1.9.
3. upgrade python to python3 and kernel version to 5.0 for V682-48y8c_d.

#### How to verify it
Build centec amd64 sonic image, verify platform functions (port, sfp, led etc) on centec v682-48y8c and v682-48x8c  board.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111

1. fix syncd compile error: `undefined reference to sai_query_stats_capability` on 202111
2. upgrade v682_48y8c-d support to bullseye and linux 5.10 on 202111

### CODE REVIEW

**Comment by LuiSzee** [comment]
Please help to review this PR, Thanks very much, @lguohan @sujinmkang
Here is the show platform command output on v682-48x8c:
https://github.com/LuiSzee/tests/blob/main/centec/show_platform_v682_48x8c.txt

**Comment by guxianghong** [comment]
Please help to review, @lguohan @sujinmkang
Thanks very much.

**Comment by sujinmkang** [comment]
@LuiSzee Do you have command output for v682-48y8c too? And PR description has the v682-48y8c information but it doesn't have v682-48x8c information.  Can you also share the output of "docker exec pmon supervisorctl status"?

**Comment by LuiSzee** [comment]
> @LuiSzee Do you have command output for v682-48y8c too? And PR description has the v682-48y8c information but it doesn't have v682-48x8c information. Can you also share the output of "docker exec pmon supervisorctl status"?

Here is the show platform command output on v682-48y8c and v682-48x8c, i also add the output of "docker exec pmon supervisorctl status":
https://github.com/LuiSzee/tests/blob/main/centec/show_platform_v682_48y8c.txt
https://github.com/LuiSzee/tests/blob/main/centec/show_platform_v682_48x8c.txt

V682-48x8c switch has 48 SFP+ (1G/10G) ports, 8 QSFP28 (40G/100G) ports on CENTEC TsingMa.MX, and has similar peripheral device design with V682-48y8c.

**Comment by guxianghong** [comment]
Please help to review this PR, this PR will upgrade centec sai to v1.9 which will fix the compile problem. 
Thanks very much. @lguohan @sujinmkang

**Review by sujinmkang — APPROVED** [review]

**Pull request merged**
