### PR TITLE
[build] enable 202205 branch build

### PR DESCRIPTION
**Pull request by yxieca**
#### Why I did it

enable branch build for 202205 branch

Signed-off-by: Ying Xie <ying.xie@microsoft.com>

### CODE REVIEW

**Comment by liushilongbuaa** [comment]
We don't need to add it in master branch.
Trigger is already set up in 202205 branch.

**Comment by liushilongbuaa** [comment]
We don't need to add it in master branch.
Trigger is already set up in 202205 branch.

**Comment by yxieca** [comment]
Not needed.

**Pull request closed without merging**
