### PR TITLE
[202012][sonic-swss][sonic-utilities] submodule updates

### PR DESCRIPTION
**Pull request by StormLiangMS**
#### Why I did it
For sonic-swss 
```
* b0e902a - (HEAD -> 202012, origin/202012) [flex counter] Flex counter threads consume too much CPU resources #9202 (#2031) (26 hours ago) [StormLiangMS]
* ab31560 - Remove redundant calls to get child scheduler group during initialization (#1965) (4 days ago) [Stephen Sun]
* cb5c511 - Fix issue: accumulative headroom can exceed limit in rare scenario (#2020) (4 days ago) [Stephen Sun]
* 046bfcf - Revert partial build temporary work-around (#2037) (5 days ago) [Prince Sunny]
```
For sonic-utilities 
```
* 239cb5c - (HEAD -> 202012, origin/202012) [flex counter] Flex counter threads consume too much CPU resources. #9202 (#1925) (26 hours ago) [StormLiangMS]
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@StormLiangMS is this PR is still relevant? if so, can you please update conflicts and rerun checkers?
there are some useful bugs fixes in this submodule update

**Comment by qiluo-msft** [comment]
Please solve the conflict.

**Comment by qiluo-msft** [comment]
Should we close this PR? @StormLiangMS

**Comment by StormLiangMS** [comment]
The submodules are advanced and which already included all changes in the PR, so close this PR.

**Comment by StormLiangMS** [comment]
@qiluo-msft Sorry, didn't notice the message, I checked, all commits are already included in current 202012, close this PR.

**Pull request closed without merging**
