### PR TITLE
[Mellanox] Fix truncated manufacture date returned from platform API

### PR DESCRIPTION
**Pull request by keboliu**
**- Why I did it**

The manufacture date returned from platform API was truncated, time is not included.
        
   05/11/2017 17:20:17  ------>   05/11/2017

**- How I did it**

Revise the regular expression used for matching.

**- How to verify it**

Call the platform API and check whether the manufacture date is correctly returned.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [x] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by keboliu** [comment]
retest this please

**Comment by Junchao-Mellanox** [comment]
retest mellanox please

**Comment by Junchao-Mellanox** [comment]
retest mellanox please

**Comment by Junchao-Mellanox** [comment]
retest vsimage please

**Comment by Junchao-Mellanox** [comment]
retest broadcom please

**Review by jleveque — APPROVED** [review]

**Pull request merged**
