### PR TITLE
[sonic-swss] Advance submodule

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

#### Why I did it
* To fix SWSS crash due to invalid CRM operations
* To add new cli for SAI_INGRESS_PRIORITY_GROUP_STAT_DROPPED_PACKETS
* To increase SAI REDIS response timeout to support FW upgrade on Mellanox platforms

#### How I did it
* N/A

#### How to verify it
1. Deploy image
2. Run regression

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog

sonic-swss:
```
Commits on Feb 04, 2021
Reduce noise during frequent route update (#1624) 5384ace
[cfgmgr]: Integrate MACsecMGR with sonic-buildimage (#1627) c7f27c8

Commits on Feb 05, 2021
[Mux] Route handling based on mux status, kernel tunnel support (#1615) 0b0d24c

Commits on Feb 06, 2021
Fix the compiling errors in gcc9 (#1621) 1438a70

Commits on Feb 07, 2021
Support shared headroom pool on top of dynamic buffer calculation (#1581 5fa2329
[buffermgr] Support maximum port headroom checking (#1607) 189a964

Commits on Feb 08, 2021
[tests] Remove legacy saiattributelist.h dependency (#1608) 6554b5d

Commits on Feb 09, 2021
Migrate serdes programming to port serdes object (#1611) b8193d1

Commits on Feb 10, 2021
Log level change from ERR to INFO for fetch systemports issue (#1632) aaa7bf2
[ci]: use build template (#1633) 8739791

Commits on Feb 11, 2021
[Mux] Neighbor handling based on FDB entry (#1631) 3f11a50

Commits on Feb 12, 2021
[test_virtual_chassis]: use wait_for function to improve test robustness 0dea91c
[ci]: run vstest f9d5959

Commits on Feb 13, 2021
[bufferorch] Handle NOT IMPLEMENTED status returned during set attr o… 32bc1b6

Commits on Feb 14, 2021
spell check fixes (#1630) f2854f8

Commits on Feb 15, 2021
[test_virtual_chassis]: use wait_for to make test more robust (#1640) 1238076
fixed unsupported resource issue (#1641) de03dd7

Commits on Feb 17, 2021
Add SAI_INGRESS_PRIORITY_GROUP_STAT_DROPPED_PACKETS counter, create n… 710df0c
Remove useless header in macsecorch (#1628) 459848f
[vstest/subintf] Update vs tests to validate physical port host inter… c49668e
[vstest]: add dvs_route fixture d407bc8
[vstest/nhg]: use dvs_route fixture to make test_nhg more robust 20ee836

Commits on Feb 22, 2021
[orchagent] Increase SAI REDIS response timeout to support FW upgrade… 16cd6c2

Commits on Feb 23, 2021
Updated PFCWD to use single ACL table for PFCWD and MUX (#1620) 97b3913
[acl] Enable VLAN ID qualifier for ACL rules (#1648) 99cfd58 

Commits on Feb 25, 2021
[synchronous mode] Add failure notification for SAI failures in synch… 1d33881 
```

#### A picture of a cute animal (not mandatory but encouraged)
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Review by liat-grozovik — DISMISSED** [review]

**Comment by nazariig** [comment]
@liat-grozovik the failures are:
1. kvmtest-t0
```
    "stderr_lines": [
        "WARNING: No route found for IPv6 destination :: (no default route?)", 
        "  from cryptography.hazmat.backends import default_backend", 
        "advanced-reboot.ReloadTest ... FAIL", 
        "", 
        "======================================================================", 
        "FAIL: advanced-reboot.ReloadTest", 
        "----------------------------------------------------------------------", 
        "Traceback (most recent call last):", 
        "  File \"ptftests/advanced-reboot.py\", line 1079, in runTest", 
        "    self.handle_post_reboot_test_reports()", 
        "  File \"ptftests/advanced-reboot.py\", line 1048, in handle_post_reboot_test_reports", 
        "    self.assertTrue(is_good, errors)", 
        "AssertionError: ", 
        "", 
        "Something went wrong. Please check output below:", 
        "", 
        "FAILED:dut:SSH threads haven't finished for 300 seconds", 
        "", 
        "", 
        "----------------------------------------------------------------------", 
        "Ran 1 test in 551.457s", 
        "", 
        "FAILED (failures=1)"
    ], 
    "stdout": "", 
    "stdout_lines": []
}

2021-02-18T12:46:27.5906291Z =========================== short test summary info ============================
2021-02-18T12:46:27.5907406Z SKIPPED [1] /data/sonic-mgmt/tests/common/fixtures/advanced_reboot.py:47: Testcase not supported for kvm
2021-02-18T12:46:27.5908466Z FAILED platform_tests/test_advanced_reboot.py::test_warm_reboot - RunAnsibleM...
2021-02-18T12:46:27.5909299Z ==================== 1 failed, 1 skipped in 619.02 seconds =====================
```

2. kvmtest-t1-lag
```
Feb 18 12:50:07.128835 vlab-03 ERR monit[466]: \'routeCheck\' status failed (1)
Traceback (most recent call last):
  File "/usr/local/bin/route_check.py", line 463, in <module>
    sys.exit(main()[0])
  File "/usr/local/bin/route_check.py", line 451, in main
    ret, res= check_routes()
  File "/usr/local/bin/route_check.py", line 392, in check_routes
    rt_appl_miss = filter_out_local_interfaces(rt_appl_miss)
  File "/usr/local/bin/route_check.py", line 332, in filter_out_local_interfaces
    e = dict(tbl.get(k.split("/"))[1])
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 2272, in get
    return _swsscommon.Table_get(self, key)
TypeError: in method \'Table_get\', argument 2 of type \'std::string const &\'

2021-02-18T12:51:11.3684340Z =========================== short test summary info ============================
2021-02-18T12:51:11.3685258Z ERROR bgp/test_bgp_allow_list.py::TestBGPAllowListBase::test_allow_list[permit]
2021-02-18T12:51:11.3686067Z ===================== 2 passed, 1 error in 202.56 seconds ======================
```

**Comment by liat-grozovik** [comment]
Thanks
@lguohan can you please notify the failures to feature owners?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by liat-grozovik** [comment]
@lguohan this submodule update is must because of a critical fix of https://github.com/Azure/sonic-swss/pull/1641
as mentioned above there are failures which requires owners. Would you help to assign/name the owner?

**Comment by liat-grozovik** [comment]
Please note that even when stating the pipelines test the kvmtest are not restarted ... Could the Azure build team be notified?

**Review by qiluo-msft — APPROVED** [review]

**Comment by nazariig** [comment]
https://github.com/Azure/sonic-buildimage/pull/6843

**Comment by liat-grozovik** [comment]
the last fail i can see is related to 
breakout/test_breakout_cli.py::TestBreakoutCli::test_breakout_modes FAILED [ 85%]

@jleveque was this seen on another PR recently?

**Comment by jleveque** [comment]
> the last fail i can see is related to
> breakout/test_breakout_cli.py::TestBreakoutCli::test_breakout_modes FAILED [ 85%]
> 
> @jleveque was this seen on another PR recently?

Yes. I did not see this PR and opened another PR to update sonic-utilities [here](https://github.com/Azure/sonic-buildimage/pull/6874), and it is failing on the same test.

This PR is supposed to fix it: https://github.com/Azure/sonic-buildimage/pull/6831

**Comment by jleveque** [comment]
@nazariig: Shall I keep my PR open to update sonic-utilities and you relegate this PR to swss only, or would you rather update sonic-utilities to the current head in this PR and I close mine?

Also, can you please add a list of the commits included in the submodule updates in your PR description?

**Comment by nazariig** [comment]
> 
> 
> @nazariig: Shall I keep my PR open to update sonic-utilities and you relegate this PR to swss only, or would you rather update sonic-utilities to the current head in this PR and I close mine?
> 
> Also, can you please add a list of the commits included in the submodule updates in your PR description?

@jleveque done

**Comment by nazariig** [comment]
https://github.com/Azure/sonic-buildimage/pull/6874

**Comment by jleveque** [comment]
Thanks, @nazariig. Can you please add a list of commits include in the swss submodule in the PR description? We will include them in the final commit message.

**Comment by jleveque** [comment]
> @jleveque you're welcome. It is already there. Please refer to `Description for the changelog`

Ah, yes. Thanks. It's just a bit more verbose than I'm used to, so I missed it. Normally I just copy/paste the info from `git status`

**Comment by nazariig** [comment]
The last t1-lag run:
```
Feb 28 14:03:53.906606 vlab-03 ERR monit[443]: routeCheck status failed (255) -- Failure results:
    "missed_ROUTE_TABLE_routes": [
        "100.1.0.17/32",
        "100.1.0.18/32",
        "100.1.0.19/32",
        "100.1.0.20/32",
        "100.1.0.21/32",
        "100.1.0.22/32",
        "100.1.0.23/32",
        "100.1.0.24/32",
        "100.1.0.25/32",
        "100.1.0.26/32",
        "100.1.0.27/32",
        "100.1.0.28/32",
        "100.1.0.29/32",
        "100.1.0.30/32",
        "100.1.0.31/32",
        "100.1.0.32/32",
        "172.16.10.0/24",
        "172.16.30.0/24",
        "172.16.50.0/24",
        "192.168.0.0/25",
        "192.168.0.128/25",
        "192.168.104.0/25",
        "192.168.104.128/25",
        "192.168.112.0/25",
        "192.168.112.128/25",
        "192.168.120.0/25",
        "192.168.120.128/25",
    ]
```

**Comment by liat-grozovik** [comment]
@prsunny could you please check the above failure?

**Comment by liat-grozovik** [comment]
@prsunny I believe this PR should be closed as you are working on having the swss submodule update in stages, right?

**Comment by prsunny** [comment]
> @prsunny I believe this PR should be closed as you are working on having the swss submodule update in stages, right?

ok.

**Pull request closed without merging**
