### PR TITLE
[submodule] Advance submodule head for sonic-utilities

### PR DESCRIPTION
**Pull request by stephenxs**
Fix a typo in mellanox_buffer_migrator ([#1090](https://github.com/azure/sonic-utilities/pull/1090))
[CLI][PFCWD][Multi-ASIC] Added multi ASIC support to 'pfcwd' CLI command ([#1080](https://github.com/azure/sonic-utilities/pull/1080))
Add namespace of the process in the coredump filename. ([#1091](https://github.com/azure/sonic-utilities/pull/1091))
[setup.py] Add aliases.ini to sonic_installer package ([#1088](https://github.com/azure/sonic-utilities/pull/1088))
[pfcwd] Add single asic unit tests for show commands ([#1085](https://github.com/azure/sonic-utilities/pull/1085))
Enhance SONiC with kubernetes management commands ([#962](https://github.com/azure/sonic-utilities/pull/962))
[counterpoll] add port buffer drop group ([#1009](https://github.com/azure/sonic-utilities/pull/1009))
[CLI][PFC] Add multi ASIC options for pfcstat and 'show pfc counters' ([#1057](https://github.com/azure/sonic-utilities/pull/1057))

Signed-off-by: Stephen Sun <stephens@nvidia.com>

**- Why I did it**

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
This submodule is also being updated as part of https://github.com/Azure/sonic-buildimage/pull/5264, along with some related changes. Please wait for that PR to merge, then rebase this to update it further.

**Comment by stephenxs** [comment]
> This submodule is also being updated as part of #5264, along with some related changes. Please wait for that PR to merge, then rebase this to update it further.

Got it. Will do. Thanks.

**Comment by jleveque** [comment]
It appears this PR has been superseded by https://github.com/Azure/sonic-buildimage/pull/5336

**Comment by stephenxs** [comment]
thanks. will close this one.

**Pull request closed without merging**
