### PR TITLE
[Mellanox] Auto correct PSU voltage threshold (WA)

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Conflicts:
	platform/mellanox/mlnx-platform-api/tests/test_psu.py

#### Why I did it

There is a hardware bug that PSU voltage threshold sysfs returns incorrect value. The workaround is to call "sensor -s" to refresh it.

#### How I did it

Call "sensor -s" when the threshold value is not incorrect and PSU is "DELTA 1100"

#### How to verify it

1. unit test
2. Manual test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111

### CODE REVIEW

**Review by keboliu — DISMISSED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @sujinmkang and @prgeor , could you please help review?

**Comment by liat-grozovik** [comment]
@prgeor could you please help to review?

**Review by keboliu — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @sujinmkang and @prgeor , could you please help review and sign-off?

**Review by prgeor — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @judyjoseph , could you please help cherry-pick to 202111?

**Pull request merged**
