### PR TITLE
[Nokika][IXR7250E] Update the Nokia IXR7250E platform platform.json  files

### PR DESCRIPTION
**Pull request by mlok-nokia**
#### Why I did it
Update the Nokia IXR7250E platform  platform.json files with correct thermal info table  

#### How I did it
Modify the platform.json file for Nokia IXR7250E linecard x86_64-nokia_ixr7250e_36x400g-r0 and supervisor card x86_64-nokia_ixr7250e_sup-r0

#### How to verify it
1)  login the IXR7250E linecard x86_64-nokia_ixr7250e_36x400g-r0
2)  check file /usr/share/sonic/device/x86_64-nokia_ixr7250e_36x400g-r0/platform.json .
3) The thermal sensor names in the thermal table should match the name in the output of "show platform temperature"
```
admin@sonic:~$ show platform temperature 
      Sensor    Temperature    High TH    Low TH    Crit High TH    Crit Low TH    Warning          Timestamp
------------  -------------  ---------  --------  --------------  -------------  ---------  -----------------
 temp_1(fan)             40        100        10           100                1      False  20211215 00:09:04
 temp_2(fan)             32         78        10            85.8              1      False  20211215 00:09:06
 temp_3(fan)             43         99        10           100                1      False  20211215 00:09:08
      temp_4             36         85        10            93.5              1      False  20211215 00:09:10
      temp_5             37         85        10            93.5              1      False  20211215 00:09:11
 temp_6(fan)             37        100        10           100                1      False  20211215 00:09:13
 temp_7(fan)             24         68        10            74.8              1      False  20211215 00:09:15
 temp_8(fan)             27         68        10            74.8              1      False  20211215 00:09:17
 temp_9(fan)             28         68        10            74.8              1      False  20211215 00:09:18
temp_10(fan)             35         99        10           100                1      False  20211215 00:09:20

```  
4) login the IXR7250E supervisor card x86_64-nokia_ixr7250e_sup-r0
5)  check file /usr/share/sonic/device/x86_64-nokia_ixr7250_sup-r0/platform.json .
6) The thermal sensor names in the thermal table should match the name in the output of "show platform temperature"
```
admin@supervisor:~$ show platform temperature 
     Sensor    Temperature    High TH    Low TH    Crit High TH    Crit Low TH    Warning          Timestamp
-----------  -------------  ---------  --------  --------------  -------------  ---------  -----------------
sfm1_1(fan)             49         99        10           100                1      False  20211215 00:27:55
     sfm1_2             36         68        10            74.8              1      False  20211215 00:27:57
     sfm1_3             37         68        10            74.8              1      False  20211215 00:27:59
sfm1_4(fan)             55        100        10           100                1      False  20211215 00:28:02
sfm1_5(fan)             68        100        10           100                1      False  20211215 00:28:04
sfm2_1(fan)             53         99        10           100                1      False  20211215 00:28:06
     sfm2_2             39         68        10            74.8              1      False  20211215 00:28:09
     sfm2_3             39         68        10            74.8              1      False  20211215 00:28:11
sfm2_4(fan)             59        100        10           100                1      False  20211215 00:28:13
sfm2_5(fan)             70        100        10           100                1      False  20211215 00:28:16
sfm3_1(fan)             53         99        10           100                1      False  20211215 00:28:18
     sfm3_2             41         68        10            74.8              1      False  20211215 00:28:20
     sfm3_3             39         68        10            74.8              1      False  20211215 00:28:23
sfm3_4(fan)             58        100        10           100                1      False  20211215 00:28:25
sfm3_5(fan)             68        100        10           100                1      False  20211215 00:28:27
sfm4_1(fan)             54         99        10           100                1      False  20211215 00:28:30
     sfm4_2             41         68        10            74.8              1      False  20211215 00:28:32
     sfm4_3             39         68        10            74.8              1      False  20211215 00:28:34
sfm4_4(fan)             58        100        10           100                1      False  20211215 00:28:37
sfm4_5(fan)             69        100        10           100                1      False  20211215 00:28:39
sfm5_1(fan)             55         99        10           100                1      False  20211215 00:28:41
     sfm5_2             43         68        10            74.8              1      False  20211215 00:28:44
     sfm5_3             38         68        10            74.8              1      False  20211215 00:28:46
sfm5_4(fan)             60        100        10           100                1      False  20211215 00:28:48
sfm5_5(fan)             72        100        10           100                1      False  20211215 00:28:51
sfm6_1(fan)             58         99        10           100                1      False  20211215 00:28:53
     sfm6_2             44         68        10            74.8              1      False  20211215 00:28:55
     sfm6_3             40         68        10            74.8              1      False  20211215 00:28:58
sfm6_4(fan)             62        100        10           100                1      False  20211215 00:29:00
sfm6_5(fan)             74        100        10           100                1      False  20211215 00:29:02
sfm7_1(fan)             55         99        10           100                1      False  20211215 00:29:05
     sfm7_2             44         68        10            74.8              1      False  20211215 00:29:07
     sfm7_3             40         68        10            74.8              1      False  20211215 00:29:09
sfm7_4(fan)             60        100        10           100                1      False  20211215 00:29:12
sfm7_5(fan)             71        100        10           100                1      False  20211215 00:29:14
sfm8_1(fan)             52         99        10           100                1      False  20211215 00:29:16
     sfm8_2             40         68        10            74.8              1      False  20211215 00:27:04
     sfm8_3             37         68        10            74.8              1      False  20211215 00:27:07
sfm8_4(fan)             60        100        10           100                1      False  20211215 00:27:09
sfm8_5(fan)             70        100        10           100                1      False  20211215 00:27:11
temp_1(fan)             35        100        10           100                1      False  20211215 00:27:43
     temp_2             34         85        10            93.5              1      False  20211215 00:27:45
     temp_3             34         85        10            93.5              1      False  20211215 00:27:48
temp_4(fan)             31         50        10            55                1      False  20211215 00:27:50
temp_5(fan)             41         90        10            99                1      False  20211215 00:27:52
```
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111

### CODE REVIEW

**Comment by mlok-nokia** [comment]
@judyjoseph @arlakshm @minionatwork   This PR is to update the Nokia Platform device data files platform.json files.  Please help to review it.  Thanks

**Comment by mlok-nokia** [comment]
@judyjoseph  @abdosi @minionatwork  Hi Judy, Please help review this PR. Thanks.

**Review by prgeor — APPROVED** [review]

**Comment by mlok-nokia** [comment]
@sujinmkang  It looks like the Analysis is not able to run although I don't have any python code change.  Is there any thing I can help? Creating a new PR will help?  Thanks

**Comment by mlok-nokia** [comment]
This PR is replaced by PR10091. It will be closed as duplicated.

**Comment by mlok-nokia** [comment]
duplicated with PR10091

**Pull request closed without merging**
