### PR TITLE
[snmp] remove hostname change as it share uts namespace with host

### PR DESCRIPTION
**Pull request by stepanblyschak**
Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by stepanblyschak** [comment]
1 try https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/2694/console, no timeout issue

**Comment by stepanblyschak** [comment]
retest vsimage please

**Comment by stepanblyschak** [comment]
2nd try vsimage - https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/2697/console. No timeout issue observed.

**Comment by stepanblyschak** [comment]
retest vsimage please

**Comment by msosyak** [comment]
Reverts https://github.com/Azure/sonic-buildimage/pull/2773

**Pull request merged**
