### PR TITLE
[BFN] Update BFN sdk to SAI 1.10.2

### PR DESCRIPTION
**Pull request by SavchukRomanLv**
#### Why I did it
SONiC moved to SAI 1.10.2
#### How I did it
Build package with SAI 1.10.2
Includes fixes for:
- outer vlan
- acl prio
#### How to verify it
Run sanity for X1, X2, Y2 profiles
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by akokhan** [comment]
@lguohan , @prgeor ,
please approve and merge SAI update to v1.10.2 for Intel
Thanks

**Comment by akokhan** [comment]
@lguohan ,
please approve and merge SAI update to v1.10.2 for Intel
Thanks

**Comment by akokhan** [comment]
@xumia , please approve and merge. Thank you

**Comment by SavchukRomanLv** [comment]
@lguohan could you please merge?

**Review by richardyu-ms — APPROVED** [review]

**Pull request merged**
