### PR TITLE
[dell]: Corrected dport map and renamed config files for S5232F

### PR DESCRIPTION
**Pull request by AshokDaparthi**
**- What I did**
- Corrected the wrong dport mapping 
- Renamed config files names to represent correct port order

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by AshokDaparthi** [comment]
@guohan - what i need to "retest vsimage please"

**Comment by AshokDaparthi** [comment]
How it can be merged early, because changes are not related to vsimage.

**Pull request merged**
