### PR TITLE
[platform][barefoot] Drop python2 support

### PR DESCRIPTION
**Pull request by vboykox**
Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>

#### Why I did it
python2 eol
#### How I did it
removed python2 support
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Comment by vboykox** [comment]
@jleveque, could you please suggest if this can be safely cherry-picked to 202012
Thanks

**Comment by vboykox** [comment]
@akokhan

**Comment by jleveque** [comment]
> @jleveque, could you please suggest if this can be safely cherry-picked to 202012
> Thanks

@vboykox: The infrastructure to run the platform daemons using Python 3 if a Python 3 sonic_platform package exists for that platform exists in 202012, so theoretically, yes, this should be safe to cherry-pick.

**Comment by vboykox** [comment]
@jleveque BTW, now we can also drop platform API 1.0 since no dependencies left on it, right? Does this apply to 202012 also?

**Comment by jleveque** [comment]
> @jleveque BTW, now we can also drop platform API 1.0 since no dependencies left on it, right? Does this apply to 202012 also?

Unless you use the led_control.py plugin, there are no more dependencies left in the master branch. However, these changes are not being backported to the 202012 branch, therefore some CLI utilities (sfputil, psuutil, etc.) will still reference the old plugins in 202012.

**Review by jleveque — APPROVED** [review]

**Pull request merged**
