### PR TITLE
Update docker-sonic-vs infrastructure in order to run CoPP UT

### PR DESCRIPTION
**Pull request by noaOrMlnx**
#### Why I did it
In order to be able to run CoPP UT in docker-sonic-vs
#### How I did it
N/A
#### How to verify it
Run Copp UT
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@noaOrMlnx are there any dependencies between swss PR and this one?

**Comment by noaOrMlnx** [comment]
> @noaOrMlnx are there any dependencies between swss PR and this one?

@liat-grozovik sonic-swss tests can only pass after sonic-buildimage changes will be merged
For this PR, there is no dependency

**Review by prsunny — APPROVED** [review]

**Pull request merged**
