### PR TITLE
[device] Add a new platform ly1200 for MiTAC

### PR DESCRIPTION
**Pull request by stanepc1**
- What I did
Add MiTAC-LY1200-B32H0-C3.
- How I did it
Add drv code for sfp, eeprom, psu utility tool
- How to verify it
Test cmd. cat/echo sysfs, spfutil, psu, eeprom, sensors to test.
- Description for the changelog
Add MiTAC-LY1200-B32H0-C3 drv code and utility

Signed-off-by: Eddy Weng <eddy.weng@mic.com.tw>

### CODE REVIEW

**Comment by lguohan** [comment]
we are now kernel 3.16.0-5-amd64, please fix your debian/control file.

https://github.com/MiTAC-EBU/sonic-platform-modules-mitac/blob/master/debian/control#L10

change to 3.16.0-5-amdn64

**Comment by lguohan** [comment]
also please sign CLA

**Comment by lguohan** [comment]
we are now requiring to change switch1 from sonic in the minigraph.xml

**Comment by lguohan** [comment]
you probably want to update the kernel submodule to include support on your platform.

https://github.com/Azure/sonic-linux-kernel/commit/5341a8f75f845240ca73d88738a7708af7e62406

**Comment by lguohan** [comment]
can you sign cla?

**Comment by stanepc1** [comment]
Our vice president wants to see how I sign the CLA in persion, but he is on a business trip, I have to wait for him.

I'm sorry for your waiting.
Thank you very much for your comments on our PR.

**Comment by stanepc1** [comment]
I have signed the CLA.
Let's continue the PR process.

**Comment by lguohan** [comment]
can you resolve conflict?

**Comment by stanepc1** [comment]
I have already resolved the conflict with Quanta.

**Comment by lguohan** [comment]
I still see conflicting files for .gitmodules, platform/broadcom/one-image.mk and platform/broadcom/rules.mk

**Comment by stanepc1** [comment]
In order to resolve conflicting files, I synced this branch to keep it up-to-date with the "Azure/sonic-buildimage" repository.

This branch has no conflicts with the latest base branch.

**Comment by stanepc1** [comment]
Thank you very much!

I has sent an email to shuche@microsoft.com asking him to add our "th-ly1200-32x100G.config.bcm" into the libsaibcm_3.0.3.3-3_amd64.deb.

Would you please remind shuche@microsoft.com to do so for us?

Thank you again.

**Pull request merged**
