### PR TITLE
[201911][BFN] Update Barefoot SDK packages

### PR DESCRIPTION
**Pull request by akokhan**
Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>

### CODE REVIEW

**Comment by prsunny** [comment]
Is this same as master? If so consider cherry-pick

**Comment by akokhan** [comment]
> Is this same as master? If so consider cherry-pick

Yeh, its the same. Whats the right why to request a cherry-pick instead of this PR?

**Comment by prsunny** [comment]
can you provide the PR that was merged to master?

**Comment by akokhan** [comment]
Actually not merged yet: https://github.com/Azure/sonic-buildimage/pull/4397

**Comment by prsunny** [comment]
ok, added label on #4397 for 201911. You can close this PR

**Comment by akokhan** [comment]
@prsunny  Thank you for the help!

**Pull request closed without merging**
