### PR TITLE
[platform mellanox] Substitute '-' symbol to '.' in Mellanox SDK vers…

### PR DESCRIPTION
**Pull request by ayurkiv-nvda**
…ion to prevent problems with finding deb package

Signed-off-by: Andriy Yurkiv <ayurkiv@nvidia.com>

**- Why I did it**
In case of non-GA SDK version there is '-' symbol in Mellanox SDK version name. (For example: 4.4.1306-006) 
In appropriate .deb packet there is '.' instead of '-'. Because of this there was problem while building SDK 
**- How I did it**
I have replaced  '-' symbol with '.' for MLNX_SDK_DEB_VERSION
**- How to verify it**
1) build SDK (non-GA version with suffix '-00X') without fix. Building will fail because it is impossible to find   appropriate package 
2) build SDK (non-GA version with suffix '-00X') with fix. Everything should be OK

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [x] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by volodymyrsamotiy** [comment]
retest this please

**Review by stepanblyschak — APPROVED** [review]

**Comment by keboliu** [comment]
retest this please

**Comment by ayurkiv-nvda** [comment]
retest vs please

**Comment by ayurkiv-nvda** [comment]
retest vsimage please

**Review by lguohan — APPROVED** [review]

**Pull request merged**
