### PR TITLE
Convert docker-nat to buster

### PR DESCRIPTION
**Pull request by joyas-joseph**
Signed-off-by: Joyas Joseph <joyas_joseph@dell.com>

**- Why I did it**
This is an enhancement.

**- How I did it**
Remove docker-nat from list of stretch dockers
move iptables to 1.8.2-4 (version in buster)
Rework the iptables patch

**- How to verify it**
Build `target/docker-nat.gz`
Verify that `/etc/apt/sources.list` points to `buster` using `docker exec nat cat /etc/apt/sources.list`

**- Description for the changelog**
Convert docker-nat to buster

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by AkhileshSamineni** [comment]
@joyas-joseph  Regarding iptables patch file changes

I have verified your changes and I see fullcone option is not getting applied for DNAT entries like below

How to verify : enable the NAT and check the "iptables -t nat -nvL" output

root@sonic:/home/admin# config nat feature enable
root@sonic:/home/admin#
root@sonic:/home/admin# iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
  322 26789 DNAT       all  --  *      *       0.0.0.0/0            0.0.0.0/0            to:1.1.1.1

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
root@sonic:/home/admin#

Expected output after NAT is enabled:

root@sonic:/home/admin# iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
  322 26789 DNAT       all  --  *      *       0.0.0.0/0            0.0.0.0/0            to:1.1.1.1 fullcone

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
root@sonic:/home/admin#

Please add fullcone option for below functions in file "extensions/libipt_DNAT.c" to reflect the fullcone option for DNAT.
DNAT_help_v2()
DNAT_parse_v2()
print_range_v2
DNAT_save_v2()
print_range_xlate_v2

**Comment by lguohan** [comment]
i think this pr needs also to be rebased master.

**Comment by joyas-joseph** [comment]
> @joyas-joseph Regarding iptables patch file changes
> 
> I have verified your changes and I see fullcone option is not getting applied for DNAT entries like below
> 
> How to verify : enable the NAT and check the "iptables -t nat -nvL" output
> 
> root@sonic:/home/admin# config nat feature enable
> root@sonic:/home/admin#
> root@sonic:/home/admin# iptables -t nat -nvL
> Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
> pkts bytes target prot opt in out source destination
> 322 26789 DNAT all -- * * 0.0.0.0/0 0.0.0.0/0 to:1.1.1.1
> 
> Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
> pkts bytes target prot opt in out source destination
> 
> Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
> pkts bytes target prot opt in out source destination
> 
> Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
> pkts bytes target prot opt in out source destination
> root@sonic:/home/admin#
> 
> Expected output after NAT is enabled:
> 
> root@sonic:/home/admin# iptables -t nat -nvL
> Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
> pkts bytes target prot opt in out source destination
> 322 26789 DNAT all -- * * 0.0.0.0/0 0.0.0.0/0 to:1.1.1.1 fullcone
> 
> Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
> pkts bytes target prot opt in out source destination
> 
> Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
> pkts bytes target prot opt in out source destination
> 
> Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
> pkts bytes target prot opt in out source destination
> root@sonic:/home/admin#
> 
> Please add fullcone option for below functions in file "extensions/libipt_DNAT.c" to reflect the fullcone option for DNAT.
> DNAT_help_v2()
> DNAT_parse_v2()
> print_range_v2
> DNAT_save_v2()
> print_range_xlate_v2

Thanks for the detailed review and for providing the way to verify.

```
root@sonic:/# iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    1   328 DNAT       all  --  *      *       0.0.0.0/0            0.0.0.0/0            to:1.1.1.1 fullcone

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
# Warning: iptables-legacy tables present, use iptables-legacy to see them
root@sonic:/# 
root@sonic:/# 
root@sonic:/# iptables --version
iptables v1.8.2 (nf_tables)
root@sonic:/# 
```

**Comment by joyas-joseph** [comment]
> i think this pr needs also to be rebased master.

Done.

**Comment by AkhileshSamineni** [comment]
LGTM

**Pull request merged**
