### PR TITLE
[swss]: Clear MUX-related state DB tables on start

### PR DESCRIPTION
**Pull request by theasianpianist**
Signed-off-by: Lawrence Lee <lawlee@microsoft.com>

**- Why I did it**
Port configuration changes can leave keys for unused interfaces behind in STATE DB

**- How I did it**
* Add *MUX_CABLE_TABLE* to set of tables to clear on SWSS start, which
will clear HW_MUX_CABLE_TABLE and MUX_CABLE_TABLE
* Order swss to start before pmon to ensure that DBs are cleared before
xcvrd (running inside pmon) starts and re-populates the tables

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Review by prsunny — COMMENTED** [review]
cleanup table lgtm.. can @vdahiya12 , @lguohan to check service dependency.

**Review by vdahiya12 — APPROVED** [review]

**Comment by lguohan** [comment]
@jleveque , now pmon is affected by swss.

**Comment by jleveque** [comment]
> @jleveque , now pmon is affected by swss.

Thanks for the heads-up!

**Review by lguohan — APPROVED** [review]

**Comment by theasianpianist** [comment]
@jleveque This dependency should not prevent PMON from starting if SWSS fails, since `Before=` does not enforce any dependencies on the health of the SWSS service, it only waits until SWSS has either completely started or failed: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Before=

**Review by jleveque — APPROVED** [review]

**Comment by lguohan** [comment]
in the chassis supervisor card environment, the pmon needs to before swss.

**Pull request merged**
