### PR TITLE
[ci] Disable the reproducible build for arm64 and armhf temporarily

### PR DESCRIPTION
**Pull request by xumia**
#### Why I did it
Disable the reproducible build for arm64 and armhf temporarily.
The package version upgrade has been disabled for armhf and armhf for long run time, so disable the reproducible build for the official builds as well. we will enable it when arm64 azure agent ready.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
we can wait for arm64 azure agent, but not sure what is the story for armhf,  it is hard to get armhf machine.

**Comment by xumia** [comment]
> we can wait for arm64 azure agent, but not sure what is the story for armhf, it is hard to get armhf machine.

Can we order an armhf machine and setup ourselves in the lab?

**Comment by lguohan** [comment]
frankly, I do not quite understand why we need to wait for armhf machine, can we build using x86 machine?

**Comment by xumia** [comment]
> frankly

Some of builds are not complete in 30 hours, needs to wait for long time to generate the version upgrade files.
See one of example: https://dev.azure.com/mssonic/build/_build/results?buildId=13563&view=results

**Comment by lguohan** [comment]
increase the build time then

**Comment by lguohan** [comment]
for version upgrade, we can do weekly or bi-weekly.

**Pull request merged**
