### PR TITLE
[sonic-mgmt docker]: Added allure-pytest library to sonic-mgmt docker container

### PR DESCRIPTION
**Pull request by ppikh**
[sonic-mgmt docker]: Added allure-pytest library to sonic-mgmt docker container

* Modified Dockerfile.j2 - added allure-pytest library

Signed-off-by: Petro Pikh <petrop@nvidia.com>

#### Why I did it
This library will allow us to have more human readable test reports

#### How I did it
Added allure-pytest library to Docker file template

#### How to verify it
Executed tests, using new docker-sonic-mgmt container which have installed library allure-pytest

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog
Added support for Allure reports 

#### A picture of a cute animal (not mandatory but encouraged)
:)

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
@ppikh I don't think we need to cherry-pick this change into 202012 branch. We always use sonic-mgmt docker from latest master. Is there a particular reason you want t his change in 202012 branch?

**Comment by ppikh** [comment]
> @ppikh I don't think we need to cherry-pick this change into 202012 branch. We always use sonic-mgmt docker from latest master. Is there a particular reason you want t his change in 202012 branch?

We can leave it in master only. It is ok.

**Comment by lguohan** [comment]
there was one. https://github.com/Azure/sonic-buildimage/pull/7650

**Comment by yxieca** [comment]
> there was one. #7650

Let's work on #7650 instead.

**Pull request merged**
