### PR TITLE
caclmgrd: add test code to check dhcp acl update

### PR DESCRIPTION
**Pull request by trzhang-msft**
- add test code to check dhcp acl update
- port to 202012 branch from https://github.com/Azure/sonic-buildimage/pull/8359

### CODE REVIEW

**Review by tahmed-dev — APPROVED** [review]

**Comment by qiluo-msft** [comment]
There is a valid build error.
```
==================================== ERRORS ====================================
____________ ERROR collecting tests/caclmgrd/caclmgrd_dhcp_test.py _____________
ImportError while importing test module '/sonic/src/sonic-host-services/tests/caclmgrd/caclmgrd_dhcp_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/caclmgrd/caclmgrd_dhcp_test.py:8: in <module>
    from pyfakefs.fake_filesystem_unittest import patchfs
E   ModuleNotFoundError: No module named 'pyfakefs'
```

**Comment by trzhang-msft** [comment]
> There is a valid build error.
> 
> ```
> ==================================== ERRORS ====================================
> ____________ ERROR collecting tests/caclmgrd/caclmgrd_dhcp_test.py _____________
> ImportError while importing test module '/sonic/src/sonic-host-services/tests/caclmgrd/caclmgrd_dhcp_test.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> tests/caclmgrd/caclmgrd_dhcp_test.py:8: in <module>
>     from pyfakefs.fake_filesystem_unittest import patchfs
> E   ModuleNotFoundError: No module named 'pyfakefs'
> ```

where / how to import pyfakefs into 202012 branch? master branch supports pyfakefs.

**Pull request merged**
