### PR TITLE
[Arista] Update platform drivers submodules

### PR DESCRIPTION
**Pull request by andywongarista**
- Fix `thermal.get_position_in_parent` issue which causes test_snmp_phy_entity failure
- Add support for xcvr thermal info so that thermalctld can incorporate it into the cooling algorithm (QSFP and OSFP/QSFP-DD modules only)
- Add improvements to `arista` CLI

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

**Comment by jleveque** [comment]
@andywongarista: Would it be possible for you to backport the `thermal.get_position_in_parent` bug fix to the 202012 branch also, please?

**Comment by andywongarista** [comment]
> @andywongarista: Would it be possible for you to backport the `thermal.get_position_in_parent` bug fix to the 202012 branch also, please?

Oops, this slipped under my radar. I'll look into backporting the bug fix.

**Comment by yxieca** [comment]
@andywongarista do we need same update on 202012 branch?

**Comment by andywongarista** [comment]
> @andywongarista do we need same update on 202012 branch?

Yes, actually. The xcvr thermal support is also something we want to have for 202012.

**Comment by andywongarista** [comment]
Backported fix for 202012: https://github.com/Azure/sonic-buildimage/pull/7916
Have decided not to include the xcvr thermal support for 202012 as I realized it depends on a large number of other changes that are likely not worth pulling into the release.

**Pull request merged**
