### PR TITLE
[device] Upgrade as 7726-32x with BCM SAI 3.5.3.1

### PR DESCRIPTION
**Pull request by dereksun01**
Signed-off-by: derek_sun derek_sun@edge-core.com

What I did
Modify SDK configuration and add LED control binary files.

How I did it
Change SDK configuration file, config file path and add LED control binary files.

How to verify it
1)Jenkins r138.
2)rebuilding SONiC.

Description for the changelog
Change configuration file, config file path and LED control binary files.

A picture of a cute animal (not mandatory but encouraged)

### CODE REVIEW

**Comment by jleveque** [comment]
Retest vs please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by dereksun01** [comment]
Do your mean to retest vs and vsimage? how to retest this procedure? thanks.

**Comment by jleveque** [comment]
@dereksun01: Those comments aren't directed at you. They are special phrases that cause our Jenkins server to re-run check builds. As you can see below, the vs and vsimage checks failed.

**Comment by jleveque** [comment]
Retest vs please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by dereksun01** [comment]
Retest vsimage please

**Comment by dereksun01** [comment]
Retest vsimage please

**Comment by dereksun01** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by jleveque** [comment]
Retest this please

**Comment by dereksun01** [comment]
Retest broadcom please

**Comment by dereksun01** [comment]
Retest broadcom please

**Comment by dereksun01** [comment]
Dear Joe,

Can this PR merge into master branch? thanks.

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by dereksun01** [comment]
Retest broadcom please

**Comment by dereksun01** [comment]
Retest broadcom please

**Comment by MalteJ** [comment]
Retest broadcom please

**Comment by dereksun01** [comment]
Retest broadcom please

**Comment by dereksun01** [comment]
Dear lguohan,

Could you review this PR? If this PR has any need to improve, please free feel to let me know, thanks.

**Comment by dereksun01** [comment]
Refer PR-4418
(https://github.com/Azure/sonic-buildimage/pull/4418)

**Pull request closed without merging**
