### PR TITLE
[device/celestica]: Fix failed test cases of DX010 platform APIs

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- Why I did it**
- To fix failed test cases of DX010 platform APIs that found on [platform_tests](https://github.com/Azure/sonic-mgmt/tree/master/tests/platform_tests/api) script

**- How I did it**
1. Add device/celestica/x86_64-cel_seastone-r0/platform.json 
2. Update functions to support python3.7
3. Add more functions follow latest sonic_platform_base
4. Fix the bug

 **- How to verify it**
- Run  [platform_tests](https://github.com/Azure/sonic-mgmt/tree/master/tests/platform_tests/api) script

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [x] 201911
- [x] 202006
- [x] 202012

Signed-off-by: Wirut Getbamrung [wgetbumr@celestica.com]

### CODE REVIEW

**Comment by nasbdh9** [comment]
can you please resolve merge conflict?

**Review by jleveque — CHANGES_REQUESTED** [review]
@mudsut4ke: Please fix the new LGTM alerts.

**Review by jleveque — APPROVED** [review]

**Comment by nasbdh9** [comment]
ping @lguohan

**Comment by nasbdh9** [comment]
Can these changes be merge ?

**Pull request merged**
