### PR TITLE
[202111][Mellanox] Update SDK/FW to 4.5.1500/2010.1500 and SAI version to 1.21.1.1

### PR DESCRIPTION
**Pull request by dprital**
#### Why I did it

Update SDK/FW to 4.5.1500/2010.1500 and SAI version to 1.21.0

SDK/FW features

* Added support for Finisar DR4 (FTCD4523E2PCM) on Spectrum-2 and Spectrum-3 systems.

SAI Features

* ECMP overlay support for IPv6
* BFD offloading / 4K scale
* Host interface user traps + improved trap registration (table entry)
* gcc11 compilation fixes
* Read support for ACL redirect action 
* Optimize ECMP DB size
* Buffer descriptors new defaults
* Updated port mapping for SN2201

SAI Fixes
* Debug counter removal when configured with all drop reasons

#### How I did it

Update submodules of both SDK and SAI

#### How to verify it

Run full sonic-mgmt regression

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Review by cbpaviz — APPROVED** [review]

**Comment by liat-grozovik** [comment]
we will issue another SDK.FW bundle towards this release branch

**Pull request closed without merging**
