### PR TITLE
management vrf using vrf function of new kernel

### PR DESCRIPTION
**Pull request by batmancn**
- What I did

Implement management vrf function follow [this spec](https://github.com/Azure/SONiC/blob/310de5a9d649481e23ec3b048cbe90242c6e063f/mgmt-vrf-design-doc.md), phase 1. This PR based on #2348 .

#2405 also define management vrf function, by namespace. This is another way to implement management vrf using vrf function in new kernel 4.5.

- How I did it

I use DB to set management vrf.
I use 'interfaces-config.sh' to trigger network restart.
For details, refer to 'How to verify it' section.

- How to verify it

1. use default DB settings to start SONiC
2. copy modified files as bellow
```
scp ./files/image_config/interfaces/interfaces.j2 root@172.18.8.213:/usr/share/sonic/templates/interfaces.j2
```
3. use these steps to add management vrf in DB
```
# cat /root/mgmt-vrf.del.json
{
    "MGMT_INTERFACE": {
        "eth0|172.18.8.213/24": null
    }
}

# config load -y /root/mgmt-vrf.del.json

# cat /root/mgmt-vrf.add.json
{
    "MGMT_INTERFACE": {
        "eth0|172.18.8.213/24": {
            "gwaddr": "172.18.8.1",
            "vrfname": "mgmtvrf"
        }
    }
}

# config load -y /root/mgmt-vrf.add.json
```
4. use this command to restart network and set management vrf
```
bash /usr/bin/interfaces-config.sh
```
5. use this command to verify
```
root@sonic:~# ip route show table 1001
default via 172.18.8.1 dev eth0
broadcast 172.18.8.0 dev eth0 proto kernel scope link src 172.18.8.213
172.18.8.0/24 dev eth0 proto kernel scope link src 172.18.8.213
local 172.18.8.213 dev eth0 proto kernel scope host src 172.18.8.213
broadcast 172.18.8.255 dev eth0 proto kernel scope link src 172.18.8.213
```
6. use these steps to del management vrf in DB
```
# cat /root/mgmt-vrf.del.json
{
    "MGMT_INTERFACE": {
        "eth0|172.18.8.213/24": null
    }
}

# config load -y /root/mgmt-vrf.del.json

# cat /root/mgmt-vrf.old.json
{
    "MGMT_INTERFACE": {
        "eth0|172.18.8.213/24": {
            "gwaddr": "172.18.8.1"
        }
    }
}

# config load -y /root/mgmt-vrf.old.json
```
7. use this command to restart network and set management vrf
```
bash /usr/bin/interfaces-config.sh
```
8. use these command to verify
```
# ip route show table 1001

# ip route show
default via 172.18.8.1 dev eth0 proto zebra
...
172.18.8.0/24 dev eth0 proto kernel scope link src 172.18.8.213
240.127.1.0/24 dev docker0 proto kernel scope link src 240.127.1.1 linkdown
```

- Known issue

Services based on old socket will be break down in a short time, like sshd/ntpd/logd...

### CODE REVIEW

**Comment by lguohan** [comment]
@nikos-github , you are using ifupdown2 to bring up eth0, do you have that PR. i think that will simplify the template here?

**Comment by nikos-github** [comment]
@batmancn The table with ifupdown2 needs to be in the 1001 to 1255 range when you specify it.

**Comment by batmancn** [comment]
Oh, this patch could not work. If it's my mistake?

This is the /etc/network/interfaces I process
```
root@sonic:~# cat /etc/network/interfaces
#
# =============== Managed by SONiC Config Engine DO NOT EDIT! ===============
# generated from /usr/share/sonic/templates/interfaces.j2 using sonic-cfggen
# file: /etc/network/interfaces
#
# The loopback network interface
auto lo
iface lo inet loopback
# Use command 'ip addr list dev lo' to check all addresses
iface lo inet static
    address 10.1.0.1
    netmask 255.255.255.255
#

auto mgmt
iface mgmt # this is line 16
    vrf-table 1001

# The management network interface
auto eth0
iface eth0 inet dhcp
    vrf mgmt
#
```

This is the error I got
```
-- The result is failed.
Nov 07 18:56:05 sonic systemd[1]: networking.service: Unit entered failed state.
Nov 07 18:56:05 sonic systemd[1]: networking.service: Failed with result 'exit-code'.
Nov 07 18:57:01 sonic CRON[6687]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 07 18:57:01 sonic CRON[6688]: (root) CMD (/usr/sbin/logrotate /etc/logrotate.conf > /dev/null 2>&1)
Nov 07 18:57:01 sonic CRON[6687]: pam_unix(cron:session): session closed for user root
Nov 07 18:58:01 sonic CRON[6705]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 07 18:58:01 sonic CRON[6706]: (root) CMD (/usr/sbin/logrotate /etc/logrotate.conf > /dev/null 2>&1)
Nov 07 18:58:01 sonic CRON[6705]: pam_unix(cron:session): session closed for user root
Nov 07 18:58:13 sonic kernel: perf: interrupt took too long (2506 > 2500), lowering kernel.perf_event_max_sample_rate to 79750
Nov 07 18:58:14 sonic su[6443]: pam_unix(su:session): session closed for user root
Nov 07 18:59:01 sonic CRON[6723]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 07 18:59:01 sonic CRON[6724]: (root) CMD (/usr/sbin/logrotate /etc/logrotate.conf > /dev/null 2>&1)
Nov 07 18:59:01 sonic CRON[6723]: pam_unix(cron:session): session closed for user root
Nov 07 18:59:42 sonic systemd[1]: Starting Raise network interfaces...
-- Subject: Unit networking.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit networking.service has begun starting up.
Nov 07 18:59:42 sonic sh[6748]: ifquery: /etc/network/interfaces:16: unknown or no address type and no inherits keyword specified
Nov 07 18:59:42 sonic sh[6748]: ifquery: couldn't read interfaces file "/etc/network/interfaces"
Nov 07 18:59:42 sonic ifup[6751]: ifup: /etc/network/interfaces:16: unknown or no address type and no inherits keyword specified
Nov 07 18:59:42 sonic ifup[6751]: ifup: couldn't read interfaces file "/etc/network/interfaces"
Nov 07 18:59:42 sonic systemd[1]: networking.service: Main process exited, code=exited, status=1/FAILURE
Nov 07 18:59:42 sonic systemd[1]: Failed to start Raise network interfaces.
-- Subject: Unit networking.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit networking.service has failed.
--
-- The result is failed.
Nov 07 18:59:42 sonic systemd[1]: networking.service: Unit entered failed state.
Nov 07 18:59:42 sonic systemd[1]: networking.service: Failed with result 'exit-code'.
```

**Comment by nikos-github** [comment]
@batmancn Some changes from https://github.com/Azure/sonic-buildimage/pull/2348 are also needed.

**Comment by nikos-github** [comment]
A couple of things. You can't have both ifupdown and ifupdown2. Also, when you specify dhcp for eth0 instead of the static IP that you have in config_db.json, you will clearly get the discrepancy you are observing. The point Guohan was making is that even with static IP assignment, the template you have for eth0 in the mgmt vrf can be simplified.

**Comment by nikos-github** [comment]
@batmancn The builds are failing because of unit tests. Have a look at src/sonic-config-engine/tests/test_j2files.py in def test_interfaces(self). I think we also want to parameterize this configuration unless the plan is to have it on by default for both dhcp and static address assignment. Please check with @lguohan.

**Pull request closed without merging**
