### PR TITLE
[BFN] Fixed settings for BMC interface

### PR DESCRIPTION
**Pull request by tkerykx**
Signed-off-by: Taras Keryk <tarasx.keryk@intel.com>

#### Why I did it
In some situations, the connection to the BMC may be lost when the ip settings differ on the BMC and CPU (SONiC) sides
#### How I did it
I changed ipv6 neighbor base_reachable_time_ms on the CPU (SONiC). Currently, base_reachable_time_ms  on the CPU and BMC sides will be the same.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by akokhan** [comment]
Please add the same changes for Maveriks
https://github.com/Azure/sonic-buildimage/blob/master/platform/barefoot/sonic-platform-modules-bfn/configs/network/interfaces.d/usb0

**Review by akokhan — APPROVED** [review]

**Comment by tkerykx** [comment]
@prgeor, can you please review
Thanks!

**Comment by akokhan** [comment]
@lguohan , could you please take a look?

**Comment by tkerykx** [comment]
@prgeor, can you please review?
Thanks!

**Comment by tkerykx** [comment]
@prgeor, can you please review?
Thanks!

**Comment by tkerykx** [comment]
@prgeor, can you please review?
Thanks!

**Review by prgeor — APPROVED** [review]

**Pull request merged**
