### PR TITLE
DellEMC: Skip thermalctld (S6000, S6100, Z9100 and Z9264) and thermal platform API changes

### PR DESCRIPTION
**Pull request by ArunSaravananBalachandran**
**- Why I did it**

-  Skip thermalctld in DellEMC S6000, S6100, Z9100 and Z9264 platforms.
-  Change the return type of thermal Platform APIs in DellEMC S6000, S6100, Z9100 and Z9264 platforms to 'float'.

**- How I did it**

- Add 'skip_thermalctld:true' in pmon_daemon_control.json for DellEMC S6000, S6100, Z9100 and Z9264 platforms.
- Made changes in thermal.py, for 'get_temperature', 'get_high_threshold' and 'get_low_threshold' to return 'float' value.

**- How to verify it**

- Check thermalctld is not running in 'pmon'.
- Wrote a python script to load Chassis class and then call the APIs accordingly and verify the return type.

UT logs : [UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/4680341/UT_logs.txt)
Test Script : [thermal_test_py.txt](https://github.com/Azure/sonic-buildimage/files/4680345/thermal_test_py.txt)
 

**- Description for the changelog**

DellEMC: Skip thermalctld (S6000, S6100, Z9100 and Z9264) and thermal platform API changes

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by ArunSaravananBalachandran** [comment]
This PR needs to be picked for 201911 branch.

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by abdosi** [comment]
@ArunSaravananBalachandran Please create PR for 201911. Cherry-pick has conflict.

@rlhui

**Comment by ArunSaravananBalachandran** [comment]
#4752 has been raised for 201911 branch

**Pull request merged**
