### PR TITLE
CRM init config for SRV6 Nexthop and MY_SID resource

### PR DESCRIPTION
**Pull request by kperumalbfn**
Why I did it
Enable CRM for SRV6 Nexthop and SRV6 MY_SID entries.

How I did it
To show CRM for SRV6 objects.

How to verify it
crm show command

### CODE REVIEW

**Comment by kperumalbfn** [comment]
@lguohan Could you please merge this CRM init config for the recent SRV6 changes.

**Review by prsunny — APPROVED** [review]

**Comment by kperumalbfn** [comment]
Thanks @prsunny Couldn't restart the sanity. '/azp or /azpw run' comment is not working to restart the sanity.

**Comment by reshmaintel** [comment]
@lguohan Could you please complete the review of this PR. Copying @prsunny @zhangyanzhao as well.
This is the only PR still open. Thanks a lot.

**Comment by kperumalbfn** [comment]
@lguohan Could you approve and merge this PR.

**Comment by reshmaintel** [comment]
@lguohan @prsunny @zhangyanzhao 
Thank you Prince.
Hi Guohan, Could you please help with this merge. Thank you.

**Comment by reshmaintel** [comment]
@kperumalbfn Hi Kumaresh, could you please look into these failures. Thanks

**Comment by reshmaintel** [comment]
@prsunny @lguohan CI issue for https://github.com/Azure/sonic-buildimage/pull/9238 is seen for  other PRs as well. This is not specific to our feature changes. Could you please suggest next steps forward. Thanks.

**Comment by prsunny** [comment]
Please rebase to the latest, currently master PRs are seen passing.

**Review by reshmaintel — APPROVED** [review]

**Comment by kperumalbfn** [comment]
@prsunny Rebase to master didn't help, Master sanities are still failing. Few other PRs are also failing at the same stage.

test_bgp_update_timer
KeyError: 'tp_len'

=========================== short test summary info ============================
FAILED bgp/test_bgp_update_timer.py::test_bgp_update_timer - KeyError: 'tp_len'
========================== 1 failed in 268.48 seconds ==========================

**Comment by kperumalbfn** [comment]
@prsunny All sanities have passed, please merge

**Comment by reshmaintel** [comment]
@lguohan @prsunny  All Sanities are finally passing. Could you please complete the merge of this PR. Thank you.

**Pull request merged**
