### PR TITLE
[Mellanox] support newly added reboot cause

### PR DESCRIPTION
**Pull request by keboliu**
Signed-off-by: Kebo Liu <kebol@nvidia.com>

#### Why I did it
Implement newly added reboot causes in PR https://github.com/Azure/sonic-platform-common/pull/277

#### How I did it
Map the reboot cause sysfs to the newly added reboot causes.

#### How to verify it
manual test, check whether the reboot cause is correct after rebooting the switch in various ways.
run the community reboot test to see whether the reboot cause checker is passing.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Review by sujinmkang — APPROVED** [review]

**Comment by keboliu** [comment]
PR checker fail depends on test fix: https://github.com/Azure/sonic-mgmt/pull/5509

**Review by stephenxs — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
