### PR TITLE
sonic-config-engine uses libswsscommon instead of swsssdk

### PR DESCRIPTION
**Pull request by qiluo-msft**
**- Why I did it**
swsssdk will be deprecated. Migrate sonic-config-engine to use libswsscommon library instead

**- How I did it**

**- How to verify it**
Unit test

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by lguohan — COMMENTED** [review]
can you check vs test failure?

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by lguohan** [comment]
looks like vstest failed again. does not seem to be random event, need investigation.

**Comment by qiluo-msft** [comment]
ACK, noticing the bug and working on it.

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Review by jleveque — APPROVED** [review]

**Pull request merged**
