### PR TITLE
[ECMP][Multi-ASIC] Have different ECMP seed value on each ASIC

### PR DESCRIPTION
**Pull request by smaheshm**
**- Why I did it**

Create different ECMP seed value on each ASIC to reduce probability of traffic hot spots within the multi ASIC switch.

**- How I did it**

Create ECMP seed value based on the name space ID.

**- How to verify it**

Unit tests and manual verification on multi ASIC switch.

```
admin@str-n3164-acs-2:~$ docker exec  swss0 cat /etc/swss/config.d/switch.json
[
    {
        "SWITCH_TABLE:switch": {
            "ecmp_hash_seed": "10",
            "lag_hash_seed": "10",
            "fdb_aging_time": "600"
        },
        "OP": "SET"
    }
]

admin@str-n3164-acs-2:~$ docker exec  swss1 cat /etc/swss/config.d/switch.json                                                                                                       
[
    {
        "SWITCH_TABLE:switch": {
            "ecmp_hash_seed": "11",
            "lag_hash_seed": "11",
            "fdb_aging_time": "600"
        },
        "OP": "SET"
    }
]

admin@str-n3164-acs-2:~$ docker exec  swss2 cat /etc/swss/config.d/switch.json                                                                                                       
[
    {
        "SWITCH_TABLE:switch": {
            "ecmp_hash_seed": "12",
            "lag_hash_seed": "12",
            "fdb_aging_time": "600"
        },
        "OP": "SET"
    }
]

admin@str-n3164-acs-2:~$ docker exec  swss3 cat /etc/swss/config.d/switch.json                                                                                                       
[
    {
        "SWITCH_TABLE:switch": {
            "ecmp_hash_seed": "13",
            "lag_hash_seed": "13",
            "fdb_aging_time": "600"
        },
        "OP": "SET"
    }
]

admin@str-n3164-acs-2:~$ docker exec  swss4 cat /etc/swss/config.d/switch.json                                                                                                       
[
    {
        "SWITCH_TABLE:switch": {
            "ecmp_hash_seed": "14",
            "lag_hash_seed": "14",
            "fdb_aging_time": "600"
        },
        "OP": "SET"
    }
]

admin@str-n3164-acs-2:~$ docker exec  swss5 cat /etc/swss/config.d/switch.json                                                                                                       
[
    {
        "SWITCH_TABLE:switch": {
            "ecmp_hash_seed": "15",
            "lag_hash_seed": "15",
            "fdb_aging_time": "600"
        },
        "OP": "SET"
    }
]

```

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

sonic-cfggen:
* Added "namespace_id" in device metadata:

"DEVICE_METADATA': { 'localhost': {'namespace_id': ""}}"

switch.json.j2:

* Update ECMP seed value based on the "namespace_id" value.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by smaheshm** [comment]
@lguohan @prsunny  This PR generates different values of ECMP seed for each ASIC. After discussion within our team it was suggested to use same hash seed for all front end ASICs and another value for backend ASICs, but same value on all backend ASICs. 
Following the current tier model it would make sense to have ECMP seed values based on the tier the ASIC is connected to.
- Front end ASICs - tier0
- Front end ASICs - tier2
- Back ASICs.

comments?

**Comment by prsunny** [comment]
> @lguohan @prsunny This PR generates different values of ECMP seed for each ASIC. After discussion within our team it was suggested to use same hash seed for all front end ASICs and another value for backend ASICs, but same value on all backend ASICs.
> Following the current tier model it would make sense to have ECMP seed values based on the tier the ASIC is connected to.
> 
> * Front end ASICs - tier0
> * Front end ASICs - tier2
> * Back ASICs.
> 
> comments?

lgtm, @lguohan , could you comment?

**Comment by smaheshm** [comment]
> > @lguohan @prsunny This PR generates different values of ECMP seed for each ASIC. After discussion within our team it was suggested to use same hash seed for all front end ASICs and another value for backend ASICs, but same value on all backend ASICs.
> > Following the current tier model it would make sense to have ECMP seed values based on the tier the ASIC is connected to.
> > 
> > * Front end ASICs - tier0
> > * Front end ASICs - tier2
> > * Back ASICs.
> > 
> > comments?
> 
> lgtm, @lguohan , could you comment?


Challenge is to determine if ASIC has ports connected to tier0 or tier2. It's possible ASIC has ports connected to both tiers. If we use same seed for front end ASICs and a different seed for backend ASICs, is there an issue with this approach.

**Comment by lguohan** [comment]
i think the potential issues is that the hash seed should be decided by the layer and namespace id.

**Comment by smaheshm** [comment]
> i think the potential issues is that the hash seed should be decided by the layer and namespace id.

That's how it is in this PR. ECMP seed generated is different in each namespace. The concern raised was:

- a flow entering different ASICs will have different outgoing ports. 

If this is not a concern then this PR is ready for review.

**Review by lguohan — APPROVED** [review]

**Pull request merged**
