### PR TITLE
[Mellanox] Update SAI/SDK/FW versions

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
* SAI implementation 1.15.5 (headers 1.5.1)
* SDK 4.3.2908
* FW xx.2000.2720

Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>

**- What I did**
Update SAI/SDK/FW versions:
* SAI implementation 1.15.5 (headers 1.5.1)
* SDK 4.3.2908
* FW xx.2000.2720

**- How I did it**
Updated appropriate sub-modules and versions

**- How to verify it**
Build an image and verify all is up and running

**- Description for the changelog**
[Mellanox] Update SAI/SDK/FW versions

### CODE REVIEW

**Comment by volodymyrsamotiy** [comment]
Depends on the below PRs and should be merged after below and ```sonic-swss``` sub-module updated.
* https://github.com/Azure/sonic-swss/pull/1166
* https://github.com/Azure/sonic-swss/pull/1158
* https://github.com/Azure/sonic-swss/pull/1108

**Comment by volodymyrsamotiy** [comment]
retest this please

**Comment by volodymyrsamotiy** [comment]
retest vs please

**Comment by volodymyrsamotiy** [comment]
retest this please

**Comment by liat-grozovik** [comment]
retest vs please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by volodymyrsamotiy** [comment]
**PLEASE DON'T MERGE UNTIL ```SWSS``` sub-module is updated to include below merged PRs:**
* Azure/sonic-swss#1166
* Azure/sonic-swss#1158
* Azure/sonic-swss#1108

**Comment by volodymyrsamotiy** [comment]
This PR should be cherry-picked to ```bmtor``` and ```201911``` branched together with PR https://github.com/Azure/sonic-buildimage/pull/3967

**Pull request merged**
