### PR TITLE
[sonic-py-swsssdk] update submodule for using correct connect parameter number

### PR DESCRIPTION
**Pull request by dzhangalibaba**
update submodule for using correct connect parameter number
    * [MultiDB] fix wrong parameter number in interface.py (#88)

Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

### CODE REVIEW

**Comment by lguohan** [comment]
retest broadcom please

**Comment by qiluo-msft** [comment]
retest broadcom please

**Review by qiluo-msft — APPROVED** [review]

**Comment by lguohan** [comment]
do we need to backport?

**Comment by qiluo-msft** [comment]
Need for 201911. I added labels to original PRs.

**Pull request merged**
