### PR TITLE
[yang_model_test]: Tests for default value of docker_routing_config_m…

### PR DESCRIPTION
**Pull request by praveen-li**
…ode and Empty ACL ports.

Signed-off-by: Praveen Chaudhary <pchaudhary@linkedin.com>

**- Why I did it**
Tests for default value of docker_routing_config_mode and Empty ACL ports.
**- How I did it**
Added tests in src/sonic-yang-models/tests/yang_model_tests/test_yang_model.py
**- How to verify it**
Build The PKG.
**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by praveen-li** [comment]
retest vsimage please

**Comment by praveen-li** [comment]
retest Azure.sonic-buildimage  please

**Comment by praveen-li** [comment]
retest kvmtest please

**Comment by praveen-li** [comment]
@lguohan @renukamanavalan : Any idea how we can rerun Azure.sonic-buildimage,  "retest Azure.sonic-buildimage please" ?

**Review by shi-su — APPROVED** [review]

**Pull request merged**
