### PR TITLE
[mellanox] temporary workaround for watchdog type 3

### PR DESCRIPTION
**Pull request by stepanblyschak**
This is temporary implementation based on a seperate
script which interacts with watchdog.
Ideally there should be a kernel driver, then
this diff can be reverted.

Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

*DEPENDS ON NEW HW-MGMT*

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by stepanblyschak** [comment]
retest this please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
retest this please

**Comment by stepanblyschak** [comment]
Not needed, since watchdog is supported in driver

**Pull request closed without merging**
