### PR TITLE
[yang]: Add Yang models for table BGP_ALLOWED_PREFIXES

### LINKED ISSUE #9866: [yang] Need Yang for BGP_ALLOWED_PREFIXES table
#### Description
We don't have yang model about BGP_ALLOWED_PREFIXES table. 
It is need by bgp prefix hijacking from Generic Config Updater E2E test.

#### Steps to reproduce the issue:
1.
```
admin@vlab-01:~/hijack$ sudo config apply-patch -i /FEATURE -i /QUEUE -i /SCHEDULER add.json
Patch Applier: Patch application starting.
Patch Applier: Patch: [{"op": "add", "path": "/BGP_ALLOWED_PREFIXES", "value": {"DEPLOYMENTID|4": {"default_action": "deny", "prefixes_v4": ["10.111.14.26/32", "51.4.22.0/23"]}}}]
Patch Applier: Getting current config db.
Patch Applier: Simulating the target full config after applying the patch.
Patch Applier: Validating target config does not have empty tables, since they do not show up in ConfigDb.
Patch Applier: Sorting patch updates.
Note: Below table(s) have no YANG models:
BGP_PEER_RANGE, CONSOLE_SWITCH, DEVICE_NEIGHBOR_METADATA, DHCP_SERVER, KDUMP, RESTAPI, SNMP, SNMP_COMMUNITY, TELEMETRY, BGP_ALLOWED_PREFIXES,
Note: Below table(s) have no YANG models:
BGP_ALLOWED_PREFIXES,                     <============================
Failed to apply patch
Usage: config apply-patch [OPTIONS] PATCH_FILE_PATH
Try "config apply-patch -h" for help.

Error: Given YANG covered config patch is not valid because it has changes to tables without YANG models

```

2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

### PR DESCRIPTION
**Pull request by StormLiangMS**
#### Why I did it
end2end test is blocked by Yang model for BGP allowed prefix list.

#### How I did it
Create new yang files for BGP allowed prefix list, and add UT.

#### How to verify it
Run UT for sonic-yang-models.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

#### Link to config_db schema for YANG module changes

Fix #9866

### CODE REVIEW

**Comment by wen587** [comment]
Seems it doesn't parse correctly. Please see my below test.
1. check that current config pass yang verification
```
admin@vlab-01:~$ cat verify_configDB_yang.py
import subprocess
import sonic_yang
import json
def get_config_db_json():
    cmd = "show runningconfiguration all"
    result = subprocess.Popen(cmd, shell=True, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    text, err = result.communicate()
    return json.loads(text)
configDbJson = get_config_db_json()
sy = sonic_yang.SonicYang("/usr/local/yang-models")
sy.loadYangModel()
sy.loadData(configDbJson )
sy.validate_data_tree()
admin@vlab-01:~$ python verify_configDB_yang.py
Note: Below table(s) have no YANG models:
CONSOLE_SWITCH, DEVICE_NEIGHBOR_METADATA, DHCP_SERVER, KDUMP, RESTAPI, SNMP, SNMP_COMMUNITY, TELEMETRY,
```
2. Add bgp prefix config and check it takes effect
```
admin@vlab-01:~$ cat hijack/add.load
{
    "BGP_ALLOWED_PREFIXES": {
        "DEPLOYMENT_ID|0": {
            "prefixes_v4": [
                "10.20.0.0/16"
            ],
            "prefixes_v6": [
                "fc02:20::/64"
            ]
        }
    }
}
admin@vlab-01:~$ sudo config load -y hijack/add.load
Running command: /usr/local/bin/sonic-cfggen -j hijack/add.load --write-to-db
admin@vlab-01:~$ show run bgp | grep prefix
...
ip prefix-list PL_ALLOW_LIST_DEPLOYMENT_ID_0_COMMUNITY_empty_V4 seq 30 permit 10.20.0.0/16 le 32  <======
...
ipv6 prefix-list PL_ALLOW_LIST_DEPLOYMENT_ID_0_COMMUNITY_empty_V6 seq 30 permit fc02:20::/64 le 128  <=====
...
```
3. Run yang verification again and it fails.
```
admin@vlab-01:~$ python verify_configDB_yang.py
Note: Below table(s) have no YANG models:
CONSOLE_SWITCH, DEVICE_NEIGHBOR_METADATA, DHCP_SERVER, KDUMP, RESTAPI, SNMP, SNMP_COMMUNITY, TELEMETRY,
sonic_yang(3):All Keys are not parsed in BGP_ALLOWED_PREFIXES
dict_keys(['DEPLOYMENT_ID|0'])
sonic_yang(3):exceptionList:[]
sonic_yang(3):Data Loading Failed:All Keys are not parsed in BGP_ALLOWED_PREFIXES
dict_keys(['DEPLOYMENT_ID|0'])
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sonic_yang_ext.py", line 1062, in loadData
    self._xlateConfigDB(xlateFile=xlateFile)
  File "/usr/local/lib/python3.9/dist-packages/sonic_yang_ext.py", line 695, in _xlateConfigDB
    self._xlateConfigDBtoYang(jIn, yangJ)
  File "/usr/local/lib/python3.9/dist-packages/sonic_yang_ext.py", line 682, in _xlateConfigDBtoYang
    self._xlateContainer(cmap['container'], yangJ[key][subkey], \
  File "/usr/local/lib/python3.9/dist-packages/sonic_yang_ext.py", line 662, in _xlateContainer
    raise(Exception("All Keys are not parsed in {}\n{}".format(table, \
Exception: All Keys are not parsed in BGP_ALLOWED_PREFIXES
dict_keys(['DEPLOYMENT_ID|0'])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/verify_configDB_yang.py", line 12, in <module>
    sy.loadData(configDbJson )
  File "/usr/local/lib/python3.9/dist-packages/sonic_yang_ext.py", line 1072, in loadData
    raise SonicYangException("Data Loading Failed\n{}".format(str(e)))
sonic_yang_ext.SonicYangException: Data Loading Failed
All Keys are not parsed in BGP_ALLOWED_PREFIXES
dict_keys(['DEPLOYMENT_ID|0'])

```

**Comment by ganglyu** [comment]
Please resolve the conflicts.

**Review by wen587 — APPROVED** [review]
LGTM. Please wait for other reviewer's approval.

**Comment by StormLiangMS** [comment]
When I do the rebase, include too much commits which not related to this topic, will close this one and open a new PR for this issue.

**Pull request closed without merging**
