### PR TITLE
[201811][DELL] S6100, Z9100 Last Reboot Reason Watchdog, Thermal Support

### PR DESCRIPTION
**Pull request by sridhar-ravindran**
**- What I did**
Added support for Watchdog & Thermal events in Last Reboot Reason "show reboot-cause" command
**- How I did it**
On branch lrr_watchdog_nov
Your branch is up-to-date with 'upstream/201811'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   files/image_config/platform/rc.local
        modified:   platform/broadcom/sonic-platform-modules-dell/common/platform_reboot
        modified:   platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
        modified:   platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-z9100.install
        new file:   platform/broadcom/sonic-platform-modules-dell/s6100/scripts/fastboot_plugin
        modified:   platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh
        new file:   platform/broadcom/sonic-platform-modules-dell/s6100/scripts/track_reboot_reason.sh
        modified:   platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
        new file:   platform/broadcom/sonic-platform-modules-dell/z9100/scripts/fastboot_plugin
        new file:   platform/broadcom/sonic-platform-modules-dell/z9100/scripts/track_reboot_reason.sh
        modified:   platform/broadcom/sonic-platform-modules-dell/z9100/scripts/z9100_platform.sh
        modified:   platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/chassis.py

Added support to track watchdog events and thermal overload of ASIC & CPU

**- How to verify it**
Added the Unit Test Results.
**- Description for the changelog**

[DELL] S6100, Z9100 Last Reboot Reason Watchdog, Thermal Support

[LRR_UnitTesting_Nov.txt](https://github.com/Azure/sonic-buildimage/files/3659306/LRR_UnitTesting_Nov.txt)

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by sujinmkang** [comment]
@sridhar-ravindran watchdog reboot reason doesn't work consistently on this branch.
Can you check why it's not working consistently?
++++++++++++++++++++++++++++++++++++++
admin@str-s6100-acs-2:~$ show reboot-cause
Unknown
admin@str-s6100-acs-2:~$ sudo cat /var/log/syslog | grep -a watchdog0
Sep 27 21:08:24.700974 str-s6100-acs-2 CRIT kernel: [  629.250819] watchdog: watchdog0: watchdog did not stop!
Sep 27 21:13:25.657467 str-s6100-acs-2 CRIT kernel: [  178.895828] watchdog: watchdog0: watchdog did not stop!
admin@str-s6100-acs-2:~$ sudo cat /var/log/syslog | grep -a watchdog
Sep 27 21:08:24.700974 str-s6100-acs-2 CRIT kernel: [  629.250819] watchdog: watchdog0: watchdog did not stop!
Sep 27 21:10:30 sonic kernel: [    0.076100] NMI watchdog: enabled on all CPUs, permanently consumes one hw-PMU counter.
Sep 27 21:10:30 sonic kernel: [    0.076100] NMI watchdog: enabled on all CPUs, permanently consumes one hw-PMU counter.
Sep 27 21:13:25.657467 str-s6100-acs-2 CRIT kernel: [  178.895828] watchdog: watchdog0: watchdog did not stop!
Sep 27 21:14:24.925744 str-s6100-acs-2 INFO kernel: [    0.076117] NMI watchdog: enabled on all CPUs, permanently consumes one hw-PMU counter.
Sep 27 21:20:52.822780 str-s6100-acs-2 INFO kernel: [    0.076068] NMI watchdog: enabled on all CPUs, permanently consumes one hw-PMU counter.
Sep 27 21:26:41.882124 str-s6100-acs-2 INFO kernel: [    0.076077] NMI watchdog: enabled on all CPUs, permanently consumes one hw-PMU counter.
admin@str-s6100-acs-2:~$ cat /sys/devices/platform/SMF.512/hwmon/hwmon1/mb_poweron_reason
0x99
++++++++++++++++++++++++++++++++

**Comment by jleveque** [comment]
@sujinmkang: can you please format your comment for readbility? Use a code block (three backticks). Reference: https://guides.github.com/features/mastering-markdown/

**Comment by paavaanan** [comment]
@sujinmkang will check and get back on this.

**Comment by sridhar-ravindran** [comment]
Hi,
We have raised https://github.com/Azure/sonic-buildimage/pull/3767 to support this feature in master.
Once approved, will raise a new PR for this branch. Request you to review the same.

**Pull request closed without merging**
