### PR TITLE
[src/sonic-utilities] Advance sonic-utilities submodule

### PR DESCRIPTION
**Pull request by daall**
Submodule src/sonic-utilities 4024019594bc9174374ed3a3b594d8a43299dd07:
> [doc/command-reference.md] dos2unix & remove trailing spaces (#591)
> [show] Add BGP neighbor info to 'show ip/ipv6 interfaces' command output (#598)
> [config]: fix the runtime error of the 'show line' command (#595) (#596)
> Revert "Removed 'show interfaces alias'. (#412)" (#603)
> [debug][undebug] Rework of CLI for BGP (#583)
> Changing "show runningconfiguration interface" to "show runningconfiguration ports" (#600)
> [config] Add commands to add/remove DHCP server address from a VLAN (#585)
> [neighbor_advertiser] Use full vlan name for vxlan tunnel map programming (#604)
> [neighbor_advertise]: Use the existing MIRROR ACL table (#605)
> Read config DB for running interface(s) and display per port/interface (#594)
> [fast/warm reboot] kill radv docker before stopping BGP (#608)
> [config] Add commands for adding/removing syslog servers (#609)
> [config] Call 'systemctl reset-failed' before 'systemctl restart' when restarting services (#607)
> [Command Reference] Add config commands for DHCP relay destination address (#610)
> [config] Add commands for adding/removing NTP servers (#611)
> [neighbor_advertiser]: Add V6 support to mirror ICMPV6 packets (#612)
> [neighbor advertiser] try getting vlan addresses from o.s first (#613)
> [show] Add command 'show runningconfiguration syslog' (#617)
> [show] Add command 'show runningconfig ntp' (#620)
> Added check to config syslog del to verify if ip address was configured. (#622)
> [fast-reboot] Check if ASIC config has changed before warm reboot (#621)

Signed-off-by: Danny Allen <daall@microsoft.com>

### CODE REVIEW

**Comment by daall** [comment]
Please take a look at your commits and let me know if they are OK to be added to the master build image.

**Comment by jleveque** [comment]
Retest this please

**Comment by yxieca** [comment]
retest mellanox please

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by stephenxs** [comment]
It seems that the latest image is broken by [[config] Add commands for adding/removing syslog servers #609](https://github.com/Azure/sonic-utilities/pull/609)  due to the name conflict between newly introduced function "syslog" and the module "syslog".
This causes all commands calling logxxx fail, like "config load_minigraph".

**Pull request merged**
