### PR TITLE
[submodule]: Advance sonic-sairedis

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

#### Why I did it
* To fix https://github.com/Azure/sonic-buildimage/issues/7403

#### How I did it
* Advanced `sonic-sairedis` submodule

#### How to verify it
1. make configure PLATFORM=mellanox
2. make target/sonic-mellanox.bin

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog

```
Commits on Aug 28, 2021
Install sonic-buildimage libnl3 for AZP (#877) cf1af5f

Commits on Aug 29, 2021
Enable test coverage on azure pipeline (#912) 29c454a
Add Globals tests bb6bba8
Fix AttrKeyMap tests 9043005
Add MetaKeyHasher tests 18ab2e5
Add NotificationFactory tests 3bab7b8
Add NotificationFdbEvent tests bc95ac8
Add NotificationPortStateChange tests aca5be6
Add NotificationQueuePfcDeadlock tests 9ae3836
Add NotificationSwitchShutdownRequest tests 9737bad
Add NotificationSwitchStateChange tests 2f90c26
Add OidRefCounter tests 2aebdd4
Add PerformanceIntervalTimer tests 34be0ac
Add PortRelatedSet tests f6356d4
Add SaiAttrWrapper tests 2ebc230
Add SaiAttributeList tests 2ddaff3
Add SaiObject tests f616d1d
Add SaiObjectCollection tests a02281e
Add SaiInterface tests ae47bf1
[meta] Refactor serialization code 6b11376
Update aspell 35400df
Add SaiSerialize tests e286816
[meta] Move NumberOidIndexGenerator to libsaimeta bf066d0
Move serialization meta/tests to gtest 7dbcc5b
Add Legacy tests interface a4a6fc9
Add Legacy FdbEntry tests b55eb6c
Add Legacy NeighborEntry tests b151bab
Add Legacy Vlan tests 0851bfc
Add Legacy RouteEntry tests f89a5a9
Add Legacy Other tests f38ba4e
Update aspell and swss log enter e8fad3b
Remove unnecessary comment from TestNotificationFactory 458ef2a
Add ZeroMQSelectableChannel tests ab9a501
Update MetaKeyHasher tests da63792
Use status log macro in Meta ce4acd8
Add Meta tests 92293df
Add dump method for test debugging in meta 5b2fb70
Add more debug logging in meta dump 253f024
Fix legacy tests 30e4d76
Update .gitignore 68b468c
Fix LegacyVlan flow test ee1a59c

Commits on Aug 30, 2021
Code coverage enable html report directory (#914) ab0fcb9
Remove gcovr htmlcov directory (#915) c3bf1be

Commits on Aug 31, 2021
Fix cast align warning (#894) 2ce0c83

Commits on Sep 01, 2021
[syncd] Add syncd linker -rdynamic flag for better crash reports (#910) f2075ff

Commits on Sep 02, 2021
Fix flex counters logic of converting poll interval to seconds from MS ( 536af40

Commits on Sep 04, 2021
Add sairedis lib unit tests (#919) d8eb0ea
[syncd] Comparison logic workaround for empty buffer profile (#906) 509b888

Commits on Sep 08, 2021
[vs] Fix return statment on hostif create (#923) 1c4f04c
Remove white space endings (#922) f3bc342 

Commits on Sep 09, 2021
[submodule]: Advance SAI to v1.8. (#926) 696ad99 
```

#### A picture of a cute animal (not mandatory but encouraged)
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Comment by nazariig** [comment]
@kcudnik VS build failed with:
```
g++ -L/usr/lib -Wl,-rpath=/usr/lib ./src/obj/switch_sai_rpc_server.o ./src/obj/saiserver.o -o saiserver \
	   ./src/obj/librpcserver.a -lthrift -lpthread -lsaivs -lsaimeta -lsaimetadata
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsaimeta.so: undefined reference to `zmq_getsockopt'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsaimeta.so: undefined reference to `zmq_socket'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsaimeta.so: undefined reference to `zmq_bind'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsaimeta.so: undefined reference to `zmq_send'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsaimeta.so: undefined reference to `zmq_poll'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsaimeta.so: undefined reference to `zmq_close'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsaimeta.so: undefined reference to `zmq_ctx_new'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsaimeta.so: undefined reference to `zmq_recv'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsaimeta.so: undefined reference to `zmq_strerror'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsaimeta.so: undefined reference to `zmq_ctx_destroy'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsaimeta.so: undefined reference to `zmq_errno'
collect2: error: ld returned 1 exit status
```
Can you please have a look?

**Comment by kcudnik** [comment]
Not sure which project is this, but if this is thrift server ~/SAI/test/saithrift/Makefile
```
 37 ifeq ($(platform),vs)
 38 LIBS += -lsaivs -lsaimeta -lsaimetadata -lzmq
 39 else
 40 LIBS += -lsai
 41 endif
```

this was already fixed on in SAI repo, maybe the one SAI in buildimage is still behind ?
```
bfbfa116 (Kamil Cudnik       2021-08-27 19:20:57 +0200  38) LIBS += -lsaivs -lsaimeta -lsaimetadata -lzmq
```

**Comment by nazariig** [comment]
> 
> 
> Not sure which project is this, but if this is thrift server ~/SAI/test/saithrift/Makefile
> 
> ```
>  37 ifeq ($(platform),vs)
>  38 LIBS += -lsaivs -lsaimeta -lsaimetadata -lzmq
>  39 else
>  40 LIBS += -lsai
>  41 endif
> ```
> 
> this was already fixed on in SAI repo, maybe the one SAI in buildimage is still behind ?
> 
> ```
> bfbfa116 (Kamil Cudnik       2021-08-27 19:20:57 +0200  38) LIBS += -lsaivs -lsaimeta -lsaimetadata -lzmq
> ```
> 
> yea just checked is here:
> 
> ```
> '/sonic/src/sonic-sairedis/SAI/test/saithrift'
> ```
> 
> is current build image on master or other branch ? since this fix was not propagated to other branches

@kcudnik nice catch! Please have a look: https://github.com/Azure/sonic-sairedis/pull/926

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
