### PR TITLE
Update Linux kernel from 5.10.46 to 5.10.103

### PR DESCRIPTION
**Pull request by saiarcot895**
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

#### Why I did it

This updates the Linux kernel from 5.10.46 to 5.10.103 to fix some CVEs, and also updates references to the kernel directory for the kernel module builds.

#### How to verify it

Loaded on virtual switch and Broadcom switch, verified that BGP neighbors came up.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by saiarcot895** [comment]
Azure/saibcm-modules#8 needs to be merged first.

**Comment by liat-grozovik** [comment]
@alexrallen could you please review?

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
would be great if you can document what tests you have done?

**Comment by saiarcot895** [comment]
Added it to the PR description

**Pull request merged**
