### PR TITLE
[ethtool] Add ethtool patch to version 5.8 to support QSFP-DD cable parsing

### PR DESCRIPTION
**Pull request by shlomibitton**
Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

**- Why I did it**
Add ethtool patch to version 5.8 to support QSFP-DD cable parsing.

**- How I did it**
Compiled the ethtool from:
https://git.kernel.org/pub/scm/network/ethtool/ethtool.git/commit/?id=88ca347ef35acb16ec0a0107f55ab599ddb18f56
Added it to 'files' directory.
Changed the buiild_debian.sh script to copy the file instead of downloading it.

**- How to verify it**
Build the image with this commit.
try to parse a QSFP-DD cable with the tool - "ethtool -m sfp#"

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by shlomibitton** [comment]
retest vs please

**Comment by shlomibitton** [comment]
retest vsimage please

**Comment by shlomibitton** [comment]
retest vsimage please

**Comment by shlomibitton** [comment]
retest vs please

**Comment by liat-grozovik** [comment]
@jleveque and @lguohan can you please review? if this approach is approved, we will have it as PR ready for merge.

**Comment by lguohan** [comment]
i suggest build ethtool debian package and install from there.

**Comment by nazariig** [comment]
@shlomibitton IMHO, it is better to integrate `ethtool` to SONiC build system (e.g., `libyang`: https://github.com/Azure/sonic-buildimage/pull/2899)

**Pull request closed without merging**
