### PR TITLE
Warm reboot: Separate syncd from swss systemd service

### PR DESCRIPTION
**Pull request by jipanyang**
Signed-off-by: Jipan Yang <jipan.yang@alibaba-inc.com>

**- What I did**
Separate syncd from swss service
This to prepare docker level warm restart for swss.

**- How I did it**
Separate syncd from swss service and have swss service depending on it.

**- How to verify it**
reboot the system,  system start without problem and traffic resume on vlan and ethernet router interface.

systemctl stop syncd:  all services which have dependency on swss service and swss service itself stopped.

systemctl restart syncd:   all services which have dependency on swss service and swss service itself start again.

### CODE REVIEW

**Comment by jipanyang** [comment]
It has been suggested to keep swss.service backward compatible for cold start,  which means to restart syncd at the same time if no warm start enabled.

Tried a few approaches, but hadn't find easy way to do it cleanly under the constraint of systemd. Warm restart setting is dynamic, both the system reboot and docker restart scenarios have to be considered.

If we keep the current implementation, the only extra change needed in SONiC is to update the "config reload" command from using swss service to syncd service.   To avoid over engineering and making the problem unnecessarily complex , probably that is the way to go.   

But new suggestion is appreciated if any one knows how to dynamically check the database setting then start/stop syncd and related work accordingly in swss service while having syncd in a standalone service.

**Comment by lguohan** [comment]
develop a .sh script which contains all the current systemctl logic. 

inside the shell script, do the db check and finish corresponding actions.

**Comment by volodymyrsamotiy** [comment]
Previously SWSS and SYNCD already were as different services and they were merged to one service by the PR https://github.com/Azure/sonic-buildimage/pull/334.
The reason why it was done is that it causes a lot of problems in terms of dependencies and synchronization.
Please make sure that separating them again doesn't cause any dependencies and synchronization issues to come back.

**Comment by jipanyang** [comment]
Microsoft is to take care of this issue, close it.

**Pull request closed without merging**
