### PR TITLE
[Mellanox] Enhance Platform API to support SN2201 - RJ45 ports and new components mgmt.

### PR DESCRIPTION
**Pull request by keboliu**
Signed-off-by: Kebo Liu <kebol@nvidia.com>

#### Why I did it
1.  SN2201 has a new type of interface - RJ45 ports which need to be supported in platform API.
     The solution is to inherit a class from sfp_base to manage RJ45 ports,  this class will only return the port type with "RJ45",
     other fields will be left with 'N/A', so XCVRD still can have a "TRANCEIVER_INFO|Ethernetx" populated to DB with type="RJ45" against an RJ45 port, and this new class will reject the lpmode, reset, etc. APIs call.  
2. Add support for a new type of SSD FW upgrade.
3. Add support for SN2201 BIOS version fetch

#### How I did it
1. Add util function to get the "RJ45" port list from hwsku.json
2. Add a new class RJ45Port which was inherited from sfp class to manage RJ45 ports, and enhance the sfp_event
3. update SSD FW upgrade scripts: mlnx-ssd-fw-update.sh 
4. New implementation to support SN2201 BIOS ComponentBIOSSN2201
5. Add unit test for new code change

#### How to verify it
Run platform test on SN2201 platform

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111

### CODE REVIEW

**Comment by keboliu** [comment]
> This pull request **introduces 1 alert** when merging [a7a0523](https://github.com/Azure/sonic-buildimage/commit/a7a0523387c9d500c2d40450c405a8bfc3301f0f) into [0f488a8](https://github.com/Azure/sonic-buildimage/commit/0f488a8cb61521e92879e1175948b1f961633265) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-buildimage/rev/pr-df55033b69e1d80572a0c839dddd1fad6a23c3a2)
> 
> **new alerts:**
> 
> * 1 for Wrong number of arguments in a class instantiation

This is a false alarm, LTGM is referring to a `sfp_event` definition in another vendors' implementation. This is a bug of LGTM.

**Comment by keboliu** [comment]
> This is a false alarm, LTGM is referring to a `sfp_event` definition in another vendors' implementation. This is a bug of LGTM.

**Comment by keboliu** [comment]
> This pull request **introduces 1 alert** when merging [fcfa115](https://github.com/Azure/sonic-buildimage/commit/fcfa115cd1b8ddfe78ffa0805cc1fd6e3b8b8c3d) into [a149457](https://github.com/Azure/sonic-buildimage/commit/a1494577d9cc55dac99f55dc7031bcac37d7d9e5) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-buildimage/rev/pr-7f7ef2961322ccc0572c9280ec3fb93f82c4aef9)
> 
> **new alerts:**
> 
> * 1 for Wrong number of arguments in a class instantiation

This is a false alarm, LTGM is referring to a `sfp_event` definition in another vendors' implementation. This is a bug of LGTM.

**Comment by stephenxs** [comment]
Timer expired on `kvmtest-t1-lag`

**Comment by keboliu** [comment]
> This pull request **introduces 2 alerts** when merging [4156651](https://github.com/Azure/sonic-buildimage/commit/4156651a9bddcd663c6dd8aa206cbd6f2c2c8cf9) into [8d299ca](https://github.com/Azure/sonic-buildimage/commit/8d299cab2bf7e17cd048016ff5894a13ea229a20) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-buildimage/rev/pr-4798c97d5fbd7ab03abac6896ef10f1a619fa167)
> 
> **new alerts:**
> 
> * 1 for Unused import
> * 1 for Wrong number of arguments in a class instantiation

Both of them are false alarms:

1. for the first one, the import of `SFP` and `deinitialize_sdk_handle` are both used in the following function, somehow LGTM is not able to correctly parse it.

2. for the second one, LTGM is referring to a sfp_event definition in another vendor's implementation. This is a bug of LGTM.

**Pull request merged**
