### PR TITLE
[ci]: Enable pr checkers for 201911 branch

### PR DESCRIPTION
**Pull request by xumia**
#### Why I did it
Enable PR checkers for the branch 201911

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [x] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Comment by rlhui** [comment]
@xumia - is this still need to be merged to 201911 branch? what's pending?

**Comment by xumia** [comment]
@rlhui , some of the tests were failed, I will investigate it and enable the checks.

**Comment by liushilongbuaa** [comment]
Test stage is skipped.

**Comment by xumia** [comment]
Close the PR, for the build checks has already enabled in 201911 branch.

**Pull request closed without merging**
