### PR TITLE
[cfggen] Allow sku with no alias mapping and minigraph with no png

### PR DESCRIPTION
**Pull request by taoyl-ms**

### CODE REVIEW

**Comment by lguohan** [comment]
>                     neighbors[endport] = {'name': startdevice, 'port': startport}

this name is not mapped to alias

---
Refers to: src/sonic-config-engine/minigraph.py:68 in e4319eb. [](commit_id = e4319eb14f80a6a79d452f907327288e07a64ced, deletion_comment = False)

**Comment by lguohan** [comment]
I do not know if it worth to do port alias mapping in the minigraph, another way to do is to do it in the template, it is like only doing this port alias mapping when needed. @jleveque , any thoughts on this?

**Comment by taoyl-ms** [comment]
I think it makes more sense to do port mapping in minigraph since it is a pure minigraph concept and sonic  components shouldn't really care about it.
After minigraph.py finish the mapping, everything on the machine (except snmp) will only need to deal with sonic interfaces name, which is a neater contract.

**Comment by jleveque** [comment]
I know we discussed making the alias mapping an extra layer, outside the minigraph, but I'm still a bit too junior on the project to know all of the potential needs for aliases throughout SONiC. I think it makes sense to be a function of sonic-config-engine nevertheless, whether it's done as part of the minigraph parsing or as another layer afterward.

**Comment by lguohan** [comment]
so, let's do more consistently and fix the neighbor port name as well?

**Comment by lguohan** [comment]
is this really about no png or only for the console, mgmt information in the device section? should we modify the title accordingly?

**Comment by taoyl-ms** [comment]
It's really about no png. In the previous version if there is no png session sonic-cfggen will crash upon reading minigraph. In the new version it won't crash, but just ignore the corresponding data. (So if your template does not depend on png data it can still work with a minigraph without png)

**Comment by taoyl-ms** [comment]
I'll take a look on the neighbor port part.

**Comment by taoyl-ms** [comment]
@lguohan Please review commit 2.

**Pull request merged**
