### PR TITLE
Update the Nokia sonic-pmon submodule

### PR DESCRIPTION
**Pull request by mlok-nokia**
#### Why I did it
Updates the Nokia sonic-pmon submodule to the latest

#### How I did it
Updates the Nokia sonic-pmon submodule to the latest with the following commits:
```
    6eda3f5 Optimize the sonic_platform platform.Platform() init
    61f6da2 use ndk version wildcard
    545716d Fixed the sfp key to be "vendor_rev"
    5b17eb6 Fixed the show platform temperature command with not-present SFP issue.
``` 
#### How to verify it
Update up the image and execute CLI command "show interface transceiver eeprom".   the output should be shown correctly 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by mlok-nokia** [comment]
@judyjoseph @minionatwork Hi Judy and Suresh, This PR is to update the Nokia sonic-pmon submodule to the latest version.  Please help to review it. Thanks.

**Comment by judyjoseph** [comment]
Are these changes same as in PR https://github.com/Azure/sonic-buildimage/pull/9198

**Comment by mlok-nokia** [comment]
> Are these changes same as in PR #9198

Yes. Sorry for the confusion.   I will close this PR

**Comment by mlok-nokia** [comment]
Duplicated with https://github.com/Azure/sonic-buildimage/pull/9198. Close it

**Pull request closed without merging**
