### PR TITLE
Platform 2.0 Infra and Reboot Reason support for Dell Platforms

### PR DESCRIPTION
**Pull request by sridhar-ravindran**
**- What I did**
Ported Platform 2.0 Infra and Dell S6100,Z9100,S6000 Changes from master to 201904 branch
**- How I did it**
git cherry-pick and resolve conflicts
It has 3 porting
a) Platform 2.0 base infra + Z9100,S6100 Reboot Reason
b) S6000 Directory clean up
c) S6000 Reboot Reason support
**- How to verify it**
Currently unable to verify because linux-kernel build is failing due to http timeout
**- Description for the changelog**

Platform 2.0 Infra and Reboot Reason support for Dell Platforms

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by sridhar-ravindran** [comment]
Unable to compile build because of following error:-


4.9.168-1+deb9u3_all.deb /sonic/target/debs/stretch/
--2019-09-03 10:14:21--  http://security.debian.org/debian-security/pool/updates/main/l/linux/linux_4.9.168-1+deb9u3.dsc
Resolving security.debian.org (security.debian.org)... 128.61.240.73, 128.31.0.63, 128.101.240.215, ...
Connecting to security.debian.org (security.debian.org)|128.61.240.73|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://security-cdn.debian.org/debian-security/pool/updates/main/l/linux/linux_4.9.168-1+deb9u3.dsc [following]
--2019-09-03 10:14:21--  http://security-cdn.debian.org/debian-security/pool/updates/main/l/linux/linux_4.9.168-1+deb9u3.dsc
Resolving security-cdn.debian.org (security-cdn.debian.org)... 151.101.40.204, 2a04:4e42:a::204
Connecting to security-cdn.debian.org (security-cdn.debian.org)|151.101.40.204|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-09-03 10:14:21 ERROR 404: Not Found.

**Comment by jleveque** [comment]
Retest this please

**Comment by sridhar-ravindran** [comment]
Hi,
We have raised https://github.com/Azure/sonic-buildimage/pull/3767 to support this feature in master.
Once approved, will raise a new PR for this branch. Request you to review the same.

**Pull request closed without merging**
