### PR TITLE
Enable zebra IPv6 route semantics for route updates

### PR DESCRIPTION
**Pull request by preetham-singh**
Starting zebra with --v6_rr_semantics to enable ipv6 route semantics:
This enables IPv6 routes are updated in kernel with NLM_F_REPLACE flag
whenever there is route update instead of treating route update as
delete and add.

**- What I did**
Enable IPv6 Route semantics in zebra by starting zebra with command line option --v6-rr-semantics
This enables IPv6 routes are updated in kernel with NLM_F_REPLACE flag
whenever there is route update from zebra instead of treating route update as
delete and add.

**- How I did it**

Adding --v6-rr-semantics option to frr docker supervisor.conf

**- How to verify it**
Create ECMP IPv6 static routes with multiple nhops.
**- Description for the changelog**

**- Steps to recreate**

In FRR:

ipv6 route 2222::2/128 100::2
ipv6 route 2222::2/128 100::3
ipv6 route 2222::2/128 100::4
ipv6 route 2222::2/128 100::5
ipv6 route 2222::2/128 100::6
ipv6 route 2222::2/128 100::7
ipv6 route 2222::2/128 100::8
ipv6 route 2222::2/128 100::9
ipv6 route 2222::2/128 100::10
ipv6 route 2222::2/128 100::11
ipv6 route 2222::2/128 100::12
ipv6 route 2222::2/128 100::13
ipv6 route 2222::2/128 100::14
ipv6 route 2222::2/128 100::15
ipv6 route 2222::2/128 100::16
ipv6 route 2222::2/128 100::17
ipv6 route 2222::2/128 100::18
ipv6 route 2222::2/128 100::19
ipv6 route 2222::2/128 100::20
!
line vty
!
end
VS1#
root@VS1:~# ip -6 route show 2222::2/128
2222::2 via 100::9 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::10 dev Vlan100 proto 196 metric 20 pref medium

root@VS1:# ps -aef | grep -i zebra
300 4208 2937 0 Sep17 pts/0 00:02:04 /usr/lib/frr/zebra -A 127.0.0.1 -s 90000000 -M fpm -M snmp
root 28292 28226 0 09:48 pts/0 00:00:00 grep -i zebra
root@VS1:#

**After fix:**

root@VS1:# ps -aef | grep -i zebra
300 3456 3379 0 09:34 pts/0 00:00:00 /usr/lib/frr/zebra -A 127.0.0.1 -s 90000000 -M fpm -M snmp **--v6-rr-semantics**
root 3964 31001 0 09:36 pts/0 00:00:00 grep -i zebra
root@VS1:#

sonic(config)# ipv6 route 2222::2/128 100::2
ipv6 route 2222::2/128 100::4
sonic(config)# ipv6 route 2222::2/128 100::3
sonic(config)# ipv6 route 2222::2/128 100::4
sonic(config)# ipv6 route 2222::2/128 100::5
sonic(config)# ipv6 route 2222::2/128 100::6
sonic(config)# ipv6 route 2222::2/128 100::7
sonic(config)# ipv6 route 2222::2/128 100::8
sonic(config)# ipv6 route 2222::2/128 100::9
sonic(config)# ipv6 route 2222::2/128 100::10
sonic(config)# ipv6 route 2222::2/128 100::11
sonic(config)# ipv6 route 2222::2/128 100::12
sonic(config)# ipv6 route 2222::2/128 100::13
sonic(config)# ipv6 route 2222::2/128 100::14
sonic(config)# ipv6 route 2222::2/128 100::15
sonic(config)# ipv6 route 2222::2/128 100::16
sonic(config)# ipv6 route 2222::2/128 100::17
sonic(config)# ipv6 route 2222::2/128 100::18
sonic(config)# ipv6 route 2222::2/128 100::19
sonic(config)# ipv6 route 2222::2/128 100::20
sonic(config)# end
sonic#
root@VS1:~# ip -6 route show 2222::2/128
2222::2 via 100::2 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::3 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::4 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::5 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::6 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::7 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::8 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::9 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::10 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::11 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::12 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::13 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::14 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::15 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::16 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::17 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::18 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::19 dev Vlan100 proto 196 metric 20 pref medium
2222::2 via 100::20 dev Vlan100 proto 196 metric 20 pref medium

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
1. How this could help SONiC?
2. Which kernel version is required for the feature?

**Comment by preetham-singh** [comment]
> 1. How this could help SONiC?
This is necessary for IPv6 ECMP route programming to route table.
For all nexthops to be programmed in hardware route table, corresponding neighbors should be resolved in kernel. These neighbors would be resolved only when all nexthops are programmed in kernel.
This also ensures IPv6 route consistency between kernel and APP_DB ROUTE_TABLE.
> 2. Which kernel version is required for the feature?
This is supported by all kernel version > 4.4.x. It is verified on 4.9.168 kernel version as well.

**Comment by pavel-shirshov** [comment]
retest vs please

**Comment by pavel-shirshov** [comment]
retest vsimage please

**Comment by pavel-shirshov** [comment]
@preetham-singh 
1. But currently SONiC already has this functionality? FRR already works without this flag. Right?

**Comment by pavel-shirshov** [comment]
Also I've found this email from Donald
https://lists.frrouting.org/pipermail/frog/2018-May/000185.html
```
We recently introduced, into master, a new cli switch for zebra on
linux `--v6-rr-semantics`.  This was allow zebra to take advantage of
the linux kernel getting v6 route replace semantics that is coming
soon in the 4.18 linux kernel.  So if you are on the bleeding edge of
linux kernels and FRR you can start to take advantage of this new
feature.
```
So we need 4.18 linux kernel to have this support. Our current master kernel is 4.9.

**Comment by preetham-singh** [comment]
> Also I've found this email from Donald
> https://lists.frrouting.org/pipermail/frog/2018-May/000185.html
> 
> ```
> We recently introduced, into master, a new cli switch for zebra on
> linux `--v6-rr-semantics`.  This was allow zebra to take advantage of
> the linux kernel getting v6 route replace semantics that is coming
> soon in the 4.18 linux kernel.  So if you are on the bleeding edge of
> linux kernels and FRR you can start to take advantage of this new
> feature.
> ```
> 
> So we need 4.18 linux kernel to have this support. Our current master kernel is 4.9.

Most of the changes required for updating IPv6 routes' nhops in kernel is available in 4.9. Only notifications of route update back to subscribed applications would send route add with individual nhops instead of route add with all nhops with NLM_F_APPEND. This was part of commit [3b1137fe74829e021f483756a648cbb87c8a1b4a ](https://dev.pyra-handheld.com/notaz/pyra-kernel/commit/3b1137fe74829e021f483756a648cbb87c8a1b4a?view=inline)which went prior to 4.18.

**Comment by preetham-singh** [comment]
> retest vsimage please

Logs says "connection lost" while building image
"Caused by: hudson.remoting.RequestAbortedException: java.io.IOException: Sorry, this connection is closed.
		at hudson.remoting.Request.abort(Request.java:340)
		at hudson.remoting.Channel.terminate(Channel.java:1040)
		at hudson.remoting.Channel.close(Channel.java:1446)
		at hudson.remoting.Channel.close(Channel.java:1405)
		at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:844)
		at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:105)
		at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:753)
		at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
		at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)"

**Comment by pavel-shirshov** [comment]
retest vsimage please

**Comment by pavel-shirshov** [comment]
@preetham-singh The commit you referenced is part of 4.11, so I don't see that change in 4.9
https://github.com/torvalds/linux/commit/3b1137fe74829e021f483756a648cbb87c8a1b4a

**Comment by lguohan** [comment]
is it time now to enable this feature?

**Comment by pavel-shirshov** [comment]
@lguohan Do we need this feature? Should we make support for it first in routesyncd?

**Comment by preetham-singh** [comment]
Closing this PR since its not required.

**Pull request closed without merging**
