### PR TITLE
[BFN] Reset BMC port on syncd start

### PR DESCRIPTION
**Pull request by KostiantynYarovyiBf**
#### Why I did it
improvement of starting barefoot SDK
#### How I did it
restart of the interface for cleaning txquee through which communication takes place between Sonic and openBMC 
#### How to verify it
run sonic autorestart  tests
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [x] 201911
- [x] 202006
- [x] 202012
- [x] 202106
- [x] 202111

### CODE REVIEW

**Review by akokhan — APPROVED** [review]

**Comment by KostiantynYarovyiBf** [comment]
@lguohan, please review

**Comment by KostiantynYarovyiBf** [comment]
@lguohan, please review

**Comment by KostiantynYarovyiBf** [comment]
@lguohan,  please review and merge

**Comment by KostiantynYarovyiBf** [comment]
@sujinmkang, @jleveque,  please review and merge

**Review by msosyak — APPROVED** [review]

**Review by sujinmkang — APPROVED** [review]

**Comment by bratashX** [comment]
@sujinmkang @lguohan
 
Could you please cherry-pick this PR into the next branch:
-  201911
-  202006
-  202012
-  202106
-  202111

**Pull request merged**
