### PR TITLE
[Accton AS7816-64X] Add new platform and device for AS7816-64X.

### PR DESCRIPTION
**Pull request by roylee123**
Add new platform AS7816-64X.
But only peripherals part. The port config and sai is not ready.

Signed-off-by: roylee123 <roy_lee@accton.com>

**- What I did**
Add platform and device files for new machine, AS7816-64X.

**- How I did it**
Add kernel drivers under submodule and a init script to install drivers and make devnode.

**- How to verify it**
>decode-syseeprom
>sensors
**- Description for the changelog**
Add kernel drivers and dpkg controls for it. Add installer.conf, eeprom.py, and  sfputil.py under device folder.

### CODE REVIEW

**Comment by lguohan** [comment]
build failure, please check, also please remove .swp file

**Comment by lguohan** [comment]
can you resolve conflict?

**Comment by jleveque** [comment]
And also remove the .sfputil.py.swp file.

**Comment by roylee123** [comment]
Can you help to merge this PR to branch 201712? 
We are running tests based on branch 201712.

**Pull request merged**
