### PR TITLE
Refactored daemon base API: added Logger.

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>

Separating daemon and logging API to add more flexibility.

**- What I did**
* Extended base class with some useful API
* Added a dedicated Logger class
* Refactored code base

**- How I did it**
* N/A

**- How to verify it**
1. service pmon restart

**- Description for the changelog**
* N/A

### CODE REVIEW

**Comment by nazariig** [comment]
@jleveque It is already done: https://github.com/Azure/sonic-platform-daemons/pull/23

**Comment by jleveque** [comment]
Looks good. Once https://github.com/Azure/sonic-platform-daemons/pull/23 is merged (please ask Liat to review again), please update the submodule pointer in this PR.

**Comment by nazariig** [comment]
@andriymoroz-mlnx please help to review and merge.

**Comment by nazariig** [comment]
@jleveque the sonic-platform-daemons submodule pointer is updated.

**Comment by nazariig** [comment]
retest this please

**Comment by nazariig** [comment]
@lguohan please review

**Comment by andriymoroz-mlnx** [comment]
required by https://github.com/Azure/sonic-buildimage/pull/2710 which is already merged

**Pull request merged**
