### PR TITLE
[swsscommon] Add c++ version sonic-db-cli from sonic-swss-common

### PR DESCRIPTION
**Pull request by liuh-80**
#### Why I did it
    Fix sonic-db-cli high CPU usage on SONiC startup issue: https://github.com/Azure/sonic-buildimage/issues/10218
    ETA of this issue will be 2022/05/31

#### How I did it
    Re-write sonic-cli with c++ in sonic-swss-common: https://github.com/Azure/sonic-swss-common/pull/607
    Modify swss-common rules and slave.mk to install c++ version sonic-db-cli.
    

#### How to verify it
    Pass all E2E test scenario.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

#### Description for the changelog
    Build and install c++ version sonic-db-cli from swss-common.

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by yxieca** [comment]
@liuh-80 sonic-swss-comm has branch for 202205. As result, this PR cannot cherry picked directly, Can you raise separate PR for 202205 branch? I can help you do the sonic-swss-common cherry-pick first, but you need to mark these PRs.

**Comment by qiluo-msft** [comment]
To clarify, due to this PR includes submodule move, it could not be cherry-picked.

**Comment by yxieca** [comment]
@liuh-80 swss-common has 202205 branch. Please mark PRs needs to be cherry-picked in swss-common repo instead.

**Pull request merged**
