### PR TITLE
[201911][monit] Periodically monitor VNET route consistency

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Signed-off-by: Volodymyr Samotiy <volodymyrs@nvidia.com>

**- Why I did it**
To run VNET route consistency check periodically.

For any failure, the monit will raise alert based on return code.
The tool will log required details.

**- How I did it**
Added configuration entry to "SONiC monit"

**- How to verify it**
Configure VNET routes then remove some in ASIC_DB or APP_DB and verify logs for error messages.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [] 201911
- [ ] 202006
- [ ] 202012

**- Description for the changelog**

[monit] Periodically monitor VNET route consistency

### CODE REVIEW

**Comment by volodymyrsamotiy** [comment]
https://github.com/Azure/sonic-utilities/pull/1443

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest mellanox please

**Comment by prsunny** [comment]
retest this please

**Comment by abdosi** [comment]
@prsunny what will be behavior on T1 ?

**Comment by prsunny** [comment]
> @prsunny what will be behavior on T1 ?

In T1, there are no Vnet routes, so the expectation is that the script shall return without any alerts.

**Review by prsunny — APPROVED** [review]

**Pull request merged**
