### PR TITLE
[Mellanox] Upgrade mft to 4.14.1-8

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**- Why I did it**

Upgrade mft tool to 4.14.1-8 

**- How I did it**

Change mft.mk file

**- How to verify it**

Manual test

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
Retest this please.

**Comment by keboliu** [comment]
Retest this please

**Comment by liat-grozovik** [comment]
retest mellanox please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by Junchao-Mellanox** [comment]
Retest mellanox please

**Pull request merged**
