### PR TITLE
[Mellanox] Update SAI version 1.18.1.0

### PR DESCRIPTION
**Pull request by keboliu**
**- Why I did it**

Changes in the new release:

1. Policy based hashing optimization
2. New attribute support for Max port headroom
3. Tunnel ECN map fixes
4. Tunnel EVPN skeleton extensions (peer attrib, maps)
5. Bridge port admin not affecting port admin (optimize port down time)
6. CRM new API for neighbors and tunnel termination entries
7. Improve FDB event for flush by bridge port (before, null bridge was reported to SONiC, now the bridge will be extracted from bridge port)
8. DHCP L2 v4+v6 traps (for ZTP use case)
9. Generic counter implementation

**- How I did it**
Update the version number in SAI make file, update the mlnx-sai submodule pointer.

**- How to verify it**
Run full regression tests (T0 and T1-Lag) on Mellanox platforms

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
@lguohan please help to restart also 'Azure.sonic-buildimage (Test kvmtest)' as it was not initiated or failed already when Azure build restarted.

**Comment by keboliu** [comment]
retest vsimage please

**Comment by keboliu** [comment]
retest vsimage please

**Pull request merged**
