### PR TITLE
Upgrade linux-image version

### PR DESCRIPTION
**Pull request by qiluo-msft**
Will merge soon

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by lguohan** [comment]
all these needs to be changed.

```
build_debian.sh:sudo dpkg --root=$FILESYSTEM_ROOT -i target/debs/linux-image-3.16.0-4-amd64_*.deb || \
build_debian.sh:sudo cp target/debs/igb.ko $FILESYSTEM_ROOT/lib/modules/3.16.0-4-amd64/kernel/drivers/net/ethernet/intel/igb/igb.ko
files/Aboot/boot0.j2:kernel=boot/vmlinuz-3.16.0-4-amd64
files/Aboot/boot0.j2:initrd=boot/initrd.img-3.16.0-4-amd64
files/build_templates/swss.service.j2:Requires=opennsl-modules-3.16.0-4-amd64.service
files/build_templates/swss.service.j2:After=opennsl-modules-3.16.0-4-amd64.service
installer/x86_64/install.sh:        linux   /$image_dir/boot/vmlinuz-3.16.0-4-amd64 root=$grub_cfg_root rw $GRUB_CMDLINE_LINUX  \
installer/x86_64/install.sh:        initrd  /$image_dir/boot/initrd.img-3.16.0-4-amd64
platform/broadcom/sdk.mk:BRCM_OPENNSL_KERNEL = opennsl-modules-3.16.0-4-amd64_3.2.3.7-1_amd64.deb
platform/broadcom/sdk.mk:$(BRCM_OPENNSL_KERNEL)_URL = "https://sonicstorage.blob.core.windows.net/packages/opennsl-modules-3.16.0-4-amd64_3.2.3.7-1_amd64.deb?sv=2015-04-05&sr=b&sig=BJEFXfq2mgvSTIYZF8qF1Jj2ePkJaxBmA0HqhhAFPmQ%3D&se=2031-08-11T03%3A27%3A43Z&sp=r"
platform/broadcom/sonic-platform-modules-delta/debian/control:Depends: linux-image-3.16.0-4-amd64
platform/broadcom/sonic-platform-modules-inventec/debian/control:Depends: linux-image-3.16.0-4-amd64
platform/broadcom/sonic-platform-modules-inventec/debian/control:Depends: linux-image-3.16.0-4-amd64
platform/cavium/cavm_platform_modules/DEBIAN/control:Depends: linux-image-3.16.0-4-amd64
platform/centec/sdk.mk:CENTEC_SDK_KERNEL = centec-gg-sdk3.5-modules-3.16.0-4-amd64.deb
platform/centec/sdk.mk:$(CENTEC_SDK_KERNEL)_URL = "https://github.com/CentecNetworks/goldengate-sai/raw/master/lib/centec-gg-sdk3.5-modules-3.16.0-4-amd64.deb"
platform/mellanox/mft.mk:KERNEL_MFT = kernel-mft-dkms_4.5.0-3.16.0-4-amd64_all.deb
platform/mellanox/mft/Makefile:KERNELVER = 3.16.0-4-amd64
platform/mellanox/mft/Makefile:DERIVED_TARGETS = kernel-mft-dkms_4.5.0-3.16.0-4-amd64_all.deb
rules/linux-kernel.mk:KVERSION_SHORT = 3.16.0-4
src/igb/Makefile:       export BUILD_KERNEL=3.16.0-4-amd64
```

**Comment by lguohan** [comment]
igb build failure

**Comment by qiluo-msft** [comment]
Retest this please

**Pull request merged**
