### PR TITLE
[Mellanox] Update MFT to 4.15.0-104

### PR DESCRIPTION
**Pull request by nazariig**
**- Why I did it**
* To update MFT to 4.15.0-104
* To enable chroot build for all Mellanox packages

**- How I did it**
* N/A

**- How to verify it**
1. make target/sonic-mellanox.bin

**- Which release branch to backport (provide reason below if seleted)**

- [ ] 201811
- [ ] 201911
- [x] 202006

**- Description for the changelog**

**Features:**
* Added GA support for Mellanox Spectrum-3 based switch systems
* Added support for QSFP-DD and CMIS cables for mlxlink

**Bugfix:**
* Fixed an issue that resulted in port split query failure on a switch with P/N MSN4600-CS2RO
* Fixed deb installation in chroot environment

**- A picture of a cute animal (not mandatory but encouraged)**
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Comment by nazariig** [comment]
retest vsimage please

**Comment by qiluo-msft** [comment]
Does it close the task "use standard way to install mft package" ?

**Comment by nazariig** [comment]
> 
> 
> Does it close the task "use standard way to install mft package" ?

@qiluo-msft yes, it does.

**Comment by nazariig** [comment]
Same changes for 201911: https://github.com/Azure/sonic-buildimage/pull/5077

**Comment by liat-grozovik** [comment]
Retest vsimage please

**Pull request merged**
