### PR TITLE
Allow ability to invoke platform specific hooks in swss

### PR DESCRIPTION
**Pull request by VenkatCisco**
#### Why I did it
Implement a platform agnostic approach to source a script as desired. 
If it exits it checks if there is a file to source and hence does the needful.

#### How I did it
This is a PR followup from the code-review discussion we had with Guhon/Judy and team. This also addresses the following two comments: 
- Convert to sourcing a file instead of executing the same., so the logic within is run in the same shell.
-  Use sonic_asic_platform instead of PLATFORM_DIR

#### How to verify it
Perform run time check for files sourced via the swss.sh hooks and execute the same.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Comment by VenkatCisco** [comment]
As per the chassis group discussion and previous PR reviews, it was concluded that this PR is essential for the multi-asic instance bring up. Additionally, cisco will look into how multi-instance services (syncd and teamd) will need to orchestrated when corresponding asic is present. To that follow up, git issue #7699 is raised to track and develop the required enhancement. 

So please help approve this PR.

**Comment by anshuv-mfst** [comment]
Chassis subgroup meeting 5/26: 
Need enhancements to this PR, please look into https://github.com/Azure/sonic-platform-common/pull/185/files and https://github.com/Azure/sonic-platform-daemons/pull/175/files and follow same method.

**Comment by anshuv-mfst** [comment]
To be tracked via #7477 , please close this PR.

**Comment by VenkatCisco** [comment]
This feature support will be tracked thru #7477. Hence closing this PR

**Pull request closed without merging**
