### PR TITLE
[Mellanox] [201911] Integrate hw-mgmt V.7.0010.1002

### PR DESCRIPTION
**Pull request by stephenxs**
#### Why I did it
Integrate hw-management V.7.0010.1002 into 201911 branch.

 - Bug fixes
   - Removing critical thermal zones to prevent unexpected software system shutdown:
    *Kernel 4.9 -0071-mlxsw-core-Remove-critical-trip-point-from-thermal-z.patch
    *Kernel 4.19 -076-mlxsw-core-Remove-critical-trip-point-from-thermal-z.patch
   - hw-mgmt: thermal: Add hardcoded critical trip point

   - Removing redundant link for cpld3 for fixed systems (SN2100, SN2010).

   - Fix an issue with a missed attribute for cpld3 (port CPLD) for SN2700, SN2410.

Signed-off-by: Stephen Sun <stephens@nvidia.com>

#### How I did it
Integrate hw-management V.7.0010.1002 into 201911 branch.

#### How to verify it
Run regression test for platform.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Comment by lguohan** [comment]
how is this different from the sonic-linux-kernel pr?

**Comment by stephenxs** [comment]
> how is this different from the sonic-linux-kernel pr?

Can you elaborate on your question?

**Comment by lguohan** [comment]
you have this 0076 patch in this pr which is the same as sonic-linux-kernel pr you just submitted. why need both?

**Comment by lguohan** [comment]
please also list which platforms are tested?

**Pull request merged**
