### PR TITLE
[Mellanox] Add support for set/get system led status

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**- Why I did it**

System health feature needs to set/get system led status

**- How I did it**

1. Add a led object in chassis class and initialize it when the API is called on host side
2. Read/write system led system fs to get/set the status

**- How to verify it**

Manual test on SN2700

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
Retest vsimage please

**Comment by sujinmkang** [comment]
@Junchao-Mellanox Can we just read "/var/run/hw-management/led/led_status" for the get_status()?

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox Can we just read "/var/run/hw-management/led/led_status" for the get_status()?

No, we cannot for now because driver doesn't put the LED status to that file as I tested.

**Comment by Junchao-Mellanox** [comment]
Retest vsimage please.

**Comment by keboliu** [comment]
retest vsimage please

**Pull request merged**
