### PR TITLE
[202012][e1031] add GbE and higig port to E1031 port_config.ini

### PR DESCRIPTION
**Pull request by yxieca**
Port change in #7208 to 202012 branch

Why I did it
These ports are being enumerated by the latest SAI. But they are not defined in port_config.ini.

SONiC end up trying to delete these 3 ports and hit SAI error and crash.

How I did it
Add the GbE and the 2 HiGig ports in the port_config.ini.

How to verify it
Put the port_config.ini on a device crashing with port deleting. load minigraph and the crash stopped.

Signed-off-by: Ying Xie ying.xie@microsoft.com

### CODE REVIEW

**Review by daall — APPROVED** [review]

**Review by daall — CHANGES_REQUESTED** [review]
I don't believe the autoneg column exists in 202012

**Review by daall — APPROVED** [review]

**Comment by 119064273** [comment]
@yxieca  it seems  not work. I check it and find swss could not start, syslog error info as below
image

root@localhost:/home/admin# show version

SONiC Software Version: SONiC.202012.85-e6bbb3c3
Distribution: Debian 10.9
Kernel: 4.19.0-12-2-amd64
Build commit: e6bbb3c3
Build date: Fri Apr 23 06:07:36 UTC 2021
Built by: johnar@jenkins-worker-1

Platform: x86_64-cel_e1031-r0
HwSKU: Celestica-E1031-T48S4
ASIC: broadcom
ASIC Count: 1
/usr/local/bin/decode-syseeprom : ERROR : Failed to read eeprom : [Errno 2] No such file or directory: '/sys/class/i2c-adapter/i2c-2/2-0050/eeprom'
Serial Number:
Uptime: 20:50:34 up  1:20,  1 user,  load average: 12.66, 12.43, 12.08

Docker images:
REPOSITORY                    TAG                  IMAGE ID            SIZE
docker-syncd-brcm             202012.85-e6bbb3c3   4e719e23cf43        692MB
docker-syncd-brcm             latest               4e719e23cf43        692MB
docker-teamd                  202012.85-e6bbb3c3   36f09b8f0e82        410MB
docker-teamd                  latest               36f09b8f0e82        410MB
docker-nat                    202012.85-e6bbb3c3   0b9b37349814        413MB
docker-nat                    latest               0b9b37349814        413MB
docker-router-advertiser      202012.85-e6bbb3c3   c491f37815a8        400MB
docker-router-advertiser      latest               c491f37815a8        400MB
docker-platform-monitor       202012.85-e6bbb3c3   027166d0a8fe        608MB
docker-platform-monitor       latest               027166d0a8fe        608MB
docker-lldp                   202012.85-e6bbb3c3   be8aaffab71c        440MB
docker-lldp                   latest               be8aaffab71c        440MB
docker-database               202012.85-e6bbb3c3   b73a8706518e        400MB
docker-database               latest               b73a8706518e        400MB
docker-orchagent              202012.85-e6bbb3c3   4a4e099e0003        429MB
docker-orchagent              latest               4a4e099e0003        429MB
docker-snmp                   202012.85-e6bbb3c3   b6e47029a243        441MB
docker-snmp                   latest               b6e47029a243        441MB
docker-sonic-telemetry        202012.85-e6bbb3c3   fa728f89956a        490MB
docker-sonic-telemetry        latest               fa728f89956a        490MB
docker-dhcp-relay             202012.85-e6bbb3c3   0fd3a1e08732        407MB
docker-dhcp-relay             latest               0fd3a1e08732        407MB
docker-sonic-mgmt-framework   202012.85-e6bbb3c3   c348b9b6708e        620MB
docker-sonic-mgmt-framework   latest               c348b9b6708e        620MB
docker-fpm-frr                202012.85-e6bbb3c3   40a14c9ab9e5        429MB
docker-fpm-frr                latest               40a14c9ab9e5        429MB
docker-sflow                  202012.85-e6bbb3c3   a3fde95bc29d        411MB
docker-sflow                  latest               a3fde95bc29d        411MB

**Comment by yxieca** [comment]
@119064273 can you file an issue and attach the show techsupport?

**Comment by 119064273** [comment]
> @119064273 can you file an issue and attach the show techsupport?

https://github.com/Azure/sonic-buildimage/issues/6459

**Comment by 119064273** [comment]
@yxieca  I double confirm it,   it‘s ok now,   after generate a new config_db.json , swss could run without crash,   old config_db.json do not have port 52-54 so the error is the same, now it's ok , thanks

**Pull request merged**
