### PR TITLE
[syncd-rpc] Install Libboost Atomic 1.71, Libqtcore And Libqtnetwork

### LINKED ISSUE #6622: syncd crash on master RPC image
**Description**

syncd crash on master RPC image, error log:

```
Jan 28 03:50:38.688445 r-anaconda-10 INFO syncd#/supervisord: syncd /usr/bin/syncd: symbol lookup error: /usr/bin/syncd: undefined symbol: _ZN6apache6thrift6server13TSimpleServerC1ERKN5boost10shared_ptrINS0_10TProcessorEEERKNS4_INS0_9transport16TServerTransportEEERKNS4_INS9_17TTransportFactoryEEERKNS4_INS0_8protocol16TProtocolFactoryEEE

```

The issue is found beween hash 25e4d77 and hash 46b3bd5. I went over all changes between two hash, here is a suspicious commit: https://github.com/Azure/sonic-buildimage/commit/8ce1e3ed92ed0e141bd74d99f76af61e34b96ffd

In this commit, it removes libboost-all-dev and upgrade it to libboost1.71-dev.

**Steps to reproduce the issue:**
Load master RPC image

**Describe the results you received:**

syncd crash and not all dockers up

**Describe the results you expected:**

syncd should be able to up correctly

**Additional information you deem important (e.g. issue happens only occasionally):**

Found at hash 46b3bd5

### PR DESCRIPTION
**Pull request by tahmed-dev**
When Building syncd-rpc, libthrift has dependency on libboost-atomic1.71.0, libqt5core5a, 
and libqt5network5 however debian packager fails to resolve the dependencies. It instead
installs libthrift from debian along with its dependencies which result in symbols not found.

signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

closes #6622 
resolves #6622

Please provide the following information:
-->

**- Why I did it**
resolve issue loading sync-rpc

**- How I did it**
ensured dependecies are installed before installing libthrift

**- How to verify it**
load docker sync-rpc on target and there should not be errors find symbol thrift server symbol

```
Preparing to unpack .../libthrift-0.11.0_0.11.0-4_amd64.deb ...
Unpacking libthrift-0.11.0 (0.11.0-4) ...
[91mdpkg: dependency problems prevent configuration of libthrift-0.11.0:
 libthrift-0.11.0 depends on libboost-atomic1.71.0; however:
  Package libboost-atomic1.71.0 is not installed.
 libthrift-0.11.0 depends on libqt5core5a (>= 5.11.0~rc1); however:
  Package libqt5core5a is not installed.
 libthrift-0.11.0 depends on libqt5network5 (>= 5.0.2); however:
  Package libqt5network5 is not installed.

dpkg: error processing package libthrift-0.11.0 (--install):
 dependency problems - leaving unconfigured
[0mProcessing triggers for libc-bin (2.28-10) ...
[91mErrors were encountered while processing:
 libthrift-0.11.0
[0mReading package lists...
Building dependency tree...
Reading state information...
Correcting dependencies... Done
The following additional packages will be installed:
  libboost-atomic1.67.0 libdouble-conversion1 libglib2.0-0 libicu63
  libpcre2-16-0 libqt5core5a libqt5dbus5 libqt5network5 libthrift-0.11.0
```
**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
can you install this libraray on all syncd-rpc docker based on buster?

**Comment by lguohan** [comment]
also can you link this pr with the issue to resolve?

**Comment by lguohan** [comment]
any update on this?

**Comment by tahmed-dev** [comment]
> any update on this?

verified the fix on target.

**Review by lguohan — APPROVED** [review]

**Pull request merged**
