### PR TITLE
Improve the PR build version

### PR DESCRIPTION
**Pull request by xumia**
#### Why I did it
Improve the version of the Pull Request build by changing the local branch name.

#### How I did it
Change the default branch name merge to [target_branch_name]-[pullrequestid].

#### How to verify it
For official build, the version is not changed.
For pull request build, the version as below:
```
<target branch name>-<pullrequest id>.<azure pipelines build id>-<merge commit id>
Example: master-7381.11668-43df5c87
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by lguohan** [comment]
i download the image and tested, does not look like the version is correct.

```
admin@vlab-01:~$ show version

SONiC Software Version: SONiC.HEAD.0-7bb0dd81
Distribution: Debian 10.9
Kernel: 4.19.0-12-2-amd64
Build commit: 7bb0dd81
Build date: Tue Apr 20 06:42:13 UTC 2021
Built by: AzDevOps@sonic-build-workers-000786

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
ASIC Count: 1
```

**Comment by xumia** [comment]
> i download the image and tested, does not look like the version is correct.
> 
> ```
> admin@vlab-01:~$ show version
> 
> SONiC Software Version: SONiC.HEAD.0-7bb0dd81
> Distribution: Debian 10.9
> Kernel: 4.19.0-12-2-amd64
> Build commit: 7bb0dd81
> Build date: Tue Apr 20 06:42:13 UTC 2021
> Built by: AzDevOps@sonic-build-workers-000786
> 
> Platform: x86_64-kvm_x86_64-r0
> HwSKU: Force10-S6000
> ASIC: vs
> ASIC Count: 1
> ```

@lguohan , it is depended on the PR https://github.com/Azure/sonic-buildimage/pull/7320, the PR has merged. I re-run it, and test again.

**Comment by xumia** [comment]
> i download the image and tested, does not look like the version is correct.
> 
> ```
> admin@vlab-01:~$ show version
> 
> SONiC Software Version: SONiC.HEAD.0-7bb0dd81
> Distribution: Debian 10.9
> Kernel: 4.19.0-12-2-amd64
> Build commit: 7bb0dd81
> Build date: Tue Apr 20 06:42:13 UTC 2021
> Built by: AzDevOps@sonic-build-workers-000786
> 
> Platform: x86_64-kvm_x86_64-r0
> HwSKU: Force10-S6000
> ASIC: vs
> ASIC Count: 1
> ```

@lguohan , it is depended on the PR https://github.com/Azure/sonic-buildimage/pull/7320, the PR has merged. I re-run it, and test again.

**Comment by xumia** [comment]
@lguohan , you have tested it after https://github.com/Azure/sonic-buildimage/pull/7320 merged?

**Comment by xumia** [comment]
https://dev.azure.com/mssonic/build/_build/results?buildId=11973&view=logs&j=d37bc48d-29a0-534f-a1dc-3d699deb17a6&t=77cf8939-28f3-5999-bfef-4ed2138e371e

"SONIC_IMAGE_VERSION"             : "master-7381.0-9c380889"

**Comment by lguohan** [comment]
the build id is not matching.

**Comment by xumia** [comment]
> the build id is not matching.

Yes, I did not export the build number env variable. The reason is that there were some opened PRs  changing the same file. So I only change the branch name issue on this PR.
I can export it when PR https://github.com/Azure/sonic-buildimage/pull/7399 merged

**Comment by xumia** [comment]
I create a separate PR https://github.com/Azure/sonic-buildimage/pull/7406, but it is ok to merge into this PR(only not sure any conflict).

**Review by lguohan — APPROVED** [review]

**Pull request merged**
