### PR TITLE
[sonic-platform-common] Update submodule

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
7670b49 [sonic_platform/sfp_base] Add common definition for get SFP error status (#194)
1336598 [CI] sonic-config-engine now depends on SONiC YANG packages (#198)
f57fee4 Add to check pcie configuration revision to get the right configuration. (#195)
4e3a0a0 Fix typo for midplane APIs. (#196)
fc2e9e2 [eeprom_tlv_info] Optimize EEPROM data process by using visitor pattern (#193)

#### Why I did it

Update submodule for sonic-platform-common to include PR "Optimize EEPROM data process by using visitor pattern (#193)"

#### How I did it

Update submodule for sonic-platform-commo

#### How to verify it

Run build

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
submodule update PR https://github.com/Azure/sonic-buildimage/pull/7868 should be merged first.

**Comment by stephenxs** [comment]
Junchao, can you advance it to Azure/sonic-platform-common#198?
Thanks

**Comment by stephenxs** [comment]
Azure/sonic-platform-common#194 as well 
Thanks

**Review by liat-grozovik — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
The job "Clean Workspace" failed, it seems not related to the change, could you please help check? @jleveque

**Comment by jleveque** [comment]
> The job "Clean Workspace" failed, it seems not related to the change, could you please help check? @jleveque

This is seen on other PRs, as well. Will try re-running.

**Pull request merged**
