### PR TITLE
mgmt_vrf_namespace: management vrf using namespace solution

### PR DESCRIPTION
**Pull request by kannankvs**
**- What I did**
Added support for management VRF using namespace solution.
Requirements that are covered are explained in the design document.

**- How I did it**
Added commands to enable/disable the management VRF. On enabling, it creates the management namespace, attached eth0 to management namespace, creates the required iptables rules and restarts the networking service.
Detailed design is explained in the design document.

**- How to verify it**
Use the following commands to enable/disable mgmt vrf and test the features.
config vrf add mgmt
config vrf del mgmt
config interface eth0 ip add ip/mask gatewayIP
Ex: config interface eth0 ip add 10.16.206.11/24 10.16.206.1

**- Description for the changelog**

### CODE REVIEW

**Comment by batmancn** [comment]
> **- What I did**
> Added support for management VRF using namespace solution.
> Requirements that are covered are explained in the design document.
> 
> **- How I did it**
> Added commands to enable/disable the management VRF. On enabling, it creates the management namespace, attached eth0 to management namespace, creates the required iptables rules and restarts the networking service.
> Detailed design is explained in the design document.
> 
> **- How to verify it**
> Use the following commands to enable/disable mgmt vrf and test the features.
> config vrf add mgmt
> config vrf del mgmt
> config interface eth0 ip add ip/mask gatewayIP
> Ex: config interface eth0 ip add 10.16.206.11/24 10.16.206.1
> 
> **- Description for the changelog**

For 'config vrf add mgmt', do you change code in sonic-utilities repo? If change, do you have PR?

**Comment by batmancn** [comment]
Added this patch, why I could not ssh onto SONiC, after restart network.

- This is sshd status
```
root@sonic:~# ip netns exec mgmt /etc/init.d/ssh status
� ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; enabled)
   Active: active (running) since Thu 2016-11-10 18:42:51 UTC; 6min ago
  Process: 5496 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 5910 ExecStartPre=/usr/local/bin/host-ssh-keygen.sh (code=exited, status=0/SUCCESS)
 Main PID: 5913 (sshd)
   CGroup: /system.slice/ssh.service

Nov 10 18:42:51 sonic systemd[1]: Started OpenBSD Secure Shell server.
Nov 10 18:42:51 sonic sshd[5913]: Server listening on 0.0.0.0 port 22.
```

- This is socket status
```
root@sonic:~#  ip netns exec mgmt netstat -ntpl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
root@sonic:~# ip netns exec mgmt netstat -atlunp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
root@sonic:~#
```

- This is sshd log
```
Nov 10 18:17:20.749788 sonic INFO sshd[354]: Server listening on 0.0.0.0 port 22.
Nov 10 18:17:21.962811 sonic INFO sshd[354]: Received SIGHUP; restarting.
Nov 10 18:17:21.973555 sonic INFO sshd[354]: Server listening on 0.0.0.0 port 22.
Nov 10 18:17:36.266890 sonic INFO sshd[354]: Received SIGHUP; restarting.
Nov 10 18:17:36.274502 sonic INFO sshd[354]: Server listening on 0.0.0.0 port 22.
Nov 10 18:17:37.518905 sonic INFO sshd[354]: Received SIGHUP; restarting.
Nov 10 18:17:37.527136 sonic INFO sshd[354]: Server listening on 0.0.0.0 port 22.
Nov 10 18:20:43.041321 sonic INFO sshd[354]: Received signal 15; terminating.
Nov 10 18:20:43.060297 sonic INFO sshd[5665]: Server listening on 0.0.0.0 port 22.
Nov 10 18:20:52.537150 sonic INFO sshd[5665]: Received signal 15; terminating.
Nov 10 18:20:52.563828 sonic INFO sshd[5684]: Server listening on 0.0.0.0 port 22.
Nov 10 18:41:38.805387 sonic INFO sshd[5684]: Received signal 15; terminating.
Nov 10 18:41:53.800973 sonic INFO sshd[5864]: Server listening on 0.0.0.0 port 22.
Nov 10 18:42:51.422850 sonic INFO sshd[5864]: Received signal 15; terminating.
Nov 10 18:42:51.441402 sonic INFO sshd[5913]: Server listening on 0.0.0.0 port 22.
```

**Comment by batmancn** [comment]
And after reboot, could not work.

- This is info
```
root@sonic:~# ip route
240.127.1.0/24 dev docker0  proto kernel  scope link  src 240.127.1.1
root@sonic:~# ip netns exec mgmt ip route
Cannot open network namespace "mgmt": No such file or directory
```

**Comment by batmancn** [comment]
> Since we faced some issues in raising pull requests on top of this pull request, we shall cancel this PR. New PR #2431 is raised. Once if it is decided to use namespace solution for management VRF, all the comments given in this PR will be addressed as part of PR#2431. This PR#2405 is cancelled. Similarly the related sonic-utilities PR PR '[Azure/sonic-utilities#422](https://github.com/Azure/sonic-utilities/pull/422)' is also cancelled.
> The new PR on sonic-utilities is at [Azure/sonic-utilities#431](https://github.com/Azure/sonic-utilities/pull/431) that contains the configuration commands like "config vrf add/del mgmt".
> PR#2431 together with PR#431 provides the complete support for namespace based management VRF solution.

I read #2431 , I found it's same code.

Do your patch only work on kernel 4.x or above? refer [this](https://github.com/kannankvs/mvrf_namespace/blob/master/Management%20VRF%20Design%20Document%20Namespace.md).

My kernel is 3.16, which I use 201807 branch.

**Comment by kannankvs** [comment]
Closing the namespace PR.

**Pull request closed without merging**
