### PR TITLE
DellEMC: S6000,S6100 SFP refactor

### PR DESCRIPTION
**Pull request by aravindmani-1**
#### Why I did it 
Since SFP refactor has common API's, redundant platform API has to be removed.
#### How I did it
Removed redundant SFP API in Dell S6000, S6100 platforms
#### How to verify it
UT: 
[dell_sfp_refactor.txt](https://github.com/Azure/sonic-buildimage/files/7378229/dell_sfp_refactor.txt)
**Note:**
Please merge this PR only when sonic-platform-common submodule is updated with sonic_xcvr package in sonic-buildimage repo.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog
Removed redundant platform SFP APIs.

### CODE REVIEW

**Comment by prgeor** [comment]
@aravindmani-1 could you resolve merge conflict?

**Comment by aravindmani-1** [comment]
> @aravindmani-1 could you resolve merge conflict?

Done.

**Comment by prgeor** [comment]
@aravindmani-1 build is failing even after repeated submission. please check.

**Comment by aravindmani-1** [comment]
> @aravindmani-1 build is failing even after repeated submission. please check.

The failures are not related to my changes. can you please check?.

**Comment by prgeor** [comment]
@aravindmani-1 can you rebase to latest master and do force push to trigger the checks again?

**Review by prgeor — APPROVED** [review]

**Comment by sachinv-msft** [comment]
@prgeor can we add the label to include this on 202012?

**Comment by prgeor** [comment]
@sachinv-msft SFP-refactor is NOT supported in 202012

**Comment by sachinv-msft** [comment]
@prgeor why is it not supported on 202012?

**Comment by prgeor** [comment]
> @prgeor why is it not supported on 202012?

its risky change

**Comment by sachinv-msft** [comment]
@prgeor i would like some clarification on next steps on how would we eventually support this moving forward?

**Comment by prgeor** [comment]
> @prgeor i would like some clarification on next steps on how would we eventually support this moving forward?

please ping me over teams, so that we can discuss.

**Comment by aravindmani-1** [comment]
@prgeor @qiluo-msft Could you please help to cherry pick this PR to 202111 branch?.

**Pull request merged**
