### PR TITLE
[swss][sairedis] advance sub-modules

### PR DESCRIPTION
**Pull request by akokhan**
[sairedis]:
* ARM32 bit fixes, for 64bit printf format specifier (#490)
* fix wrong API type , add cmdline parse option , remove unuseful api call (#499)
* Use pointer to member function to reduce the footprint of collectCounters() (#488)
* [syncd] Add support for Innovium platform (#496)
* [saisdkdump]: Fix dump generation crash (#493)

[swss]:
* Add scope attribute to VNET table. (#954)
* [portsyncd]: Fix portsyncd restart case (#1019)
* [vnet]: Enable "vnet_orch_1" VS test case (#1020)
* [vlan] Add pytest cases to validate the behavior about add LAG member to vlan. (#875)
* [policerorch]: Add the capability to update policer rate/size (#1017)
* [aclorch]: Add MIRRORv6 support for NPS platform (#1018)
* [orchagent]: Avoid crash by setting g_syncMode flag before create_switch (#1014)
* [orchagent] Add support for Innovium platform (#1005)
* Provide broadcast IP while configuring interface ip address (#1007)
* [VLAN] Add pytest cases to validate different use-case of tagging_mode. (#860)
* [vstest]: Add test_port_config.py which include breakout port test. (#866)
* [vstests]: change 'test_acl_egress_table.py' to UNIX format (#1010)
* [vlan] Add pytest cases to verify data in app db and state db. (#895)
* [vstest]: Add the CRM tests (#1013)
* [warm-reboot]: add bgp eoiu support to speed up route reconcile (#856)
* [fdborch] support mac update (#877)
* [vxlanorch] Fix Logic of Vxlan tunnel removal  (#995)
* Fix VLAN error introduced with new 4.9 kernel behavior (#1001)
* Config DB manual is being moved from Wiki to SWSS repo (#1002)
* Trap DHCPv6 packets for supporting ZTP over in-band interfaces using … (#997)

Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>

### CODE REVIEW

**Comment by akokhan** [comment]
@lguohan could you please merge this?

**Comment by lguohan** [comment]
can you put commits in the commit message? what are the commits advanced in this submodule updates?

**Comment by akokhan** [comment]
> can you put commits in the commit message? what are the commits advanced in this submodule updates?

done

**Comment by akokhan** [comment]
@lguohan please merge this.

This PR should fix runtime issue that I see on VLAN TC. I think it's caused by the bug that is fixed in:
"fix wrong API type , add cmdline parse option , remove unuseful api call " -
 https://github.com/Azure/sonic-sairedis/pull/499

**Pull request merged**
