### PR TITLE
[202012][submodule] Update sonic-swss and sonic-utilities submodules

### PR DESCRIPTION
**Pull request by daall**
sonic-swss:
* fixed unsupported resource issue (#1641) 
* [bufferorch] Handle NOT IMPLEMENTED status returned during set attr operation (#1639)
* [Mux] Neighbor handling based on FDB entry (#1631)
* Migrate serdes programming to port serdes object (#1611)
* [tests] Remove legacy saiattributelist.h dependency (#1608)
* Fix the compiling errors in gcc9 (#1621) [Stephen Sun]

sonic-utilities:
* [config] Prevent deleting VLAN with IP addresses. (#1429)
* [show] Issue in CLI output alignment with shorter alias names in intf naming mode "alias" #1397 (#1411)
* [consutil] Look for udevprefix.conf file under platform dir, not plugins (#1431) [Joe LeVeque]
* [storyteller] sort output by time and improve lag support (#1430) [Ying Xie]
* [show mux]: Sort output by intf name (#1418) [Lawrence Lee]
* Revert "Add FW dump with new SAI implementation (#1338)" (#1407)
* [pcieutil] Remove the warning message and change the config file location (#1362)

Signed-off-by: Danny Allen <daall@microsoft.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Comment by liat-grozovik** [comment]
retest vsimage please

**Review by liat-grozovik — COMMENTED** [review]
Can you please add change log so we know what are the items we get as part of it?

**Review by liat-grozovik — APPROVED** [review]

**Comment by daall** [comment]
retest vsimage please

**Comment by daall** [comment]
retest vsimage please

**Review by theasianpianist — APPROVED** [review]

**Pull request merged**
