### PR TITLE
[image]: build debug symbol packages for swss-common, libsairedis, li…

### PR DESCRIPTION
**Pull request by lguohan**
…bsaimetadata, syncd, syncd-rpc

### CODE REVIEW

**Comment by lguohan** [comment]
do not merge until validated

**Comment by stcheng** [comment]
No space left on device

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
please resolve the conflicts

**Comment by lguohan** [comment]
resolved conflict

**Comment by stcheng** [comment]
i think this PR will also have conflict with https://github.com/Azure/sonic-buildimage/pull/564. Let's close https://github.com/Azure/sonic-buildimage/pull/564?

**Pull request merged**
