### PR TITLE
bgp template changes for new multi Asic minigraph

### PR DESCRIPTION
**Pull request by arlakshm**
Signed-off-by: Arvindsrinivasan Lakshmi Narasimhan <arlakshm@microsoft.com>

**- Why I did it**
Align the bgp templates with new minigraph generated for multi NPU platforms

**- How I did it**
change the references to 'type' field to 'sub_role' 
change the references to 'InternalFrontend' and 'InternalBackend' to 'FrontEnd' and 'BackEnd' respectively

**- How to verify it**
Check if the configuration is generated properly on multi NPU platforms

**- Description for the changelog**

change the references to 'type' field to 'sub_role' 
change the references to 'InternalFrontend' and 'InternalBackend' to 'FrontEnd' and 'BackEnd' respectively
add a statement to reflect route-reflector for backend asics
Add a change to set "next-hop-self force" configuration for internal BGP session in multi asic platform.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
We should wait until we have 'sub-role' generation merged to the master?

**Comment by arlakshm** [comment]
retest vsimage please

**Comment by pavel-shirshov** [comment]
you need to rebase the new parser to this change first

**Comment by arlakshm** [comment]
retest vsimage please

**Pull request merged**
