### PR TITLE
[Arista] Fix 7060 flex HWSKU SFP ports and Ethernet8/1

### PR DESCRIPTION
**Pull request by zzhiyuan**
#### Why I did it
Longxiang (Longxiang.Lv@microsoft.com) brought up that Ethernet8/1 was encountering issues while testing the flex broadcom config compared to the regular config. Indeed an issue was found and this PR addresses it. Additionally the SFP ports had the wrong Sonic names.

#### How I did it
Edit the broadcom config file for the flex HWSKU to fix the Ethernet8/1 issue, and edit the relevant files for the HWSKU to fix the SFP issue.

#### How to verify it
Can boot up a 7060 and replace the config with the flex config and Ethernet8/1 will be up as expected.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by lolyu — APPROVED** [review]
LGTM, the bcm flex configuration works now!

**Comment by yxieca** [comment]
Requesting this change in 202012 because we are experimenting sonic fanout with 202012 branch.

**Comment by zzhiyuan** [comment]
> Requesting this change in 202012 because we are experimenting sonic fanout with 202012 branch.

Hi Ying, which products do you want the breakouts in? I can backport flex configs to 202012 but it would be easier to verify with a small pool of products.

Thanks

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by zzhiyuan** [comment]
> This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

This is due to the dynamic breakout HWSKUs not existing in 202012. Therefore there would be work to be done to add the HWSKUs in 202012. Please let me know which products the flex configs are desired on.

Thanks

**Comment by qiluo-msft** [comment]
@yxieca Please check @zzhiyuan question above.

**Comment by lguohan** [comment]
@yxieca do we really need this on 202012, I think we can use it in other branch as well.

**Comment by yxieca** [comment]
@lguohan We are working on sonic fanout switch with 202012 branch. The flex config is needed for that.

**Comment by yxieca** [comment]
@zzhiyuan if you could add support for 7060 and 7260, that would be sufficient for our purpose.

**Pull request merged**
