### PR TITLE
[202012][submodule] Update sonic-swss submodule

### PR DESCRIPTION
**Pull request by dprital**
Signed-off-by: dprital [drorp@nvidia.com](mailto:drorp@nvidia.com)

#### Why I did it

Update sonic-swss submodule pointer to include the following:

* Revert "[202012][cherry-pick]Update orchagent to support new field `pfcwd_sw_enable` ([#2245](https://github.com/Azure/sonic-swss/pull/2265))"  ([#2265](https://github.com/Azure/sonic-swss/pull/2265))
* [Vnet] Set BFD multihop to true for Vnet routes ([#2244](https://github.com/Azure/sonic-swss/pull/2244)]

#### How I did it

Update submodule pointer

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by prsunny** [comment]
Duplicate PR - https://github.com/Azure/sonic-buildimage/pull/10860

**Review by bingwang-ms — APPROVED** [review]

**Pull request merged**
