### PR TITLE
[platform/nephos] Optimize the code to reduce changes due to the kernel upgrade

### PR DESCRIPTION
**Pull request by simonJi2018**
…el upgrade

**- What I did**
1. bug fix : Fixed an issue which the nps ko file was not loaded due to the wrong service file name
2. Optimize the code to reduce changes due to the kernel upgrade
3. Remove nephos ko file loaded in swss.service.j2 because it has loaded at syncd.service.j2
**- How I did it**

**- How to verify it**
 make sonic-nephos.bin and test it at accton as7116 platform

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
can you resolve the conflict?

**Comment by simonJi2018** [comment]
I have resolved the conflict ,please have time to review it

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Pull request merged**
