### PR TITLE
[sonic-utilities] Update sonic-utilities submodule to pick set of new fixes 

### PR DESCRIPTION
**Pull request by gechiang**
**- Why I did it**
submodule sonic-utilities in sonic-buildimage has not been updated for a while and there were many fixes needed to be picked up to ease debug/development in master branch.
Here are the list of changes that this update will bring in:

1.   Added show ip/v6 route summary support for multi-asic platform (#1320)
2.   [pytest][qos][config] Added pytests for "config qos reload" commands (#1266)
3.   [CRM]Add support for snat, dnat and ipmc crm resources (#1258)
4.   Retain fgnhg state db table entry during warm reboot (#1315)
5.   Fix exception handling in python3 (#1324)
6.   [config] Add unit tests for 'config interface breakout' command (#1223)
7.   [dropcounters] Fix clear for non-root users (#1253)
8.   Kubernetes support commands update (#1133)
9. VXLAN config and show utilities (#870)
10. [Multi-asic] Enhanced Feature Table configuration for multi-asic platforms (#1152)
11. [config vlan]: Remove `-t` flag from docker exec command (#1317)
12. [fast-reboot-dump] Fix exception in struct.pack (#1309)
13. Mgmt vrf/SNMP agent validations and bug fixes (#1289)
14. [Dynamic buffer calc] Support dynamic buffer calculation (#973)
15. show tech with platform dump option (#1158)
16. [kdump]: Parse sonic_platform kernel command line parameter to read the platform identifier string (#1291)
17. [pcieutil] Remove 'pcie-' prefix from arguments (#1297)
18. Added 'detailed' option for 'show interface counters' command (#1299)
19. Fix show ip route summary on pizzabox platforms (#1302)

**- Description for the changelog**
[sonic-utilities] Update sonic-utilities submodule to pick set of new fixes

### CODE REVIEW

**Comment by jleveque** [comment]
Looks like PFCWD unit tests are failing with "Root privileges are required for this operation". Not sure why this wasn't seen before. Looks like @smaheshm modified these recently. Maybe he can help troubleshoot?

**Comment by smaheshm** [comment]
> Looks like PFCWD unit tests are failing with "Root privileges are required for this operation". Not sure why this wasn't seen before. Looks like @smaheshm modified these recently. Maybe he can help troubleshoot?

Let me take a look. Looks like there's a difference between how sonic-buildimage repo runs tests vs sonic-utilities repo.

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
need to fix the unit test failure.

**Review by lguohan — DISMISSED** [review]

**Comment by lguohan** [comment]
there are about 23 commits picked up in sonic-utilities repo, the description only listed 19 commits.

**Comment by lguohan** [comment]
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/8207/

07:11:55  Sunday 27 December 2020  15:11:54 +0000 (0:00:00.059)       0:00:21.107 ******* 
07:12:51  fatal: [vlab-01]: FAILED! => {"changed": true, "cmd": "config load_minigraph -y", "delta": "0:00:47.452274", "end": "2020-12-27 15:12:41.680371", "msg": "non-zero return code", "rc": 1, "start": "2020-12-27 15:11:54.228097", "stderr": "Warning: Stopping telemetry.service, but it can still be activated by:\n  telemetry.timer\nTraceback (most recent call last):\n  File \"/usr/local/bin/config\", line 8, in <module>\n    sys.exit(config())\n  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/dist-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/usr/local/lib/python3.7/dist-packages/config/main.py\", line 1673, in reload\n    sonic_version_file = device_info.get_sonic_version_file()\nAttributeError: module 'sonic_py_common.device_info' has no attribute 'get_sonic_version_file'", "stderr_lines": ["Warning: Stopping telemetry.service, but it can still be activated by:", "  telemetry.timer", "Traceback (most recent call last):", "  File \"/usr/local/bin/config\", line 8, in <module>", "    sys.exit(config())", "  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 764, in __call__", "    return self.main(*args, **kwargs)", "  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 717, in main", "    rv = self.invoke(ctx)", "  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 1137, in invoke", "    return _process_result(sub_ctx.command.invoke(sub_ctx))", "  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 1137, in invoke", "    return _process_result(sub_ctx.command.invoke(sub_ctx))", "  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 956, in invoke", "    return ctx.invoke(self.callback, **ctx.params)", "  File \"/usr/local/lib/python3.7/dist-packages/click/core.py\", line 555, in invoke", "    return callback(*args, **kwargs)", "  File \"/usr/local/lib/python3.7/dist-packages/click/decorators.py\", line 17, in new_func", "    return f(get_current_context(), *args, **kwargs)", "  File \"/usr/local/lib/python3.7/dist-packages/config/main.py\", line 1673, in reload", "    sonic_version_file = device_info.get_sonic_version_file()", "AttributeError: module 'sonic_py_common.device_info' has no attribute 'get_sonic_version_file'"], "stdout": "Executing stop of service telemetry...\nExecuting stop of service swss...\nExecuting stop of service lldp...\nExecuting stop of service pmon...\nExecuting stop of service bgp...\nRunning command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json   --write-to-db\nRunning command: pfcwd start_default\nRunning command: /usr/local/bin/sonic-cfggen -d -y /etc/sonic/sonic_version.yml -t /usr/share/sonic/templates/sonic-environment.j2,/etc/sonic/sonic-environment\nRunning command: config qos reload --no-dynamic-buffer", "stdout_lines": ["Executing stop of service telemetry...", "Executing stop of service swss...", "Executing stop of service lldp...", "Executing stop of service pmon...", "Executing stop of service bgp...", "Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json   --write-to-db", "Running command: pfcwd start_default", "Running command: /usr/local/bin/sonic-cfggen -d -y /etc/sonic/sonic_version.yml -t /usr/share/sonic/templates/sonic-environment.j2,/etc/sonic/sonic-environment", "Running command: config qos reload --no-dynamic-buffer"]}

**Review by lguohan — APPROVED** [review]

**Comment by smaheshm** [comment]
> > Looks like PFCWD unit tests are failing with "Root privileges are required for this operation". Not sure why this wasn't seen before. Looks like @smaheshm modified these recently. Maybe he can help troubleshoot?
> 
> Let me take a look. Looks like there's a difference between how sonic-buildimage repo runs tests vs sonic-utilities repo.

https://github.com/Azure/sonic-utilities/pull/1340

**Pull request merged**
