### PR TITLE
[202012][submodule] Update sonic-swss, sonic-utilities, and sonic-linux-kernel submodules

### PR DESCRIPTION
**Pull request by daall**
sonic-swss
* Add table descriptions for dynamic buffer calculation to the documents (#1664)
* Remove vxlanmgrd dependency on orchagent (#1647)

sonic-utilities
* [show] Fix 'show mac' output, when FDB entry with Vlan 1 is present (#1368)
* [warm-reboot]: Check empty key before issuing redis hget (#1496)
* [generate-dump] Remove Arista specific logic (#1482)
* [warm-reboot]: added automated recover for ISSU file (#1466)
* [warm-reboot] Check if warm restart flag is set when issuing a warm-reboot (#1460)
* [show][config] fix for show/config muxcable hwmode model value; fix show/config muxcable return codes; (#1494)

sonic-linux-kernel
* [net] Disable prio and cls cgroups to make working cgroup2 sock matching (#198)

Signed-off-by: Danny Allen <daall@microsoft.com>

#### Why I did it
Pull the latest submodule changes into 202012.

#### How I did it
Update the pointer.

#### How to verify it
See PR tests.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

#### Description for the changelog
Update sonic-swss, sonic-utilities, and sonic-linux-kernel submodules

#### A picture of a cute animal (not mandatory but encouraged)
image

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@daall there is a build test failure related to test_ro_user_allowed_command
not sure this PR is relevant but that means there is some change which make it unstable (is it random test parameters)?

**Comment by liat-grozovik** [comment]
The reason 202012 new PRs cannot be merged is due to the following 
[ro_user] test is failing on 202012 branch:  https://github.com/Azure/sonic-mgmt/issues/3116
seems that there is not an alignment between the test and the code on 202012 but the test is passing on master. the test was recently changed but since we have no sonic-mgmt for 202012 it was not verified against 202012 and casing so many PRs to fail.

@daall  and @lguohan please suggest next step. As we need many PRs to be taken in to 202012 we should
I suggest to ignore the test till it will be modified to be able to work on different branches. 
please help to conclude this

**Comment by daall** [comment]
> The reason 202012 new PRs cannot be merged is due to the following
> [ro_user] test is failing on 202012 branch: [Azure/sonic-mgmt#3116](https://github.com/Azure/sonic-mgmt/issues/3116)
> seems that there is not an alignment between the test and the code on 202012 but the test is passing on master. the test was recently changed but since we have no sonic-mgmt for 202012 it was not verified against 202012 and casing so many PRs to fail.
> 
> @daall and @lguohan please suggest next step. As we need many PRs to be taken in to 202012 we should
> I suggest to ignore the test till it will be modified to be able to work on different branches.
> please help to conclude this

It is passing in master so we must be missing a cherry-pick. I will look

**Review by prsunny — APPROVED** [review]

**Pull request merged**
