### PR TITLE
[utilities] advance utilities submodule head

### PR DESCRIPTION
**Pull request by yxieca**
**- How I did it**

advance utilities submodule head

- [storyteller] adding a grep wrapper with predefined scenarios (#1349)
- Adding global-timeout, individual command timeout, log files collection (#1249)
- Add FW dump with new SAI implementation (#1338)
- [unit test][pfcwd] Fix tests that require sudo access (#1340)

Signed-off-by: Ying Xie <ying.xie@microsoft.com>

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

**Comment by yxieca** [comment]
retest vsimage please

**Comment by yxieca** [comment]
retest vsimage please

**Comment by yxieca** [comment]
retest vsimage please

**Comment by yxieca** [comment]
retest vsimage please

**Pull request merged**
