### PR TITLE
[submodule] update sonic-utilities submodule

### PR DESCRIPTION
**Pull request by vivekreddynv**
Includes

```
3fa08549 [CLI][show bgp] On chassis don't show internal BGP sessions by default (Azure#1927)
6de91af5 [Auto-Techsupport] Issues related to Multiple Cores crashing handled (Azure#1948)
656ade1a SFP-Refactor: Vendor revision is not displayed properly (Azure#1950)
67466cb4 [port] Fix port speed set (Azure#1952)
5172972f Fix invalid output of syslog IPv6 servers (Azure#1933)
290ff5f4 Routed subinterface enhancements (Azure#1821)
1ea88e21 Enhance sfputil for CMIS QSFP (Azure#1949)
4e132c1c [debug dump] Refactoring Modules and Unit Tests (#1943)
b550c44e Add command reference for trap flow counters (#1876)
67a267b2 [Reclaim buffer] [Mellanox] Db migrator support reclaiming reserved buffer for unused ports (#1822)
30e4654c Add show command for BFD sessions (#1942)
e63f47e0 [warm-reboot] Fix failures of warm reboot on disconnect of ssh session (#1529)
c05845df Add trap flow counter support (#1868)
ef82f00a [load_minigraph] Delay pfcwd start until the buffer templates are rendered (#1937)
f5e5a567 [sonic-package-manager] support sonic-cli-gen and packages with YANG model (#1650)
64777a40 generic_config_updater: Filename changed & VLAN validator added (#1919)
1f8f6ab5 [config reload] Update command reference (#1941)
```

Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by vivekreddynv** [comment]
@qiluo-msft Please review and signoff

**Review by qiluo-msft — APPROVED** [review]

**Comment by vivekreddynv** [comment]
Closing this as there is another PR which has the latest sonic-utilities changes. https://github.com/Azure/sonic-buildimage/pull/9467

**Pull request closed without merging**
