### PR TITLE
[Mellanox][asan] add address sanitizer support for syncd

### PR DESCRIPTION
**Pull request by Yakiv-Huryk**
#### Why I did it
To support address sanitizer for Mellanox syncd
#### How I did it
* /var/log/asan is mapped for syncd container (the same as for swss)
* container stop() has a timeout (60s) for syncd (the same as for swss)
This is so libasan has enough time to generate a report.
* added ASAN's log path to Mellanox syncd supervisord.conf
* added "asan: yes" to sonic_version.yml
#### How to verify it
1) Added artificial memory leaks
2) Compiled with ENABLE_ASAN=y
3) Installed the image on DUT
4) Rebooted the DUT
5) Verified that /var/log/asan/syncd-asan.log contains the leaks
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Review by oleksandrivantsiv — APPROVED** [review]

**Review by yxieca — DISMISSED** [review]

**Comment by Yakiv-Huryk** [comment]
@yxieca sorry, I had to rebase since the diff to master was too big, and merge produced a lot of commits in this pr.

**Review by oleksandrivantsiv — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@yxieca kindly reminder to signoff the PR

**Review by yxieca — APPROVED** [review]

**Pull request merged**
