### PR TITLE
[barefoot][platform] Update BFN platforms

### PR DESCRIPTION
**Pull request by vsenchyshyn**
**- Why I did it**
1. Added support of BFN newport new platform name.
2. Updated debian version for montara and mavericks platforms.

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [X] 201911
- [X] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vsenchyshyn** [comment]
@lguohan Please review

**Review by akokhan — APPROVED** [review]

**Comment by vsenchyshyn** [comment]
retest mellanox please

**Review by jleveque — APPROVED** [review]

**Comment by vsenchyshyn** [comment]
@jleveque @lguohan Since the PR is approved could you please merge?

**Comment by abdosi** [comment]
@vsenchyshyn Cherry-pick has conflict for 201911. Please create PR direct for 201911

**Pull request merged**
