### PR TITLE
[Quanta]: Add a new supported device and platform, IX1B-32X

### PR DESCRIPTION
**Pull request by cpchangtw**
Switch Vendor: Quanta
Switch SKU:    IX1B-32X
ASIC Vendor:   Broadcom
Swich ASIC:    Tomahawk
Port Config:   32x100G

Signed-off-by: Chih-Pei.Chang@qct.io

**- What I did**
Add Quanta IX1B support
**- How I did it**
Follow https://github.com/Azure/SONiC/wiki/Porting-Guide
**- How to verify it**
Follow https://github.com/Azure/SONiC/wiki/Command-Reference 
to verify hardware information can get from CLI correctly
**- Description for the changelog**
Initial commit

### CODE REVIEW

**Comment by cpchangtw** [comment]
Build fail had been fixed, please check, thanks.

**Comment by lguohan** [comment]
please fix conflicting files.

**Comment by lguohan** [comment]
we are now requiring to change switch1 in the minigraph to sonic now.

**Comment by cpchangtw** [comment]
Hi @lguohan 
1. kernel version already updated, maybe wrong check?
2. conflict solved.
3. minigraph updated.

please review, thanks.

**Comment by cpchangtw** [comment]
Hi @lguohan 
1. kernel version already updated.
2. conflict file resolved.
3. minigraph updated.

please review, thanks.

**Comment by lguohan** [comment]
your debian/control file is still 3.16.0-4-amd64.

**Pull request merged**
