### PR TITLE
Per-switching silicon Common config for Broadcom Supported Platforms

### PR DESCRIPTION
**Pull request by geans-pin**
Additional commit along with [PR#693](https://github.com/Azure/sonic-sairedis/pull/693) and HLD [PR#699 ](https://github.com/Azure/SONiC/pull/699)

### CODE REVIEW

**Comment by lguohan** [comment]
can you check the url for 693, it does not seem relavant.

**Comment by geans-pin** [comment]
> can you check the url for 693, it does not seem relavant.

Sorry, I correct the typo and point to the right PR. Pls check again

**Comment by lguohan** [comment]
@gechiang , can you help to review?

**Comment by gechiang** [comment]
@geans-pin For the 6 common config.bcm file sock properties, can you detailed what each SOC property is for and whether these ones belong to the set where you do not expect any vendor from making changes from their specific SKU's config.bcm file?

**Comment by geans-pin** [comment]
> @geans-pin For the 6 common config.bcm file sock properties, can you detailed what each SOC property is for and whether these ones belong to the set where you do not expect any vendor from making changes from their specific SKU's config.bcm file?

Per HLD reply, we will provide the detail for each SOC property in an enhancement PR after this baseline PR is merged.
So far we are collecting the information from the BRCM Team ...

Geans

**Comment by geans-pin** [comment]
Gechiang,

Pls check the property readme I uploaded.

Geans

**Review by gechiang — APPROVED** [review]

**Pull request merged**
