### PR TITLE
Add  snh60b0-640 and snh60a0-320fv2  devices

### PR DESCRIPTION
**Pull request by juntseng62**
ASIC Vendor: Broadcom
Swich ASIC:
  1.Tomhawk2 chip: for snh60b0-640f device
  2.Tomhawk chip: for snh60a0-320fv2 device

**- What I did**
  1. Add new platform snh60b0-640f
  2. Add new platform snh60a0-320fv2

**- How I did it**
  Provide device and plarform related files.
**- How to verify it**
	How to verify it
	psuutil status
	sfputil show presence
	sfputil show eeprom
	decode-syseeprom
	sensors
	fan policy check
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
@juntseng62 , can you please sign cla.

Since we are going to merge the debian 9 kernel in about one month, we do not deal with new platform in the master. The reason is that if the platform is going to be support in the next June release. You need to make your platform driver ready for debian 9 kernel. Meanwhile, you can still check-in your code into March relase (201803) branch.

As we have discussed in the community meeting, we wound like to check-in the platform module into buildimage repo instead of using submodule. It is proven to be easier for later kernel patch upgrade. So, can you remove your submodule and check-in the source code file directly?

The debian 9 kernel is at https://github.com/lguohan/sonic-buildimage/tree/stretch

**Comment by juntseng62** [comment]
lguohan,
Do I need to  cancel the PR and request another PR in branch 201803  or just sign the CLA?

**Comment by lguohan** [comment]
sign cla is ok. I can merge it into 201803 branch.

**Comment by juntseng62** [comment]
@lguohan 
We are going to sign CLA, and will modify code. I need to cancel this PR and send another request to check-in code into March relase (201803) branch right?

**Pull request closed without merging**
