### PR TITLE
update SAI and sonic-utilities submodules

### PR DESCRIPTION
**Pull request by pavel-shirshov**

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
can you check the commit id in SAI?

**Comment by lguohan** [comment]
the commit in the SAI is https://github.com/opencomputeproject/SAI/commit/940c7b6afb1db4e8504b7cdb24ccd669748dbde8

**Comment by pavel-shirshov** [comment]
In my local repo

git show
commit a6b5b3115f39f599d39629ab9bfaeea17333d0bc
Merge: a967527 aa4d316
Author: svc-acs <svc-acs@users.noreply.github.com>
Date:   Tue May 30 12:11:11 2017 -0700

    Merge pull request #605 from pavel-shirshov/pavelsh/pysai

    [python-saithrift package]: Install package into /usr/, not /usr/local/

I'll fix it asap

**Comment by pavel-shirshov** [comment]
Fix: https://github.com/Azure/sonic-buildimage/pull/647

Someone made a forced update of SAI repo.
git pull
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/opencomputeproject/SAI
 + a6b5b31...940c7b6 v0.9.4     -> origin/v0.9.4  (forced update)
Merge made by the 'recursive' strategy.

**Pull request merged**
