### PR TITLE
[sairedis] Big refactor/rebase TEST ONLY DO NOT MERGE

### PR DESCRIPTION
**Pull request by kcudnik**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by kcudnik** [comment]
retest this please

**Comment by kcudnik** [comment]
retest this please

**Comment by kcudnik** [comment]
retest this please

**Comment by kcudnik** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by kcudnik** [comment]
retest this please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by kcudnik** [comment]
retest vsimage

**Comment by kcudnik** [comment]
retest vs please

**Comment by kcudnik** [comment]
retest vsimage please

**Comment by kcudnik** [comment]
retest vsimage please

**Pull request closed without merging**
