### PR TITLE
[build] Fix rules/functions generate_manifest function

### PR DESCRIPTION
**Pull request by liushilongbuaa**
#### Why I did it
Fix a bug in sonic debug image build. That bug is imported in the following PR:
https://github.com/Azure/sonic-buildimage/pull/8920
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [x] 202106

### CODE REVIEW

**Comment by stepanblyschak** [comment]
@liushilongbuaa What is the issue?

**Comment by liushilongbuaa** [comment]
> @liushilongbuaa What is the issue?

Official debug sonic image build break.
generate_manifest uses 'j2 $($*.gz_PATH)/Dockerfile$(2).j2' command to generate Dockerfile.
If replace '-dbg' with 'dbg', j2 can't find correct Template file.

**Comment by stepanblyschak** [comment]
I think ```j2 $($*.gz_PATH)/Dockerfile$(2).j2``` in generate_manifest was a copy paste mistake. The generate_manifest should not generate the Dockerfile. The Dockerfile is generated by slave.mk https://github.com/Azure/sonic-buildimage/blob/master/slave.mk#L814 and for debug dockers - https://github.com/Azure/sonic-buildimage/blob/master/slave.mk#L871. I suggest just to remove the line ```j2 $($*.gz_PATH)/Dockerfile$(2).j2```.

**Comment by liushilongbuaa** [comment]
@stepanblyschak I think you are right. I triggered a job to validate this PR. https://dev.azure.com/mssonic/build/_build/results?buildId=53359&view=results

**Review by lguohan — APPROVED** [review]

**Review by xumia — APPROVED** [review]

**Comment by xumia** [comment]
It is failed in publishing the artifacts step, it will be fixed in another PR https://github.com/Azure/sonic-buildimage/pull/9357, force push it to break the loop.

**Pull request merged**
