### PR TITLE
[Mellanox] [202012] Update SDK to v4.4.3360 and FW to v2008.3358

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Signed-off-by: Volodymyr Samotiy <volodymyrs@nvidia.com>

#### Why I did it
To include latest fixes.

> * On CMIS modules, after low power configuration, the firmware waited for the module state to be ModuleReady instead of ModuleLowPower causing delays.
> * When connecting Spectrum devices with optical transceivers that support RXLOS, remote side port down might cause the switch firmware to get stuck and cause unexpected switch behavior. 
> * On rare occasions, when working with port rates of 1GbE or 10GbE and congestion occurs, packets may get stuck in the chip and may cause switch to hang. 
> * When ECMP has high amount of next-hops based on VLAN interfaces, in some rare cases, packets will get a wrong VLAN tag and will be dropped. 
> * Using SN4600C with copper or optics loopback cables in NRZ speeds, link may raise in long link up times ( up to 70 seconds). 
> * When connecting SN4600C to SN4600C after Fastboot in 50GbE No_FEC mode with a copper cable, the link up time may take ~20 seconds. 

#### How I did it
Updated SDK submodule and relevant makefiles with the required versions.

#### How to verify it
Build an image and run tests from "soni-mgmt".

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog

[Mellanox] Update SDK to v4.4.3360 and FW to v2008.3358

### CODE REVIEW

**Comment by prsunny** [comment]
Could you please list the fixes in description?

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
