### PR TITLE
[config] Do not fail for minigraphs which do not have neighbors listed in <Devices> section

### PR DESCRIPTION
**Pull request by NStetskovych**
Signed-off-by: Nadiya.Stetskovych <nstetskovych@barefootnetworks.com>

**- What I did**
add a check if  neighbors metadata exist

**- How to verify it**
apply `config load_minigraph -y` upon old minigraph without DEVICE_NEIGHBOR_METADATA

**- A picture of a cute animal (not mandatory but encouraged)**
```
 __         __
/  \.-"""-./  \
\    -   -    /
 |   o   o   |
 \  .-'''-.  /
  '-\__Y__/-'
     `---`
```

### CODE REVIEW

**Comment by NStetskovych** [comment]
@lguohan pls review

**Comment by jleveque** [comment]
Retest this please.

**Comment by lguohan** [comment]
please fix master first, after it is merge into master we can do cherry-pick.

**Comment by NStetskovych** [comment]
@lguohan  https://github.com/Azure/sonic-buildimage/pull/2522

**Comment by jleveque** [comment]
Closing this PR in favor of https://github.com/Azure/sonic-buildimage/pull/2522

**Pull request closed without merging**
