### PR TITLE
Add fsck filesystem check support prior mounting filesystem

### PR DESCRIPTION
**Pull request by olivier-singla**
If the filesystem become non clean ("dirty"), SONiC does not run fsck to
repair and mark it as clean again.

This patch adds the functionality to run fsck on each boot, prior to the
filesystem being mounted. This allows the filesystem to be repaired if
needed.

Note that if the filesystem is maked as clean, fsck does nothing and simply
return so this is perfectly fine to call fsck every time prior to mount the
filesystem.

How to verify this partch:

Using an image without this patch:

1) Make the filesystem "dirty" (not clean)
[we are making the assumption that filesystem is stored in /dev/sda3 - Please adjust depending of the platform]
[do this only on a test platform!]

dd if=/dev/sda3 of=superblock bs=1 count=2048
printf "$(printf '\\x%02X' 2)" | dd of="superblock" bs=1 seek=1082 count=1 conv=notrunc &> /dev/null
dd of=/dev/sda3 if=superblock bs=1 count=2048

2) Verify that filesystem is not clean

tune2fs -l /dev/sda3 | grep "Filesystem state:"

3) reboot and verify that the filesystem is still not clean

Redo the same test with an image with this patch, and verify that at next reboot the filesystem is repaired and becomes clean.

### CODE REVIEW

**Comment by olivier-singla** [comment]
retest vsimage please

**Comment by olivier-singla** [comment]
retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by lguohan** [comment]
have you checked this option?

https://unix.stackexchange.com/questions/216105/how-to-force-a-file-system-check-on-the-next-boot-of-the-root-file-system-on-gen

**Pull request closed without merging**
