### PR TITLE
[bgpcfgd] to support removal part of configuration of bgp allowed prefix list

### PR DESCRIPTION
**Pull request by StormLiangMS**
#### Why I did it
Failed to remove part of configuration of bgp allowed prefix list. The details in #10141

#### How I did it
There are two issues:
1. In FRR, ipv6 default route is ::/0, but in the configuration, it is 0::/0, string comparison would be false, but why ipv4 failed to remove the allowed prefix list, ipv6 works? Looks into next one for the answer. 

2. The current managers_allow_list doesn’t support removal part of the prefix list. But why IPv6 works in 1? It is because the bug for the IPv6 default route comparison, it would do the update no matter what is the operation (the code will compare the prefix list in the FRR and configuration db, if all configurations in db are presented in FRR, it do nothing, otherwise it will update the prefix list based on the configuration from db).

#### How to verify it
Follow the step in #10141

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by wen587** [comment]
Hi Storm, any way to apply the change on my existing kvm machine?
Or I have to rebuild the image?

**Comment by StormLiangMS** [comment]
@wen587 You can just copy the file managers_allow_list.py to the bgp docker, then restart the bpgcfgd, below are detailed steps. 
1. Upload the managers_allow_list.py to the TB by scp.
2. In TB, copy the managers_allow_list.py to the bgp docker.
   `docker cp managers_allow_list.py bgp:/`
3. Enter the docker, find the file and replace it. 
  ```
root@vlab-01:/# find / -name "managers_allow_list.py"
  /usr/local/lib/python3.7/dist-packages/bgpcfgd/managers_allow_list.py
cp /managers_allow_list.py /usr/local/lib/python3.7/dist-packages/bgpcfgd/managers_allow_list.py
```
4. Restart the bgpcfgd in the bgp docker
root@vlab-01:/# supervisorctl 
bgpcfgd                          RUNNING   pid 8735, uptime 1 day, 1:58:28
bgpd                             RUNNING   pid 50, uptime 1 day, 19:08:56
bgpmon                           RUNNING   pid 58, uptime 1 day, 19:08:56
dependent-startup                EXITED    Mar 06 01:47 PM
fpmsyncd                         RUNNING   pid 59, uptime 1 day, 19:08:56
rsyslogd                         RUNNING   pid 196, uptime 1 day, 19:03:22
staticd                          RUNNING   pid 49, uptime 1 day, 19:08:56
supervisor-proc-exit-listener    RUNNING   pid 28, uptime 1 day, 19:08:59
zebra                            RUNNING   pid 35, uptime 1 day, 19:08:58
zsocket                          EXITED    Mar 06 01:47 PM
supervisor> restart bgpcfgd
5. wait for 1 mins before the bgpcfgd come back to service. 
6. Then the new manager allow list function is in place.

**Review by wen587 — COMMENTED** [review]
LGTM

**Review by abdosi — APPROVED** [review]

**Pull request merged**
