### PR TITLE
Dell S6100: Modify transceiver change event from interrupt to poll mode

### PR DESCRIPTION
**Pull request by aravindmani-1**
#### Why I did it

- xcvrd crash was seen in latest 201811 images.
- For Dell S6100,API 2.0 uses poll mode while 1.0 was still using interrupt mode.

#### How I did it

- Modified get_transceiver_change_event in 1.0 to poll mode.

#### How to verify it

- Do OIR testing, check xcvrd status and syslogs.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

#### Description for the changelog
[UT:]
[s6100_xcvr_UT.txt](https://github.com/Azure/sonic-buildimage/files/6305328/s6100_xcvr_UT.txt)

### CODE REVIEW

**Comment by jleveque** [comment]
>xcvrd crash was seen in latest 201811 images.

@aravindmani-1: This PR is raised against the master branch with no indication that it should be backported to other branches. Is this expected?

**Comment by aravindmani-1** [comment]
> > xcvrd crash was seen in latest 201811 images.
> 
> @aravindmani-1: This PR is raised against the master branch with no indication that it should be backported to other branches. Is this expected?

Cherry pick to 201811 may not work. I'll raise a separate PR for 201811 branch.

**Comment by jleveque** [comment]
> Cherry pick to 201811 may not work. I'll raise a separate PR for 201811 branch.

@aravindmani-1: What about 202012 and 201911 branches?

**Comment by aravindmani-1** [comment]
> > Cherry pick to 201811 may not work. I'll raise a separate PR for 201811 branch.
> 
> @aravindmani-1: What about 202012 and 201911 branches?
Added the cherry pick request for 202012.  For 201911, i'll have to raise a separate PR. sfputil changes will be merged properly but platform init script varies across branches. so, cherry pick might not work.

**Review by jleveque — APPROVED** [review]

**Pull request merged**
