### PR TITLE
Rectify buffer_port_profile(ing/egr) yang files & related tests

### PR DESCRIPTION
**Pull request by AmitKaushik7**
#### Why I did it
Rectified Buffer Port Ingress/Egress Profile yang files derived from sonic/mgmt-cvl/testdata/schema from sonic-mgmt-common,  used by mgmt-framework.

Updated BUFFER_PORT_INGRESS_PROFILE_LIST and BUFFER_PORT_EGRESS_PROFILE_LIST - Use Comma Separated string as profile list instead of List of Profile.

#### How I did it
         "BUFFER_PORT_EGRESS_PROFILE_LIST": {
             "Ethernet9": {
-                "profile_list": ["egress_lossless_profile", "egress_lossy_profile"]   <== Removed
+                "profile_list": "egress_lossless_profile, egress_lossy_profile"     <== Added
             }
         },

Same change for BUFFER_PORT_INGRESS_PROFILE_LIST. 

#### How to verify it
Rectified the test cases for ingress/egress buffer profile list.
test_yang_model.py         210 INFO     BUFFER_PORT_INGRESS_PROFILE_LIST_CORRECT_PROFILE_VALUE no failure Passed
test_yang_model.py         210 INFO     BUFFER_PORT_EGRESS_PROFILE_LIST_WRONG_PORT_VALUE pattern failure Passed
test_yang_model.py         210 INFO     BUFFER_PORT_EGRESS_PROFILE_LIST_CORRECT_PROFILE_VALUE no failure Passed
test_yang_model.py         210 INFO     BUFFER_PORT_EGRESS_PROFILE_LIST_MANDATORY_PROFILE_VALUE no profile Passed
test_yang_model.py         210 INFO     BUFFER_PORT_INGRESS_PROFILE_LIST_MANDATORY_PROFILE_VALUE no profile Passed
test_yang_model.py         210 INFO     BUFFER_PORT_INGRESS_PROFILE_LIST_WRONG_PORT_VALUE pattern failure Passed

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

#### Description for the changelog

Rectify buffer_port_profile(ing/egr) yang files & update related test cases.

### CODE REVIEW

**Comment by qiluo-msft** [comment]
@Junchao-Mellanox Please help review.

**Comment by Junchao-Mellanox** [comment]
The old yang definition looks better. Could you please elaborate the reason to change it from string to list? There is already a PR to handle DPB issue: https://github.com/Azure/sonic-buildimage/pull/10291

**Comment by AmitKaushik7** [comment]
I have not heard back on my comments last week in PR#9801, hence raised this PR.
If you agree that old yang model is correct, then I will cancel this PR.

**Comment by dgsudharsan** [comment]
@AmitKaushik7 The suggestion from the yang community is to first initially fix it in yang infraand then slowly correct the offending configurations and not the yang model itself. Please sync up with @bandaru-viswanath

**Comment by AmitKaushik7** [comment]
Ok. closing the PR.

**Pull request closed without merging**
