### PR TITLE
[hostcfgd] Fix crash bug

### PR DESCRIPTION
**Pull request by ouxlwhu**
**- Why I did it**
when I set ip for Loopback0 , hostcfgd will exit, and log is like this:

Jul 20 16:50:50.316075 leaf-229 INFO hostcfgd[1012]: Traceback (most recent call last): 
Jul 20 16:50:50.316674 leaf-229 INFO hostcfgd[1012]: File "/usr/bin/hostcfgd", line 400, in <module> 
Jul 20 16:50:50.317109 leaf-229 INFO hostcfgd[1012]: main() 
Jul 20 16:50:50.317539 leaf-229 INFO hostcfgd[1012]: File "/usr/bin/hostcfgd", line 396, in main 
Jul 20 16:50:50.317968 leaf-229 INFO hostcfgd[1012]: daemon.start() 
Jul 20 16:50:50.318398 leaf-229 INFO hostcfgd[1012]: File "/usr/bin/hostcfgd", line 391, in start 
Jul 20 16:50:50.318828 leaf-229 INFO hostcfgd[1012]: self.config_db.listen() 
Jul 20 16:50:50.319289 leaf-229 INFO hostcfgd[1012]: File "/usr/local/lib/python2.7/dist-packages/swsssdk/configdb.py", line 112, in listen 
Jul 20 16:50:50.319791 leaf-229 INFO hostcfgd[1012]: self.__fire(table, row, data) 
Jul 20 16:50:50.320263 leaf-229 INFO hostcfgd[1012]: File "/usr/local/lib/python2.7/dist-packages/swsssdk/configdb.py", line 97, in __fire 
Jul 20 16:50:50.320734 leaf-229 INFO hostcfgd[1012]: handler(table, key, data) 
Jul 20 16:50:50.321206 leaf-229 INFO hostcfgd[1012]: File "/usr/bin/hostcfgd", line 389, in <lambda> 
Jul 20 16:50:50.321677 leaf-229 INFO hostcfgd[1012]: self.config_db.subscribe('LOOPBACK_INTERFACE', lambda table, key, data: self.lpbk_handler(key, data)) 
Jul 20 16:50:50.322150 leaf-229 INFO hostcfgd[1012]: File "/usr/bin/hostcfgd", line 335, in lpbk_handler 
Jul 20 16:50:50.322621 leaf-229 INFO hostcfgd[1012]: key = ConfigDBConnector.deserialize_key(key) 
Jul 20 16:50:50.323098 leaf-229 INFO hostcfgd[1012]: TypeError: unbound method deserialize_key() must be called with ConfigDBConnector instance as first argument (got unicode instance instead) 
Jul 20 16:50:50.339127 leaf-229 NOTICE systemd[1]: hostcfgd.service: Main process exited, code=exited, status=1/FAILURE 
Jul 20 16:50:50.340624 leaf-229 NOTICE systemd[1]: hostcfgd.service: Unit entered failed state. 
Jul 20 16:50:50.341193 leaf-229 WARNING systemd[1]: hostcfgd.service: Failed with result 'exit-code'. 

**- How I did it**
replace  'key = ConfigDBConnector.deserialize_key(key) ' with 'key = self.config_db.deserialize_key(key) '

**- How to verify it**
set ip for Loopback0

**- Which release branch to backport (provide reason below if selected)**

- [x] 201811
- [x] 201911
- [x] 202006
-->these three branch are same code with master

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by ouxlwhu** [comment]
> retest vsimage please

Hi, is there anything that I can do for this test failed?   ^_^

**Comment by lguohan** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
Not sure why it fails at the same place each time? @daall, do you have idea?

`Test Result (1 failure / +1)pc.test_po_cleanup.test_po_cleanup`

**Comment by daall** [comment]
> Not sure why it fails at the same place each time? @daall, do you have idea?
> 
> `Test Result (1 failure / +1)pc.test_po_cleanup.test_po_cleanup`

It's failing semi-frequently across the board. Opened https://github.com/Azure/sonic-buildimage/issues/5432 to track.

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
how to repro this bug?

**Comment by ouxlwhu** [comment]
Hi，how to process this pull request？

**Comment by lguohan** [comment]
is this still needed?

**Comment by ouxlwhu** [comment]
> is this still needed?

No，it is no longer needed

**Pull request closed without merging**
