### PR TITLE
[pmon] Move smartctl from pmon to host

### PR DESCRIPTION
**Pull request by alexrallen**
#### Why I did it

Need to be able to run `smartctl` when pmon docker is not running. 

#### How I did it

Removed the pmon dependency for pmon as well as the command wrapper and added it to the debian-extension. 

#### How to verify it

* Stop pmon
* Run `smartctl` from the host and verify it runs without error

#### Which release branch to backport (provide reason below if selected)

None.

#### Description for the changelog
[pmon] Move smartctl from pmon to host

### CODE REVIEW

**Comment by qiluo-msft** [comment]
What is the reason that pmon docker is not running?

**Comment by alexrallen** [comment]
I need smartctl to be accessible during reboot in order to perform firmware installations. I also believe that it is important for a diagnostic tool such as smartctl to not be dependent on high level functionality like docker.

**Review by sujinmkang — DISMISSED** [review]

**Comment by alexrallen** [comment]
@sujinmkang I fixed the conflict, please re-review.

**Review by sujinmkang — APPROVED** [review]

**Comment by judyjoseph** [comment]
@alexrallen There are conflicts merging into 202111, please raise a new PR on branch 20211.

**Pull request merged**
