### PR TITLE
[quagga bgp] set quagga graceful restart timeout to 180 seconds

### PR DESCRIPTION
**Pull request by yxieca**
**- What I did**
set quagga graceful restart timeout to 180 seconds

We need graceful restart timeout of 180 for warm reboot.

### CODE REVIEW

**Comment by rodnymolina** [comment]
@yxieca Can you please also adjust the default timer we are using at fpmsyncd level? Both timers should ideally match, at least till we have a synchronization mechanism between bgpd and fpmsyncd.

**Comment by zhenggen-xu** [comment]
@rodnymolina Since this only change quagga default timer, it might not be exactly right to change the fpmsyncd timer alone. 
If we want to keep everything in sync, we should change FRR configuration to 120s too, and then fpmsyncd changes in a different PR against sonic-swss.

Or we can have timer configuration in the config-db per platform.

**Comment by nikos-github** [comment]
@rodnymolina @zhenggen-xu This is changing the timer for the peer. That's completely unrelated to the local fpmsyncd timer. The two timers must not have a requirement to match nor should they be compared against each other. The synchronization you are referring to has no bearing or influence to the peer restart timer the local system has sent.

**Comment by zhenggen-xu** [comment]
@nikos-github I was referring the case where you have SONiC deployed at different layers as we change the graceful restart timer for all SONiC devices in the PR,  if the peer SONiC device has graceful restart timer changed to be 180s, we should keep the local fpmsyncd default timer matching that. 
Even the peer is not SONiC, if it was configured as 180 seconds already (probably the case for MSFT), we should match too. 
If the configuration are not consistent for different devices, that should be handled by config-DB settings as mentioned earlier, but the default should be consistent across SONiC devices.

**Comment by lguohan** [comment]
retest this please

**Comment by nikos-github** [comment]
@rodnymolina The artificial correlation you are making between the timers is not correct irrespective of a signal or not for EoR. We can discuss offline.

**Comment by lguohan** [comment]
@rodnymolina , I feel the two timers are not related. the gr timer is between the bgp shutdown and bgp session setup after reboot, the local timer starts after the bgp session setup after reboot.

**Comment by rodnymolina** [comment]
@lguohan I agree/understand that both timers can potentially measure different things, but in the absence of a mechanism to sync-up bgp and fpmsyncd (through a EoR/EOIU message), i feel it's a good idea to have both timers being more and less in-sync. My point is specially valid for typical warm-reboot use-cases (daemon/docker restart), as in these scenarios both bgp-gr-timer and fpmsyncd-timer are going to be measuring similar things. On the other hand, i understand that this correlation is much weaker on the system-warm-reboot case, as both timers can/will diverge.

Question is, which case should we optimize for? I feel that warm-restart scenarios (daemon/docker restart) are much more frequent than system-warm-reboot ones, so i'd rather cover the first scenario as best as we can. And perhaps we could go even further: forget about the system-warm-reboot case altogether, so that we can set more reasonable bgp-gr timers (~30 secs) and reduce the suboptimal-routing window. If we are interesting in optimizing for the warm-restart case, bgp-gr-timer and fpmsyncd-timer values would need to be (more and less) in-sync.

**Pull request merged**
