### PR TITLE
[DPB][YANG-models] extended regex pattern according to Mellanox systems speeds requirements

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
**- Why I did it**

All Mellanox platforms require DPB modes with a specific set of speeds [example](https://github.com/Azure/sonic-buildimage/pull/6021/files)

**- How I did it**

Extended regex pattern inside YANG model.
Supported platforms: `SN2010`, `SN2100`, `SN2410`, `SN2700`, `SN3420`, `SN3700`, `SN3700C`, `SN3800`, `SN4600C`, `SN4410`, `SN4700`

**- How to verify it**

Manually tested DPB CLI on all platform with all modes

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
retest vs please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by vadymhlushko-mlnx** [comment]
retest vsimage please

**Comment by zhenggen-xu** [comment]
I think sonic-breakout_cfg.yang should be removed and backend should check the speed by platform.json, and not  limit this into yang models.  This is going to be accommodated by https://github.com/Azure/sonic-utilities/pull/1020 and new PR(s).  sonic-port.yang changes are fine. 

@praveen-li

**Comment by liat-grozovik** [comment]
> I think sonic-breakout_cfg.yang should be removed and backend should check the speed by platform.json, and not limit this into yang models. This is going to be accommodated by [Azure/sonic-utilities#1020](https://github.com/Azure/sonic-utilities/pull/1020) and new PR(s). sonic-port.yang changes are fine.
> 
> @praveen-li

I believe this approach is better but it will take time until it will be available. Meanwhile we are blocked with many PRs.
As of that i think this change should be merged, later on it will be not relevant as you will do the changes mentioned above.
Can we proceed with this PR approval and merge?

**Comment by lguohan** [comment]
@zhenggen-xu , what are the new PRs you mentioned?

**Comment by zhenggen-xu** [comment]
OK, we can get this,  we will have new PR to remove the sonic-breakout_cfg.yang and make the configMgmt logic to check the mode instead.

**Review by zhenggen-xu — APPROVED** [review]

**Review by praveen-li — CHANGES_REQUESTED** [review]
Please add atleast a new test with it. 

To add Test:
1.) Add Config at https://github.com/Azure/sonic-buildimage/blob/e52581e919c95e861cf630c9c7e1a840fc5e8ebd/src/sonic-yang-models/tests/yang_model_tests/yangTest.json#L2

2.) Add matching detail and expected error string at:
https://github.com/Azure/sonic-buildimage/blob/e52581e919c95e861cf630c9c7e1a840fc5e8ebd/src/sonic-yang-models/tests/yang_model_tests/test_yang_model.py#L52

**Review by praveen-li — APPROVED** [review]
LGTM, note it may be possible that we may deprecate BRK_CFG Yang model later. Thx.

**Comment by vadymhlushko-mlnx** [comment]
Retest vsimage please

**Review by zhenggen-xu — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
