### PR TITLE
Add support as9716-32d platform

### PR DESCRIPTION
**Pull request by jostar-yang**
**- What I did**
Add support as9716-32x platform
**- How I did it**
Add support as9716-32x platform
**- How to verify it**
Test sysfs node and sensors comand
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jostar-yang** [comment]
Add testing report,
root@sonic:/home/admin# sensors
acbel_fsh082-i2c-10-59
Adapter: i2c-1-mux (chan_id 1)
in3:         +12.12 V
fan1:        14080 RPM
temp1:        +28.0 C
power2:       88.75 W
curr2:        +7.75 A

lm75-i2c-18-49
Adapter: i2c-1-mux (chan_id 1)
temp1:        +44.0 C  (high = +80.0 C, hyst = +75.0 C)

acbel_fsh082-i2c-9-58
Adapter: i2c-1-mux (chan_id 0)
in3:         +11.95 V
fan1:        14080 RPM
temp1:        +31.0 C
power2:      105.62 W
curr2:        +8.75 A

as9716_32d_fan-i2c-17-66
Adapter: i2c-1-mux (chan_id 0)
fan1:        20900 RPM
fan2:        20800 RPM
fan3:        20800 RPM
fan4:        20800 RPM
fan5:        20900 RPM
fan6:        20800 RPM
fan11:       22000 RPM
fan12:       21700 RPM
fan13:       21700 RPM
fan14:       21000 RPM
fan15:       22000 RPM
fan16:       21700 RPM

pch_haswell-virtual-0
Adapter: Virtual device
temp1:        +54.0 C

lm75-i2c-18-4f
Adapter: i2c-1-mux (chan_id 1)
temp1:        +42.0 C  (high = +80.0 C, hyst = +75.0 C)

lm75-i2c-18-4c
Adapter: i2c-1-mux (chan_id 1)
temp1:        +45.5 C  (high = +80.0 C, hyst = +75.0 C)

lm75-i2c-18-4a
Adapter: i2c-1-mux (chan_id 1)
temp1:        +40.0 C  (high = +80.0 C, hyst = +75.0 C)

lm75-i2c-18-48
Adapter: i2c-1-mux (chan_id 1)
temp1:        +39.0 C  (high = +80.0 C, hyst = +75.0 C)

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +61.0 C  (high = +82.0 C, crit = +104.0 C)
Core 0:         +61.0 C  (high = +82.0 C, crit = +104.0 C)
Core 1:         +61.0 C  (high = +82.0 C, crit = +104.0 C)
Core 2:         +61.0 C  (high = +82.0 C, crit = +104.0 C)
Core 3:         +61.0 C  (high = +82.0 C, crit = +104.0 C)

lm75-i2c-18-4e
Adapter: i2c-1-mux (chan_id 1)
temp1:        +37.5 C  (high = +80.0 C, hyst = +75.0 C)

lm75-i2c-18-4b
Adapter: i2c-1-mux (chan_id 1)
temp1:        +35.0 C  (high = +80.0 C, hyst = +75.0 C)

**Comment by lguohan** [comment]
can you fix build error?

**Comment by jostar-yang** [comment]
I add as9716-32d to debian rule and control for fix build error. Please check "d26d253a".

**Comment by lguohan** [comment]
can you resolve conflict?

**Comment by jostar-yang** [comment]
> can you resolve conflict?

**Comment by jostar-yang** [comment]
> can you resolve conflict?

I add as4630 platform to build-file that resolve conflict

**Comment by lguohan** [comment]
there are still conflict.

**Comment by lguohan** [comment]
there are still conflict.

**Comment by jostar-yang** [comment]
Close this PR(as9716_20190508 branch) due to there is another PR has sent.

**Pull request closed without merging**
