### PR TITLE
[swss-common]: Advance submodule

### PR DESCRIPTION
**Pull request by qiluo-msft**
```
ec96868 2020-11-03 | Fix: treat DBConnector timeout=0 as infinite timeout (#408) [Qi Luo]
b4b8334 2020-11-03 | Add lua script for redis multi keys api hmset and del (#406) [Kamil Cudnik]
```

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by lguohan** [comment]
retest vs please

**Comment by lguohan** [comment]
build issue unrelated.

**Pull request merged**
