### PR TITLE
[device/celestica] blacklist gpio_ich kernel module on seastone

### PR DESCRIPTION
**Pull request by pphuchar**
**- What I did**
Blacklist Intel gpio_ich kernel module driver.

**- How I did it**
Add the extra kernel parameter in seastone device installer.conf file.

**- How to verify it**
After SONiC bootup, the gpio_ich will not load by default.
 
**- Description for the changelog**

- Blacklist Intel gpio_ich in the seastone device.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
please add to haliburton.

**Comment by pphuchar** [comment]
> this should be haliburton.

Seastone also need this blacklist.

**Comment by lguohan** [comment]
your other PR is not correct, it says haliburton, but it was actually seastone.

**Comment by pphuchar** [comment]
> your other PR is not correct, it says haliburton, but it was actually seastone.

Oh, will revert #2692 and update this PR.

**Pull request merged**
