### PR TITLE
[DellEMC] S6100 Platform Service optimization

### PR DESCRIPTION
**Pull request by santhosh-kt**
<!--
     Please make sure you've read and understood our contributing guidelines:
     https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

     ** Make sure all your commits include a signature generated with `git commit -s` **

     If this is a bug fix, make sure your description includes "fixes #xxxx", or
     "closes #xxxx" or "resolves #xxxx"

     Please provide the following information:
-->

#### Why I did it
- To reduce rc.local script execution time.
- Time consumption of rc.local script is around 22 seconds in S6100.

#### How I did it
- Moving platform-modules-s6100.service and s6100-lpc-monitor.service asynchronous to rc.local script.

#### How to verify it
- Load the image with the changes and the time consumption of rc.local script reduced from 22 seconds(approx.) to 14 seconds(approx.) during warm-/fast-reboot upgrades.
- sonic-mgmt test results.
[Logs.zip](https://github.com/Azure/sonic-buildimage/files/8812544/Logs.zip)


#### Which release branch to backport (provide reason below if selected)

<!--
- Note we only backport fixes to a release branch, *not* features!
- Please also provide a reason for the backporting below.
- e.g.
- [x] 202006
-->

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

#### Description for the changelog
<!--
Write a short (one line) summary that describes the changes in this
pull request for inclusion in the changelog:
-->
On branch 202012                                                                                                                                                                           
Your branch is up to date with 'origin/202012'.                                                                                                                                            
                                                                                                                                                                                           
Changes to be committed:                                                                                                                                                                   
  (use "git restore --staged <file>..." to unstage)                                                                                                                                        
        deleted:    ../platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.init                                                                                    
        modified:   ../platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh
        modified:   ../platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.postinst 

#### Link to config_db schema for YANG module changes
<!--
Provide a link to config_db schema for the table for which YANG model
is defined
Link should point to correct section on https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md
-->

#### A picture of a cute animal (not mandatory but encouraged)

### CODE REVIEW

**Review by vaibhavhd — APPROVED** [review]
LGTM, please wait for Sujin's review before merge.

**Comment by vaibhavhd** [comment]
We need this change for master, 2022** branches too. Will there be separate PRs for that?

**Comment by aravindmani-1** [comment]
> We need this change for master, 2022** branches too. Will there be separate PRs for that?

We will raise separate PRs

**Review by sujinmkang — APPROVED** [review]

**Comment by yxieca** [comment]
@santhosh-kt please create master branch PR and we will cherry-pick it from master branch. Thanks.

**Comment by santhosh-kt** [comment]
Raised https://github.com/Azure/sonic-buildimage/pull/11329 for 202205 branch and https://github.com/Azure/sonic-buildimage/pull/11330 for master branch

**Pull request merged**
