### PR TITLE
[202311][Mellanox] implement platform wait in python code (#17398)

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Backport PR https://github.com/sonic-net/sonic-buildimage/pull/17398

#### Why I did it

New implementation of Nvidia platform_wait due to:

1. sysfs deprecated by hw-mgmt
2. new dependencies to SDK
3. For CMIS host management mode

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

- wait hw-management ready
- wait SDK sysfs nodes ready

#### How to verify it

manual test
unit test
sonic-mgmt regression

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
> No pipelines are associated with this pull request.

@liushilongbuaa can you help check this failure? Thanks.

**Comment by liushilongbuaa** [comment]
> > No pipelines are associated with this pull request.
> 
> @liushilongbuaa can you help check this failure? Thanks.

Hi Ying, you forgot a 'e' in pipeline name.

**Comment by yxieca** [comment]
@Junchao-Mellanox can you rebase your branch to latest 202311 with this PR? https://github.com/sonic-net/sonic-buildimage/pull/17748

**Comment by Junchao-Mellanox** [comment]
Hi @yxieca , checker passed. Could you please help merge?

**Pull request merged**
