### PR TITLE
[sonic-utilities] Build and install as a Python wheel package

### PR DESCRIPTION
**Pull request by jleveque**
**- Why I did it**
We are moving toward building all Python packages for SONiC as wheel packages rather than Debian packages. This will also allow us to more easily transition to Python 3.

Python files are now packaged in "sonic-utilities" Pyhton wheel. Data files are now packaged in "sonic-utilities-data" Debian package.

This PR will need to update the following submodules once these PRs are merged:
- [x] https://github.com/Azure/sonic-utilities/pull/1122
- [x] https://github.com/Azure/sonic-ztp/pull/19

Submodule updates:

* src/sonic-utilities aa27dd9...2244d7b (5):
  > Support building sonic-utilities as a Python wheel package instead of a Debian package (#1122)
  > [consutil] Display remote device name in show command (#1120)
  > [vrf] fix check state_db error when vrf moving (#1119)
  > [consutil] Fix issue where the ConfigDBConnector's reference is missing (#1117)
  > Update to make config load/reload backward compatible. (#1115)

* src/sonic-ztp dd025bc...911d622 (1):
  > Update paths to reflect new sonic-utilities install location, /usr/local/bin/ (#19)

**- How I did it**
- Build and install sonic-utilities as a Python package
- Remove explicit installation of wheel dependencies, as these will now get installed implicitly by pip when installing sonic-utilities as a wheel
- Build and install new sonic-utilities-data package to install data files required by sonic-utilities applications
- Update all references to sonic-utilities scripts/entrypoints to either reference the new /usr/local/bin/ location or remove absolute path entirely where applicable

**- How to verify it**
Ensure all CLI-related functionality continues to work as expected

### CODE REVIEW

**Comment by jleveque** [comment]
Retest baseimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
@jleveque , can you also check if any change is needed in sonic-mgmt repo?

**Comment by jleveque** [comment]
@lguohan: sonic-mgmt PR is here: https://github.com/Azure/sonic-mgmt/pull/2247

**Pull request merged**
