### PR TITLE
[DellEMC-Z9332f] Fix platform issues

### PR DESCRIPTION
**Pull request by srideepDell**
**- Why I did it**
 Fixed issues identified in dev/system test

**- How I did it**
Changing platform api 2.0 code and platform startup script

**- How to verify it**
verified on target 9332

**- Description for the changelog**

[DellEMC-Z9332f] Fix platform issues
              * Change to optoe driver
              * fix API 2.0 issues
              * Support reboot reason

### CODE REVIEW

**Comment by srideepDell** [comment]
[ut_z9332.txt](https://github.com/Azure/sonic-buildimage/files/5716914/ut_z9332.txt)

**Comment by srideepDell** [comment]
> This pull request **introduces 2 alerts** when merging [e65a806](https://github.com/Azure/sonic-buildimage/commit/e65a8063a731d677bfac8e327c345d9c7c4e4049) into [e88c7d1](https://github.com/Azure/sonic-buildimage/commit/e88c7d11cae12a4973eca4f1ca9f4b4ba9facd71) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-buildimage/rev/pr-0e9e48b21a304ccaf7db9c41d1973f2318009327)
> 
> **new alerts:**
> 
> * 1 for Module imports itself
> * 1 for 'import *' may pollute namespace

from sonic_platform import * is required to import as sonic_platform
is being used ""https://github.com/Azure/sonic-mgmt/blob/master/tests/common/helpers/platform_api/scripts/platform_api_server.py#L14 and  "sonic-buildimage/src/sonic-utilities/watchdogutil/main.py" 
Also same change is done for all the platforms supporting api 2.0

**Review by jeff-yin — APPROVED** [review]

**Comment by srideepDell** [comment]
retest vsimage please

**Comment by jleveque** [comment]
> > This pull request **introduces 2 alerts** when merging [e65a806](https://github.com/Azure/sonic-buildimage/commit/e65a8063a731d677bfac8e327c345d9c7c4e4049) into [e88c7d1](https://github.com/Azure/sonic-buildimage/commit/e88c7d11cae12a4973eca4f1ca9f4b4ba9facd71) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-buildimage/rev/pr-0e9e48b21a304ccaf7db9c41d1973f2318009327)
> > **new alerts:**
> > 
> > * 1 for Module imports itself
> > * 1 for 'import *' may pollute namespace
> 
> from sonic_platform import * is required to import as sonic_platform
> is being used ""https://github.com/Azure/sonic-mgmt/blob/master/tests/common/helpers/platform_api/scripts/platform_api_server.py#L14 and "sonic-buildimage/src/sonic-utilities/watchdogutil/main.py"
> Also same change is done for all the platforms supporting api 2.0

We'll allow these warnings for the time being. We'll need to make a pass later and figure out how to eliminate them throughout all vendors' sonic_platform packages.

**Review by jleveque — APPROVED** [review]

**Pull request merged**
