### PR TITLE
fix SFP initialization in the Chassis for mlnx-platform-api

### PR DESCRIPTION
**Pull request by txj36**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
@txj36: From the previous PR which you closed, I assume this will need to get cherry-picked into the 201904 branch. Is that the only other branch?

**Comment by txj36** [comment]
> @txj36: From the previous PR which you closed, I assume this will need to get cherry-picked into the 201904 branch. Is that the only other branch?

Yes,  the mlnx-platform-api  is just introduced in the 201904 branch.

**Comment by jleveque** [comment]
Retest vs please

**Comment by txj36** [comment]
> Retest vs please
this is a new feature which not used yet.

**Pull request merged**
