### PR TITLE
Security kernel update to 4.9.189

### PR DESCRIPTION
**Pull request by olivier-singla**
This patch upgrade the kernel from version
4.9.0-9-2 (4.9.168-1+deb9u3) to 4.9.0-11-2 (4.9.189-3+deb9u2)

This PR needs another PR in sonic-linux-kernel:
https://github.com/Azure/sonic-linux-kernel/pull/116

### CODE REVIEW

**Comment by lguohan** [comment]
build failures, please check.

**Comment by qiluo-msft** [comment]
Did you make code change in https://github.com/Azure/sonic-linux-kernel/ first ?

**Comment by olivier-singla** [comment]
Yes, I made code change in both sonic-buildimage and sonic-linux-kernel, and I pushed sonc-linux-kernel first. Does that make a difference?
The two need to be built togethe: without sonic-linux-kernel kernel upgrade, sonic-buildimage kernel upgrade build will fail.
How do you handle the case when two PRs have a dependency and need to be built together?

**Comment by qiluo-msft** [comment]
Let's block this PR on https://github.com/Azure/sonic-linux-kernel/pull/116.
That one will be merged first, and then you need to update the submodule pointer in this PR.

**Comment by lguohan** [comment]
Azure/sonic-linux-kernel#116 is merged. Can you proceed and resolve the conflict?

**Comment by lguohan** [comment]
there is still build error. @olivier-singla , can you check? 

dpkg-source: error: cannot fstat file ./linux_4.9.168.orig.tar.xz: No such file or directory

**Comment by olivier-singla** [comment]
> there is still build error. @olivier-singla , can you check?
> 
> dpkg-source: error: cannot fstat file ./linux_4.9.168.orig.tar.xz: No such file or directory

This PR needs another PR in sonic-linux-kernel:
Azure/sonic-linux-kernel#116

I think this is because this issue is being seen.

So we need to apply these two PR simultaneously:
https://github.com/Azure/sonic-linux-kernel/pull/116
https://github.com/Azure/sonic-buildimage/pull/3913

**Comment by rajendra-dendukuri** [comment]
retest please

**Comment by rajendra-dendukuri** [comment]
retest this please

**Comment by rajendra-dendukuri** [comment]
retest vsimage please

**Comment by olivier-singla** [comment]
retest this please

**Comment by olivier-singla** [comment]
retest vsimage please

**Comment by olivier-singla** [comment]
retest vsimage please

**Comment by olivier-singla** [comment]
Hi Qi, is there any anything pending preventing to merge this PR?

**Comment by qiluo-msft** [comment]
The current changes are huge because your code is based on old commit on master branch but not the latest master. Could you please rebase to master, or merge master to your branch?

Then you need to pass all the PR checks to be merged.

**Comment by lguohan** [comment]
@olivier-singla , next time, can you do rebase instead of merge, it will be much easier to see what has changed.

**Pull request merged**
