### PR TITLE
Update lldpd to latest stable version

### PR DESCRIPTION
**Pull request by pavel-shirshov**
**- What I did**
Updated lldpd to the latest stable version. This is for master only.

**- How I did it**
Changed lldpd version and removed patches, which are already part of the latest stable version.

**- How to verify it**
Build it and run on your dut.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
retest vsimage please

**Comment by pavel-shirshov** [comment]
@lguohan There is some incompatibility. I see it on my DUT.
I'll work on it as soon as I have time.

**Comment by lguohan** [comment]
retest vsimage please

**Comment by pavel-shirshov** [comment]
retest vsimage please

**Pull request merged**
