### PR TITLE
Change update_feature_state call to pass False as default if feature has no 'has_timer' field

### PR DESCRIPTION
**Pull request by noaOrMlnx**
**- Why I did it**
In order to make hostcfgd not to fail if feature has no 'has_timer' field
**- How I did it**
Change the update_feature_state call to pass False by default.
**- How to verify it**
Enable feature that has no 'has timer' field and make sure hostcfgd not failing. 
**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [x] 201911
- [x] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by noaOrMlnx** [comment]
retest vsimage please

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by tahmed-dev** [comment]
@noaOrMlnx, can you please check with latest master. There was an issue where has_timer was passed in as a string and so it was evaluating to `True` all the time. That issues was fixed via [PR:5241](https://github.com/Azure/sonic-buildimage/issues/5241)

**Comment by jleveque** [comment]
retest vsimage please

**Comment by noaOrMlnx** [comment]
@tahmed-dev I checked an image with the merged PR. 
The problem is caused when calling `update_feature_state` function, and trying to receive the has_timer field, even though there is no such field. 
`update_feature_state(feature_name, state, feature_table[feature_name]['has_timer'])` -> this call makes the feature initialization to fail if the feature doesn't have the field. 
This PRs purpose is to prevent the failure.

**Comment by noaOrMlnx** [comment]
retest vsimage please

**Comment by noaOrMlnx** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
retest bsimage please

**Comment by liat-grozovik** [comment]
retest baseimage please

**Comment by tahmed-dev** [comment]
> @tahmed-dev I checked an image with the merged PR.
> The problem is caused when calling `update_feature_state` function, and trying to receive the has_timer field, even though there is no such field.
> `update_feature_state(feature_name, state, feature_table[feature_name]['has_timer'])` -> this call makes the feature initialization to fail if the feature doesn't have the field.
> This PRs purpose is to prevent the failure.

@noaOrMlnx what is the exact scenario where this new field `has_timer` would go missing? The reason is I see all feature have their `has_timer` fields populated in [init_cfg.json.j:21](https://github.com/Azure/sonic-buildimage/blob/master/files/build_templates/init_cfg.json.j2#L21). So, it is not clear to me which scenario requires this change.

**Comment by noaOrMlnx** [comment]
> @noaOrMlnx what is the exact scenario where this new field has_timer would go missing? The reason is I see all feature have their has_timer fields populated in init_cfg.json.j:21. So, it is not clear to me which scenario requires this change.

@tahmed-dev This change is required for external features we have. Instead of changing the feature structure, this change will prevent the system to crush if the external feature doesn't have this field.

**Review by tahmed-dev — APPROVED** [review]

**Pull request merged**
