### PR TITLE
[submodule] Update sonic-utilities submodule

### PR DESCRIPTION
**Pull request by ayurkiv-nvda**
Signed-off-by: Andriy Yurkiv <ayurkiv@nvidia.com>

#### Why I did it
Update sonic-utilities submodule pointer to include the following::

- [yang] remove mistakenly added parameter for 'get_module_name'  [2193](https://github.com/Azure/sonic-utilities/pull/2193)
- [counters] skip showing counters that are not enabled [2199](https://github.com/Azure/sonic-utilities/pull/2199)
- [config][muxcable] Add support for displaying soc_ipv4 and cable_type in config/show muxcable commands [2189](https://github.com/Azure/sonic-utilities/pull/2189)
- Add check to not allow deleting PO if its member of vlan. [2141](https://github.com/Azure/sonic-utilities/pull/2141)
- [dump] Optimized dump state cli and modified tests to not use common data [2175](https://github.com/Azure/sonic-utilities/pull/2175)
- Fix sonic-installer and 'show version' command crash when database docker not running issue. [2183](https://github.com/Azure/sonic-utilities/pull/2183)
- [sonic-installer] use host docker startup arguments when running dockerd in chroot [2179](https://github.com/Azure/sonic-utilities/pull/2179)
- fix for non-coherent cmis modules [2163](https://github.com/Azure/sonic-utilities/pull/2163)
- [subinterface] Fix route add command to accept subinterface as dev [2180](https://github.com/Azure/sonic-utilities/pull/2180)
- [subinterface]Avoid removing the subinterface when last configured ip is removed [2181](https://github.com/Azure/sonic-utilities/pull/2181)
- [GCU] Handling type1 lists [2171](https://github.com/Azure/sonic-utilities/pull/2171)
- [yang] extend ConfigMgmt constructor to pass YANG options [2118](https://github.com/Azure/sonic-utilities/pull/2118)
- [dump] implement ACL modules [2153](https://github.com/Azure/sonic-utilities/pull/2153)
- show commands for SYSTEM READY [1851](https://github.com/Azure/sonic-utilities/pull/1851)
- [GCU] Handling non-compliant leaf-list with string values [2174](https://github.com/Azure/sonic-utilities/pull/2174)
- Add sonic-delayed.target to Application Extension .timer file generator [2176](https://github.com/Azure/sonic-utilities/pull/2176)
- [portconfig] Allow to configure interface mtu for physical ports only 
- Broadcast Unknown-multicast and Unknown-unicast Storm-control [928](https://github.com/Azure/sonic-utilities/pull/928)
- sonic-utils: initial support for link-training [2071](https://github.com/Azure/sonic-buildimage/pull/2071)

#### How I did it
update sonic-utilities submodule pointer

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@ayurkiv-nvda please handle conflicts.

**Comment by ayurkiv-nvda** [comment]
> @ayurkiv-nvda please handle conflicts.

@liat-grozovik failure and conflicts should be resolved after merging https://github.com/Azure/sonic-buildimage/pull/10986
Also I notice that sonic-utils submodule was partially updated https://github.com/Azure/sonic-buildimage/pull/11090

**Comment by ayurkiv-nvda** [comment]
@liat-grozovik conflict is fixed now, but still need to wait when https://github.com/Azure/sonic-buildimage/pull/10986 will be merged

**Comment by liat-grozovik** [comment]
there is already another PR on this submodule. closing this one

**Pull request closed without merging**
