### PR TITLE
[sonic-platform-common][sonic-platform-daemons][sonic-snmpagent][sonic-utilities] Update submodules

### PR DESCRIPTION
**Pull request by jleveque**
Update Python-based submodules to include updated dependencies in setup.py files.

* src/sonic-platform-common 14c6e53...7255d3a (2):
  > [setup.py] Update dependenices (#120)
  > [sfputilbase|sfputilhelper] fix value unpack error due to port_alias_asic_map in portconfig.py file (#116)

* src/sonic-platform-daemons e1842b2...1aaffcc (2):
  > Add 'wheel' package to 'setup_requires' list (#95)
  > [thermalctld] Fix issue: thermalctld should be auto restarted when being killed (#94)

* src/sonic-snmpagent 1a2b62a...5957460 (1):
  > [setup.py] Add 'wheel' to 'setup_requires' (#160)

* src/sonic-utilities 2244d7b...2f79ac1 (4):
  > [show] Add missing import to fix `show ip interfaces` (#1126)
  > Fixed config load_minigrpah not working for Multi-asic platfroms. (#1123)
  > Add CLI for configuring synchronous mode (#1094)
  > [setup.py] Update dependencies (#1125)

### CODE REVIEW

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by slogan621** [comment]
@jleveque can you add sonic-sairedis to this, so we can pick up https://github.com/Azure/sonic-sairedis/pull/661

**Comment by jleveque** [comment]
@slogan621: It's better if you update the sonic-sairedis submodule in this PR.

**Comment by slogan621** [comment]
> @slogan621: It's better if you update the sonic-sairedis submodule in your PR. Those changes are not related to these.

Yeah, after asking realized there was no relation.

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
