### PR TITLE
DellEMC SFP Refactor

### PR DESCRIPTION
**Pull request by aravindmani-1**
#### Why I did it 
Since SFP refactor has common API's, redundant platform API has to be removed.
#### How I did it
Removed redundant SFP API in DellEMC platforms.
#### How to verify it
Execute "sfpshow eeprom -d", verify syslogs pertaining to pmon, OIR tests etc..
[z9332f_ut.txt](https://github.com/Azure/sonic-buildimage/files/7459243/z9332f_ut.txt)

**Note:**
Please merge this PR only when sonic-platform-common submodule is updated with sonic_xcvr package in sonic-buildimage repo.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by prgeor** [comment]
@aravindmani-1 please test the case where a user plugs-out and plugs-in a different sfp type

1. QSFP+/QSFP28 -> QSFP-DD
2. QSFP-DD -> QSFP+/QSFP28

Ensure the APIs created by the xcvr_api_factory.py is correctly matches to the type of sfp module inserted.

**Comment by aravindmani-1** [comment]
> @aravindmani-1 please test the case where a user plugs-out and plugs-in a different sfp type
> 
> 1. QSFP+/QSFP28 -> QSFP-DD
> 2. QSFP-DD -> QSFP+/QSFP28
> 
> Ensure the APIs created by the xcvr_api_factory.py is correctly matches to the type of sfp module inserted.

yes. with the OIR testing, QSFP-DD to QSFP28/QSFP+ and vice versa has been tested, it is working fine.

**Comment by prgeor** [comment]
@aravindmani-1 device/dell/x86_64-dellemc_z9332f_d1508-r0/plugins/sfputil.py doesn't use sfpoptoebase

**Review by prgeor — APPROVED** [review]

**Comment by aravindmani-1** [comment]
@prgeor  @qiluo-msft  Could you please help to cherry pick this PR to 202111 branch?.

**Comment by judyjoseph** [comment]
@aravindmani-1 Please raise a separate PR for 202111 as there are conflicts

**Pull request merged**
