### PR TITLE
[sairedis]: force to disable parallel build for sairedis package

### PR DESCRIPTION
**Pull request by lguohan**
sairedis package cannot be built in parellel

### CODE REVIEW

**Comment by marian-pritsak** [comment]
@lguohan When do you have problems with a parallel build for sairedis? Is it related to some platform? Can you share log with failure?

**Comment by lguohan** [comment]
when doing parellel, it tries to build syncd, syncd-rpc target at the same time, then there is race condition. It fails at the different places each time. 

You can see following if you use dpkg-buildpackage -us -uc -b -j4

```
dh build  -N syncd-rpc -N syncd-rpc-dbg --with autotools-dev
dh build  -N syncd -N syncd-dbg --with autotools-dev
```

**Comment by marian-pritsak** [comment]
https://github.com/Azure/sonic-sairedis/blob/master/debian/rules#L25

Can you please try to change

```
binary: binary-syncd binary-syncd-rpc
```

to 

```
binary: binary-syncd-rpc

binary-syncd-rpc: binary-syncd
```

This will make builds in sairedis sequential (first binary-syncd, then binary-syncd-rpc) and we won't have such conflicts

**Comment by stcheng** [comment]
@marian-pritsak this seems to change the dependency relationship. but `binary-syncd` and `binary-syncd-rpc` are not dependent with each other.

**Comment by jleveque** [comment]
We could just make binary-syncd an order-only prerequisite of binary-syncd-rpc, which will ensure binary-syncd is always built first, but does not imply a dependency between the two:

```
binary: binary-syncd binary-syncd-rpc
binary-syncd-rpc: | binary-syncd
```

**Comment by lguohan** [comment]
solve in https://github.com/Azure/sonic-sairedis/pull/225

**Pull request closed without merging**
