### PR TITLE
[201911][Arista] Update device configuration for DCS-7060[PD]X-32

### PR DESCRIPTION
**Pull request by Staphylo**
#### Why I did it

The configuration for these 2 platforms was outdated.
Also one variant was not supported.

#### How I did it

Backported up to date configurations from master.

#### Description for the changelog

Update device configuration for DCS-7060[PD]X-32

### CODE REVIEW

**Comment by Staphylo** [comment]
This platform now unfortunately hits issue #5530
```
ERR syncd#syncd: [none] brcm_sai_create_tunnel_term_table_entry:1811 P2MP tunnel terminator not supported on this platform.
ERR syncd#syncd: :- processEvent: attr: SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_VR_ID: oid:0x3000000000024
ERR syncd#syncd: :- processEvent: attr: SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TYPE: SAI_TUNNEL_TERM_TABLE_ENTRY_TYPE_P2MP
ERR syncd#syncd: :- processEvent: attr: SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TUNNEL_TYPE: SAI_TUNNEL_TYPE_IPINIP
ERR syncd#syncd: :- processEvent: attr: SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_ACTION_TUNNEL_ID: oid:0x2a00000000054d
ERR syncd#syncd: :- processEvent: attr: SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_DST_IP: 10.0.0.4
ERR syncd#syncd: :- processEvent: failed to execute api: create, key: SAI_OBJECT_TYPE_TUNNEL_TERM_TABLE_ENTRY:oid:0x2b00000000054f, status: SAI_STATUS_NOT_SUPPORTED
ERR syncd#syncd: :- syncd_main: Runtime error: :- processEvent: failed to execute api: create, key: SAI_OBJECT_TYPE_TUNNEL_TERM_TABLE_ENTRY:oid:0x2b00000000054f, status: SAI_STATUS_NOT_SUPPORTED
NOTICE syncd#syncd: :- notify_OA_about_syncd_exception: sending switch_shutdown_request notification to OA
NOTICE syncd#syncd: :- notify_OA_about_syncd_exception: notification send successfull
NOTICE syncd#syncd: :- syncd_main: Removing the switch gSwitchId=0xb980112100000000
INFO syncd.sh[3390]: requested COLD shutdown
```

**Comment by Staphylo** [comment]
@jleveque any comment on this PR?

**Comment by jleveque** [comment]
> @jleveque any comment on this PR?

No comments from me. But since this is a direct PR for 201911, I will leave the review and merge to @abdosi.

**Comment by Staphylo** [comment]
This backport is not needed on 201911. Closing.

**Pull request closed without merging**
