### PR TITLE
[device/accton]: Add a new supported device, AS7312-54X

### PR DESCRIPTION
**Pull request by pollyhsu2git**
Switch Vendor: Edge-core

Switch SKU: AS7312-54X

ASIC Vendor: Broadcom

Swich ASIC: Tomahawk

Port Configuration: 48x25G + 6x100G

SONiC Image: SONiC-ONIE-Broadcom

Signed-off-by: polly_hsu@accton.com

**- What I did**
Add a new supported device, AS7312-54X

**- How I did it**
Add the new supported device, AS7312-54X based on the SONiC Porting Guide (https://github.com/Azure/SONiC/wiki/Porting-Guide)

**- How to verify it**
1. Target-verified the port mapping of 48x25G + 6x100G as expected
2. Target-verified the port link of 48x25G + 6x100G as expected
3. Target-verified the pre-emphasis setting as expected
4. Target-verified the LED macro init setting with (2)
5. Verified our config.bcm via config_checker passed except those lane specific pre-emphasis setting for our device.  We'll send our config.bcm to @shuche as reminded on the Porting Guilde.

**- Description for the changelog**

Add a new supported device, AS7312-54X

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by pollyhsu2git** [comment]
@jleveque, we original ported our device with the newlines at the end of all files, but we removed them after seeing your PRs removing extra trailing newlines at EOF, e.g. `Remove extra trailing newlines at EOF (#804)`.  Do we need the newline? or?

**Comment by jleveque** [comment]
In that PR, I was removing *extra* newlines (i.e., the files ended with "\n\n" and I changed them to end in "\n"). Your files should end with a single "\n"

**Comment by pollyhsu2git** [comment]
@jleveque, clarified!  We'll add newlines at the end of all files.

**Comment by jleveque** [comment]
Retest this please.

**Comment by pollyhsu2git** [comment]
@jleveque, we'll re-test it, and update you after done.

**Comment by jleveque** [comment]
@pollyhsu2git: I wasn't asking you to retest this. I noticed a couple of our automated check builds failed. By entering the phrase "retest this please" into a comment, GitHub triggers our Jenkins instance to re-run all of the check builds. I think the build failures were erroneous, so I wanted to try them again.

**Comment by jleveque** [comment]
Retest this please.

**Comment by lguohan** [comment]
retest this please

**Comment by jleveque** [comment]
Retest this please.

**Comment by pollyhsu2git** [comment]
@lguohan / @jleveque, we just found out that there is the branch, 201709 here.  Do we need to create a new PR for the 201709 branch to update / add the device / platform support ? Or?

**Comment by jleveque** [comment]
@pollyhsu2git: The 201709 branch is frozen to new features. We will only be merging bug fixes into the branch.

**Comment by pollyhsu2git** [comment]
@jleveque, Thanks! Clarified~

**Pull request merged**
