### PR TITLE
[bcm sai] upgrade to sai version 3.1.3.4-3

### PR DESCRIPTION
**Pull request by yxieca**
**- What I did**
Upgarding bcm SAI to 3.1.3.4-3:
- included bcm config files missed between 3.0 and 3.1.

This PR fixes issue #1416.

**- How to verify it**
Executed nightly test.

### CODE REVIEW

**Comment by pollyhsu2git** [comment]
Dear Sir(s), 
We've sent our config.bcm, `th2-as7816-64x100G.config.bcm` via the e-mail suject, `[Azure/SONiC] [config.bcm] ADD AS7816-64X (PR#1426)` on `Tue 2/27/2018 8:08 PM` to `sonicdev@microsoft.com` stated on the latest `Porting Guide`, but we haven't seen it by checking the url of #1451.

**Comment by yxieca** [comment]
@pollyhsu2git I'll check in this config file and update sai again.

**Comment by pollyhsu2git** [comment]
@yxieca, thanks for the update~

**Comment by yxieca** [comment]
@pollyhsu2git You are very welcome!

**Comment by pollyhsu2git** [comment]
@yxieca,
We've verified that th2-as7816-64x100G.config.bcm has been checked-in  on SONiC.HEAD.518-913a62c (SAI 3.1.3.4-4).
Thanks~

**Comment by yxieca** [comment]
@pollyhsu2git  Awesomeness! Thank you!

**Pull request merged**
