### PR TITLE
[Arista] Update drivers and boot script

### PR DESCRIPTION
**Pull request by Staphylo**
- Refactor of boot0 to ease with SKU development
- Refactor of platform detection in the library to make it more robust
- Add mdio support in scd-hwmon by implementing mii_bus interface
- Enhance reboot cause reporting by appending timestamp on unknown reboot causes
- Extend platform api support by implementing more methods
- Fix fan speed reading in crow-fan-driver
- Add support for DCS-7050CX3-32S platform
- Add Arista-7050CX3-32S-C32 hwsku with 32x100G + 2x10

### CODE REVIEW

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest vs please

**Comment by Staphylo** [comment]
retest vs please

**Comment by Staphylo** [comment]
Anything I should do to get this PR unblocked by vs/vsimage?

**Pull request merged**
