### PR TITLE
[barefoot][build] Fixed BFN platform build failure

### PR DESCRIPTION
**Pull request by akokhan**
Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>

**What I did**
Updated BFN debian packages

**Why I did it**
Migration from libswitchsai.so to libsai.so

**How I verified it**
Private build of BFN target

### CODE REVIEW

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
retest vs please

**Comment by vsenchyshyn** [comment]
retest vs please

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
@lguohan please merge this

**Pull request merged**
