### PR TITLE
Skip configuring buffer and QoS config on recirc ports

### PR DESCRIPTION
**Pull request by ysmanman**
Buffer or QoS config is not supported on recirc ports with today's DNX SAI.  Failing to config buffer or QoS on recirc ports results in swss to exit unexpectly. So skip buffer and QoS config on recirc ports for now.

#### Why I did it
DNX SAI does not support to configure buffer and QoS on recirc ports today. Failing to configure buffer or QoS on recirc port results in SWSS to exit unexpectedly.

### How I did it
We skipped configuring buffer and QoS on recirc ports for now. We can revert this change once SAI support is ready.

#### How to verify it
SWSS container exited unexpectedly when the above error encounters. 
SWSS container came up fine with the fix mentioned above.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Comment by rlhui** [comment]
Is this still needed?

**Comment by ysmanman** [comment]
> Is this still needed?

@rlhui We will confirm if this is still needed when testing PFC + PFCWD with SAI 5.2.

**Review by smaheshm — APPROVED** [review]

**Comment by rlhui** [comment]
> Can you explore adding a unit test for this.
> 
> e.g. https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/tests/test_j2files.py

@ysmanman  - was unit test added? Thanks.

**Comment by ysmanman** [comment]
> > Can you explore adding a unit test for this.
> > e.g. https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/tests/test_j2files.py
> 
> @ysmanman - was unit test added? Thanks.



> > Can you explore adding a unit test for this.
> > e.g. https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/tests/test_j2files.py
> 
> @ysmanman - was unit test added? Thanks.

@rlhui @smaheshm  Let me check if this is still issue in SAI 6.0.0.13. If it's, I will add the requested unit test.

**Comment by smaheshm** [comment]
> > > Can you explore adding a unit test for this.
> > > e.g. https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/tests/test_j2files.py
> > 
> > 
> > @ysmanman - was unit test added? Thanks.
> 
> > > Can you explore adding a unit test for this.
> > > e.g. https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/tests/test_j2files.py
> > 
> > 
> > @ysmanman - was unit test added? Thanks.
> 
> @rlhui @smaheshm Let me check if this is still issue in SAI 6.0.0.13. If it's, I will add the requested unit test.

@ysmanman we will still need this fix. 202106 release is using SAI 5.x

**Comment by ysmanman** [comment]
> > > > Can you explore adding a unit test for this.
> > > > e.g. https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/tests/test_j2files.py
> > > 
> > > 
> > > @ysmanman - was unit test added? Thanks.
> > 
> > 
> > > > Can you explore adding a unit test for this.
> > > > e.g. https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/tests/test_j2files.py
> > > 
> > > 
> > > @ysmanman - was unit test added? Thanks.
> > 
> > 
> > @rlhui @smaheshm Let me check if this is still issue in SAI 6.0.0.13. If it's, I will add the requested unit test.
> 
> @ysmanman we will still need this fix. 202106 release is using SAI 5.x

@smaheshm Thanks. I committed the test change just now.

**Comment by smaheshm** [comment]
@ysmanman Can you debug failure, looks like related to your changes.

**Comment by smaheshm** [comment]
Is there a difference in the sample output between py2 and py3. If so, why? Is it possible to have one sample output for both qos and buffer.

**Comment by ysmanman** [comment]
> Is there a difference in the sample output between py2 and py3. If so, why? Is it possible to have one sample output for both qos and buffer.

@smaheshm yes, buffer sample outputs of py2 & py3 are different. The differences are because ports are iterated with different ordering.  Regarding " Is it possible to have one sample output for both qos and buffer.",  qos and buffer outputs are generated by different template files, i.e., qos.json.j2 and buffer.json.j2. So it seems reasonable to have separate sample output. Also, existing tests use separate sample outputs too, e.g., qos-dell6100.json and buffers-dell6100.json.

**Comment by smaheshm** [comment]
@ysmanman Thanks for adding the test case and keeping up the quality.

**Pull request merged**
