### PR TITLE
[snmpagent] update submodule

### PR DESCRIPTION
**Pull request by stepanblyschak**
Includes below sonic-snmpagent commits
```
dfde06e 2021-01-13 | Revert "[rfc1213] Interface MIB add l3 vlan interfaces & aggregate rif counters (#169)" (#191) [Stepan Blyshchak]
45edd7e 2021-01-04 | [snmpagent] Fix hardcoded qsfp lane count by reading sensor status from DB (#184) [Junchao-Mellanox]
3b72a6f 2021-01-02 | Fix: handle empty LOC_CHASSIS_TABLE (#190) [Qi Luo]
4aad821 2020-12-29 | [sysName]: Implement sysName OID (#185) [SuvarnaMeenakshi]
8efb4bb 2020-12-29 | [rfc1213] fix counter value type (#189) [Stepan Blyshchak]
025483a 2020-12-23 | [RouteUpdater]: Fix multi_asic mock function implementation and multi_asic variable name (#186) [SuvarnaMeenakshi]
381ae47 2020-12-10 | [mibs] b'VLAN_TABLE:' -> 'VLAN_TABLE' (#181) [Stepan Blyshchak]
e54036c 2020-12-09 | [rfc1213] Interface MIB add l3 vlan interfaces & aggregate rif counters (#169) [Stepan Blyshchak]
fd1eae7 2020-11-24 | Set swsscommon logging level (#178) [Qi Luo]
706d504 2020-11-23 | Improve MockRedis _encode(): so it will work on all types of value (#179) [Qi Luo]
64c93a1 2020-11-16 | [RFC4292][Namespace]: Fix implementation of RouteUpdater for multi-asic platform (#176) [SuvarnaMeenakshi]
b8f19ee 2020-11-12 | [sonic-snmpagent] SONiC physical entity mib extension (#168) [Junchao-Mellanox]
6b94ec3 2020-11-05 | Replace swsssdk.SonicV2Connector with swsscommon.SonicV2Connector (SWIG wrapper of C++ implementation) in production code (#162) [Qi Luo]
```

**- Why I did it**

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by stepanblyschak** [comment]
Looking at the VS test failure

**Comment by stepanblyschak** [comment]
@qiluo-msft  Looks like swsscommon SonicV2Connector is missing pubsub interface: 
```
Dec 10 11:22:52.244611 r-tigon-11 ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.7/dist-packages/ax_interface/mib.py", line 43, in start#012    self.update_data()#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 560, in update_data#012    self.pubsub[i] = mibs.get_redis_pubsub(self.db_conn[i], self.db_conn[i].APPL_DB, pattern)#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/__init__.py", line 477, in get_redis_pubsub#012    pubsub = redis_client.pubsub()#012  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1076, in <lambda>#012    __getattr__ = lambda self, name: _swig_getattr(self, DBConnector, name)#012  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 80, in _swig_getattr#012    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))#012AttributeError: 'DBConnector' object has no attribute 'pubsub'
```

Could you please help to resolve this issue?

Also, could you please look at small fixup of https://github.com/Azure/sonic-snmpagent/pull/181?

**Comment by qiluo-msft** [comment]
Ack

**Comment by qiluo-msft** [comment]
It should be fixed in https://github.com/Azure/sonic-buildimage/pull/6197

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by stepanblyschak** [comment]
retest this please

**Comment by stepanblyschak** [comment]
retest this please

**Comment by qiluo-msft** [comment]
retest mellanox please

**Comment by qiluo-msft** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
@qiluo-msft, loosk like is failing, is there a regression in this submodule update?

snmp.test_snmp_pfc_counters.test_snmp_pfc_counters

**Comment by qiluo-msft** [comment]
We are working on it, there is at least one known issue.

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by qiluo-msft** [comment]
Retest mellanox please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
the test is still failing? can you folks check?

**Comment by lguohan** [comment]
@stepanblyschak , @qiluo-msft , where are we on this pr?

**Comment by lguohan** [comment]
retest vsimage please

**Comment by stepanblyschak** [comment]
@qiluo-msft The test fails because the test gets the interfaces from rfc1213 MIB and description from rfc2863 MIB. Since Vlan has been added to rfc1213 only it fails to get "description". I'm modifying test to work without required 'description'.

**Comment by stepanblyschak** [comment]
@qiluo-msft Could you please check https://github.com/Azure/sonic-mgmt/pull/2782?

**Comment by qiluo-msft** [comment]
@stepanblyschak, this is not a test code issue, but an code issue inside snmpagent. The interfaces in rfc1213 MIB and rfc2863 MIB should be consistent. For this case, you need to add the 'Description' (and also other fields?) to rfc2863, even an empty string is better than nothing.

**Review by lguohan — APPROVED** [review]

**Pull request merged**
