### PR TITLE
[yang] add yang options for Context object

### PR DESCRIPTION
**Pull request by ayurkiv-nvda**
#### Why I did it
Need to pass LY_CTX_DISABLE_SEARCHDIR_CWD to Context in order to disable automatically searching for schemas in current working directory (which is by default searched automatically)

#### How I did it
add additional attribute into YANG context

#### How to verify it
Create some invalid link on switch :
1) **ln -s /usr/abc xxx**
2) run **spm list**
--> There should not be these messages:
```
libyang[1]: Unable to get information about "xxx" file in "/tmp" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about "xxx" file in "/tmp" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about "xxx" file in "/tmp" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about "xxx" file in "/tmp" when searching for (sub)modules (No such file or directory)
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111

### CODE REVIEW

**Review by stepanblyschak — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@qiluo-msft could you please help to signoff?

**Comment by qiluo-msft** [comment]
Could you explain more of the section "How to verify it"
The path "/usr/abc" is not existing.
What is `spm`?

**Comment by ayurkiv-nvda** [comment]
> Could you explain more of the section "How to verify it" The path "/usr/abc" is not existing. What is `spm`? You mentioned "LY_CTX_DISABLE_SEARCHDIR_CWD" but it does not appear in code.

spm in sonic-package-manager
LY_CTX_DISABLE_SEARCHDIR_CWD is defined in related PR https://github.com/Azure/sonic-utilities/pull/2118

**Comment by liat-grozovik** [comment]
@qiluo-msft could you please review following comments above?

**Comment by liat-grozovik** [comment]
@praveen-li could you please take a look on this PR as well?

**Comment by praveen-li** [comment]
Sure, I will try to review it today or tomorrow evening.

Thanks,

Regards
Praveen
________________________________

**Review by qiluo-msft — COMMENTED** [review]
LGTM. Please wait for other reviewers.

**Comment by liat-grozovik** [comment]
@praveen-li kindly reminder to review this PR

**Review by qiluo-msft — APPROVED** [review]

**Review by lguohan — APPROVED** [review]

**Pull request merged**
