### PR TITLE
[sonic-swss] Update submodule

### PR DESCRIPTION
**Pull request by qiluo-msft**
Including below commits:
```
693a02c 2021-01-08 | [gearbox] Add support for "hwinfo" field (#1547) [Baptiste Covolato]
7e3b2c6 2021-01-09 | [Evpn Warmreboot] Added Dependancy check logic in VrfMgr (#1466) [nkelapur]
a960e2e 2021-01-09 | [Orchagent]: FdbOrch changes for EVPN VXLAN (#1275) [Pankaj Jain]
097cfda 2021-01-08 | [swss test] update setup guide for swss tests (#1582) [Ying Xie]
b42253a 2021-01-05 | Fix for armhf build (#1580) [Qi Luo]
d8c1465 2021-01-05 | [dvs] Update/disable DVS tests with new FRR 7.5 behavior (#1579) [Danny Allen]
f6c7422 2021-01-05 | ASIC internal temperature sensors support (#1517) [Santhosh Kumar T]
0aa9ef2 2021-01-01 | Simply by auto iterator type, because we will tune the return types of library functions (#1577) [Qi Luo]
773238b 2020-12-31 | [build]: Fix format string for size_t (#1576) [Qi Luo]
7ba4e43 2020-12-30 | [fgnhgorch] add warm reboot support for fgnhg (#1538) [weixchen1215]
4cf6617 2020-12-30 | [ci]: add build for arm64 and armhf (#1572) [lguohan]
6ebc0ed 2020-12-29 | [ci]: add azure-pipeline for amd64 (#1571) [lguohan]
e32b9d0 2020-12-29 | [FDBSYNCD] Added pytest for fdbsyncd (#1560) [KISHORE KUNAL]
a43f6be 2020-12-30 | [crm] Add support for snat, dnat and ipmc crm resources (#1511) [Prabhu Sreenivasan]
7fc3888 2020-12-29 | PY Test script for EVPN L3 VxLAN (#1330) [Tapash Das]
6eb36d9 2020-12-27 | vlanmgr changes related to EVPN VxLan warmboot (#1460) [anilkpan]
```

**- Why I did it**

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
can you check the build failure?

**Review by jleveque — CHANGES_REQUESTED** [review]
@qiluo-msft: Can you please update sonic-swss once commit further to include ASIC internal temperature sensors support (#1517)?

**Comment by lguohan** [comment]
@jleveque , that is nice to have, but should not be blocking, right?

**Comment by jleveque** [comment]
> @jleveque , that is nice to have, but should not be blocking, right?

Correct. But I just figured it could be included here. It can wait if you prefer.

**Comment by vaibhavhd** [comment]
@qiluo-msft, I want to include an important fix in sonic-sairedis submodule to prevent traffic loss after warm reboot: https://github.com/Azure/sonic-sairedis/pull/761
Do you suggest that I create a separate PR for this?

**Comment by qiluo-msft** [comment]
@vaibhavhd, please submit a separate PR

**Comment by qiluo-msft** [comment]
retest vsimage please

**Comment by lguohan** [comment]
@qiluo-msft , can you resolve conflict and rebuild?

**Comment by qiluo-msft** [comment]
Retest mellanox please

**Comment by qiluo-msft** [comment]
Retest broadcom please

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by daall** [comment]
retest vsimage please

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by daall** [comment]
retest vsimage please

**Comment by lguohan** [comment]
```
        if result["total"]["match"] != 0 or result["total"]["expected_missing_match"] != 0:
>           raise LogAnalyzerError(result)
E           LogAnalyzerError: {'match_messages': {'/tmp/syslog.2021-01-13-04:16:09': ['Jan 13 04:15:04.164722 vlab-01 ERR swss#orchagent: :- getResAvailableCounters: Failed to get switch attribute 60 , rv:-15\n']}, 'total': {'expected_match': 0, 'expected_missing_match': 0, 'match': 1}, 'match_files': {'/tmp/syslog.2021-01-13-04:16:09': {'expected_match': 0, 'match': 1}}, 'expect_messages': {'/tmp/syslog.2021-01-13-04:16:09': []}, 'unused_expected_regexp': []}
```

this seems caused by crm counter.

**Comment by lguohan** [comment]
retest vsimage please

**Comment by daall** [comment]
retest vsimage please

**Comment by qiluo-msft** [comment]
retest vsimage please

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
kvmtest passed.

**Pull request merged**
