### PR TITLE
updating sonic-utilities submodule

### PR DESCRIPTION
**Pull request by Praveen-Brcm**
Updating the sonic-utilies submodule to pick PR#1338 changes to master.

### CODE REVIEW

**Comment by arlakshm** [comment]
Please update the PR with all the commits this submodule update includes

**Comment by haslersn** [comment]
@Praveen-Brcm I think you didn't pull the master of sonic-utilities before adding (`git add`) the submodule. This PR has submodule commit d19829cdf01500213101cc0d2f78587af5f86cf3 while master has 0efd297fc4249c764997d9f128b04e12bc0eda65.

**Comment by haslersn** [comment]
List of commits (newest first):

Azure/sonic-utilities@0efd297fc4249c764997d9f128b04e12bc0eda65 **(origin/master, origin/HEAD)**  mclag enhancements as per HLD at Azure/SONIC#596 (#1138)
Azure/sonic-utilities@e98bbb642ae724802e20c1be415ec4f9a3ed7b3a Reworked IP validation in "config interface ip add/remove" command (#1709)
Azure/sonic-utilities@866d1d7b2f4ea4e36b19c5f51f05b09eb1398672 [minigraph][port_config] Consume port_config.json while reloading minigraph (#1705)
Azure/sonic-utilities@9ae6f6bc191ddbb6131f95a52e0489671fa1f5de [debug dump util] Match Infrastructure (#1666)
Azure/sonic-utilities@8fe7e260109acafac1035502b5f354a7591e349c Coverage uses top level directory as source (#1711)
Azure/sonic-utilities@3f0b69033c4b8605042ce2d0b41d958d3ff066db [MPLS][CLI] added config/show CLI for MPLS interface, MPLS CRM threshold config, updated CLI reference manual
Azure/sonic-utilities@e8b6c5cc6a4cbe991d0ac08ea3a608df7da2511c [ci] Fix python coverage color bar (#1692)
Azure/sonic-utilities@888701b67fd4f1cc5b9da534a360048f93f263f4 [Mellanox] Remove mstdump from  Mellanoxs collect dump script (#1706)
Azure/sonic-utilities@4818360d7d9f5460169bce9a9f87f44311647a64 [sonic-package-manager] support warm/fast reboot for extension packages (#1554)
Azure/sonic-utilities@793b84722a00efc10f5271634985b1936cf8d1d5 [show priority-group drop counters] Remove backup with cached PG drop counters after 'config reload' (#1679)
Azure/sonic-utilities@24fe1acb0b9111ac79ef8296c23ca14576256a6a [show][config] support for interface alias for muxcable commands (#1699)
Azure/sonic-utilities@186d851380f2807222daceecb54048ce8634fb89 Pcieutil to load the platform api first instead of using common api (#1672)
Azure/sonic-utilities@7a82c0691c9f95cb6faabdce14256a8042b00d7c [Mellanox] Update mellanox dump generation to include SDK dumps (#1640)
Azure/sonic-utilities@38f8c0681c038bc0c948ec73cf91f2d0397095df [sfputil] Expose error status fetched from STATE_DB or platform API to CLI (#1658)
Azure/sonic-utilities@c5d00ae4b8430aac81cf078ba79224096815686c [pfcwd] Fix the return code in invalid case (#1691)
Azure/sonic-utilities@57dc4032e52d204a10cfc8d3eca1376a285df086 [ci]: Fix config prompt question issue (#1693)
Azure/sonic-utilities@5708497358a2be22be940da550191ca79c698e61 [show] fix `show version` (#1686)
Azure/sonic-utilities@9041ba038ba2a6c6df6f3e0f6c03c8eb0219a654 [config] Adding sanity checks for config reload (#1664)
Azure/sonic-utilities@2cdadb52b7a4d6296726af5b5fe4e29e0b5e6bc8 [config]: Create portchannel with LACP key (#1473)
Azure/sonic-utilities@6f74ba53d7768312a015a1d04c677349fbccab9e [vnet_route_check] Fix logic for getting VNET routes from ASIC DB (#1653)
Azure/sonic-utilities@54fee0f7c81378a1ff956993fb3f058b9120bb83 Add range check on portchannel min-links (#1630)

**Review by qiluo-msft — APPROVED** [review]

**Comment by haslersn** [comment]
@qiluo-msft You just merged this into master even though it references the wrong commit.

**Pull request merged**
