### PR TITLE
[sonic-cfggen]: Improve T2 chassis frontend parsing

### PR DESCRIPTION
**Pull request by baiwei0427**
**- What I did**
Update parse_spine_chassis_fe in minigraph.py 

**- How to verify it**
SONiC VM

Signed-off-by: Wei Bai baiwei0427@gmail.com

### CODE REVIEW

**Comment by baiwei0427** [comment]
@prsunny  Can you review this PR?

**Comment by baiwei0427** [comment]
retest this please

**Comment by lguohan** [comment]
retest mellanox please

**Comment by lguohan** [comment]
retest vs please

**Comment by prsunny** [comment]
Thanks for addressing Wei

**Pull request merged**
