### PR TITLE
[DPB] [Mellanox] added capability files for SN3700 platform

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
**- Why I did it**

`platform.json` and `hwsku.json` files are required for a feature called Dynamic Port Breakout

**- How I did it**

Created capability files according to platform specification `SN3700`

**- How to verify it**

Full qualification requires bugs fixes reported under sonic-buildimage

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Review by liat-grozovik — COMMENTED** [review]
please check if we can allow all other speeds when all lanes are used and no split.
like 1x200G[100G, 40G] can we add more options?

**Review by liat-grozovik — COMMENTED** [review]
missing 50g in the default, any reason why not?

**Comment by vadymhlushko-mlnx** [comment]
> please check if we can allow all other speeds when all lanes are used and no split.
> like 1x200G[100G, 40G] can we add more options?

If I will try split mode like this - `1x200G[100G,50G,40G,25G,10G]`, I will get the next error:

```
libyang[0]: Value "1x200G[100G,50G,40G,25G,10G]" does not satisfy the constraint "1x100G\[40G\]|2x50G|4x25G\[10G\]|2x25G\(2\)\+1x50G\(2\)|1x50G\(2\)\+2x25G\(2\)|1x400G|2x200G|4x100G|8x50G" (range, length, or pattern). (path: /sonic-breakout_cfg:sonic-breakout_cfg/BREAKOUT_CFG/BREAKOUT_CFG_LIST[port='Ethernet252']/brkout_mode)
Data Loading Failed
Failed to break out Port. Error: Failed to load the config. Error: ConfigMgmtDPB Class creation failed
```

But `1x200G[100G,50G,40G,25G,10G]` seems to be a valid mode, I will ask the owners about it.

**Comment by vadymhlushko-mlnx** [comment]
retest vsimage please

**Comment by vadymhlushko-mlnx** [comment]
Please don't merge this PR until [[DPB][MLNX][YANG-models] extended regex pattern according to MLNX systems speeds requirements](https://github.com/Azure/sonic-buildimage/pull/6279) PR will be merged

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by vadymhlushko-mlnx** [comment]
retest vsimage please

**Comment by vadymhlushko-mlnx** [comment]
retest vsimage please

**Pull request merged**
