### PR TITLE
[Centec][arm64] support new board E530-48s4x and E530-24x2q

### PR DESCRIPTION
**Pull request by guxianghong**
1. support new board E530-48s4x E530-24x2q
    2. optimize platform driver for Centec TsingMa board

#### Why I did it
1. Support new board E530-48s4x and E530-24x2q
2. Platform functions (fan, psu, sfp, etc)  improvement
3. Upgrade sai to v1.7

#### How I did it
Modify related code in platform and device directory.

#### How to verify it
Build centec arm64 sonic image,  verify platform functions (fan, psu, sfp, etc) on E530 series board.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Comment by lguohan** [comment]
can you fix lgtm first?

**Comment by guxianghong** [comment]
retest kvmtest-t1-lag please

**Comment by guxianghong** [comment]
retest kvmtest please

**Comment by guxianghong** [comment]
retest this please

**Comment by guxianghong** [comment]
retest this please

**Comment by guxianghong** [comment]
retest kvmtest-t1-lag, please

**Comment by guxianghong** [comment]
retest this, please

**Comment by guxianghong** [comment]
retest please

**Comment by guxianghong** [comment]
retest this please

**Comment by guxianghong** [comment]
> This pull request **introduces 20 alerts** when merging [575758c](https://github.com/Azure/sonic-buildimage/commit/575758cdfcfb0384425e0c3196e4019db9275165) into [ecaf97d](https://github.com/Azure/sonic-buildimage/commit/ecaf97d8a3591daaf8f0c8c187785678a2939350) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-buildimage/rev/pr-86c7fb20c9c72bb076966f7acd13f683a252f5a6)
> 
> **new alerts:**
> 
> * 20 for Wrong number of arguments in a class instantiation

These 20 alerts seems false positive,  centec platform python class do not call other chip vendor's.  Please help to review it,  @lguohan , Thanks.

**Comment by guxianghong** [comment]
retest this please

**Comment by guxianghong** [comment]
> This pull request **introduces 20 alerts** when merging [575758c](https://github.com/Azure/sonic-buildimage/commit/575758cdfcfb0384425e0c3196e4019db9275165) into [6d83a42](https://github.com/Azure/sonic-buildimage/commit/6d83a424b50f41a6b9f4d60fb326bb697552039e) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-buildimage/rev/pr-a9a66d570950a9f396711672fe62626c5dc84602)
> 
> **new alerts:**
> 
> * 20 for Wrong number of arguments in a class instantiation

It looks like all these new alerts are false positives, centec platform utilities will not call other vendor's platfom utility. Please help to review this PR, Thanks.

**Comment by guxianghong** [comment]
It looks like all these new alerts are false positives, centec platform utilities will not call other vendor's platfom utility. @lguohan please help to review this PR, thanks.

**Review by lguohan — APPROVED** [review]

**Comment by guxianghong** [comment]
Please help to merge this PR, @lguohan , thanks.

**Comment by guxianghong** [comment]
Please help to review&merge this PR, @lguohan @jleveque, thanks very much.

**Pull request merged**
