### PR TITLE
Fix reboot-cause for 201811 arista

### PR DESCRIPTION
**Pull request by zzhiyuan**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
change to large, are we only doing bug fixes on this branch?

**Comment by zzhiyuan** [comment]
Currently testing...

**Comment by zzhiyuan** [comment]
retest mellanox please

**Comment by yxieca** [comment]
retest this please

**Pull request merged**
