### PR TITLE
[docker-ptf] Upgrade to buster

### PR DESCRIPTION
**Pull request by msosyak**
#### Why I did it
To make docker ptf buster based

#### How I did it
Update docker file

#### How to verify it
```
make init
make configure PLATFORM=vs
make target/docker-ptf.gz
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [x] 202106

### CODE REVIEW

**Comment by msosyak** [comment]
Yes. I have run sanity regression with few tests from t1 and t0 and all passed as expected.

My intention is to align all docker bases to avoid building a stretch slave image.

**Comment by msosyak** [comment]
@yxieca Do you see any issues with that update or could we merge this PR?

**Comment by yxieca** [comment]
@msosyak , do you have the capability of running a full nightly test with buster ptf and compare the results with stretch ptf? If the test results are the same, then we can proceed with this upgrade.

**Comment by msosyak** [comment]
Could we marge this or something else is needed?

**Comment by msosyak** [comment]
@yxieca Please update

**Review by yxieca — APPROVED** [review]

**Pull request merged**
