### PR TITLE
Remove unnecessary sudo authority in build Makefile

### PR DESCRIPTION
**Pull request by xumia**
**- Why I did it**
In some build machine, it may be not able to run as root during the build, only has root authority in docker containers.

**- How I did it**
Remove the sudo in Makefile

**- How to verify it**
cd src/sonic-build-hooks
make all

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by xumia** [comment]
retest vsimage

**Comment by xumia** [comment]
retest vsimage please

**Comment by xumia** [comment]
retest mellanox  please

**Comment by xumia** [comment]
retest mellanox please

**Comment by xumia** [comment]
retest vsimage please

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
