### PR TITLE
Flashrom refactoring

### PR DESCRIPTION
**Pull request by santhosh-kt**
**- Why I did it**
To build flashrom properly with dependency tracking.

**- How I did it**
Moved flashrom code from platform/broadcom/sonic-platform-modules-dell/tools directory to src/flashrom directory.
At the end, flashrom_0.9.7_amd64.deb package is build which will be installed in the devices.

**- How to verify it**
Attached logs as reference.
[Logs.txt](https://github.com/Azure/sonic-buildimage/files/5700765/Logs.txt)

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

On branch flashrom-refactor
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   ../../build_debian.sh
        modified:   ../../files/build_templates/sonic_debian_extension.j2
        modified:   ../../platform/broadcom/platform-modules-dell.mk
        modified:   ../../platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
        deleted:    ../../platform/broadcom/sonic-platform-modules-dell/tools/flashrom.sh
        new file:   ../../rules/flashrom.dep
        new file:   ../../rules/flashrom.mk
        modified:   ../../slave.mk
        new file:   Makefile
        renamed:    ../../platform/broadcom/sonic-platform-modules-dell/tools/0002-Flashrom-support-for-Intel-Rangeley-and-Denverton-CP.patch -> patch/0002-Flashrom-support-for-Intel-Rangeley-and-Denverton-CP.patch
        new file:   patch/0003-Debian-package-base.patch
        new file:   patch/0004-Flashrom-remove-tmpl.patch
        new file:   patch/series

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by santhosh-kt** [comment]
retest this please

**Comment by santhosh-kt** [comment]
retest vs please

**Comment by jleveque** [comment]
Azure Pipelines check builds stuck. Closing and reopening PR in hopes of fixing it.

**Comment by santhosh-kt** [comment]
@jleveque : If this is a problem, shall I close this PR and raise a new PR?

**Comment by jleveque** [comment]
> @jleveque : If this is a problem, shall I close this PR and raise a new PR?

You could first try a rebase and a force-push to your branch. That might re-trigger the stuck builds. If that doesn't work, then you may need to close this PR and raise a new one.

**Comment by santhosh-kt** [comment]
@jleveque : Had some issue with rebase.
Will raise a new PR to avoid all these conflicts.

**Pull request closed without merging**
