### PR TITLE
[Mellanox] optimize platform API import time

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

"import sonic_platform" takes about 600ms ~ 1000ms, it is kind of slow. After this optimization, the time is about 100ms. The benefit is that those CLIs which does not need the slow import sentence would be faster than before.

#### How I did it

Find slow import and call them when need.

#### How to verify it

Measure the import time.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @prgeor , could you please review and sign-off?

**Comment by Junchao-Mellanox** [comment]
Hi @prgeor, kindly reminder

**Pull request merged**
