### PR TITLE
[Nvidia][SDK] Build SDK with PRM sniffer support

### PR DESCRIPTION
**Pull request by stepanblyschak**
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>

#### Why I did it

To have an ability to use PRM sniffer.

#### How I did it

Enabled the option in configure flags.

#### How to verify it

Built and ran on switch. Enabled the feature in runtime and checked the sniffer recording.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [x] 201911
- [x] 202006
- [x] 202012
- [x] 202106
- [x] 202111

### CODE REVIEW

**Comment by lguohan** [comment]
what is PRM sniffer? can you describe a little bit more?

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
