### PR TITLE
[SNMP] management VRF SNMP support

### PR DESCRIPTION
**Pull request by vharish02**
This commit adds SNMP support for Management VRF using l3mdev.
The patch included provides VRF support, there is no single
"listendevice" configuration, rather multiple agentaddress
config options can each have their own "interface" to bind to
using "ip%interface". The snmpd.conf file is accordingly
generated using the snmp.yml file and redis database info.

Adding below the comments of SNMP patch 1376
--------------------------------------------
Since the Linux kernel added support for Virtual Routing
and Forwarding (VRF) in version 4.3
(Note: these won't compile on non-linux platforms)

https://www.kernel.org/doc/Documentation/networking/vrf.txt

Linux users could not use snmpd in its current form to
bind specific listening IP addresses to specific VRF
devices. A simplified description of a VRF inteface
is an interface that is a master (a container of sorts)
that collects a set of physicalinterfaces to form a
routing table.

This set of two patches (one for V5-7-patches and one
for V5-8-patches branches) is almost identical to patch
single "listendevice" configuration. Rather, multiple
agentAddress config options can each have their own
"interface" to bind to using the <ip>%<interface>
syntax.</interface></ip>
-------------------------------------------

Signed-off-by: Harish Venkatraman <harish_venkatraman@dell.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Retest this please

**Comment by pavel-shirshov** [comment]
Hi,

Can you please resolve the conflict?

Thanks

**Comment by kannankvs** [comment]
> I reviewed changes, but I can't understand all changes in the snmpd patch
SNMP does not have the support to differentiate the management VRF. When SNMP tries to send the trap to the SNMP manager, it uses "setsocketopt" to set the properties for the socket.
netsnmp_udp_sockopt_set function has been enhanced to do "SO_BINDTODEVICE" to bind to the management interface. This "iface" is being passed as parameter based on the user configuration, where users can configure the snmp_trap_manager_ip_address along with the VRF through which the IP is reachable. For example, if trap_mgr_ip1 is configured through management VRF, this SO_BINDTODEVICE enhancement will take care of binding to the management VRF interface. Without this enhancement, SNMP does not have a facility to bind sockets to the VRF.  
If you need more information, we shall schedule for a conference call to go through the changes and the reasons.

**Comment by pavel-shirshov** [comment]
@kannankvs Thanks for the explanations
Can you resolve the conflict in this PR please?

**Comment by kannankvs** [comment]
@pavel-shirshov : Thank you. I will resolve the conflict and checkin.

**Comment by vharish02** [comment]
> @kannankvs Thanks for the explanations
> Can you resolve the conflict in this PR please?

@pavel-shirshov I have resolved the conflicts

**Comment by pavel-shirshov** [comment]
retest vs please

**Comment by pavel-shirshov** [comment]
@vharish02 The vs test is failing for this PR. We tested two times.

**Comment by vharish02** [comment]
> @vharish02 The vs test is failing for this PR. We tested two times.

@pavel-shirshov I don't think the failures are related to the changes of the PR. Looks like some environment issue.

**Comment by lguohan** [comment]
are snmpd vrf related changes from upstream?

can we use a simpler approach to just run snmpd in cgexec so that snmpd is bind to the mgmt vrf? 

also this pr should be splitted into two PR. one for enable snmp trap feature, another for mgmt vrf.

**Comment by vharish02** [comment]
> are snmpd vrf related changes from upstream?
> snmp VRF Patch was picked from the following link where snmp patches are upstreamed
 https://sourceforge.net/p/net-snmp/patches/1376/

> can we use a simpler approach to just run snmpd in cgexec so that snmpd is bind to the mgmt vrf?
Will look into this approach and get back to you. You want snmpd to be started using cgexec on mgmt-vrf and stop snmpd in default VRF.
> 
> also this pr should be splitted into two PR. one for enable snmp trap feature, another for mgmt vrf.
Will do

**Comment by vharish02** [comment]
> > can we use a simpler approach to just run snmpd in cgexec so that snmpd is bind to the mgmt vrf?

@lguohan When snmpd is run using cgexec snmpwalk will work through the mgmt port (eth0), snmpwalk through FPP will not work. Is this solution acceptable? where snmp via FPP is not feasible.

Note: We did a quick prototype to run snmpd using cgexec (without docker) and confirmed that snmpwalk works only through mgmt vrf (eth0) and not through Front panel ports (FPP). 

But when snmp patch is used snmpwalk works with both mgmt vrf (eth0) and FPP interfaces.

**Comment by vharish02** [comment]
> > > can we use a simpler approach to just run snmpd in cgexec so that snmpd is bind to the mgmt vrf?
> 
> @lguohan When snmpd is run using cgexec snmpwalk will work through the mgmt port (eth0), snmpwalk through FPP will not work. Is this solution acceptable? where snmp via FPP is not feasible.
> 
> Note: We did a quick prototype to run snmpd using cgexec (without docker) and confirmed that snmpwalk works only through mgmt vrf (eth0) and not through Front panel ports (FPP).
> 
> But when snmp patch is used snmpwalk works with both mgmt vrf (eth0) and FPP interfaces.

Update on cgexec:

Without using snmp patch and using cgexec for snmp to bind to mgmt-vrf has complications.
 1. We can make SNMP to work via mgmt interface only (not through Front panel ports) but BGP FRR will have issue. BGP runs an SNMP subagent and it tries to connect to master agent using localhost.(127.0.0.1) When master agent SNMP docker is run using cgexec, the FRR BGP subagent will not be able to connect to the master agent. Loopback interface cannot be moved to management VRF. Loopback interface is very much required in default VRF for all docker and internal communication.

2. Tried to create a dedicated loopback interface "lo1" for management VRF with IP 100.100.100,100/32, the subagent related to ax_implementation(ifMIB and other MIB's) can be made to work using this lo1, but still BGP docker won't be able to reach to this lo1 without having inter-vrf routes.

With the patch as per the PR SNMP for all MIB's including BGP MIBs works through both management VRF (eth0) and default VRF (FPP). We will have additional configuration in snmpd.conf 
ex. agentaddress ipaddress%vrf where we can have both mgmt vrf and default vrf entries.
With this configuration master agent does setsockeropt with SO_BINDTODEVICE and binds it to the VRF and hence replies back to SNMP requests coming from external SNMP managers.

**Comment by lguohan** [comment]
understand the concern, fine with the original approach to patch snmpd to support vrf. Can you add original commit id in you snmpd patch and also resolve the conflict?

**Comment by kannankvs** [comment]
@lguohan : resolved the conflict. Regarding the "original snmpd commit id", I am not clear on how to get it. The patch was generated long time back and we are unable to track and find the commit ID related to it. Can this be ignored?

**Comment by lguohan** [comment]
@kannankvs , all upstream patch needs to have upstream commit id for tracking purpose so that when we later upgrade the code we will know if such patch can be remove or not. I wish i could find this issue earlier.

**Comment by lguohan** [comment]
can you also resolve conflict?

**Comment by kannankvs** [comment]
@lguohan : This patch is from https://sourceforge.net/p/net-snmp/patches/1376/. We are exploring on  how to get the upstream commit ID for this patch. After finding it, we shall add it in the "Subject" inside the patch file 0008-Linux-VRF-5.7.3-Support.patch. We shall resolve the conflict then.

**Comment by lguohan** [comment]
there is still conflict.

**Comment by lguohan** [comment]
also, snmp has git repo, you can use git blame to find the commit id.

**Comment by kannankvs** [comment]
@lguohan : I was working in parallel to resolve the conflict. Its resolved now. 
Regarding the commit ID, I am unable to find it in sourceforge.net as well as in the net-snmp github (https://github.com/net-snmp/net-snmp). I searched using "git blame" & "git log" in the net-snmp github in both master and V5-8, V5-7 branches as well, but no success. We will explore more to find the commit ID. Now that we have given the reference in the patch file, if that is enough, you can merge this PR.

**Pull request merged**
