### PR TITLE
[DELL] S6100, Z9100 Last Reboot Reason Watchdog, Thermal Support

### PR DESCRIPTION
**Pull request by sridhar-ravindran**
**- What I did**
Added support for Watchdog & Thermal events in Last Reboot Reason "show reboot-cause" command
**- How I did it**
Changes to be committed:
(use "git reset HEAD ..." to unstage)

    modified:   files/image_config/platform/rc.local
    modified:   platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6100.install
    modified:   platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-z9100.install
    new file:   platform/broadcom/sonic-platform-modules-dell/s6100/scripts/platform_plugin
    modified:   platform/broadcom/sonic-platform-modules-dell/s6100/scripts/platform_reboot_override
    modified:   platform/broadcom/sonic-platform-modules-dell/s6100/scripts/s6100_platform.sh
    new file:   platform/broadcom/sonic-platform-modules-dell/s6100/scripts/track_reboot_reason.sh
    modified:   platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
    new file:   platform/broadcom/sonic-platform-modules-dell/z9100/scripts/platform_plugin
    modified:   platform/broadcom/sonic-platform-modules-dell/z9100/scripts/platform_reboot_override
    new file:   platform/broadcom/sonic-platform-modules-dell/z9100/scripts/track_reboot_reason.sh
    modified:   platform/broadcom/sonic-platform-modules-dell/z9100/scripts/z9100_platform.sh
    modified:   platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/chassis.py
Added support to track watchdog events and thermal overload of ASIC & CPU
**- How to verify it**
Added the Unit Test Results for all reboot reasons
**- Description for the changelog**

[DELL] S6100, Z9100 Last Reboot Reason Watchdog, Thermal Support

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by sridhar-ravindran** [comment]
[LRR_UnitTesting_S6100.txt](https://github.com/Azure/sonic-buildimage/files/3627943/LRR_UnitTesting_S6100.txt)
[LRR_UnitTesting_Z9100.txt](https://github.com/Azure/sonic-buildimage/files/3627944/LRR_UnitTesting_Z9100.txt)

**Comment by sujinmkang** [comment]
@sridhar-ravindran I checked reboot-cause with the build here but software reboot reason seems not working even I tried several time. Can you please double check all other reboot reason is working along with watchdog and hw reboot reason?

**Comment by sujinmkang** [comment]
'''
Oct  4 22:45:18.611062 str-z9100-acs-2 INFO systemd[1]: Starting LSB: Execute the kexec -e command to reboot system...
Oct  4 22:45:18.650619 str-z9100-acs-2 INFO systemd[1]: Started LSB: Execute the kexec -e command to reboot system.
Oct  4 22:45:21.305600 str-z9100-acs-2 INFO process-reboot-cause[927]: Traceback (most recent call last):
Oct  4 22:45:21.305835 str-z9100-acs-2 INFO process-reboot-cause[927]:   File "/usr/bin/process-reboot-cause", line 136, in <module>
Oct  4 22:45:21.306062 str-z9100-acs-2 INFO process-reboot-cause[927]:     main()
Oct  4 22:45:21.306279 str-z9100-acs-2 INFO process-reboot-cause[927]:   File "/usr/bin/process-reboot-cause", line 77, in main
Oct  4 22:45:21.306494 str-z9100-acs-2 INFO process-reboot-cause[927]:     platform = sonic_platform.platform.Platform()
Oct  4 22:45:21.306714 str-z9100-acs-2 INFO process-reboot-cause[927]:   File "/usr/local/lib/python2.7/dist-packages/sonic_platform/platform.py", line 25, in __init__
Oct  4 22:45:21.306929 str-z9100-acs-2 INFO process-reboot-cause[927]:     self._chassis = Chassis()
Oct  4 22:45:21.307143 str-z9100-acs-2 INFO process-reboot-cause[927]:   File "/usr/local/lib/python2.7/dist-packages/sonic_platform/chassis.py", line 119, in __init__
Oct  4 22:45:21.307371 str-z9100-acs-2 INFO process-reboot-cause[927]:     self._component_name_list.append(COMPONENT_BIOS)
Oct  4 22:45:21.307585 str-z9100-acs-2 INFO process-reboot-cause[927]: AttributeError: 'Chassis' object has no attribute '_component_name_list'
Oct  4 22:45:22.064487 str-z9100-acs-2 INFO process-reboot-cause: Starting up...
Oct  4 22:45:22.064786 str-z9100-acs-2 NOTICE systemd[1]: process-reboot-cause.service: Main process exited, code=exited, status=1/FAILURE
Oct  4 22:45:22.065380 str-z9100-acs-2 NOTICE systemd[1]: process-reboot-cause.service: Unit entered failed state.
Oct  4 22:45:22.065997 str-z9100-acs-2 WARNING systemd[1]: process-reboot-cause.service: Failed with result 'exit-code'.
'''

**Comment by sujinmkang** [comment]
@sridhar-ravindran can we have this PR updated based on  PR3698 ?

**Comment by sridhar-ravindran** [comment]
Hi,
We have raised https://github.com/Azure/sonic-buildimage/pull/3767 with updated code changes to support this feature in master. Request you to review the same.

**Pull request closed without merging**
