### PR TITLE
Added Netberg Aurora 715 support

### PR DESCRIPTION
**Pull request by andrewsapronov**
#### Why I did it

Suport Innovium based platform Netberg Aurora 715
ASIC: Innovium Teralynx IVM 55300
Pors: 32x 100G

#### How I did it

Added specification x86_64-netberg_aurora_715-r0 device/netberg directory
Added platform/innovium/sonic-platform-modules-netberg contains kernel modules, scripts and sonic_platform package. 
Modified the platform/innovium/one-image.mk and platform/innovium/rule.mk to include Aurora 715 related ID and files. 

#### How to verify it
Build sonic
Install the image on the device and verify the related components are installed and shown correctly. 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog

Initial support for Netberg Aurora 715

### CODE REVIEW

**Comment by andrewsapronov** [comment]
@lguohan could you please review this PR. Did we miss something?

**Comment by andrewsapronov** [comment]
@sujinmkang @prgeor - Can you review and approve the changes ?

**Comment by sujinmkang** [comment]
@andrewsapronov Can you please share the show platform  commands output?

**Comment by sujinmkang** [comment]
@andrewsapronov LGTM but I want you to check this two questions below.
 
1. PSU2_FAN1  is this your device issue or could it be an api issue?
```
 root@sonic:/home/admin# show platform fan
  Drawer    LED        FAN    Speed    Direction    Presence    Status          Timestamp
--------  -----  ---------  -------  -----------  ----------  --------  -----------------
     N/A    N/A  PSU1_FAN1      77%          N/A     Present        OK  20210612 02:53:58
     N/A    N/A  PSU2_FAN1       0%          N/A     Present    Not OK  20210612 02:53:58
```
2. Health and Temperature is not reported with this cli. Can you check why?
```
admin@sonic:~$ show platform ssdhealth 
Device Model : KINGSTON RBUSNS4180S3128GJ
Health       : N/A
Temperature  : N/A
```

**Comment by andrewsapronov** [comment]
> LGTM 
@sujinmkang  LGTM's errors are false positives with other platforms ( like in https://github.com/Azure/sonic-buildimage/pull/8717 - the wrong name/number of the argument alerts are due to different platform definitions)

>     1. PSU2_FAN1  is this your device issue or could it be an api issue?
It was just one cable plugged. Sorry for this. Please check the attached file with plug/unplug the power. 

>     2. Health and Temperature is not reported with this cli. Can you check why?
As I understand, according to sonic_ssd there are not so many ssd vendors supported:

```
        self.vendor_ssd_utility = {
            "Generic"  : { "utility" : SMARTCTL, "parser" : self.parse_generic_ssd_info },
            "InnoDisk" : { "utility" : INNODISK, "parser" : self.parse_innodisk_info },
            "M.2"      : { "utility" : INNODISK, "parser" : self.parse_innodisk_info },
            "StorFly"  : { "utility" : VIRTIUM,  "parser" : self.parse_virtium_info },
            "Virtium"  : { "utility" : VIRTIUM,  "parser" : self.parse_virtium_info }
        }
```

With Kingston we are going through the generic approach with just model detection. There is neither fw nor endurance in generic SSD type.
[nba715-psustatus.txt](https://github.com/Azure/sonic-buildimage/files/7315111/nba715-psustatus.txt)
[nba715-smartctl.txt](https://github.com/Azure/sonic-buildimage/files/7315113/nba715-smartctl.txt)

**Pull request merged**
