### PR TITLE
[sonic-sairedis] submodule update

### PR DESCRIPTION
**Pull request by Sabareesh-Kumar-Anandan**
[vs] Add workaround for clean up macsec ports (#752)
[SAI submodule] Update SAI to 1.7.1 (#748)
[logfile]: Add handling of Sairedis rec filename  (#747)
Update README.md
[meta] Fix stat_mode enums to sai_bulk_op_error_mode_t (#753)
[syncd][tests] Add syncd deprecated attribute value test (#751)
[vs] Skip MACsec clean up if /sbin/ip is not accessible (#750)
Configure enable -Wcast-align=strict when supported by compiler (#749)
[syncd] Translate depreacated attr enum values to new ones (#746)
[sairedis]vs SAI support for voq neighbor (#725)
[syncd] Translate removed RIDs in fdb notification (#734)
[syncd] Move syncd classes to syncd namespace (#742)
[vs] Use /sbin/ip absolute path for ip command in MACsecManager (#744)
[saidiscovery] Update saidiscovery to use VendorSai object and metadata (#736)
Remove Winline warning since it depends on external headers (#741)
[meta] Enable strict cast-align warning (#738)
[vs] Use meta class instead info when using unittests (#740)
[vs] Support flush entry type all on virtual switch (#735)
[vslib]: Add MACsec state to state base (#722)
[README.md] Update installation steps (#730)
Switch Capability support (#728)
[vs] Fail switch create when warm boot requested and no warm boot state (#739)
Dynamic Port breakout fix the crash, port down event processing after<E2><80><A6> (#727)
Code clean (#721)

Signed-off-by: Sabareesh Kumar Anandan <sanandan@marvell.com>

**- Why I did it**

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
@kcudnik , build failure. can you check? https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all-pr/6611/console

**Comment by kcudnik** [comment]
g++: error: unrecognized command line option '-Wcast-align=strict'; did you mean '-Wcast-align'?
seems like gcc that compiles broadcom and mellanox dont have this strict align option

**Comment by kcudnik** [comment]
i will make fix PR for mellanox (broadcom will also fail after cast fix)

**Comment by lguohan** [comment]
broadcom build failure depends on this PR. https://github.com/Azure/sonic-buildimage/pull/6106

**Comment by kcudnik** [comment]
@Sabareesh-Kumar-Anandan you will need to move sairedis pointer forward, after fix on sairedis will be merged, and also maybe wait for update on brcm PR fix

**Comment by kcudnik** [comment]
mellanox fix PR merged on sairedis

**Comment by Sabareesh-Kumar-Anandan** [comment]
Thanks @kcudnik. I have updated the sairedis pointer

**Comment by kcudnik** [comment]
hmm, mellanox still failing in the same error
```C++ exception with description ":- cleanup_macsec_device: Cannot show MACsec ports" thrown in SetUp().```
maybe there is no /sbin/ip in that build docker but this would seem unlikely, i can add another check in code for that and skip if not command is found, but it would be better to figure out is this command is there

@lguohan does meallanox docker is build in some special way ?

**Comment by lguohan** [comment]
this is running inside the sonic-slave docker, it is the same for broadcom, mellanox.

**Comment by lguohan** [comment]
@kcudnik, can you investigate more on the build issue? we have lots of new sairedis pr to merge.

**Comment by kcudnik** [comment]
retest vsimage please

**Comment by kcudnik** [comment]
I added cast-align=strict condition https://github.com/Azure/sonic-sairedis/pull/749

**Comment by lguohan** [comment]
both pr mentioned by kamil is merged, wonder if you can update this submodule update so that we can get this one merge?

**Comment by kcudnik** [comment]
still the same error :(
``` C++ exception with description ":- cleanup_macsec_device: Cannot show MACsec ports" thrown in SetUp().```
have no idea how to debug this one

**Comment by kcudnik** [comment]
intresting mellanox passed without macsec fix

@Sabareesh-Kumar-Anandan i merged fix in sairedis repo, lets try one last time to update this submodule pointer

**Review by lguohan — DISMISSED** [review]

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
test passing. https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/8018/

**Comment by lguohan** [comment]
test passing. https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/8018/

**Comment by lguohan** [comment]
test passing. https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/8018/

**Pull request merged**
