### PR TITLE
CISCO: Give an opportunity to apply platform specific patches

### PR DESCRIPTION
**Pull request by VenkatCisco**
#### Why I did it
The platform/$PLATFORM/patches/configure.sh will apply patches as desired. 

#### How I did it
Changes to slave.mk file to invoke platform/$PLATFORM/patches/configure.sh. The patches directory, will host all the patches in its path. 

#### How to verify it

A sample bash script that does the following: 

platform/cisco-8000/patches/configure.sh 
```
#!/bin/bash

set -e
ROOT=$(pwd)
PATCHES=${ROOT}/platform/cisco-8000/patches
for path in ${PATCHES}/*; do
    if [ -d ${path} ]; then
        dir=${path##*/}
        (cd ${ROOT} && git submodule update src/${dir})

        (cd src/$dir && git clean -xfd \
                     && git reset --hard \
                     && git apply $(sed -n -e "/^#/n" -e "/^\\S/s@^@${path}/@p" ${path}/series))
    fi
```

#### Which release branch to backport (provide reason below if selected)

- [X] 201811
- [X ] 201911
- [X] 202006
- [X] 202012

### CODE REVIEW

**Comment by lguohan** [comment]
such patch can do anything, it is actually hard to do code review and reasoning now. i am not in favor of introducing such capability to the build system.

**Comment by VenkatCisco** [comment]
> such patch can do anything, it is actually hard to do code review and reasoning now. i am not in favor of introducing such general capability to the build system.

Ideally, we dont want to maintain any local patches for non platform code. This fix will only aids us with the following: 

1. Rapid development of platform code by the engineering team before code is upstreamed to Azure/sonic environment
2. Avoid rebase overheads and be very close to Azure/sonic code on an on-going basis.
3. Stage any code that requires up-streaming to Azure/sonic until it gets merged into Azure/sonic env.

**Comment by VenkatCisco** [comment]
azp/run

**Comment by VenkatCisco** [comment]
azp-run

**Comment by anshuv-mfst** [comment]
PR Scrum meeting 5/4: 
Please refer following:
1. https://github.com/Azure/sonic-buildimage/tree/master/src/redis-dump-load.patch
2. https://github.com/Azure/sonic-linux-kernel/tree/99ad21026954f58b364cd20815e38777fc5195fd/patch


Venkat: Is there way for patching at platform/patch level?
Ying: This might introduce merge conflict with linux_kernel_patch;

**Comment by VenkatCisco** [comment]
> PR Scrum meeting 5/4:
> Please refer following:
> 
> 1. https://github.com/Azure/sonic-buildimage/tree/master/src/redis-dump-load.patch
> 2. https://github.com/Azure/sonic-linux-kernel/tree/99ad21026954f58b364cd20815e38777fc5195fd/patch
> 
> Venkat: Is there way for patching at platform/patch level?
> Ying: This might introduce merge conflict with linux_kernel_patch;

The above 2 examples require the code to be upstreamed to particular src submodule and as we concluded in MSFT-CISCO code review mtg and this approach will not scale if a vendor wishes not to upstream the fix to src/<submodule/patch folder for sensitive reasons. 

Like we discussed in the code review. The file introduces no merge conflicts. We are not overriding the existing code, but appending to the existing code with this approach.  This is a heavily tested approach which only aids rapid internal development progress

**Comment by anshuv-mfst** [comment]
CC: @yxieca

**Comment by lguohan** [comment]
@qiluo-msft, can you check?

**Comment by qiluo-msft** [comment]
We have similar capability already, one example is as below https://github.com/Azure/sonic-buildimage/blob/8f883fee674eaa4c5bfe8d5649c709cb7c42a66f/slave.mk#L385

Could you try leverage?

**Comment by VenkatCisco** [comment]
> We have similar capability already, one example is as below
> 
> https://github.com/Azure/sonic-buildimage/blob/8f883fee674eaa4c5bfe8d5649c709cb7c42a66f/slave.mk#L385
> 
> Could you try leverage?

the _SRC_PATH is hardcoded to "src" directory. 

SRC_PATH = src
...
#     $(SOME_NEW_FILE)_SRC_PATH = $(SRC_PATH)/project_name                                                                                                      
...
        if [ -f $($*_SRC_PATH).patch/series ]; then pushd $($*_SRC_PATH) && QUILT_PATCHES=../$(notdir $($*_SRC_PATH)).patch quilt push -a; popd; fi



If the patch folder is under platform/<>/patch how would we want to extend quilt to that folder ?. For instance, the patch/series file is under platform/cisco-8000/patch/series

**Comment by qiluo-msft** [comment]
I am confused at the motivation. If the usage is only relating to cisco platform, why you need a patch? You can change the code under `platform/cisco-8000` directly. If you have concern about open source, you can maintain an internal branch, and rebase frequently.

**Comment by VenkatCisco** [comment]
Closing this PR as per conclusion that the sonic-linux-kernel code will have to be upstreamed rather

**Pull request closed without merging**
