### PR TITLE
[teamd] Porting teamd patch which solves the race condition between RTM_NEWLINK and port add

### PR DESCRIPTION
**Pull request by yxieca**
**- What I did**

Porting teamd patch which solves the race condition between RTM_NEWLINK and port add.

Removed previous patches from us: 0006, 0008, 0009.

Signed-off-by: Ying Xie <ying.xie@microsoft.com>

**- How to verify it**
continuous warm-reboot.

### CODE REVIEW

**Comment by yxieca** [comment]
@jipanyang here is the RCA you asked for when I checked in patch 0009. I think patch 0006, 0008, 0009 and 0011 incrementally solved the issue and this should be the last piece of the puzzle.

**Comment by jipanyang** [comment]
I have not gone through code flow thoroughly.  Likely I missed some key points.

When adding member,  there is processing to fetch the member attribute via netlink synchronously (team_refresh() ?   All the member attribute info should be available at kernel at that time based on the upper layer dependency control.  

Why need to have dependency on RTM_NEWLINK event?  Would the previous patches be unnecessary but just adding some complexity,  if team_refresh() change here works?

**Comment by yxieca** [comment]
I think they are fixing timing issue too. My previous 2 patches are fixing the timing issue with sequence of (1) create port, (2) RMT_NEWLINK but initial update failed. This last change was fixing the time sequence of (1) RTM_NEWLINK but initial update failed, (2) create port.

**Comment by pavel-shirshov** [comment]
Have you checked this patch?
https://github.com/jpirko/libteam/commit/45912ded9cb5166d8286a6a4fb53bfe9fffcd8a9

**Comment by yxieca** [comment]
@pavel-shirshov The change you identified has passed 200-ish iterations of tests where I removed patch 0006, 0007, 0008 and the patch in this PR. It looks like this change could be the fix. Thanks for looking into it!

**Comment by yxieca** [comment]
retest this please

**Pull request merged**
