### PR TITLE
[Mellanox] Update the buffer setting

### PR DESCRIPTION
**Pull request by stephenxs**
Update the buffer size.
Signed-off-by: Stephen Sun <stephens@mellanox.com>

**- Why I did it**
Recently buffer configuration has been updated:
- The way the headroom size calculated has been improved.
- Adjust `dynamic_th` of profiles used for BUFFER_PORT_INGRESS_PROFILE_LIST/BUFFER_PORT_EGRESS_PROFILE_LIST which represent per port ingress/egress reserved buffer respectively.
- Buffer pool sizes for all ingress pools and egress lossy pool are adjusted accordingly since we calculate them by subtracting accumulative reserved buffers for ports, PGs, and queues from total available memory.

This update is applied to all Mellanox platforms and SKUs. It is enforced by the `db_migrator` which will check the buffer configuration after a switch undergoes a SONiC-to-SONiC upgrade from an old image to a new one. If the buffer configuration matches the default value it will be upgraded to the new one. The granularity of matching is:
- For buffer pool, the configuration of all pools is compared as a whole, which means the update is performed only if the configuration of all pools matches the default value.
- For buffer profile for per port reserved ingress/egress buffer, the configuration of all profiles are compared as a whole, which means the update is performed only if the configuration of all that kind of profiles matches the default value
- For profile for lossless PGs, each profile of a speed, cable length pair is compared separately.

It depends on [sonic-utilities PR #993](https://github.com/Azure/sonic-utilities/pull/993) which includes the `db_migrator` part.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by stephenxs** [comment]
retest this please

**Comment by keboliu** [comment]
retest this please

**Comment by stephenxs** [comment]
> Please extend your PR message with more information about motivation, which SKUs are affected and how to have this new values enforced. Add relation to the db migrator PR as well

Done.

**Comment by stephenxs** [comment]
retest this please

**Comment by liat-grozovik** [comment]
This PR was tested by QoS community test and all is passing for the different ASICs/platforms.
As long as the db migration is not merged, a user will be able to do reload minigraph and get those values.
This PR is needed for 201911 as well (as marked on the labels).

**Pull request merged**
