### PR TITLE
[sonic-platform-daemons] submodule update

### PR DESCRIPTION
**Pull request by vdahiya12**
This PR updates the following commits in master for sonic-platform-daemons

b0be7ca [xcvrd] add unit test infrastructure and unit tests for xcvrd (#133)
8555077 [xcvrd] removing the delete notification message logic for command probe in mux cable driver (#134)

Signed-off-by: vaibhav-dahiya <vdahiya@microsoft.com>

### CODE REVIEW

**Review by tahmed-dev — APPROVED** [review]

**Review by jleveque — APPROVED** [review]

**Comment by vdahiya12** [comment]
Retest Broadcom please

**Comment by vdahiya12** [comment]
Retest mellanox please

**Comment by vdahiya12** [comment]
Retest broadcom please

**Comment by vdahiya12** [comment]
Retest vsimage please

**Comment by lguohan** [comment]
retest this please

**Pull request merged**
