### PR TITLE
[sairedis] Update sairedis submodule

### PR DESCRIPTION
**Pull request by daall**
[vs] Add CRM SAI attributes to virtual switch interface (#673)
Fix boot type for fast boot (#674)
Add support for saiplayer bulk API and add performance timers (#666)
Add ZeroMQ communication channel between sairedis and syncd (#659)
Support System ports config (#657)
Enable fabric counter for syncd's FlexCounter (#669)

Signed-off-by: Danny Allen <daall@microsoft.com>

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by daall** [comment]
retest broadcom please

**Comment by daall** [comment]
retest mellanox please

**Comment by daall** [comment]
retest vsimage please

**Review by lguohan — APPROVED** [review]

**Review by kcudnik — APPROVED** [review]

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
@daall , there seems some geninue problem of this pr. the vsimage tests continuously failing.

**Comment by daall** [comment]
> @daall , there seems some geninue problem of this pr. the vsimage tests continuously failing.

ack, I'll take a look

**Comment by lguohan** [comment]
depends on #5715

**Comment by daall** [comment]
> depends on #5715

Thanks, @lguohan! Do you want me to update this PR to grab the other bug fixes from sairedis as well?

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
let's just do your current commits, i haven't tested other commits from sairedis yet.

**Comment by daall** [comment]
#5703 includes all of these commits, closing

**Pull request closed without merging**
