### PR TITLE
Change PortChannel MTU to 9216

### PR DESCRIPTION
**Pull request by andriymoroz-mlnx**

### CODE REVIEW

**Comment by stcheng** [comment]
Do we need to set regular host interfaces' MTU to 9216?

**Comment by lguohan** [comment]
@stcheng, I think so.

**Comment by lguohan** [comment]
@andriymoroz-mlnx, can you also update the sonic-swss submodule?

**Comment by stcheng** [comment]
@lguohan sonic-swss is already updated.

**Comment by lguohan** [comment]
duplicate with 17f063314355a11e3e298fb6af63ad8a6364be9a

**Pull request closed without merging**
