### PR TITLE
[bfn] Added GENL3 dependency for SAI

### PR DESCRIPTION
**Pull request by akokhan**
Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>

**- What I did**
Added GENL3 dependency for BFN SAI

**- How to verify it**
```
make init
make configure PLATFORM=barefoot
time make all
```

### CODE REVIEW

**Comment by akokhan** [comment]
retest vsimage please

**Comment by akokhan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by akokhan** [comment]
retest vsimage please

**Pull request merged**
