### PR TITLE
Update DHCP_PACKET_MARK schema in state_db

### PR DESCRIPTION
**Pull request by trzhang-msft**
- update DHCP_PACKET_MARK schema in state_db
- this is an update over https://github.com/Azure/sonic-buildimage/pull/9015

Example output of DHCP_PACKET_MARK table in state_db:

state_db_mark

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by qiluo-msft** [comment]
his commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by trzhang-msft** [comment]
> This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

I don't see mux docker template file in 202012. Please solve that problem first. "mark_dhcp_packet" is a service inside mux container.

**Comment by trzhang-msft** [comment]
> This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

Please check if this pr now can be cherry-picked. If not, I will submit another.

**Comment by qiluo-msft** [comment]
I cherry-picked again and it failed.

**Pull request merged**
