### PR TITLE
[frr]: change frr as default sonic routing stack

### PR DESCRIPTION
**Pull request by lguohan**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
retest this please

**Comment by jipanyang** [comment]
It looks VS docker change is needed to use frr? supervisord.conf is hardcoded with quagga path.

**Comment by lguohan** [comment]
current pr won't work in case the routing stack is quagga, need to figure out a way to support both quagga and frr.

**Comment by lguohan** [comment]
@jipanyang , for first 2, check #2870

**Comment by zhenggen-xu** [comment]
@jipanyang  Can you elaborate this "zebra/bgpd will be restarted automatically by watchfrr. it will affect warm reboot function."?  What exactly the impact?  
There were reasons the daemons were restarted:  crashed or hang etc. And I assume we want the daemons to be restarted to recover. They are agnostic to warm-restart/reboot. 

In case BGP restart, zebra is supposed to remove all routes from kernel and SONiC. This is BGP feature gap that if we need support unplanned warm restart.

In case zebra crash/restart, routes were not removed and the fpmsyncd will do the reconciliation later once zebra is back.

**Comment by jipanyang** [comment]
@zhenggen-xu Currently bgpd and zebra are killed explicitly for warm reboot.  If watchfrr is there, change may be needed to take watchfrr into account.
 
```
# Kill bgpd to start the bgp graceful restart procedure
debug "Stopping bgp ..."
docker exec -i bgp pkill -9 zebra
docker exec -i bgp pkill -9 bgpd || [ $? == 1 ]
debug "Stopped  bgp ..."
```

**Pull request merged**
