### PR TITLE
[core_uploader.py] Convert to Python 3; Use logger from sonic-py-common for uniform logging 

### PR DESCRIPTION
**Pull request by jleveque**
**- Why I did it**

As part of moving all SONiC code from Python 2 (no longer supported) to Python 3

**- How I did it**

- Convert core_uploader.py script to Python 3
- Use logger from sonic-py-common for uniform logging
- Reorganize imports alphabetically per PEP8 standard
- Two blank lines precede functions per PEP8 standard
- Remove unnecessary global variable declarations

**- How to verify it**

Ensure core_uploader.py still functions correctly

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

### CODE REVIEW

**Review by renukamanavalan — APPROVED** [review]
Thank you, Joe!

**Comment by jleveque** [comment]
Retest baseimage please

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by jleveque** [comment]
Retest vsimage please

**Review by renukamanavalan — DISMISSED** [review]

**Review by renukamanavalan — APPROVED** [review]

**Pull request merged**
