### PR TITLE
[201811] advance sub module heads

### PR DESCRIPTION
**Pull request by yxieca**
**- What I did**

Submodule src/sonic-platform-common 42119e1..5d7954e:
  > [ChassisBase] Make reboot cause constant strings human-readable (#35)
  > Add .gitignore file (#28)
  > [sonic_platform_base] Add sonic_sfp and sonic_eeprom to sonic_platform_base (#27)
  > Enhance new platform API (#19)
  > fix typo in platform API base class (#25)

Submodule src/sonic-swss 9cf7b01..1e99c93:
  > Set timer only when interval changes. Not in each firing of the timer. (#945)

Submodule src/sonic-utilities ec1e93f..24958f1:
  > [fast reboot] stop removing opennsl module before reboot (#560)

Submodule src/sonic-swss-common b472f6e..d6140fa:
  > timerfd:read failure - Record in logs as error. (#295)
  > do not abort when read timerfd return 0 and errno = 0 (#291)
  > Add an assert to logger, which will log a message and abort. (#286)

Signed-off-by: Ying Xie <ying.xie@microsoft.com>

### CODE REVIEW

**Comment by lguohan** [comment]
can you update sonic-swss-common?

**Comment by yxieca** [comment]
Thanks for the point! Done.

**Comment by lguohan** [comment]
looks good, can you update the description to include sonic-swss-common changes?

**Comment by yxieca** [comment]
retest this please

**Comment by yxieca** [comment]
Comments has been updated.

**Pull request merged**
