### PR TITLE
[pmon][barefoot] Disabled fancontrol pmon daemon

### PR DESCRIPTION
**Pull request by msosyak**
**- Why I did it**
fancontrol is not supported by these platforms
**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by msosyak** [comment]
Need for 201911

**Comment by msosyak** [comment]
FYI: @akokhan

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by rlhui** [comment]
@msosyak , cherry-pick has conflicts.  please raise a separate PR for 201911 branch. Thanks.

**Comment by msosyak** [comment]
Cherry-piked to 201911 by https://github.com/Azure/sonic-buildimage/pull/4578

**Pull request merged**
