### PR TITLE
Update REAME and diag utility for Nephos

### PR DESCRIPTION
**Pull request by kaiyu22**
**- What I did**
Add Nephos information in README.md
Update content of npx_diag from binary to shell

**- How I did it**

**- How to verify it**
Check npx_diag work as well

**- Description for the changelog**
Update REAME and diag utility for Nephos

Signed-off-by: Sam Yang <yang.kaiyu@gmail.com>

### CODE REVIEW

**Comment by lguohan** [comment]
we do not host binary in this github.

**Comment by kaiyu22** [comment]
Hi @lguohan , 
The diff shows type of npx_diag as binary, because I have committed npx_diag as binary in last commitment ([74fdb88](https://github.com/Azure/sonic-buildimage/pull/1082/commits/74fdb880482b64865505831186f7d37dfdc1f74f)). And this time, I will change the type of npx_diag from binary to shell script. 

You can also check the [content ](https://github.com/kaiyu22/sonic-buildimage/blob/9433ff57f3b5ee4f3a7b1316f1ed27c52c55d411/platform/nephos/docker-syncd-nephos/base_image_files/npx_diag)and [attribute ](https://drive.google.com/file/d/0BxHGMQfuLSOgNW9yWEUxYXVINDQ/view?usp=sharing)of npx_diag. It is a shell script.

**Comment by stcheng** [comment]
are we also having versions on the README.md file?

**Comment by kaiyu22** [comment]
The current version of README.md is **201709 branch**, and it is not in the **master**

**Pull request merged**
