### PR TITLE
[swsssdk-py] update submodule for sonic-py-swsssdk

### PR DESCRIPTION
**Pull request by dzhangalibaba**
update multiDB changes in sonic-py-swsssdk, including:
*[multi-DB] Part 4: add sonic-db-cli to replace redis-cli (#54)
*[multi-DB] Part 3: Python API changes (#52)
*remove SonicV2Connector which is not used any more (#53)

This needs https://github.com/Azure/sonic-buildimage/pull/3825 to be merged first. Otherwise when reloading minigraph/config will hit error.

Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

### CODE REVIEW

**Comment by dzhangalibaba** [comment]
BLOCK on https://github.com/Azure/sonic-buildimage/pull/3825

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
#3825 is merged, but the vs image test is still failing. Have you build a whole image and test? I feel something is still wrong.

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
> #3825 is merged, but the vs image test is still failing. Have you build a whole image and test? I feel something is still wrong.

Yes . I tested it locally, it works fine. I noticed not only my PR failed, other PR failed with the same reason.
Let me restet vsimage and see if it passed.

**Comment by lguohan** [comment]
I did config reload -y but found the eth0 has no IP address.

**Comment by dzhangalibaba** [comment]
> I did config reload -y but found the eth0 has no IP address.

interesting. I did the same  and the eth0 ip is good. For safety resaon, I masked the real IP.

```
admin@ASW-7005:~$ sudo config reload -y
Stopping service swss ...
Stopping service lldp ...
Stopping service bgp ...
Stopping service hostcfgd ...
Running command: /usr/local/bin/sonic-cfggen -j /etc/sonic/config_db.json --write-to-db
Resetting failed status for service bgp ...
Resetting failed status for service dhcp_relay ...
Resetting failed status for service hostcfgd ...
Resetting failed status for service hostname-config ...
Resetting failed status for service interfaces-config ...
Resetting failed status for service lldp ...
Resetting failed status for service ntp-config ...
Resetting failed status for service radv ...
Resetting failed status for service rsyslog-config ...
Resetting failed status for service swss ...
Resetting failed status for service syncd ...
Resetting failed status for service teamd ...
Restarting service hostname-config ...
Restarting service interfaces-config ...
Restarting service ntp-config ...
Restarting service rsyslog-config ...
Restarting service swss ...
Restarting service bgp ...
Restarting service lldp ...
Restarting service hostcfgd ...
Restarting service sflow ...
admin@ASW-7005:~$ 
admin@ASW-7005:~$ sudo ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet XX.XX.XXX.XX  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::205:64ff:fe2f:109c  prefixlen 64  scopeid 0x20<link>
        ether 00:05:64:2f:10:9c  txqueuelen 1000  (Ethernet)
        RX packets 1355305  bytes 207044605 (197.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 34764  bytes 4578922 (4.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xdfe60000-dfe7ffff  

admin@ASW-7005:~$ 


```

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Pull request merged**
