### PR TITLE
[DPB] [Mellanox] added capability files for SN3800 platform

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
**- Why I did it**

`platform.json` and `hwsku.json` files are required for a feature called Dynamic Port Breakout

**- How I did it**

Created capability files according to platform specification `SN3800`

**- How to verify it**

Full qualification requires bugs fixes reported under sonic-buildimage

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Review by liat-grozovik — CHANGES_REQUESTED** [review]
remove split of 4

**Comment by vadymhlushko-mlnx** [comment]
retest broadcom please

**Comment by vadymhlushko-mlnx** [comment]
Please don't merge this PR until [[DPB][MLNX][YANG-models] extended regex pattern according to MLNX systems speeds requirements](https://github.com/Azure/sonic-buildimage/pull/6279) PR will be merged

**Review by liat-grozovik — CHANGES_REQUESTED** [review]
Extend the speeds for all SKUs

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
