### PR TITLE
[sonic-sairedis update] Support for SAI header v1.10.2 with BRCM SAI v7.1.0.0 and MLNX SAI v1.21.1.0

### PR DESCRIPTION
**Pull request by vmittal-msft**
Signed-off-by: Vineet Mittal <vineetmittal@microsoft.com>

#### Why I did it
Support SAI header v1.10.2

#### How I did it
Integrated SAI header 1.10.2 with sonic-sairedis and made changes to vendor code in sonic
https://github.com/Azure/sonic-sairedis/pull/1034
https://github.com/Azure/saibcm-modules/commit/fb4cf12529bc27fffc1c988029f4db100138f133

#### How to verify it
Verified to be working fine on BRCM TD3/TH based HWSKUs. 

BRCM SAI ver: [7.1.0.0], OCP SAI ver: [1.10.2], SDK ver: [sdk-6.5.24] CANCUN ver: [06.04.01]

show int status
     Interface            Lanes    Speed    MTU    FEC         Alias            Vlan    Oper    Admin             Type    Asym PFC
--------------  ---------------  -------  -----  -----  ------------  --------------  ------  -------  ---------------  ----------
     Ethernet0          1,2,3,4     100G   9100     rs   Ethernet1/1          routed    down     down  QSFP28 or later         off
     Ethernet4          5,6,7,8     100G   9100     rs   Ethernet2/1           trunk      up       up  QSFP28 or later         off
     Ethernet8       9,10,11,12     100G   9100     rs   Ethernet3/1           trunk      up       up  QSFP28 or later         off
    Ethernet12      13,14,15,16     100G   9100     rs   Ethernet4/1           trunk      up       up  QSFP28 or later         off
    Ethernet16      21,22,23,24     100G   9100     rs   Ethernet5/1           trunk      up       up  QSFP28 or later         off
    Ethernet20      17,18,19,20     100G   9100     rs   Ethernet6/1           trunk      up       up  QSFP28 or later         off
    Ethernet24      25,26,27,28     100G   9100     rs   Ethernet7/1           trunk      up       up  QSFP28 or later         off
    Ethernet28      29,30,31,32     100G   9100     rs   Ethernet8/1           trunk      up       up  QSFP28 or later         off
    Ethernet32      37,38,39,40     100G   9100     rs   Ethernet9/1           trunk      up       up  QSFP28 or later         off
    Ethernet36      33,34,35,36     100G   9100     rs  Ethernet10/1           trunk      up       up  QSFP28 or later         off
    Ethernet40      41,42,43,44     100G   9100     rs  Ethernet11/1           trunk      up       up  QSFP28 or later         off
    Ethernet44      45,46,47,48     100G   9100     rs  Ethernet12/1           trunk      up       up  QSFP28 or later         off
    Ethernet48      53,54,55,56     100G   9100     rs  Ethernet13/1           trunk      up       up  QSFP28 or later         off
    Ethernet52      49,50,51,52     100G   9100     rs  Ethernet14/1           trunk      up       up  QSFP28 or later         off
    Ethernet56      57,58,59,60     100G   9100     rs  Ethernet15/1           trunk      up       up  QSFP28 or later         off
    Ethernet60      61,62,63,64     100G   9100     rs  Ethernet16/1           trunk      up       up  QSFP28 or later         off
    Ethernet64      69,70,71,72     100G   9100     rs  Ethernet17/1           trunk      up       up  QSFP28 or later         off
    Ethernet68      65,66,67,68     100G   9100     rs  Ethernet18/1           trunk      up       up  QSFP28 or later         off
    Ethernet72      73,74,75,76     100G   9100     rs  Ethernet19/1           trunk      up       up  QSFP28 or later         off
    Ethernet76      77,78,79,80     100G   9100     rs  Ethernet20/1           trunk      up       up  QSFP28 or later         off
    Ethernet80      85,86,87,88     100G   9100     rs  Ethernet21/1           trunk      up       up  QSFP28 or later         off
    Ethernet84      81,82,83,84     100G   9100     rs  Ethernet22/1           trunk      up       up  QSFP28 or later         off
    Ethernet88      89,90,91,92     100G   9100     rs  Ethernet23/1           trunk      up       up  QSFP28 or later         off
    Ethernet92      93,94,95,96     100G   9100     rs  Ethernet24/1           trunk      up       up  QSFP28 or later         off
    Ethernet96  101,102,103,104     100G   9100     rs  Ethernet25/1           trunk      up       up  QSFP28 or later         off
   Ethernet100     97,98,99,100     100G   9100     rs  Ethernet26/1          routed    down     down  QSFP28 or later         off
   Ethernet104  105,106,107,108     100G   9100     rs  Ethernet27/1          routed    down     down  QSFP28 or later         off
   Ethernet108  109,110,111,112     100G   9100     rs  Ethernet28/1          routed    down     down  QSFP28 or later         off
   Ethernet112  117,118,119,120     100G   9100     rs  Ethernet29/1  PortChannel101      up       up  QSFP28 or later         off
   Ethernet116  113,114,115,116     100G   9100     rs  Ethernet30/1  PortChannel102      up       up  QSFP28 or later         off
   Ethernet120  121,122,123,124     100G   9100     rs  Ethernet31/1  PortChannel103      up       up  QSFP28 or later         off
   Ethernet124  125,126,127,128     100G   9100     rs  Ethernet32/1  PortChannel104      up       up  QSFP28 or later         off
   Ethernet128              129      10G   9100    N/A    Ethernet33          routed    down     down              N/A         off
   Ethernet132              128      10G   9100    N/A    Ethernet34          routed    down     down              N/A         off
PortChannel101              N/A     100G   9100    N/A           N/A          routed      up       up              N/A         N/A
PortChannel102              N/A     100G   9100    N/A           N/A          routed      up       up              N/A         N/A
PortChannel103              N/A     100G   9100    N/A           N/A          routed      up       up              N/A         N/A
PortChannel104              N/A     100G   9100    N/A           N/A          routed      up       up              N/A         N/A

show ip bgp sum

IPv4 Unicast Summary:
BGP router identifier 10.1.0.32, local AS number 65100 vrf-id 0
BGP table version 12806
RIB entries 12807, using 2458944 bytes of memory
Peers 4, using 87264 KiB of memory
Peer groups 4, using 256 bytes of memory

Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down      State/PfxRcd  NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.0.57      4  64600       3231       3230         0      0       0  00:01:10             6400  ARISTA01T1
10.0.0.59      4  64600       3231       3230         0      0       0  00:01:10             6400  ARISTA02T1
10.0.0.61      4  64600       3228       3229         0      0       0  00:01:10             6400  ARISTA03T1
10.0.0.63      4  64600       3231       3230         0      0       0  00:01:11             6400  ARISTA04T1

Total number of neighbors 4

show ip route summary
Route Source         Routes               FIB  (vrf default)
connected            7                    7                    
ebgp                 6403                 6403                 
ibgp                 0                    0                    
------
Totals               6410                 6410                 

show ipv6 route summary
Route Source         Routes               FIB  (vrf default)
kernel               1                    1                    
connected            43                   43                   
static               1                    1                    
ebgp                 6403                 6403                 
ibgp                 0                    0                    
------
Totals               6448                 6448                 

Following sonic-mgmt tests are passing with this -
fib/test_fib.py 
vxlan/test_vxlan_decap.py
fdb/test_fdb.py 
decap/test_decap.py
ipfwd/test_dir_bcast.py
vlan/test_vlan.py

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

#### Description for the changelog

SAI header tag v1.10.2 support

### CODE REVIEW

**Comment by dgsudharsan** [comment]
@vmittal-msft  Can you please correct the MLNX SAI version in the title to v1.21.1.0?

**Comment by vmittal-msft** [comment]
> @vmittal-msft Can you please correct the MLNX SAI version in the title to v1.21.1.0?

Done. Thanks.

**Comment by dgsudharsan** [comment]
> > @vmittal-msft Can you please correct the MLNX SAI version in the title to v1.21.1.0?
> 
> Done. Thanks.

Hi @vmittal-msft I still see the title with v1.12.1.0
[[sonic-sairedis update] Support for SAI header v1.10.2 with BRCM SAI v7.1.0.0 and MLNX SAI v1.12.1.0](https://github.com/Azure/sonic-buildimage/pull/10583#)

**Comment by vmittal-msft** [comment]
> > > @vmittal-msft Can you please correct the MLNX SAI version in the title to v1.21.1.0?
> > 
> > 
> > Done. Thanks.
> 
> Hi @vmittal-msft I still see the title with v1.12.1.0 [[sonic-sairedis update] Support for SAI header v1.10.2 with BRCM SAI v7.1.0.0 and MLNX SAI v1.12.1.0](https://github.com/Azure/sonic-buildimage/pull/10583#)

Done. Thanks.

**Review by alexrallen — CHANGES_REQUESTED** [review]
@vmittal-msft Before you update the sonic-sairedis submodule pointer in sonic-buildimage you need to make sure the following PRs are merged from SAI and the pointer is updated in this repo as the v1.10 is currently missing them and will cause regressions. 

https://github.com/opencomputeproject/SAI/pull/1473
https://github.com/opencomputeproject/SAI/pull/1472

**Comment by vmittal-msft** [comment]
> [opencomputeproject/SAI#1473](https://github.com/opencomputeproject/SAI/pull/1473)
> [opencomputeproject/SAI#1472](https://github.com/opencomputeproject/SAI/pull/1472)

Opened PR to take care of above - 
https://github.com/Azure/sonic-sairedis/pull/1037

**Pull request merged**
