### PR TITLE
[sonic-platform-common] Update submodule

### PR DESCRIPTION
**Pull request by jleveque**
Commits include:

* src/sonic-platform-common d912db6...fa0aaa6 (3):
  > [sonic_sfp]: add logical_to_asic dict (#141)
  > [sonic_pcie][sonic_ssd] Make Python 3-compliant (#150)
  > [eeprom_base] Close lock file after unlocking (#149)

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Comment by judyjoseph** [comment]
@jleveque Could you take this PR as well ..https://github.com/Azure/sonic-platform-common/pull/141, or let me know I can update this PR itself - thanks

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
> @jleveque Could you take this PR as well ..[Azure/sonic-platform-common#141](https://github.com/Azure/sonic-platform-common/pull/141), or let me know I can update this PR itself - thanks

@judyjoseph: vsimage test failed, so I pulled in your commit.

**Comment by lguohan** [comment]
retest vs please

**Comment by lguohan** [comment]
retest mellanox please

**Comment by lguohan** [comment]
retest vsimage please

**Review by lguohan — APPROVED** [review]

**Comment by judyjoseph** [comment]
> > @jleveque Could you take this PR as well ..[Azure/sonic-platform-common#141](https://github.com/Azure/sonic-platform-common/pull/141), or let me know I can update this PR itself - thanks
> 
> @judyjoseph: vsimage test failed, so I pulled in your commit, seeing as I had to wait for a re-test anyway.

Thanks @jleveque .. wanted to get this PR in as it will unblock for single ASIC platforms using platform.json file.

**Pull request merged**
