### PR TITLE
[device][mellanox] Add 2x40G support to MSN4700 platform

### PR DESCRIPTION
**Pull request by alexrallen**
#### Why I did it

MSN4700 platform has 8 lanes per port and thus can support 2x40G with each lane running at 10G

#### How I did it

Added 40G to 2x200G breakout mode in platform.json

#### How to verify it

Run `config int break Ethernet0 2x40G[200G,100G,50G,25G,10G,1G]`
And verify the command runs successfully and the port speed was set to 40G with a 2x breakout. 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [x] 202106
- [x] 202111 

#### Description for the changelog
[device][mellanox] Add 2x40G support to MSN4700 platform

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@alexrallen what about 202012 branch? will this PR be cherry pickable ? if not and still needed please issue a different PR.

**Comment by dgsudharsan** [comment]
@liat-grozovik Can you please review and merge?

**Review by liat-grozovik — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Pull request merged**
