### PR TITLE
[Mellanox] Fix the memory leak in mlnx-sfpd

### PR DESCRIPTION
**Pull request by stephenxs**
**- What I did**
Fix the memory leak in mlnx-sfpd.

**- How I did it**
Fix the memory leak in mlnx-sfpd::on_pmpe.

**- How to verify it**
reset an SFP module, and then:
1. observe /proc/\<pid of mlnx-sfpd>/maps and check whether [heap] increases.
2. observe syslog and check whether SFP module plugin/out event has been recorded.

**- Description for the changelog**
[Mellanox] Fix the memory leak in mlnx-sfpd

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
@jleveque , we should do pmon memory limit so that it won't impact other services in sonic.

**Comment by lguohan** [comment]
can you identify which branch are affected?

**Comment by keboliu** [comment]
> can you identify which branch are affected?
@lguohan @stephenxs this issue affect 201807 and above, for 201807 need a dedicated PR since the code was refactored since 201811.  for 201811 and above can cherry-pick.

**Comment by stephenxs** [comment]
> > can you identify which branch are affected?
> > @lguohan @stephenxs this issue affect 201807 and above, for 201807 need a dedicated PR since the code was refactored since 201811.  for 201811 and above can cherry-pick.

[PR#3131](https://github.com/Azure/sonic-buildimage/pull/3131) for 201807

**Pull request merged**
