### PR TITLE
[Arista] Add platform.json to Arista platforms

### PR DESCRIPTION
**Pull request by zzhiyuan**
Also removed the folder symlink for BlackhawkDD because it has a different
platform.json than BlackhawkO.

**- Why I did it**
platform.json is needed for sonic-mgmt testing.
Also in the future it will be used as part of dynamic port breakout.

**- How I did it**
Used a script to generate the file per platform.

**- How to verify it**
I ran sonic-mgmt chassis test and the parts that require platform.json facts pass.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

**Comment by SavchukRomanLv** [comment]
@jleveque can it be added to 201911 also?

**Comment by jleveque** [comment]
@SavchukRomanLv: I don't believe there is anythin in the 201911 branch which references platform.json. Why do you ask?

**Comment by SavchukRomanLv** [comment]
> @SavchukRomanLv: I don't believe there is anythin in the 201911 branch which references platform.json. Why do you ask?
@jleveque  we run api cases from sonic-mgmt, and they requires platform.json file

**Comment by jleveque** [comment]
@SavchukRomanLv: The platform.json files were added as an enhancement in the master branch, we did not intend for this functionality to be backported to 201911. The sonic-mgmt Platform API tests were written against the master branch, and may not align properly with the state of the API in the 201911 branch. I feel it is best to not backport these files and just use them moving forward.

**Comment by SavchukRomanLv** [comment]
@jleveque I see, thank you for response!!

**Pull request merged**
