### PR TITLE
Extend t1-lag timeout to 360 minutes

### PR DESCRIPTION
**Pull request by stephenxs**
Signed-off-by: Stephen Sun <stephens@nvidia.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by stephenxs** [comment]
Looks like the run time of t1-lag drops to 270~280 minutes. closing this one.

**Comment by stephenxs** [comment]
Last time it took 326 minutes to finish kvmtest-t1-lag 
`Azure.sonic-buildimage (Test kvmtest-t1-lag) Successful in 326m — Test kvmtest-t1-lag succeeded`

**Review by yxieca — APPROVED** [review]

**Pull request merged**
