### PR TITLE
[202012][Mellanox] Update SDK/FW to 4.5.1500/2010.1500 and SAI version to 1.21.1.2

### PR DESCRIPTION
**Pull request by dgsudharsan**
#### Why I did it
Update SDK/FW to 4.5.1500/2010.1500 and SAI version to 1.21.1.2 

**SDK/FW features**
- Added support for Finisar DR4 (FTCD4523E2PCM) on Spectrum-2 and Spectrum-3 systems.

**SAI features**
- ECMP overlay support for IPv6
- BFD offloading / 4K scale
- SDK 4.5.1500 porting

**SAI fixes**
- Reduce verbosity of print in case packet ingress on invalid port 
- Added support for Host table entry removal API to remove registration of a trap to a channel.

#### How I did it
Update submodules of both SDK and SAI

#### How to verify it
Run full sonic-mgmt regression

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by prsunny** [comment]
@dgsudharsan , can you check the build failure? 
@sumukhatv for viz

**Comment by dgsudharsan** [comment]
> @dgsudharsan , can you check the build failure? @sumukhatv for viz

@prsunny  This is still under draft. We are preparing SDK binaries and once merged we will open the PR

**Comment by dgsudharsan** [comment]
The build fails in kvmtest and is not related to platform specific changes done here

**Pull request merged**
