### PR TITLE
[submodule update] update sonic-snmpagent pointer

### PR DESCRIPTION
**Pull request by mykolaf**
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>

**- What I did**
update sonic-snmpagent pointer
**- How I did it**

**- How to verify it**

**- Description for the changelog**

[sonic-snmpagent]
 - Added logic to get PSU info directly from the state DB (#101)
 - Fix issue #104: lldpLocManAddrTable supports multiple IP addresses (#106)
 - Add mgmt port speed test (#107)
 - [rfc2737] fix typo in xcvr removal flow (#109)
 - Add signal handler to change debug level. (#96) 
 - [LLDP MIB] fix lldp loc mgmt ip logic (#113) 

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
@qiluo-msft , do we need this in 201811 branch?

**Comment by qiluo-msft** [comment]
> @qiluo-msft , do we need this in 201811 branch?

We don't need.

**Comment by lguohan** [comment]
then, why is the PR is created against 201811 branch?

**Comment by mykolaf** [comment]
There are a few bugfixes, but I guess it's not mandatory to pull them to such old release.

**Pull request closed without merging**
