### PR TITLE
update submodule sonic-py-swsssdk

### PR DESCRIPTION
**Pull request by ysmanman**
#### Why I did it
Update submodule sonic-py-swsssdk to incorporate the following commits: 
2436648 define index for recirc port (#118)
84c7a85 [ci]: Support code diff coverage (#116)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Review by SuvarnaMeenakshi — APPROVED** [review]
Please change PR description to specify the commits of sonic-py-swsssdk that is included in this update

**Comment by ysmanman** [comment]
> Please change PR description to specify the commits of sonic-py-swsssdk that is included in this update

@SuvarnaMeenakshi Update the PR description as you suggested.

**Comment by SuvarnaMeenakshi** [comment]
> > Please change PR description to specify the commits of sonic-py-swsssdk that is included in this update
> 
> @SuvarnaMeenakshi Update the PR description as you suggested.

This also has https://github.com/Azure/sonic-py-swsssdk/pull/116 change, correct?
Can you mention that as well.

**Comment by ysmanman** [comment]
> > > Please change PR description to specify the commits of sonic-py-swsssdk that is included in this update
> > 
> > 
> > @SuvarnaMeenakshi Update the PR description as you suggested.
> 
> This also has [Azure/sonic-py-swsssdk#116](https://github.com/Azure/sonic-py-swsssdk/pull/116) change, correct? Can you mention that as well.
Thanks. Updated the description to include the above commit too.

**Comment by SuvarnaMeenakshi** [comment]
> > > > Please change PR description to specify the commits of sonic-py-swsssdk that is included in this update
> > > 
> > > 
> > > @SuvarnaMeenakshi Update the PR description as you suggested.
> > 
> > 
> > This also has [Azure/sonic-py-swsssdk#116](https://github.com/Azure/sonic-py-swsssdk/pull/116) change, correct? Can you mention that as well.
> > Thanks. Updated the description to include the above commit too.

Modified to include PR# to match submodule PR description.

**Pull request merged**
