### PR TITLE
[sonic-utilities]: Update Submodule

### PR DESCRIPTION
**Pull request by tahmed-dev**
Changes in this update:
37695c8 [show]: Use TCP Connection For Muxcable Commands (#1371)
8119ba2 Validations checks while creating and deleting a Portchannel (#1326)
3df267e [config] Fix Breakout mode option and BREAKOUT_CFG table check method (#1270)
9bd709b [show] Fix show arp in case with FDB entries, linked to default VLAN (#1357)
bc2d27e [generate_dump]: fix syntax error

signed-of-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

**- Why I did it**
Fix bugs in sonic-buildimage

**- How I did it**
ported fixes via submodule update

**- How to verify it**
PR check and on target verification

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Review by vdahiya12 — APPROVED** [review]

**Comment by tahmed-dev** [comment]
retest broadcom please

**Comment by tahmed-dev** [comment]
retest Azure.sonic-buildimage please

**Comment by tahmed-dev** [comment]
retest kvmtest please

**Comment by tahmed-dev** [comment]
retest "Test kvmtest" please

**Review by lguohan — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Pull request merged**
