### PR TITLE
[201811][platform-cel]: Fix dx010 FSC error

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- Why I did it**
- Fix DX010 FSC error from https://github.com/Azure/sonic-buildimage/pull/4867

**- How I did it**
- Add GPIO init script for Fan
- Replace fancontrol in pmon 

**- How to verify it**
- Check fan service status by using commands
  - `docker exec -it pmon supervisorctl status` 
  - [201811-dx010-fsc-pmon.log](https://github.com/Azure/sonic-buildimage/files/5222494/201811-dx010-fsc-pmon.log)

**Signed-off-by**: Wirut Getbamrung [wgetbumr@celestica.com]

### CODE REVIEW

**Comment by mudsut4ke** [comment]
Waiting for test result........

**Comment by yxieca** [comment]
This change has some improvement but didn't address the issue fully:

Improvement: the fancontrol module no longer generate error:

Jul 14 18:09:45 sonic fancontrol.sh[1448]:   MAXPWM=255
Jul 14 18:09:45 sonic fancontrol.sh[1448]:   THYST=3
Jul 14 18:09:45 sonic fancontrol.sh[1448]:   THYST=3
Jul 14 18:09:45 sonic fancontrol.sh[1448]: Settings for ASIC temperature sensor:
Jul 14 18:09:45 sonic fancontrol.sh[1448]: Settings for ASIC temperature sensor:
Jul 14 18:09:45 sonic fancontrol.sh[1448]:   Depends on /sys/bus/i2c/devices/7-004a/hwmon/hwmon*/temp1_input
Jul 14 18:09:45 sonic fancontrol.sh[1448]:   MAXTEMPCRIT=75
Jul 14 18:09:45 sonic fancontrol.sh[1448]:   Depends on /sys/bus/i2c/devices/7-004a/hwmon/hwmon*/temp1_input
Jul 14 18:09:45 sonic fancontrol.sh[1448]:   MAXTEMPCRIT=75
Jul 14 18:09:45 sonic fancontrol.sh[1448]: Settings for CPU temperature sensor:
Jul 14 18:09:45 sonic fancontrol.sh[1448]: Settings for CPU temperature sensor:
Jul 14 18:09:45 sonic fancontrol.sh[1448]:   Depends on /sys/bus/i2c/devices/14-0048/hwmon/hwmon*/temp1_input
Jul 14 18:09:45 sonic fancontrol.sh[1448]:   Depends on /sys/bus/i2c/devices/14-0048/hwmon/hwmon*/temp1_input
Jul 14 18:09:45 sonic fancontrol.sh[1448]:   MAXTEMPCRIT=75
Jul 14 18:09:45 sonic fancontrol.sh[1448]:   MAXTEMPCRIT=75
Jul 14 18:09:45 sonic fancontrol.sh[1448]: Enabling PWM on fans...
Jul 14 18:09:45 sonic fancontrol.sh[1448]: Enabling PWM on fans...
Jul 14 18:09:46 sonic fancontrol.sh[1448]: Starting automatic fan control...
Jul 14 18:09:46 sonic fancontrol.sh[1448]: Starting automatic fan control...

Issue left:
admin@str-dx010-acs-1:~$ docker exec -it pmon bash 
root@str-dx010-acs-1:/# supervisorctl status
fancontrol                       STOPPED   Not started
ledd                             EXITED    Jul 14 06:10 PM
lm-sensors                       EXITED    Jul 14 06:09 PM
rsyslogd                         RUNNING   pid 12, uptime 0:02:09
start.sh                         EXITED    Jul 14 06:10 PM
xcvrd                            RUNNING   pid 37, uptime 0:01:44

root@str-dx010-acs-1:/# supervisorctl start fancontrol
fancontrol: ERROR (spawn error)
root@str-dx010-acs-1:/# supervisorctl status
fancontrol                       BACKOFF   Exited too quickly (process log may have details)
ledd                             EXITED    Jul 14 06:10 PM
lm-sensors                       EXITED    Jul 14 06:09 PM
rsyslogd                         RUNNING   pid 12, uptime 0:03:46
start.sh                         EXITED    Jul 14 06:10 PM
xcvrd                            RUNNING   pid 37, uptime 0:03:21
root@str-dx010-acs-1:/# supervisorctl status
fancontrol                       FATAL     Exited too quickly (process log may have details)
ledd                             EXITED    Jul 14 06:10 PM
lm-sensors                       EXITED    Jul 14 06:09 PM
rsyslogd                         RUNNING   pid 12, uptime 0:03:53
start.sh                         EXITED    Jul 14 06:10 PM
xcvrd                            RUNNING   pid 37, uptime 0:03:28

**Comment by mudsut4ke** [comment]
@yxieca , I am discussing about the solution in an email

**Review by yxieca — CHANGES_REQUESTED** [review]
This change doesn't work. Fancontrol is still down in pmon docker. Please test your change before submitting for review.

**Comment by mudsut4ke** [comment]
> This change doesn't work. Fancontrol is still down in pmon docker. Please test your change before submitting for review.

@yxieca, this change is to fix an error of fancontrol daemon
but anyway the our fancontrol daemon is running on sonic host 
so fancontrol daemon on pmon is not in use

**Comment by mudsut4ke** [comment]
@yxieca , I have submitted new change to run fancontrol in pmon docker (https://github.com/Azure/sonic-buildimage/pull/4949/commits/8c366272d688b78c09c7810b191c484d13f63e87)

Please review it again

**Review by yxieca — APPROVED** [review]

**Review by jleveque — APPROVED** [review]

**Pull request merged**
