### PR TITLE
[Arista] Update configurations for 7800R3A-36D2

### PR DESCRIPTION
**Pull request by Staphylo**
#### Why I did it

This linecard runs in multi-asic mode and therefore needs the `use_pcie_id_chassis` file to work properly.
The `default_sku` file was also missing which would break the boot when no minigraph is provided.

#### Description for the changelog

Add missing `default_sku` and `use_pci_id_chassis` configs for `7800R3A-36D2`

### CODE REVIEW

**Review by lizhuhuams — DISMISSED** [review]
look good.

**Comment by Staphylo** [comment]
@arlakshm

**Comment by kenneth-arista** [comment]
@arlakshm gentle reminder to review and merge. All is ready.

**Review by arlakshm — APPROVED** [review]

**Pull request merged**
