### PR TITLE
added files to create SKU Mellanox-SN3800-C64

### PR DESCRIPTION
**Pull request by madhanmellanox**
- What I did
Created all the relevant files to modify SKU Mellanox-SN3800-C64

- How I did it
Created all the SKU related files using a XML file provided and a sonic_sku_create.py script to generate the files.

- How to verify it
Load the new HWKU related config using follow command and reload the config.
sudo sonic-cfggen --preset l2 -p -H -k Mellanox-SN3800-C64 > /tmp/newconfig
sudo cp /tmp/newconfig /etc/sonic/config_db.json
sudo config reload
show interfaces status

- Description for the changelog
Created SKU related files buffers_defaults_t0.j2, buffers_defaults_t1.j2, buffers.json.j2, pg_profile_lookup.ini, port_config.ini, qos.json.j2, sai_3800.xml and sai.profile.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by prsunny** [comment]
I thought this is same as ACS-MSN3800 and this should only be a "symlink". I believe you duplicated all files from ACS-MSN3800 or is it different?

**Comment by madhanmellanox** [comment]
> I thought this is same as ACS-MSN3800 and this should only be a "symlink". I believe you duplicated all files from ACS-MSN3800 or is it different?

It is same as files of ACS-MSN3800. But, when we create symlink and then try to set the HWSKU on the switch, it does not work properly. That is why I created physical files instead of symlinks.

**Comment by prsunny** [comment]
> > I thought this is same as ACS-MSN3800 and this should only be a "symlink". I believe you duplicated all files from ACS-MSN3800 or is it different?
> 
> It is same as files of ACS-MSN3800. But, when we create symlink and then try to set the HWSKU on the switch, it does not work properly. That is why I created physical files instead of symlinks.

Please check [this](https://github.com/Azure/sonic-buildimage/tree/master/device/mellanox/x86_64-mlnx_msn2700-r0) - Mellanox-SN2700 is a symlink

**Comment by prsunny** [comment]
Why is it not a symlink?

**Comment by madhanmellanox** [comment]
> Why is it not a symlink?

Nowhere in the SKUs, port_config.ini, sai.profile, sai_xxx.xml is a symlink. Otherwise, we will have problems loading the HWSKU.

**Comment by prsunny** [comment]
> > Why is it not a symlink?
> 
> Nowhere in the SKUs, port_config.ini, sai.profile, sai_xxx.xml is a symlink. Otherwise, we will have problems loading the HWSKU. Rest of all other files, I have made it as symlink.

Did you check the link I shared for 2700? How is that working?

**Comment by madhanmellanox** [comment]
Not sure, if the whole directory is itself a symlink. I will modify my fix to be the same.

**Comment by prsunny** [comment]
@sschlafman, can you sign off?

**Comment by madhanmellanox** [comment]
retest vsimage please

**Comment by prsunny** [comment]
Looks different from this [PR ](https://github.com/Azure/sonic-buildimage/pull/1169/files)- can you confirm it is working with the symlink?

**Pull request merged**
