### PR TITLE
[Mellanox] Add support of SN5600 platform on top of Nvidia ASIC simulation

### PR DESCRIPTION
**Pull request by raphaelt-nvidia**
Signed-off-by: Raphael Tryster <raphaelt@nvidia.com>

#### Why I did it

Add new Spectrum-4 system support SN5600 on top of Nvidia ASIC simulator.

#### How I did it

Add all relevant system and simulator SKU.
Updated syseeprom.hex and related directories to reflect Nvidia SN5600 brand name.

#### How to verify it

Tested init flow, basic show commands, up interfaces, traffic test.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog

Support Nvidia SN5600 simulation.

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by judyjoseph** [comment]
Please raise a new PR for 202111 branch, as this patch cannot be cleanly cherry-picked.

**Comment by raphaelt-nvidia** [comment]
New PR for 202111 branch: https://github.com/Azure/sonic-buildimage/pull/9656

**Comment by raphaelt-nvidia** [comment]
This is the PR for 202111: https://github.com/Azure/sonic-buildimage/pull/9656.  Several of the checkers fail, and there is another PR for the same branch with the same failures in sonic_yang_ext.py: https://github.com/Azure/sonic-buildimage/pull/9654.

Raphael Tryster
Staff Engineer, Software

**Pull request merged**
