### PR TITLE
[DellEMC S6000]: Move fan control to thermalctld from fancontrol.sh

### PR DESCRIPTION
**Pull request by ArunSaravananBalachandran**
#### Why I did it

To implement fan control using thermalctld in DellEMC S6000 platform

**Requires:** Azure/sonic-linux-kernel#241

#### How I did it

- Add thermal policies in 'thermal_policy.json'
- Implemented thermal_manager.py and the necessary modules to perform fan control via thermalctld
- Removed fancontrol.sh

#### How to verify it

Verified that the fan speeds are set based on the fan and temperature status.
Logs: [S6000_fan_control_test_logs.txt](https://github.com/Azure/sonic-buildimage/files/6264419/S6000_fan_control_test_logs.txt)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Review by jleveque — CHANGES_REQUESTED** [review]
Please remove unused import per LGTM

**Comment by ArunSaravananBalachandran** [comment]
> Please remove unused import per LGTM

Removed the unused import.

**Comment by ArunSaravananBalachandran** [comment]
Please do not merge before Azure/sonic-linux-kernel#241 is available in src/sonic-linux-kernel module.

**Comment by ArunSaravananBalachandran** [comment]
As part of Azure/sonic-linux-kernel#241 (available in master branch) max6620 driver alarm behavior and the hwmon sysfs path have been changed. Will add a new commit to handle the driver changes.

Please do not merge this PR until the commit has been added.

**Comment by ArunSaravananBalachandran** [comment]
@sujinmkang, have pushed a commit with the changes based on the updated max6620 driver

**Comment by sujinmkang** [comment]
@ArunSaravananBalachandran can you please check the LGTM?

**Comment by ArunSaravananBalachandran** [comment]
> @ArunSaravananBalachandran can you please check the LGTM?

Have pushed a new commit to resolve the LGTM alerts

**Review by sujinmkang — APPROVED** [review]

**Pull request merged**
