### PR TITLE
[device/celestica]: Add xcvrd event support for Seastone-DX010

### LINKED ISSUE #5853: [Celestica] PMon error
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
```
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd Process Process-1:
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd Traceback (most recent call last):
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd   File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd     self.run()
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
syslog.80.gz:Nov  7 11:47:08.067304 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd     self._target(*self._args, **self._kwargs)
syslog.80.gz:Nov  7 11:47:08.067371 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd   File "/usr/local/bin/xcvrd", line 963, in task_worker
syslog.80.gz:Nov  7 11:47:08.067371 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd     status, port_dict = _wrapper_get_transceiver_change_event(timeout)
syslog.80.gz:Nov  7 11:47:08.067371 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd   File "/usr/local/bin/xcvrd", line 184, in _wrapper_get_transceiver_change_event
syslog.80.gz:Nov  7 11:47:08.067371 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd     return platform_sfputil.get_transceiver_change_event(timeout)
syslog.80.gz:Nov  7 11:47:08.067371 str2-dx010-acs-6 INFO pmon#supervisord: xcvrd AttributeError: 'SfpUtilHelper' object has no attribute 'get_transceiver_change_event'
syslog.80.gz:Nov  7 11:47:09.283457 str2-dx010-acs-6 WARNING pmon#thermalctld: Fan fault warning: PSU-1 FAN-1 is broken.
syslog.80.gz:Nov  7 11:47:09.340973 str2-dx010-acs-6 WARNING pmon#thermalctld: Insufficient number of working fans warning: 1 fans are not working.
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- Why I did it**
- The xcvr service requires an event detection function, unplug or plug in the transceiver.

Fix #5853

**- How I did it**
- Add sysfs interrupt to notify userspace app of external interrupt
- Implement get_change_event() in chassis api.

**- How to verify it**
- Verify xcvrd running with error in syslog
- Verify port status and port information with this following command
  - `show interfaces status`
  - `show interfaces transceiver eeprom`
- Log : [xcvrd.log](https://github.com/Azure/sonic-buildimage/files/5534763/xcvrd.log)

**Signed-off-by**: Wirut Getbamrung [wgetbumr@celestica.com]

### CODE REVIEW

**Comment by mudsut4ke** [comment]
retest broadcom please

**Comment by mudsut4ke** [comment]
retest baseimage please

**Comment by lguohan** [comment]
can you verify if xrcvd is running ok or not?

**Comment by mudsut4ke** [comment]
> can you verify if xrcvd is running ok or not?

@lguohan, I compiling a test image 
After verified , I will mark this PR to ready to review

**Comment by lguohan** [comment]
retest broadcom please

**Review by jleveque — DISMISSED** [review]

**Comment by mudsut4ke** [comment]
ref: https://github.com/Azure/sonic-buildimage/commit/a98cf22162d7edbfdbe4753da7900e9d4279b441
retest broadcom please

**Comment by mudsut4ke** [comment]
retest broadcom please

**Comment by lguohan** [comment]
is this tested?

**Comment by mudsut4ke** [comment]
> is this tested?

@lguohan , I found this error on xcvrd

 Screenshot from 2020-11-13 11-28-56

It cause by missing mapping of logical port names to ASIC instance on device that used platform.json
So, I submit another PR to fix it : https://github.com/Azure/sonic-platform-common/pull/141

**Comment by lguohan** [comment]
@mudsut4ke, now the Azure/sonic-platform-common#141 has been merge. can you resolve the conflict for this pr?

**Comment by mudsut4ke** [comment]
> @mudsut4ke, now the [Azure/sonic-platform-common#141](https://github.com/Azure/sonic-platform-common/pull/141) has been merge. can you resolve the conflict for this pr?

@lguohan , those file are conflict because of this change https://github.com/Azure/sonic-buildimage/pull/5926
So, After resolved the conflict I will re-verify an image again

**Comment by lguohan** [comment]
retest baseimage please

**Review by lguohan — APPROVED** [review]

**Review by jleveque — APPROVED** [review]

**Pull request merged**
