### PR TITLE
[202205][Tunnel PFC] render remap property for tunnel PFC

### PR DESCRIPTION
**Pull request by yxieca**
#### Why I did it

Cherry-picking #10962 due to master PR test difficulties.

Replace the config.bcm file with j2 template file
- Add 'sai_remap_prio_on_tnl_egress=1' property when device metadata local
- Host subtype is 'dualtor'
- Change sai.profile for the new config.bcm.j2

#### How to verify it
Local build with this change has passed.

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Review by richardyu-ms — APPROVED** [review]

**Comment by yxieca** [comment]
This PR is no longer needed. I've already cherry-picked #10962 to 202205 branch. Leaving it open to debug PR tests.

**Comment by yxieca** [comment]
Cherry-pick is done.

**Pull request closed without merging**
