### PR TITLE
[sonic-utilities] Update submodule

### PR DESCRIPTION
**Pull request by madhanmellanox**
**- Why I did it**
Updating submodule for sonic-utilities to get the changes to Azure master. The following were the commits that were part of this submodule.

[celestica] consutil to support customize tty device name (#1155) 3a7457c72a01ff7ddb2c55bbabea54b7ed45e816

Fix exception for ipaddress in python2 (#1164)	059cdca94d9fc88df6e3f05e050ea3c535be2871

[watermarkstat] Add unit tests for watermarkstat show commands (#1157)  a733df5dc33a3cf20d876da5db2464e2474362de

[consutil] Fix issue where the show line command crash if no ttyUSB exists (#1173)  e51d44f2832a3ff6b964e7e6110a1db49b5745b3

[config/console] Support update console configuration related commands (#1166)  c382d8940a6618bd33ef7f7e0b11fb56e84e5c46

Modify fast-reboot script to use BGP service script to stop bgp service (#1177)  c395e14c395eeb1ed2312a52e6e47449efa4d910

[consutil] Add brief option to show line command (#1176)  510d0ad5349340879a75847cecf55f4bc8f085ae

[config/show] Add CLI support for proxy arp (#1168)  59a511d3855cc151b510201e1aaefb33d0b8a8a5

Fixes the issue with show interface counters and for pfc and queue counters. (#1180)  13bd06be696fc14663ddfe5bb6c19abb9b647759

[counterpoll] Disable Counter Poll When Entering Fast Reboot (#1174)  ca92e36faf5496a4fec23fbd6ad475dcfbaec370

Remove stdeb.cfg; no longer used now that we build as wheel (#1182)  0c3a97f180a07c0a5f921c7b4fd0e4df2c030664

fdbshow and nbrshow use SonicV2Connector with decode_responses=True, and remove all the decode() (#1187)   00a25705c9bc07719667ae7adf98f39cbd450871

[CLI][show][platform] Added ASIC count in the output. (#1185)  f14bbe527b41b8ae856d2086fa8754e31f413118

[fwutil]: Set min log priority to INFO. (#1191)  e8892127260e1da50e3ae1385612d57021ca50ef

Add license file, remove third-party licenses file (#1192)  63c6733ffd642ca8ad29573f04082c2dc836dd22

[show] remove 'device2interface_dict' in show interface neighbor expected (#1188)  1753f225fa2ee4afe1a147c1db66298fad0405fc

Show FG_NHG CLI Commands Added (#1056)  8af9aeed753c438d08cc3315b7c788af9dda62e6

[sfputil] Display 'N/A' for non-SFP ports (#1078)  ef5f21231f97277b253d7eb10370a8549848344d

[consutil] Store console port state in STATE_DB (#1208)   e3d3d92bb06595f1a669f97be72caa906fe50cf5

Add a switch to route_check to control whether write log to syslog (#1215)  acfa8248d79970e4d0225dd08082dc8f85ad030d

[show/fgnhg.py] Fix whitespace issues (#1211)  061f428d19bbd9e02b6a08ca5f3fb243543e7fb5

SONiC installer - fix string formatting during image type check (#1197)  42efc0316f990a5232e08e10340a04dcec51216f

[Mellanox] SKU creator Tool (#1163)  99de1678e25fd8499dadb2044802a1b6ab388b50

**- How I did it**
Merged sonic-utilities changes for SKU creator tool to Azure master. Now, updating the submodule changes.

**- How to verify it**
Use SKU creator tool to create port_config.ini file from xml file or Minigraph file which contains SKU definition.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [x] 201911
- [ ] 202006

**- Description for the changelog**

This changeset contains relevant python script files for SKU creator tool.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Retest baseimage please

**Comment by lguohan** [comment]
what is the error here? @madhanmellanox , can you investigate?

**Comment by lguohan** [comment]
we cannot cherry-pick submodule the way as it is. please generate submodule update for 201911 branch seperately.

**Comment by lguohan** [comment]
please use rebase other than merge. it is unclear what your changes are now.

**Comment by madhanmellanox** [comment]
@lguohan I tried to restore back to previous working commit f506c9a42aab0d86709bcbe87cfedf15371dc79d in this branch, but I am getting errors while pushing the commit. I may need help.

**Comment by jleveque** [comment]
Closing. Superseded by https://github.com/Azure/sonic-buildimage/pull/5849

**Pull request closed without merging**
