### PR TITLE
[barefoot] add platform.json and hwsku.json for Newport

### PR DESCRIPTION
**Pull request by mykolaxgerasymenko**
Signed-off-by: Mykola Gerasymenko <mykolax.gerasymenko@intel.com>

#### Why I did it
To support dynamic port breakout configurations on Newport platforms.

#### How I did it
Add platform.json and hwsku.json for dynamic port breakout usage.

#### How to verify it
Manually tested DPB CLI on Newport platform with all modes.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by mykolaxgerasymenko** [comment]
@lguohan  @praveen-li @akokhan please review.

**Comment by mykolaxgerasymenko** [comment]
@praveen-li @akokhan Please review.

**Review by akokhan — APPROVED** [review]

**Comment by mykolaxgerasymenko** [comment]
@lguohan Please review and merge.

**Comment by mykolaxgerasymenko** [comment]
@lguohan Please review and merge.

**Pull request merged**
