### PR TITLE
[Submodule] Update src/sonic-py-swsssdk

### PR DESCRIPTION
**Pull request by liuh-80**
Updating sonic-utilities sub module with the following commits

ca785a2 Remove sonic-db-cli

#### Why I did it
To fix sonic-db-cli high CPU usage on SONiC startup issue: https://github.com/Azure/sonic-buildimage/issues/10218
sonic-db-cli re-write with c++ and move to sonic-swss-common repo.

#### Description for the changelog
ca785a2 Remove sonic-db-cli

### CODE REVIEW

**Comment by qiluo-msft** [comment]
This is a disruptive change. If we found it bad in case in future, we need to revert.

**Review by qiluo-msft — APPROVED** [review]

**Comment by lguohan** [comment]
can you provide motiviation, what is the benefit of switching to sonic-db-cli c++ implementation, how much gain are we seeing here?

**Comment by liuh-80** [comment]
> can you provide motiviation, what is the benefit of switching to sonic-db-cli c++ implementation, how much gain are we seeing here?
This change is for following issue:
"sonic-db-cli high CPU usage on SONiC startup"
https://github.com/Azure/sonic-buildimage/issues/10218

**Comment by qiluo-msft** [comment]
Please check the test failure
```
host = <MultiAsicSonicHost vlab-01>
cmd = "sonic-db-cli   APPL_DB HGETALL 'MACSEC_PORT_TABLE:Ethernet8'"

    def sonic_db_cli(host, cmd):
>       return ast.literal_eval(host.shell(cmd)["stdout_lines"][0])
E       IndexError: list index out of range

cmd        = "sonic-db-cli   APPL_DB HGETALL 'MACSEC_PORT_TABLE:Ethernet8'"
host       = <MultiAsicSonicHost vlab-01>
```

**Comment by liuh-80** [comment]
> Please check the test failure
> 
> ```
> host = <MultiAsicSonicHost vlab-01>
> cmd = "sonic-db-cli   APPL_DB HGETALL 'MACSEC_PORT_TABLE:Ethernet8'"
> 
>     def sonic_db_cli(host, cmd):
> >       return ast.literal_eval(host.shell(cmd)["stdout_lines"][0])
> E       IndexError: list index out of range
> 
> cmd        = "sonic-db-cli   APPL_DB HGETALL 'MACSEC_PORT_TABLE:Ethernet8'"
> host       = <MultiAsicSonicHost vlab-01>
> ```

Download image from pipeline and test on devbox passed will continue check reason.

**Comment by liuh-80** [comment]
This PR blocked by a bug in new sonic-db-cli when handle hget commands, will create another PR to fix it.

**Comment by yxieca** [comment]
Reverted from 202205 branch due to PR test failures.

**Pull request merged**
