### PR TITLE
[frr]: Move to version 7.2

### PR DESCRIPTION
**Pull request by pavel-shirshov**
**- What I did**
Moved to frr 7.2

**- How I did it**
Changed frr sources and adapted patches

**- How to verify it**
Build an image and run it on your dut

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
@tylerlinp I've removed 0005-Support-VRF.patch from the patchset. I see that https://github.com/Azure/sonic-frr/pull/15 you asked for RT_TABLE_COMPAT instead of RT_TABLE_UNSPEC from frr team. You referred to fpmsyncd compatibility. Is it still valid? Should I add an extrapatch for frr 7.2?
Thanks

**Comment by tylerlinp** [comment]
@pavel-shirshov It doesn't matter RT_TABLE_UNSPEC or RT_TABLE_COMPAT, it would be ignored, so there is no need to change it again. Yes, a new patch is needed in frr 7.2 to revert the table_id to vrf_id. Now fpmsyncd codes are basing on vrf_id.

This is the part to revert:
@@ -224,14 +224,17 @@ static int netlink_route_info_fill(netlink_route_info_t *ri, int cmd,
				   rib_dest_t *dest, struct route_entry *re)
{
	struct nexthop *nexthop;
+	struct zebra_vrf *zvrf;

	memset(ri, 0, sizeof(*ri));

	ri->prefix = rib_dest_prefix(dest);
	ri->af = rib_dest_af(dest);

	ri->nlmsg_type = cmd;
-	ri->rtm_table = zvrf_id(rib_dest_vrf(dest));
+	zvrf = rib_dest_vrf(dest);
+	if (zvrf)
+		ri->rtm_table = zvrf->table_id;
	ri->rtm_protocol = RTPROT_UNSPEC;

**Comment by pavel-shirshov** [comment]
@tylerlinp Thank you for your prompt reply.
Would it be better to change fpmsyncd to use table_id?
So we can use standard frr?
Thanks

**Comment by pavel-shirshov** [comment]
retest vs please

**Comment by lguohan** [comment]
there are a few patches removed? can you explain why? because they are included in the frr 7.2?

**Comment by pavel-shirshov** [comment]
Yes. All other patches are parts of FRR 7.2 now.

**Comment by lguohan** [comment]
@tylerlinp , can you follow up on Pavel's question?

**Comment by tylerlinp** [comment]
> @tylerlinp Thank you for your prompt reply.
> Would it be better to change fpmsyncd to use table_id?
> So we can use standard frr?
> Thanks

In my oponion using vrf_id is better. If to use table_id, it will get much more work and loss of efficiency. It is a subject deserved to discuss.

**Pull request merged**
