### PR TITLE
[Arista] Driver and platform update

### PR DESCRIPTION
**Pull request by Staphylo**
- Add support for `DCS-7050SX3-48YC8` and `DCS-7050SX3-48C8` platform
 - Add support for more variants of `DCS-7280CR3-32[PD]4`
 - Add Supervisor to Linecard consutil support
 - Complete Watchdog platform API support
 - Fix some PSU behavior on `DCS-7050QX-32` and `DCS-7060CX-32S`
 - Fix SEU management on `DCS-7060CX-32S`
 - Allow kernel modules to build up to linux 5.10
 - Rename led color `orange` to `amber`
 - Miscellaneous fixes

### CODE REVIEW

**Comment by Staphylo** [comment]
retest vsimage please

**Comment by lguohan** [comment]
do we need these in 202012 branch?

Complete Watchdog platform API support
Fix some PSU behavior on DCS-7050QX-32 and DCS-7060CX-32S
Miscellaneous fixes

**Comment by Staphylo** [comment]
Yes we do want this change on 202012 as well.
I was planning on making a dedicated PR for this since the submodule update is problematic for cherry-picking I believe.

**Review by jleveque — APPROVED** [review]

**Comment by Staphylo** [comment]
@jleveque anything I should be doing here?

**Comment by jleveque** [comment]
> @jleveque anything I should be doing here?

It looks like something went awry with the Azure Pipelines check builds. I will try re-running them. If they still don't run, you can try closing and reopening the PR.

**Pull request merged**
