### PR TITLE
[build]: Add possibility to override dockerd config file for multiarch builds.

### LINKED ISSUE #8898: [Bug] [Build] DOCKERD for march cmd fails when there are conflicting directives in /etc/docker/daemon.json
#### Steps to reproduce the issue:
1.  Check if there is a /etc/docker.daemon.json file and if not create one on the build server
2.  Add a directive for data-root
```
{
    "data-root": "/build/docker",
    ............
}
```
3. Run make config and try to build for a cross-architecture target.
4. Run this:
`NOJESSIE=1 NOSTRETCH=1 make docker-start`

#### Describe the results you received:

```
+++ --- Making docker-start --- +++
BLDENV=buster make -f Makefile.work docker-start
multiarch docker not found ...
Unable to find image 'multiarch/qemu-user-static:register' locally
register: Pulling from multiarch/qemu-user-static
d60bca25ef07: Pull complete 
7045fbe28d35: Pull complete 
ed8a5179ae11: Pull complete 
1ec39da9c97d: Pull complete 
Digest: sha256:0434e870ebbe9d28d254c1e65b46969bef458490be5df04d3266ef87380518e2
Status: Downloaded newer image for multiarch/qemu-user-static:register
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc-static as binfmt interpreter for sparc
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-sparc64-static as binfmt interpreter for sparc64
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Setting /usr/bin/qemu-or1k-static as binfmt interpreter for or1k
Killing march docker 
setfacl: /var/run/march/docker.sock: No such file or directory
Starting docker build service...
setfacl: /tmp/d/d/var/run/docker.sock: No such file or directory
SONiC Build System

Build Configuration
.......................
"MULTIARCH_QEMU_ENVIRON"          : "y"
....................

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
```

Unfortunately, the actual error is not captured and is not written to stdout and thus the above output might not explicitly suggest what went wrong from the first glance

#### Describe the results you expected:

This shouldn't be seen

#### Triage:

Other useful internal commands to know about which are used internally in the Makefile.work:

**CMD which starts the slave docker:** 
```
docker run --rm=true --privileged --init -v <build_dir>:/sonic -w /sonic -e http_proxy= -e https_proxy= -e no_proxy= -it -v /var/cache/sonic/artifacts:/dpkg_cache:rw -v /var/run/march/docker.sock:/var/run/docker.sock -v /var/run/march/docker.pid:/var/run/docker.pid -v /var/run/march/docker:/var/run/docker -v /var/lib/march/docker:/var/lib/docker`
```

As you can see, this expects a working `/var/run/march/docker.pid and /var/run/march/docker.sock` on the build server

**CMD which starts the docker daemon for building Cross-Arch Docker targets inside the slave docker:** 
This command fails to start a new dockerd process and the error log is attached and should be self-explanatory
```
root@build-server:<build_dir>$ dockerd --experimental=true --storage-driver=vfs --data-root=/var/lib/march/docker --exec-root=/var/run/march/docker/ -H unix:///var/run/march/docker.sock -p /var/run/march/docker.pid
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: data-root: (from flag: /var/lib/march/docker, from file: /builds2/docker)
```

#### Workaround:

add a `--config-file=` to the docker daemon start command, which then doesn't bother about what is in the daemon.json file

```
     SONIC_SERVICE_DOCKERD_FOR_MULTIARCH=y
-    SONIC_NATIVE_DOCKERD_FOR_MUTLIARCH := dockerd  --experimental=true --storage-driver=vfs \
+    SONIC_NATIVE_DOCKERD_FOR_MUTLIARCH := dockerd --config-file= --experimental=true --storage-driver=vfs \

     SONIC_NATIVE_DOCKERD_FOR_DOCKERFS := rm -fr $(PWD)/dockerfs; mkdir -p $(PWD)/dockerfs; sudo rm -fr /tmp/d; mkdir -p /tmp/d; ln -s -f $(PWD)/dockerfs $(D_ROOT); \
-                                       sudo dockerd --storage-driver=overlay2 --iptables=false \
+                                       sudo dockerd --config-file= --storage-driver=overlay2 --iptables=false \


```

#### Potential Solution:

IMO, the dockerd process should not be started by the Makefile.work itself. It should already be running on the build server and the Makefile can mount the running pid and sock files inside the slave docker 

This is how the non-cross architecture builds operate. They doesn't kill/start a dockerd process but instead leverages the process which is already running on the build server

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
#### Why I did it
Fixes #8898 

Dockerd for multiarch build by default use host OS config file ("/etc/docker/daemon.json").
Default configuration used on host OS may not work for containers run inside sonic-slave.
"DOCKER_CONFIG_FILE_FOR_MULTIARCH" variable allows overriding path to the
config file that will be used for multiarch dockerd.

#### How I did it

Added "DOCKER_CONFIG_FILE_FOR_MULTIARCH" to Makefile.work file that allow to
override path to dockerd config file through environment variable:
```
DOCKER_CONFIG_FILE_FOR_MULTIARCH=${path_to_file}/daemon.json   make ...
```
If the env variable is not set build the system preserves its default behavior.

#### How to verify it
- Set DOCKER_CONFIG_FILE_FOR_MULTIARCH env variable
- Run build
- While build is running execute `ps -eo pid,cmd | grep "[0-9] dockerd.*march"` command
- Verify that `--config-file` parameter is set to the same path that was specified in DOCKER_CONFIG_FILE_FOR_MULTIARCH variable.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by vivekreddynv** [comment]
Fixes https://github.com/Azure/sonic-buildimage/issues/8898

**Comment by liat-grozovik** [comment]
@xumia could you please help to review or suggest someone else?

**Comment by qiluo-msft** [comment]
@xumia Could you check?

**Review by xumia — APPROVED** [review]

**Pull request merged**
