### PR TITLE
[sonic-platform-common] Install Python 3 package in host OS and PMon container

### PR DESCRIPTION
**Pull request by vboykox**
Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>

**- Why I did it**
To include python 3 sonic-platform-common into SONiC image

**- How to verify it**
`ls /usr/local/lib/python3.7/`

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

### CODE REVIEW

**Comment by vboykox** [comment]
@jleveque

**Comment by jleveque** [comment]
@vboykox: Thanks for opening this PR! Is it ready for merge? I saw "WIP" in the title, so I wanted to wait for an update from you.

**Comment by vboykox** [comment]
@jleveque yes, the PR is ready for merge

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
@vboykox: The Python 3 sonic-platform-common package will also need to be installed in the [PMon container](https://github.com/Azure/sonic-buildimage/blob/master/rules/docker-platform-monitor.mk). Do you intend to do this in a separate PR?

**Review by jleveque — APPROVED** [review]

**Comment by vboykox** [comment]
> @vboykox: The Python 3 sonic-platform-common package will also need to be installed in the [PMon container](https://github.com/Azure/sonic-buildimage/blob/master/rules/docker-platform-monitor.mk). Do you intend to do this in a separate PR?

Thanks for pointing that out

**Comment by lguohan** [comment]
retest baseimage please

**Comment by jleveque** [comment]
@vboykox: The Docker container install of the Python 3 wheel is failing. The issue is it's trying to install a Python 3 wheel using Python 2 pip. This is because the Dockerfile is using a macro from dockers/dockerfile-macros.j2, but the macro needs to be updated to be smarter. In the meantime, I suggest you update this section https://github.com/Azure/sonic-buildimage/blob/master/dockers/docker-platform-monitor/Dockerfile.j2#L45 to work like the change I made here: https://github.com/Azure/sonic-buildimage/blob/master/platform/vs/docker-sonic-vs/Dockerfile.j2#L109.

I can work on updating the macro in the future.

**Comment by vboykox** [comment]
retest mellanox please

**Comment by vboykox** [comment]
retest broadcom please

**Review by jleveque — APPROVED** [review]

**Pull request merged**
