### PR TITLE
[Mellanox] Implement new platform API for SONiC physical entity mib extension

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**- Why I did it**

In order to support SONiC physical entity mib extension, a few new platform API are added to sonic-platform-common, this PR is to provide an mellanox platform implementation for those new APIs.

**- How I did it**

Implement all new APIs.

**- How to verify it**

Manual tests on MSN2410.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
The LGTM check shows "10 for Wrong number of arguments in a class instantiation", actually it is missreport. It checks non-mellanox API with mellanox code change.

**Comment by jleveque** [comment]
Please fix conflicts

**Comment by Junchao-Mellanox** [comment]
The LGTM warning is not a real issue.

**Comment by Junchao-Mellanox** [comment]
retest broadcom please

**Review by keboliu — APPROVED** [review]

**Comment by keboliu** [comment]
@jleveque would you please help to check? this PR is to support the new physical Entity MIB.

**Review by jleveque — APPROVED** [review]

**Pull request merged**
