### PR TITLE
[sonic-slave]: Ignore old certificates in apt.

### PR DESCRIPTION
**Pull request by marian-pritsak**
Signed-off-by: marian-pritsak <marianp@mellanox.com>

### CODE REVIEW

**Comment by marian-pritsak** [comment]
Tried to rebuild sonic slave and got this error:
```
make sonic-slave-build
...
Get:9 http://debian-archive.trafficmanager.net jessie/updates/non-free Sources [20 B]

E: Release file for http://debian-archive.trafficmanager.net/debian/dists/jessie-backports/InRelease is expired (invalid since 2d 4h 45min 34s). Updates for this repository will not be applied.

The command '/bin/sh -c apt-get clean && apt-get update && apt-get install -y  apt-utils default-jre-headless openssh-server curl wget unzip git build-essential libtool lintian' returned a non-zero code: 100
```

**Comment by paulnice** [comment]
I don't like this. It will solve the problem, but it will introduce a security problem in our build process. I think we need to contact repo managers and ask them to fix their repo.

**Comment by pavel-shirshov** [comment]
I don't like this. It will solve the problem, but it will introduce a security problem in our build process. I think we need to contact repo managers and ask them to fix their repo.

**Comment by NStetskovych** [comment]
Observed for ONE image build too:
Ign http://debian-archive.trafficmanager.net jessie InRelease
Get:1 http://debian-archive.trafficmanager.net jessie/updates InRelease [63.1 kB]
Get:2 http://debian-archive.trafficmanager.net jessie Release.gpg [2373 B]
E: Release file for http://debian-archive.trafficmanager.net/debian-security/dists/jessie/updates/InRelease is expired (invalid since 1h 9min 31s). Updates for this repository will not be applied.
+ sudo umount ./fsroot/proc
+ true
slave.mk:304: recipe for target 'target/sonic-cavium.bin' failed
make: Leaving directory '/sonic'
Makefile:32: recipe for target 'target/sonic-cavium.bin' failed
make: *** [target/sonic-cavium.bin] Error 2

**Comment by lguohan** [comment]
ack pavel, then should we change to another jessie-backports repo?

deb http://ftp.debian.org/debian jessie-backports main

**Comment by lguohan** [comment]
@NStetskovych, is the error on your local build?

**Comment by NStetskovych** [comment]
@lguohan yes, not in CI.

**Comment by lguohan** [comment]
is it this issue https://github.com/Azure/sonic-buildimage/issues/411

**Comment by marian-pritsak** [comment]
Issue no longer reproduces

**Pull request closed without merging**
