### PR TITLE
[docker-orchagent]: Add vrfmgrd to supervisorctl

### PR DESCRIPTION
**Pull request by marian-pritsak**
Signed-off-by: Marian Pritsak <marianp@mellanox.com>

### CODE REVIEW

**Comment by marian-pritsak** [comment]
Depends on https://github.com/Azure/sonic-swss/pull/621

**Comment by lguohan** [comment]
also need this one in vs docker.

**Comment by lguohan** [comment]
https://github.com/Azure/sonic-buildimage/tree/master/platform/vs/docker-sonic-vs

**Comment by lguohan** [comment]
can you include in this PR?

Azure/sonic-swss#621

**Pull request merged**
