### PR TITLE
[202012][swss-common][swss] Submodule update

### PR DESCRIPTION
**Pull request by stephenxs**
#### Why I did it

Update sonic-swss-common

54879741 [202012][schema] Add vnet route tunnel and advertise network tables for state_db (Azure/sonic-swss-common#563)
a5394f9d Update for BFD, default route table (Azure/sonic-swss-common#550)

Update sonic-swss

fbbe5bcc [202012][pfc_detect] fix RedisReply errors (Azure/sonic-swss#2078)
5762b0c2 [Reclaim buffer][202012] Reclaim unused buffer for dynamic buffer model (Azure/sonic-swss#1985)
33e9bd19 [Document][202012] Supply the missing ingress/egress port profile list in document (Azure/sonic-swss#2066)
1b6ffba1 [Reclaiming buffer][202012] Support reclaiming buffer in traditional buffer model (Azure/sonic-swss#2063)
afb33f16 [202012] Update default route status to state DB (Azure/sonic-swss#2009) (Azure/sonic-swss#2067)
b9c44f75 Common code update for reclaiming buffer (backport community PR Azure/sonic-swss#1996 to 202106/202012) (Azure/sonic-swss#2061)
cf5182d8 [request parser] Allow request parser to parse multiple values

Signed-off-by: Stephen Sun <stephens@nvidia.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by stephenxs** [comment]
Both t0 and t1-lag tests were failed due to the host unreachable during `test_collect_techsupport` test.
```
2021-12-15T21:00:30.1409842Z         # Raise exception if host(s) unreachable
2021-12-15T21:00:30.1410931Z         # FIXME - if multiple hosts were involved, should an exception be raised?
2021-12-15T21:00:30.1411322Z         if cb.unreachable:
2021-12-15T21:00:30.1411888Z >           raise AnsibleConnectionFailure("Host unreachable", dark=cb.unreachable, contacted=cb.contacted)
2021-12-15T21:00:30.1412379Z E           AnsibleConnectionFailure: Host unreachable
```

**Comment by stephenxs** [comment]
Notice that there is a sonic-utilities commit where show tech support stuff is updated. Revert it for now as there are show tech support related issues in both topo.

**Comment by stephenxs** [comment]
kvmtest-t0 test_dhcpv6_relay_counter failed.
fields in DHCPv6_COUNTER_TABLE table were zero but non-zero was expected

**Comment by stephenxs** [comment]
@qiluo-msft can you please help check the dhcp relay failure? This is not related to the PR. It also failed other PRs.

**Comment by stephenxs** [comment]
Blocked by #9572

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
