### PR TITLE
[minigraph] Check for null VLAN MAC

### PR DESCRIPTION
**Pull request by theasianpianist**
Signed-off-by: Lawrence Lee <lawlee@microsoft.com>

Fixes #7874

#### Why I did it
Null VLAN MACs will cause SWSS to crash

#### How I did it
Explicitly check for null VLAN MAC before setting it - if it is null, do not set the VLAN MAC attribute

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

#### A picture of a cute animal (not mandatory but encouraged)
image

### CODE REVIEW

**Review by prsunny — DISMISSED** [review]

**Review by yxieca — APPROVED** [review]

**Comment by lguohan** [comment]
can you remove the .swp file?

**Comment by theasianpianist** [comment]
@lguohan whoops, removed

**Review by prsunny — APPROVED** [review]

**Review by tahmed-dev — APPROVED** [review]

**Review by yxieca — APPROVED** [review]

**Pull request merged**
