### PR TITLE
[BFN] Updated platform APIs impl

### PR DESCRIPTION
**Pull request by akokhan**
Signed-off-by: Andriy Kokhan <andriyx.kokhan@intel.com>

#### Why I did it
Added missing implementation for BFN platform APIs

#### How to verify it
Run sonic-mgmt platform TCs

#### Which release branch to backport (provide reason below if selected)
- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by akokhan** [comment]
@qiluo-msft , @lguohan , please approve and merge

**Review by lguohan — DISMISSED** [review]

**Comment by akokhan** [comment]
@lguohan , please merge.

**Comment by akokhan** [comment]
@lguohan , this PR extends platform API implementation for BFN platform. Please approve and merge.

**Comment by akokhan** [comment]
@lguohan , please approve and merge

**Comment by akokhan** [comment]
The following PR includes these changes:
https://github.com/Azure/sonic-buildimage/pull/9540

**Pull request closed without merging**
