### PR TITLE
[swss-common] Update submodule 

### PR DESCRIPTION
**Pull request by mykolaxgerasymenko**
#### Why I did it
Need to update sonic-swss-common submodule to have fixed DPB.

#### How I did it
Update sonic-swss-common submodule.

- fix getting hash from redis db (#465)
- [dbconnector] Initialize redisContext (#464)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by mykolaxgerasymenko** [comment]
please restart

**Comment by mykolaxgerasymenko** [comment]
I pushed with force without changes to restart automatic checks and tests.

**Review by qiluo-msft — APPROVED** [review]

**Comment by allas-nvidia** [comment]
@mykolaxgerasymenko 
Can you please merge it to 202012?
Thanks

**Review by lguohan — APPROVED** [review]

**Comment by daall** [comment]
removing 202012 label as swss-common has its own 202012 branch now

**Pull request merged**
