### PR TITLE
Advance sonic-py-swsssdk pointer

### PR DESCRIPTION
**Pull request by judyjoseph**
**- Why I did it**
Advance sonic-py-swsssdk submodule to latest.

03748ce [MultiDB] add sonic-db-cli SAVE/FLUSHALL option (#69)
f2a7598  [doc]: Update README.md (#70)
581add1 [Multiasic]: Add calculation of interface index for backplane interfaces (#68)

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
retest vs please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by judyjoseph** [comment]
Please don't merge this PR now. The current sonic-py-swsssdk and sonic-snmpagent is already advanced throught this PR https://github.com/Azure/sonic-buildimage/pull/4421.

I am keeping this as a place holder to advance the pointer again after this PR https://github.com/Azure/sonic-py-swsssdk/pull/68, is merged in.

**Comment by lguohan** [comment]
do we still this pr?

**Comment by judyjoseph** [comment]
> do we still this pr?

If you could review this PR https://github.com/Azure/sonic-py-swsssdk/pull/68, and approve if ok. Will update sonic-py-swsssdk in master branch using this PR.

**Comment by lguohan** [comment]
Azure/sonic-py-swsssdk#68 is merged

**Comment by dzhangalibaba** [comment]
could you help advance one more commit in sonic-py-swsssdk for the PING/SAVE/FLUSHALL changes.

 [MultiDB] add sonic-db-cli SAVE/FLUSHALL option (#69)

**Comment by judyjoseph** [comment]
retest this please

**Comment by qiluo-msft** [comment]
@judyjoseph  there is conflict, could you help fix?

**Comment by judyjoseph** [comment]
retest broadcom please

**Comment by dzhangalibaba** [comment]
retest broadcom please

**Pull request merged**
