### PR TITLE
[PINS] update sonic-p4rt docker to bullseye

### PR DESCRIPTION
**Pull request by rhalstea**
#### Why I did it
SONiC is migrating to bullseye. This will update the sonic-pins container to bullseye.

#### How I did it
The [sonic-pins code](https://github.com/Azure/sonic-buildimage/blob/master/rules/p4rt.mk) isn't dependent on any architecture so it will already build successfully for bullseye. This PR updates the docker to use bullseye.

#### How to verify it
Today we cannot build the docker-sonic-p4rt.gz target (e.g. Issue #9885). With this change the docker will build successfully. The P4RT executable will not run, because of a missing runtime library, libgmpxx, which I'll address in a followup PR.

#### Which release branch to backport (provide reason below if selected)
None.

#### Description for the changelog
Update docker-sonic-p4rt.gz target to build with Bullseye instead of Buster.

#### Link to config_db schema for YANG module changes
N/A

### CODE REVIEW

**Comment by bocon13** [comment]
Thanks @rhalstea for working on this!

Here's the fix on the packaging side: https://github.com/Azure/sonic-pins/pull/4
After that's merged, we'll need to just update the submodule.

**Comment by pettershao-ragilenetworks** [comment]
@rhalstea I faced the same build error when I build libsairedis locally, how can I fix this, thanks!:
```
ERROR: invalid type '' for SAI_ACL_COUNTER_ATTR_TABLE_ID
ERROR: flags are not defined for SAI_ACL_COUNTER_ATTR_TABLE_ID
ERROR: FATAL ERROR === MUST FIX === : Can't use an undefined value as an ARRAY reference at parse.pl line 1676.
```

**Comment by rhalstea** [comment]
@pettershao-ragilenetworks I haven't looked into the siaredis issue. This fix is addressing the incompatibilities in the p4rt docker. Have you tried the suggestions in this comment: https://github.com/Azure/sonic-buildimage/issues/9885#issuecomment-1035239310

**Review by lguohan — APPROVED** [review]

**Comment by rhalstea** [comment]
Thanks @lguohan, Is there anything else needed before we merge this?

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
