### PR TITLE
[Python] Migrate applications/scripts to import sonic-py-common package

### PR DESCRIPTION
**Pull request by jleveque**
**- Why I did it**

As part of consolidating all common Python-based functionality into the new sonic-py-common package, this pull request:
1. Redirects all Python applications/scripts in sonic-buildimage repo which previously imported sonic_device_util or sonic_daemon_base to instead import sonic-py-common, which was added in https://github.com/Azure/sonic-buildimage/pull/5003
2. Replaces all calls to `sonic_device_util.get_platform_info()` to instead call `sonic_py_common.get_platform()` and removes any calls to `sonic_device_util.get_machine_info()` which are no longer necessary (i.e., those which were only used to pass the results to `sonic_device_util.get_platform_info()`.
3. Removes unused imports to the now-deprecated sonic-daemon-base package and sonic_device_util.py module

This is the next step toward resolving https://github.com/Azure/sonic-buildimage/issues/4999

Also reverted my previous change in which device_info.get_platform() would first try obtaining the platform ID string from Config DB and fall back to gathering it from machine.conf upon failure because this function is called by sonic-cfggen before the data is in the DB, in which case, the db_connect() call will hang indefinitely, which was not the behavior I expected. As of now, the function will always reference machine.conf.

**- How to verify it**

Test that all affected Python applications/scripts continue to function properly

**- Which release branch to backport (provide reason below if seleted)**

- [ ] 201811
- [ ] 201911
- [x] 202006

### CODE REVIEW

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by jleveque** [comment]
Removed "Request for 201911 Branch" label, as backporting this change and the related changes will most likely be better performed by creating new PRs against the 201911 branch.

**Comment by jleveque** [comment]
Retest vs please

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vs please

**Comment by jleveque** [comment]
Retest vs please

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by jleveque** [comment]
Retest vs please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by lguohan** [comment]
lgtm, one thing you might want to check is the arista platform, they have their platform code in their own directory, I do not know if you grep their directory or not.

**Comment by jleveque** [comment]
> lgtm, one thing you might want to check is the arista platform, they have their platform code in their own directory, I do not know if you grep their directory or not.

Yes. I grepped the entire repo as well as the submodules. Arista is not importing either sonic_device_util or sonic_daemon_base.

**Pull request merged**
