### PR TITLE
 support Debian 9 for nephos platform

### PR DESCRIPTION
**Pull request by simonJi2018**
**- What I did**
1. update sai to 1.3.5 
2. update sdk to support debian 4.9 and  GPL  License
3. update device driver to support debian 4.9 
4. update qos config parameter
5. temporarily removed pegatron device support due to some bug 
**- How I did it**
The relevant files have been modified, like sai.mk sdk.mk , one-image.mk and rules.mk qos.json.j2 ...
**- How to verify it**
have build and test on device
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
where is the gpl license?

**Comment by qiluo-msft** [comment]
Please refine the pull request title. Do you mean support Debian 9 for specific ASIC or platform?

**Comment by simonJi2018** [comment]
> where is the gpl license?
admin@switch1:/lib/modules/4.9.0-7-amd64/extra$ sudo modinfo nps_dev.ko
filename:       /lib/modules/4.9.0-7-amd64/extra/nps_dev.ko
description:    SDK Kernel Module
author:         Nephos
license:        GPL
depends:
retpoline:      Y
vermagic:       4.9.0-7-amd64 SMP mod_unload modversions
admin@switch1:/lib/modules/4.9.0-7-amd64/extra$ sudo modinfo nps_netif.ko
filename:       /lib/modules/4.9.0-7-amd64/extra/nps_netif.ko
description:    NETIF Kernel Module
author:         Nephos
license:        GPL
depends:        nps_dev
retpoline:      Y
vermagic:       4.9.0-7-amd64 SMP mod_unload modversions
parm:           dbg_flag:bit0:Error, bit1:Tx, bit2:Rx, bit3:Intf, bit4:Profile (uint)

**Comment by lguohan** [comment]
can you provide the source code so that we can compile in buildimage.

**Comment by simonJi2018** [comment]
> can you provide the source code so that we can compile in buildimage.

Yes, I need some time to do this. Can the you accept the current pull request first or not ?

**Comment by yxieca** [comment]
Made to 201811 branch on 2019/2/14

**Comment by yxieca** [comment]
Change has been included in 201811 branch long time ago.

**Pull request merged**
