### PR TITLE
[Kubernetes Setup] Removed flannel, kube-proxy images

### PR DESCRIPTION
**Pull request by isabelmsft**
**- Why I did it**
Save disk space on kubernetes-enabled devices

**- How I did it**
Removed installation of kube-proxy (117 MB) and flannel (53 MB) images

**- How to verify it**
I deployed the rebuilt image without Kube-proxy and Flannel on my DUT and joined the DUT to my Kubernetes master in Starlab. I ensured that daemonset deployments successfully go through. I also tested on KVM cluster.

I initialized the master skipping the kube-proxy addon and did not deploy a CNI (eg Flannel). We do not need a CNI, as we do not need to set up k8s pod networking. However, without a CNI like Flannel deployed, the node status shows "NotReady" when you run `kubectl get nodes.`  This does not affect our functionality; pods can still be scheduled on nodes marked NotReady as long as we add a toleration to run on NotReady nodes in daemonset manifest declaration. If we decide we want to change the status to "Ready" for readability purposes, we can look into Kubenet, which is essentially a built-in CNI but would take up less space than Flannel. 

For user verification: Run `docker images` on SONiC, images should not appear

**- Which release branch to backport (provide reason below if seleted)**
- [ ] 201811
- [x] 201911
- [x] 202006

### CODE REVIEW

**Comment by renukamanavalan** [comment]
Can you test the case, where node is really not ready and see what happens, when the node become ready.

You may disable/enable kubelet service on node, to simulate this.

What is the minimum required to get the node, marked as ready ?

**Comment by isabelmsft** [comment]
> Can you test the case, where node is really not ready and see what happens, when the node become ready.
> You may disable/enable kubelet service on node, to simulate this.

When we don't have a CNI, you can see the reason for the NotReady label with `kubectl describe node <NotReadyNodeName>`
image
We see that the reason is that "cni config is uninitialized"
After stopping kubelet, we see updated reason for NotReady: Kubelet stopped posting node status: 
image
After restarting kubelet, we see the original reason for NotReady: "cni config is uninitialized"
image

> What is the minimum required to get the node, marked as ready ?

So it seems, the minimum requirement to get the node marked as Ready is to deploy a CNI. KubeNet should not take much extra space, though it adds functionality that we should not have any use for beyond getting the status to show Ready.

**Comment by renukamanavalan** [comment]
Thanks Isabel. Can you please add a sample manifest with that toleration,  in this PR as comments ?

**Comment by lguohan** [comment]
retest mellanox please

**Comment by isabelmsft** [comment]
> What is the minimum requirement to get the node marked as ready?

I found a way to get around the CNI check. We can manually create the CNI config file. Essentially, the kubelet is searching for a config file in `/etc/cni/net.d` directory. Deploying flannel as a CNI normally places a flannel config file in that directory. When the kubelet doesn't find the config file, the check fails and node's status shows as NotReady. 

I manually created a flannel config file in that directory (without setting up flannel), and the node's status changes to Ready. Once I remove the file config file and restart the kubelet, the node's status updates to NotReady. I tested this because I noticed that the node status showed Ready as long as I deployed flannel once, and stayed Ready even after I deleted flannel (deleting flannel does not delete the config file) when I used the same SONiC image. If we manually create this file, we don't have to add any unnecessary networking complexity by deploying an unused CNI, and we can better tell when nodes are truly NotReady in our use case. Renuka suggests we may add this in kube_join script.


> Can you please add a sample manifest with that toleration, in this PR as comments ?

We should not need tolerations any more if we manually add a config file (confirmed with local testing), but here is the format of my original toleration, parallel to `volumes` and `containers` in the manifest definition: 

image

**Pull request merged**
