### PR TITLE
[202012]BRCM SAI 4.3.3.7 Picked up BRCM SAI Fixes up to release 4.3.3.7 include 4.3.3.6

### PR DESCRIPTION
**Pull request by gechiang**
#### Why I did it
This is to pick up BRCM SAI 4.3.3.7 which contains 2 set of changes
1.  tunnel, mmu, ecc control related issues and pipeline changes (4.3.3.6 changes)
2.  fixes for CS00012178692, CS00012183901, CS00012182148, SDK SID and other minor cleanups

Please note that the pipeline changes although were picked up but the actual build is not yet changed. Build team will work on that separately. 

Preliminary tests looks fine. BGP neighbors were all up with proper routes programmed
interfaces are all up
Manually ran the following test cases on S6100 DUT and all passed:
```
     ipfwd/test_dir_bcast.py
     fib/test_fib.py
     vxlan/test_vxlan_decap.py
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog
Merged in new BRCM SAI 4.3.3.7 to 202012 branch

### CODE REVIEW

**Review by smaheshm — APPROVED** [review]
:shipit:

**Comment by gechiang** [comment]
@prsunny @lguohan 
I believe the "vstest" failure is a known issue.  I tried merge to pick up from latest 202012 but it is not making any difference.
My change is purely BRCM SAI and should not have anything to do with vstest.  I may need some help on how to overcome this issue.  Tried re-run the test or restart "/azp run" several times.  Neither made any difference...

**Review by prsunny — APPROVED** [review]

**Pull request merged**
