### PR TITLE
[submodule] Update sonic-utilities submodule

### PR DESCRIPTION
**Pull request by aravindmani-1**
Includes:

- fe00bbf (HEAD) Revert "[sonic-package-manager] support sonic-cli-gen and packages with YANG model (#1650)" (https://github.com/Azure/sonic-utilities/pull/1972)
- 5fe6d92 [warm/fast-reboot] Fix kexec portion to support platforms based on Device Tree (https://github.com/Azure/sonic-utilities/pull/1966)
- 74d2a09 [portstat] check TX/RX utilization calculation correctness (https://github.com/Azure/sonic-utilities/pull/1840)
- e44c3f6 [generic-config-updater] Improving CreateOnly validator and marking /LOOPBACK_INTERFACE/LOOPBACK#/vrf_name as create-only (https://github.com/Azure/sonic-utilities/pull/1969)
- 0067cc4 [build] adapt for upstream target path change (https://github.com/Azure/sonic-utilities/pull/1971)
- 96143ee preserve old order for config reload (https://github.com/Azure/sonic-utilities/pull/1964)
- f08c81d [vxlan] remove unnecessary whitespace for show commands (https://github.com/Azure/sonic-utilities/pull/1792)
- 14889ce [soft-reboot] Add support for platforms based on Device Tree (https://github.com/Azure/sonic-utilities/pull/1963)
- 7ceccd7 [generic-config-updater] Adding non-strict mode (https://github.com/Azure/sonic-utilities/pull/1929)
- 2e462ef [sfputil] Firmware download/upgrade CLI support for QSFP-DD (https://github.com/Azure/sonic-utilities/pull/1947)
- 7c34b79 [config] Add portchannel support  for static route  (https://github.com/Azure/sonic-utilities/pull/1857)
- 54cc370 [doc] Refine doc on show loopback/mgmt ports (https://github.com/Azure/sonic-utilities/pull/1958)
- 3714f63 [port2alias]: Fix to get right number of return values (https://github.com/Azure/sonic-utilities/pull/1906)
- 3fa0854 [CLI][show bgp] On chassis don't show internal BGP sessions by default (https://github.com/Azure/sonic-utilities/pull/1927)
- 6de91af [Auto-Techsupport] Issues related to Multiple Cores crashing handled (https://github.com/Azure/sonic-utilities/pull/1948)
- 656ade1 SFP-Refactor: Vendor revision is not displayed properly (https://github.com/Azure/sonic-utilities/pull/1950)
- 67466cb [port] Fix port speed set (https://github.com/Azure/sonic-utilities/pull/1952)
- 5172972 Fix invalid output of syslog IPv6 servers (https://github.com/Azure/sonic-utilities/pull/1933)
- 290ff5f Routed subinterface enhancements (https://github.com/Azure/sonic-utilities/pull/1821)
- 1ea88e2 Enhance sfputil for CMIS QSFP (https://github.com/Azure/sonic-utilities/pull/1949)
- 4e132c1 [debug dump] Refactoring Modules and Unit Tests (https://github.com/Azure/sonic-utilities/pull/1943)
- b550c44 Add command reference for trap flow counters (https://github.com/Azure/sonic-utilities/pull/1876)
- 67a267b [Reclaim buffer] [Mellanox] Db migrator support reclaiming reserved buffer for unused ports (https://github.com/Azure/sonic-utilities/pull/1822)
- 30e4654 Add show command for BFD sessions (https://github.com/Azure/sonic-utilities/pull/1942)
- e63f47e [warm-reboot] Fix failures of warm reboot on disconnect of ssh session (https://github.com/Azure/sonic-utilities/pull/1529)
- c05845d Add trap flow counter support (https://github.com/Azure/sonic-utilities/pull/1868)
- ef82f00 [load_minigraph] Delay pfcwd start until the buffer templates are rendered (https://github.com/Azure/sonic-utilities/pull/1937)
- f5e5a56 [sonic-package-manager] support sonic-cli-gen and packages with YANG model (https://github.com/Azure/sonic-utilities/pull/1650)
- 64777a4 generic_config_updater: Filename changed & VLAN validator added (https://github.com/Azure/sonic-utilities/pull/1919)
- 1f8f6ab [config reload] Update command reference (https://github.com/Azure/sonic-utilities/pull/1941)

Signed-off-by: Aravind Mani aravind_m1@dell.com
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by prgeor** [comment]
there is another one here [https://github.com/Azure/sonic-buildimage/pull/9414](https://github.com/Azure/sonic-buildimage/pull/9414)

**Comment by prgeor** [comment]
@aravindmani-1 can you include the following fix in your submodule update so that build passes?
[https://github.com/Azure/sonic-utilities/commit/fe00bbf63283ca6f3842e470b88cdc5b6d266a0d](https://github.com/Azure/sonic-utilities/commit/fe00bbf63283ca6f3842e470b88cdc5b6d266a0d)

**Comment by prgeor** [comment]
@lguohan could you approve

**Comment by prgeor** [comment]
@aravindmani-1 seems this PR is not required now, another one already merged [https://github.com/Azure/sonic-buildimage/pull/9315](https://github.com/Azure/sonic-buildimage/pull/9315)

**Comment by aravindmani-1** [comment]
> @aravindmani-1 seems this PR is not required now, another one already merged #9315
Will close this PR. Thanks.

**Pull request closed without merging**
