### PR TITLE
[BFN] Update BFN modules

### PR DESCRIPTION
**Pull request by msosyak**
**- What I did**
Update BFN platform modules

**- How I did it**

**- How to verify it**
Build for BFN platform and run CTs

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by msosyak** [comment]
Needed for 291911 as well

**Comment by msosyak** [comment]
@lguohan merge, please and add need_for_201911 label

FYI: @akokhan @sunesh @ravi861

**Comment by msosyak** [comment]
retest vsimage please

**Comment by akokhan** [comment]
retest vsimage please

**Comment by msosyak** [comment]
retest vsimage please

**Comment by akokhan** [comment]
@lguohan , @jleveque ,
could you please merge this. Also, how this can be propagated to 201911 branch? Thank you.

**Comment by akokhan** [comment]
@lguohan , @jleveque ,
can we merge this into master and cherry-pick into 201911 please?

**Pull request merged**
