### PR TITLE
[DellEMC] s5232f console and sfputil fix

### PR DESCRIPTION
**Pull request by srideepDell**
Remove hardcoding 115K baudrate for console
Enhance sfputil api as per spec

**- What I did**
Remove hardcoding 115K baudrate for console
Enhance sfputil api as per spec

**- How I did it**
Modifying platform related files for S5232 under device folder.

**- How to verify it**
Did verify on S5232 platform

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by srideepDell** [comment]
Verified images with console 9600 
and 
below logs for sfp test cases.

root@sonic:~# show  interfaces status
  Interface            Lanes    Speed    MTU            Alias    Vlan    Oper    Admin             Type    Asym PFC
-----------  ---------------  -------  -----  ---------------  ------  ------  -------  ---------------  ----------
  Ethernet0          1,2,3,4     100G   9100   hundredGigE1/1  routed      up       up  QSFP28 or later         N/A
  Ethernet4          5,6,7,8     100G   9100   hundredGigE1/2  routed      up       up  QSFP28 or later         N/A
  Ethernet8       9,10,11,12     100G   9100   hundredGigE1/3  routed      up       up  QSFP28 or later         N/A
 Ethernet12      13,14,15,16     100G   9100   hundredGigE1/4  routed      up       up  QSFP28 or later         N/A
 Ethernet16      17,18,19,20     100G   9100   hundredGigE1/5  routed      up       up  QSFP28 or later         N/A
 Ethernet20      21,22,23,24     100G   9100   hundredGigE1/6  routed      up       up  QSFP28 or later         N/A
 Ethernet24      25,26,27,28     100G   9100   hundredGigE1/7  routed      up       up  QSFP28 or later         N/A
 Ethernet28      29,30,31,32     100G   9100   hundredGigE1/8  routed      up       up  QSFP28 or later         N/A
 Ethernet32      33,34,35,36     100G   9100   hundredGigE1/9  routed      up       up  QSFP28 or later         N/A
 Ethernet36      37,38,39,40     100G   9100  hundredGigE1/10  routed      up       up  QSFP28 or later         N/A
 Ethernet40      41,42,43,44     100G   9100  hundredGigE1/11  routed      up       up  QSFP28 or later         N/A
 Ethernet44      45,46,47,48     100G   9100  hundredGigE1/12  routed      up       up  QSFP28 or later         N/A
 Ethernet48      49,50,51,52     100G   9100  hundredGigE1/13  routed      up       up  QSFP28 or later         N/A
 Ethernet52      53,54,55,56     100G   9100  hundredGigE1/14  routed      up       up  QSFP28 or later         N/A
 Ethernet56      57,58,59,60     100G   9100  hundredGigE1/15  routed      up       up  QSFP28 or later         N/A
 Ethernet60      61,62,63,64     100G   9100  hundredGigE1/16  routed      up       up  QSFP28 or later         N/A
 Ethernet64      65,66,67,68     100G   9100  hundredGigE1/17  routed      up       up  QSFP28 or later         N/A
 Ethernet68      69,70,71,72     100G   9100  hundredGigE1/18  routed      up       up  QSFP28 or later         N/A
 Ethernet72      73,74,75,76     100G   9100  hundredGigE1/19  routed      up       up  QSFP28 or later         N/A
 Ethernet76      77,78,79,80     100G   9100  hundredGigE1/20  routed      up       up  QSFP28 or later         N/A
 Ethernet80      81,82,83,84     100G   9100  hundredGigE1/21  routed      up       up  QSFP28 or later         N/A
 Ethernet84      85,86,87,88     100G   9100  hundredGigE1/22  routed      up       up  QSFP28 or later         N/A
 Ethernet88      89,90,91,92     100G   9100  hundredGigE1/23  routed      up       up  QSFP28 or later         N/A
 Ethernet92      93,94,95,96     100G   9100  hundredGigE1/24  routed      up       up  QSFP28 or later         N/A
 Ethernet96     97,98,99,100     100G   9100  hundredGigE1/25  routed      up       up  QSFP28 or later         N/A
Ethernet100  101,102,103,104     100G   9100  hundredGigE1/26  routed      up       up  QSFP28 or later         N/A
Ethernet104  105,106,107,108     100G   9100  hundredGigE1/27  routed      up       up  QSFP28 or later         N/A
Ethernet108  109,110,111,112     100G   9100  hundredGigE1/28  routed      up       up  QSFP28 or later         N/A
Ethernet112  113,114,115,116     100G   9100  hundredGigE1/29  routed      up       up  QSFP28 or later         N/A
Ethernet116  117,118,119,120     100G   9100  hundredGigE1/30  routed      up       up  QSFP28 or later         N/A
Ethernet120  121,122,123,124     100G   9100  hundredGigE1/31  routed      up       up  QSFP28 or later         N/A
Ethernet124  125,126,127,128     100G   9100  hundredGigE1/32  routed      up       up   QSFP+ or later         N/A
Ethernet128              129      10G   9100      tenGigE1/33  routed    down       up   SFP/SFP+/SFP28         N/A
Ethernet129              128      10G   9100      tenGigE1/34  routed    down       up   SFP/SFP+/SFP28         N/A
root@sonic:~# sfputil show presence
Port         Presence
-----------  ----------
Ethernet0    Present
Ethernet4    Present
Ethernet8    Present
Ethernet12   Present
Ethernet16   Present
Ethernet20   Present
Ethernet24   Present
Ethernet28   Present
Ethernet32   Present
Ethernet36   Present
Ethernet40   Present
Ethernet44   Present
Ethernet48   Present
Ethernet52   Present
Ethernet56   Present
Ethernet60   Present
Ethernet64   Present
Ethernet68   Present
Ethernet72   Present
Ethernet76   Present
Ethernet80   Present
Ethernet84   Present
Ethernet88   Present
Ethernet92   Present
Ethernet96   Present
Ethernet100  Present
Ethernet104  Present
Ethernet108  Present
Ethernet112  Present
Ethernet116  Present
Ethernet120  Present
Ethernet124  Present
Ethernet128  Present
Ethernet129  Present
root@sonic:~# sfputil show eeprom
Ethernet0: SFP EEPROM detected
        Connector: No separable connector
        Encoding: 64B66B
        Extended Identifier: Power Class 1(1.5W max)
        Extended RateSelect Compliance: QSFP+ Rate Select Version 1
        Identifier: QSFP28 or later
        Length Cable Assembly(m): 2
        Length OM1(m): 0
        Length OM2(m): 0
        Length OM3(2m): 0
        Length(km): 0
        Nominal Bit Rate(100Mbs): 255
        Specification compliance:
                10/40G Ethernet Compliance Code: 40GBASE-CR4
        Vendor Date Code(YYYY-MM-DD Lot): 2018-04-18
        Vendor Name: DELL
        Vendor OUI: 78-a7-14
        Vendor PN: 76V43
        Vendor Rev: A0
        Vendor SN: CN0APX0084G1F2Y

**Comment by srideepDell** [comment]
request to add this commit to 201911 branch too.

**Comment by srideepDell** [comment]
retest broadcom please

**Comment by srideepDell** [comment]
retest vsimage please

**Comment by srideepDell** [comment]
retest vsimage please

**Comment by abdosi** [comment]
@srideepDell Please raise PR for 201911. There is conflict in cherry-pick.

**Pull request merged**
