### PR TITLE
[libteam] Upgrade libteam to 1.28-1 and reorganize patches

### PR DESCRIPTION
**Pull request by lorchid**
Signed-off-by: yorke <yorke.yuan@asterfusion.com>

**- What I did**
Upgrade libteam to 1.28-1 and reorganize patches.

**- How I did it**
Modify Makefile and patch serires.
1. Advance libteam to jpirko/libteam 5c5e498
2. Advance debian supporting to debian/libteam.git 7188c361
3. Remove patch 0001, 0010 and 0011 as they are already including in the new source code
4. Reorganize the other patches simultaneously
Note: NETLINK_RCVBUF is 196608 now (prev patch set it to 983040) and it works fine for testing. (Refering to libteam: double NETLINK_RCVBUF to fix -ENOMEM error)

**- How to verify it**
Build a SONiC image and run the lacp test in the sonic-mgmt repo. Ensure the test succeeds.

**- Description for the changelog**
	modified:   rules/libteam.mk
	modified:   src/libteam/Makefile
	new file:   src/libteam/patch/series
	deleted:    src/libteam/series
	deleted:    src/libteam/0001-libteam-Add-team_get_port_enabled-function.patch
	deleted:    src/libteam/0010-teamd-lacp-update-port-state-according-to-partners-sy.patch
	deleted:    src/libteam/0011-libteam-resynchronize-ifinfo-after-lost-RTNLGRP_LINK-.patch
	renamed:    src/libteam/0002-libteam-Temporarily-remove-redundant-debug-mes.patch -> src/libteam/patch/0001-Temporarily-remove-redundant-debug-messages.patch
	renamed:    src/libteam/0003-teamd-lacp-runner-will-send-lacp-update-right-after-.patch -> src/libteam/patch/0002-Lacp-runner-will-send-lacp-update-right-after-it-rec.patch
	renamed:    src/libteam/0004-libteam-Add-lacp-fallback-support-for-single-member-.patch -> src/libteam/patch/0003-Add-fallback-support-for-single-member-port-LAG.patch
	renamed:    src/libteam/0005-libteam-Add-warm_reboot-mode.patch -> src/libteam/patch/0004-Add-warm_reboot-mode.patch
	renamed:    src/libteam/0007-Skip-setting-the-same-hwaddr-to-lag-port-to-avoid-di.patch -> src/libteam/patch/0005-Skip-setting-the-same-hwaddr-to-lag-port-to-avoid-di.patch
	renamed:    src/libteam/0012-teamd-do-not-process-lacpdu-before-the-port-ifinfo-i.patch -> src/libteam/patch/0006-teamd-do-not-process-lacpdu-before-the-port-ifinfo-i.patch
	renamed:    src/libteam/0013-teamd-lacp-port-admin-down-recv-not-processing.patch -> src/libteam/patch/0007-Administratively-shutdown-port-channel-has-member-po.patch

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lorchid** [comment]
> is 1.28-1 stable enough?
> 
> could you maintain the patches' original owner's names? otherwise it's losing tracks of who's the author of the patches.



> Thanks for the patch!
> 
> 1. Please add following PR in your patch: [3f4de49](https://github.com/Azure/sonic-buildimage/commit/3f4de49e3d3d101bfb4fa2499f64a00df0708cc0)
> 2. I think this is part of current libteam master now: 0006-teamd-do-not-process-lacpdu-before-the-port-ifinfo-i.patch
> 3. Please reorder patches to make 0004-Add-warm_reboot-mode.patch as the last one.
> 4. Please keep the NETLINK_RCVBUF as 983040. 196608 is not enough for the device with 32 team interfaces

OK. Thanks for reviewing. I will improve that as you suggest.

**Comment by stcheng** [comment]
@lorchid thanks!

**Comment by pavel-shirshov** [comment]
Can you please resolve the conflict and also remove "0014-Send-LACP-PDU-immediately-if-our-state-changed.patch" file?

**Comment by pavel-shirshov** [comment]
For future references
```
0001-libteam-Add-team_get_port_enabled-function.patch            - master
0002-libteam-Temporarily-remove-redundant-debug-mes.patch        - 0001-libteam-Temporarily-remove-redundant-debug-messages.patch
0003-teamd-lacp-runner-will-send-lacp-update-right-after-.patch  - 0002-teamd-lacp-runner-will-send-lacp-update-right-after-.patch 
0004-libteam-Add-lacp-fallback-support-for-single-member-.patch  - 0003-libteam-Add-fallback-support-for-single-member-port-.patch 
0005-libteam-Add-warm_reboot-mode.patch                          - 0008-libteam-Add-warm_reboot-mode.patch
0007-Skip-setting-the-same-hwaddr-to-lag-port-to-avoid-di.patch  - 0004-Skip-setting-the-same-hwaddr-to-lag-port-to-avoid-di.patch 
0010-teamd-lacp-update-port-state-according-to-partners-sy.patch - master
0011-libteam-resynchronize-ifinfo-after-lost-RTNLGRP_LINK-.patch - master + 0005-Increase-default-buffer-size-from-98304-to-983040.patch 
0012-teamd-do-not-process-lacpdu-before-the-port-ifinfo-i.patch  - master
0013-teamd-lacp-port-admin-down-recv-not-processing.patch        - 0006-teamd-Administratively-shutdown-port-channel-has-mem.patch 
0014-Send-LACP-PDU-immediately-if-our-state-changed.patch        - 0007-Send-LACP-PDU-immediately-if-our-state-changed.patch 
```

**Pull request merged**
