### PR TITLE
[BFN] [202111] Updated platform plugins 

### PR DESCRIPTION
**Pull request by bratashX**
Signed-off-by:  Petro Bratash [petrox.bratash@intel.com](mailto:petrox.bratash@intel.com)

#### Why I did it
Have a lot of missing BFN platform APIs implementation in SONiC 202111

#### How I did it
Ported BFN platform plugins from `master` branch.

#### How to verify it
Run sonic-mgmt platform TCs

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by bratashX** [comment]
@akokhan @msosyak @SavchukRomanLv FYI

**Comment by bratashX** [comment]
> This pull request introduces 1 alert when merging https://github.com/Azure/sonic-buildimage/commit/bd6a86b7287ae99a8494bc20ec7e4ce949408189 into https://github.com/Azure/sonic-buildimage/commit/5809e7cad4f16dd2bcefb4455d7d6f957119d9ea - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-buildimage/rev/pr-4fef45ff9abc85998ff82258666e7b0a90dfe216)
> 
> new alerts:
> 
> 1 for Wrong number of arguments in a class instantiation

False-negative, opened issue: https://github.com/github/codeql/issues/3617

**Review by akokhan — APPROVED** [review]

**Comment by akokhan** [comment]
@lguohan , this PR contains back porting of multiple BFN fixes including platform plugins updates from SONiC master. Please approve and merge.

**Comment by bratashX** [comment]
@prgeor @sujinmkang, please  review and merge

**Review by prgeor — APPROVED** [review]

**Pull request merged**
