### PR TITLE
Update submodule platform/broadcom/sonic-platform-modules-ingrasys

### PR DESCRIPTION
**Pull request by wadelnn**
* Fixed FAN Status Setup Error.
* Add Drivers deinitialization feature.
* Allow for updating drivers on a running system.
* Let fans returned to full speed when driver uninstalled.
* Change S8900-64XC fancontrol config
* Delete S9100 syncd.conf

Signed-off-by: Wade He <chihen.he@gmail.com>

### CODE REVIEW

**Comment by lguohan** [comment]
build on broadcom fails, please check

**Comment by stcheng** [comment]
@wadelnn  you could comment "retest this please" to trigger new build. 
what i saw here in the output is:
```
Unpacking sonic-platform-ingrasys-s8900-54xc (1.1.0) ...
Setting up sonic-platform-ingrasys-s8900-54xc (1.1.0) ...
depmod: ERROR: could not open directory /lib/modules/4.4.0-59-generic: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
+ sudo mkdir -p ./fsroot/platform/x86_64-ingrasys_s8900_54xc-r0
+ sudo cp target/debs/sonic-platform-ingrasys-s8900-54xc_1.1.0_amd64.deb ./fsroot/platform/x86_64-ingrasys_s8900_54xc-r0/
++ find ./fsroot/var/cache/apt/archives -name '*.deb'
+ sudo dpkg --root=./fsroot -P sonic-platform-ingrasys-s8900-54xc
(Reading database ... 21461 files and directories currently installed.)
Removing sonic-platform-ingrasys-s8900-54xc (1.1.0) ...
rmmod: ERROR: Module coretemp is not currently loaded
rmmod: ERROR: Module jc42 is not currently loaded
rmmod: ERROR: Module w83795 is not currently loaded
rmmod: ERROR: Module eeprom_mb is not currently loaded
/usr/sbin/i2c_utils.sh: line 604: /sys/bus/i2c/devices/i2c-10/delete_device: No such file or directory
/usr/sbin/i2c_utils.sh: line 605: /sys/bus/i2c/devices/i2c-13/delete_device: No such file or directory
rmmod: ERROR: Module gpio_pca953x is not currently loaded
rmmod: ERROR: Module i2c_mux_pca954x is not currently loaded
rmmod: ERROR: Module i2c_ismt is not currently loaded
rmmod: ERROR: Module i2c_i801 is not currently loaded
Start Time:  (1496656644)
End Time  : Mon Jun  5 09:57:24 UTC 2017 (1496656644)
Total Execution Time: 0 sec
done!!!
depmod: ERROR: could not open directory /lib/modules/4.4.0-59-generic: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
dpkg: error processing package sonic-platform-ingrasys-s8900-54xc (--purge):
 subprocess installed post-removal script returned error exit status 1
Errors were encountered while processing:
 sonic-platform-ingrasys-s8900-54xc
```

**Comment by wadelnn** [comment]
Hi, @stcheng 
I saw the [jenkins](https://sonic-jenkins.westus.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all-pr/463/)  is build this PR again. 
the test detail link is not show on this page.
Do I comment "retest this please" again??

**Comment by stcheng** [comment]
@wadelnn https://sonic-jenkins.westus.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all-pr/457/console this is the link to the previous failed build. Currently the Jenkins is building again. But since you didn't update the pull request, Jenkins might fail again due to the same reason.
Once you figure out the reason of the failure and push again to this pull request, Jenkins will trigger another build.
We could proceed to merge once the build succeeds.

**Comment by wadelnn** [comment]
Got it. Thanks a lot

**Pull request merged**
