### PR TITLE
[Mellanox]Integrate hw-mgmt 7.0000.3012 and advance the linux kernel

### PR DESCRIPTION
**Pull request by stephenxs**
**- What I did**
Integrate hw-mgmt 7.0000.3012

Advance the sonic-linux-kernel

1. [sFlow]: Patch to fix skb_over_panic in psample driver ([#120](https://github.com/Azure/sonic-linux-kernel/pull/120))
2. Added support in the kernel for fullcone 3-tuple unique nat. ([#100](https://github.com/Azure/sonic-linux-kernel/pull/100))
3. Adding support to compile ARM architecture (#102)
4. [ixgbe] Support bcm54616s external phy in ixgbe ([#122](https://github.com/Azure/sonic-linux-kernel/pull/122))
5. Fix i2c ISMT DMA buffer alignment issue ([#123](https://github.com/Azure/sonic-linux-kernel/pull/123))
6. [mellanox]: Add SN4700 patches. ([#126](https://github.com/Azure/sonic-linux-kernel/pull/126))

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by nazariig** [comment]
retest vsimage please

**Comment by stephenxs** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by stephenxs** [comment]
retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by stephenxs** [comment]
Retest vsimage please

**Comment by stephenxs** [comment]
Retest vsimage please

**Pull request merged**
