### PR TITLE
[Mellanox] Change MFT version to 4.13.3

### PR DESCRIPTION
**Pull request by noaOrMlnx**
**- What I did**
Updated MFT version to 4.13.3 (revision 6)

**- How I did it**
Changed mft.mk

**- How to verify it**
* make configure PLATFORM=mellanox
* make target/sonic-mellanox.bin

**- Description for the changelog**

* N/A

**- Notice**
Need to update both master and 201911 branches, by adding a lable. 

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by nazariig** [comment]
@lguohan please take this to `201911` branch

**Comment by liat-grozovik** [comment]
retest vsimage

**Comment by liat-grozovik** [comment]
retest vsimage

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Pull request merged**
