### PR TITLE
Test AzurePipelinesWrapper

### PR DESCRIPTION
**Pull request by MiaoXuHui**
#### Why I did it
Test /AzurePipelinesWrapper

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Comment by MiaoXuHui** [comment]
/AzurePipelinesWrapper run "Azure.sonic-buildimage (Build vs)"

**Comment by MiaoXuHui** [comment]
/AzurePipelinesWrapper run "Azure.sonic-buildimage (Build vs)"

**Comment by MiaoXuHui** [comment]
/AzurePipelinesWrapper run "Azure.sonic-buildimage (Build vs)"

**Comment by lguohan** [comment]
@xumia , can you close this pr?

**Comment by xumia** [comment]
> @xumia , can you close this pr?

Closed.

**Pull request closed without merging**
