### PR TITLE
[202405][Nokia-7220 IXR] Add support for NOKIA 7220 IXR-H4

### PR DESCRIPTION
**Pull request by fzhou-nokia**
#### Why I did it
Add support for NOKIA 7220 IXR-H4

> NOKIA 7220-IXR-H4:
> Platform: x86_64-nokia_ixr7220_h4-r0
> HwSKU: Nokia-IXR7220-H4
> ASIC: Broadcom
> Port Config: 64x400G + 2x10G

Add device files for NOKIA 7220 IXR-H4-32D

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added module under ../device/nokia directory.
Modified the platform/broadcom/one-image.mk and platform/broadcom/ platform-modules-nokia.mk

#### How to verify it

1. Make sure the sonic-buildimage is successful

2. Run this image on x86_64-nokia_ixr7220_h4-r0 and x86_64-nokia_ixr7220_h4_32d-r0 and verify all dockers are up and test basic commands like:

- show version
- show platform summary
- show platform syseeprom
- show platform fan
- show platform psustatus
- show platform firmware status
- show platform temperature
- sudo show system-health detail
- show interface status

3. Run OC test, for T0/T1 topology and have 100% pass on platform.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by Pavan-Nokia** [comment]
@arlakshm @bingwang-ms Please help merge this PR.
This is a backport PR for https://github.com/sonic-net/sonic-buildimage/pull/19738 due to cherry-pick conflicts

**Comment by Pavan-Nokia** [comment]
@bingwang-ms @Blueve  Rebased PR to address build issue. 

This is a backport PR for https://github.com/sonic-net/sonic-buildimage/pull/19738  and https://github.com/sonic-net/sonic-buildimage/pull/20559 due to cherry-pick conflicts

please help Merge

**Comment by bingwang-ms** [comment]
Hi @fzhou-nokia, I can't merge this PR to 202405 since #20559 is not merged to master yet.

**Pull request merged**
