### PR TITLE
Potential fix for Celestica E1031 device hang

### PR DESCRIPTION
**Pull request by sumukhatv**
**- Why I did it**
To prevent Celestica E1031 from going to hang state abruptly
**- How I did it**
Preventing CPU sleep; setting idle cstate to 0
**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [- ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

Potential fix for Celestica E1031 hang issue

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
can you provide the max_cstate in running system?

**Comment by sumukhatv** [comment]
> can you provide the max_cstate in running system?

$ cat /sys/module/intel_idle/parameters/max_cstate
9

**Comment by lguohan** [comment]
what about the value this change?

**Comment by sumukhatv** [comment]
> what about the value this change? it needs to be zero.

With this change:
$ cat /sys/module/intel_idle/parameters/max_cstate
0

**Review by lguohan — APPROVED** [review]

**Pull request merged**
