### PR TITLE
Add necessary changes for python3 virtual environment of sonic-mgmt docker container

### PR DESCRIPTION
**Pull request by OleksandrKozodoi**
Signed-off-by: Oleksandr Kozodoi <oleksandrx.kozodoi@intel.com>

This PR includes necessary changes for the setup of the Python3  virtual environment in the sonic-mgmt docker container.
#### How to activate Python3 virtual environment?
1. Connect to the sonic-mgmt container
```
$ docker exec -ti sonic-mgmt bash
```
2. Activate the virtual environment
```
$ source /var/user/env-python3/bin/activate
```
#### Why I did it
Migration of sonic-mgmt codebase from Python 2 to Python 3
#### How I did it
Added all necessary dependencies to the env-python3 virtual environment.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by SavchukRomanLv** [comment]
Hi @lguohan can this be merged? Thank you

**Pull request merged**
