### PR TITLE
fix DELL S6000 port mapping

### PR DESCRIPTION
**Pull request by stevenlu99**
Dell S6000 front port is labeled as below:
4 12 20 ...
0  8 16 ...
Adjusted port mapping to reflect front port

**- What I did**
Adjust port mapping for Dell S6000 to reflect front-port numbering

**- How I did it**
Modify port name/alias and lanes in port_config.ini to reflect front-port numbering

**- How to verify it**
connect ports in each cage and verified correct port shows link up.

**- Description for the changelog**

The DELL S6000 front port is numbered as below:
4 12  20  24 ... 124
0  8   16  20 ... 120
But the port mapping in port_config.ini was like:
0  8  16 ... 120
4 12 20 ... 124
Modified port_config.ini so that correct port number will be shown in SONiC

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
s6000 is meant to be s6000-on which has different physical layout.

**Comment by stevenlu99** [comment]
This is S6000 and I checked logo on front-panel and output from "show platform summary"
root@Td22:/home/admin# show platform summary 
Platform: x86_64-dell_s6000_s1220-r0
HwSKU: Force10-S6000
ASIC: broadcom

**Comment by lguohan** [comment]
unfortunately, dell use the same string for s6000 and s6000-on. I think we need to take this issue to dell and ask them to solve the problem.

**Comment by lguohan** [comment]
@Anandaraj-Maharajan  to look

**Comment by Anandaraj-Maharajan** [comment]
Sorry for the delay, we will look into this and get back.

**Comment by lguohan** [comment]
i do not think this pr can be merged due to reason given above.

**Pull request closed without merging**
