### PR TITLE
[mellanox] Update FW to 13/29.2000.2714

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>

**- What I did**
* Updated Mellanox ASIC firmware

**- How I did it**
* Updated makefile/submodule

**- How to verify it**
1. make configure PLATFORM=mellanox
2. make target/sonic-mellanox.bin

**- Description for the changelog**
* N/A

**- A picture of a cute animal (not mandatory but encouraged)**
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Comment by nazariig** [comment]
@liat-grozovik please add 201911 label

**Comment by prsunny** [comment]
retest vs please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by nazariig** [comment]
@lguohan / @prsunny FYI. Build errors:
`vsimage`:
```
TASK [find interface name mapping and individual interface speed if defined] ***
Monday 13 January 2020  21:31:29 +0000 (0:00:00.354)       0:00:01.943 ******** 
[WARNING]: Unhandled error in Python interpreter discovery for host vlab-01:
Failed to connect to the host via ssh: ssh: connect to host 10.250.0.101 port
22: Connection timed out
fatal: [vlab-01]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"10.250.0.101\". Make sure this host can be reached over ssh: ssh: connect to host 10.250.0.101 port 22: No route to host\r\n", "unreachable": true}
```
`vs`:
```
self = <docker.transport.unixconn.UnixHTTPAdapter object at 0x7f20a4300990>
request = <PreparedRequest [POST]>, stream = False
timeout = <urllib3.util.timeout.Timeout object at 0x7f20a429ce10>, verify = True
cert = None, proxies = OrderedDict()

    def send(self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None):
        """Sends PreparedRequest object. Returns Response object.

        except (_SSLError, _HTTPError) as e:
            if isinstance(e, _SSLError):
                # This branch is for urllib3 versions earlier than v1.22
                raise SSLError(e, request=request)
            elif isinstance(e, ReadTimeoutError):
>               raise ReadTimeout(e, request=request)
E               ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

**Comment by nazariig** [comment]
retest vsimage please

**Comment by nazariig** [comment]
retest vsimage please

**Comment by nazariig** [comment]
retest vs please

**Pull request merged**
