### PR TITLE
Support AS9716-32D 10G port (33/34)

### PR DESCRIPTION
**Pull request by chihhan123**
Support 10G ports (33/34) for As9716-32D.
Test port link up works fine.

### CODE REVIEW

**Comment by chihhan123** [comment]
Retest kvmtest-t0 please

**Comment by chihhan123** [comment]
Retest Test kvmtest-t0 please

**Comment by chihhan123** [comment]
Retest kvmtest please

**Comment by chihhan123** [comment]
retest kvmtest-t0 please

**Comment by chihhan123** [comment]
Hi Reviewer @jleveque  ,

How to retest Azure.sonic-buildimage (Test kvmtest-t0) and Azure.sonic-buildimage  by comment?
Thanks.

Sincerely,
       Chih Han

**Comment by jleveque** [comment]
> Hi Reviewer @jleveque ,
> 
> How to retest Azure.sonic-buildimage (Test kvmtest-t0) and Azure.sonic-buildimage by comment?
> Thanks.
> 
> Sincerely,
> Chih Han

Currently only repository members can do this with Azure Pipelines. We're trying to find a solution to at least let the PR author do the same.

**Pull request closed without merging**
