### PR TITLE
[iccpd] Fix iccpd env

### PR DESCRIPTION
**Pull request by novikauanton**
#### Why I did it
 `mclagsyncd` source is in sonic-swss repo, its binary is inside `iccpd` container and binary use `platform` env var https://github.com/Azure/sonic-swss/blob/ef6b5d48297f7f19a8ec57e2d7b997fd0919bb9d/mclagsyncd/mclaglink.cpp#L191

 But `platform` env is set only inside `swss` container services, for example https://github.com/Azure/sonic-buildimage/blob/7d40384c58848c368ecf7b2c520f7a17fcbc8bdb/dockers/docker-orchagent/orchagent.sh#L7 

So code doesn't support branch with port isolation group, because env is not set.

#### How I did it
Added env to iccpds start script, like in `orchagent`

#### How to verify it
* build sonic with iccpd
* configure mclag
* wait iccpd bring up
* /var/log/syslog must contains row with text `Delete all isolation group destination ports`, hence code branch with port isolation group was used instead of ACL
* 
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [x] 202106

### CODE REVIEW

**Comment by novikauanton** [comment]
@gechiang could you please review it?

**Comment by akokhan** [comment]
@gitsabari, @Praveen-Brcm , please take a look

**Comment by novikauanton** [comment]
@lguohan could you please help to review it?

**Comment by gechiang** [comment]
Looks good to me.  But let's wait for @gitsabari, @Praveen-Brcm to review and approve.

**Comment by Praveen-Brcm** [comment]
Changes looks good to me. Please add me to the reviwers list to approve. Thanks.

**Comment by gechiang** [comment]
> Changes looks good to me. Please add me to the reviwers list to approve. Thanks.

@Praveen-Brcm 
Looks like I am not able to add you as a reviewer... but since you have already reviewed it and approved, I will go ahead approve it and merge it.
Thanks!

**Comment by gitsabari** [comment]
changes looks good to me also. Please add me to reviewer list to approve

**Review by gechiang — APPROVED** [review]
LGTM! @praveen-brcm has also reviewed and approved.

**Pull request merged**
