### PR TITLE
[Mellanox] Fix platform json for MSN2100

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

2x40G is not supported on MSN2100, need remove it from platform.json

#### How I did it

Remove 2x40G from platform.json

#### How to verify it

Run build

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @jleveque, it seems the failure is not related to my change, could you please help re-trigger the test?

**Comment by Junchao-Mellanox** [comment]
The test failure is not related to the change,  could you please help re-trigger the test?

**Comment by Junchao-Mellanox** [comment]
Hi @jleveque，

Error ```The job running on agent sonic-build-workers-0001NP ran longer than the maximum time of 240 minutes```， seems it reached some timeout. Could you please rerun the test? Thanks!

**Comment by Junchao-Mellanox** [comment]
The test case failed to extract yang model, it is not related to this change.

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
