### PR TITLE
Mgmt reorg -- submodule and build rules for sonic-mgmt-common

### PR DESCRIPTION
**Pull request by sachinholla**
**- Why I did it**
New repo sonic-mgmt-common is introduced for the common translib related code. This commit adds build rules for this new repo.

**- How I did it**
1) Added sonic-mgmt-common submodule
2) Added build rules for the new sonic-mgmt-common repo. It creates two deb packages -- sonic-mgmt-common_1.0.0_{arch}.deb and sonic-mgmt-common-codegen_1.0.0_{arch}.deb. Package cache is enabled.
3) Added dependency on sonic-mgmt-common for mgmt-framework and telemetry debs and dockers.

**- How to verify it**
Full build and incremental builds
Basic ACL and interface opreations through REST, KLISH CLI and gNMI

**- Description for the changelog**
Git submodule and build rules for the new sonic-mgmt-common repo.

### CODE REVIEW

**Comment by renukamanavalan** [comment]
please retest vsimage

**Comment by renukamanavalan** [comment]
please retest vsimage

**Comment by renukamanavalan** [comment]
retest vsimage please.

**Comment by renukamanavalan** [comment]
retest vsimage please

**Comment by renukamanavalan** [comment]
retest vsimage please

**Comment by renukamanavalan** [comment]
retest vsimage please

**Comment by renukamanavalan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by renukamanavalan** [comment]
retest vsimage please

**Comment by renukamanavalan** [comment]
Expect, last failed build to have done the required cleanup

**Pull request merged**
