### PR TITLE
[sonic-vs]: build sonic vs kvm image

### PR DESCRIPTION
**Pull request by lguohan**
**- What I did**
build sonic kvm virtual switch image.

**- How I did it**

**- How to verify it**
```
Debian GNU/Linux 9 sonic ttyS0

sonic login: admin       
Password: 
Last login: Tue Nov 20 04:20:10 UTC 2018 on ttyS0
Linux sonic 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2015-12-19) x86_64
You are on
  ____   ___  _   _ _  ____
 / ___| / _ \| \ | (_)/ ___|
 \___ \| | | |  \| | | |
  ___) | |_| | |\  | | |___
 |____/ \___/|_| \_|_|\____|

-- Software for Open Networking in the Cloud --

Unauthorized access and/or use are prohibited.
All access and/or use are subject to monitoring.

Help:    http://azure.github.io/SONiC/

admin@sonic:~$ show version
SONiC Software Version: SONiC.vs.0-dirty-20181119.192446
Distribution: Debian 9.6
Kernel: 4.9.0-7-amd64
Build commit: 6da43f6
Build date: Mon Nov 19 21:24:10 UTC 2018
Built by: lgh@gulv-vm2

Docker images:
REPOSITORY                 TAG                          IMAGE ID            SIZE
docker-orchagent-vs        latest                       e23a570e62a9        282.8 MB
docker-orchagent-vs        vs.0-dirty-20181119.192446   e23a570e62a9        282.8 MB
docker-syncd-vs            latest                       a7d312639103        253.9 MB
docker-syncd-vs            vs.0-dirty-20181119.192446   a7d312639103        253.9 MB
docker-lldp-sv2            latest                       faa11fec626e        271.1 MB
docker-lldp-sv2            vs.0-dirty-20181119.192446   faa11fec626e        271.1 MB
docker-dhcp-relay          latest                       d23042b92931        253.3 MB
docker-dhcp-relay          vs.0-dirty-20181119.192446   d23042b92931        253.3 MB
docker-database            latest                       fe2c44fd002e        251.9 MB
docker-database            vs.0-dirty-20181119.192446   fe2c44fd002e        251.9 MB
docker-snmp-sv2            latest                       5ab023abbe50        290.8 MB
docker-snmp-sv2            vs.0-dirty-20181119.192446   5ab023abbe50        290.8 MB
docker-teamd               latest                       daa1d8eea116        270.9 MB
docker-teamd               vs.0-dirty-20181119.192446   daa1d8eea116        270.9 MB
docker-router-advertiser   latest                       4c2050570fbf        249.6 MB
docker-router-advertiser   vs.0-dirty-20181119.192446   4c2050570fbf        249.6 MB
docker-platform-monitor    latest                       bbb9d07af0be        283.5 MB
docker-platform-monitor    vs.0-dirty-20181119.192446   bbb9d07af0be        283.5 MB
docker-fpm-quagga          latest                       78afae0a560b        277.7 MB
docker-fpm-quagga          vs.0-dirty-20181119.192446   78afae0a560b        277.7 MB

admin@sonic:~$ show platform summary
Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
admin@sonic:~$ lspci
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II]
00:01.2 USB controller: Intel Corporation 82371SB PIIX3 USB [Natoma/Triton II] (rev 01)
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
00:02.0 PCI bridge: Red Hat, Inc. QEMU PCI-PCI bridge
00:03.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:04.0 Unclassified device [00ff]: Red Hat, Inc Virtio memory balloon
00:05.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:06.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:07.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:08.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:09.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:0a.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:0b.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:0c.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:0d.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:0e.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:0f.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:10.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:11.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:12.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:13.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:14.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:15.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:16.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:17.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:18.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:19.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:1a.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:1b.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:1c.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:1d.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:1e.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:1f.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
01:01.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
01:02.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
01:03.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
01:04.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
01:05.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
01:06.0 SCSI storage controller: Red Hat, Inc Virtio block device
```

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
depends on https://github.com/Azure/sonic-sairedis/pull/384

**Comment by lguohan** [comment]
addressed #1990

**Comment by lguohan** [comment]
addressed #2134

**Comment by vikasksrivastava** [comment]
Hi @lguohan  , I downloaded the sonic-vs.bin and  installed via onie-nos-install on a  VirtualBox VM. 
The platform and port mapping in the VM are as per Force10-S6000 . 

How can I emulate a different platform , say "[Celestica-E1031-T48S4](https://github.com/Azure/sonic-buildimage/tree/master/device/celestica/x86_64-cel_e1031-r0/Celestica-E1031-T48S4)" ?  

Do I need to rebuild / make the image by changing the name under "[default_sku](https://github.com/Azure/sonic-buildimage/blob/master/device/virtual/x86_64-kvm_x86_64-r0/default_sku)"

Appreciate any help , thank you !

**Pull request merged**
