### PR TITLE
Updated BGP Template for Chassis/Multi-asic

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
```
 Updated BGP Template for the case:
    
   1. For Packet Chassis do not advertise Loopback4096 address into BGP as there is Static Route for same. 
       Having this route in BGP causes two level of recursion in Zebra and cause assert in Zebra 
       when there are many nexthop involved
 
   2. Advertise only P2P Connected IP's into BGP (External Peers). For Packet chassis we have backend IP Interface subnet and if 
        they  get advertised into BGP then it also causes recursion . Eg:

- Static Route using backend ip interface
str2-xxxx-lc2-1# show ip route 3.3.3.6/32
Routing entry for 3.3.3.6/32
  Known via "static", distance 1, metric 0, best
  Last update 00:01:44 ago
  * 10.0.1.4, via PortChannel40.2, weight 1
  * 10.0.2.4, via PortChannel41.2, weight 1
  * 10.0.3.4, via PortChannel42.2, weight 1
  * 10.0.4.4, via PortChannel43.2, weight 1
  * 10.0.5.4, via PortChannel44.2, weight 1
  * 10.0.6.4, via PortChannel45.2, weight 1
  * 10.0.7.4, via PortChannel46.2, weight 1
  * 10.0.8.4, via PortChannel47.2, weight 1
  * 10.0.9.4, via PortChannel48.2, weight 1
  * 10.0.10.4, via PortChannel49.2, weight 1  

str2-xxxx-lc2-1# show ip bgp 10.0.1.4
BGP routing table entry for 10.0.1.0/24
Paths: (2 available, best #2, table default, not advertised to EBGP peer)
  Advertised to non peer-group peers:
  3.3.3.6
  Local
    3.3.3.6 from 3.3.3.6 (3.3.3.6)        ==> Via iBGP
      Origin incomplete, metric 0, localpref 100, valid, internal
      Community: no-export
      Last update: Wed Nov 17 20:40:39 2021
  Local
    0.0.0.0 from 0.0.0.0 (3.3.3.5)  ==> Via redistribute connected
      Origin incomplete, metric 0, weight 32768, valid, sourced, best (Weight)
      Community: no-export
      Last update: Wed Nov 17 20:40:29 2021

-  If we disable one of backend interface it cause un-necessary recursion

sudo config interface -n asic0 shutdown PortChannel40.2

str2-xxxx-lc2-1# show ip route 3.3.3.6
Routing entry for 3.3.3.6/32
  Known via "static", distance 1, metric 0, best
  Last update 00:00:35 ago
    10.0.1.4 (recursive), weight 1
  *   10.0.2.4, via PortChannel41.2, weight 1
  *   10.0.3.4, via PortChannel42.2, weight 1
  *   10.0.4.4, via PortChannel43.2, weight 1
  *   10.0.5.4, via PortChannel44.2, weight 1
  *   10.0.6.4, via PortChannel45.2, weight 1
  *   10.0.7.4, via PortChannel46.2, weight 1
  *   10.0.8.4, via PortChannel47.2, weight 1
  *   10.0.9.4, via PortChannel48.2, weight 1
  *   10.0.10.4, via PortChannel49.2, weight 1
    10.0.2.4, via PortChannel41.2 (duplicate nexthop removed), weight 1
    10.0.3.4, via PortChannel42.2 (duplicate nexthop removed), weight 1
    10.0.4.4, via PortChannel43.2 (duplicate nexthop removed), weight 1
    10.0.5.4, via PortChannel44.2 (duplicate nexthop removed), weight 1
    10.0.6.4, via PortChannel45.2 (duplicate nexthop removed), weight 1
    10.0.7.4, via PortChannel46.2 (duplicate nexthop removed), weight 1
    10.0.8.4, via PortChannel47.2 (duplicate nexthop removed), weight 1
    10.0.9.4, via PortChannel48.2 (duplicate nexthop removed), weight 1
    10.0.10.4, via PortChannel49.2 (duplicate nexthop removed), weight 1
 
-  After change we do not see recursion/duplicate nexthop.
    str2-xxxx-lc2-1# show ip bgp 10.0.1.4 
   % Network not in table
```

How I verify:

-  Unit Test updated
- Manual Verification on devices.

### CODE REVIEW

**Comment by abdosi** [comment]
@anamehra

**Review by anamehra — APPROVED** [review]

**Pull request merged**
