### PR TITLE
[chassis] create v4 and v6 peer group for VoQ internal neighbors

### PR DESCRIPTION
**Pull request by arlakshm**
#### Why I did it
In the recent minigraph changes we add separate BGP session configuration for V4 and V6 internal VoQ neighbors.
This PR is adding different Peer groups for V4 and V6 neighbors
 
#### How I did it
Add `VOQ_CHASSIS_V4_PEER` and `VOQ_CHASSIS_V6_PEER`   groups
Add extra Unit tests

#### How to verify it
UT and check if the internal sessions come up on VoQ chassis

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by arlakshm** [comment]
@vganesan-nokia and skbarista for viz.

**Comment by abdosi** [comment]
@arlakshm do we need this `set ipv6 next-hop prefer-global` for v6 voq neighbors ?

**Review by abdosi — APPROVED** [review]

**Pull request merged**
