### PR TITLE
DellEMC: Fix EEPROM read error

### PR DESCRIPTION
**Pull request by aravindmani-1**
**- Why I did it**
EEPROM read failure was seen in Dell platforms
**- How I did it**
Make python 2/3 compliant API's to fix the issue 
**- How to verify it**
Check sfpshow eeprom and dom CLI output.
**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

**Comment by aravindmani-1** [comment]
@jleveque can you please merge this PR?.

**Comment by aravindmani-1** [comment]
@jleveque  All checks passed after closing/reopening the PR. Can you please PR be merged?.

**Pull request merged**
