### PR TITLE
[Monit] Deprecate the feature of monitoring the critical processes by Monit

### PR DESCRIPTION
**Pull request by yozhao101**
Signed-off-by: Yong Zhao <yozhao@microsoft.com>

#### Why I did it
Currently we leveraged the Supervisor to monitor the running status of critical processes in each container and it is more reliable and flexible than doing the monitoring by Monit. So we removed the functionality of monitoring the critical processes by Monit.

#### How I did it
I removed the script `process_checker` and corresponding Monit configuration entries of critical processes.

#### How to verify it
I verified this on the device `str-7260cx3-acs-1`.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x ] 202012

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]
:shipit:

**Comment by qiluo-msft** [comment]
This could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by yozhao101** [comment]
> This could not be cleanly cherry-picked to 202012. Please submit another PR.

I will submit a separate PR for 202012 branch.

**Pull request merged**
