### PR TITLE
[DPB] [Mellanox] added capability files for SN2700 platform

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
**- Why I did it**

`platform.json` and `hwsku.json` files are required for a feature called Dynamic Port Breakout

**- How I did it**

Created capability files according to platform specification `SN2700`

**- How to verify it**

Full qualification requires bugs fixes reported under sonic-buildimage

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Comment by vadymhlushko-mlnx** [comment]
Retest vsimage please

**Review by liat-grozovik — CHANGES_REQUESTED** [review]
missing none of the consecutive port in case of split 4

**Comment by vadymhlushko-mlnx** [comment]
retest vsimage please

**Review by liat-grozovik — CHANGES_REQUESTED** [review]
Current implementation of SONiC DPB is not aligned with the HLD and is missing functionality required for SN2700 split to 4 (unable to remove consecutive port ) this option should be removed with a comment in the file.

**Comment by vadymhlushko-mlnx** [comment]
> Current implementation of SONiC DPB is not aligned with the HLD and is missing functionality required for SN2700 split to 4 (unable to remove consecutive port ) this option should be removed with a comment in the file.

comments are not allowed inside the JSON files

**Comment by vadymhlushko-mlnx** [comment]
Please don't merge this PR until [[DPB][MLNX][YANG-models] extended regex pattern according to MLNX systems speeds requirements](https://github.com/Azure/sonic-buildimage/pull/6279) PR will be merged

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
