### PR TITLE
[minigraph] asymmetric pfc is disabled by default

### PR DESCRIPTION
**Pull request by mykolaf**
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>

**- What I did**

add generation of "pfc_asym" property for PORT. Asymmetric PFC is off by default.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by mykolaf** [comment]
@stcheng could you please take a look?

**Comment by liat-grozovik** [comment]
@lguohan could you please review? this is a fix i believe should go to 201811 branch as well.

**Comment by yxieca** [comment]
Made to 201811 branch on 2/21/2019

**Comment by MichelMoriniaux** [comment]
I get a compile error on _test_minigraph_port_description_ where this seems to be expected too

**Comment by mykolaf** [comment]
Hi @MichelMoriniaux, check this out https://github.com/Azure/sonic-buildimage/pull/2593

**Comment by MichelMoriniaux** [comment]
cool!

**Pull request merged**
