### PR TITLE
[barefoot][platform] Fix sonic-platform host installation

### PR DESCRIPTION
**Pull request by vboykox**
Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>

**- Why I did it**
prerm is needed for platform modules package to be properly removed.
**- How I did it**
Added prerm to remove installed in postinst wheel packages.
**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [X] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vboykox** [comment]
@akokhan

**Comment by vboykox** [comment]
@jleveque

**Comment by jleveque** [comment]
@vboykox: Just curious under what circumstances it is necessary to remove the packages first. At the time the platform modules are installed, there should be no sonic-platform package installed.

**Comment by vboykox** [comment]
@jleveque  Actually lazy installs are [installed/purged](https://github.com/Azure/sonic-buildimage/blob/85a631442418582d1a2f77bf0ca1b7b5addee12a/files/build_templates/sonic_debian_extension.j2#L533) during build to install all dependencies.

**Review by akokhan — APPROVED** [review]

**Review by jleveque — APPROVED** [review]

**Pull request merged**
