### PR TITLE
Add trap flow counter support

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

Add trap flow counter support

#### How I did it

Enable trap flow rate calculation

#### How to verify it

Manual test/VS test/sonic-mgmt test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by keboliu — DISMISSED** [review]

**Review by prsunny — APPROVED** [review]
Lgtm, can yang subgroup review the Yang file change?

**Review by prsunny — APPROVED** [review]

**Pull request merged**
