### PR TITLE
[sonic-swss-common] submodule update

### PR DESCRIPTION
**Pull request by donNewtonAlpha**
signed-off-by: Don Newton <don@opennetworking.org>

#### Why I did it
Submodule update for sonic-swss-common
Incorporates:

95aec72 2021-11-19  [PINS] Add Bazel support for external projects (#557)
1dfe06f 2021-11-18 P4Runtime : Status Code additions (#545)
8c93532 2021-11-18 Ported Marvell armhf build on amd64 host for debian buster to use cross-comp… (#501)
74264d9 2021-11-17 [PINS] Add AppDB ACL schema values shared between the P4RT app and P4Orch (#556)
a18618f 2021-11-15 [schema] Add vnet route tunnel and advertise network tables for state db (#560)
155770e 2021-11-12 [VS test] Increase test timeout (#559)
2b11dea 2021-11-08 [PINS] Update Redis schema to match P4Orch (#548)
be7d483 2021-11-08 [schema] add ACL_TABLE_TYPE table (#546)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by donNewtonAlpha** [comment]
@prsunny this is the pr that brings in the sonic-swss-common changes from 545

**Comment by saiarcot895** [comment]
I see Azure/sonic-swss-common#558 is now included in this PR. With that change, there needs to be a corresponding change in sonic-buildimage as well, specifically in `rules/sonic-swss-common.mk`:

```diff
diff --git a/rules/swss-common.mk b/rules/swss-common.mk
index 83a8d0f19..1a17d5e53 100644
--- a/rules/swss-common.mk
+++ b/rules/swss-common.mk
@@ -20,6 +20,8 @@ $(eval $(call add_derived_package,$(LIBSWSSCOMMON),$(LIBSWSSCOMMON_DEV)))
 ifeq ($(ENABLE_PY2_MODULES), y)
     PYTHON_SWSSCOMMON = python-swsscommon_$(LIBSWSSCOMMON_VERSION)_$(CONFIGURED_ARCH).deb
     $(eval $(call add_derived_package,$(LIBSWSSCOMMON),$(PYTHON_SWSSCOMMON)))
+else
+    $(LIBSWSSCOMMON)_BUILD_ENV += DEB_BUILD_PROFILES=nopython2
 endif

 PYTHON3_SWSSCOMMON = python3-swsscommon_$(LIBSWSSCOMMON_VERSION)_$(CONFIGURED_ARCH).deb
```

**Comment by donNewtonAlpha** [comment]
> I see [Azure/sonic-swss-common#558](https://github.com/Azure/sonic-swss-common/pull/558) is now included in this PR. With that change, there needs to be a corresponding change in sonic-buildimage as well, specifically in `rules/sonic-swss-common.mk`:
> 
> ```diff
> diff --git a/rules/swss-common.mk b/rules/swss-common.mk
> index 83a8d0f19..1a17d5e53 100644
> --- a/rules/swss-common.mk
> +++ b/rules/swss-common.mk
> @@ -20,6 +20,8 @@ $(eval $(call add_derived_package,$(LIBSWSSCOMMON),$(LIBSWSSCOMMON_DEV)))
>  ifeq ($(ENABLE_PY2_MODULES), y)
>      PYTHON_SWSSCOMMON = python-swsscommon_$(LIBSWSSCOMMON_VERSION)_$(CONFIGURED_ARCH).deb
>      $(eval $(call add_derived_package,$(LIBSWSSCOMMON),$(PYTHON_SWSSCOMMON)))
> +else
> +    $(LIBSWSSCOMMON)_BUILD_ENV += DEB_BUILD_PROFILES=nopython2
>  endif
> 
>  PYTHON3_SWSSCOMMON = python3-swsscommon_$(LIBSWSSCOMMON_VERSION)_$(CONFIGURED_ARCH).deb
> ```

Would it be better for me to back out that commit from the submodule or can that be a separate PR?  I was just moving the pointer to the HEAD.  
Don

**Comment by donNewtonAlpha** [comment]
@prsunny @qiluo-msft The build jobs are failing but if you look in azure pipelines it is way past where it builds swss-common and swss.  The tests that are failing are within the management container.  Would it be possible to get this merged so we can get the tests running on swss/pull/1992 ?

**Comment by bocon13** [comment]
Rebased to latest master

**Review by prsunny — APPROVED** [review]

**Pull request merged**
