### PR TITLE
[submodule] Update submodule for sonic-swss

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
a89d1f8 Fix failing DPB LAG tests (#1919)
86b4ede [portsorch] Avoid orchagent crash when set invalid interface types to port (#1906)
025032f [VS] Skip failing test - test_recirc_port (#1918)
d338bd0 [pfcwd] Fix the polling interval time granularity (#1912)
14c937e Enabling copp tests (#1914)
fbdcaae [teammgrd]: Improve LAGs cleanup on shutdown: send SIGTERM directly to PID. (#1841)
002bb1d [tlm teamd] Add retry mechanism before logging the ERR in get_dumps. (#1629)
57d21e7 [pfcwd] Convert polling interval from ms to us in LUA scripts (#1908)
d01524d [fgnhgorch] Enable packet flow when no FG ECMP neighbors are resolved (#1900)
8cf355d Mux state order change (#1902)
7a0ec8f [Flex-counters] Fix the delay of flex counters flow to prevent infinite loop (#1899)
254bc12 WCMP support for MPLS (#1895)
447ac71 [portsorch] Add an extra check before setting oper speed to APPL_DB (#1885)
a8d6246 Update acl type check logic (#1886)
62f7200 Update port_rates & rif_rates lua scripts to convert poll_interval to MS (#1855)
5643532 [Flex Counters] Delay flex counters even if tables are present in the DB (#1877)
eb79ca4 [pbh]: Add PBH OA (#1782)
3d6b1f0 [buffer orch] Bugfix: Don't query counter SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES on a pool where it is not supported (#1857)

#### Why I did it

Include PR https://github.com/Azure/sonic-swss/pull/1885

#### How I did it

Update submodule sonic-swss

#### How to verify it

Run build

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by lguohan** [comment]
do not merge. found a regression in sonic-swss

https://github.com/Azure/sonic-buildimage/issues/8722

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox could you please verify if no other PRs to update swss were already merged and if this is still needed lets have the conflict resolved.

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Please resolve conflicts.

**Comment by Junchao-Mellanox** [comment]
This PR is no longer needed as the submodule pointer of sonic-swss has already been moved.

**Pull request closed without merging**
