### PR TITLE
[Mellanox] Support shared headroom pool

### PR DESCRIPTION
**Pull request by stephenxs**
**- Why I did it**
Support shared headroom pool

Signed-off-by: Stephen Sun <stephens@nvidia.com>

**- How I did it**
- Port configurations for SKUs based on 2700/3800 platform from 201911
  - For SN3800 platform:
    - C64: 32 100G down links and 32 100G up links.
    - D112C8: 112 50G down links and 8 100G up links.
    - D24C52: 24 50G down links, 20 100G down links, and 32 100G up links.
    - D28C50: 28 50G down links, 18 100G down links, and 32 100G up links.
  - For SN2700 platform:
    - D48C8: 48 50G down links and 8 100G up links
    - C32: 16 100G downlinks and 16 100G uplinks
- Add configuration for Mellanox-SN4600C-D112C8
  - 112 50G down links and 8 100G up links.

**- How to verify it**
Run regression test.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by stephenxs** [comment]
retest this, please

**Review by neethajohn — APPROVED** [review]

**Comment by stephenxs** [comment]
retest this please

**Comment by stephenxs** [comment]
retest vs please

**Comment by stephenxs** [comment]
retest vsimage please

**Comment by stephenxs** [comment]
retest this, please

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@neethajohn the azure build is in progress for quite some time. Can you please take a look and help to merge?

**Pull request merged**
