### PR TITLE
[secureboot] only remove exec bit in secureboot

### PR DESCRIPTION
**Pull request by Staphylo**
Address issue #4832

### CODE REVIEW

**Comment by lguohan** [comment]
@qiluo-msft, can you link the issue in the pr?

**Comment by qiluo-msft** [comment]
Retest mellanox please

**Comment by daall** [comment]
retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by qiluo-msft** [comment]
@jleveque Please do not retest when there is one already running. Sometimes there are multiple triggered, and each finished one will mark failure here. I aborted the latest one. Thanks for your helping!

**Comment by jleveque** [comment]
@qiluo-msft: The test was showing as failed, which is why I issued the retest. If it was still running, it wasn't reflected properly here.

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by ciju-juniper** [comment]
This fixes https://github.com/Azure/sonic-buildimage/issues/4646
Built an image and tested.

**Comment by qiluo-msft** [comment]
Sorry @Staphylo, I don't know what happens to Github. After I merge this PR, the commit shows my name https://github.com/Azure/sonic-buildimage/commit/719c8e68c84941b895ff89d884d9f4ef8973e10a

Credit should go to you.

**Comment by jleveque** [comment]
Interesting. GitHub used to display "<user x> authored and <user y> committed". Maybe something changed with the new redesign?

**Comment by Staphylo** [comment]
No worries, I don't mind it. The fix was the important thing ^^

**Comment by qiluo-msft** [comment]
It turns out somehow I mistakenly merge instead of squash merge, so there is fork and merge in the history and your original commit is also in the history before.

**Pull request merged**
