### PR TITLE
[device/celestica] Implement PSU APIs based on the new platform API

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- What I did**

- Implement part of the Chassis and Psu related APIs.
- Psu APi
  - get_fan()
  - set_status_led()

**- How I did it**
1. Implement API based on sonic platform API base
3. Init Psu list in Chassis class.

**- How to verify it**
- Update HLX psu driver (https://github.com/Azure/sonic-buildimage/pull/2871)
- Create python script follow the new platform API design doc to verify it (Azure/SONiC#285.)

Signed-off-by: Wirut Getbamrung wgetbumr@celestica.com

### CODE REVIEW

**Comment by lguohan** [comment]
retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by mudsut4ke** [comment]
@lguohan , Can you merge this PR first ?
I will submit another API

**Comment by jleveque** [comment]
Retest vs please

**Comment by mudsut4ke** [comment]
Can you merge this PR ?

**Pull request merged**
