### PR TITLE
Submodule update

### PR DESCRIPTION
**Pull request by prsunny**
**- What I did**

Submodule update for 
1. sonic-py-swsssdk
2. sonic-snmpagent 
3. sonic-utilities

### CODE REVIEW

**Comment by lguohan** [comment]
conflict, can you check?

**Comment by yxieca** [comment]
The conflict is kind of expected with Qi's PR #1350. And it should be easy to resolve.

**Comment by prsunny** [comment]
@yxieca, I did a merge from upstream and seems to have resolved the conflict. Can you check.

**Comment by stcheng** [comment]
@prsunny what's this pull request's update?

**Pull request merged**
