### PR TITLE
[Broadcom SAI] upgrade to version 3.1.3.5-6

### PR DESCRIPTION
**Pull request by yxieca**
Signed-off-by: Ying Xie <ying.xie@microsoft.com>

**- What I did**
Upgrade Broadcom SAI to 3.1.3.5-6

### CODE REVIEW

**Comment by lguohan** [comment]
we have header changes, need to update the SAI header in sairedis

**Comment by zhenggen-xu** [comment]
It would be good to list the feature added and/or bugs fixed when libsai was upgraded.
In this particular upgrade, what was the change?

**Comment by wendani** [comment]
This upgrade adds the handler to support sai attribute SAI_PORT_ATTR_PKT_TX_ENABLE

**Comment by yxieca** [comment]
Closing this PR. It is likely that we need to upgrade to the next version to pick up the SAI header changes.

**Pull request closed without merging**
