### PR TITLE
[201811] Build debug dockers and debug one image

### PR DESCRIPTION
**Pull request by renukamanavalan**
1) Build debug docker image for each docker
2) Install debug tools in every debug docker image
3) Install available debug symbols in debug docker image
4) Provide additional host/docker mapping for host dirs /src & /debug
    4.1) The one-image will have source code under /src
    4.2) /debug is mapped as rw. User can put his core file there and use this dir to
         collect debug session logs too.
5) Build debug image using debug dockers
6) Source code is archived into /src of debug image
7) The welcome banner is extended to display these additional facilities in debug image.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
what is the relation with #3098

**Comment by renukamanavalan** [comment]
Same feature, but cannot be cherry picked. So completely re-done for Nov branch, where dockers are not stretch based. Plus, many of the debug symbols that are available in master is not available in Nov. 

This is the initial checkin.

After this, I plan to do a comparison with Masters and see how we can get more symbols for Nov, as this is crucial/important for us.

**Comment by jleveque** [comment]
Why does the title of this PR begin with "1)"? #1 of what?

**Comment by renukamanavalan** [comment]
I missed to notice/remember that first line of comments become the title. Corrected.

**Comment by jleveque** [comment]
When creating a PR against any branch other than master, I have been prepending the branch name to the beginning of the title. I believe this helps eliminate confusion when looking over the PRs. For example, I suggest you rename this PR as follows:

[201811] Build debug dockers and debug one image

**Pull request merged**
