### PR TITLE
[Build]: Add debian host base image version to support the reproducible build

### PR DESCRIPTION
**Pull request by xumia**
#### Why I did it
[Build]: Add debian host base image version to support the reproducible build

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by liushilongbuaa — APPROVED** [review]

**Comment by bluecmd** [comment]
I'm trying to get this patch to compile on [my fork](https://github.com/kamelnetworks/sonic-buildimage/tree/202111) and it seems the error I am getting is:
```
[..]
2022-01-05T15:12:48.9425728Z 
2022-01-05T15:12:48.9426322Z 2022-01-05 15:12:48 (119 MB/s) - 'target/baseimage/var/cache/apt/archives/libssl1.1_1.1.1k-1+deb11u1_amd64.deb' saved [1554464/1554464]
2022-01-05T15:12:48.9426584Z 
2022-01-05T15:12:48.9426887Z No found package or found multiple package for package libstdc++6, url: 
2022-01-05T15:12:48.9427392Z [  FAIL LOG END  ] [ target/sonic-aboot-broadcom.swi ]
2022-01-05T15:12:48.9427864Z make: *** [slave.mk:990: target/sonic-aboot-broadcom.swi] Error 1
2022-01-05T15:12:56.8836379Z make[1]: *** [Makefile.work:304: target/sonic-aboot-broadcom.swi] Error 2
2022-01-05T15:12:56.8837291Z make[1]: Leaving directory '/agent/_work/1/s'
2022-01-05T15:12:56.8837999Z make: *** [Makefile:33: target/sonic-aboot-broadcom.swi] Error 2
2022-01-05T15:12:56.9048575Z ##[error]Bash exited with code '2'.
2022-01-05T15:12:56.9092898Z ##[section]Finishing: Build sonic image
```

The only changes my fork has to the main one is a custom Azure DevOps pipeline job and a patch to mark the VERSION so I know what versions were built by our pipeline.

Full log at https://dev.azure.com/kamelnetworks/53a5c7e8-3f52-4611-a688-a61ab05a4216/_apis/build/builds/24/logs/10.
What could the issue be? Is there an `apt-get update` missing somewhere maybe?

**Comment by xumia** [comment]
@bluecmd , thanks for finding the issue. 
It is caused by url encoding issue.
I sent a PR to fix it, https://github.com/Azure/sonic-buildimage/pull/9683

**Pull request merged**
