### PR TITLE
[sonic-restapi] Update submodule

### PR DESCRIPTION
**Pull request by prsunny**
**- Why I did it**
[Submodule update]
```
ed640ac - 2020-06-09 : Program VNET routes to APP DB instead of Config DB (#45) [Prince Sunny]
c99ad62 - 2020-06-08 : Rename Go package (#43) [Sumukha Tumkur Vani]
65193ca - 2020-06-07 : Monitor certs only for https endpoint (#44) [Prince Sunny]

```

### CODE REVIEW

**Comment by prsunny** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Comment by prsunny** [comment]
retest vsimage please

**Pull request merged**
