### PR TITLE
fix Z9100 port index issue

### PR DESCRIPTION
**Pull request by aravindmani-1**
**- What I did**
Fixed port indexing issue in Z9100 for AP

**- How I did it**
Used overriding method to fix the port index issue.
**- How to verify it**
Check sfpshow presence,eeprom and do OIR,verify whether the appropriate port status is getting updated or not.
**- Description for the changelog**
UT log:[z9100_indexing_UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/4367472/z9100_indexing_UT_logs.txt)

### CODE REVIEW

**Comment by jleveque** [comment]
@aravindmani-1: Should this PR be cherry-picked into 201911? 201811? Both?

**Comment by aravindmani-1** [comment]
@jleveque Can you please cherry-pick it for both branches(201811 & 201911)?.

**Comment by yxieca** [comment]
@aravindmani-1 can you create another PR for 201811 branch? this PR cannot be cherry-picked cleanly to 201811 branch. Thanks!

**Comment by aravindmani-1** [comment]
Hi Ying,

From the November branch code, i could see that the get_sfp functions ,API 2.0 functions are not invoked currently from xcvrd. I'll raise the Pull request for 201811 branch when needed.

Thanks,
Aravind.

**Pull request merged**
