### PR TITLE
[sonic-utilities] Update submodule

### PR DESCRIPTION
**Pull request by jleveque**
* src/sonic-utilities 42cab68...0430083 (18):
  > [generate_dump] allow to extend dump with plugin scripts. (#1335)
  > [Mellanox] Add support for SN4600 system (#1462)
  > [route_check]: Dropped redundant code. (#1463)
  > [vlan] Vlan deletion is not allowed when there are members assigned to this VLAN. (#1420)
  > [decode-syseeprom] Refactor use of swsscommon; Add unit tests (#1444)
  > [dpb|config] Fix the validation logic of breakout mode (#1440)
  > [doc] Add documentation for console feature switch (#1456)
  > Update SonicDBConfig APIs for centralize_database (#1441)
  > Added CLI reference for buffer-pool watermark|persistent-watermark commands (#1426)
  > [ci] No longer pass '--privileged' option to slave container (#1446)
  > Refactor neighbor_advertiser script and use mock for testing (#1427)
  > [sfputil] Refactor to utilize sonic-platform package (#1421)
  > [sfpshow] Cleanup (#1405)
  > Add new cli for SAI_INGRESS_PRIORITY_GROUP_STAT_DROPPED_PACKETS counter in counterpoll utility (#1355)
  > [config] Prevent deleting VLAN with IP addresses. (#1429)
  > [show] Issue in CLI output alignment with shorter alias names in intf naming mode "alias" #1397 (#1411)
  > [psuutil] Refactor to utilize sonic-platform package (#1434)
  > [decode-syseeprom] Refactor to utilize sonic-platform package (#1435)

### CODE REVIEW

**Comment by jleveque** [comment]
@samaity, @praveen-li: The `test_breakout_modes` test is failing on this submodule update. Can you please look into this?

**Comment by praveen-li** [comment]
@jleveque sure let me have a look

**Comment by praveen-li** [comment]
@samaity can u list the PR here about VS platform.json

**Comment by samaity** [comment]
> @samaity can u list the PR here about VS platform.json

yes @praveen-li, You are right. https://github.com/Azure/sonic-buildimage/pull/6831  has the latest changes regarding vs related platform.json changes which are needed to build vs successfully if we include [#1440PR]([dpb|config] Fix the validation logic of breakout mode (#1440)) in submodule update.

**Comment by jleveque** [comment]
@samaity:  https://github.com/Azure/sonic-buildimage/pull/6831 is blocked by its own check build failures. https://github.com/Azure/sonic-utilities/pull/1440 should have had a disclaimer that it should not be merged until https://github.com/Azure/sonic-buildimage/pull/6831. What is the status of https://github.com/Azure/sonic-buildimage/pull/6831?

**Comment by samaity** [comment]
> Azure/sonic-utilities#1440

@jleveque, sure. I just updated the sonic-utilities submodule as the `sonic-utilities` deb package was getting failed in #6831 PR. waiting for the result.

**Comment by liat-grozovik** [comment]
@lguohan and @jleveque why this one is closed? do we have another PR for updating the utilities submodule with all the above?

**Comment by jleveque** [comment]
@liat-grozovik : PR https://github.com/Azure/sonic-buildimage/pull/6831 updated the sonic-utilities submodule

**Pull request closed without merging**
