### PR TITLE
[sonic-platform-daemons] Update submodule

### PR DESCRIPTION
**Pull request by bratashX**
Signed-off-by: Petro Bratash <petrox.bratash@intel.com>

Update sonic-platform-daemons:

- [thermalctld] [psud] [chassisd] Fix crash with undefined environment variable
https://github.com/Azure/sonic-platform-daemons/commit/f63ec30521d690e9bbef76fdbbed52e4af56ec44

- [sonic-platform-daemons] Add more physical entity information to DB for physical entity mib
 https://github.com/Azure/sonic-platform-daemons/commit/ef15ff51dfc70791d0b31d097e56e70ef6c25441

### CODE REVIEW

**Comment by bratashX** [comment]
@akokhan

**Comment by jleveque** [comment]
@bratashX: There are build failures. Can you please check?

```
01:33:00  ______________________ test_updater_thermal_check_min_max ______________________
01:33:00  
01:33:00      def test_updater_thermal_check_min_max():
01:33:00          chassis = MockChassis()
01:33:00      
01:33:00          thermal = MockThermal()
01:33:00          chassis.get_all_thermals().append(thermal)
01:33:00      
01:33:00          chassis.set_modular_chassis(True)
01:33:00          chassis.set_my_slot(1)
01:33:00          temperature_updater = TemperatureUpdater(SYSLOG_IDENTIFIER, chassis)
01:33:00      
01:33:00          temperature_updater.update()
01:33:00          slot_dict = temperature_updater.chassis_table.get('Thermal 1')
01:33:00  >       assert slot_dict['minimum_temperature'] == str(thermal.get_minimum_recorded())
01:33:00  E       TypeError: 'NoneType' object has no attribute '__getitem__'
01:33:00  
01:33:00  tests/test_thermalctld.py:341: TypeError
```

**Comment by mprabhu-nokia** [comment]
> 
> 
> @bratashX: There are build failures. Can you please check?
> 
> ```
> 01:33:00  ______________________ test_updater_thermal_check_min_max ______________________
> 01:33:00  
> 01:33:00      def test_updater_thermal_check_min_max():
> 01:33:00          chassis = MockChassis()
> 01:33:00      
> 01:33:00          thermal = MockThermal()
> 01:33:00          chassis.get_all_thermals().append(thermal)
> 01:33:00      
> 01:33:00          chassis.set_modular_chassis(True)
> 01:33:00          chassis.set_my_slot(1)
> 01:33:00          temperature_updater = TemperatureUpdater(SYSLOG_IDENTIFIER, chassis)
> 01:33:00      
> 01:33:00          temperature_updater.update()
> 01:33:00          slot_dict = temperature_updater.chassis_table.get('Thermal 1')
> 01:33:00  >       assert slot_dict['minimum_temperature'] == str(thermal.get_minimum_recorded())
> 01:33:00  E       TypeError: 'NoneType' object has no attribute '__getitem__'
> 01:33:00  
> 01:33:00  tests/test_thermalctld.py:341: TypeError
> ```

Looks like the thermal name format changed. Could you please prefix this with the default parent name? Ideally, we should have set the name in MockThermal like MockFanDrawer and then we can use thermal.get_name() below as well. 
```
slot_dict = temperature_updater.chassis_table.get('Thermal 1')
```

**Comment by bratashX** [comment]
@mprabhu-nokia Thanks you.  Fix: https://github.com/Azure/sonic-platform-daemons/pull/121

**Pull request closed without merging**
