### PR TITLE
 DellEMC: DellEMC platform bug fixes

### PR DESCRIPTION
**Pull request by srideepDell**
* Dynamic bus detection and loading driver for eeprom on s5248,s5232
          * sfputil fix for S5248

**- What I did**
           * Dynamic bus detection and loading driver for eeprom on s5248,s5232
          * sfputil fix for S5248
**- How I did it**
       Modified  Dell EMC platform specific files
**- How to verify it**
      Verified on S5232 and S5248 platfoms.
      logs below.
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by srideepDell** [comment]
Logs from commands for the changes

root@sonic:/# show  platform syseeprom
TlvInfo Header:
   Id String:    TlvInfo
   Version:      1
   Total Length: 180
TLV Name             Code Len Value
-------------------- ---- --- -----
Product Name         0x21   9 S5248F-ON
Part Number          0x22   6 01XR4W
Serial Number        0x23  20 CN046MRJCES0085E0016
Base MAC Address     0x24   6 54:BF:64:BA:3E:C0
Manufacture Date     0x25  19 01/15/2017 11:03:36
Device Version       0x26   1 1
Label Revision       0x27   3 X01
Platform Name        0x28  30 x86_64-dellemc_s5248f_c2538-r0
ONIE Version         0x29  10 3.40.1.1-6
MAC Addresses        0x2A   2 256
Manufacturer         0x2B   5 77931
Manufacture Country  0x2C   2 CN
Vendor Name          0x2D   8 DELL EMC
Diag Version         0x2E  10 3.40.4.1-2
Service Tag          0x2F   7 GCPQG02
Vendor Extension     0xFD   4
CRC-32               0xFE   4 0xD5CB85D8

(checksum valid)

root@sonic:/# show  interfaces status
  Interface            Lanes    Speed    MTU                 Alias    Vlan    Oper    Admin                    Type    Asym PFC
-----------  ---------------  -------  -----  --------------------  ------  ------  -------  ----------------------  ----------
  Ethernet0               49      25G   9100   twentyfiveGigE1/1/1  routed      up       up          SFP/SFP+/SFP28         N/A
  Ethernet1               50      25G   9100   twentyfiveGigE1/1/2  routed      up       up          SFP/SFP+/SFP28         N/A
  Ethernet2               51      25G   9100   twentyfiveGigE1/1/3  routed    down       up                     N/A         N/A
  Ethernet3               52      25G   9100   twentyfiveGigE1/1/4  routed    down       up                     N/A         N/A
  Ethernet4               57      25G   9100   twentyfiveGigE1/2/1  routed    down       up                     N/A         N/A
  Ethernet5               58      25G   9100   twentyfiveGigE1/2/2  routed    down       up                     N/A         N/A
  Ethernet6               59      25G   9100   twentyfiveGigE1/2/3  routed    down       up                     N/A         N/A
  Ethernet7               60      25G   9100   twentyfiveGigE1/2/4  routed    down       up                     N/A         N/A
  Ethernet8               61      25G   9100   twentyfiveGigE1/3/1  routed    down       up                     N/A         N/A
  Ethernet9               62      25G   9100   twentyfiveGigE1/3/2  routed    down       up                     N/A         N/A
 Ethernet10               63      25G   9100   twentyfiveGigE1/3/3  routed    down       up                     N/A         N/A
 Ethernet11               64      25G   9100   twentyfiveGigE1/3/4  routed    down       up                     N/A         N/A
 Ethernet12               77      25G   9100   twentyfiveGigE1/4/1  routed    down       up                     N/A         N/A
 Ethernet13               78      25G   9100   twentyfiveGigE1/4/2  routed    down       up                     N/A         N/A
 Ethernet14               79      25G   9100   twentyfiveGigE1/4/3  routed    down       up                     N/A         N/A
 Ethernet15               80      25G   9100   twentyfiveGigE1/4/4  routed    down       up                     N/A         N/A
 Ethernet16               85      25G   9100   twentyfiveGigE1/5/1  routed      up       up          SFP/SFP+/SFP28         N/A
 Ethernet17               86      25G   9100   twentyfiveGigE1/5/2  routed      up       up          SFP/SFP+/SFP28         N/A
 Ethernet18               87      25G   9100   twentyfiveGigE1/5/3  routed    down       up                     N/A         N/A
 Ethernet19               88      25G   9100   twentyfiveGigE1/5/4  routed    down       up                     N/A         N/A
 Ethernet20               93      25G   9100   twentyfiveGigE1/6/1  routed    down       up                     N/A         N/A
 Ethernet21               94      25G   9100   twentyfiveGigE1/6/2  routed    down       up                     N/A         N/A
 Ethernet22               95      25G   9100   twentyfiveGigE1/6/3  routed    down       up                     N/A         N/A
 Ethernet23               96      25G   9100   twentyfiveGigE1/6/4  routed    down       up                     N/A         N/A
 Ethernet24               13      25G   9100   twentyfiveGigE1/7/1  routed    down       up                     N/A         N/A
 Ethernet25               14      25G   9100   twentyfiveGigE1/7/2  routed    down       up                     N/A         N/A
 Ethernet26               15      25G   9100   twentyfiveGigE1/7/3  routed    down       up                     N/A         N/A
 Ethernet27               16      25G   9100   twentyfiveGigE1/7/4  routed    down       up                     N/A         N/A
 Ethernet28               21      25G   9100   twentyfiveGigE1/8/1  routed    down       up                     N/A         N/A
 Ethernet29               22      25G   9100   twentyfiveGigE1/8/2  routed    down       up                     N/A         N/A
 Ethernet30               23      25G   9100   twentyfiveGigE1/8/3  routed    down       up                     N/A         N/A
 Ethernet31               24      25G   9100   twentyfiveGigE1/8/4  routed    down       up                     N/A         N/A
 Ethernet32               29      25G   9100   twentyfiveGigE1/9/1  routed    down       up                     N/A         N/A
 Ethernet33               30      25G   9100   twentyfiveGigE1/9/2  routed    down       up                     N/A         N/A
 Ethernet34               31      25G   9100   twentyfiveGigE1/9/3  routed    down       up                     N/A         N/A
 Ethernet35               32      25G   9100   twentyfiveGigE1/9/4  routed    down       up                     N/A         N/A
 Ethernet36               97      25G   9100  twentyfiveGigE1/10/1  routed    down       up                     N/A         N/A
 Ethernet37               98      25G   9100  twentyfiveGigE1/10/2  routed    down       up                     N/A         N/A
 Ethernet38               99      25G   9100  twentyfiveGigE1/10/3  routed    down       up                     N/A         N/A
 Ethernet39              100      25G   9100  twentyfiveGigE1/10/4  routed    down       up                     N/A         N/A
 Ethernet40              105      25G   9100  twentyfiveGigE1/11/1  routed    down       up                     N/A         N/A
 Ethernet41              106      25G   9100  twentyfiveGigE1/11/2  routed    down       up                     N/A         N/A
 Ethernet42              107      25G   9100  twentyfiveGigE1/11/3  routed    down       up                     N/A         N/A
 Ethernet43              108      25G   9100  twentyfiveGigE1/11/4  routed    down       up                     N/A         N/A
 Ethernet44              113      25G   9100  twentyfiveGigE1/12/1  routed    down       up                     N/A         N/A
 Ethernet45              114      25G   9100  twentyfiveGigE1/12/2  routed    down       up                     N/A         N/A
 Ethernet46              115      25G   9100  twentyfiveGigE1/12/3  routed    down       up                     N/A         N/A
 Ethernet47              116      25G   9100  twentyfiveGigE1/12/4  routed    down       up                     N/A         N/A
 Ethernet48  121,122,123,124     100G   9100       hundredGigE1/49  routed      up       up         QSFP28 or later         N/A
 Ethernet49  125,126,127,128     100G   9100       hundredGigE1/50  routed    down       up                     N/A         N/A
 Ethernet50      69,70,71,72     100G   9100       hundredGigE1/51  routed      up       up         QSFP28 or later         N/A
 Ethernet51      65,66,67,68     100G   9100       hundredGigE1/52  routed    down       up                     N/A         N/A
 Ethernet52          1,2,3,4     100G   9100       hundredGigE1/53  routed    down       up  Unknown or unspecified         N/A
 Ethernet53      33,34,35,36     100G   9100       hundredGigE1/54  routed    down       up                 Unknown         N/A
 Ethernet54          5,6,7,8     100G   9100       hundredGigE1/55  routed    down       up                     N/A         N/A
 Ethernet55      41,42,43,44     100G   9100       hundredGigE1/56  routed    down       up                     N/A         N/A
root@sonic:/#

**Comment by srideepDell** [comment]
restest vsimage please

**Comment by srideepDell** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vs please

**Comment by srideepDell** [comment]
Retest vsimage please

**Comment by srideepDell** [comment]
Retest vs please

**Pull request merged**
