### PR TITLE
Change redis conf: listen on unix socket

### PR DESCRIPTION
**Pull request by qiluo-msft**

### CODE REVIEW

**Comment by stcheng** [comment]
Could you explain more about this change?

**Comment by qiluo-msft** [comment]
By default redis-server will listening on localhost TCP port. This PR will make it also listening on domain socket, which will have better client-server performance.

**Comment by stcheng** [comment]
What process is doing the domain socket?

**Comment by qiluo-msft** [comment]
Plan to change all the client to use domain socket (unix socket), including orchagent, intfsyncd, etc...

**Pull request merged**
