### PR TITLE
[dockers] Rename 'docker-lldp-sv2' to 'docker-lldp'

### PR DESCRIPTION
**Pull request by jleveque**
The `-sv2` suffix was used to differentiate SNMP Dockers when we transitioned from "SONiCv1" to "SONiCv2", about four years ago. The old Docker materials were removed long ago; there is no need to keep this suffix. Removing it aligns the name with all the other Dockers.

### CODE REVIEW

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest broadcom please

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Pull request merged**
