### PR TITLE
[build] Extend rules/config.user to more Makefiles

### PR DESCRIPTION
**Pull request by bluecmd**
rules/config.user allows overriding default properties without
touching tracked files. This change makes sure all properties
can be set and not just the ones used in slave.mk.

#### Why I did it

I want to set `SONIC_CONFIG_USE_NATIVE_DOCKERD_FOR_BUILD` which is read by `Makefile.work`.

#### How I did it

I extended the existing functionality introduced in https://github.com/Azure/sonic-buildimage/pull/5325.

#### How to verify it

```
echo 'SONIC_CONFIG_USE_NATIVE_DOCKERD_FOR_BUILD = y` > rules/config.user
make [some target]
ps ax | grep 'docker.sock' --color
# Verify that the docker container running has  -v /var/run/docker.sock:/var/run/docker.sock set.
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog

Extending functionality of `rules/config.user` to include all build options.

#### A picture of a cute animal (not mandatory but encouraged)
image

### CODE REVIEW

**Comment by bluecmd** [comment]
@Staphylo: You did the initial addition of the config.user, what do you say about this addition?

**Comment by bluecmd** [comment]
Not sure why `Azure.sonic-buildimage (Test kvmtest-t0) Failing after 53m — Test kvmtest-t0 failed` is happening. Hints welcome!

**Comment by Staphylo** [comment]
That change looks good to me. I actually missed that `include rules/config` reference in `Makefile.work` so thanks for the fix!
It was indeed the intention to include the user config everywhere the base config is included.

Regarding the test runs, you'll have to wait for a project owner to restart the failed jobs.
I'm not sure if the job re-trigger knobs via comments are back with the azure pipelines.

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
now there is command like "/azpw run"

**Pull request merged**
