### PR TITLE
[CoPP] Add always_enabled field

### PR DESCRIPTION
**Pull request by noaOrMlnx**
#### Why I did it
Add the "always_enabled" field to copp_cfg.j2 file, in order to allow traps without an entry in features table, to be installed automatically.

#### How I did it
Add the new field, and changed the logic in sonic-swss.
In addition, add all of the enabled features to init_cfg.json.j2 file in order to have the UT passing. 
#### How to verify it
Check that arp, udld, ip2me and lacp traps are auto installed, and traps that has no feature entry are not auto installed.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [x] 202106

### CODE REVIEW

**Review by dgsudharsan — DISMISSED** [review]

**Review by prsunny — DISMISSED** [review]

**Comment by qiluo-msft** [comment]
Seems lgtm feel difficult to fetch old commit on your forked repo. Could you rebase your commits onto latest master?

**Comment by noaOrMlnx** [comment]
> Seems lgtm feel difficult to fetch old commit on your forked repo. Could you rebase your commits onto latest master

@qiluo-msft 
Done

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
@dgsudharsan , please sign-off

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by prsunny** [comment]
Please raise a separate PR for 202012

**Pull request merged**
