### PR TITLE
[device/celestica]: Fix failed test cases of Haliburton platform API

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- Why I did it**
- To fix failed test cases of Haliburton platform APIs that found on [platform_tests](https://github.com/Azure/sonic-mgmt/tree/master/tests/platform_tests/api) script

**- How I did it**
1. Add device/celestica/x86_64-cel_e1031-r0/platform.json 
2. Update functions to support python3.7
3. Add more functions follow latest sonic_platform_base
4. Fix the bug

 **- How to verify it**
- Run  [platform_tests](https://github.com/Azure/sonic-mgmt/tree/master/tests/platform_tests/api) script

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [x] 201911
- [x] 202006
- [x] 202012

Signed-off-by: Wirut Getbamrung [wgetbumr@celestica.com]

### CODE REVIEW

**Comment by mudsut4ke** [comment]
@jleveque , Can you please review and merge this PR ?
But before that please help cherry-pick https://github.com/Azure/sonic-buildimage/pull/6493 to 202012 branch first to avoid conflict on 202012

**Comment by yxieca** [comment]
@sujinmkang please review this PR.

**Comment by yxieca** [comment]
@mudsut4ke  please create an PR for 202012 branch. This change will break 202012 build due to platform.json format differences.

**Comment by mudsut4ke** [comment]
> @mudsut4ke please create an PR for 202012 branch. This change will break 202012 build due to platform.json format differences.

@yxieca ,In this PR  https://github.com/Azure/sonic-buildimage/pull/8217, I have cherry-picked a change from https://github.com/Azure/sonic-buildimage/pull/6493 to the 202012 branch
Please help to review and merge

**Review by sujinmkang — APPROVED** [review]

**Review by sujinmkang — APPROVED** [review]

**Comment by mudsut4ke** [comment]
@sujinmkang @yxieca , Please also merge another PR to 202012 branch https://github.com/Azure/sonic-buildimage/pull/8297

**Pull request merged**
