### PR TITLE
[DPB] [Mellanox] added capability files for SN4600C platform

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
**- Why I did it**

`platform.json` and `hwsku.json` files are required for a feature called Dynamic Port Breakout

**- How I did it**

Created capability files according to platform specification `SN4600C`

**- How to verify it**

Full qualification requires bugs fixes reported under sonic-buildimage

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Review by liat-grozovik — COMMENTED** [review]
pls check also if we can enable more speeds when not splitting

**Comment by vadymhlushko-mlnx** [comment]
> pls check also if we can enable more speeds when not splitting

https://github.com/Azure/sonic-buildimage/pull/6021#issuecomment-745199046

**Comment by vadymhlushko-mlnx** [comment]
Please don't merge this PR until [[DPB][MLNX][YANG-models] extended regex pattern according to MLNX systems speeds requirements](https://github.com/Azure/sonic-buildimage/pull/6279) PR will be merged

**Review by liat-grozovik — COMMENTED** [review]
please doble check the non default SKU is up to date with port_conifg.ini

**Comment by liat-grozovik** [comment]
retest mellanox please

**Comment by vadymhlushko-mlnx** [comment]
retest vsimage please

**Comment by vadymhlushko-mlnx** [comment]
retest mellanox please

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
