### PR TITLE
[Mellanox] Fix thermal control bugs 

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**- What I did**

1. Fix issue: add PSU fan no matter sysfs exists or not
2. Fix issue: get fan direction per drawer index instead of per fan index
3. Fix issue: clarify logs for PSU absence and PSU power off
4. Add 2100/2010 support to get fan presence status
5. Fix issue: pmon docker exists on 3800
6. Add unit test for code changes 

**- How I did it**

**- How to verify it**

Manually verify and run existing regression cases

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
I closed review https://github.com/Azure/sonic-buildimage/pull/4252 and created this new one. I did a rebase for build issue in previous review.

**Comment by jleveque** [comment]
Retest this please

**Comment by Junchao-Mellanox** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Looks good to me. I'd just like someone else from Mellanox to review and approve.

**Comment by Junchao-Mellanox** [comment]
@kebol could you please help review?

**Comment by abdosi** [comment]
@Junchao-Mellanox Please create PR for 201911. There is merge conflict.
Removing Request for 201911 Label

@rlhui @liat-grozovik

**Pull request merged**
