### PR TITLE
[codeowners]: Add some auto reviewers for sonic-yang-models folder

### PR DESCRIPTION
**Pull request by qiluo-msft**
#### Why I did it
Add some auto reviewers for sonic-yang-models folder

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by qiluo-msft** [comment]
@praveen-li @dgsudharsan @rathnasabapathyv @venkatmahalingam
I added you guys as 'Triage' role in this repo. Please accept this invitation in your github associated email.

**Comment by zhangyanzhao** [comment]
Thanks @qiluo-msft  for the quick action.

**Review by zhangyanzhao — DISMISSED** [review]

**Review by lguohan — COMMENTED** [review]
can you add you as owner for this?

**Comment by qiluo-msft** [comment]
> can you add you as owner for this?

Sure.

**Review by zhangyanzhao — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Not impact build, so merge without passing checkers.

**Pull request merged**
