### PR TITLE
[Arista] Update platform submodules

### PR DESCRIPTION
**Pull request by Staphylo**
- Refactor pci topology logic for chassis (fixes some chassis commands and chassisd on linecard)
 - Introduce new cooling algorithm
 - Fix linecard poweroff logic when supervisor is going down
 - Fix linecard status led leading to `system-health` crashing
 - Misc fixes

### CODE REVIEW

**Comment by kenneth-arista** [comment]
Tagging @arlakshm for awareness

**Review by arlakshm — APPROVED** [review]

**Pull request merged**
