### PR TITLE
[device/celestica]: DX010 platform API update

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- Why I did it**
- Various fixes and improvement

**- How I did it**
- Fix fancontrol.service path
- Fix return temp format in thermal API
- Improve init time in chassis API
- Upgrade sfp API

**- How to verify it**
- Run `show platform` command 
  - [dx010-api-update.log](https://github.com/Azure/sonic-buildimage/files/4633825/dx010-api-update.log)

### CODE REVIEW

**Comment by mudsut4ke** [comment]
@pphuchar , Can you help review this ?

**Comment by jleveque** [comment]
Wait for review from @pphuchar.

**Comment by mudsut4ke** [comment]
@jleveque , Please also help add tag for merge this change to 201911 branch

**Comment by abdosi** [comment]
@mudsut4ke Please create seprate PR for 201911. There are conflicts.

@rlhui

**Comment by mudsut4ke** [comment]
@abdosi , OK

**Pull request merged**
