### PR TITLE
[Juniper] Updating platform documentation

### PR DESCRIPTION
**Pull request by ciju-juniper**
This patch set updates the documentation for
QFX5200 & QFX5210 Juniper switching platforms.

Signed-off-by: Ciju Rajan K <crajank@juniper.net>

### CODE REVIEW

**Comment by ciju-juniper** [comment]
@jleveque Could you merge this documentation change?

**Comment by ciju-juniper** [comment]
retest broadcom please

**Comment by ciju-juniper** [comment]
retest vsimage please

**Comment by ciju-juniper** [comment]
retest mellanox please

**Comment by ciju-juniper** [comment]
@lguohan Please merge this patch. This is just a documentation update

**Review by lguohan — APPROVED** [review]

**Comment by ciju-juniper** [comment]
@lguohan Could you merge this now as all the builds are done? Thanks!

**Pull request merged**
