### PR TITLE
[sonic-py-swsssdk]: Update sonic-py-swsssdk submodule

### PR DESCRIPTION
**Pull request by mlok-nokia**
Signed-off-by: mlok <marty.lok@nokia.com>

#### Why I did it
Update sonic-py-swsssdk submodule to include below commits:
d07682e Merge pull request #111 from xumia/azp-coverage
482cac2 [Ethernet-IB][index] Modifed the port_util to support the VoQ Inband Port (#113)
69eac92 Support azp diff coverage

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by mlok-nokia** [comment]
@SuvarnaMeenakshi @qiluo-msft  Please review this PR, Thanks

**Review by qiluo-msft — DISMISSED** [review]

**Comment by mlok-nokia** [comment]
@qiluo-msft   The build failed. Should I rebase and re-run? or Another suggestion?

**Comment by anshuv-mfst** [comment]
@judyjoseph - FYI

**Comment by qiluo-msft** [comment]
In sonic-utilities unit test
https://github.com/Azure/sonic-py-swsssdk/compare/6be76f45705f35ae7a8baefea801558511cd68e7...740a44ce0ffba853dfbeb45c63d44c023055c8d9#diff-70932c8be17fb6930f6e4498f1a6335bbb2d925e76b174f44222619b46092f61R69
```
    if_name_map = db.get_all('COUNTERS_DB', 'COUNTERS_PORT_NAME_MAP', blocking)
```
This line actually calls swsssdk `SonicV2Connector.get_all()`. That function could not accept `blocking` as a positional argument. This is a bug in swsssdk repo.

**Comment by mlok-nokia** [comment]
> In sonic-utilities unit test
> [Azure/sonic-py-swsssdk@6be76f4...740a44cdiff-70932c8be17fb6930f6e4498f1a6335bbb2d925e76b174f44222619b46092f61R69](https://github.com/Azure/sonic-py-swsssdk/compare/6be76f45705f35ae7a8baefea801558511cd68e7...740a44ce0ffba853dfbeb45c63d44c023055c8d9diff-70932c8be17fb6930f6e4498f1a6335bbb2d925e76b174f44222619b46092f61R69)
> 
> ```
>     if_name_map = db.get_all('COUNTERS_DB', 'COUNTERS_PORT_NAME_MAP', blocking)
> ```
> 
> This line actually calls swsssdk `SonicV2Connector.get_all()`. That function could not accept `blocking` as a positional argument. This is a bug in swsssdk repo.

Since this bug is introduced by last commit in the sonic-py-swsssdk,  I just updated the submodule up to the previous commit.  And I will log note to that PR (which has been merged) to let the author know that it is a bug. Thanks

**Review by qiluo-msft — APPROVED** [review]

**Comment by mlok-nokia** [comment]
Duplicated with 8757

**Pull request closed without merging**
