### PR TITLE
[cfggen] Remove NatSorted

### PR DESCRIPTION
**Pull request by tahmed-dev**
Natural sorting of SONiC config gen output consumes lot of CPU cycles.
The sole use of natsorted was to make test comparison easier and so,
the natsorting logic is now relocated to the test suite. As a result
sonic-cfggen gained nearly 1 sec per call since we no longer import
natsorted module!

singed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
good improvement. is there a way to make sure the natsorted is not introduced again in the future accidentally? it is easier missed. especially, I am a little concern that if one of the dependency packages that sonic-cfggen uses will introduce natsorted. this is not a real concern for this pr. it is about future-proofing.

**Comment by tahmed-dev** [comment]
> good improvement. is there a way to make sure the natsorted is not introduced again in the future accidentally? it is easier missed. especially, I am a little concern that if one of the dependency packages that sonic-cfggen uses will introduce natsorted. this is not a real concern for this pr. it is about future-proofing.

Thanks! I am aware of putting a package on hold using apt `sudo apt-mark hold <package-name>` not sure about pip though. @jleveque is there something similart in pip? Or can we whitelist packages?

**Comment by tahmed-dev** [comment]
retest vsimage please

**Comment by tahmed-dev** [comment]
retest vsimage please

**Pull request merged**
