### PR TITLE
[BFN][master] Updated SDK packages to 20201216

### PR DESCRIPTION
**Pull request by akokhan**
Signed-off-by: Andriy Kokhan <andriyx.kokhan@intel.com>

**- Why I did it**
- Update SDK to newer version;
- Bugfixes

**- How I did it**

**- How to verify it**

### CODE REVIEW

**Comment by akokhan** [comment]
retest vsimage please

**Comment by akokhan** [comment]
retest vsimage please

**Comment by akokhan** [comment]
retest vsimage please

**Comment by akokhan** [comment]
@lguohan , @jleveque , could you please approve and merge this PR.

**Comment by lguohan** [comment]
can you describe bug fixes in detail?

**Comment by akokhan** [comment]
Closing this PR due to SONiC master migration to SAI v1.7.1

**Pull request closed without merging**
