### PR TITLE
[FRR]: Update frr to latest 7.2.1

### PR DESCRIPTION
**Pull request by pavel-shirshov**
**- What I did**
Updated frr to latest stable version

**- How I did it**
Changing default tag for frr

**- How to verify it**
Build an image and run on your dut

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
retest vs please

**Comment by pavel-shirshov** [comment]
retest vsimage please

**Comment by lguohan** [comment]
is this needed for 201911 branch? if yes, can you mark?

**Comment by pavel-shirshov** [comment]
@lguohan Sure. Thanks

**Comment by pavel-shirshov** [comment]
retest vs please

**Pull request merged**
