### PR TITLE
[pfx_filter]: Add a prefix mask by default in pfx_filter, when there is no one

### PR DESCRIPTION
**Pull request by pavel-shirshov**
**- Why I did it**
If some table with a list of tuples (interface name, ip prefix) has ip prefixes without a mask length, it will cause issues in SONiC. For example quagga and frr will treat ipv4 address without a mask, so "10.20.30.40" address will be treated as "10.0.0.0/8", which is dangerous. 

**- How I did it**
If pfx_filter get a tuple (interface name, ip prefix), where the ip prefix doesn't have prefix mask length, add a mask by default: "/32 for ipv4 addresses, /128 for ipv6 addresses".

**- How to verify it**
Run the unit tests from this PR.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
thanksk , looks like there are some test failures.

**Comment by pavel-shirshov** [comment]
retest vsimage please

**Comment by pavel-shirshov** [comment]
retest mellanox please

**Comment by pavel-shirshov** [comment]
retest vsimage please

**Pull request merged**
