### PR TITLE
[submodule] Update sonic-linux-kernel pointer to pick up new commits

### PR DESCRIPTION
**Pull request by keboliu**
**- Why I did it**
Update sonic-linux-kernel pointer to pick up new commits:

- Backport patches to increase critical threshold for ASIC and validate transceiver temperature a7c1af7c44edde90dff49d672071139043bcdb65  https://github.com/Azure/sonic-linux-kernel/commit/548e8e0be49692050ea4071d5e9945816bc5aacc
- [ci]: Set up CI with Azure Pipelines   548e8e0be49692050ea4071d5e9945816bc5aacc https://github.com/Azure/sonic-linux-kernel/commit/a7c1af7c44edde90dff49d672071139043bcdb65

**- How I did it**

update sonic-linux-kernel repo pointer

**- How to verify it**

run regression test

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by liat-grozovik** [comment]
retest vs please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Review by liat-grozovik — APPROVED** [review]

**Comment by keboliu** [comment]
retest Azure.sonic-buildimage please

**Comment by keboliu** [comment]
retest vsimage please

**Pull request merged**
