### PR TITLE
[sonic-py-swsssdk/snmpagent] update submodule for sonic-py-swsssdk / snmpagent

### PR DESCRIPTION
**Pull request by dzhangalibaba**
update multiDB changes in swsssdk, including:

* [MultiDB] add sonic-db-cli PING all instances support (#65)
* Revert "Revert "read portchannel name from LAG_NAME_MAP_TABLE in COUNTERS_DB (#51)" (#57)" (#64)

update snmpagent, including:
* add mock tables for LAG_NAME_MAP_TABLE in COUNTERS_DB (#114)
* Parse quagga output without knowledge about hostname, so robust against hostname changes or mismatch (#124)
* Fix quagga/FRR parser on IPv6 BGP sessions (#122)
* Fix index nodes in LLDP tables whose access right is not-accessible. (#112)
* Implement cbgpPeer2State in CiscoBgp4MIB (#119)

Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

### CODE REVIEW

**Comment by lguohan** [comment]
can you fix the build break?

**Comment by dzhangalibaba** [comment]
> can you fix the build break?

looks it caused by
Revert "Revert "read portchannel name from LAG_NAME_MAP_TABLE in COUNTERS_DB (#51)" (#57)" (#64)

My changes won't affect build.

**Comment by lguohan** [comment]
why not update only you commit?

**Comment by dzhangalibaba** [comment]
> why not update only your commit?

Revert "Revert "read portchannel name from LAG_NAME_MAP_TABLE in COUNTERS_DB (#51)" (#57)" (#64).    was in before my changes, but not updated head, it has some dependency on other commits.  How can I update my commit without some earlier commits ?

**Comment by lguohan** [comment]
https://github.com/Azure/sonic-snmpagent/commit/7632ee89caa8a485d68ce389f60f202fce197579 fix the build break issue.

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/3415/

looks like there are some snmp cpu failures.

**Comment by dzhangalibaba** [comment]
> https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/3415/
> 
> looks like there are some snmp cpu failures.

I did a test on updating the LAG changes in swsssdk and other commits on SNMP only. It also failed. I think the commits for snmp those are not updated submodule has issues. https://github.com/Azure/sonic-buildimage/pull/4459

add mock tables for LAG_NAME_MAP_TABLE in COUNTERS_DB (#114)
Parse quagga output without knowledge about hostname, so robust against hostname changes or mismatch (#124)
Fix quagga/FRR parser on IPv6 BGP sessions (#122)
Fix index nodes in LLDP tables whose access right is not-accessible. (#112)
Implement cbgpPeer2State in CiscoBgp4MIB (#119)

**Comment by lguohan** [comment]
retest vsimage please

**Comment by judyjoseph** [comment]
May be this would need the updated sonic-swss-common submodule too ? 
https://github.com/Azure/sonic-swss/pull/885#issuecomment-535714914.                                         
 I am updating the sonic-swss and sonic-swss-common via this PR https://github.com/Azure/sonic-buildimage/pull/4465. So will try this again after that is committed.

**Comment by judyjoseph** [comment]
Meanwhile @dzhangalibaba  In this PR Could you again advance the sonic-py-swssdk submodule  ? I did the merge namespace changes in SonicV2Connector/SonicDBConfig and I am looking forward to advance the pointer again -- could do it here in this PR itself.

**Comment by qiluo-msft** [comment]
retest vsimage please

**Comment by zhenggen-xu** [comment]
@dzhangalibaba @judyjoseph What are needed to make 201911 branch work while advancing the snmpagent submodule to take some changes (BGP metrics etc)?

**Comment by lguohan** [comment]
retest vsimage please

**Comment by judyjoseph** [comment]
retest vsimage please

**Comment by judyjoseph** [comment]
@dzhangalibaba vsimage tests are passing now after the swss module updates. I have few more updates in sonic-swsssdk-py module. Shall I add it here ?

**Comment by dzhangalibaba** [comment]
> @dzhangalibaba vsimage tests are passing now after the swss module updates. I have few more updates in sonic-swsssdk-py module. Shall I add it here ?

Namespace support in SonicV2Connector (#63).    Want to update this as well ?

**Comment by judyjoseph** [comment]
> > @dzhangalibaba vsimage tests are passing now after the swss module updates. I have few more updates in sonic-swsssdk-py module. Shall I add it here ?
> 
> Namespace support in SonicV2Connector (#63). Want to update this as well ?

Yes, sure thanks

**Comment by dzhangalibaba** [comment]
> > > @dzhangalibaba vsimage tests are passing now after the swss module updates. I have few more updates in sonic-swsssdk-py module. Shall I add it here ?
> > 
> > 
> > Namespace support in SonicV2Connector (#63). Want to update this as well ?
> 
> Yes, sure thanks

OK. will update the head here

**Comment by dzhangalibaba** [comment]
previous checks passed , now update sonic-py-swsssdk to Namespace support in SonicV2Connector (#63) as Judy's need. @judyjoseph

**Comment by dzhangalibaba** [comment]
retest broadcom please

**Comment by dzhangalibaba** [comment]
retest vs please

**Comment by judyjoseph** [comment]
retest vs please

**Comment by judyjoseph** [comment]
retest vs please

**Comment by abdosi** [comment]
sonic-pyswssdk is updated with relevant PR's for 201911

**Pull request merged**
