### PR TITLE
DellEMC Z9100 : Platform2.0 API implementation [PSU, Thermal]

### PR DESCRIPTION
**Pull request by ArunSaravananBalachandran**
**- What I did**

- Implement PSU and Thermal platform2.0 API for DellEMC Z9100 platform
- Implement get_system_eeprom_info API

**- How I did it**

- Added new files psu.py and thermal.py for PSU and thermal platform2.0 API implementation
- Made change in eeprom.py for implementing get_system_eeprom_info 

**- How to verify it**

Wrote python script to load Chassis class and then call get_system_eeprom_info, PSU and Thermal APIs accordingly.
UT Logs : [UT_logs-PSU.txt](https://github.com/Azure/sonic-buildimage/files/3514554/UT_logs-PSU.txt), [UT_logs-thermal.txt](https://github.com/Azure/sonic-buildimage/files/3514555/UT_logs-thermal.txt), [UT_logs-eeprom.txt](https://github.com/Azure/sonic-buildimage/files/3514558/UT_logs-eeprom.txt)

**- Description for the changelog**

DellEMC Z9100 : Platform2.0 API implementation [PSU, Thermal]

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by sujinmkang** [comment]
retest mellanox please

**Comment by sujinmkang** [comment]
redo broadcom please

**Comment by sujinmkang** [comment]
rebuild Broadcom please

**Comment by sujinmkang** [comment]
rebuild broadcom please

**Comment by sujinmkang** [comment]
redo all

**Comment by sujinmkang** [comment]
can you please rebase to the latest?

**Comment by ArunSaravananBalachandran** [comment]
> @ArunSaravananBalachandran can you please rebase to the latest?

Merge conflicts have been resolved.

**Comment by sujinmkang** [comment]
retest vs and vsimage please

**Comment by sujinmkang** [comment]
retest vs please

**Comment by sujinmkang** [comment]
retest vsimage please!

**Pull request merged**
