### PR TITLE
[barefoot][sonic-platform] Fix Fan.set_speed

### PR DESCRIPTION
**Pull request by vboykox**
Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>

#### Why I did it
To fix https://github.com/Azure/sonic-buildimage/issues/7758
#### How I did it
Fixed typo
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

#### Description for the changelog

Fix Fan.set_speed in barefoot's sonic_platform

### CODE REVIEW

**Review by akokhan — APPROVED** [review]

**Comment by vboykox** [comment]
@jleveque

**Review by jleveque — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This commit could not be cherry-pick cleanly to 202012. Please submit a new PR.

**Comment by vboykox** [comment]
@qiluo-msft  That's because this PR https://github.com/Azure/sonic-buildimage/pull/7004 was not cherry-picked

**Comment by jleveque** [comment]
> @qiluo-msft That's because this PR #7004 was not cherry-picked

I just added the label.

**Pull request merged**
