### PR TITLE
    [device]: Add a new supported device DellEMC s5248f

### PR DESCRIPTION
**Pull request by srideepDell**
* Switch Vendor: DellEMC
    * Switch SKU: s5248F
    * ASIC Vendor: Broadcom
    * Swich ASIC: Trident3
    * Port Configuration: 48x25G,4x100G,2x200G
    * SONiC Image: sonic-broadcom.bin

    * Changes Include ipmitool implementation for platform_sensors script is inclued in pmon startup
    * Added 25G,10G configruation(25G is default) 1-48FP. 4x100G,2x200G (49-54 FP)
    * LED support for s5248f

**- What I did**
DellEMC s5248f device support added .

**- How to verify it**
Platform support test

show version

SONiC Software Version: SONiC.master.0-dirty-20191001.124648
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: abc02a70
Build date: Tue Oct  1 19:51:55 UTC 2019
Built by: sdevireddy@sonic-2

Platform: x86_64-dellemc_s5248f_c3538-r0
HwSKU: DellEMC-S5248f-P-25G
ASIC: broadcom
Serial Number: CN046MRJCES008AB0003
Uptime: 08:05:46 up 23 min,  2 users,  load average: 0.50, 0.63, 0.69

Docker images:
REPOSITORY                 TAG                              IMAGE ID            SIZE
docker-snmp-sv2            latest                           8c5fe308e87f        334MB
docker-snmp-sv2            master.0-dirty-20191001.124648   8c5fe308e87f        334MB
docker-orchagent           latest                           4023c7f0713b        320MB
docker-orchagent           master.0-dirty-20191001.124648   4023c7f0713b        320MB
docker-fpm-frr             latest                           71c98849269e        318MB
docker-fpm-frr             master.0-dirty-20191001.124648   71c98849269e        318MB
docker-syncd-brcm          latest                           7d72f96d0816        391MB
docker-syncd-brcm          master.0-dirty-20191001.124648   7d72f96d0816        391MB
docker-teamd               latest                           c834b1222ba0        302MB
docker-teamd               master.0-dirty-20191001.124648   c834b1222ba0        302MB
docker-lldp-sv2            latest                           5da51640182b        298MB
docker-lldp-sv2            master.0-dirty-20191001.124648   5da51640182b        298MB
docker-sflow               latest                           d01366525363        302MB
docker-sflow               master.0-dirty-20191001.124648   d01366525363        302MB
docker-platform-monitor    latest                           f723a0a869cb        325MB
docker-platform-monitor    master.0-dirty-20191001.124648   f723a0a869cb        325MB
docker-dhcp-relay          latest                           6cf4b73c50c0        289MB
docker-dhcp-relay          master.0-dirty-20191001.124648   6cf4b73c50c0        289MB
docker-database            latest                           41974d466622        280MB
docker-database            master.0-dirty-20191001.124648   41974d466622        280MB
docker-router-advertiser   latest                           31498e2396e0        281MB
docker-router-advertiser   master.0-dirty-20191001.124648   31498e2396e0        281MB
docker-sonic-telemetry     latest                           7c1be0641a76        303MB
docker-sonic-telemetry     master.0-dirty-20191001.124648   7c1be0641a76        303MB

show platform syseeprom
TlvInfo Header:
   Id String:    TlvInfo
   Version:      1
   Total Length: 180
TLV Name             Code Len Value
-------------------- ---- --- -----
Product Name         0x21   9 S5248F-ON
Part Number          0x22   6 046MRJ
Serial Number        0x23  20 CN046MRJCES008AB0003
Base MAC Address     0x24   6 3C:2C:30:1D:A6:80
Manufacture Date     0x25  19 10/12/2018 01:35:16
Device Version       0x26   1 1
Label Revision       0x27   3 A01
Platform Name        0x28  30 x86_64-dellemc_s5248f_c3538-r0
ONIE Version         0x29  10 3.40.1.1-6
MAC Addresses        0x2A   2 256
Manufacturer         0x2B   5 CES00
Manufacture Country  0x2C   2 CN
Vendor Name          0x2D   8 Dell EMC
Diag Version         0x2E  10 3.40.4.1-2
Service Tag          0x2F   7 6W000Q2
Vendor Extension     0xFD   4
CRC-32               0xFE   4 0x34561797

show environment
acpitz-virtual-0
Adapter: Virtual device
temp1:         +0.0 C  (crit = +94.0 C)

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +33.0 C  (high = +74.0 C, crit = +94.0 C)
Core 2:         +32.0 C  (high = +74.0 C, crit = +94.0 C)
Core 6:         +31.0 C  (high = +74.0 C, crit = +94.0 C)
Core 8:         +32.0 C  (high = +74.0 C, crit = +94.0 C)
Core 12:        +33.0 C  (high = +74.0 C, crit = +94.0 C)

Onboard Temperature Sensors:
  PT_Left_temp:                     27 degrees C
  PT_Mid_temp:                      28 degrees C
  PT_Right_temp:                    29 degrees C
  Broadcom Temp:                    35 degrees C
  Inlet Airflow Temp:               26 degrees C
  CPU Temp:                         34 degrees C

Fan Trays:
  Fan Tray 1:
    Fan1 Speed:                     8520 RPM
    Fan2 Speed:                     7680 RPM
    Fan1 State:                     Normal
    Fan2 State:                     Normal
  Fan Tray 2:
    Fan1 Speed:                     8400 RPM
    Fan2 Speed:                     7680 RPM
    Fan1 State:                     Normal
    Fan2 State:                     Normal
  Fan Tray 3:
    Fan1 Speed:                     8640 RPM
    Fan2 Speed:                     7800 RPM
    Fan1 State:                     Normal
    Fan2 State:                     Normal
  Fan Tray 4:
    Fan1 Speed:                     8760 RPM
    Fan2 Speed:                     7800 RPM
    Fan1 State:                     Normal
    Fan2 State:                     Normal

PSUs:
    PSU1:
       FAN Normal Temperature:         36 degrees C
       FAN AirFlow Temperature:        27 degrees C
       FAN RPM:                        7440 RPM
       Input Voltage:                  206.80 Volts
       Output Voltage:                 12.40 Volts
       Input Power:                    130 Watts
       Output Power:                   110 Watts
       Input Current:                  0.64 Amps
       Output Current:                 9.50 Amps

  PSU  2 Not present

    Total Power:                       130 Watts
root@sonic:/usr/share/sonic/templates#

### CODE REVIEW

**Comment by srideepDell** [comment]
retest please failure is due to no space

vs-image.
open /var/lib/docker/vfs/dir/772d322ee65ec8224357e79404606e6ba2b529805905053b356d7dfc10c27298/usr/include/x86_64-linux-gnu/sys/file.h: no space left on device
[  FAIL LOG END  ] [ target/docker-config-engine-stretch.gz ]

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vs please

**Comment by srideepDell** [comment]
vs passed
vsimage failed with 
E: Some index files failed to download.

could we retest vsimage again.

**Comment by jleveque** [comment]
Retest vsimage please

**Pull request merged**
