### PR TITLE
Restart ntp after ntp-config

### PR DESCRIPTION
**Pull request by taoyl-ms**
**- What I did**
In ntp-config service, explicitly restart ntp service after generating ntp.conf file

### CODE REVIEW

**Comment by jleveque** [comment]
Does removing the ntp.service dependency fix the issue that caused Shuotian to revert this change a few days ago (https://github.com/Azure/sonic-buildimage/pull/1102)?

**Comment by stcheng** [comment]
how you verify with this change?

**Comment by taoyl-ms** [comment]
Yes, this fix #1102.

**Comment by taoyl-ms** [comment]
I manually set wrong hwclock on a test device, didn't specify ntp server in minigraph, and re-imaged the box. When it's loaded, the system clock is wrong because ntp is not working. I then manually wrote correct ntp server into configdb, ran `service restart ntp-config`, and observed the system clock was corrected by ntp.

**Pull request merged**
