### PR TITLE
[yang] Update device_metadata to add dhcp_server

### LINKED ISSUE #10365: [yang] device metadata validation failed
#### Description

https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/tests/test_minigraph_case.py#L173-#L184
There's a new field 'dhcp_server' in device metadata, and yang model is not updated.

#### Steps to reproduce the issue:
1. Follow test_minigraph_dhcp_server_feature to run sonic-cfggen command, and check device_metadata field.

#### Describe the results you received:
Output can't pass yang validation.

#### Describe the results you expected:
Output can pass yang validation.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

### PR DESCRIPTION
**Pull request by ganglyu**
Signed-off-by: Gang Lv ganglv@microsoft.com

#### Why I did it
dhcp_server is introduced, and need to update yang model.

#### How I did it
Update yang models and add unit test.

#### How to verify it
Run unit test for sonic-yang-models.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

#### Description for the changelog

Fix #10365

### CODE REVIEW

**Review by Blueve — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by ganglyu** [comment]
@praveen-li @rathnasabapathyv @venkatmahalingam @dgsudharsan 
Would you please review this PR?

**Comment by judyjoseph** [comment]
There is merge conflict in 202111, please raise a separate PR

**Pull request merged**
