### PR TITLE
[swss]: Update the ipinip.j2 template to specify the IPv4 loopback address

### PR DESCRIPTION
**Pull request by stcheng**
output:
```
root@str-s6000-on-2:/# sonic-cfggen -m /etc/sonic/minigraph.xml -d -v "LOOPBACK_INTERFACE.keys()"

[('Loopback0', '200A:0100::20/128'), ('Loopback0', '10.1.0.32/32')]

[                                              
    {                                          
        "TUNNEL_DECAP_TABLE:IPINIP_TUNNEL" : { 
            "tunnel_type":"IPINIP",            
            "src_ip":"10.1.0.32",              
            "dst_ip":"10.1.0.32",              
            "dscp_mode":"pipe",                
            "ecn_mode":"copy_from_outer",      
            "ttl_mode":"pipe"                  
        },                                     
        "OP": "SET"                            
    }                                          
]                                              
```

### CODE REVIEW

**Comment by taoyl-ms** [comment]
Just a comment - Please note that this will fail when there will be multiple ipv4 lo addresses.
Not sure if that is a scenario we are going to support though.

**Comment by stcheng** [comment]
Yes. It will also fail if there's no IPv4 address assigned to the loopback interface.

**Comment by stcheng** [comment]
```
                              _,add8ba,
                            ,d888888888b,
                           d8888888888888b                        _,ad8ba,_
                          d888888888888888)                     ,d888888888b,
                          I8888888888888888 _________          ,8888888888888b
                __________`Y88888888888888P"""""""""""baaa,__ ,888888888888888,
            ,adP"""""""""""9888888888P""^                 ^""Y8888888888888888I
         ,a8"^           ,d888P"888P^                           ^"Y8888888888P'
       ,a8^            ,d8888'                                     ^Y8888888P'
      a88'           ,d8888P'                                        I88P"^
    ,d88'           d88888P'                                          "b,
   ,d88'           d888888'                                            `b,
  ,d88'           d888888I                                              `b,
  d88I           ,8888888'            ___                                `b,
 ,888'           d8888888          ,d88888b,              ____            `b,
 d888           ,8888888I         d88888888b,           ,d8888b,           `b
,8888           I8888888I        d8888888888I          ,88888888b           8,
I8888           88888888b       d88888888888'          8888888888b          8I
d8886           888888888       Y888888888P'           Y8888888888,        ,8b
88888b          I88888888b      `Y8888888^             `Y888888888I        d88,
Y88888b         `888888888b,      `""""^                `Y8888888P'       d888I
`888888b         88888888888b,                           `Y8888P^        d88888
 Y888888b       ,8888888888888ba,_          _______        `""^        ,d888888
 I8888888b,    ,888888888888888888ba,_     d88888888b               ,ad8888888I
 `888888888b,  I8888888888888888888888b,    ^"Y888P"^      ____.,ad88888888888I
  88888888888b,`888888888888888888888888b,     ""      ad888888888888888888888'
  8888888888888698888888888888888888888888b_,ad88ba,_,d88888888888888888888888
  88888888888888888888888888888888888888888b,`"""^ d8888888888888888888888888I
  8888888888888888888888888888888888888888888baaad888888888888888888888888888'
  Y8888888888888888888888888888888888888888888888888888888888888888888888888P
  I888888888888888888888888888888888888888888888P^  ^Y8888888888888888888888'
  `Y88888888888888888P88888888888888888888888888'     ^88888888888888888888I
   `Y8888888888888888 `8888888888888888888888888       8888888888888888888P'
    `Y888888888888888  `888888888888888888888888,     ,888888888888888888P'
     `Y88888888888888b  `88888888888888888888888I     I888888888888888888'
       "Y8888888888888b  `8888888888888888888888I     I88888888888888888'
         "Y88888888888P   `888888888888888888888b     d8888888888888888'
            ^""""""""^     `Y88888888888888888888,    888888888888888P'
                             "8888888888888888888b,   Y888888888888P^
                              `Y888888888888888888b   `Y8888888P"^
                                "Y8888888888888888P     `""""^
                                  `"YY88888888888P'
                                       ^""""""""'
```

**Comment by lguohan** [comment]
yes, we do have two ipv4 loopback address scenario.

**Comment by stcheng** [comment]
it seems that the source IP is not used. we're not encapsulating packets. we will need to remove that part later.

**Pull request merged**
