### PR TITLE
[submodule] update sonic-linux-kernel

### PR DESCRIPTION
**Pull request by qiluo-msft**
- [x] Waiting Mellanox updates kernel modules
- [x] smoke test: ports up, bgp sessions up
  - [x] Mellanox
  - [x] Broadcom Dell 6100
  - [x] Broadcom Arista

### CODE REVIEW

**Comment by lguohan** [comment]
any smoke test?

please do "git grep 4.8.0-8-2" and replace all of them.

**Comment by qiluo-msft** [comment]
Retest mellanox please

**Comment by qiluo-msft** [comment]
Retest broadcom please

**Comment by qiluo-msft** [comment]
Retest broadcom please

**Comment by qiluo-msft** [comment]
Retest broadcom please

**Pull request merged**
