### PR TITLE
[Mellanox] Initialize PSU API on both host and docker side

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

There was a change to replace platform utils with sonic platform API in psuutil. However, psu API is not initialized on host side. The PR is to fix it.

#### How I did it

Initialize PSU API on both host and non-host side

#### How to verify it

Manual test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Comment by jleveque** [comment]
@Junchao-Mellanox: Please fix conflicts

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@jleveque kindly review. We need this in 202012 and we are in final qualification of this branch

**Review by jleveque — APPROVED** [review]

**Comment by daall** [comment]
@liat-grozovik @Junchao-Mellanox merge conflict cherry-picking to 202012, please submit a PR against the branch

**Comment by Junchao-Mellanox** [comment]
sure

**Pull request merged**
