### PR TITLE
Add ethtool to docker-platform-monitor 

### PR DESCRIPTION
**Pull request by VenkatCisco**
#### Why I did it
 ethtool can be used to query and change settings such as speed, auto- negotiation and checksum offload on many network devices, especially Ethernet devices. 

#### How I did it
add package extension to docker-platform-monitor/Dockerfile.j2 
#### How to verify it
ethtool -y 
more examples are @ https://linuxhint.com/ethtool_commands_examples/

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [x] 202006
- [x] 202012

#### Description for the changelog

 ethtool can be used to query and change settings such as speed, auto- negotiation and checksum offload on many network devices, especially Ethernet devices. 

```
root@sonic:/# dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | grep ethtool
593     ethtool
```

### CODE REVIEW

**Comment by jleveque** [comment]
@VenkatCisco: In the PR description, can you please indicate the installed size of this package on disk?

**Comment by VenkatCisco** [comment]
> @VenkatCisco: In the PR description, can you please indicate the installed size of this package on disk?

Done

**Review by jleveque — APPROVED** [review]

**Comment by jleveque** [comment]
@VenkatCisco: Is it necessary to backport this to the 201911 branch? That branch is relatively stable; we only want to backport bug fixes.

**Comment by VenkatCisco** [comment]
> @VenkatCisco: Is it necessary to backport this to the 201911 branch? That branch is relatively stable; we only want to backport bug fixes.

Our primary development branches are 202012 and azure/master. Updated the PR accordingly.

**Comment by keboliu** [comment]
I think this commit is not necessary, ethtool should already been installed in pmon container, please check PR https://github.com/Azure/sonic-buildimage/pull/5725 @VenkatCisco did you see ethtool missing in the pmon docker before this commit?

**Pull request merged**
