### PR TITLE
[Mellanox] [202012] Enhance the platform.json with adding more platform device facts.

### PR DESCRIPTION
**Pull request by keboliu**
#### Why I did it

Current platform.json lacks some peripheral device related facts, like chassis/fan/pasu/drawer/thermal/components names, numbers, etc.

#### How I did it

Add platform device facts to the platform.json file

#### How to verify it

Run sonic-mgmt platform API tests which depend on these facts.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@jleveque please note that this PR is against 202012 and cannot be cherry picked from master as master has interfaces already included for dynamic port breakout which should not be taken to 202012.

**Review by jleveque — APPROVED** [review]

**Comment by keboliu** [comment]
Hi, @daall would you please help to merge to 202012?

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
