### PR TITLE
sonic-port.yang: add link training support

### PR DESCRIPTION
**Pull request by ds952811**
This is part of HLD  Azure/SONiC#925

#### Why I did it
Add link-training support

#### How I did it
Update SONiC YANG for port link-training support

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

#### Description for the changelog

Add "link_training" to sonic-port.yang

#### Link to config_db schema for YANG module changes

https://github.com/sonic-net/SONiC/wiki/Configuration#port

### CODE REVIEW

**Review by dgsudharsan — CHANGES_REQUESTED** [review]
Please add UT
Update  schema in https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md
Add sample configuration in https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/tests/files/sample_config_db.json

**Review by dgsudharsan — CHANGES_REQUESTED** [review]
@ds952811 I still see unit tests are missing in this PR. Apart from adding it in sample_config_db.json you should also add UT to cover negative test cases. Please refer to other yang PRs

**Comment by ds952811** [comment]
> @ds952811 I still see unit tests are missing in this PR. Apart from adding it in sample_config_db.json you should also add UT to cover negative test cases. Please refer to other yang PRs

Thanks, I think I know what's missing now, will update the PR

**Review by Junchao-Mellanox — DISMISSED** [review]

**Review by dgsudharsan — APPROVED** [review]

**Review by Junchao-Mellanox — APPROVED** [review]

**Review by ganglyu — APPROVED** [review]

**Pull request merged**
