### PR TITLE
[Mellanox] Update hw-mgmt package to V.7.0000.3020

### PR DESCRIPTION
**Pull request by keboliu**
**Dependency PR https://github.com/Azure/sonic-linux-kernel/pull/129 has been merged, this PR is ready to merge** 

**- What I did**
Update hw-mgmt version to V.7.0000.3020

**- How I did it**
update hw-mgmt submodule to V.7.0000.3020, 
update hw-mgmt patch  

**- How to verify it**
run regression test on Mellanox platform

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by keboliu** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by keboliu** [comment]
retest vsimage please

**Comment by abdosi** [comment]
@keboliu There is conflict in cherry-pick. Please create PR for 201911

**Comment by abdosi** [comment]
@liat-grozovik

**Comment by keboliu** [comment]
@abdosi  This PR has a dependency on some kernel patches
 https://github.com/Azure/sonic-linux-kernel/pull/128 Fix issue: thermal algorithm not work for optical module
https://github.com/Azure/sonic-linux-kernel/pull/129  [Mellanox] Add new patches come along with hw-mgmt V.7.0000.3020

could you please cherry-pick those two PRs first? If still have issue I will create a PR for 201911 to update the hw-mgmt.

**Pull request merged**
