### PR TITLE
[vs] add information about features to config db

### PR DESCRIPTION
**Pull request by stepanblyschak**
vs has components from swss, bgp, teamd and nat. This table is needed by this change https://github.com/Azure/sonic-utilities/pull/1554.

Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>

#### Why I did it
Because https://github.com/Azure/sonic-utilities/pull/1554 requires "config warm_restart enable FEATURE" and the FEATURE has to be in feature table.

#### How I did it
Added FEATURE table to VS.

#### How to verify it
Run VS tests.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Review by prsunny — APPROVED** [review]
lgtm.. @lguohan to review

**Comment by liat-grozovik** [comment]
@lguohan kindly reminder, can you please review?

**Pull request merged**
