### PR TITLE
[build_debian] pip install pexpect in the base image for ansible module

### PR DESCRIPTION
**Pull request by okanchou9**
Signed-off-by: Okanchou9 <kenie7@gmail.com>

**- What I did**
PIP install pexpect in the base image for ansible module(sonic-mgmt)

**- How I did it**
Add a line to pip install pexpect in file build_debian.sh

**- How to verify it**
Build a test image with this change and check if pexpect is installed in this test image without any issue

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
why do we need pexpect in the base image?

**Comment by okanchou9** [comment]
There is a script [config_sonic_basedon_testbed.yml](https://github.com/Azure/sonic-mgmt/blob/master/ansible/config_sonic_basedon_testbed.yml) in sonic-mgmt which can generate matching configuration file and deploy it into SONiC box.

In the latest image, we are using "config load_minigraph" and type "y" to setup new minigraph into SONiC box. Ansible cannot type "y" after issued CLI "config load_minigraph" without pexpect installed in SONiC box.

According to the comment of @stcheng in [#282](https://github.com/Azure/sonic-mgmt/pull/282), I raised a PR for this enhancement.

Please let me know if any, thanks.

**Comment by lguohan** [comment]
we should use "config load_minigraph -y" to load minigraph in the ansible test without asking user's response. 

We do not need to install pexpect in the base image.

**Comment by okanchou9** [comment]
@lguohan 

OK, thank you for the suggestion.
Will modify the test to use the option "-y"

**Pull request closed without merging**
