### PR TITLE
[ntp][apparmor] Allow apparmor read permission for ntpd under rw mount path of rootfs

### PR DESCRIPTION
**Pull request by antony-rheneus**
Certain platform specific packages sonic-platform-xyz, installs files onto rootfs, which would be placed on read-write mount path on /host/image-name/rw/...
when ntpd starts it tries to do read access on /usr/bin /usr/sbin/ /usr/local/bin , which inturn links further to the read-write mount path also.
Where ntpd would get below Apparmor Warning message

LOG:-
audit: type=1400 audit(1606226503.240:21): apparmor="DENIED" operation="open" profile="/usr/sbin/ntpd" name="/image-HEAD-dirty-20201111.173951/rw/usr/local/bin/" pid=3733 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
audit: type=1400 audit(1606226503.240:22): apparmor="DENIED" operation="open" profile="/usr/sbin/ntpd" name="/image-HEAD-dirty-20201111.173951/rw/usr/sbin/" pid=3733 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
audit: type=1400 audit(1606226503.240:23): apparmor="DENIED" operation="open" profile="/usr/sbin/ntpd" name="/image-HEAD-dirty-20201111.173951/rw/usr/bin/" pid=3733 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Fix:
Add rw/.. mount path similar to root path access provided for ntpd in /etc/apparmor.d/usr.sbin.ntpd

Signed-off-by: Antony Rheneus <arheneus@marvell.com>

**- Why I did it**

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
@antony-rheneus , does this fix #5975?

**Comment by antony-rheneus** [comment]
> @antony-rheneus , does this fix #5975?

I dont think, as #5975 describes different error where it has dependency with libpcap library and also it was mentioned the error is seen in Testbed and Not on DUT.

This PR is for ntpd running on DUT.

**Comment by lguohan** [comment]
can you describe the impact without this pr, is this just syslog issue, or ntpd is not running on the dut?

**Comment by antony-rheneus** [comment]
> can you describe the impact without this pr, is this just syslog issue, or ntpd is not running on the dut?

NTPD will still run on the DUT, however apparmor will report the errors in syslog.

**Review by lguohan — APPROVED** [review]

**Pull request merged**
