### PR TITLE
[build]: simplify the function to covert PFX certificate

### PR DESCRIPTION
**Pull request by xumia**
**- Why I did it**

**- How I did it**
Not necessary to remove the certificate attributes by grep when exporting the private/public certificate.

**- How to verify it**

**- Which release branch to backport (provide reason below if seleted)**

- [ ] 201811
- [ ] 201911
- [x] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
can you explain what has been simplified?

**Comment by xumia** [comment]
> can you explain what has been simplified?
There are only one private key and one none CA certificate in PFX file, so not necessary to remove the certificate attributes by grep when exporting the private/public certificate. The openssl command provide -out option to export the file directly.

**Comment by lguohan** [comment]
next time can you put this into your commit message?

**Comment by lguohan** [comment]
if you check https://github.com/Azure/sonic-buildimage/commit/918ce2a633d1d402eeab3aebe363e5091937f5a9, it is empty.

**Pull request merged**
