### PR TITLE
kernel ABI update from version 6 to version 6-2

### PR DESCRIPTION
**Pull request by olivier-singla**
By changing the kernel ABI from version 6 to version 6-2, this will allow to disable the kernel ABI check which Debian performs at the very end of the kernel build.

In SONiC branch 201911 (Stretch), there is this patch which is applied:

packaging-update-abiname-to-11-2.patch

It changes the kernel ABI from 11 to 11-2

This has the side effect to disable the ABI check performed by the script
debian/bin/buildcheck.py

This is because the buildcheck.py script is looking to compare the file
debian/build/build_amd64_none_amd64/Module.symvers
(generated by the build)
with the file
debian/abi/4.9.0-11-2/amd64_none_amd64

But since the ABI has changed, the Debian file checked-in is still:
debian/abi/4.9.0-11/amd64_none_amd64

So buildcheck.py, not finding the file
debian/abi/4.9.0-11-2/amd64_none_amd64
just bails out, without error, and will not check the ABI change.

In SONiC latest master branch, based on Buster, there is no such patch to change the ABI.
The script buildcheck.py will then compare the file
debian/build/build_amd64_none_amd64/Module.symvers
with the file
debian/abi/4.19.0-6/amd64_none_amd64

so any ABI change will be effectively checked..

For example, the patch:
Support-for-fullcone-nat.patch
which apply fine with SONiC 201911 (Stretch) can not currently be applied in the master branch (Buster), because there is a change in a global kernel structure
(include/net/netfilter/nf_conntrack.h in this example).

Without changing the kernel ABI, many patches might just fail because the ABI check., this is why we want to change the kernel ABI.

Please note that PR needs also this PR:
https://github.com/Azure/sonic-linux-kernel/pull/145

### CODE REVIEW

**Comment by jleveque** [comment]
Can you please add to the PR description and describe why we want to disable the kernel ABI check?

**Comment by olivier-singla** [comment]
> Can you please add to the PR description and describe why we want to disable the kernel ABI check?

Did you had a chance to  review my comment?

**Comment by lguohan** [comment]
the build is broken, can you check?

**Comment by olivier-singla** [comment]
retest this please

**Comment by olivier-singla** [comment]
retest this please

**Comment by olivier-singla** [comment]
retest this please

**Comment by olivier-singla** [comment]
retest this please

**Comment by olivier-singla** [comment]
> the build is broken, can you check?

This is fixed now

**Comment by rajendra-dendukuri** [comment]
retest vsimage please

**Comment by olivier-singla** [comment]
retest please

**Comment by olivier-singla** [comment]
> > the build is broken, can you check?
> 
> This is fixed now

lguohan, now the conflict is resolved, do think you will able to merge this patch today? 
PR #145 has been already merged, and it need this PR #4711
Thanks.

**Pull request merged**
