### PR TITLE
Add BRCM SOC Property to not count ACL drops towards interface RX_DRP…

### PR DESCRIPTION
**Pull request by gechiang**
… counter for 7050CX3 and 7260CX3 DualToR platforms

#### Why I did it
For DualToR There will be expected packet drops that should not be counted towards interface RX_DRP counters.
SAI support this feature but is only enabled if the proper SOC property is set in the device's conf.bcm file.
this change is to add the necessary SOC property for the HW SKUs that are purposed for DualToR Roles.

#### How to verify it
Send packet that is expected to be drop and check that it is not being counted towards interface RX_DRP counter.
Also tested with the case where  SAI change is not yet there but SOC is already enabled and observe it does not cause any undesirable side-effect.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

#### Description for the changelog
Add SOC property to not count ACL Drops towards interface RX_DRP for DualToR role HW SKUs.

### CODE REVIEW

**Review by prsunny — DISMISSED** [review]

**Comment by yxieca** [comment]
Does TD2/TH also need this change? why only change TD3 and TH2?

**Comment by gechiang** [comment]
> Does TD2/TH also need this change? why only change TD3 and TH2?

This is only needed for DualToR roles.  So far I only know the TD3 and TH2 HW SKUs are planed for DualToR roles and not others...

**Comment by yxieca** [comment]
> > Does TD2/TH also need this change? why only change TD3 and TH2?
> 
> This is only needed for DualToR roles. So far I only know the TD3 and TH2 HW SKUs are planed for DualToR roles and not others...

I see. Thanks!

**Review by yxieca — DISMISSED** [review]

**Comment by prsunny** [comment]
looks like there is a submodule update in PR? could you please revert that?

**Comment by gechiang** [comment]
> looks like there is a submodule update in PR? could you please revert that?

Thanks for catching it!  I did not realize the merge picked it up by accident.  Have reverted all the merge changes and resolve merge conflict on the single file that was needed manually.

**Review by lguohan — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Comment by qiluo-msft** [comment]
@gechiang This PR could not be cleanly cherry-pick to 202012. Please submit another PR.

**Pull request merged**
