### PR TITLE
[dhcp_relay] Adapt config/show CLI commands to support DHCPv6 relay

### PR DESCRIPTION
**Pull request by shlomibitton**
Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

#### Why I did it
- Adapt config/show CLI commands to support DHCPv6 relay
- Support multiple dhcp servers assignment in one command
- Fix IP validation
- Adapt UT and add new UT cases

#### How I did it
- Modify config/show dhcp relay files
- Modify config/show UT files

#### How to verify it
This PR has a dependency on PR https://github.com/Azure/sonic-utilities/pull/1717
Build an image with the dependent PR and this PR
Use config/show DHCPv6 relay commands.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [x] 202106

### CODE REVIEW

**Comment by shlomibitton** [comment]
@tahmed-dev can you please review this PR?
Thanks

**Review by tahmed-dev — APPROVED** [review]
LGTM, Thanks!

**Comment by anshuv-mfst** [comment]
@tahmed-dev - please help with merge asap, needed for 202106 release

**Comment by tahmed-dev** [comment]
@shlomibitton, can you please the build failure?

**Comment by shlomibitton** [comment]
> @shlomibitton, can you please the build failure?

Hey @tahmed-dev we need this PR to merge in order to fix the build issue:
https://github.com/Azure/sonic-buildimage/pull/8557

**Comment by shlomibitton** [comment]
@tahmed-dev all checked are passing now, can we proceed and merge?
thanks

**Pull request merged**
