### PR TITLE
[hostcfgd] differentiate between UnitFileState and UnitFilePreset

### PR DESCRIPTION
**Pull request by stepanblyschak**
It can be that service is not enabled but UnitFilePreset=enabled (case
for Application Extension):

```
    Loaded: loaded (/lib/systemd/system/cpu-report.service; disabled; vendor preset: enabled)
```

This makes existing logic skip enabling the service.

Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>

#### Why I did it

To fix an issue when a 3rd party package cannot be started by hostcfgd.

#### How I did it

Check explicitely for UnitFileState.

#### How to verify it

Ran UT & ran it on the switch.
Installed 3rd party package and enabled it in config db, verified feature can start.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [x] 202106

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@yxieca could you please help to review? note that this is a degradation noticed in both master and 202012 thus the urgency.
@stepanblyschak  can you please check the failures on CI and see if relevant or what is failing.

**Review by stephenxs — APPROVED** [review]

**Review by yxieca — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This PR could not be cleanly cherry-pick to 202012. Please submit another PR.

**Comment by stepanblyschak** [comment]
@qiluo-msft https://github.com/Azure/sonic-buildimage/pull/8228

**Pull request merged**
