### PR TITLE
[knet] Address Tx drop No DMA resource issue

### PR DESCRIPTION
**Pull request by neethajohn**
Signed-off-by: Neetha John <nejo@microsoft.com>

**- How to verify it**
Created a repro where Tx drops were seen
Built an image with the changes in the patch and verified that Tx drops are no longer seen

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

Broadcom patch to address Tx drop No DMA resource issue

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Comment by lguohan** [comment]
retest broadcom please

**Comment by yxieca** [comment]
retest broadcom please

**Comment by lguohan** [comment]
retest broadcom please

**Comment by zhenggen-xu** [comment]
It looks like the patch is included in master but not in any other branches like 201904, 201911, 202006 etc.  are we going to cherry-pick from this branch (201811) to other branches after merge?

**Comment by xumia** [comment]
retest broadcom please

**Review by yxieca — APPROVED** [review]

**Pull request merged**
