### PR TITLE
Add python linuxfd to image and pmon

### PR DESCRIPTION
**Pull request by zzhiyuan**
**- What I did**
Add python linuxfd support in base image and pmon container.

To support a mix of blocking fd and polling event change detection in platform API, a timerfd is best suited to this task. Currently it would only be needed in base image but added for pmon as well since platform API functionality will most likely be used by pmon services in the future.

**- How I did it**

**- How to verify it**
linuxfd is able to be imported on device, and is able to be imported by python2 and python3 in pmon container.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
this pr has increase the pmon docker size to 212MB.

docker-platform-monitor.gz | Jul 31, 2019 12:01:59 AM | 212.43 MB

current size is 126MB.


docker-platform-monitor.gz | Jul 31, 2019 5:05:24 AM | 126.72 MB

Can you fix this size issue?

**Comment by zzhiyuan** [comment]
> size increased a lot.

Just revised the commit, now the size increase is less than 100KB. Thanks.

**Comment by jleveque** [comment]
You force-pushed, so we lost the history. Please try to avoid this if possible. What did you change in the new commit?

**Comment by zzhiyuan** [comment]
> You force-pushed, so we lost the history. Please try to avoid this if possible. What did you change in the new commit?

Noted, will avoid force pushes in the future, here is what changed in this commit compared to the last one:
- Previous commit apt-get installs curl, gcc, python-dev, and python3-dev
- This commit only installs gcc and libpython-dev

- Previous commit installs up-to-date pip with curl
- This commit does not

- Previous commit installs linuxfd on python2 and python3
- This commit only installs linuxfd on python2, note that pmon doesn't have python3

- Previous commit apt-get purges curl and gcc
- This commit purges gcc and libpython-dev, note that curl was not installed

- This commit additionally cleans the apt lists folder. 

Thanks

**Comment by zzhiyuan** [comment]
I will put this PR on hold until I have verified that the change is needed for platform API. Thanks.

**Pull request closed without merging**
