### PR TITLE
[submodule] [sonic-utilities] update sonic-utilities submodule 

### PR DESCRIPTION
**Pull request by vivekreddynv**
```
a3e34e30 [Auto Techsupport] Event driven Techsupport Changes (#1796)
efa2ff62 [show][platform summary] Add chassis type in the platform summary output(#1922)
a39350c6 [aclshow] enhance ACL counters to work with FC infrastructure (#1858)
ed880131 [sonic-package-manager] fix registry requests failing when no service field in Bearer fields (#1921)
00b60455 [VS test] Increase test timeout (#1924)
```

Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by dgsudharsan** [comment]
@qiluo-msft  Raised submodule update.

**Comment by dgsudharsan** [comment]
@qiluo-msft @lguohan   The pipeline is passing now. Can you please help with the merge?

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
