### PR TITLE
[Arista] Update platform library

### PR DESCRIPTION
**Pull request by Staphylo**
- Fix an issue with front panel port led introduced in previous PR
 - Implement status led for linecards
 - Implement full power cycle for linecards
 - Improve reboot cause reporting for Ucd devices
 - Add fan support for PikeZ
 - Miscellaneous fixes and improvements

### CODE REVIEW

**Review by Blueve — APPROVED** [review]

**Comment by Blueve** [comment]
@Staphylo could you help confirm if all the changes need to be backport to 202205?  
We need PikeZ change back ported to 202205, but I am not sure about the barefoot platform

**Comment by Staphylo** [comment]
@Blueve these changes will need to go in 202205 but I'll make a dedicated PR for this, I'm still waiting for a few more changes.
Usually these changes are not cherry-pickable and I have to do individual PRs for various branches.

**Comment by Blueve** [comment]
> @Blueve these changes will need to go in 202205 but I'll make a dedicated PR for this, I'm still waiting for a few more changes. Usually these changes are not cherry-pickable and I have to do individual PRs for various branches.

OK, I removed the backport label 😃

**Comment by yxieca** [comment]
@Staphylo can you create separate PR for 202205 branch. there is conflict.

**Pull request merged**
