### PR TITLE
nokia: add ndk debian url

### PR DESCRIPTION
**Pull request by jon-nokia**
Signed-off-by: Jon Goldberg <jon.goldberg@nokia.com>

#### Why I did it
Adds the ndk.deb package to the build for IXRE 7250e support

#### How to verify it
Build for platform=broadcom and verify online deb download of ndk

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by jon-nokia** [comment]
@judyjoseph Can you review?

**Review by judyjoseph — APPROVED** [review]

**Comment by lguohan** [comment]
can you explain what is ndk, why this is close sourced?

**Review by lguohan — CHANGES_REQUESTED** [review]
what is ndk, and why is this close sourced?

**Review by judyjoseph — APPROVED** [review]

**Comment by judyjoseph** [comment]
@lguohan This PR is updated with the new nokia platform package uploaded and checksum verified. Is it ok to be merged

**Comment by jon-nokia** [comment]
> Yes.  Ok, to merge

**Pull request closed without merging**
