### PR TITLE
[FRR] Added support for L3VNI for EVPN as described in the PR Azure/SONiC#437

### PR DESCRIPTION
**Pull request by kishorekunal01**
Sending RMAC with EVPN Type5 prefix to fpmsyncd. This is a temp fix, 
This patch will be removed once neighorch is ready to handle the Prefix and ARP(containing RMAC) separately.

**- Why I did it**
Currently FRR is send Prefix with VNI information to FPMSYNCD, added code to send RMAC along with the prefix.
This is a temp fix. This patch will be removed once neighorch is ready to handle the Prefix and ARP(containing RMAC) separately.

**- How I did it**
Part of overall EVPN-VXLAN Implementation

**- How to verify it**
Verified on VS build.

**- Description for the changelog**

ADD L3 VNI EVPN Support for SONiC, Send RMAC and VNI with prefix to FPMSYNCD

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Kishore Kunal kishore.kunal@broadcom.com

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
Hi Kishore,

Can you please upstream your code to FRR?

**Comment by kishorekunal01** [comment]
> Hi Kishore,
> 
> Can you please upstream your code to FRR?

We are going to upstream to FRR soon, but it will be going to master and will take time to be part of the release.

**Comment by pavel-shirshov** [comment]
@kishorekunal01 Can you please make a PR with FRR first?

**Comment by kishorekunal01** [comment]
> @kishorekunal01 Can you please make a PR with FRR first?

Working on it, to raise PR with FRR

**Comment by pavel-shirshov** [comment]
@kishorekunal01 thanks!

**Comment by kishorekunal01** [comment]
These changes are inline with FRR7.5 changes. The PR in FRR is https://github.com/FRRouting/frr/pull/7469

**Comment by prvattem** [comment]
```
- Why I did it
Currently FRR is send Prefix with VNI information to FPMSYNCD, added code to send RMAC and VLAN along with the prefix.
```

Are you referring to  "RMAC and L3VNI" ?

**Comment by kishorekunal01** [comment]
> ```
> - Why I did it
> Currently FRR is send Prefix with VNI information to FPMSYNCD, added code to send RMAC and VLAN along with the prefix.
> ```
> 
> Are you referring to "RMAC and L3VNI" along with the prefix?

I was passing nexthop VLAN information along with prefix, But since nexthop can be extracted from nexthop ifindex(tb[RTA_OIF] ) I am no longer sending VLAN information with prefix. Hence update the review description.

Existing FRR code already send L3VNI information along with the prefix, I have added support to add RMAC information as well with the prefix.

**Comment by prvattem** [comment]
`I was passing nexthop VLAN information along with prefix, But since nexthop can be extracted from nexthop ifindex(tb[RTA_OIF] ) I am no longer sending VLAN information with prefix. `  - Not seind the VLAN across is the right thing to do. By sending VLAN across, are you not fixing VLANs on either side?

**Comment by kishorekunal01** [comment]
> By sending VLAN across, are you not fixing VLANs on either side?

Vlan-Id was used to set the nexthop interface name based on L3VNI to VLAN mapping. So it was not fixed earlier as well.  Since the information can be extracted from tb[RTA_OIF] hence removed the information in the new patch.

**Comment by kishorekunal01** [comment]
Created new PR in FRR community as I was not able to resolve static check error. 
New PR https://github.com/FRRouting/frr/pull/7852

**Comment by prsunny** [comment]
retest mellanox please

**Review by prsunny — APPROVED** [review]

**Pull request merged**
