### PR TITLE
[sairedis] Advance sairedis pointer to support cmd zmq flag

### PR DESCRIPTION
**Pull request by kcudnik**
**- Why I did it**
To support new communication channel (including zmq) in sairedis. Required to compile sonic-swss https://github.com/Azure/sonic-swss/pull/1505

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

commits added:
```
d814d2cc7c52240d49752c45ca4c9ebd0ca7106c [meta] Use memcpy instead of cast to prevent strict-aliasing error (#723)
6dfad66653d0214caec448930f5ae805ad338466 [vslib]Add MACsec forward and filters to HostInterfaceInfo (#719)
2fb5230f77e1cc90295353df24218f16d33cdab2 [vslib] Add StateBase function for MACsec (#717)
f26c408ce3cc75ffb57cb649ebb611fe0fbfee75 Add support for default zmq synchronous mode flag (#711)
f37413a6c513f2f9dde29388c113bf5d915667de [syncd] Code clean (#720)
56f5a21c80e6c699c83ec826ed5d5f415e10cb94 [sairedis] Remove custom bulk fdb methods (#710)
f1b1f05094388ac7b0338b37256f271b81714d36 [vslib]Add MACsec Filters (#713)
a5cfa361c4925d41030649d42c22a67cc66722f1 [vslib]Add MACsec Forwarder (#714)
5f8fff04a3fe2a9004919e73f6d863e6dfab1f3b [vslib]Add MACsec Manager (#715)
65de89877519f80c7d28302f4323cbd1a370dfdc Add helper functions, findObjects and dumpObject (#716)
e713473c19fee713876e114079fc40f0e2e177aa Code clean refactor (#712)
425ffbcbf57fdb66160c1ba84bbec2c0f1f5e983 [vslib] Fix CorePortIndexMap log line (#708)
34a6935b77abf8d4121bdeefed088fe52675c9a9 [meta] Use custom hash in SaiObjectCollection (#709)
c8477338c49b9c069d97abc008196916210b0629 Fix LGTM localtime function warnings (#707)
9fb6fe9705700c3cb066f06d89d77cbcf9778ff2 [vs] VoQ Switch objects initialization - Local Port OID mapping to System Ports (#703)
6ace7d3cb07efe25eec717cdeec44a21bd6d687f Code style refactor (#705)
fc50cf5b4fcaa8cc6cc5e6b516ed9d704355f76f [vs] Initialization of VOQ switch objects (#702)
e2f76cf78fb122fdf50607154cae56050e5f1168 [vs] SAI support for VOQ switches - Switch State Initialization (#701)
1bd090cdec3f6e7e581874033d4994d2e917b672 Add MACsec meta methods (#704)
37786735cb3e6b45ad424327b9ee0414b9b84ae3 [vs] SAI support for VOQ switches (#698)
036ffbaaba3ca4d0d698430484b3c3485a67abbc [vs] SAI support for VOQ switches - Core Port Index Map File parser (#700)
7e67eb2c0599b468520f06cea568e54470374b18 [vs] SAI support for VoQ switch - Core Port Index Map Container (#699)
74eb14e21bff6b1922def9e658018a7225489d47 [syncd][sairedis] Change pub/sub model to push/pull in zmq notification (#695)
584ce03dcc37e1e0b3450b2d636d244680c11afe [syncd] Use lua script to update db when using bulk api (#690)
797197cb5556c58033f8b1200ada741bce2f4f0b [syncd] Fix bulk api object type for next hop group members (#685)
0b08f52a0b2163dc1cd3a5c867d16b43deea9994 Add FlexCounter for MACsec SA (#684)
```

### CODE REVIEW

**Comment by kcudnik** [comment]
retest broadcom please

**Comment by kcudnik** [comment]
retest mellanox please

**Comment by kcudnik** [comment]
retest vsimage please

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
can you list all commits in the submodule in the pr message?

**Comment by kcudnik** [comment]
is there a easy way in github to list them ?

**Comment by lguohan** [comment]
this is the history check, we can just look at the commit message to understand what went into this submodule update.

**Comment by kcudnik** [comment]
updated description

**Review by shi-su — APPROVED** [review]

**Comment by kcudnik** [comment]
[sairedis] Advance sairedis pointer to support cmd zmq flag

[meta] Use memcpy instead of cast to prevent strict-aliasing error (#723)
[vslib]Add MACsec forward and filters to HostInterfaceInfo (#719)
[vslib] Add StateBase function for MACsec (#717)
Add support for default zmq synchronous mode flag (#711)
[syncd] Code clean (#720)
[sairedis] Remove custom bulk fdb methods (#710)
[vslib]Add MACsec Filters (#713)
[vslib]Add MACsec Forwarder (#714)
[vslib]Add MACsec Manager (#715)
Add helper functions, findObjects and dumpObject (#716)
Code clean refactor (#712)
[vslib] Fix CorePortIndexMap log line (#708)
[meta] Use custom hash in SaiObjectCollection (#709)
Fix LGTM localtime function warnings (#707)
[vs] VoQ Switch objects initialization - Local Port OID mapping to System Ports (#703)
Code style refactor (#705)
[vs] Initialization of VOQ switch objects (#702)
[vs] SAI support for VOQ switches - Switch State Initialization (#701)
Add MACsec meta methods (#704)
[vs] SAI support for VOQ switches (#698)
[vs] SAI support for VOQ switches - Core Port Index Map File parser (#700)
[vs] SAI support for VoQ switch - Core Port Index Map Container (#699)
[syncd][sairedis] Change pub/sub model to push/pull in zmq notification (#695)
[syncd] Use lua script to update db when using bulk api (#690)
[syncd] Fix bulk api object type for next hop group members (#685)
Add FlexCounter for MACsec SA (#684)

**Comment by kcudnik** [comment]
will require https://github.com/Azure/sonic-swss/pull/1505 to work

**Pull request merged**
