### PR TITLE
[Mellanox] Update SN2201 sai profile and platform reboot script

### PR DESCRIPTION
**Pull request by keboliu**
#### Why I did it
1. SN2201 sai profile needs to be updated according to the latest hardware.
2. In the reboot script, need to use the common symbol link of the power_cycle sysfs instead of directly accessing it due to SN2201 sysfs is different than other platforms.
3. `echo 1 > $SYSFS_PWR_CYCLE` will trigger the reboot immediately, the following `sleep 3` and `echo 0 > $SYSFS_PWR_CYCLE` will never be executed, can be removed.

#### How I did it
1. Replace the SN2201 sai profile with the latest one.
2. In the platform_reboot script, replace the direct sysfs path with the symbol link path.
3. Remove the redundant code from platform_reboot

#### How to verify it
Perform reboot on all the Nvidia platforms, and check all can be rebooted successfully.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205

### CODE REVIEW

**Review by stephenxs — DISMISSED** [review]

**Comment by liat-grozovik** [comment]
@keboliu spped in sai xml is a bitmask. can you please add a note of the bitmask and explain what this value means?

**Comment by stephenxs** [comment]
> @keboliu spped in sai xml is a bitmask. can you please add a note of the bitmask and explain what this value means?

Hi @liat-grozovik the note is listed in the first port. but we do not repeat it in each port.
```
                <!-- (BITMASK) 3 - 1Gb, 28700 - 10Gb , 939524096 - 25Gb , 98368 - 40Gb , 3221225472 - 50Gb , 11534336 - 100Gb, 1024 - 10MB_T, 2048 - 100MB_TX, 131072 - 1000MB_T  -->
                <port-speed>131072</port-speed>
```

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
