### PR TITLE
kdump support for arm, as the dependency with uboot, skipping kdump installation on ARM

### PR DESCRIPTION
**Pull request by banagiri**
as the dependency with uboot, skipping kdump installation on ARM

** skipping kdump installation on ARM platforms**

**SONIC compilation for arm arch**

**compile SONIC for ARM arch**

**- Description for the changelog**
as the current kdump installation is searching for grub path, and ARM arch (marvell-armhf) are dependent on uboot, these changes has to be addressed

### CODE REVIEW

**Comment by lguohan** [comment]
how do we plan to enable it?

**Comment by banagiri** [comment]
++@antony-rheneus

**Comment by antony-rheneus** [comment]
> how do we plan to enable it?

Issue is in the kdump post installation scripts of debian package, which check for grub.conf.
We will be revisiting this change once we fix the kdump package source post installation script to work with uboot env firmware

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by banagiri** [comment]
> retest this please

@lguohan this has been tested successfully

**Comment by jleveque** [comment]
@banagiri: That comment wasn't directed at you. By entering the phrase "retest this please" into a comment, GitHub triggers our Jenkins instance to re-run all of the check builds.

**Comment by banagiri** [comment]
@jleveque

Understood. But it's bit confusing to whom the sentence was ment.
Can we add  ```@jenkins retest this please```

**Comment by jleveque** [comment]
@banagiri: I completely agree that it is confusing. However, that phrase is coded into a third-party Jenkins plugin which we use, and to the best of my knowledge it is not customizable. :(

**Pull request merged**
