### PR TITLE
[redis] Use redis-server and redis-tools in blob storage to prevent upstream link broken

### PR DESCRIPTION
**Pull request by qiluo-msft**
**- Why I did it**
Upstream link broken and the build is failed

**- How I did it**
Use redis-server and redis-tools in blob storage

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [x] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by yxieca** [comment]
Is this change compatible with 201911/201811 branch? Do we need to change these 2 branches?

**Comment by qiluo-msft** [comment]
No. I added proper label.

**Review by jleveque — APPROVED** [review]
Should we consider upgrading to 6.0.7, which is the latest release available for Buster backports? Maybe missing some bugfixes otherwise?

**Review by yxieca — APPROVED** [review]

**Comment by qiluo-msft** [comment]
@jleveque that will be a long term goal. Here I am trying to fix the build.

**Review by renukamanavalan — COMMENTED** [review]
Would it be feasible to declare this redis version in one place and refer from everywhere ?

**Pull request merged**
