### PR TITLE
[platform-celestica] - Implement FAN APIs based on the new platform API

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- What I did**

- Implement part of the Chassis and Fan related APIs.
- Chassis API
  - get_base_mac()
  - get_component_versions()
- Fan APi
  - get_direction()
  - get_speed()
  - get_target_speed()
  - get_speed_tolerance()
  - set_speed()
  - set_status_led()

**- How I did it**
1. Add a python built package named sonic_platform_api that included part of  Chassis and Fan API
2. Place the package under sonic-platform-modules-cel
3. Add rule to make python wheel package and install it in pmon docker

**- How to verify it**
- Create python script follow the new platform API design doc to verify it (Azure/SONiC#285.)

Signed-off-by: Wirut Getbamrung wgetbumr@celestica.com

### CODE REVIEW

**Comment by mudsut4ke** [comment]
Hi @jleveque 
 
According to your new API design document  (Azure/SONiC#285.)

> Appropriate platform-specific package will be installed during first boot, similar to platform drivers

Can you give me a suggestion about how to install this package to pmon during first boot ?

**Comment by mudsut4ke** [comment]
@jleveque Do you have any comment ?

**Comment by jleveque** [comment]
@mudsut4ke: We currently do not have any examples to follow, but a couple vendors are working on their implementations. The idea is that your platform-specific `sonic_platform` package will be installed at first boot. The plan for now is to have the package reside in the `device/<vendor>/<platform>/` directory.

**Comment by mudsut4ke** [comment]
@jleveque So for now I should place sonic_platform package under device/<vendor>/<platform>/ directory first 

Is that right ?

**Comment by jleveque** [comment]
@mudsut4ke; Yes. For now, that is the location.

**Comment by mudsut4ke** [comment]
retest this please

**Comment by mudsut4ke** [comment]
retest this please

**Comment by mudsut4ke** [comment]
retest

**Comment by mudsut4ke** [comment]
retest this please

**Comment by mudsut4ke** [comment]
retest this please

**Comment by mudsut4ke** [comment]
@jleveque Can review the design ?
If it OK, I i will submit another API

**Pull request merged**
