### PR TITLE
[Mellanox] [201911] Upgrade hw-mgmt to 7.0100.2344

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

To support new PSU fan on mellanox platforms

#### How I did it

Upgrade hw-mgmt to 7.0100.2344

#### How to verify it

1. manual test
2. sonic-mgmt regression test, no issue found

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by lguohan** [comment]
@abdosi to check?

**Comment by abdosi** [comment]
for which platforms does PR cater to ?

**Comment by keboliu** [comment]
> cater

this is for all Mellanox platform.

**Comment by keboliu** [comment]
Hi @abdosi would you please help to merge this one?

**Comment by liat-grozovik** [comment]
@abdosi please merge

**Comment by prsunny** [comment]
> > cater
> 
> this is for all Mellanox platform.

I think @abdosi 's question was which specific MLNX platform or this applies to all?

**Comment by Junchao-Mellanox** [comment]
The new PSU will apply to SN4700, SN4600C, SN4600. @keboliu please correct me if any mistake.

**Comment by prsunny** [comment]
> The new PSU will apply to SN4700, SN4600C, SN4600. @keboliu please correct me if any mistake.

In that case, prefer not to take to 201911.

**Pull request merged**
