### PR TITLE
[AS4630-54PE]Support platform API2.0

### PR DESCRIPTION
**Pull request by jostar-yang**
**- Why I did it**
Support platform API 2.0
**- How I did it**
Implement code.
**- How to verify it**
Test for each case.
root@sonic:~/sonic_platform# ./component.py
vernios=v37.0b.01.01

root@sonic:~/sonic_platform# ./eeprom.py
my_tlv.get_mac=1C:EA:0B:89:66:80
my_tlv.get_serial=463054PE1936004
my_tlv.get_eeprom={'0xFE': '0x3015E6D4', '0x28': 'x86_64-accton_as4630_54pe-r0', '0x29': '2018.11.00.03', '0x22': 'F0PZZ4654037A', '0x23': '463054PE1936004', '0x21': 'AS4630-54PE-O-AC-F', '0x27': 'R0C', '0x24': '1C:EA:0B:89:66:80', '0x25': '10/08/2019', '0x2B': 'Accton', '0x2C': 'TW', '0x2A': '256', '0x2D': 'Edgecore', '0x2E': '0c.0c.01.00'}

root@sonic:~/sonic_platform# ./psu.py
PSU-1:
get_name=PSU-1
get_presence=1
get_powergood=1
get_voltage=54.62
get_current=0.63
get_power=34.00
get_temperature=30.000
get_voltage_high_threshold=56.12
get_voltage_low_threshold=52.81

root@sonic:/mnt/usb/AS4630/sonic_platform# ./fan.py
Start to debug fan.py
my_fan1present =1
my_fan2 present =1
my_fan3 present =1
my_fan1 speed =18
my_fan2 speed =18
my_fan3 speed =18

./sfp_qsfp.py
port-53, QSPF
my_sfp.get_serial=ERR02X9
my_sfp.get_model()=FTL410QE3C
hwsku_path=/usr/share/sonic/device/x86_64-accton_as4630_54pe-r0/Accton-AS4630-54PE
sefl.index=52
my_sfp.get_name()=Ethernet52
my_sfp.get_rx_los=1
my_sfp.get_tx_fault()=1
get_tx_disable
[False, False, False, False]
set lpmode to False
my_sfp.get_lp_mode=0
my_sfp.get_lp_mode=1
my_sfp.get_temperature=28.6211
my_sfp.get_voltage=3.324
val=0
my_sfp.get_tx_bias=[0.116, 0.074, 0.09, 0.11]
my_sfp.get_rx_power=[-24.437, -23.4679, -40.0, -40.0]
my_sfp.get_reset_status()=0
Do reset
self.port_to_eeprom_mapping[49]=/sys/bus/i2c/devices/18-0050/eeprom
port-49, SFP
my_sfp.get_serial=ADF2093900005HH
my_sfp.get_model()=57-0000076-01
hwsku_path=/usr/share/sonic/device/x86_64-accton_as4630_54pe-r0/Accton-AS4630-54PE
sefl.index=48
my_sfp.get_name()=Ethernet48
my_sfp.get_rx_los=1
my_sfp.get_tx_fault()=0
get_tx_disable
True
my_sfp.get_lp_mode=0
my_sfp.get_temperature=37.5469
my_sfp.get_voltage=3.2919
my_sfp.get_tx_bias=[40.868, 'N/A', 'N/A', 'N/A']
my_sfp.get_rx_power=[-33.0103, 'N/A', 'N/A', 'N/A']

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
can you fix the lgtm alerts?

**Comment by lguohan** [comment]
retest vsimage please

**Comment by jostar-yang** [comment]
OK. I am checking for "the lgtm alerts".

**Comment by jostar-yang** [comment]
> This pull request **introduces 5 alerts** when merging [a756c8d](https://github.com/Azure/sonic-buildimage/commit/a756c8d94875a490f5e509dd8acc23d6d69bdad7) into [458b4ae](https://github.com/Azure/sonic-buildimage/commit/458b4aef484f8ac4722b8041b538145232416c6e) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-buildimage/rev/pr-22b933b3945eb2f9fe084c76f825236503a7ad5a)
> 
> **new alerts:**
> 
> * 4 for Wrong number of arguments in a class instantiation
> * 1 for Testing equality to None

Hi ,
  I don't understand new alerts. Can you check alert  rule?
I check lgtm and found below ,

for index in range(0, NUM_PSU):
    psu = Psu(index)
Call to Psu.__init__ with too few arguments; should be no fewer than 2.
Call to Psu.__init__ with too many arguments; should be no more than 0.

But from below psu.py code, it can inpunt one argument to Psu.__init__()
class Psu(PsuBase):  
    def __init__(self, psu_index):

for index in range(0, NUM_THERMAL):
            thermal = Thermal(index)
Call to Thermal.__init__ with too few arguments; should be no fewer than 3.

But from below thermal.py code, it can input one argument to Thermal.__init__()

class Thermal(ThermalBase):
      def __init__(self, thermal_index):

for index in range(0, NUM_SFP):
    sfp = Sfp(index)

Call to 2 Values with too few arguments; should be no fewer than 2.
Call to Sfp.__init__ with too few arguments; should be no fewer than 3.
Call to 3 Values with too few arguments; should be no fewer than 5.

But from sfp.py as below, it can input one argument to Sfp.__init__()
class Sfp(SfpBase):
    def __init__(self, sfp_index):
        SfpBase.__init__(self)


for index in range(0, NUM_COMPONENT):
    component = Component(index)
Call to Component.__init__ with too many arguments; should be no more than 0.


But from component.py code as below, and it input one argument to Component.__init__.
class Component(ComponentBase):
     def __init__(self, component_index):

**Comment by jostar-yang** [comment]
I  re-send new PR because this is old code.

**Pull request closed without merging**
