### PR TITLE
[Mellanox]: Update FW to 13.2000.1658 version

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>

**- What I did**
Updated Mellanox FW to 13.2000.1658 version

This new FW version includes the following fixes:
- SFP thermal shutdown issue 

**- How I did it**
Updated Mellanox FW version and pointer in appropriate Makefiles

**- How to verify it**
Build an image and run tests

**- Description for the changelog**
[Mellanox]: Update FW to 13.2000.1658 version

### CODE REVIEW

**Comment by lguohan** [comment]
what is the fw fix?

**Comment by volodymyrsamotiy** [comment]
@lguohan, updated PR description with the details

**Comment by liat-grozovik** [comment]
retest this please

**Comment by jleveque** [comment]
Will a similar fix be needed for the master/201911 branches?

**Comment by volodymyrsamotiy** [comment]
@jleveque, yes, similar fix is part of the new FW that we are going to integrate soon to  ```201911``` and ```master``` branches.

**Pull request merged**
