### PR TITLE
[swss] advance swss submodule head

### PR DESCRIPTION
**Pull request by yxieca**
**- Why I did it**
Advance swss submodule to pick up latest changes.

**- How I did it**
Including folowing changes:
- [portsorch] adjust port initialized event back to notice (#1532)

Signed-off-by: Ying Xie <ying.xie@microsoft.com>

- [ ] 201811
- [ ] 201911
- [ ] 202006

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by yxieca** [comment]
retest this please

**Comment by yxieca** [comment]
retest broadcom please

**Comment by yxieca** [comment]
retest vsimage please

**Review by prsunny — APPROVED** [review]

**Comment by yxieca** [comment]
retest vsimage please

**Comment by yxieca** [comment]
retest vsimage please

**Pull request merged**
