### PR TITLE
[utilities]: Update sonic-utilities submodule

### PR DESCRIPTION
**Pull request by stcheng**
Adapt to py-swsssdk refactor of mod_entry and mod_config (#165)
[intfutil]: Fix python indentation (#166)

Signed-off-by: Shu0T1an ChenG <shuche@microsoft.com>

### CODE REVIEW

**Comment by lguohan** [comment]
please update the sonic-py-swsssdk

**Comment by stcheng** [comment]
fixed

it seems that we lack some tests so that even the corresponding submodule is not updated the build passes.

**Comment by jleveque** [comment]
@stcheng: Currently, the PR build test for sonic-utilities only ensures the Debian package is built successfully. I agree that we could use to add a unit test suite in the future.

**Comment by lguohan** [comment]
@taoyl-ms

**Pull request merged**
