### PR TITLE
Invoke disk check periodically.

### PR DESCRIPTION
**Pull request by renukamanavalan**
#### Why I did it
Helps with periodic scan of disk for RO state.
If found, this script makes transient fix and raise error message.

**NOTE**: This requires [PR #1569](https://github.com/Azure/sonic-utilities/pull/1569). Only after that  PR & corresponding submodule update, this PR can be merged.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Comment by lguohan** [comment]
@qiluo-msft, can you review this one?

**Comment by qiluo-msft** [comment]
Pending on https://github.com/Azure/sonic-utilities/pull/1569

**Review by jleveque — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by abdosi** [comment]
@renukamanavalan please create seprate pr for this for 201911.

**Comment by renukamanavalan** [comment]
@abdosi, please pull [#1569](https://github.com/Azure/sonic-utilities/pull/1569) into 201911, before this one.

**Pull request merged**
