### PR TITLE
[bgpcfgd]: Extract classes into their own files. Run bgpcfgd as a module

### PR DESCRIPTION
**Pull request by pavel-shirshov**
**- Why I did it**

**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
retest broadcom please

**Comment by lguohan** [comment]
seems lots of conflicts, maybe rebase?

**Comment by pavel-shirshov** [comment]
this change was done with "allow prefix" feature was merged. So I need to merge "allow list" first, then there will be only one conflict - from this PR https://github.com/Azure/sonic-buildimage/pull/5506

**Comment by pavel-shirshov** [comment]
Close this as I moved the changes to https://github.com/Azure/sonic-buildimage/pull/5535

**Pull request closed without merging**
