### PR TITLE
[202012][Arista] Update platform library submodules

### LINKED ISSUE #8621: 202012 branch image cannot detect PSU power loss event on Arista-7050-QX-32S platform
#### Description
202012 branch image cannot detect PSU power loss event on Arista-7050-QX-32S platform

#### Steps to reproduce the issue:
(Note: PDU connection information is correct, turning off both PDU outlets will cause DUT to lost power).

1. turn off one of the 2 PDU connections towards Arista-7050-QX-32S
2. run "sudo psuutil status" to check PSU status on the PDU side
3.

#### Describe the results you received:
admin@str2-7050qx-32s-acs-02:~$ sudo psuutil status  
PSU    Status
-----  --------
PSU 1  OK
PSU 2  OK

Note that first PDU outlet has been turned off:
yinxi@64b9ea7e4f13:/var/src/sonic-mgmt/ansible$ ./devutils -i str2 -a pdu_status -j -l str2-7050qx-32s-acs-02   
[
    {
        "Action": "status",
        "Host": "str2-7050qx-32s-acs-02",
        "PDU status": [
            {
                "outlet_on": false,
                "output_watts": "0",
                "outlet_id": ".1.1.46",
                "pdu_name": "pdu-122",
                "pdu_index": 0
            },
            {
                "outlet_on": true,
                "output_watts": "129",
                "outlet_id": ".1.1.46",
                "pdu_name": "pdu-121",
                "pdu_index": 1
            }
        ],
        "Summary": []
    }
]

#### Describe the results you expected:
psuutil status shows one of the 2 PSUs being off.

#### Output of `show version`:

```
SONiC Software Version: SONiC.20201231.20
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: 21a1781936
Build date: Fri Aug 27 13:13:07 UTC 2021
Built by: AzDevOps@sonic-int-build-workers-00036B
```

### PR DESCRIPTION
**Pull request by Staphylo**
- Fix psustatus for Clearlake/Cloverdale (fixes #8621)
 - Fix typo in thermal info code

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by sujinmkang** [comment]
@Staphylo can we get the platform api test results to see if there is any regression with new PR?

**Comment by Staphylo** [comment]
@sujinmkang I will try to get this for you

**Pull request merged**
