### PR TITLE
[202012][submodule] update sonic-platform-common and sonic-platform-daemons

### PR DESCRIPTION
**Pull request by vdahiya12**
This PR updates the following commits in sonic-platform-common
9d2e7d5 Add y-cable driver for simulated mux (#213)
e3e8f09 [Y-Cable][Broadcom] Broadcom implementation of YCable class which inherits from YCableBase required for Y-Cable API's in sonic-platform-daemons (#208)

This PR updates the following commits in sonic-platform-daemons

ebc4f3f [Y-Cable] create unknown entries for mux_cable when there is a cable present but module definition is not present/invalid module
b10c417 [xcvrd] initial support for integrating vendor specfic class objects for calling Y-Cable API's inside xcvrd (#197) (#213)
f3fc1ea [y-cable] fix for logging the xcvrd metrics before writing the state to the State-DB (#208)

Signed-off-by: vaibhav-dahiya <vdahiya@microsoft.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by vdahiya12** [comment]
./azp run

**Comment by liat-grozovik** [comment]
@vdahiya12 please note https://github.com/Azure/sonic-buildimage/pull/8627 whihc integrating additional fixes on sonic-utilities.

**Comment by vdahiya12** [comment]
Hi @qiluo-msft , @lguohan both #8627 and #8607 seems to be failing with same testcase on t1-lag. Do we need to fix this ?

**Comment by yozhao101** [comment]
> Hi @qiluo-msft , @lguohan both #8627 and #8607 seems to be failing with same testcase on t1-lag. Do we need to fix this ?
> 
> ____________________ test_container_checker[vlab-03|teamd] _____________________
> 2021-08-30T12:19:46.6146965Z
> 2021-08-30T12:19:46.6147988Z duthosts = <tests.common.devices.duthosts.DutHosts object at 0x7f4ed07e1350>
> 2021-08-30T12:19:46.6149358Z enum_dut_feature_container = 'vlab-03|teamd'
> 2021-08-30T12:19:46.6150545Z rand_selected_dut = vlab-03
> 2021-08-30T12:19:46.6152197Z tbinfo = {'auto_recover': 'False', 'comment': 'Tests virtual switch vm', 'conf-name': 'vms-kvm-t1-lag', 'duts': ['vlab-03'], ...}
> 2021-08-30T12:19:46.6152771Z
> 2021-08-30T12:19:46.6153942Z def test_container_checker(duthosts, enum_dut_feature_container, rand_selected_dut, tbinfo):
> 2021-08-30T12:19:46.6156405Z """Tests the feature of container checker.
> 2021-08-30T12:19:46.6156878Z
> 2021-08-30T12:19:46.6157423Z This function will check whether the container names will appear in the Monit
> 2021-08-30T12:19:46.6159241Z alerting message if they are stopped explicitly or they hit start limitation.
> 2021-08-30T12:19:46.6159954Z
> 2021-08-30T12:19:46.6160517Z Args:
> 2021-08-30T12:19:46.6161159Z duthosts: list of DUTs.
> 2021-08-30T12:19:46.6162102Z enum_dut_feature_container: A list contains strings ("<dut_name>|<container_name>").
> 2021-08-30T12:19:46.6163032Z rand_selected_dut: The fixture returns a randomly selected DuT.
> 2021-08-30T12:19:46.6163649Z tbinfo: Testbed information.
> 2021-08-30T12:19:46.6164107Z
> 2021-08-30T12:19:46.6164664Z Returns:
> 2021-08-30T12:19:46.6165234Z None.
> 2021-08-30T12:19:46.6165594Z """
> 2021-08-30T12:19:46.6172148Z dut_name, container_name = decode_dut_and_container_name(enum_dut_feature_container)
> 2021-08-30T12:19:46.6173280Z pytest_require(dut_name == rand_selected_dut.hostname and container_name != "unknown",
> 2021-08-30T12:19:46.6174791Z "Skips testing container_checker of container '{}' on the DuT '{}' since another DuT '{}' was chosen."
> 2021-08-30T12:19:46.6175624Z .format(container_name, dut_name, rand_selected_dut.hostname))
> 2021-08-30T12:19:46.6176177Z duthost = duthosts[dut_name]
> 2021-08-30T12:19:46.6176606Z
> 2021-08-30T12:19:46.6177123Z loganalyzer = LogAnalyzer(ansible_host=duthost, marker_prefix="container_checker")
> 2021-08-30T12:19:46.6177753Z loganalyzer.expect_regex = []
> 2021-08-30T12:19:46.6178160Z
> 2021-08-30T12:19:46.6178643Z disabled_containers = get_disabled_container_list(duthost)
> 2021-08-30T12:19:46.6179003Z
> 2021-08-30T12:19:46.6179265Z skip_containers = disabled_containers[:]
> 2021-08-30T12:19:46.6179552Z skip_containers.append("gbsyncd")
> 2021-08-30T12:19:46.6179861Z skip_containers.append("database")
> 2021-08-30T12:19:46.6180816Z # Skip 'radv' container on devices whose role is not T0.
> 2021-08-30T12:19:46.6181428Z if tbinfo["topo"]["type"] != "t0":
> 2021-08-30T12:19:46.6181978Z skip_containers.append("radv")
> 2021-08-30T12:19:46.6182339Z
> 2021-08-30T12:19:46.6182597Z pytest_require(container_name not in skip_containers,
> 2021-08-30T12:19:46.6183162Z "Container '{}' is skipped for testing.".format(container_name))
> 2021-08-30T12:19:46.6183524Z stop_container(duthost, container_name)
> 2021-08-30T12:19:46.6183745Z
> 2021-08-30T12:19:46.6184028Z expected_alerting_message = get_expected_alerting_message(container_name)
> 2021-08-30T12:19:46.6184369Z loganalyzer.expect_regex.extend(expected_alerting_message)
> 2021-08-30T12:19:46.6184669Z marker = loganalyzer.init()
> 2021-08-30T12:19:46.6184902Z
> 2021-08-30T12:19:46.6185260Z # Wait for 1 minutes such that Monit has a chance to write alerting message into syslog.
> 2021-08-30T12:19:46.6185929Z logger.info("Sleep 1 minutes to wait for the alerting message...")
> 2021-08-30T12:19:46.6186298Z time.sleep(70)
> 2021-08-30T12:19:46.6186616Z
> 2021-08-30T12:19:46.6187051Z logger.info("Checking the alerting messages from syslog...")
> 2021-08-30T12:19:46.6190985Z > loganalyzer.analyze(marker)
> 2021-08-30T12:19:46.6191338Z
> 2021-08-30T12:19:46.6200903Z container_name = 'teamd'
> 2021-08-30T12:19:46.6201964Z disabled_containers = ['sflow', 'nat']
> 2021-08-30T12:19:46.6202861Z dut_name = 'vlab-03'
> 2021-08-30T12:19:46.6203554Z duthost = vlab-03
> 2021-08-30T12:19:46.6204061Z duthosts = <tests.common.devices.duthosts.DutHosts object at 0x7f4ed07e1350>
> 2021-08-30T12:19:46.6205109Z enum_dut_feature_container = 'vlab-03|teamd'
> 2021-08-30T12:19:46.6206358Z expected_alerting_message = ['.*Expected containers not running._teamd._']
> 2021-08-30T12:19:46.6207172Z loganalyzer = <tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzer instance at 0x7f4ecde00640>
> 2021-08-30T12:19:46.6208371Z marker = 'container_checker.2021-08-30-12:15:27'
> 2021-08-30T12:19:46.6210027Z rand_selected_dut = vlab-03
> 2021-08-30T12:19:46.6210880Z skip_containers = ['sflow', 'nat', 'gbsyncd', 'database', 'radv']
> 2021-08-30T12:19:46.6211865Z tbinfo = {'auto_recover': 'False', 'comment': 'Tests virtual switch vm', 'conf-name': 'vms-kvm-t1-lag', 'duts': ['vlab-03'], ...}
> 2021-08-30T12:19:46.6212466Z
> 2021-08-30T12:19:46.6212895Z container_checker/test_container_checker.py:244:

I am checking this issue and will figure out the root cause.

**Comment by liat-grozovik** [comment]
@vdahiya12 can you please update PR description?

**Pull request merged**
