### PR TITLE
[docker-platform-monitor]: Add smartmontools 6.6-1

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- What I did**

- Add smartmontools version 6.6-1 to platform monitor docker
(to support SSD testing)

**- How I did it**

1. Download smartmontools source from debian server
2. Build smartmontools with strech debian
3. Add smartmontools to pmon docker

**- How to verify it**

- Run command _smartctl_ on SONiC

Signed-off-by: Wirut Getbamrung wgetbumr@celestica.com

### CODE REVIEW

**Comment by mudsut4ke** [comment]
Retest this please

**Comment by zhenggen-xu** [comment]
Can you add  the output from the smartctl command?
Does the smartd service running by default on the system after this fix?

**Comment by mudsut4ke** [comment]
Here is an output from smartctl and smartd
( only smartctl command can access from sonic cli)

```
root@sonic:~# show version 
SONiC Software Version: SONiC.HEAD.3935-92958e2
Distribution: Debian 9.8
Kernel: 4.9.0-8-2-amd64
Build commit: 92958e2
Build date: Mon Apr  1 06:45:45 UTC 2019
Built by: johnar@jenkins-worker-1

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.3935-92958e2   b876cb6118ed        361MB
docker-syncd-brcm          latest              b876cb6118ed        361MB
docker-dhcp-relay          HEAD.3935-92958e2   c015caf978ec        256MB
docker-dhcp-relay          latest              c015caf978ec        256MB
docker-teamd               HEAD.3935-92958e2   fe56807e38a7        274MB
docker-teamd               latest              fe56807e38a7        274MB
docker-snmp-sv2            HEAD.3935-92958e2   2253115a19cb        294MB
docker-snmp-sv2            latest              2253115a19cb        294MB
docker-lldp-sv2            HEAD.3935-92958e2   48f061d61cc6        274MB
docker-lldp-sv2            latest              48f061d61cc6        274MB
docker-fpm-quagga          HEAD.3935-92958e2   2b8446835a87        281MB
docker-fpm-quagga          latest              2b8446835a87        281MB
docker-orchagent-brcm      HEAD.3935-92958e2   e99869b4a44b        315MB
docker-orchagent-brcm      latest              e99869b4a44b        315MB
docker-database            HEAD.3935-92958e2   2a8da020e01d        280MB
docker-database            latest              2a8da020e01d        280MB
docker-sonic-telemetry     HEAD.3935-92958e2   4667ba5feaf8        300MB
docker-sonic-telemetry     latest              4667ba5feaf8        300MB
docker-platform-monitor    HEAD.3935-92958e2   2c789c0a078d        324MB
docker-platform-monitor    latest              2c789c0a078d        324MB
docker-router-advertiser   HEAD.3935-92958e2   7ff966f67961        279MB
docker-router-advertiser   latest              7ff966f67961        279MB

root@sonic:~# smartctl -V
smartctl 6.6 2017-11-05 r4594 [x86_64-linux-4.9.0-8-2-amd64] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

smartctl comes with ABSOLUTELY NO WARRANTY. This is free
software, and you are welcome to redistribute it under
the terms of the GNU General Public License; either
version 2, or (at your option) any later version.
See http://www.gnu.org for further details.

smartmontools release 6.6 dated 2017-11-05 at 15:20:58 UTC
smartmontools SVN rev 4594 dated 2017-11-05 at 15:21:35
smartmontools build host: x86_64-pc-linux-gnu
smartmontools build with: C++14, GCC 6.3.0 20170516
smartmontools configure arguments: '--prefix=/usr' '--build=x86_64-linux-gnu' '--host=x86_64-linux-gnu' '--sysconfdir=/etc' '--mandir=/usr/share/man' '--with-initscriptdir=no' '--docdir=/usr/s'
root@sonic:~# 
root@sonic:~# docker exec -it pmon smartd -V
smartd 6.6 2017-11-05 r4594 [x86_64-linux-4.9.0-8-2-amd64] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

smartd comes with ABSOLUTELY NO WARRANTY. This is free
software, and you are welcome to redistribute it under
the terms of the GNU General Public License; either
version 2, or (at your option) any later version.
See http://www.gnu.org for further details.

smartmontools release 6.6 dated 2017-11-05 at 15:20:58 UTC
smartmontools SVN rev 4594 dated 2017-11-05 at 15:21:35
smartmontools build host: x86_64-pc-linux-gnu
smartmontools build with: C++14, GCC 6.3.0 20170516
smartmontools configure arguments: '--prefix=/usr' '--build=x86_64-linux-gnu' '--host=x86_64-linux-gnu' '--sysconfdir=/etc' '--mandir=/usr/share/man' '--with-initscriptdir=no' '--docdir=/usr/s'
root@sonic:~# 

```

**Comment by qiluo-msft** [comment]
Hi @mudsut4ke 
I shared those source packages in Azure Blob, in order to stable the build process. Could you use those links?

https://sonicstorage.blob.core.windows.net/packages/debian/smartmontools_6.6-1.debian.tar.xz?sv=2015-04-05&sr=b&sig=H0RFeC41MCvhTQCln85DuPLn5v2goozwz%2FB9sA9p5eQ%3D&se=2046-08-20T23%3A46%3A02Z&sp=r
https://sonicstorage.blob.core.windows.net/packages/debian/smartmontools_6.6-1.dsc?sv=2015-04-05&sr=b&sig=IS7FKUN%2Bvq0T55f4X2hGAViB70Y%2FgzjGgvzpUJLyUfA%3D&se=2046-08-20T23%3A46%3A57Z&sp=r
https://sonicstorage.blob.core.windows.net/packages/debian/smartmontools_6.6.orig.tar.gz?sv=2015-04-05&sr=b&sig=JZx4qiLuO36T0rsGqk4V2RDuWjRw6NztsLK7vlBYAkg%3D&se=2046-08-20T23%3A47%3A13Z&sp=r

**Comment by mudsut4ke** [comment]
> Hi @mudsut4ke
> I shared those source packages in Azure Blob, in order to stable the build process. Could you use those links?
> 
> https://sonicstorage.blob.core.windows.net/packages/debian/smartmontools_6.6-1.debian.tar.xz?sv=2015-04-05&sr=b&sig=H0RFeC41MCvhTQCln85DuPLn5v2goozwz%2FB9sA9p5eQ%3D&se=2046-08-20T23%3A46%3A02Z&sp=r
> https://sonicstorage.blob.core.windows.net/packages/debian/smartmontools_6.6-1.dsc?sv=2015-04-05&sr=b&sig=IS7FKUN%2Bvq0T55f4X2hGAViB70Y%2FgzjGgvzpUJLyUfA%3D&se=2046-08-20T23%3A46%3A57Z&sp=r
> https://sonicstorage.blob.core.windows.net/packages/debian/smartmontools_6.6.orig.tar.gz?sv=2015-04-05&sr=b&sig=JZx4qiLuO36T0rsGqk4V2RDuWjRw6NztsLK7vlBYAkg%3D&se=2046-08-20T23%3A47%3A13Z&sp=r

OK, Updated

**Pull request merged**
