### PR TITLE
[sonic-platform-common][sonic-platform-daemon] Update submodules

### PR DESCRIPTION
**Pull request by keboliu**
**- What I did**
update submodules to pick up the recent platform related change.

**- How I did it**
update sonic-platform-common pointer
update sonic-platform-daemon pointer

[sonic-platform-common]

-  [sonic_sfp] Interpret sff 'int' element =0 as valid value (https://github.com/Azure/sonic-platform-common/pull/51)
-  add more error code to get_transceiver_change_event ((https://github.com/Azure/sonic-platform-common/pull/50)
-  [sonic_platform_base] support new-platform-api-based daemons ((https://github.com/Azure/sonic-platform-common/pull/48)
-  sync change to sonic_platform_base/sonic_sfp and create symbol link ((https://github.com/Azure/sonic-platform-common/pull/49)
-  Add parser support for Tx_RxLos,TxFault, PowerControl, ResetStatus in sff8436.py ((https://github.com/Azure/sonic-platform-common/pull/45)
-  readd type_abbrv_name in sonic_sfp/sff8436.py ((https://github.com/Azure/sonic-platform-common/pull/44)
-  [psu_base] get_status_led() returns current state of the status LED ((https://github.com/Azure/sonic-platform-common/pull/39)
-  Fix abbrv name for OSFP ((https://github.com/Azure/sonic-platform-common/pull/36)
-  [sff8436] support "Control Bytes" and "Options" ((https://github.com/Azure/sonic-platform-common/pull/38)
-  sonic_sfp: avoid possible key error in get_physical_to_logical() ((https://github.com/Azure/sonic-platform-common/pull/37)

[sonic-platform-daemons]

-  [xcvrd] Enhance xcvrd to handle new system level event/error (https://github.com/Azure/sonic-platform-daemons/pull/39)
-  [xcvrd] Support both new platform API and old platform plugins (https://github.com/Azure/sonic-platform-daemons/pull/38)
-  [psud] Support both new platform API and old platform plugins (https://github.com/Azure/sonic-platform-daemons/pull/37)
-  [syseepromd] Support both new platform API and old platform plugins (https://github.com/Azure/sonic-platform-daemons/pull/36)
-  Add missing import statemet (https://github.com/Azure/sonic-platform-daemons/pull/32)
-  sonic_xcvrd: Support for DOM Threshold values for EEPROM dump (https://github.com/Azure/sonic-platform-daemons/pull/29)

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by akokhan** [comment]
Could you please include the latest commit added Aug 12, 2019 as well? Thanks.

**Comment by keboliu** [comment]
> Could you please include the latest commit added Aug 12, 2019 as well? Thanks.

which repo and which commit ID are you referring to?  if no other dependency for that commit ID I can do it.

**Comment by lguohan** [comment]
can you add commits into the commit message?

**Comment by akokhan** [comment]
> > Could you please include the latest commit added Aug 12, 2019 as well? Thanks.
> 
> which repo and which commit ID are you referring to? if no other dependency for that commit ID I can do it.

sonic-platform-common repo, commit 0caf265 ([sonic_sfp] Interpret sff 'int' element =0 as valid value) which is the latest. Thank you a lot.

**Comment by keboliu** [comment]
> can you add commits into the commit message?

updated, please check.

**Pull request merged**
