### PR TITLE
[submodule]: update sonic-wpa-supplicant

### PR DESCRIPTION
**Pull request by lguohan**
**- Why I did it**
* 3b330db4a 2021-01-18 | [build]: Fix build error when compiling for armhf (32-bit) (#30) (HEAD, origin/master, origin/HEAD, master) [dflynn-Nokia]
* 56aaa225b 2021-01-16 | [ci]: add pipeline for armhf and arm64 (#29) [lguohan]
* 90da6141c 2021-01-12 | [ci]: propagate the correct error code the next step (#27) [lguohan]

**- How I did it**
submodule update

**- How to verify it**
check the build

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
@Pterosaur to review

**Comment by Pterosaur** [comment]
> @Pterosaur to review

Please wait for this PR: https://github.com/Azure/sonic-wpa-supplicant/pull/31

**Comment by lguohan** [comment]
kvm test passed.

**Comment by lguohan** [comment]
@Pterosaur , please submit a new pr to update that. thanks.

**Pull request merged**
