### PR TITLE
[Mellanox] Fix thermal control bugs

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**- What I did**

1. Fix issue: add PSU fan no matter sysfs exists or not
2. Fix issue: get fan direction per drawer index instead of per fan index
3. Fix issue: clarify logs for PSU absence and PSU power off
4. Add 2100/2010 support to get fan presence status
5. Fix issue: pmon docker exists on 3800
6. Add unit test for code changes 

**- How I did it**

**- How to verify it**

Manually verify and run existing regression cases

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
Depend on https://github.com/Azure/sonic-platform-common/pull/78

**Comment by jleveque** [comment]
@Junchao-Mellanox: https://github.com/Azure/sonic-platform-common/pull/78 has merged. Please update the submodule in this PR.

**Comment by keboliu** [comment]
retest this please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by Junchao-Mellanox** [comment]
Retest mellanox please

**Comment by Junchao-Mellanox** [comment]
I

**Pull request closed without merging**
