### PR TITLE
[teamd]: update teamd docker to stretch

### PR DESCRIPTION
**Pull request by hzheng5**
Signed-off-by: Haiyang Zheng <haiyang.z@alibaba-inc.com>

**- What I did**
* update teamd docker to stretch

**- How I did it**
* use stretch base docker and config engine to build teamd docker

**- How to verify it**
* lag flapping/teamd docker restart/system reload

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
why baseimage build failed? can you investigate?

**Comment by hzheng5** [comment]
retest please

**Comment by hzheng5** [comment]
retest this please

**Comment by lguohan** [comment]
@hzheng5, any update on this PR?

**Comment by hzheng5** [comment]
> @hzheng5, any update on this PR?

Hi @lguohan 

I did some investigation. Looks like the base build is using "BLDENV=stretch make -f Makefile.work stretch" to compile all stretch targets. Our teamd docker is dependent on  swss, which is dependent on libsairedis and libsai.

For generic platform, we don't build any libsai on stretch, so we are hitting the following error.

/sonic/src/sonic-sairedis/meta/.libs/libsaimetadata.so /sonic/src/sonic-sairedis/meta/.libs/libsaimeta.so -ldl
/usr/bin/ld: cannot find -lsai
collect2: error: ld returned 1 exit status
Makefile:650: recipe for target 'syncd' failed
make[4]: *** [syncd] Error 1
make[4]: Leaving directory '/sonic/src/sonic-sairedis/syncd'

Is there a way to include any libsai to generic platform ? Or to block teamd build in baseimage.

Thanks,
Haiyang

**Comment by hzheng5** [comment]
> @hzheng5, any update on this PR?

Another question is SWSS has also been upgraded to stretch, why "BLDENV=stretch make -f Makefile.work stretch"  didn't trigger the swss docker build, it may hit the same issue here.

Did I miss anything that excludes swss docker from the stretch target?

Thanks,
Haiyang

**Comment by lguohan** [comment]
#2771 might solve this issue.

**Comment by hzheng5** [comment]
> #2771 might solve this issue.

Cool. Thanks. Let me give a try locally first.

**Comment by lguohan** [comment]
retest this please

**Comment by springxucoder** [comment]
For generic platform, we don't build any libsai on stretch, so we are hitting the following error.

/sonic/src/sonic-sairedis/meta/.libs/libsaimetadata.so /sonic/src/sonic-sairedis/meta/.libs/libsaimeta.so -ldl
/usr/bin/ld: cannot find -lsai
collect2: error: ld returned 1 exit status
Makefile:650: recipe for target 'syncd' failed
make[4]: *** [syncd] Error 1
make[4]: Leaving directory '/sonic/src/sonic-sairedis/syncd'

Is there a way to include any libsai to generic platform ? Or to block teamd build in baseimage.

SDE编译报错，会有以上错误

**Pull request merged**
