### PR TITLE
Remove SSH host keys after installing the custom version of sshd

### PR DESCRIPTION
**Pull request by saiarcot895**
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

#### Why I did it

SSH host keys are getting packaged in the image, because there's a custom version of sshd getting installed after the keys are initially removed, resulting in the host keys getting regenerated. They should instead be generated on first boot/use.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [x] 202106
- [x] 202111

### CODE REVIEW

**Review by abdosi — DISMISSED** [review]

**Review by abdosi — COMMENTED** [review]
@saiarcot895 after this change SSH server do no run with the error

`Mar 20 19:55:26 sonic sshd[462]: sshd: no hostkeys available -- exiting.
Mar 20 19:55:26 sonic sshd[462]: sshd: no hostkeys available -- exiting.`

**Comment by saiarcot895** [comment]
Updated the PR to properly create the SSH host keys before starting sshd.

**Comment by abdosi** [comment]
testing this 2 commit on internal branch,

**Review by abdosi — APPROVED** [review]
tested and looks fine.

**Comment by liuh-80** [comment]
202012 branch PR merged: https://github.com/sonic-net/sonic-buildimage/pull/11140

**Pull request merged**
