### PR TITLE
[mellanox] enable ISSU on SPC2 systems

### PR DESCRIPTION
**Pull request by stepanblyschak**
Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by stepanblyschak** [comment]
retest vsimage please

**Comment by stepanblyschak** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by stepanblyschak** [comment]
@liat-grozovik Yes

**Pull request merged**
