### PR TITLE
[swsssdk]: Update nomenclature: 'sswsdk' -> 'swsssdk'

### PR DESCRIPTION
**Pull request by jleveque**
This PR is dependent upon the PR @ https://github.com/Azure/sonic-py-swsssdk/pull/4.

sonic-py-swsssdk submodule will need to be updated before this PR can be merged.

### CODE REVIEW

**Comment by lguohan** [comment]
seems like there is build failure.

**Comment by jleveque** [comment]
Builds are expected to fail until Azure/sonic-py-swsssdk#4 is merged and the submodule pointer is updated.

**Comment by lguohan** [comment]
approved Azure/sonic-py-swsssdk#4

**Comment by jleveque** [comment]
Mellanox build failure seems to be a Jenkins bug, "Process leaked file descriptors." This should be safe to merge.

**Pull request merged**
