### PR TITLE
[Mellanox] update SDK/FW

### PR DESCRIPTION
**Pull request by mykolaf**
SDK:
4.3.1634

FW:
13.2000.1634
29.2000.1634

Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>

Integrating official Mellanox SDK/FW release as a pre condition for getting new Mellanox SAI release with hash changes (inner field) and 3k VXLAN scale. As well as bug fix for Spectrum LP mode and Spectrum 2 PFC WD

### CODE REVIEW

**Comment by mykolaf** [comment]
reteset mellanox please

**Comment by mykolaf** [comment]
retest mellanox please

**Comment by liat-grozovik** [comment]
retest vs please

**Comment by liat-grozovik** [comment]
Integrating official Mellanox SDK/FW release as a pre condition for getting new Mellanox SAI release with hash changes (inner field) and 3k VXLAN scale. As well as bug fix for Spectrum LP mode and Spectrum 2 PFC WD

**Pull request merged**
