### PR TITLE
[DELL][Z9100,S6100,S6000] Platform 2.0 SFP Changes

### PR DESCRIPTION
**Pull request by sridhar-ravindran**
**- What I did**
Added support for SFP APIs for platform 2.0
**- How I did it**
        modified:   platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/__init__.py
        modified:   platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/chassis.py
        new file:   platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/sfp.py
        modified:   platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/__init__.py
        modified:   platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/chassis.py
        new file:   platform/broadcom/sonic-platform-modules-dell/s6100/sonic_platform/sfp.py
        modified:   platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/__init__.py
        modified:   platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/chassis.py
        new file:   platform/broadcom/sonic-platform-modules-dell/z9100/sonic_platform/sfp.py

Added support in sfp.py file which will be generic. Send the eeprom path and sfp_control path from chassis.py

**- How to verify it**
Added test show commands to invoke the 2.0 api and check the results.

**- Description for the changelog**

[DELL][Z9100,S6100,S6000] Platform 2.0 SFP Changes
**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by sridhar-ravindran** [comment]
[s6000_sfp.txt](https://github.com/Azure/sonic-buildimage/files/3441096/s6000_sfp.txt)
[s6100_sfp.txt](https://github.com/Azure/sonic-buildimage/files/3441097/s6100_sfp.txt)
[z9100_sfp.txt](https://github.com/Azure/sonic-buildimage/files/3441098/z9100_sfp.txt)

**Comment by jleveque** [comment]
Retest this please

**Comment by lguohan** [comment]
retest broadcom please

**Comment by jleveque** [comment]
@sridhar-ravindran: Please fix new conflicts

**Comment by sridhar-ravindran** [comment]
> @sridhar-ravindran: Please fix new conflicts

Hi @jleveque 
I have synced to latest and resolved all conflicts.
-Sridhar.R

**Comment by lguohan** [comment]
retest this please

**Pull request merged**
