### PR TITLE
[swss]: Wait for vlan intf to start ndppd 

### PR DESCRIPTION
**Pull request by theasianpianist**
Second try for PR #10036 (had to be reverted due to a bug)

#### Why I did it
If the VLAN interface is not up when ndppd starts, it will fail to enable `allmulti` mode on the interface and be unable to process received NDP packets

The following logs are seen:
```
/var/log/syslog.33.gz:Feb 18 10:33:12.825406 sonic INFO swss#/supervisord: ndppd (error) Failed to set allmulti: No such device
```
#### How I did it
Use the `wait_for_link` script currently used by `radv` to delay ndppd startup until the vlan interface is ready

#### How to verify it
Apply the changes to a device. `config reload` the device and confirm that the above error logs are not observed when ndppd starts. Run the `arp/test_arp_dualtor.py::test_proxy_arp` test case and verify it passes. 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by gord1306** [comment]
Hi, there was a similar [PR 9476](https://github.com/Azure/sonic-buildimage/pull/9476) that I created before to check PortInitDone, what I was thinking is whether the XXXsyncd/XXXmgrd should not be started until the PortInitDone being presented?

**Comment by theasianpianist** [comment]
> Hi @theasianpianist @prsunny, there was a similar [PR 9476](https://github.com/Azure/sonic-buildimage/pull/9476) that I created before to check PortInitDone, what I was thinking is whether the XXXsyncd/XXXmgrd should not be started until the PortInitDone being presented?

@prsunny can you comment on this?

**Comment by prsunny** [comment]
> > Hi @theasianpianist @prsunny, there was a similar [PR 9476](https://github.com/Azure/sonic-buildimage/pull/9476) that I created before to check PortInitDone, what I was thinking is whether the XXXsyncd/XXXmgrd should not be started until the PortInitDone being presented?
> 
> @prsunny can you comment on this?

This change seems to be impactful and has to be tested with warmboot scenarios etc before confirming.

**Pull request merged**
