### PR TITLE
[as7326-54x] Remove not need executable flag

### PR DESCRIPTION
**Pull request by jostar-yang**
**- Why I did it**
Debian service file  that is not need  executable permission 
**- How I did it**
Remove executable bit from the service files
**- How to verify it**
Original files that cause OS to show below,
2020-12-28 10:01:25,972 T0000: INFO  [D1-H5] Dec 28 09:56:05.475188 sonic WARNING systemd[1]: Configuration file /lib/systemd/system/as7326-platform-monitor-fan.service is marked executable. 

After remove executable bit, no such log to show.
**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by fk410167 — COMMENTED** [review]
Looks good to me

**Review by jleveque — APPROVED** [review]

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by fk410167** [comment]
Retest vsimage please

**Pull request merged**
