### PR TITLE
[sonic_daemon_base] add load_chassis method to daemon_base

### PR DESCRIPTION
**Pull request by stephenxs**
**- What I did**
add load_chassis method to daemon_base.

**- How I did it**
add load_chassis method to daemon_base

**- How to verify it**
test daemons with/without new platform api enabled

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Is this necessary? Not all daemons will need access to the platform API. I feel like the platform API should only be imported on an as-needed basis in the daemons which need it. I don't feel like this gives any beneficial abstraction, but could instead add confusion.

**Comment by stephenxs** [comment]
> Is this necessary? Not all daemons will need access to the platform API. I feel like the platform API should only be imported on an as-needed basis in the daemons which need it. I don't feel like this gives any beneficial abstraction, but could instead add confusion.

Yes. Only some of the daemons need it. But I think the principle of abstracting interfaces into the base class is to provide a common way to do something and avoid duplicate code. 
in this sense, is it better to provide a common way to load platform for some daemons who need it?

**Comment by jleveque** [comment]
I guess the main reason I'm leaning against this is I'm not a fan of calling a function in a library which will import a new package into the client. I feel this makes the client code less understandable, because you reference classes and functions that have no obvious declaration.

**Comment by stephenxs** [comment]
> I guess the main reason I'm leaning against this is I'm not a fan of calling a function in a library which will import a new package into the client. I feel this makes the client code less understandable, because you reference classes and functions that have no obvious declaration.

Got your point. In this sense, maybe you are correct. I'll reflect this idea.

**Comment by stephenxs** [comment]
BTW, please also help to review this PR https://github.com/Azure/sonic-platform-daemons/pull/35/files regarding whether it aligns with what we discussed last week.
Thank you.

**Comment by stephenxs** [comment]
BTW, please also help to review this PR https://github.com/Azure/sonic-platform-daemons/pull/35/files regarding whether it aligns with what we discussed last week. Thank you.

**Comment by stephenxs** [comment]
> I guess the main reason I'm leaning against this is I'm not a fan of calling a function in a library which will import a new package into the client. I feel this makes the client code less understandable, because you reference classes and functions that have no obvious declaration.

Having reflected it, I tend to agree that it is unnecessary to introduce a new interface which loads new platform api, so I'm going to close this PR.

**Pull request closed without merging**
