### PR TITLE
Summary: add ruijie b6510 device

### PR DESCRIPTION
**Pull request by tim-rj**
**- What I did**
    add support of ruijie b6510 device
**- How I did it**
    add ruijie b6510 platform and device
**- How to verify it**
    compile SONiC bin and run in ruijie b6510 device
**- Description for the changelog**
    add ruijie b6510 device

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tim-rj** [comment]
does this problem is some like this issues？
https://github.com/Azure/sonic-buildimage/issues/1924

**Comment by tim-rj** [comment]
Is this the same problem as https://github.com/Azure/sonic-buildimage/issues/1924
https://github.com/Azure/sonic-buildimage/pull/1925/commits/b7999da70bcc0a4646badf0ac47523c36a15f5f6
It seems that it is not caused by my PR. How can I  continue my PR?

**Comment by lguohan** [comment]
for new platforms, please submit to master branch first.

**Comment by lguohan** [comment]
new device needs to go to master first.

**Pull request closed without merging**
