### PR TITLE
[201911][submodule]: Advance sonic-utilities

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

#### Why I did it
* Advanced submodule to pick up FDB CLI improvements

#### How I did it
* Advanced `sonic-utilities` submodule

#### How to verify it
1. make configure PLATFORM=mellanox
2. make target/sonic-mellanox.bin

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog

```
Commits on Oct 26, 2021
Remove exec from platform_reboot call to prevent reboot hang (#1881) 066b5adf6d737a5bd174123d4d00dab4b6110cf6
  
Commits on Nov 17, 2021
[fdbshow]: Handle FDB cleanup gracefully. (#1918) c80321c98d0741f340d2900108bad7fed76c80cd
```

#### A picture of a cute animal (not mandatory but encouraged)
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by yxieca** [comment]
@nazariig please list the utilities repo commits included by this PR.

**Comment by nazariig** [comment]
> @nazariig please list the utilities repo commits included by this PR in the PR comments.

@yxieca already there - please check `Description for the changelog`

**Review by yxieca — APPROVED** [review]

**Comment by nazariig** [comment]
@liat-grozovik can you please help to merge?

**Comment by nazariig** [comment]
@qiluo-msft can you please help to merge?

**Pull request merged**
