### PR TITLE
[submodule]: update sonic-utilities

### PR DESCRIPTION
**Pull request by lguohan**
```
* 794cdd3 2021-02-08 | Fix: initialize SonicDBConfig differently for single or multi_asic (#1409) [Qi Luo]
* 16b2274 2021-02-08 | Support shared headroom pool on top of dynamic buffer calculation (#1348) [Stephen Sun]
* 2ad1168 2021-02-06 | Fix unsupported fs.squashfs extraction in sonic-installer (#1366) [Samuel Angebault]
* 7578f08 2021-02-06 | [show] Use proper variable to avoid exception in natshow script (#1383) [maksymbelei95]
* 910d284 2021-02-06 | Set up CI with Azure Pipelines [lguohan]
* 270208b 2021-02-05 | [config reload]: Restart mux container (#1401) [Lawrence Lee]
* e6cce21 2021-02-04 | Advertise ipv6 link local address (#1402) [Sumukha Tumkur Vani]
* a6e322a 2021-02-04 | [storyteller] Enhance the storyteller utility (#1400) [Danny Allen]
* 5cff775 2021-02-05 | [show] Fix int status when portchannel is in the system (#1376) [Dmytro]
* 9e0a4fa 2021-02-04 | [config][show] cli support for retrieving ber, eye-info and configuring prbs, loopback on Y-cable  (#1386) [vdahiya12]
* 9ac47e5 2021-02-03 | Skip route check for tun0 interfaces (#1399) [Prince Sunny]
* ba68aed 2021-02-03 | do not parse stderr to get correct routing stack (#1398) [lguohan]
* aa7b90e 2021-02-03 | [storyteller] allow storyteller to work on downloaded logs (#1388) [Ying Xie]
* a6ae218 2021-02-02 | [vrf]: Fix freezing during interface binding (#1325) [maksymbelei95]
* 2e1f354 2021-02-01 | Use SonicV2Connector/ConfigDBConnector/SonicDBConfig from swsscommon instread of swsssdk (#1392) [Qi Luo]
```

**- Why I did it**
update submodule 

**- How I did it**

**- How to verify it**
pr test

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by qiluo-msft — DISMISSED** [review]

**Comment by jleveque** [comment]
KVM check build is failing because with this submodule update, sonic-utilities begins depending on sonic-platform-common. I have opened https://github.com/Azure/sonic-buildimage/pull/6703 to add this dependency. Once that PR merges, the check builds should pass.

**Comment by qiluo-msft** [comment]
@lguohan could you help move submodule again to include this commit
```
794cdd3 2021-02-08 | Fix: initialize SonicDBConfig differently for single or multi_asic (#1409) [Qi Luo]
```

**Comment by lguohan** [comment]
@qiluo-msft, done

**Review by qiluo-msft — APPROVED** [review]
I updated the PR description

**Comment by lguohan** [comment]
@qiluo-msft, can you check the pr build, looks like we still have the error msg.

https://dev.azure.com/mssonic/build/_build/results?buildId=3347&view=ms.vss-test-web.build-test-results-tab&runId=41976&paneView=debug&resultId=100000

**Comment by lguohan** [comment]
@qiluo-msft, i can see other places have the same issue. can you fix all of them once for all?

```
acl_loader/main.py:        SonicDBConfig.load_sonic_global_db_config()
config/main.py:    SonicDBConfig.load_sonic_global_db_config()
crm/main.py:    SonicDBConfig.load_sonic_global_db_config()
scripts/db_migrator.py:            SonicDBConfig.load_sonic_global_db_config(namespace=args.namespace)
scripts/lldpshow:        SonicDBConfig.load_sonic_global_db_config()
scripts/portconfig:        SonicDBConfig.load_sonic_global_db_config(namespace=args.namespace)
tests/mock_tables/dbconnector.py:    # SonicDBConfig load_sonic_global_db_config
tests/mock_tables/dbconnector.py:    SonicDBConfig.load_sonic_global_db_config(
```

**Comment by qiluo-msft** [comment]
@lguohan Could you update the submodule again to include below commit
```
73e28b9 2021-02-11 | Fix: initialize SonicDBConfig differently for single or multi_asic (continued) (#1417) [Qi Luo]
```

**Pull request closed without merging**
