### PR TITLE
[submodule] Update submodule for sonic-utilities

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
0d538d3 [ci]: Support code diff coverage (#1834)
48887d1 [config] support for configuring muxcable to standby mode of operation (#1837)
2088a9a Provide support to install platform extensions (#1578)
c97fe54 Add check_db_integrity script to setup.py (#1828)
c0b9917 [debug dump util] COPP Module Added (#1670)
826311c [techsupport] Removed interactive option for docker commands and Improved Error Reporting (#1723)
ce11545 [config reload] Removed job-mode for sonic.target restart (#1820)
f76f672 [fdbshow]: Fix typo in comment (#1809)
17208a0 [ci]: Support PR coverage (#1806)
c2c2354 fix wrong code indent in sfputil (#1808)
47a9a0f [portconfig] Validate duplicate speed value and interface type value (#1745)
f1086ee [sonic_installer]Add --skip-platform-check option for sonic_installer when image mismatch (#1791)
c007d65 [warm-reboot] Add new preboot health check: verify database integrity (#1785)
41e31e8 Fix PatchApplier init order (#1762)
2416175 [config reload] Fix config reload failure due to sonic.target job cancellation (#1814)
2b12aad [portstat, intfstat] added rates and utilization (#1750)
26e700a [debug dump util] Techsupport addition (#1669)
9f2326e [debug dump util] Base Skeleton and Click Class added (#1668)

#### Why I did it

Include PR https://github.com/Azure/sonic-utilities/pull/1745

#### How I did it

Update submodule for sonic-utilities

#### How to verify it

Run build

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by keboliu — DISMISSED** [review]

**Comment by judyjoseph** [comment]
@Junchao-Mellanox Can you update this PR with the latest commits on sonic-utilities, this t0 test failures should go away

**Comment by Junchao-Mellanox** [comment]
Hi @judyjoseph, all checks are passed, could you please review this agian?

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
