### PR TITLE
[BRCM SAI 6.0.0.13-3] Fix Warm-reboot issue

### PR DESCRIPTION
**Pull request by gechiang**
This is to fix BRCM SAI 6.0.0.13-3 warm-reboot issue on BRCM platforms.

Preliminary tests look fine. BGP neighbors were all up with proper routes programmed
interfaces are all up
Manually ran the following test cases on DX010(TH) T0 DUT and all passed:
```
     fib/test_fib.py
     vxlan/test_vxlan_decap.py
     fdb/test_fdb.py
     decap/test_decap.py
     acl/null_route/test_null_route_helper.py
     vlan/test_vlan.py
     manual test on wam-reboot and fast-reboot
```

This fixes (https://github.com/Azure/sonic-buildimage/issues/9898)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [x] 202106

#### Description for the changelog
[BRCM SAI 6.0.0.13-3] Fix Warm-reboot issue

### CODE REVIEW

**Review by vmittal-msft — APPROVED** [review]

**Review by richardyu-ms — APPROVED** [review]

**Comment by gechiang** [comment]
@xumia The build failure seems to be saying it is not able to find the libsaibcm debian for 6.0.0.13-3  Is there something wrong with the automatic sonic-storage upload?  Can you help take a look?
Thanks!

**Review by judyjoseph — APPROVED** [review]

**Review by xumia — APPROVED** [review]

**Comment by zhengbiqing** [comment]
where is the "BRCM SAI 6.0.0.13-3"？Thanks！

**Comment by gechiang** [comment]
@zhengbiqing All BRCM SAI debians are now automatically loaded to the sonic-storage.
Is there a need to know its url ?

**Comment by zhengbiqing** [comment]
This file "https://github.com/Azure/sonic-buildimage/blob/master/platform/broadcom/sai.mk" ?
The brcm sai is "https://sonicstorage.blob.core.windows.net/public/sai/bcmsai/REL_6.0/6.0.0.13-3/libsaibcm_6.0.0.13-3_amd64.deb" ?
This is a lib.  Where is the source code?

LIBSAIBCM_VERSION = 6.0.0.13-3
LIBSAIBCM_BRANCH_NAME = REL_6.0
LIBSAIBCM_URL_PREFIX = "https://sonicstorage.blob.core.windows.net/public/sai/bcmsai/$(LIBSAIBCM_BRANCH_NAME)/$(LIBSAIBCM_VERSION)"

BRCM_SAI = libsaibcm_$(LIBSAIBCM_VERSION)_amd64.deb
$(BRCM_SAI)_URL = "$(LIBSAIBCM_URL_PREFIX)/$(BRCM_SAI)"
BRCM_SAI_DEV = libsaibcm-dev_$(LIBSAIBCM_VERSION)_amd64.deb
$(eval $(call add_derived_package,$(BRCM_SAI),$(BRCM_SAI_DEV)))
$(BRCM_SAI_DEV)_URL = "$(LIBSAIBCM_URL_PREFIX)/$(BRCM_SAI_DEV)"

**Comment by gechiang** [comment]
@zhengbiqing My understanding is that BRCM SAI source code are not accessible by the community.  If you need access of their source code, please contact BRCM directly.

**Comment by zhengbiqing** [comment]
ok.  thanks!

**Comment by zhengbiqing** [comment]
It's strange only provide lib file but not source code?   so what about :  https://github.com/Broadcom-Switch/SAI  ?

**Comment by gechiang** [comment]
@zhengbiqing I would suggest that you open an issue with BRCM to see if they would share the SAI code for 6.0 or 6.1 for the Git Repo you mentioned.  It looks like BRCM choose to release for some branch but not all.  Maybe they have not caught up yet or have other constraints that I am not aware of and will not speculate here.  In short, we only release the BRCM SAI debians as part of the sonic-buildimage so that we can provide SONiC images for devices that are BRCM platform based to the SONiC community.
Thanks!

**Comment by zhengbiqing** [comment]
Thanks！

**Pull request merged**
