### PR TITLE
[BFN] Fix syncd-rpc build

### PR DESCRIPTION
**Pull request by msosyak**
#### Why I did it
To fix syncd-rpc build

#### How I did it
Fix build rules 

#### How to verify it
```
NOJESSIE=1 NOSTRETCH=1 make configure PLATFORM=barefoot
BLDENV=buster make -f Makefile.work target/docker-syncd-bfn-rpc.gz
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by msosyak** [comment]
@richardyu-ms Please help to review and merge

**Comment by msosyak** [comment]
@prgeor @qiluo-msft Please help to merge

**Comment by msosyak** [comment]
@prgeor @qiluo-msft Please, help merge

**Comment by akokhan** [comment]
@qiluo-msft , please approve and merge

**Review by richardyu-ms — APPROVED** [review]

**Review by akokhan — APPROVED** [review]

**Review by xumia — APPROVED** [review]

**Pull request merged**
