### PR TITLE
[build]: Fixed BFN target build

### PR DESCRIPTION
**Pull request by vsenchyshyn**
Signed-off-by: Vitaliy Senchyshyn <vsenchyshyn@barefootnetworks.com>

**- What I did**
Updated BFN packages in order to fix the BFN platform build

**- How I did it**
Updated the links to the packages which work with the latest SONiC 

**- How to verify it**
Built the SONiC with the packages uploaded and ran the CT regression

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vsenchyshyn** [comment]
@jleveque @lguohan Please have a look.

**Comment by akokhan** [comment]
This PR updates BFN SAI plugin to v1.5

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
retest vsimage please

**Pull request merged**
