### PR TITLE
[barefoot][platform] Support fans and thermal

### PR DESCRIPTION
**Pull request by vboykox**
Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>

#### Why I did it
To support fan_drawer and thermal
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

#### Description for the changelog

[barefoot] Add support for fans and thermals to sonic_platform package

### CODE REVIEW

**Comment by vboykox** [comment]
@akokhan

**Comment by vboykox** [comment]
@jleveque

**Comment by jleveque** [comment]
@vboykox: Please add details to the PR description which will be added to the changelog

**Review by akokhan — APPROVED** [review]

**Comment by vboykox** [comment]
> @vboykox: Please add details to the PR description which will be added to the changelog

Done

**Review by jleveque — APPROVED** [review]

**Pull request merged**
