### PR TITLE
[Mellanox] Upgrade hw-mgmt to 7.0100.2303

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Depends on https://github.com/Azure/sonic-linux-kernel/pull/211

#### Why I did it

Upgrade hw-mgmt to 7.0100.2303

 Bug fixes
 - Fan direction feature fix for fixed FAN system (using shell instead of binutils/strings)
 - Remove cpld 4th link on systems with only 3 CPLD's
 - hw-mgmt: thermal: Add hardcoded critical trip point. Follow-up after patch "Removing critical thermal zones to prevent unexpected software system shutdown".
 - Fix sensor attribute mapping to be label based instead of index based to allow common handling of voltage regulator names independently of hardware changes.
 - Update 'lm-sensors' custom configuration file. Relevant only for users utilizing sensors.conf files coming along with hw-management package.

For full feature list please follow https://github.com/Mellanox/hw-mgmt/blob/V.7.0010.2300_BR/debian/Release.txt

#### How I did it

1. Update hw-mgmt pointer
2. Remove unused patches
3. Fix existing patch to make sure it apply successfully

#### How to verify it

Regression on mellanox platform all passed

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
Related to https://github.com/Azure/sonic-linux-kernel/pull/211

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox  should we go on and merge it or you need to update the linux kernel submodule following PR Azure/sonic-linux-kernel#211 merge?

**Comment by Junchao-Mellanox** [comment]
I will update linux kernel submodule pointer first.

**Comment by Junchao-Mellanox** [comment]
Submodule update PR for sonic-linux-kernel: https://github.com/Azure/sonic-buildimage/pull/7454

**Pull request merged**
