### PR TITLE
DellEMC: Change PG values for S5232f,Z9264f

### PR DESCRIPTION
**Pull request by aravindmani-1**
#### Why I did it
Modified PG values for Dell S5232f and Z9264f platform.
 
#### How I did it
Edited pg_lookup_profile.ini file to modify the vaues
#### How to verify it
Check "show mmu" CLI, buffer profile related commands.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [x] 201911
- [x] 202006
- [x] 202012

#### Description for the changelog
UT:
[s5232f_Z9264f_pg_UT.txt](https://github.com/Azure/sonic-buildimage/files/6168982/s5232f_Z9264f_pg_UT.txt)

### CODE REVIEW

**Review by AshokDaparthi — APPROVED** [review]

**Comment by aravindmani-1** [comment]
@vmittal-msft can you please help to merge this PR?.

**Review by vmittal-msft — APPROVED** [review]

**Pull request merged**
