### PR TITLE
Auto-completion, help (?), cmd navigation (up arrow) not working in vtysh on host system.

### PR DESCRIPTION
**Pull request by nikos-li**
Auto-completion, help (?), cmd navigation (up/down arrows) not working in vtysh on host system.
This fix complements https://github.com/Azure/sonic-quagga/pull/19/

### CODE REVIEW

**Comment by lguohan** [comment]
why are there so many commits in your PR? are you synced with the master to generate the PR?

**Comment by nikos-li** [comment]
This is the commit and sync history of my private branch. I don't think it affect Azure/sonic-buildimage.

**Comment by lguohan** [comment]
it causes issue in the merge messages, the commit message will by default includes all previous commit messages, we have to manually edited it.

**Comment by nikos-li** [comment]
I'm just following regular github process. If you have a suggestion that omits that without squashing the history of my private branch or deleting it, let me know.

**Comment by lguohan** [comment]
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

We recommend that you make changes in a topic branch, so that you can push followup commits if you receive feedback on your pull request. 

first, you make yout topic branch exactly the same as the master branch, then cherry-pick your commits and finally generate PR.

**Comment by nikos-li** [comment]
My topic branch/fork is long lived. I sync to the latest master each time, commit to it and I generate the PR as the above link suggests. That's how it picks up the delta of the diffs and the comparison is across the fork and the master.

**Comment by lguohan** [comment]
as time goes, you will have more and more commits in your PR. We cannot really know which commits is the one you want to merge.

**Comment by nikos-li** [comment]
Of course you do - you have the diffs of what I want to be merged. The PR generates always the delta. And on my side I want the pull requests directly on my forks not on topic branches. This is a valid way to work on github.

**Comment by lguohan** [comment]
https://gist.github.com/Chaser324/ce0505fbed06b947d962

I think we can discuss the workflow offline.

back to the PR, I tried this, vtysh will give me (END), I need to manually type 'q' to make the (END) go away. Am I missing anything here?

**Comment by nikos-li** [comment]
Cmds work fine for me. What exactly are you trying out?

**Comment by lguohan** [comment]
this problem: http://www.brianlinkletter.com/quagga-vtysh-shell-end-problem/

**Comment by nikos-li** [comment]
In files/image_config/environment/environment the vtysh pager is set to more. Sounds like the quagga docker needs more fixing in addition to this one. On our side with frr, the pager is set properly to more and all commands work fine including the sonic show cli as well as everything inside vtysh.

**Comment by lguohan** [comment]
I think in this case, the vtysh is looking for the env inside the docker. If frr is working for you, then, can you limit this PR to only FRR? With -t, the vtysh is not working for us.

**Comment by nikos-li** [comment]
Let me take a stab at it and make this working for quagga as well. You really do want the 't' option because other more important things don't work. If I can't make it work, then I'll exclude the quagga change.

**Comment by nikos-li** [comment]
BTW when you go into the bgp docker, you simply do 'docker exec -i bgp bash' without the 't' option?

**Comment by rodnymolina** [comment]
Quagga's issue can be easily fixed by editing host's vtysh:

docker exec -it bgp bash -c "export VTYSH_PAGER=more; vtysh \"$@\""

FRR deals with this issue by explicitly adding VTYSH_PAGER as env-var in /etc/environment:

<-- frr/debian/frr.postinst

ENVIRONMENTFILE=/etc/environment
if ! grep --quiet VTYSH_PAGER=/bin/cat ${ENVIRONMENTFILE}; then
    echo "VTYSH_PAGER=/bin/cat"  >> ${ENVIRONMENTFILE}
fi

**Comment by rodnymolina** [comment]
Above fix needs more work as it breaks click cli.

**Comment by nikos-li** [comment]
Which click cli is it breaking for you?

**Comment by rodnymolina** [comment]
Any "show" command (e.g. show bgp sum). Btw, i'm referring to my Quagga fix, not FRR one (yours).

**Comment by nikos-li** [comment]
I will test in quagga and see and fix accordingly if possible.

**Comment by nikos-li** [comment]
@lguohan Ok I fixed this in quagga by pointing the docker's pager to cat instead of less. I tested it extensively and it works. Are you ok with that change? Want me to post the diffs?

**Comment by nikos-li** [comment]
The changes below will complete the fix for quagga/vtysh:

diff --git a/debian/quagga.postinst b/debian/quagga.postinst
index bed2fd3..20c6d76 100644
--- a/debian/quagga.postinst
+++ b/debian/quagga.postinst
@@ -1,5 +1,8 @@
 #!/bin/bash -e
 
+rm /etc/alternatives/pager
+ln -s /bin/cat /etc/alternatives/pager
+
 if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
 ${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*"}
 
Are you ok with those changes?

**Comment by nikos-li** [comment]
I have submitted the PR for quagga as well. Please approve.

**Comment by lguohan** [comment]
can you update the sonic-quagga submodule head in this PR?

**Pull request merged**
