### PR TITLE
[mellanox] Update SDK/FW pointers

### PR DESCRIPTION
**Pull request by stepanblyschak**
Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
is this sai 1.3.3?

**Comment by liatgrozovik** [comment]
@lguohan IMO this is not sai 1.33. it was before it was request. 
Is SAI 1.33 was already approved and is updated? if so we will make this one aligned with SAI 1.33 as well

**Comment by liatgrozovik** [comment]
But since SAI 1.33 was not yet integrated can we merge this one and then have another update for SAI 1.3.3?

**Comment by lguohan** [comment]
sai 1.3.3 is already integrated.

**Pull request closed without merging**
