### PR TITLE
Fix pip3 hook ENABLE_VERSION_CONTROL_PY param

### PR DESCRIPTION
**Pull request by baxia-lan**
#### Why I did it
Fix command line 
`PIP_VERSION_FILE=$VERSION_FILE ENABLE_VERSION_CONTROL_PY=$ENABLE_VERSION_CONTROL_PY2 REAL_COMMAND=$REAL_COMMAND run_pip_command "$@"`
to 
`PIP_VERSION_FILE=$VERSION_FILE ENABLE_VERSION_CONTROL_PY=$ENABLE_VERSION_CONTROL_PY3 REAL_COMMAND=$REAL_COMMAND run_pip_command "$@"`

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

**Comment by lguohan** [comment]
@xumia , can you check?

**Review by xumia — APPROVED** [review]

**Comment by xumia** [comment]
Thanks for fixing it.
@lguohan , it would be an issue when only py2 or py3 enabled. It has no impact on release 202012, since both of py2 and py3 are enabled with version control.

**Comment by xumia** [comment]
Not urgent, but suggest to merge 202012.

**Pull request merged**
