### PR TITLE
caclmgrd: support packet mark in DHCP chain

### PR DESCRIPTION
**Pull request by trzhang-msft**
#### Why I did it
caclmgrd: support packet mark in DHCP chain

#### How I did it
enhance caclmgrd

#### How to verify it
vs testbed

#### Which release branch to backport (provide reason below if selected)
- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [ ] 202106

#### Description for the changelog
1) use packet mark if corresponding interfaces have marks in state_db
2) use interface name if corresponding interfaces don't have marks in state-db
3) add unitests

### CODE REVIEW

**Review by prsunny — COMMENTED** [review]
Overall, changes looks good to me. However ,does this assume caclmgrd is always started after mux container? what if caclmgrd starts first? Also, what if mux container is restarted?

**Comment by trzhang-msft** [comment]
> Overall, changes looks good to me. However ,does this assume caclmgrd is always started after mux container? what if caclmgrd starts first? Also, what if mux container is restarted?

- Is there an order currently?
- At least caclmgrd assumes that config_db is present when caclmgrd starts. How is this guaranteed?
- If no order between mux container and caclmgrd can be guaranteed, we cannot put "mark_dhcp_packet" in mux container. Instead, we have to merge it into caclmgrd together. Thoughts?

**Comment by prsunny** [comment]
> > Overall, changes looks good to me. However ,does this assume caclmgrd is always started after mux container? what if caclmgrd starts first? Also, what if mux container is restarted?
> 
> * Is there an order currently?
> * At least caclmgrd assumes that config_db is present when caclmgrd starts. How is this guaranteed?
> * If no order between mux container and caclmgrd can be guaranteed, we cannot put "mark_dhcp_packet" in mux container. Instead, we have to merge it into caclmgrd together. Thoughts?

I dont think there is an order currently. So the PR has to assume there is no order. 
Config_db shall be present when caclmgrd starts. That is guaranteed. 
No, Instead I think we need to get notified for statedb changes

**Comment by trzhang-msft** [comment]
> > > Overall, changes looks good to me. However ,does this assume caclmgrd is always started after mux container? what if caclmgrd starts first? Also, what if mux container is restarted?
> > 
> > 
> > 
> > * Is there an order currently?
> > * At least caclmgrd assumes that config_db is present when caclmgrd starts. How is this guaranteed?
> > * If no order between mux container and caclmgrd can be guaranteed, we cannot put "mark_dhcp_packet" in mux container. Instead, we have to merge it into caclmgrd together. Thoughts?
> 
> I dont think there is an order currently. So the PR has to assume there is no order. Config_db shall be present when caclmgrd starts. That is guaranteed. No, Instead I think we need to get notified for statedb changes

make sense, updated

**Review by prsunny — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by trzhang-msft** [comment]
> This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

https://github.com/Azure/sonic-buildimage/pull/9191 This is already picked and merged.

**Pull request merged**
