### PR TITLE
DellEMC: get_change_event Platform API implementation for S6000, S6100 and Z9100

### PR DESCRIPTION
**Pull request by ArunSaravananBalachandran**
**- Why I did it**

For detecting transceiver change events through xcvrd in DellEMC S6000, S6100 and Z9100 platforms.

**- How I did it**

- In S6000, rename 'get_transceiver_change_event' in chassis.py to 'get_change_event' and return appropriate values.
- In S6100, implement 'get_change_event' through polling method (poll interval = 1 second) in chassis.py (Transceiver insertion/removal does not generate interrupts due to a CPLD bug)
- In Z9100, implement 'get_change_event' through interrupt method using select.epoll().

**- How to verify it**

Perform transceiver insertion/removal and check the transceiver presence using "show interfaces transceiver command". During transceiver insertion/removal testing, no substantial CPU spike was observed when pfcwd was enabled.

UT Logs:
[S6000_OIR_UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/4626788/S6000_OIR_UT_logs.txt)
[S6100_OIR_UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/4626792/S6100_OIR_UT_logs.txt)
[Z9100_OIR_UT_logs.txt](https://github.com/Azure/sonic-buildimage/files/4626793/Z9100_OIR_UT_logs.txt)

 

**- Description for the changelog**

DellEMC: get_change_event Platform API implementation for S6000, S6100 and Z9100

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by ArunSaravananBalachandran** [comment]
This PR needs to be picked for 201911 branch.

**Comment by sujinmkang** [comment]
@ArunSaravananBalachandran Can you please fix the LGTM alerts?

**Comment by ArunSaravananBalachandran** [comment]
> @ArunSaravananBalachandran Can you please fix the LGTM alerts?

@sujinmkang Resolved the LGTM alerts.

**Comment by sujinmkang** [comment]
Retest mellanox please!

**Comment by jleveque** [comment]
Retest mellanox please

**Pull request merged**
