### PR TITLE
[MultiDB] (./dockers dir) : replace redis-cli with sonic-db-cli and use new DBConnector

### PR DESCRIPTION
**Pull request by dzhangalibaba**
this commit made changes in sonic-buildimage/dockers/ directory:

* replace redis-cli with sonic-db-cli
* replace old DBConnector with new DBConnector 
* vs tests passed, loaded on DUT, looks good, script works fine.

Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

### CODE REVIEW

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
@qiluo-msft FYI

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
> retest vsimage please
retesr this [\slaes

**Comment by dzhangalibaba** [comment]
retest vsimage

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Comment by lguohan** [comment]
test failure. @dzhangalibaba , looks like the bgp_fact test failed, and it seems the bgpd.conf does not have all the neighbor information. Can you check?

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
> test failure. @dzhangalibaba , looks like the bgp_fact test failed, and it seems the bgpd.conf does not have all the neighbor information. Can you check?

Hi @lguohan   , looks without my changes in other PRs, it failed at the same place, looks it is not my changes caused this failure. It is something else in basic test.

e.g.  
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/1964/consoleFull

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/1962/consoleFull

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/1960/consoleFull

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/1959/consoleFull

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/1957/consoleFull

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/1956/consoleFull

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/1955/consoleFull

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-pr/1954/

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
retest vs please

**Comment by dzhangalibaba** [comment]
retest vsimage please

**Comment by dzhangalibaba** [comment]
@qiluo-msft We can start review on this PR now

**Pull request merged**
