### PR TITLE
[Mellanox] Change port index in port_config.ini to 1-based

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**- Why I did it**

Change port index of port_config.ini from 0-based to 1-based.

**- How I did it**

1. Change all SKU port_config.ini file, set index from 0-based to 1-based
2. Change chassis.get_sfp function to accept a 1-based index as its argument

**- How to verify it**

Manual test show interfaces and sfp related command, compare the command output with old one and make sure they are equal.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by prsunny** [comment]
Is this required for cherry-pick to 201911?

**Comment by Junchao-Mellanox** [comment]
> Is this required for cherry-pick to 201911?

I suppose not. 
@liat-grozovik could you advice?

**Pull request merged**
