### PR TITLE
Update PG profiles for Arista 7050

### PR DESCRIPTION
**Pull request by baiwei0427**
Signed-off-by: Wei Bai webai@microsoft.com

**- Why I did it**
Current PG headroom values are wrong

**- How I did it**
Recalculate PG headroom with the following assumptions:
* Link partner device: TD2
* Packet in the Way - Size: 9216 bytes
* Packet size distribution: 50% 64-byte packets and 50% 1082-byte packets. 

And PG min = 1248 bytes. Size = PG min + PG headroom 
 
**- How to verify it**

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [x] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by baiwei0427** [comment]
retest this please

**Comment by neethajohn** [comment]
provided comments offline

**Review by neethajohn — APPROVED** [review]

**Review by smaheshm — APPROVED** [review]

**Comment by abdosi** [comment]
@neethajohn Does it have impact of test case on pfc wd for 7050 ?

**Comment by abdosi** [comment]
@neethajohn Do we need this for 201911 ? If yes i would prefer test case update and then verify before taking it for 201911.

**Comment by neethajohn** [comment]
More changes coming in upcoming PR for PG profile parameters. Will take that final version into 201911

**Pull request merged**
