### PR TITLE
[Mellanox] Update SAI to v.1.17.6

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

**- Why I did it**
* Updated SAI to v.1.17.6

**- How I did it**
* N/A

**- How to verify it**
1. make configure PLATFORM=mellanox
2. make target/sonic-mellanox.bin

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

Enhancements and new features:
- L3 VXLAN new VRF pipeline
- FB vLAN allocation optimization
- Enhanced SAI debug dump with FW dumps
- Implement create method for several switch attributes
- Fine grain ECMP support
- SN4410 system support
- Add bridge disable learn attribute
- Unified log messages format
- Improve various logging messages

Bugs fix:
- Remove route with empty next hop group

**- A picture of a cute animal (not mandatory but encouraged)**
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by nazariig** [comment]
retest vsimage please

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
retest vs please

**Comment by keboliu** [comment]
retest vs please

**Comment by liat-grozovik** [comment]
vs failure is irrelevant for new SAi version update. same headers, new fixes from Mellanox implementation. thus approved for merge.

**Comment by qiluo-msft** [comment]
retest vs please

**Comment by liat-grozovik** [comment]
retest vs please

**Pull request merged**
