### PR TITLE
[submodule][sonic-platform-daemons] Update submodule

### PR DESCRIPTION
**Pull request by vboykox**
[xcvrd] Fix bailing out on platforms that do not support QSFP-DD (#78)
Fix psud and test_thermalctld (#75)
[Thermal] Fix for 'show platform fan' command (#71)

Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>

**- Why I did it**
To integrate fixes done in #78 and #75 pull requests
**- How I did it**

**- How to verify it**

**- Which release branch to backport (provide reason below if seleted)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vboykox** [comment]
@akokhan

**Comment by vboykox** [comment]
please rebuild mellanox

**Comment by vboykox** [comment]
please retest mellanox

**Comment by jleveque** [comment]
Retest mellanox please

**Comment by jleveque** [comment]
Retest mellanox please

**Pull request merged**
