### PR TITLE
[Mellanox] PSU led platform API fixes

### PR DESCRIPTION
**Pull request by shlomibitton**
Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

**- Why I did it**
Fix return False if unsupported color request.

**- How I did it**
Return 'False' when unsupported led color is requested, preventing an exception.

**- How to verify it**
Try to set PSU LED color to unsupported color with Mellanox platform device.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by shlomibitton** [comment]
retest broadcom mellanox vsimage please

**Comment by shlomibitton** [comment]
retest broadcom please

**Comment by shlomibitton** [comment]
retest mellanox please

**Comment by shlomibitton** [comment]
retest vsimage please

**Comment by shlomibitton** [comment]
retest broadcom please

**Comment by shlomibitton** [comment]
retest vsimage please

**Comment by shlomibitton** [comment]
retest vsimage please

**Comment by shlomibitton** [comment]
retest mellanox please

**Comment by shlomibitton** [comment]
retest vsimage please

**Review by jleveque — APPROVED** [review]

**Pull request merged**
