### PR TITLE
[arista] Update drivers submodule

### PR DESCRIPTION
**Pull request by Staphylo**
- Refactor of the cli
 - Refactor of the logging mechanism
 - Add some more utilities
 - Miscelaneous fixes and improvements

### CODE REVIEW

**Comment by Staphylo** [comment]
retest vs please

**Comment by Staphylo** [comment]
retest vsimage test

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by Staphylo** [comment]
retest vsimage please

**Pull request merged**
