### PR TITLE
[Mellanox] Update hw-mgmt package to V.7.0010.1000 for master

### PR DESCRIPTION
**Pull request by keboliu**
**has dependency on https://github.com/Azure/sonic-linux-kernel/pull/142, needs to update the submodule pointer after it merged.**

**- Why I did it**
Pick up Mellanox hw-mgmt package new version  V.7.0010.1000

**- How I did it**
update the hw-mgmt submodule, 
update the related make file
update the sonic-linux-kernel pointer for new patches. 

**- How to verify it**
run platform related test on Mellanox platform

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by keboliu** [comment]
retest vsimage plese

**Comment by keboliu** [comment]
Retest vsimage please

**Comment by keboliu** [comment]
Retest vsimage please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by keboliu** [comment]
Retest vsimage please

**Comment by keboliu** [comment]
Retest vsimage please

**Comment by keboliu** [comment]
Retest vsimage please

**Comment by keboliu** [comment]
Retest vsimage please

**Pull request merged**
