### PR TITLE
New platform as6712-32x

### PR DESCRIPTION
**Pull request by roylee123**
Switch Vendor: Edge-core
Switch SKU: AS6712-32X
ASIC Vendor: Broadcom
Swich ASIC: Trident2
Port Configuration: 32x40G
SONiC Image: SONiC-ONIE-Broadcom
Signed-off-by: Roy Lee roy_lee@edge-core.com

**- What I did**
Add device and platform files for new mode as6712-32x.

**- How I did it**
Add as SONiC Porting Guide.

**- How to verify it**
Target-verified the port link of 32x4G as expected.
Target-verified the LED macro on port status changing.
config.bcm is sent to 'sonicdev@microsoft.com'.
decode-syseeprom
sensors
psuutil 
sfputil
thermal monitor

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
@roylee123 , as we discussed in the community meeting, please add new platforms to stretch branch.

**Comment by roylee123** [comment]
Where can I get the minutes of that community meeting? Can I check-in this code to branch 201803 ?

**Comment by roylee123** [comment]
Close this PR, which is for deb 8.
Move changes to another PR, [platform]Accton, add platform as6712-32x. #2178.

**Comment by roylee123** [comment]
Close this PR, which is for deb 8.
Move changes to another PR, [platform]Accton, add platform as6712-32x. #2178.

**Comment by roylee123** [comment]
Close this PR, which is for deb 8.
Move changes to another PR, [platform]Accton, add platform as6712-32x. #2178.

**Pull request closed without merging**
