### PR TITLE
[sonic-snmpagent][sonic-py-swsssdk] Advance submodules

### PR DESCRIPTION
**Pull request by SuvarnaMeenakshi**
Signed-off-by: SuvarnaMeenakshi <sumeenak@microsoft.com>

**- Why I did it**
Update sonic-snmpagent submodule with PRs:
89b7b2c  [Multi-asic]: Namespace support for LLDP and Sensor tables (#131)
fcb8955 Simplify test code (#132)
a677876 [Multi-asic]: Support multi-asic platform (#126)

update sonic-py-swsssdk submodule with PRs:
132f8d5  [MultiDB]: use python class composition to avoid confusion in base class (#74)

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Retest mellanox please

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by qiluo-msft** [comment]
Retest mellanox please

**Comment by abdosi** [comment]
Done Manually

**Pull request merged**
