### PR TITLE
[Inventec][D6356] Update Inventec 6356

### PR DESCRIPTION
**Pull request by david-xk**
**- What I did**
* [Platform API] Add get_change_event implementation for Chassis class
* [Platforn monitor] skip ledd to avoid pmon init failure

**- How I did it**
* Add pmon_daemon_control.json to device/inventec/x86_64-inventec_d6356-r0/
* Add transceiver_event.py to platform/broadcom/sonic-platform-modules-inventec/d6356/sonic_platform
* Modify chassis.py to platform/broadcom/sonic-platform-modules-inventec/d6356/sonic_platform

**- How to verify it**
* check platform eeprom: show platform syseeprom
* check platform PSUs:  show platform psustatus
* check interface status: show interfaces status
* check transceiver presence: show interfaces transceiver presence

**- Description for the changelog**

* 20191102
  * [Platform API] Add get_change_event implementation for Chassis class
  * [Platforn monitor] skip ledd to avoid pmon init failure

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by david-xk** [comment]
Retest vsimage please

**Comment by david-xk** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by david-xk** [comment]
Hi @jleveque, Looks like past the vsiamge test, would you please merge this PR at your convenience?
Thanks,
David

**Pull request merged**
