### PR TITLE
[sonic-swss] Advance submodule

### PR DESCRIPTION
**Pull request by stephenxs**
swss:
bb0733aa [aclorch] Add ACL_TABLE_TYPE configuration  (Azure/sonic-swss#1982)
59cab5d9 Support for setting switch level DSCP to TC QoS map (Azure/sonic-swss#2023)
da21172e [aclorch] add generic AclOrch::updateAclRule() method (Azure/sonic-swss#1993)
4f6cb055 [Reclaiming buffer] Support reclaiming buffer in traditional model (Azure/sonic-swss#2011)
32d7a69e [Reclaiming buffer] Common code update (Azure/sonic-swss#1996)
b91d8ba7 [swss] L2 Forwarding Enhancements (Azure/sonic-swss#1716)
797dab41 [muxorch] Bind all ports to drop ACL table (Azure/sonic-swss#2027)
99929cd7 [lgtm.yml] add libgmock-dev (Azure/sonic-swss#2035)
8727ae5c [flex counter] Flex counter threads consume too much CPU resources #9202 (Azure/sonic-swss#2031)
103fdf05 Remove redundant calls to get child scheduler group during initialization (Azure/sonic-swss#1965)
18ea8404 [macsec]: MACsec statistics support (Azure/sonic-swss#1867)
0c462420 [orchagent] Flush pipeline every 1 second, not only when select will timeout (Azure/sonic-swss#2003)
339101cf [cbf] Add class-based forwarding support (Azure/sonic-swss#1963)
24a615bd Fix issue: accumulative headroom can exceed limit in rare scenario (Azure/sonic-swss#2020)
708e232a Test divide by zero processing path (Azure/sonic-swss#2028)
8f1d035c [macsecmgr]: Wait for port up before enabling macsec (Azure/sonic-swss#2032)
4912a770 Remove buffer drop counter when port is removed (Azure/sonic-swss#1860)
f9462c49 [Dynamic buffer] [Mellanox] Calculate the peer response time according to the speed (Azure/sonic-swss#1930)
8b5a401e Routed subinterface enhancements (Azure/sonic-swss#2017)
cdea5e9b Fix next hop compilation (Azure/sonic-swss#2025)
37c197d0 [SRV6] Sonic-swss changes for SRV6 (Azure/sonic-swss#1964)
f502c320 [vnetorch] Add ECMP support for vnet tunnel routes (Azure/sonic-swss#1960)

Signed-off-by: Stephen Sun <stephens@nvidia.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by stephenxs** [comment]
Broadcom and vs failed due to the following error 
2021-11-19T03:21:02.2184132Z Expected equality of these values:
2021-11-19T03:21:02.2184668Z   std::get<0>(mTestCompositeState)
2021-11-19T03:21:02.2185121Z     Which is: 2
2021-11-19T03:21:02.2185639Z   link_prober::LinkProberState::Label::Wait
2021-11-19T03:21:02.2186141Z     Which is: 3
2021-11-19T03:21:02.2186717Z [  FAILED  ] LinkManagerStateMachineTest.MuxActiveLinkProberUnkno

**Comment by stephenxs** [comment]
2 issues:
1. Kvmtest-t0 didn’t finish after 5 hours. Need to enlarge the timeout
2. LGTM got stuck even if I push new commits

**Comment by stephenxs** [comment]
> Kvmtest-t0 didn’t finish after 5 hours. Enlarged it to 6 hours as a dry run. I will open another PR if it passes the tests.

Kvmtest-t0 passed with timeout extended to 6 hours. It took 5h14m59s.

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Could you try rebase to latest master? Not sure if it helps lgtm checker.

**Comment by stephenxs** [comment]
> Could you try rebase to latest master? Not sure if it helps lgtm checker.

Thanks. Per my understanding the LGTM failure is caused by sonic-platform-common’s commit hash pointed by sonic build image not existing in its repo. I merged the master back but did not see a fix.

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
