### PR TITLE
[202012] [sonic-linux-kernel] Re-land kernel config changes for Cisco 8000.

### PR DESCRIPTION
**Pull request by saiarcot895**
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

#### Description for the changelog

Bring in the kernel config changes needed for Cisco 8000 support.

This brings in the following commit:

* 15e6f4b0a: Kernel config changes to support cisco platforms [madhava28]

### CODE REVIEW

**Comment by yxieca** [comment]
Please list the kernel submodule commits include by this submodule change

**Comment by saiarcot895** [comment]
Updated the PR description.

**Review by yxieca — APPROVED** [review]

**Comment by wally-wang-accton** [comment]
@yxieca & @saiarcot895, this PR caused Accton platforms bootup abnormal (no console output).  It's caused by this configuration, CONFIG_SERIAL_8250_RUNTIME_UARTS=32.  We already submit one issue, https://github.com/Azure/sonic-buildimage/issues/11238.  Please review and process it.

**Comment by lguohan** [comment]
why this must be kernel configuration parameter? why cannot we set it as booting parameter as suggested below?

@kevinwangsk 

Set this to the maximum number of serial ports you want the kernel to register at boot time. This can be overridden with the module parameter "nr_uarts", or boot-time parameter 8250.nr_uarts

https://cateee.net/lkddb/web-lkddb/SERIAL_8250_RUNTIME_UARTS.html

**Comment by lguohan** [comment]
@kevinwangsk , can you sync with cisco?

**Pull request merged**
