### PR TITLE
PG headroom change for th2

### PR DESCRIPTION
**Pull request by wendani**
Verified with https://github.com/Azure/sonic-mgmt/pull/1156

Signed-off-by: Wenda Ni <wenni@microsoft.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by lguohan** [comment]
can you change 40m as well?

**Comment by abdosi** [comment]
@wendani do you remember what was the context of this change ? Why we increased headroom here ?

**Comment by wendani** [comment]
> @wendani do you remember what was the context of this change ? Why we increased headroom here ?

I do not remember. Most likely come from rdma team recommendation/requirement. @baiwei0427

**Comment by baiwei0427** [comment]
> > @wendani do you remember what was the context of this change ? Why we increased headroom here ?
> 
> I do not remember. Most likely come from rdma team recommendation/requirement. @baiwei0427

@wendani I did some calculations and found these numbers were too large.

**Pull request merged**
