### PR TITLE
[yang-models]: Default value for leaf-lists and tests.

### PR DESCRIPTION
**Pull request by praveen-li**
**- What I did**
[yang-models]: Default value for leaf-lists and tests.

    Changes:
    -- Add Default value for leaf-lists in ACL and portchannel.
    -- Remove members in VLAN.
    -- Test modifications.

**- How I did it**
Used default statement of YANG RFC 7950.

**- How to verify it**

Build Time Tests

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by praveen-li** [comment]
retest vsimage please

**Comment by praveen-li** [comment]
retest vsimage please

**Comment by praveen-li** [comment]
retest baseimage please

**Comment by praveen-li** [comment]
retest vsimage please

**Comment by vasant17** [comment]
Can we merge this?

**Comment by lguohan** [comment]
@vasant17 , can you sign-off?

**Review by lguohan — APPROVED** [review]

**Pull request merged**
