### PR TITLE
[platform] Add serial number and model number to Mellanox PSU platform implementation

### PR DESCRIPTION
**Pull request by robocoder99**
#### Why I did it

We want to add the ability for the command `show platform psustatus` to show the serial number and part number of the PSU devices on Mellanox platforms. This will be useful for data-center management of field replaceable units (FRUs) on switches.

#### How I did it

I implemented the platform 2.0 functions `get_model()` and `get_serial()` for the PSU in the mellanox platform API by referencing the sysfs nodes provided by the [hw-management](https://github.com/Azure/sonic-buildimage/tree/master/platform/mellanox/hw-management) module.

#### How to verify it

I ran `show platform psustatus` and verified that the serial number and model number were present on platforms where the information was accessible through sysfs. (Currently functioning on all mellanox platforms other than MSN2100 and MSN2010)

#### Which release branch to backport (provide reason below if selected)

None

#### Description for the changelog

[platform] Add serial number and model number to Mellanox PSU platform implementation

#### A picture of a cute animal (not mandatory but encouraged)

97f64614927328325cf385c8be8aa80b

### CODE REVIEW

**Comment by jleveque** [comment]
Please fix LGTM alert

**Comment by robocoder99** [comment]
Already fixed, you may see that in the latest run details from LGTM. (My lastest commit on this branch addresses the changes)

**Comment by jleveque** [comment]
> Already fixed, you may see that in the latest run details from LGTM. (My lastest commit on this branch addresses the changes)

Thanks! Sorry, I missed that :)

**Review by jleveque — DISMISSED** [review]

**Review by jleveque — APPROVED** [review]

**Pull request merged**
