### PR TITLE
[dockers][platform-monitor] Add chassis_db_init to platform monitor tasks

### PR DESCRIPTION
**Pull request by robocoder99**
#### Why I did it
I added `chassis_db_init` to the startup tasks for the `docker-platform-monitor` docker so that the script is run on startup of the switch and the chassis info is correctly provisioned to STATE_DB.

**NOTE: THIS DEPENDS ON https://github.com/Azure/sonic-platform-daemons/pull/183 DO NOT MERGE**

#### How I did it
I modified the supervisord template in order to define the new task to be started. 

#### How to verify it

Run `sudo redis-cli -n 6 hgetall "CHASSIS_INFO|chassis 1"`

Expected output (exact values will differ per platform)

```
1) "serial"
2) "MT1822K07815"
3) "model"
4) "MSN2700-CS2FO"
5) "revision"
6) "A1"
7) "psu_num"
8) "2"
```

#### Description for the changelog
[dockers][platform-monitor] Add chassis_db_init to platform monitor tasks

#### A picture of a cute animal (not mandatory but encouraged)
babycow

### CODE REVIEW

**Comment by jleveque** [comment]
PR title mentions `chassisshow`, but PR description and content doesn't reflect this. Please update title and/or description as appropriate.

**Comment by robocoder99** [comment]
Whoops, copied from the internal system prior to the name change, thanks. Up to date now.

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@robocoder99 as the dependent PR is merged, please check submodule is updated and then we can move forward with the merge process.

**Comment by robocoder99** [comment]
Submodule bump PR is here https://github.com/Azure/sonic-buildimage/pull/7709 may proceed once this merge completes. Please let me know if anything else is needed.

**Review by jleveque — APPROVED** [review]

**Pull request merged**
