### PR TITLE
[DellEMC] Platform2.0 API Implementation for Watchdog [Z9264F]

### PR DESCRIPTION
**Pull request by santhosh-kt**
**- What I did**

- [DellEMC] Platform2.0 API Implementation for Watchdog [Z9264F]

**- How I did it**

- Added new file watchdog.py in sonic_platform directory.
- Enabled API support to Enable/disable watchdog.

**- How to verify it**
- Attached Unit test case results.
[Unit test - Watchdog - z9264.txt](https://github.com/Azure/sonic-buildimage/files/4243735/Unit.test.-.Watchdog.-.z9264.txt)

**- Description for the changelog**

On branch z9264f-watchdog
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/chassis.py
        new file:   platform/broadcom/sonic-platform-modules-dell/z9264f/sonic_platform/watchdog.py

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by sujinmkang** [comment]
retest vsimage please

**Comment by santhosh-kt** [comment]
retest vsimage please

**Comment by jleveque** [comment]
@santhosh-kt: Please fix conflicts.

**Comment by jleveque** [comment]
@santhosh-kt: Please fix recent conflicts.

**Comment by santhosh-kt** [comment]
2.0 Fan.py PR #4191  also keeps on getting merge conflict on chassis.py. After the PR merged, I will resolve these conflicts to avoid reviews getting dismissed multiple times.

**Comment by santhosh-kt** [comment]
retest default please

**Comment by santhosh-kt** [comment]
retest this please

**Pull request merged**
