### PR TITLE
Fix Accton as7326 port breakout

### PR DESCRIPTION
**Pull request by stevenlu99**
**- What I did**
Added dport mappings for possible-breakout ports

**- How I did it**
Modified config.bcm file

**- How to verify it**
breakout ports and verify links up

**- Description for the changelog**

Add Dport mapping for possible breakout sub-ports make sure breakout ports link up on AS7326

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by pollyhsu2git** [comment]
@stevenlu99
May we know how you verified the breakout ports and verified them linked up?

**Comment by stevenlu99** [comment]
@pollyhsu2git, need modify port_config.ini, config.bcm and config_db.json file to breakout a port and then reboot to verify link to link partner also breakout same way.

**Comment by lguohan** [comment]
retest vs please

**Comment by lguohan** [comment]
the pr looks good to me, @pollyhsu2git, any other concerns?

**Comment by jleveque** [comment]
Retest vs please

**Comment by jleveque** [comment]
Retest vs please

**Pull request merged**
