### PR TITLE
[sonic-platform-common] Update submodule

### PR DESCRIPTION
**Pull request by DavidZagury**
Update submodule to include:
ce51894 2021-08-12 [Y-Cable] add the definition inside setup.py to include sonic_y_cable.credo as a package (#211)
cd3cca7 2021-08-06 [Y-Cable][Credo] Credo implementation of YCable class which inherits from YCableBase required for Y-Cable API's in sonic-platform-daemons (#203)
bd694b2 2021-08-03 Load interval from thermal_policy.json (#178)
c43dc17 2021-07-28 [sonic_y_cable] add abstract class YCableBase required for Y-cable API support for multiple vendors (#186)
e168f1d 2021-07-19 [python coverage] fix result color bar (#202)
87c81de 2021-07-13 Fix Xcvrd crash due to invalid key access in type_of_media_interface, host_electrical_interface, connector_dict (#206)
4533f82 2021-06-21 Add a template function that returns list of asics on module (#185)
1e860c5 2021-06-18 Fix decode error when parsing EEPROM fields (#199)
93641f3 2021-06-17 Unifying the platform api for get_pcie_aer_stats with PcieBase (#197)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
@judyjoseph , can you check, this is for 202106 branch.

**Comment by judyjoseph** [comment]
> @judyjoseph , can you check, this is for 202106 branch.

Thanks @lguohan will take in eeprom/xcvr fixes and chassis PR.

**Review by qiluo-msft — APPROVED** [review]

**Comment by judyjoseph** [comment]
@DavidZagury I didn't notice that this was a 202106 branch PR. I had already updated the branch via this commit https://github.com/Azure/sonic-buildimage/commit/c95a9d1db7602101343f53a287d5bdee196e8211
```
93641f3 2021-06-17 Unifying the platform api for get_pcie_aer_stats with PcieBase (#197)
87c81de 2021-07-13 Fix Xcvrd crash due to invalid key access in type_of_media_interface, host_electrical_interface, connector_dict (#206)
bd694b2 2021-08-03 Load interval from thermal_policy.json (#178)
```
If that looks good we could close this PR.

**Comment by DavidZagury** [comment]
> @DavidZagury I didn't notice that this was a 202106 branch PR. I had already updated the branch via this commit https://github.com/Azure/sonic-buildimage/commit/c95a9d1db7602101343f53a287d5bdee196e8211
> ```
> 93641f3 2021-06-17 Unifying the platform api for get_pcie_aer_stats with PcieBase (#197)
> 87c81de 2021-07-13 Fix Xcvrd crash due to invalid key access in type_of_media_interface, host_electrical_interface, connector_dict (#206)
> bd694b2 2021-08-03 Load interval from thermal_policy.json (#178)
> ```
> If that looks good we could close this PR.

@judyjoseph thank you

**Pull request closed without merging**
