### PR TITLE
Do not configure LLDP on recirc ports

### PR DESCRIPTION
**Pull request by ysmanman**
#### Why I did it
Recirc port is used to only forward traffic from one asic to another asic. So it's not required to configure LLDP on it.

#### How I did it
Add interface prefix helper for recirc port. Similar to skip configuring LLDP on inband port,  add check in lldpmgrd to skip recirc port by checking interface prefix.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Comment by ysmanman** [comment]
@vganesan-nokia can you please review this?

**Comment by ysmanman** [comment]
@abdosi can you please review this PR? This PR is similar to https://github.com/Azure/sonic-buildimage/pull/6477, but for recirc port.

**Review by vganesan-nokia — APPROVED** [review]

**Review by arlakshm — APPROVED** [review]
lgtm

**Pull request merged**
