### PR TITLE
Refine SED_DPKG: install dependencies from apt source

### PR DESCRIPTION
**Pull request by qiluo-msft**

### CODE REVIEW

**Comment by marian-pritsak** [comment]
This may cause same problem as before - packages built from sources will be overridden by packages from apt
Why not install dependencies from apt explicitly?

Also apt get install -f does not fail if package failed to install, if always returns 0
We might end up with docker image without some package, as it already happened with libteam before

**Comment by qiluo-msft** [comment]
1. I will follow up with Marian on "packages built from sources will be overridden by packages from apt".
2. I can install dependencies from apt explicitly. I prefer implicit installing by 'apt-get -y install -f' because it is more general, no hard-coded, and keep code DRY.
3. I agree on 'install -f does not fail if package failed to install'. Can you improve it instead of just removing it? It may break others. For example, after https://github.com/Azure/sonic-docker-base/pull/2 committed, several docker images build will be broken.

**Comment by stcheng** [comment]
i vote that it is better to manually install all the dependencies instead of using apt-get -f to install all the 'unknown' dependencies recursively.

**Comment by qiluo-msft** [comment]
Let's keep this pull request and discussion open. I submitted another PR https://github.com/Azure/sonic-buildimage/pull/128 for a quick build fix to unblock all others.

**Comment by lguohan** [comment]
@marian-pritsak , can you explain this "packages built from sources will be overridden by packages from apt" a little bit more? usually, our customized packages have higher version number, so it would not be possible to be override by default package.

**Comment by marian-pritsak** [comment]
As an example, consider a case when only redis-server is installed into docker-database, but we forgot about redis-tools:

```
sudo dpkg -i target/debs/redis-server_3.2.4-1~bpo8+1_amd64.deb || sudo apt-get install -f
Selecting previously unselected package redis-server.
(Reading database ... 104367 files and directories currently installed.)
Preparing to unpack .../redis-server_3.2.4-1~bpo8+1_amd64.deb ...
Unpacking redis-server (3:3.2.4-1~bpo8+1) ...
dpkg: dependency problems prevent configuration of redis-server:
 redis-server depends on redis-tools (= 3:3.2.4-1~bpo8+1); however:
  Package redis-tools is not installed.

dpkg: error processing package redis-server (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (215-17+deb8u5) ...
Processing triggers for man-db (2.7.0.2-5) ...
Errors were encountered while processing:
 redis-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  redis-server
0 upgraded, 0 newly installed, 1 to remove and 2 not upgraded.
1 not fully installed or removed.
After this operation, 1130 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 104374 files and directories currently installed.)
Removing redis-server (3:3.2.4-1~bpo8+1) ...
Processing triggers for man-db (2.7.0.2-5) ...
```

The logs above show us that redis-server depends on redis-tools, and this makes first command fail, but then `apt-get install -f` just silently removes unconfigured package redis-server.

Here we end up in a situation, where build finishes successfully, but required packages are not installed into docker. This mistake will be noticed only when dockers are deployed to switch.

Having said that, I would suggest to catch such mistakes during build with clear error message from dpkg tool instead of debugging missing binaries on switch whenever we can.

Similar issue was fixed in [this PR](https://github.com/Azure/sonic-buildimage/commit/0d10feca1163b663cb87dd0ec23f9cb5091cf9c4)

**Comment by qiluo-msft** [comment]
@marian-pritsak Please check my latest commit which remove your possibility of this kind of mistakes, and keep all the previous features. Do you feel better?

**Comment by stcheng** [comment]
I find the updated change hacky. It is better to install everything that we know and we think are needed instead of relying on -f to auto-solve the dependency issues.

**Comment by lguohan** [comment]
commit 0a0e69c seems hacky, i tend to agree with marian

**Pull request closed without merging**
