### PR TITLE
[sonic-yang]: introduce yang template for cvl yang

### PR DESCRIPTION
**Pull request by lguohan**
…models

python3 setup.py build
python3 setup.py sdist

Signed-off-by: Guohan Lu <lguohan@gmail.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by lguohan** [comment]
related #6861

**Review by anand-kumar-subramanian — CHANGES_REQUESTED** [review]
Yang model type should be CVL and PV(python validator) instead of int and ext.

**Comment by zhangyanzhao** [comment]
> Yang model type should be CVL and PV(python validator) instead of int and ext.

@lguohan  would you please double check this and get the build issue fixed? Thanks

**Review by anand-kumar-subramanian — APPROVED** [review]

**Pull request merged**
