### PR TITLE
[Mellanox] [pmon] Fix for PMON service not starting when restarting SWSS service after fast/warm reboot

### PR DESCRIPTION
**Pull request by shlomibitton**
#### Why I did it

Recent change to delay PMON service in case of fast/warm reboot introduce an issue when restarting only SWSS service after fast/warm reboot for Nvidia platform.
Since the timer is triggered only when the system boot, in a scenario when the system is after a fast/warm reboot and the user restart SWSS service, as part of syncd.sh script, PMON service will stop but the timer will not start again.

#### How I did it

On syncd.sh script, in case of fast/warm indication, check if pmon.timer is running.
If it is running it means we are at the first boot and continue normally.
If it is not running, meaning the service was restarted, start the timer to keep the system behavior consistent.

#### How to verify it

1. Run fast/warm reboot.
2. service swss restart.
3. Observe PMON service starting.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111
- [x] 202205

### CODE REVIEW

**Review by liat-grozovik — DISMISSED** [review]

**Comment by liat-grozovik** [comment]
@shlomibitton could you please checkout the failures?

**Comment by shlomibitton** [comment]
> @shlomibitton could you please checkout the failures?

@liat-grozovik looks like environment issue, I retriggered.

**Comment by shlomibitton** [comment]
@liat-grozovik all checkers are now passing

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
