### PR TITLE
Adding SKU Mellanox-SN3800-D100C12S2

### PR DESCRIPTION
**Pull request by madhanmellanox**
#### Why I did it
To create a new SKU Mellanox-SN3800-D100C12S2

#### How I did it
I arrived at the SKU configuration values based on the following SKU template, Port mapping and number of uplinks and downlinks.

SKU template:
Port configuration
• Breakout mode for each port - Defined in port mapping
• Speed of the port Defined in Port mapping
• Auto-negotiation enable/disable No setting required
• FEC mode No setting required
• Type of transceiver used Not needed
Buffer configuration
• Shared headroom enable
• If shared headroom enabled what is the over-subscription ratio as in SN3800
• Dynamic Buffer disable
• In static buffer scenario how many uplinks and downlinks? as in SN3800
• 2km cable support required? no
Switch configuration
• Warmboot enabled? yes
• Should warmboot be added to SAI profile when enabled? yes
• Is VxLAN source port range set? yes
• Should Vxlan source port range be added to SAI profile when set. as in SN3800
• Is Static Policy Based Hashing enabled? no

Port Mapping
etp1 to etp37 split into 50G
etp38 and etp40 is 10G
etp39 splint into 50G
etp41 to etp52 split into 50G
etp53 to etp64 is 100G

Number of Uplinks / Downlinks:
TO topology: 12 100G uplinks and rest all downlinks.
T1 topology: (SKU will not be used in T1 topology), so same 12 100G uplinks and rest all downlinks is used to arrive at buffer config values.

#### How to verify it
Build the image, install it on the 3800 switch and set the SKU and verify the ports come up with proper speeds.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog

Changes are in sonic-buildimage/device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D100C12S2/ folder.

### CODE REVIEW

**Comment by prsunny** [comment]
Ref PR for 201911 - https://github.com/Azure/sonic-buildimage/pull/7972

**Review by dgsudharsan — DISMISSED** [review]

**Review by prsunny — DISMISSED** [review]

**Comment by lguohan** [comment]
please fix build failure.

**Review by prsunny — APPROVED** [review]

**Comment by dgsudharsan** [comment]
Request for 202106 Branch

**Comment by ayurkiv-nvda** [comment]
SAI_VXLAN_SRCPORT_RANGE_ENABLE=1 line will be reverted due to new implementation  https://github.com/Azure/sonic-buildimage/pull/9956

**Pull request merged**
