### PR TITLE
Build and install redis-dump-load Python 3 package in host image

### PR DESCRIPTION
**Pull request by qiluo-msft**
Fix https://github.com/Azure/sonic-buildimage/issues/4656

Tested these cases with `sonic-mellanox.bin` image
1. `redis-dump` (python2)
2. `python3 /usr/local/bin/redis-dump`
3. `sonic-db-dump` (python2)
4. `python3 /usr/local/bin/sonic-db-dump`

### CODE REVIEW

**Comment by qiluo-msft** [comment]
@dzhangalibaba Please help review

**Comment by qiluo-msft** [comment]
Retest baseimage please

**Comment by qiluo-msft** [comment]
Tested these cases with `sonic-mellanox.bin` image
1. `redis-dump` (python2)
2. `python3 /usr/local/bin/redis-dump`
3. `sonic-db-dump` (python2)
4. `python3 /usr/local/bin/sonic-db-dump`

**Comment by qiluo-msft** [comment]
Retest vsimage please

**Comment by lguohan** [comment]
retest vsimage please

**Pull request merged**
