### PR TITLE
[Mellanox] Add bitmap support for SFP error event

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Depends on https://github.com/Azure/sonic-platform-daemons/pull/184

#### Why I did it

Currently, SONiC use a single value to represent SFP error, however, multiple SFP errors could exist at the same time. This PR is aimed to support it

#### How I did it

Return bitmap instead of single value when a SFP event occurs

#### How to verify it

1. New unit test case is added to cover the change
2. Manual test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Comment by jleveque** [comment]
This is pending on the discussion at https://github.com/stephenxs/SONiC/pull/12, with regard to making this a generic feature, if possible.

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox now that it is not single value how the user is expected to understand the errors? should we add some information in the CLI? we cannot assume users has the code :-)

Please confirm which HLD we should refer in this PR. Is it https://github.com/Azure/SONiC/pull/586 ?

**Comment by Junchao-Mellanox** [comment]
The LGTM warnings are not real issue. It looks like a bug of LGTM.

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox now that it is not single value how the user is expected to understand the errors? should we add some information in the CLI? we cannot assume users has the code :-)
> 
> Please confirm which HLD we should refer in this PR. Is it [Azure/SONiC#586](https://github.com/Azure/SONiC/pull/586) ?

Stephen has updated the HLD, and user could get the error status from CLI.

**Review by keboliu — APPROVED** [review]

**Comment by stephenxs** [comment]
Pending on PR Azure/sonic-platform-common#194 to be merged first.

**Comment by stephenxs** [comment]
@jleveque can you review the PR when you have time? thanks.

**Review by jleveque — APPROVED** [review]
Looks good to me.

https://github.com/Azure/sonic-platform-daemons/pull/184 has merged. Please update the submodule, then we can merge this PR.

**Comment by stephenxs** [comment]
> Looks good to me.
> 
> [Azure/sonic-platform-daemons#184](https://github.com/Azure/sonic-platform-daemons/pull/184) has merged. Please update the submodule, then we can merge this PR.

Thank you. Will do.

**Comment by stephenxs** [comment]
> > Looks good to me.
> > [Azure/sonic-platform-daemons#184](https://github.com/Azure/sonic-platform-daemons/pull/184) has merged. Please update the submodule, then we can merge this PR.
> 
> Thank you. Will do.

advancing submodule PR: Azure/sonic-buildimage#7961

**Pull request merged**
