### PR TITLE
Submodule update for swss

### PR DESCRIPTION
**Pull request by AshokDaparthi**
* a3fdaf4 QOS fieldvalue reference ABNF format to string changes (#1754)
* a8fcadf Add sleep to ensure starting route perf test after the vs is stable (#1929)
* a89d1f8 Fix failing DPB LAG tests (#1919)
* 86b4ede [portsorch] Avoid orchagent crash when set invalid interface types to port (#1906)
* 025032f [VS] Skip failing test - test_recirc_port (#1918)
* d338bd0 [pfcwd] Fix the polling interval time granularity (#1912)
* 14c937e Enabling copp tests (#1914)
* fbdcaae [teammgrd]: Improve LAGs cleanup on shutdown: send SIGTERM directly to PID. (#1841)
* 002bb1d [tlm teamd] Add retry mechanism before logging the ERR in get_dumps. (#1629)
* 57d21e7 [pfcwd] Convert polling interval from ms to us in LUA scripts (#1908)
* d01524d [fgnhgorch] Enable packet flow when no FG ECMP neighbors are resolved (#1900)
* 8cf355d Mux state order change (#1902)

#### Why I did it
Include PR https://github.com/Azure/sonic-swss/pull/1754
#### How I did it
Sub module update for sonic-swss
#### How to verify it
Run build

### CODE REVIEW

**Comment by smaheshm** [comment]
All the commits mention in description section seem old. Can you check once?

**Comment by AshokDaparthi** [comment]
@smaheshm - i see latest sonic-buildimage is pointing to sonic-swss @ db9ca83 [submodule]: retreat sonic-swss submodule (#8732) 17 days ago.                                                                                                                                                                                                        Followed below steps to update submodule.                                                                                                                                               1#cd sonic-buildimage/src/sonic-swss 
git checkout master
2# cd sonic-buildimage
git add src/sonic-swss
3#git push. 

I did git log and got below list and added. 
 git log --graph --decorate --pretty=oneline --abbrev-commit
* a3fdaf4 (HEAD -> master, upstream/master, origin/master, origin/HEAD) QOS fieldvalue reference ABNF format to string changes (#1754)
* a8fcadf Add sleep to ensure starting route perf test after the vs is stable (#1929)
* a89d1f8 Fix failing DPB LAG tests (#1919)
* 86b4ede [portsorch] Avoid orchagent crash when set invalid interface types to port (#1906)
* 025032f [VS] Skip failing test - test_recirc_port (#1918)
* d338bd0 [pfcwd] Fix the polling interval time granularity (#1912)
* 14c937e Enabling copp tests (#1914)
* fbdcaae [teammgrd]: Improve LAGs cleanup on shutdown: send SIGTERM directly to PID. (#1841)
* 002bb1d [tlm teamd] Add retry mechanism before logging the ERR in get_dumps. (#1629)
* 57d21e7 [pfcwd] Convert polling interval from ms to us in LUA scripts (#1908)
* d01524d [fgnhgorch] Enable packet flow when no FG ECMP neighbors are resolved (#1900)
* 8cf355d Mux state order change (#1902)
* 7a0ec8f [Flex-counters] Fix the delay of flex counters flow to prevent infinite loop (#1899)
* 254bc12 WCMP support for MPLS (#1895)
* 447ac71 [portsorch] Add an extra check before setting oper speed to APPL_DB (#1885)
* a8d6246 Update acl type check logic (#1886)
* 62f7200 Update port_rates & rif_rates lua scripts to convert poll_interval to MS (#1855)
* 5643532 [Flex Counters] Delay flex counters even if tables are present in the DB (#1877)
* eb79ca4 [pbh]: Add PBH OA (#1782)
* 3d6b1f0 [buffer orch] Bugfix: Don't query counter SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES on a pool where it is not supported (#1857)
* db9ca83 Fix vs test failure in test_buffer_traditional (#1881)

Let me know if i am missing anything or i need to do only my commit id alone in submodule update?

**Comment by smaheshm** [comment]
> @smaheshm - i see latest sonic-buildimage is pointing to sonic-swss @ db9ca83 [submodule]: retreat sonic-swss submodule (#8732) 17 days ago. Followed below steps to update submodule. 1#cd sonic-buildimage/src/sonic-swss
> git checkout master
> 2# cd sonic-buildimage
> git add src/sonic-swss
> 3#git push.
> 
> I did git log and got below list and added.
> git log --graph --decorate --pretty=oneline --abbrev-commit
> 
> * a3fdaf4 (HEAD -> master, upstream/master, origin/master, origin/HEAD) QOS fieldvalue reference ABNF format to string changes ([[sonic-platform-daemons] Update submodule #1754](https://github.com/Azure/sonic-buildimage/pull/1754))
> * a8fcadf Add sleep to ensure starting route perf test after the vs is stable ([[mellanox]: Update hw-mgmt service with the stop action #1929](https://github.com/Azure/sonic-buildimage/pull/1929))
> * a89d1f8 Fix failing DPB LAG tests ([[socat]: build socat with readline #1919](https://github.com/Azure/sonic-buildimage/pull/1919))
> * 86b4ede [portsorch] Avoid orchagent crash when set invalid interface types to port ([Upgrade azure-keyvault to known compatible version #1906](https://github.com/Azure/sonic-buildimage/pull/1906))
> * 025032f [VS] Skip failing test - test_recirc_port ([[rsyslog]: use # to separate container and program name in syslog msg #1918](https://github.com/Azure/sonic-buildimage/pull/1918))
> * d338bd0 [pfcwd] Fix the polling interval time granularity ([Download newer version (8.23.0-2) of rsyslog from jessie-backports in hopes of eliminating memory leaks #1912](https://github.com/Azure/sonic-buildimage/pull/1912))
> * 14c937e Enabling copp tests ([[Mellanox] Update hw-management service config #1914](https://github.com/Azure/sonic-buildimage/pull/1914))
> * fbdcaae [teammgrd]: Improve LAGs cleanup on shutdown: send SIGTERM directly to PID. ([[docker-syncd-mlnx] add new mlnx-sfpd daemon to docker-syncd-mlnx #1841](https://github.com/Azure/sonic-buildimage/pull/1841))
> * 002bb1d [tlm teamd] Add retry mechanism before logging the ERR in get_dumps. ([[py-swss/config] config load-minigraph failure leaves database in wrong state #1629](https://github.com/Azure/sonic-buildimage/issues/1629))
> * 57d21e7 [pfcwd] Convert polling interval from ms to us in LUA scripts ([[interfaces]: Move IP/MTU information from interfaces file into database #1908](https://github.com/Azure/sonic-buildimage/pull/1908))
> * d01524d [fgnhgorch] Enable packet flow when no FG ECMP neighbors are resolved ([Update arista driver submodule to includes interrupt handling changes #1900](https://github.com/Azure/sonic-buildimage/pull/1900))
> * 8cf355d Mux state order change ([[submodule] update snmpagent and dbsyncd, extending/implementing ieee802.1ab, rfc3433, rfc2737 MIBs #1902](https://github.com/Azure/sonic-buildimage/pull/1902))
> * 7a0ec8f [Flex-counters] Fix the delay of flex counters flow to prevent infinite loop ([[help]Questions about some pull requests #1899](https://github.com/Azure/sonic-buildimage/issues/1899))
> * 254bc12 WCMP support for MPLS ([[submodule] Update submodule: swss-common #1895](https://github.com/Azure/sonic-buildimage/pull/1895))
> * 447ac71 [portsorch] Add an extra check before setting oper speed to APPL_DB ([[submodule] Update submodule: swss-common #1885](https://github.com/Azure/sonic-buildimage/pull/1885))
> * a8d6246 Update acl type check logic ([add new device accton 7116 support for sonic 201803 branch #1886](https://github.com/Azure/sonic-buildimage/pull/1886))
> * 62f7200 Update port_rates & rif_rates lua scripts to convert poll_interval to MS ([[sonic-swss]: Update submodule in 201803 branch #1855](https://github.com/Azure/sonic-buildimage/pull/1855))
> * 5643532 [Flex Counters] Delay flex counters even if tables are present in the DB ([Quagga log will not be able to log to /var/log/quagga #1877](https://github.com/Azure/sonic-buildimage/issues/1877))
> * eb79ca4 [pbh]: Add PBH OA ([Introducing 'debugging' and 'profiling' options in sonic build-infra #1782](https://github.com/Azure/sonic-buildimage/pull/1782))
> * 3d6b1f0 [buffer orch] Bugfix: Don't query counter SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES on a pool where it is not supported ([Update sonic-dbsyncd submodule: Support empty string in lldp_rem_port_desc #1857](https://github.com/Azure/sonic-buildimage/pull/1857))
> * db9ca83 Fix vs test failure in test_buffer_traditional ([[build]: add barefoot master build badge #1881](https://github.com/Azure/sonic-buildimage/pull/1881))
> 
> Let me know if i am missing anything or i need to do only my commit id alone in submodule update?

sorry, your update is correct. Was looking at the wrong field.

**Review by neethajohn — APPROVED** [review]

**Pull request merged**
