### PR TITLE
[DPB] [Mellanox] added capability files for SN2100 platform

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
**- Why I did it**

`platform.json` and `hwsku.json` files are required for a feature called Dynamic Port Breakout

**- How I did it**

Created capability files according to platform specification `SN2100`

**- How to verify it**

Full qualification requires bugs fixes reported under sonic-buildimage

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012

### CODE REVIEW

**Review by liat-grozovik — COMMENTED** [review]
are you missing 50G? i can do split to 2 and still have 50G.
in the default and for non split, why not other speeds are allowed and only 100g and 40g?

**Comment by vadymhlushko-mlnx** [comment]
> are you missing 50G? i can do split to 2 and still have 50G.
> in the default and for non split, why not other speeds are allowed and only 100g and 40g?

About allowed speed: I took as an example [[DPB Seastone] On boarding DPB feature to Seastone HWSKUs](https://github.com/Azure/sonic-buildimage/pull/4235) PR.
Why there is only 100G and 40G allowed - because I suppose that all available lanes should be on. If the port has 4 lanes each lane 25G, and if all 4 lanes will be on, only 2 variants have a sense (100G = 25G + 25G + 25G + 25G) and (40G = 10G + 10G + 10G + 10G)

**Comment by vadymhlushko-mlnx** [comment]
Please don't merge this PR until [[DPB][MLNX][YANG-models] extended regex pattern according to MLNX systems speeds requirements](https://github.com/Azure/sonic-buildimage/pull/6279) PR will be merged

**Comment by vadymhlushko-mlnx** [comment]
retest vs please

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
