### PR TITLE
[device/celestica]:Fix failed test case of Haliburton snmp 

### PR DESCRIPTION
**Pull request by cel-taylor**
#### Why I did it
Fix snmp test case(snmp/test_snmp_phy_entity.py) failed.
#### How I did it
Update the return value of the get_position_in_parent method in psu.py and thermo.py.
#### How to verify it
Rerun test case to verify.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201911
- [ ] 202006
- [x] 202012
- [ ] 202106
- [ ] 201811
- [ ] 202111

### CODE REVIEW

**Review by sujinmkang — APPROVED** [review]

**Comment by Blueve** [comment]
No space left on build machine. Asking help for build team.

**Review by Blueve — APPROVED** [review]

**Pull request merged**
