### PR TITLE
Update AS7312-54X,AS7312-54XS,AS7315-27XB config.bcm file

### PR DESCRIPTION
**Pull request by chihhan123**
Update AS7312-54X,AS7312-54XS,AS7315-27XB config.bcm file to make sure there is no the following error message.

configuration: format error in /usr/share/sonic/hwsku/th-as7312-48x25G+6x100G.config.bcm on line 110 (ignored)#15

### CODE REVIEW

**Comment by chihhan123** [comment]
retest vs

**Comment by chihhan123** [comment]
retest vs please

**Comment by chihhan123** [comment]
retest vsimage please

**Comment by chihhan123** [comment]
retest mellanox please

**Comment by chihhan123** [comment]
retest mellanox please

**Comment by chihhan123** [comment]
retest mellanox please

**Comment by tanpinsiang** [comment]
Hi chihhan123,

I tested this commit but I still get the error:
`sonic INFO syncd#supervisord: syncd Platform configuration: format error in /usr/share/sonic/hwsku/th-as7312-48x25G+6x100G.config.bcm on line 110 (ignored)#015`

I found that this file is not exist in the location:
```
ls -l /usr/share/sonic/hwsku/th-as7312-48x25G+6x100G.config.bcm
ls: cannot access '/usr/share/sonic/hwsku/th-as7312-48x25G+6x100G.config.bcm': No such file or directory
```

The file do exist in the location with the changes:
```
/usr/share/sonic/device/x86_64-accton_as7312_54xs-r0/Accton-AS7312-54XS/th-as7312-48x25G+6x100G.config.bcm

/usr/share/sonic/device/x86_64-kvm_x86_64-r0/Accton-AS7312-54XS/th-as7312-48x25G+6x100G.config.bcm
```

**Comment by chihhan123** [comment]
HI Tan Pin Siang,
          You should find the file /usr/share/sonic/hwsku/th-as7312-48x25G+6x100G.config.bcm
under docker syncd.
          The following command could go to docker syncd environment.
                 docker exec –it syncd bash

Sincerely,
      Chih Han

**Comment by chihhan123** [comment]
Hi Tan Pin Siang,
   please make sure the line 110 in /usr/share/sonic/device/x86_64-accton_as7312_54xs-r0/Accton-AS7312-54XS/th-as7312-48x25G+6x100G.config.bcm is right. 
  #/* Port Map */

Thanks!
Sincerely,
        Chih Han

**Comment by tanpinsiang** [comment]
@chihhan123 The previous error I observed are from the last version. Now the error do not appearing after a few reboot. So this PR does fix the format error.
I checked the config.bcm according to your instruction. The results are normal with the changes:
```
admin@sonic:~$ docker exec -it syncd bash
root@sonic:/# sed -n 110p /usr/share/sonic/hwsku/th-as7312-48x25G+6x100G.config.bcm
#/* Port Map */
root@sonic:/# exit
admin@sonic:~$ sed -n 110p /usr/share/sonic/device/x86_64-accton_as7312_54xs-r0/Accton-AS7312-54XS/th-as7312-48x25G+6x100G.config.bcm
#/* Port Map */
```
I also included the [dump](https://akirakan-my.sharepoint.com/:u:/p/pinsiang_tan/EfaEcd-R3zhHoyXBL4PI0MEBVpV-alvjpdt-mQ43bcvG3w?e=F4jj8b) for your further inspection.

Thanks for your attention on this issue.

**Pull request merged**
