### PR TITLE
[swss-common] Update submodule

### PR DESCRIPTION
**Pull request by shi-su**
#### Why I did it
Update the sonic-swss-common submodule. The following are new commits in the submodule.
```
a18618f [schema] Add vnet route tunnel and advertise network tables for state db (#560)
155770e [VS test] Increase test timeout (#559)
2b11dea [PINS] Update Redis schema to match P4Orch (#548)
be7d483 [schema] add ACL_TABLE_TYPE table (#546)
```

#### How I did it
Update the sonic-swss-common submodule pointer.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by shi-su** [comment]
Closing since the changes are covered by https://github.com/Azure/sonic-buildimage/pull/9322

**Pull request closed without merging**
