### PR TITLE
[Arista] Fix Clearwater2 phy initialization when no configuration is provided

### PR DESCRIPTION
**Pull request by Staphylo**
#### Why I did it

Fix an issue on the Clearwater2 linecard.
When the linecard is started with a fresh image without configuration, phys would not be initialized.

#### How I did it

Added `default_sku` for Clearwater2 which prevents `config-setup` from failing to create a default `config_db.json`.
Added some extra logic in the phy-credo-init script to run the `phy_config.sh` of the hwsku pointed by `default_sku` if the `DEVICE_METADATA.localhost.hwsku` information is not populated in `CONFIG_DB`.

#### How to verify it

Booting an image with this change and without configuration will lead to the phys being initialized using the `phy_config.sh` from `default_sku`.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [x] 202106

Cherry-pick required for the 202106 chassis branch.

#### Description for the changelog

Fix phy initialization on Clearwater2 when booting without configuration

### CODE REVIEW

**Comment by Staphylo** [comment]
@lguohan

**Review by arlakshm — APPROVED** [review]
lgtm

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
