### PR TITLE
[sflow] Fix port_index_mapper.py script; Convert to Python 3

### PR DESCRIPTION
**Pull request by GarrickHe**
**- Why I did it**
A memory issue was discovered during system test for scaling. The issue is documented here.

https://docs.pyroute2.org/ipdb.html

> One of the major issues with IPDB is its memory footprint. It proved not to be suitable for environments with thousands of routes or neighbours. Being a design issue, it could not be fixed, so a new module was started, NDB, that aims to replace IPDB. IPDB is still more feature rich, but NDB is already more fast and stable.

**- How I did it**
- Rewrote the port_index_mapper.py script to use dB events.
- Convert to Python 3

**- How to verify it**
Enabled the sflow container and verified the PORT_INDEX_TABLE was populated properly

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [] 201911
- [ ] 202006

**- Description for the changelog**
* Refactored port-index-mapper script due to memory scaling issue
  of the IPDB library.

Signed-off-by: Garrick He <garrick_he@dell.com>

### CODE REVIEW

**Comment by jleveque** [comment]
@GarrickHe: Thanks for the fixes. I have a [PR](https://github.com/Azure/sonic-buildimage/pull/5791) open to convert this script to Python 3 and use the logger from sonic-py common. However, it seems you are more familiar with this script than I, so you would be able to test it more thoroughly. Would you mind also converting this script to Python 3 and use the logger from sonic-py common in this PR? If so, I will close my other PR.

**Comment by GarrickHe** [comment]
@jleveque - Sure. I'll change it to python 3

**Comment by GarrickHe** [comment]
@jleveque - I changed to python3 but the script is no longer populating the dB. Is there a way I can show you my changes?

**Comment by jleveque** [comment]
@GarrickHe: Are you testing against the latest master HEAD? This PR was merged yesterday. It might be part of your problem?

https://github.com/Azure/sonic-buildimage/pull/5757

If you can confirm missing this commit is not the cause, I guess you could push your new changes to this PR and we can review them.

**Comment by GarrickHe** [comment]
@jleveque - nevermind. looks like python3 got another library to convert ifname to ifindex. I just had to use that one instead.

**Comment by GarrickHe** [comment]
@jleveque - I updated the script and retested. It works and the PORT_INDEX_TABLE in stateDB shows the proper information.

**Comment by jleveque** [comment]
Retest vs please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
@padmanarayana: Please review

**Review by jleveque — APPROVED** [review]

**Pull request merged**
