### PR TITLE
[sairedis] fix incorrect package specified in sairedis rules

### PR DESCRIPTION
**Pull request by stepanblyschak**
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>

#### Why I did it

Fix the build with updated sairedis

#### How I did it
Specify nopython2 for syncd and fixed a copy paste mistake for libsairedis

#### How to verify it

Run build with updated sairedis

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@qiluo-msft , @kcudnik could you please help to review and signoff?

**Review by kcudnik — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by yxieca** [comment]
@stepanblyschak can you create PR for 202205 or suggest dependencies to cherry-pick?

**Comment by stepanblyschak** [comment]
@yxieca I created a seperate PR for 202205 https://github.com/Azure/sonic-buildimage/pull/11308

**Pull request merged**
